objects/Account.object
<CustomObject>
    <fields>
        <fullName>FirmType__c</fullName>
        <description>MARS Firm Type picklist, Data Flow: Mars -&gt; SF</description>
        <label>Firm Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ADU BANK TRUST</fullName>
                </value>
                <value>
                    <fullName>ASSET MGR</fullName>
                </value>
                <value>
                    <fullName>BACK OFFICE</fullName>
                </value>
                <value>
                    <fullName>BANK TRUST B</fullName>
                </value>
                <value>
                    <fullName>BANK TRUST PW</fullName>
                </value>
                <value>
                    <fullName>BROKER DEALER B</fullName>
                </value>
                <value>
                    <fullName>CLEARING</fullName>
                </value>
                <value>
                    <fullName>CONSULTANT</fullName>
                </value>
                <value>
                    <fullName>DCIO</fullName>
                </value>
                <value>
                    <fullName>DC PLATFORM</fullName>
                </value>
                <value>
                    <fullName>DIRECT H</fullName>
                </value>
                <value>
                    <fullName>DIRECT L</fullName>
                </value>
                <value>
                    <fullName>DIRECT N</fullName>
                </value>
                <value>
                    <fullName>DIRECT O</fullName>
                </value>
                <value>
                    <fullName>EDJ</fullName>
                </value>
                <value>
                    <fullName>INDEPENDENT BD A</fullName>
                </value>
                <value>
                    <fullName>INDEPENDENT BD B</fullName>
                </value>
                <value>
                    <fullName>INDEPENDENT BD C</fullName>
                </value>
                <value>
                    <fullName>INSTITUTIONAL A</fullName>
                </value>
                <value>
                    <fullName>INSTITUTIONAL P</fullName>
                </value>
                <value>
                    <fullName>INSTITUTIONAL PW</fullName>
                </value>
                <value>
                    <fullName>INTNL GKA</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>OFFSHORE</fullName>
                </value>
                <value>
                    <fullName>PLAN SPONSOR</fullName>
                </value>
                <value>
                    <fullName>RCDU BANK TRUST</fullName>
                </value>
                <value>
                    <fullName>RCDU BD</fullName>
                </value>
                <value>
                    <fullName>RCDU GKA</fullName>
                </value>
                <value>
                    <fullName>RIA A</fullName>
                </value>
                <value>
                    <fullName>RIA ADU PW</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HomeOfficeId__c</fullName>
        <description>MARS Home Office Id, Data Flow: Mars -&gt; SF</description>
        <label>Home Office Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MarsAccountId__c</fullName>
        <description>The unique Account Identifier for MARS; used in integrations, Data Flow: Mars -&gt; SF</description>
        <externalId>true</externalId>
        <label>MARS Account Id</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>WCMRelationshipFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Maintained by loading firms identified by Data Ops, the data is not integrated. This field is used in formulas at the office and contact level and indicates that the related advisers should not have WCM products discussed with them or related material emailed to them.</description>
        <label>WCM Relationship Flag</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Firm</fullName>
        <active>true</active>
        <description>Firms, offices, and reps are organized into a hierarchy. This means that each rep must be assigned to an office, and each office must be assigned to a firm. Firm is the highest level in the hierarchy.</description>
        <label>Firm</label>
    </recordTypes>
    <recordTypes>
        <fullName>Office</fullName>
        <active>true</active>
        <description>An individual branch location for a firm. Each firm must have a home office, which is the firm's primary location. Additionally, a firm can have multiple branch offices.</description>
        <label>Office</label>
    </recordTypes>
</CustomObject>

objects/WCMRelationshipSyncOverride__mdt.object
<CustomObject>
    <fields>
        <fullName>SFID__c</fullName>
        <description>The SFID of the account or contact that should not have their WCM Relationship Flag inherited from parent.  Use the 18-digit ID.</description>
        <inlineHelpText>The SFID of the account or contact that should not have their WCM Relationship Flag inherited from parent.  Use the 18-digit ID.</inlineHelpText>
        <label>SFID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <description>If an account or contact is in this list, their record will not inherit the WCM Relationship Flag field value from their parent account.</description>
    <label>WCM Relationship Sync Override</label>
    <pluralLabel>WCM Relationship Sync Overrides</pluralLabel>
</CustomObject>

classes/AccountTriggerHandler.cls
public without sharing class AccountTriggerHandler {
    
    public static Id firmRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Firm').getRecordTypeId();
    public static Id officeRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Office').getRecordTypeId();
    
    public static void onAfterInsert(List<Account> newList, Map<Id,Account> newMap) {
        
        List<Account> acctList = newList;
        
        Map<Id,Account> parentMap = getParentMap(acctList);
        addAcctToMARS(acctList);
        setFirmHomeOfficeId(acctList, parentMap);
        
    }
    
    public static void onAfterUpdate(List<Account> newList, Map<Id,Account> newMap, List<Account> oldList, Map<Id,Account> oldMap) {
        
        List<Account> acctList = newList;
        
        Map<Id,Account> parentMap = getParentMap(acctList);
        setFirmHomeOfficeId(acctList, parentMap);
        
    }    
    
    public static void onBeforeInsert(List<Account> newList, Map<Id,Account> newMap) {
        
        List<Account> acctList = newList;
        
        Map<Id,Account> parentMap = getParentMap(acctList);
        acctList = setWCMRelationshipFieldBeforeInsert(acctList, parentMap);
        acctList = setFirmType(acctList, parentMap);
        
    }
    
    public static void onBeforeUpdate(List<Account> newList, Map<Id,Account> newMap, List<Account> oldList, Map<Id,Account> oldMap) {
        
        List<Account> acctList = newList;
        
        Map<Id,Account> parentMap = getParentMap(acctList);
        
        acctList = setWCMRelationshipFieldBeforeUpdate(acctList, oldMap, parentMap);
        acctList = setFirmType(acctList, parentMap);
        
    } 
    
    public static void addAcctToMARS (List<Account> newAccounts) {
        
        for (Account a : newAccounts) {
            if (!test.isRunningTest() && a.MarsAccountId__c == null 
                && (a.RecordTypeId == firmRecTypeId || a.RecordTypeId == officeRecTypeId)) {              
                    AddAccountToMarsWSC.AddAccountMarsById(a.Id);  
                }
        }
        
    }
    
    public static Map<Id,Account> getParentMap(List<Account> newAccounts) {
        
        Set<Id> parentIdSet = new Set<Id>();
        
        for (Account a : newAccounts) {
            parentIdSet.add(a.ParentId);
        }
        
        Map<Id,Account> parentMap = new Map<Id,Account>([SELECT Id, WCMRelationshipFlag__c, FirmType__c
                                                         FROM Account
                                                         WHERE Id IN :parentIdSet]);         
        
        return parentMap;
        
    }
    
    
    public static List<Account> setWCMRelationshipFieldBeforeInsert(List<Account> newAccounts, Map<Id,Account> parentMap) {
        
        Set<Id> wcmOverrideSet = new Set<Id>();
        WCMRelationshipSyncOverride__mdt[] wcmOverrides = [SELECT SFID__c FROM WCMRelationshipSyncOverride__mdt];
        
        for (WCMRelationshipSyncOverride__mdt w : wcmOverrides) {
            wcmOverrideSet.add(w.SFID__c);
        }        
        
        for (Account a : newAccounts) {
        if (parentMap.containsKey(a.ParentId) && !wcmOverrideSet.contains(a.Id)) {
                a.WCMRelationshipFlag__c = parentMap.get(a.ParentId).WCMRelationshipFlag__c;
            }
        }
        
        return newAccounts;
    }
    
    public static List<Account> setWCMRelationshipFieldBeforeUpdate(List<Account> newAccounts, Map<Id,Account> oldMap, Map<Id,Account> parentMap) {
        
        Set<Id> wcmOverrideSet = new Set<Id>();
        WCMRelationshipSyncOverride__mdt[] wcmOverrides = [SELECT SFID__c FROM WCMRelationshipSyncOverride__mdt];
        
        for (WCMRelationshipSyncOverride__mdt w : wcmOverrides) {
            wcmOverrideSet.add(w.SFID__c);
        }        
        
        for (Account a : newAccounts) {
            if (a.ParentId != oldMap.get(a.Id).ParentId) {
            if (parentMap.containsKey(a.ParentId) && !wcmOverrideSet.contains(a.Id)) {
                    a.WCMRelationshipFlag__c = parentMap.get(a.ParentId).WCMRelationshipFlag__c;
                }
            }
        }
        
        return newAccounts;
    }    
    
    public static List<Account> setFirmType(List<Account> newAccounts, Map<Id,Account> parentMap) {
        
        for (Account a : newAccounts) {
            if (parentMap.containsKey(a.ParentId) && a.FirmType__c == null) {
                a.FirmType__c = parentMap.get(a.ParentId).FirmType__c;
            }
        }
        
        return newAccounts;
    }    
    
    public static void setFirmHomeOfficeId(List<Account> newAccounts, Map<Id,Account> parentMap) {
        
        Set<Id> homeIdSet = new Set<Id>();
        
        for (Account a : newAccounts) {
            if (a.Type == 'Home') homeIdSet.add(a.Id);
        }
        
        if (!homeIdSet.isEmpty()) {
            List<Account> accountsToUpdate = new List<Account>();
            
            for (Account a : [SELECT Id, ParentId, Parent.HomeOfficeId__c, MARSAccountId__c, HomeOfficeId__c
                              FROM Account
                              WHERE Id IN :homeIdSet]) {
                                  if (a.Parent.HomeOfficeId__c != a.MarsAccountId__c && a.MarsAccountId__c != null) {
                                      accountsToUpdate.add(new Account(Id = a.ParentId, HomeOfficeId__c = a.MarsAccountId__c));
                                  }
                              }
            
            if (!accountsToUpdate.isEmpty()) {
                update accountsToUpdate;
            }
        }
        
    }
}