objects/Account.object
<CustomObject>
    <fields>
        <fullName>PotentialReason__c</fullName>
        <description>Integrated from EDW and calculated by DIG; used in hover for Key Insights</description>
        <label>Potential Reason</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>RiskReason__c</fullName>
        <description>Integrated from EDW and calculated by DIG; used in hover for Key Insights</description>
        <label>Risk Reason</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/FilteredListColumn__mdt.object
<CustomObject>
    <fields>
        <fullName>ColumnLabel__c</fullName>
        <description>The label that will display in the column header for this column.</description>
        <inlineHelpText>The label that will display in the column header for this column.</inlineHelpText>
        <label>Column Label</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldName__c</fullName>
        <description>The name of the field on the object to display. May not be used by custom lightning components but is required in most cases.</description>
        <inlineHelpText>The name of the field on the object to display. May not be used by custom lightning components but is required in most cases.</inlineHelpText>
        <label>Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Value_Add_Symb__c</fullName>
        <description>Show Additional symbol to each value in column (For exmaple: % or $)</description>
        <inlineHelpText>Show Additional symbol to each value in column (For exmaple: % or $)</inlineHelpText>
        <label>Field Value Add Symb</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FilteredListConfiguration__c</fullName>
        <description>The filtered list to display this column on.</description>
        <inlineHelpText>The filtered list to display this column on.</inlineHelpText>
        <label>Filtered List Configuration</label>
        <referenceTo>FilteredListConfiguration__mdt</referenceTo>
        <relationshipLabel>Filtered List Columns</relationshipLabel>
        <relationshipName>FilteredListColumns</relationshipName>
        <required>true</required>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>IsLink__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this is checked and the field is a lookup it will display in the component as a clickable link that will direct the user to that record.</description>
        <inlineHelpText>If this is checked and the field is a lookup it will display in the component as a clickable link that will direct the user to that record.</inlineHelpText>
        <label>Is Link</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LightningComponentName__c</fullName>
        <description>If this column is controlled by a lightning component add it's name here and it will show up in the column instead of the field.</description>
        <inlineHelpText>If this column is controlled by a lightning component add it's name here and it will show up in the column instead of the field.</inlineHelpText>
        <label>Lightning Component Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LightningComponentParams__c</fullName>
        <label>Lightning Component Params</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ordering__c</fullName>
        <description>Where should this column be? Higher numbers are later in the columns.</description>
        <inlineHelpText>Where should this column be? Higher numbers are later in the columns.</inlineHelpText>
        <label>Ordering</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <description>A configuration record for a filtered list column.</description>
    <label>Filtered List Column</label>
    <pluralLabel>Filtered List Columns</pluralLabel>
</CustomObject>

objects/FilteredListConfiguration__mdt.object
<CustomObject>
    <fields>
        <fullName>ObjectName__c</fullName>
        <description>Name of the SObject that this table displays.</description>
        <inlineHelpText>Name of the SObject that this table displays.</inlineHelpText>
        <label>Object Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <description>A collection of filtered list column records that are used to configure a filtered list.</description>
    <label>Filtered List Configuration</label>
    <pluralLabel>Filtered List Configurations</pluralLabel>
</CustomObject>

objects/FilteredListParam__mdt.object
<CustomObject>
    <fields>
        <fullName>FieldName__c</fullName>
        <label>Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FilterDefaultValue__c</fullName>
        <label>Filter Default Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FilterLabel__c</fullName>
        <label>Filter Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FilterOperation__c</fullName>
        <label>Filter Operation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>equals</fullName>
                    <default>true</default>
                    <label>equals</label>
                </value>
                <value>
                    <fullName>not equal to</fullName>
                </value>
                <value>
                    <fullName>less than</fullName>
                </value>
                <value>
                    <fullName>greater than</fullName>
                </value>
                <value>
                    <fullName>less or equal</fullName>
                </value>
                <value>
                    <fullName>greater or equal</fullName>
                </value>
                <value>
                    <fullName>contains</fullName>
                </value>
                <value>
                    <fullName>does not contain</fullName>
                </value>
                <value>
                    <fullName>starts with</fullName>
                </value>
                <value>
                    <fullName>includes</fullName>
                </value>
                <value>
                    <fullName>excludes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FilteredListConfiguration__c</fullName>
        <label>Filtered List Configuration</label>
        <referenceTo>FilteredListConfiguration__mdt</referenceTo>
        <relationshipLabel>Filtered List Params</relationshipLabel>
        <relationshipName>Filtered_List_Params</relationshipName>
        <required>true</required>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>IsEnableb__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Enableb</label>
        <type>Checkbox</type>
    </fields>
    <description>A configuration filter for a filter list column (right block in main list).</description>
    <label>Filtered List Param</label>
    <pluralLabel>Filtered List Params</pluralLabel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>KeyInsightListViewId__c</fullName>
        <description>Id of this user's private key insight list view.</description>
        <inlineHelpText>Id of this user's private key insight list view.</inlineHelpText>
        <label>Key Insight List View Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/SL_ctrl_ListViewHomePage.cls
/**
*  Test name   :   SL_ctrl_ListViewHomePage
*  Created by  :   Alex Zhurylo
*  Created on  :   7/18/2019
*  Description :   apex class for SL_ListViewHomePage and all inner components
**/
public with sharing class SL_ctrl_ListViewHomePage {
    
    @AuraEnabled
    public static String getListOfColumns(String metadataRecordName){

        FilteredListConfiguration__mdt record = [SELECT id, MasterLabel, ObjectName__c
                                                 FROM FilteredListConfiguration__mdt  
                                                 WHERE Label =: metadataRecordName LIMIT 1];
        
        String objectApiName = record.ObjectName__c;
        String recordId = record.id;

        List<FilteredListColumn__mdt> filterListRecords = [SELECT ColumnLabel__c, FieldName__c, FilteredListConfiguration__c, IsLink__c, 
                                                    LightningComponentName__c, LightningComponentParams__c, Ordering__c, Field_Value_Add_Symb__c 
                                                    FROM FilteredListColumn__mdt WHERE FilteredListConfiguration__c =: recordId];
        
        List<FilteredListParam__mdt> filterListParams = [SELECT FieldName__c, FilterDefaultValue__c, FilteredListConfiguration__c, FilterLabel__c,
                                                        FilterOperation__c, IsEnableb__c FROM FilteredListParam__mdt 
                                                        WHERE FilteredListConfiguration__c =: recordId ];
        RecordsWrapper wrapper = new RecordsWrapper(record, filterListRecords, filterListParams);
        return JSON.serialize(wrapper);
        
    }

    @AuraEnabled
    public static string getAllRecordsThrougthColumns(String objName, String listOfHeaderElements, String numberOfRecords, 
                                                    String defaultOrder,  Boolean isAsc){

// TJB 20190827                                                       
        String strAsc = '';
        if (isAsc) {
            strAsc = ' desc';
        } else {
            strAsc = ' asc';
        } 

        List<String> lstDeserialize = (List<String>)JSON.deserialize(listOfHeaderElements, List<String>.class);
        String elementsToSlect = '';
        for (Integer i = 0; i < lstDeserialize.size(); i++) {
            
            elementsToSlect += lstDeserialize[i] ;

            if(lstDeserialize.size() != i+1){
                elementsToSlect +=  ',';
            }
        }
        //elementsToSlect +=  ' ,PotentialReason__c,RiskReason__c ';
        
// TJB 20190827                                                       
//        String query = 'SELECT ' + elementsToSlect +' FROM ' + objName + ' ORDER By ' + defaultOrder + ' '+ strAsc + ' NULLS LAST  LIMIT 2000' ;
 //       String query = 'SELECT ' + elementsToSlect +' FROM ' + objName + ' ORDER By ' + defaultOrder + ' LIMIT 2000' ;              System.debug('------------query' + query);
        String query = 'SELECT ' + elementsToSlect +' FROM ' + objName + ' ORDER By ' + defaultOrder + ' '+ strAsc + ' NULLS LAST LIMIT ' + numberOfRecords; 
        List<sObject> lstObject = Database.query(query);

                                                        /*List<Id> lstAccountIds = new List<Id>();
        for (Integer i = 0; i < lstObject.size(); i++) {
            lstAccountIds.add((id)lstObject[i].get(taskParam));
        }

        List<Task> lstTasks = [SELECT id, WhatID FROM Task WHERE WhatID IN : lstAccountIds ];*/
        
        /*Map<Id, Integer> mapOfAccountIdAndCountOfTask = new Map<Id, Integer>();
        for (Integer i = 0; i < lstTasks.size(); i++) {
            if(mapOfAccountIdAndCountOfTask.get(lstTasks[i].WhatID) == null){
                mapOfAccountIdAndCountOfTask.put(lstTasks[i].WhatID, 1);
            }else{
                Integer countTasks = mapOfAccountIdAndCountOfTask.get(lstTasks[i].WhatID);
                countTasks++;
                mapOfAccountIdAndCountOfTask.put(lstTasks[i].WhatID, countTasks);
            }
        }*/
        
        List<ListSerachWrapper> lstWrappers = new List<ListSerachWrapper>();
        
        for (Integer i = 0; i < lstObject.size(); i++) {
            //Integer countTasks = mapOfAccountIdAndCountOfTask.get((Id)lstObject[i].get(taskParam));
            lstWrappers.add(new ListSerachWrapper(lstObject[i]));//, countTasks)); 
        }
        
        return JSON.serialize(lstWrappers);
    }

    @AuraEnabled
    public static String createTaskRecords(List<String> listOfTaskId){
        
        List<Task> lstTasks = new List<Task>();
        for (Integer i = 0; i < listOfTaskId.size(); i++) {
            lstTasks.add(new Task(WhatId = listOfTaskId[i], WhoId = null, OwnerId = UserInfo.getUserId(), ActivityDate = Date.today(), 
                                  ActivityType__c = 'Research', Priority = 'Normal', Status = 'Open', 
                                  Subject='Follow Up Call - Key Insights', ActivitySubType__c = 'Research'));
        }

        try{
            insert lstTasks;
            return 'SUCCESS';
        }catch(Exception e){
            return 'Error ' + e;
        }
        
    }

    @AuraEnabled
    public static String getUserKeyInsightsUrl(){
        User userToGetUrlFor = [SELECT KeyInsightListViewId__c FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];
        return '/lightning/o/Account/list?filterName=' + userToGetUrlFor.KeyInsightListViewId__c;
    }

    public class ListSerachWrapper {
        sObject objectRecord {get; set;}
        //Integer countOfTask {get;set;}
   
        public ListSerachWrapper(sObject objectRecord) {  
            this.objectRecord = objectRecord;   
        }
	}

    public class RecordsWrapper {
        public FilteredListConfiguration__mdt record {get; set;}
		public List<FilteredListColumn__mdt> filterListRecords {get; set;}
        public List<FilteredListParam__mdt> filterListParams {get;set;}

        public RecordsWrapper(FilteredListConfiguration__mdt record, List<FilteredListColumn__mdt> filterListRecords, List<FilteredListParam__mdt> filterListParams) {  
            this.record = record;   
            this.filterListRecords = filterListRecords;
            this.filterListParams = filterListParams;
        }
    }

    private ApexPages.StandardController stdCtrl {get; set;}
    
    public List<sObject> Records {get; set;}
    public list<string> recordIds {get; set;}
    
    
    public SL_ctrl_ListViewHomePage(ApexPages.StandardController std){
        this.stdCtrl = std;
    }
    
    public SL_ctrl_ListViewHomePage(ApexPages.StandardSetController controller) {
        
        Records = controller.getSelected();
        
        recordIds = new list<string>();
        
        for (sObject r : Records){
            recordIds.add(r.Id);
        }   
		     
	}
    
    public PageReference Redirect() {
        
        PageReference newRef = null;
        User UserRec = [select ID,KeyInsightListViewId__c from User where ID=:UserInfo.getUserId() limit 1];

        if(String.isBlank(UserRec.KeyInsightListViewId__c)){
            newRef = new PageReference('/lightning/o/Account/list');
        }
        else {
            newRef = new PageReference('/lightning/o/Account/list?filterName='+UserRec.KeyInsightListViewId__c);
        }
        newRef.setRedirect(true);
        if(recordIds.size() > 0){
            createTaskRecords(recordIds);
        }
       
        return newRef;
        
    }
}