objects/Account.object
<CustomObject>
    <fields>
        <fullName>WCMRelationshipFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Maintained by loading firms identified by Data Ops, the data is not integrated. This field is used in formulas at the office and contact level and indicates that the related advisers should not have WCM products discussed with them or related material emailed to them.</description>
        <label>WCM Relationship Flag</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/WCMRelationshipSyncOverride__mdt.object
<CustomObject>
    <fields>
        <fullName>SFID__c</fullName>
        <description>The SFID of the account or contact that should not have their WCM Relationship Flag inherited from parent.  Use the 18-digit ID.</description>
        <inlineHelpText>The SFID of the account or contact that should not have their WCM Relationship Flag inherited from parent.  Use the 18-digit ID.</inlineHelpText>
        <label>SFID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <description>If an account or contact is in this list, their record will not inherit the WCM Relationship Flag field value from their parent account.</description>
    <label>WCM Relationship Sync Override</label>
    <pluralLabel>WCM Relationship Sync Overrides</pluralLabel>
</CustomObject>

classes/WCMRelationshipAccountSyncBatch.cls
global class WCMRelationshipAccountSyncBatch implements Database.batchable<sObject>, Database.stateful {
    
    global Map<Id,Boolean> parentWCMMap0 = new Map<Id,Boolean>();
    
    public String query = ' SELECT Id, Type, ParentId, Parent.ParentId, Parent.Parent.ParentId, Parent.Parent.Parent.ParentId, ' +
        ' WCMRelationshipFlag__c ' +
        ' FROM Account ' +
        ' ORDER BY ParentId, Parent.ParentId, Parent.Parent.ParentId, Parent.Parent.Parent.ParentId ';
    
    global Database.querylocator start(Database.BatchableContext BC){   
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Account> scope) {
        
        Set<Id> wcmOverrideSet = new Set<Id>();
        WCMRelationshipSyncOverride__mdt[] wcmOverrides = [SELECT SFID__c FROM WCMRelationshipSyncOverride__mdt];
        
        for (WCMRelationshipSyncOverride__mdt w : wcmOverrides) {
            wcmOverrideSet.add(w.SFID__c);
        }    
        
        List<Account> wcmOverrideAcctList = [SELECT Id, WCMRelationshipFlag__c
                                             FROM Account
                                             WHERE Id IN :wcmOverrideSet];
        
        for (Account a : wcmOverrideAcctList) {
            parentWCMMap0.put(a.Id,a.WCMRelationshipFlag__c); 
        }
        
        List<Account> acctsToUpdate = new List<Account>();
        
        for (Account a : [SELECT Id, WCMRelationshipFlag__c
                          FROM Account
                          WHERE ParentId = null]) {
                              parentWCMMap0.put(a.Id,a.WCMRelationshipFlag__c);
                          }
        
        for (Account a : scope) {
            
            if (parentWCMMap0.containsKey(a.ParentId)) {
                if (a.WCMRelationshipFlag__c != parentWCMMap0.get(a.ParentId)) {
                    if (!wcmOverrideSet.contains(a.Id)) {
                        a.WCMRelationshipFlag__c = parentWCMMap0.get(a.ParentId);
                        acctsToUpdate.add(a);
                    }
                }
            } else {
                
                if (parentWCMMap0.containsKey(a.Parent.ParentId)) {
                    if (a.WCMRelationshipFlag__c != parentWCMMap0.get(a.Parent.ParentId)) {
                        if (!wcmOverrideSet.contains(a.Id)) {
                            a.WCMRelationshipFlag__c = parentWCMMap0.get(a.Parent.ParentId);
                            acctsToUpdate.add(a);
                        }
                    }
                } else {
                    
                    if (parentWCMMap0.containsKey(a.Parent.Parent.ParentId)) {
                        if (a.WCMRelationshipFlag__c != parentWCMMap0.get(a.Parent.Parent.ParentId)) {
                            if (!wcmOverrideSet.contains(a.Id)) {
                                a.WCMRelationshipFlag__c = parentWCMMap0.get(a.Parent.Parent.ParentId);
                                acctsToUpdate.add(a);
                            }
                        }
                    } else {
                        
                        if (parentWCMMap0.containsKey(a.Parent.Parent.Parent.ParentId)) {
                            if (a.WCMRelationshipFlag__c != parentWCMMap0.get(a.Parent.Parent.Parent.ParentId)) {
                                if (!wcmOverrideSet.contains(a.Id)) {
                                    a.WCMRelationshipFlag__c = parentWCMMap0.get(a.Parent.Parent.Parent.ParentId);
                                    acctsToUpdate.add(a);
                                }
                            }
                        }
                    }
                }
            }
            
        }
        
        if (!acctsToUpdate.isEmpty()) update acctsToUpdate;
        
    }     
    
    global void finish(Database.BatchableContext BC) {
        
        if (!test.isRunningTest()) {
            Id batchJobId = Database.executeBatch(new WCMRelationshipContactSyncBatch(),10000);
        }
        
    }
    
    
}