objects/Account.object
<CustomObject>
    <fields>
        <fullName>MarsAccountId__c</fullName>
        <description>The unique Account Identifier for MARS; used in integrations, Data Flow: Mars -&gt; SF</description>
        <externalId>true</externalId>
        <label>MARS Account Id</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AccountTerritory__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Territories</relationshipLabel>
        <relationshipName>Account_Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GroupId__c</fullName>
        <formula>Territory__r.GroupId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GroupId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MarsAccountId__c</fullName>
        <formula>Account__r.MarsAccountId__c</formula>
        <label>Mars Account Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RoleId__c</fullName>
        <formula>Territory__r.RoleId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Role Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Territory__c.RoleId__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Account Territories</relationshipLabel>
        <relationshipName>Account_Territories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <description>Stores the Account Territory assignment records. 
These records are used to drive the AccountShare table and provide visibility to corresponding Roles in the Role Hierarchy.</description>
    <label>Account Territory</label>
    <nameField>
        <displayFormat>AT-{0000000000}</displayFormat>
        <label>Account Territory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Territories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>GroupId__c</fullName>
        <externalId>true</externalId>
        <label>Group Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RoleGroupId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Role Group Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RoleId__c</fullName>
        <externalId>true</externalId>
        <label>Role Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TerritoryName__c</fullName>
        <defaultValue>"Update Me"</defaultValue>
        <externalId>true</externalId>
        <label>MARS Territory Name</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/AccountTerritoryTriggerHandler_Test.cls
@isTest
private class AccountTerritoryTriggerHandler_Test {
        /*
    static testMethod void deleteAccountShareTest() {

       Account a = new Account(MarsAccountId__c = 'OF123456', Name = 'TestAccount');
       insert a;
       system.debug('a.id: ' + a.Id);
       List<Territory__c> tl = new List<Territory__c>();
       for(Integer i=0; i< 3; i++) {
              Territory__c t = new Territory__c(TerritoryName__c = 'WHSE TERR' + i);
              insert t;
              system.debug('t.id: ' + t.Id);
              UserRole role = new UserRole(Name = t.TerritoryName__c, CaseAccessForAccountOwner = 'None',
                   ContactAccessForAccountOwner = 'None',OpportunityAccessForAccountOwner = 'None',DeveloperName = t.Id);
               insert role;
               Group g = new Group(Name = t.TerritoryName__c, DeveloperName = t.id);
               insert g;
              
              List<Group> grps = [select Id from Group where RelatedId =: role.Id and Type =: 'Role']; 
//            if(grsp.size() <= 0) throw new exception('No role group');
              t.GroupId__c = g.Id;
              t.RoleId__c = role.Id;
              t.RoleGroupId__c = grps[0].Id;
              update t;
              System.debug(t.Id + ' - ' + t.TerritoryName__c + ' - ' + t.GroupId__c + ' - ' + t.RoleId__c + ' - ' + t.RoleGroupId__c);
              tl.add(t);
       }
       List<AccountTerritory__c> atl = new List<AccountTerritory__c>();
       List<AccountShare> asl = new List<AccountShare>();
       for(Integer i=0; i<tl.size(); i++) { 
              Territory__c t = tl[i];           
              AccountTerritory__c atc = new AccountTerritory__c(Account__c = a.Id, Territory__c = t.Id);
              atl.add(atc);
              AccountShare ashare = new AccountShare(AccountId = a.Id, 
                                                       AccountAccessLevel = 'Edit',
                                                              OpportunityAccessLevel = 'Edit',
                                                ContactAccessLevel = 'None',
                                                UserOrGroupId = t.RoleGroupId__c);
              asl.add(ashare);
              ashare = new AccountShare(AccountId = a.Id, 
                                                       AccountAccessLevel = 'Edit',
                                                              OpportunityAccessLevel = 'Edit',
                                                ContactAccessLevel = 'None',
                                                UserOrGroupId = t.GroupId__c);
              asl.add(ashare);
       }
       insert atl;
       insert asl;
       AccountTerritory__c[] ata = [select Id, Account__c from AccountTerritory__c where Account__r.MarsAccountId__c =: 'OF123456'];            
       Set<Id> ids = new Set<Id>();
       for(AccountTerritory__c a1 : ata) ids.add(a1.Account__c);
        delete ata;
        
        AccountShare[] asl1 = [select Id from AccountShare where AccountId in :ids and RowCause = 'Manual'];
        System.assertEquals(0, asl1.size());
    }*/
}