objects/AccountTerritory__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Territories</relationshipLabel>
        <relationshipName>Account_Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GroupId__c</fullName>
        <formula>Territory__r.GroupId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GroupId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RoleId__c</fullName>
        <formula>Territory__r.RoleId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Role Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Territory__c.RoleId__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Account Territories</relationshipLabel>
        <relationshipName>Account_Territories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <description>Stores the Account Territory assignment records. 
These records are used to drive the AccountShare table and provide visibility to corresponding Roles in the Role Hierarchy.</description>
    <label>Account Territory</label>
    <nameField>
        <displayFormat>AT-{0000000000}</displayFormat>
        <label>Account Territory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Territories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>GroupId__c</fullName>
        <externalId>true</externalId>
        <label>Group Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RoleGroupId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Role Group Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RoleId__c</fullName>
        <externalId>true</externalId>
        <label>Role Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/AccountShareWS.cls
@RestResource(urlMapping='/AccountTerritoryShare/*')
global with sharing class AccountShareWS {

    @HttpPost
    global static List<id> ComputeSharing(DateTime LastTime) {  
        //String pLastTime = RestContext.request.params.get('pLastTime');
        //DateTime LastTime = Datetime.valueOf(pLastTime); 
        List<id> JobIds = new List<id>();

    	AccountShareBatch ASI = new AccountShareBatch();
        ASI.query = 'select Account__c, Territory__r.RoleGroupId__c, RoleId__c, GroupId__c from AccountTerritory__c WHERE CreatedDate >'+LastTime.format('yyyy-MM-dd')+'T'+ LastTime.format('HH:mm')+':00.000Z';
    	ID ASIid = database.executeBatch(ASI,2000);  
        JobIds.add(ASIid );
        return JobIds ;
    }
    
}