objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Affiliate</fullName>
        <active>true</active>
        <label>Affiliate</label>
    </recordTypes>
</CustomObject>

objects/ActivityContact__c.object
<CustomObject>
    <fields>
        <fullName>ActivityContact__c</fullName>
        <description>This Field is populated by the trigger and contains ActivityId__c + Contact__c, it is used to ensure that no duplicate contact on an activity (does not allow duplicate)</description>
        <label>ActivityContact</label>
        <length>37</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ActivityId__c</fullName>
        <description>This fake Id field is binded to Task through the use of the "Contacts" Grid build in the GridBuddy application. It is populated by GB with Task.Id</description>
        <externalId>true</externalId>
        <label>ActivityId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is entered through the Gridbuddy Form and is set to the id of the contact entered through the form. It is used by the trigger to create the TaskRelation entry to the related Task</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Activity Contacts</relationshipLabel>
        <relationshipName>ActivityContacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <description>Each activity will have 1 to Many contacts. These activity related contacts are stored in this object along necessary attributes to allow for advanced activity reporting. This Table is synched up with the TaskRelation standard object through the "ActivityContactTrigger" trigger and the "ActivityContactTriggerHandler" Class.
This object is "virtually" related to Task through the use of the "ActivityId__c" field. This fake Id field is binded to Task through the use of the "Contacts" Grid build in the GridBuddy application.</description>
    <label>Activity Contact</label>
    <nameField>
        <displayFormat>AC-{0000000000}</displayFormat>
        <label>Activity Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Contacts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Artemus.Request.requestor_id
varchar(100)</description>
        <label>Requester</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Requestor</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel><enableHistory>true</enableHistory>
</CustomObject>

objects/Contact.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Affiliate</fullName>
        <active>true</active>
        <label>Affiliate</label>
    </recordTypes>
</CustomObject>

objects/NGAMSettings__c.object
<CustomObject>
    <fields>
        <fullName>ProfileSystemAdministrator__c</fullName>
        <description>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</description>
        <inlineHelpText>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</inlineHelpText>
        <label>Profile: System Administrator</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Holds the NGAM settings</description>
    <label>NGAM Settings</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>UserID__c</fullName>
        <defaultValue>"Populate This Field"</defaultValue>
        <externalId>true</externalId>
        <label>UserID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EventTriggerHandlerTest.cls
@isTest 
public class EventTriggerHandlerTest { 
    
    @testSetup
    static void setup() {
        
        DataFactory.CreateNGAMCustomSettings(); 
        Account acc = new Account(); 
        acc.Name = 'Test'; 
        acc.type = 'Affiliate'; 
        insert acc; 
        
    }
    
    static testMethod void myTest() { 
        Id affiliateEventRecTypeId = Schema.SObjectType.Event.getRecordTypeInfosByName().get('Affiliate Event').getRecordTypeId(); 
        Id affiliateCaseRecTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Affiliate Request').getRecordTypeId(); 
        
        List<Account> myAccounts = DataFactory.createTestAccounts(1);
        myAccounts[0].Name = 'Test'; 
        myAccounts[0].Type = 'Affiliate'; 
        insert myAccounts;
        
        List<Contact> myContacts = DataFactory.createTestContacts(2, myAccounts, false) ;
        insert myContacts; 
        
        
        
        
        //Profile pf = [select id from profile where name='System Administrator']; 
        
        NGAMSettings__c ngamSettings = [select id,ProfileSystemAdministrator__c from NGAMSettings__c limit 1]; 
        string pf = Util.getCustomSettingProfileId(ngamSettings.ProfileSystemAdministrator__c); 
        
        User u = new User(alias = 'standt', email='SFDCadmin@natixis.com', 
                          emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
                          localesidkey='en_US', profileid = pf, 
                          timezonesidkey='America/Los_Angeles', username='SFDCadmin@natixis.com',UserID__c='SFDCadmin'); 
        System.runAs(u) {     
            
            User u0 = new User(alias = 's0', email='Sales0@ngam.natixis.com', 
                               emailencodingkey='UTF-8', lastname='Testing0', languagelocalekey='en_US', 
                               localesidkey='en_US', profileid = pf, 
                               timezonesidkey='America/Los_Angeles', username='Sales0@ngam.natixis.com',UserID__c='Sales0');             
            insert u0; 
            
            DateTime myDateTime = datetime.now(); 
            
            Test.startTest(); 
            
            Case c1 = new Case(ownerid= u0.id,
                               recordtypeid =affiliateCaseRecTypeId, 
                               Requestor__c = u0.id, 
                               AccountId = myAccounts[0].Id) ;             
            insert c1; 
            
            Event e00 = new Event(WhatId=c1.Id,ShortSubject__c='Test1',
                                  Type='Call',
                                  WhoId = myContacts[0].Id,
                                  StartDateTime=myDateTime,
                                  EndDateTime=myDateTime.addMinutes(30)); 
            insert e00; 
            
            Event e02 = New Event(WhatId=c1.Id,
                                  ShortSubject__c='Test2',
                                  Type='Meeting',
                                  WhoId = myContacts[0].Id,
                                  StartDateTime=myDateTime.addMinutes(10),
                                  EndDateTime=myDateTime.addMinutes(30)); 
            insert e02;    
            
            Event e01 = New Event(WhatId=c1.Id,
                                  ShortSubject__c='Test3', 
                                  Type='Onsite',
                                  WhoId = myContacts[0].Id,
                                  StartDateTime=myDateTime.addMinutes(5), 
                                  EndDateTime=myDateTime.addMinutes(30));             
            insert e01; 
            
            List<ActivityContact__c> myACs = new List<ActivityContact__c>();
            myACs.add(new ActivityContact__c(ActivityId__c = (String)e00.Id, Contact__c = myContacts[0].Id));
            myACs.add(new ActivityContact__c(ActivityId__c = (String)e00.Id, Contact__c = myContacts[1].Id));
            myACs.add(new ActivityContact__c(ActivityId__c = (String)e02.Id, Contact__c = myContacts[0].Id));
            myACs.add(new ActivityContact__c(ActivityId__c = (String)e02.Id, Contact__c = myContacts[1].Id));
            myACs.add(new ActivityContact__c(ActivityId__c = (String)e01.Id, Contact__c = myContacts[0].Id));
            myACs.add(new ActivityContact__c(ActivityId__c = (String)e01.Id, Contact__c = myContacts[1].Id));
            insert myACs;
            
            //AfterUpdate 
            e01.StartDateTime = myDateTime.addMinutes(15); 
            update e01;
            delete e01;
                          
            Test.stopTest(); 
        } 
    } 
}