objects/Account.object
<CustomObject>
    <fields>
        <fullName>MarsAccountId__c</fullName>
        <description>The unique Account Identifier for MARS; used in integrations, Data Flow: Mars -&gt; SF</description>
        <externalId>true</externalId>
        <label>MARS Account Id</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TranPYPurchases__c</fullName>
        <description>Mars Integration field, Data Flow: Mars -&gt; SF</description>
        <label>PY Purchases</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TranYTDPurchases__c</fullName>
        <description>Mars Integration field, Data Flow: Mars -&gt; SF</description>
        <inlineHelpText>Natixis YTD Purchases</inlineHelpText>
        <label>YTD Purchases</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>MarsRepId__c</fullName>
        <description>Source: MARS na_load_rep.Id
Loaded by a nightly job. Unique identifier for MARS. Data Flow: Mars -&gt; SF</description>
        <externalId>true</externalId>
        <label>MARS Rep Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TranPYPurchases__c</fullName>
        <description>Mars Integration field. Data Flow: Mars -&gt; SF. Prior Year Purchases.</description>
        <label>PY Purchases</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TranYTDPurchases__c</fullName>
        <description>Mars Integration field. Data Flow: Mars -&gt; SF</description>
        <label>YTD Purchases</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Team</fullName>
        <active>true</active>
        <label>Team</label>
    </recordTypes>
</CustomObject>

objects/NGAMSettings__c.object
<CustomObject>
    <fields>
        <fullName>ProfileSystemAdministrator__c</fullName>
        <description>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</description>
        <inlineHelpText>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</inlineHelpText>
        <label>Profile: System Administrator</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Holds the NGAM settings</description>
    <label>NGAM Settings</label>
</CustomObject>

objects/NGAMSettingsHierarchy__c.object
<CustomObject>
    <fields>
        <fullName>ByPassAccountValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows entity to by-pass validation rules on Account</description>
        <inlineHelpText>Allows entity to by-pass validation rules on Account</inlineHelpText>
        <label>By-Pass Account Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NGAM Settings - Hierarchy</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>UserID__c</fullName>
        <defaultValue>"Populate This Field"</defaultValue>
        <externalId>true</externalId>
        <label>UserID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/RelationshipTriggerHandler_Test.cls
@isTest
private class RelationshipTriggerHandler_Test {

    static testMethod void RelationshipTriggerHandlerInsert() {
    
        NGAMSettingsHierarchy__c hsettings = NGAMSettingsHierarchy__c.getOrgDefaults();
        hsettings.ByPassAccountValidationRules__c  = TRUE;
        upsert hsettings NGAMSettingsHierarchy__c.Id;

       // Profile p = [select id from profile where name='System Administrator']; 
        DataFactory.CreateNGAMCustomSettings(); 
        NGAMSettings__c ngamSettings = [select id,ProfileSystemAdministrator__c from NGAMSettings__c limit 1]; 
        string p = Util.getCustomSettingProfileId(ngamSettings.ProfileSystemAdministrator__c);
        
        User u = new User(alias = 'standt', email='SFDCadmin@ngam.natixis.com', 
                          emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
                          localesidkey='en_US', profileid = p, 
                          timezonesidkey='America/Los_Angeles', username='SFDCadmin@ngam.natixis.com',UserID__c='SFDCadmin');
                          
        System.runAs(u) {
            Account f = new account(MarsAccountId__c = '12', Name='test1');
            insert f;
            
            Account a = new account(MarsAccountId__c = '11', Name='test', Parent = f);
            insert a;
            
            // create test contacts
            contact ct = new contact(MarsRepID__c = '1111', FirstName = 'user1', LastName = 'test1', TranYTDPurchases__c = 100.0, TranPYPurchases__c = 200.0, Account = a,AccountId=a.Id);
            ct.RecordType = new RecordType( Name='Team' );
            insert ct;
            
            contact c = new contact(MarsRepID__c = '2222', FirstName = 'user', LastName = 'test', TranYTDPurchases__c = 10.0, TranPYPurchases__c = 50.0, Account = a,AccountId=a.Id);
            c.RecordType = new RecordType( Name='Rep/Contact' );
            insert c;
                        
            // create test relationships
            List<npe4__Relationship__c> rs = new List<npe4__Relationship__c>();
            npe4__Relationship__c r = new npe4__Relationship__c();
            r.TeamRepId__c='1';
            r.npe4__Type__c = 'Team Individual';
            r.npe4__Contact__r = new contact(MarsRepId__c = ct.MarsRepId__c);
            r.npe4__RelatedContact__r = new contact(MarsRepId__c = c.MarsRepId__c);
            rs.add(r);   
            insert rs;  
            
            npe4__Relationship__c rl = [Select Id,  ContactYTDPurchases__c from npe4__Relationship__c where teamrepId__c = '1' limit 1];
            system.assert(ct.TranYTDPurchases__c == rl.ContactYTDPurchases__c, 'successfull');        
        }   
    }    
}