objects/Account.object
<CustomObject>
    <fields>
        <fullName>CRDID__c</fullName>
        <description>Account's CDR ID, Data Flow: Mars -&gt; SF</description>
        <externalId>true</externalId>
        <label>CRD ID#</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MarsAccountId__c</fullName>
        <description>The unique Account Identifier for MARS; used in integrations, Data Flow: Mars -&gt; SF</description>
        <externalId>true</externalId>
        <label>MARS Account Id</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CRDID__c</fullName>
        <description>Source: MARS na_load_rep.CrdId
Loaded by a nightly job. Data Flow: Mars -&gt; SF</description>
        <label>CRD ID#</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MarsRepId__c</fullName>
        <description>Source: MARS na_load_rep.Id
Loaded by a nightly job. Unique identifier for MARS. Data Flow: Mars -&gt; SF</description>
        <externalId>true</externalId>
        <label>MARS Rep Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RepContactType__c</fullName>
        <description>Source: MARS RecordType</description>
        <label>Rep/Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Control Group</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>House Rep</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Rep</fullName>
                </value>
                <value>
                    <fullName>Rep/Staff</fullName>
                </value>
                <value>
                    <fullName>Staff</fullName>
                </value>
                <value>
                    <fullName>Team</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <description>URL associated to a contact if they have a web profile etc.</description>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Team</fullName>
        <active>true</active>
        <label>Team</label>
    </recordTypes>
</CustomObject>

objects/ContactWebProfile__c.object
<CustomObject>
    <fields>
        <fullName>CRDId__c</fullName>
        <description>CRD Id as entered by the contact via the website</description>
        <inlineHelpText>CRD Id as entered by the contact via the website</inlineHelpText>
        <label>CRD Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CompanyName__c</fullName>
        <description>Company Name as entered by the contact via the website</description>
        <inlineHelpText>Company Name as entered by the contact via the website</inlineHelpText>
        <label>Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContactIdCookieValue__c</fullName>
        <label>ContactIdCookieValue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>Contact for this Contact Web Profile</description>
        <inlineHelpText>Contact for this Contact Web Profile</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Web Profiles</relationshipLabel>
        <relationshipName>ContactWebProfiles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email as entered by the contact via the website</description>
        <inlineHelpText>Email as entered by the contact via the website</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <description>First Name as entered by the contact via the website</description>
        <inlineHelpText>First Name as entered by the contact via the website</inlineHelpText>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <description>Last Name as entered by the contact via the website</description>
        <inlineHelpText>Last Name as entered by the contact via the website</inlineHelpText>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NotApproved__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The contact is not approved to access protected content via the website</description>
        <inlineHelpText>The contact is not approved to access protected content via the website</inlineHelpText>
        <label>Not Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Phone as entered by the contact via the website</description>
        <inlineHelpText>Phone as entered by the contact via the website</inlineHelpText>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>RegistrationSource__c</fullName>
        <description>The initial source Contact Web Profile data when the person first signed up for access to website exclusive content (i.e., LinkedIn vs Website)</description>
        <inlineHelpText>The initial source Contact Web Profile data when the person first signed up for access to website exclusive content (i.e., LinkedIn vs Website)</inlineHelpText>
        <label>Registration Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>State as entered by the contact via the website</description>
        <inlineHelpText>State as entered by the contact via the website</inlineHelpText>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Verified__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the contact has verified their email address</description>
        <inlineHelpText>Indicates if the contact has verified their email address</inlineHelpText>
        <label>Verified</label>
        <type>Checkbox</type>
    </fields>
    <description>Stores information collected by the Natixis website for access to FA exclusive content</description>
    <label>Contact Web Profile</label>
    <nameField>
        <displayFormat>CWP-{000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Web Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PortalActivity__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <description>Artemus.dbo.Portal_Audit_Log(500)</description>
        <inlineHelpText>Tracks the action/event for this Portal Activity record.</inlineHelpText>
        <label>Action</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contact related to this Portal Activity.  If this value is blank, the contact has been deleted from the system.</description>
        <inlineHelpText>The contact related to this Portal Activity.  If this value is blank, the contact has been deleted from the system.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Portal Activities</relationshipLabel>
        <relationshipName>Portal_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the Portal Activity.  Contains supporting or additional information related to the activity.</description>
        <inlineHelpText>Description of the Portal Activity.  Contains supporting or additional information related to the activity.</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EventTime__c</fullName>
        <description>Artemus.dbo.Portal_audit_log.event_time(datetime)</description>
        <inlineHelpText>Time the Portal Activity event occurred</inlineHelpText>
        <label>Event Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LoginMethod__c</fullName>
        <description>Tracks how user authenticated (i.e., via website or LinkedIn)</description>
        <inlineHelpText>Tracks how user authenticated (i.e., via website or LinkedIn)</inlineHelpText>
        <label>Login Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RepId__c</fullName>
        <description>An additional Id of the contact to which this Portal Activity belongs (i.e., email, MARS Id, etc.)</description>
        <inlineHelpText>An additional Id of the contact to which this Portal Activity belongs (i.e., email, MARS Id, etc.)</inlineHelpText>
        <label>Rep Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <inlineHelpText>The Source of this Portal Activity</inlineHelpText>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PRCG Advisor Portal</fullName>
                </value>
                <value>
                    <fullName>NGAM Website</fullName>
                </value>
                <value>
                    <fullName>Fugent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Url__c</fullName>
        <description>artemus.dbo.portal_audit_log.url(200)</description>
        <inlineHelpText>The detailed URL (page) from which the activity originates.</inlineHelpText>
        <label>Url</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <description>Tracks important web and portal activities.  Records created systematically by Apex/Web Services when events occur.</description>
    <label>Portal Activity</label>
    <nameField>
        <displayFormat>PA-{0000000000}</displayFormat>
        <label>Portal Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WebsiteContactCreateService.cls
@RestResource(urlMapping='/websitecreatecontact/*')
global with sharing class WebsiteContactCreateService {

    global class Response {
        public String ContactId { get; set; }
        public String FirstName { get; set; }
        public String LastName { get; set; }
        public String Status { get; set; }
        public String Message { get; set; }
        public String ErrorCode { get; set; }            
        public boolean Verified { get; set; }
        public boolean NotApproved { get; set; }   
        public String LoginMethod { get; set; }  
        public String ContactIdCookieValue { get; set; }
        public List<ContactSalesTeam> ContactSalesTeams { get; set; }           
    }
    
    global class WebContact {
        public String Id { get; set; }
        public String FirstName { get; set; }
        public String LastName { get; set; }
        public String Email { get; set; }
        public String CompanyName { get; set; }
        public String Phone { get; set; }
        public String State { get; set; }
        public String CrdId { get; set; }                 
        public String LoginMethod { get; set; } 
        public boolean Verified { get; set; } 
        public String Url { get; set; }  
        public String ContactIdCookieValue { get; set; }
    }
    
    global class ContactSalesTeam { 
        public String TerritoryId { get; set; }
        public String Territory { get; set; }
        public String ZoneName { get; set; }
        public decimal Zone { get; set; }
        public String UserId { get; set; }
        public String FirstName { get; set; }
        public String LastName { get; set; }
        public String Email { get; set; }
        public String Title { get; set; }
        public String Phone { get; set; }        
    }
           
    @HttpGet
    global static Response getContact() {
    
        Response r = new Response();        
        
        try 
        {        
            //Read the Request from the URL 
            String email = RestContext.request.params.get('email');
            String id = RestContext.request.params.get('id');
            String cookieId = RestContext.request.params.get('cookieId');
            String loginMethod = RestContext.request.params.get('loginmethod');
            String url = RestContext.request.params.get('url');
            
            if (String.IsBlank(email) && String.IsBlank(id)) {
                r.ErrorCode = '0003'; 
                r.Status = 'Error'; 
                r.Message = 'Fail : Email/Id is not specified'; 
                return r;
            }                                        
           
            if (!String.IsBlank(email)) {
                boolean found = false;
                String message;
                String contactId;
                String webProfileId;
                String firstName;
                String lastName;
                String state;
                String phone;
                String compName;
                String crdId;
                Boolean notApproved;
                Boolean verified;  
                String contactIdCookieValue;             
                
                ContactWebProfile__c [] cwps = [select id, email__c, FirstName__c, LastName__c, CompanyName__c, Phone__c, State__c, CRDId__C, NotApproved__c, Verified__c, contact__r.id, contactIdCookieValue__c from ContactWebProfile__c where email__c = :email];                      
                
                if (cwps.size() == 0) {
                    Contact[] contacts = [select Id, MarsRepId__c, Email, FirstName, LastName, Phone, CRDID__c, Account.Name, MailingStateCode from Contact where email = :email and repContactType__c != 'Team'];
                    
                    system.debug('con size:'+ contacts.size());
                                    
                    if (contacts.size() == 1) {
                        String cwpId = createContactWebProfile(contacts[0].FirstName, contacts[0].LastName, email, contacts[0].Account.Name, contacts[0].Phone,
                                            contacts[0].MailingStateCode, contacts[0].CRDID__c, contacts[0].id, loginMethod);
                        contactId = contacts[0].id;
                        webProfileId = cwpId;
                        firstName = contacts[0].FirstName;
                        lastName = contacts[0].LastName;
                        compName = contacts[0].Account.Name;
                        phone = contacts[0].Phone;
                        state = contacts[0].MailingStateCode;
                        crdId = contacts[0].CRDID__c;                        
                        found = true;
                        notApproved = null;
                        verified = null;
                    }                    
                } 
                else if (cwps.size() > 1) {
                    found = false;
                    message = 'Fail : Multiple Contact Web Profiles found';
                }
                else {
                    contactId = cwps[0].contact__r.id;
                    webProfileId = cwps[0].id;
                    firstName = cwps[0].FirstName__c;
                    lastName = cwps[0].LastName__c;
                    compName = cwps[0].CompanyName__c;
                    phone = cwps[0].Phone__c;
                    state = cwps[0].State__c;
                    crdId = cwps[0].CRDID__c;   
                    notApproved = cwps[0].NotApproved__c;
                    verified = cwps[0].Verified__c;   
                    contactIdCookieValue = cwps[0].contactIdCookieValue__c;            
                    found = true;
                }                
                
                if (found == true) {            
                    r.Status = 'Success'; 
                    r.ErrorCode = null; 
                    r.Message = 'Success : Found Contact'; 
                    r.ContactId = contactId;
                    r.NotApproved = notApproved;
                    r.Verified = verified;
                    r.FirstName = firstName;
                    r.LastName = lastName;
                    r.contactIdCookieValue = contactIdCookieValue;
                    
                    String des = 'First Name:'+firstName+'\r\nLast Name:'+lastName+'\r\nEmail:'+email+
                            '\r\nPhone:'+phone+'\r\nState:'+state+'\r\nCrd Id:'+crdId+'\r\nContact Id:'+contactId;
                    String paId = createPortalActivity(contactId, 'Login', loginMethod, url, des);
                } else {
                    r.ErrorCode = '0002'; 
                    r.Status = 'Error'; 
                    r.Message = String.IsBlank(message) ? 'Fail : Contact with email ' + email + ' Not Found' : message; 
                }
            }
            else if (!String.IsBlank(id)) {
                 Contact[] c = [select Id, MarsRepId__c, Email, FirstName, LastName, Phone, CRDID__c, Account.Name, MailingStateCode, (select id, contactIdCookieValue__c, NotApproved__c, Verified__c from ContactWebProfiles__r) from Contact where id=:id]; 
                 
                 system.debug('Hello:'+c);
                 if (c.size() == 0) {
                    r.ErrorCode = '0002'; 
                    r.Status = 'Error'; 
                    r.Message = 'Fail : Contact with id ' + id + ' Not Found'; 
                 }
                 else {
                    r.Status = 'Success'; 
                    r.ErrorCode = null; 
                    r.Message = 'Success : Found Contact'; 
                    r.ContactId = id;
                    r.NotApproved = c[0].ContactWebProfiles__r[0].NotApproved__c;
                    r.Verified = c[0].ContactWebProfiles__r[0].Verified__c;
                    r.FirstName = c[0].FirstName;
                    r.LastName = c[0].LastName;
                    r.ContactIdCookieValue = c[0].ContactWebProfiles__r[0].contactIdCookieValue__c;
                    
                    String des = 'First Name:'+c[0].FirstName+'\r\nLast Name:'+c[0].LastName+'\r\nEmail:'+c[0].Email+
                            '\r\nPhone:'+c[0].Phone+'\r\nState:'+c[0].MailingStateCode+'\r\nCrd Id:'+c[0].CrdId__c+'\r\nContact Id:'+id;
                    String paId = createPortalActivity(id, 'Login', loginMethod, url, des);
                 } 
            }
        }  
        catch(Exception e)  
        { 
             //Add custom error code when you could not insert a record 
             r.ErrorCode = '0001'; 
             r.Status = 'Error'; 
             r.Message = e.getMessage(); 
        } 
        return r;      
    }
    
    @HttpPost
    global static Response addContact(WebContact req) {
        //String requestBody = RestContext.request.requestBody.toString();
        //WebContact req = (WebContact) JSON.deserialize(requestBody, WebContact.class); 
        
        system.debug('req:'+req);        
        
        Response r = new Response();
        
        //system.debug('Fm:'+ firstname + 'Lm:'+lastname+ 'email:'+email+'comp:'+companyName+'phone:'+phone+'state:'+state+'crdId:'+crdid);
        
        if (String.isBlank(req.FirstName) || string.isBlank(req.LastName) || String.isBlank(req.Email)) {            
            r.ErrorCode = '0003';
            r.Status = 'Error';
            r.Message = 'The first name and last name and email cannot be empty for a contact';
            return r;
        }       
        
        try {
            // Create contact
            String contactId = createContact(req.FirstName, req.LastName, req.Phone, req.CrdId);
            
            system.debug('Hello:'+contactId);
            
            //Create contact web profile
            String cwpId = createContactWebProfile(req.FirstName, req.LastName, req.Email, req.CompanyName, req.Phone, req.State, req.CrdId, contactId, req.LoginMethod);           
                      
            // Create portal activity
            String paDesc = 'First Name:'+req.FirstName+'\r\nLast Name:'+req.LastName+'\r\nEmail:'+req.Email+'\r\nCompany Name:'+req.CompanyName+
                            '\r\nPhone:'+req.Phone+'\r\nState:'+req.State+'\r\nCrd Id:'+req.CrdId+'\r\nContact Id:'+contactId;
            String paId = createPortalActivity(contactId, 'Login', req.LoginMethod, req.Url, paDesc);
            
            system.debug('activity:'+ paId);
            
            r.Status = 'Success'; 
            r.ErrorCode = null; 
            r.Message = 'Success : Created contact, contact web profile and portal activity'; 
            r.ContactId = contactId;
        }
        catch(Exception ex) {
             r.ErrorCode = '0003'; 
             r.Status = 'Error'; 
             r.Message = ex.getMessage(); 
        }
        
        return r;
    }       
    
    private static String createContactWebProfile(String firstName, String lastName, String email, String companyName, String phone, String state, String crdId, String contactId, String source) {
    system.debug('CWP:'+ contactId);
        ContactWebProfile__c cwp = new ContactWebProfile__c(
            FirstName__c = firstName,
            LastName__c = lastName,
            Email__c = email,
            CompanyName__c = companyName,
            Phone__c = phone,
            State__c = state,
            CRDId__c = crdId,
            Contact__c = contactId,
            RegistrationSource__c = source
        );
        
        insert cwp;
        return cwp.Id;
    }
    
    private static String createContact(String firstname, String lastname,
        String phone, String crdid) {
        system.debug('con:'+firstname + ' '+lastname+ ' '+ phone+ ' '+ crdid);
        String officeId = 'OF882244';
        Contact c = new Contact(
            FirstName = firstname,
            LastName = lastname,
            Phone = phone,
            RecordType = new RecordType (Name='Rep/Contact'),
            RepContactType__c = 'Rep/Contact',
            Account = new account(MarsAccountId__c = officeId),  
            CrdID__c = crdid,
            Ownerid = '005F0000003xza2IAA'
        );
        insert c;
        return c.Id;
    }  
           
    private static String createPortalActivity(String contactId, String action, String loginMethod, String url, String description) {
        PortalActivity__c pa = new PortalActivity__c (
            EventTime__c = system.now(),
            Contact__c = contactId,            
            Action__c = action,
            LoginMethod__c = loginMethod,
            Url__c = url,
            Source__c = 'NGAM Website',
            Description__c = description,
            RepId__c = contactId,
            Ownerid = '005F0000003xza2IAA'
        );
        insert pa;
        return pa.Id;       
    }
}