objects/Account.object
<CustomObject>
    <fields>
        <fullName>NumberOfOpenTasks__c</fullName>
        <description>The number of open tasks this Account has. Controlled by a trigger on task.</description>
        <inlineHelpText>The number of open tasks this Account has.</inlineHelpText>
        <label>Number of Open Tasks</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Affiliate</fullName>
        <active>true</active>
        <label>Affiliate</label>
    </recordTypes>
</CustomObject>

objects/ActionPlan__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Action Plans</relationshipLabel>
        <relationshipName>Action_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Action_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Action Plan</label>
        <referenceTo>ActionPlan__c</referenceTo>
        <relationshipName>Action_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The Start Date of the Action Plan</description>
        <inlineHelpText>The Start Date of the Action Plan</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <description>Action Plan instance.</description>
    <label>Action Plan</label>
    <nameField>
        <label>Action Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/APTaskTemplate__c.object
<CustomObject>
    <fields>
        <fullName>APTaskTemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Task Dependency</label>
        <referenceTo>APTaskTemplate__c</referenceTo>
        <relationshipLabel>AP Tasks</relationshipLabel>
        <relationshipName>R00NR0000000VcWbMAK</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DaysFromStart__c</fullName>
        <label>Days After</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dependent__c</fullName>
        <label>Dependent</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Phone Call</fullName>
                </value>
                <value>
                    <fullName>Mail</fullName>
                </value>
                <value>
                    <fullName>Misc</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Action_Plan__c</fullName>
        <label>Action Plan</label>
        <referenceTo>ActionPlan__c</referenceTo>
        <relationshipName>R00NR0000000VccFMAS</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <description>Action Plan Task detail</description>
    <label>AP Task</label>
    <nameField>
        <label>APTaskTemplate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AP Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Effective date of the EPAT request of type Onboard and populated by EPAT-SFDC job.</description>
        <inlineHelpText>Effective date of the EPAT request of type Onboard and populated by EPAT-SFDC job.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>UserID__c</fullName>
        <defaultValue>"Populate This Field"</defaultValue>
        <externalId>true</externalId>
        <label>UserID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/SL_TaskTrigger_test.cls
@isTest
public class SL_TaskTrigger_test {
    
    @isTest
    public static void insert_test() {
        
        Account acc = new Account(Name = 'testAccount' + Math.random(), type = 'Affiliate', NumberOfOpenTasks__c = 3 );
        insert acc;

        Account returnedAcc = [SELECT id, NumberOfOpenTasks__c FROM Account WHERE id =: acc.Id LIMIT 1];

        System.assertEquals(returnedAcc.NumberOfOpenTasks__c, 3);

        List<Task> lstTaskToInsert = new List<Task>();
            lstTaskToInsert.add(new Task(WhatId = acc.Id));
            lstTaskToInsert.add(new Task(WhatId = acc.Id));
        insert lstTaskToInsert;

        returnedAcc = [SELECT id, NumberOfOpenTasks__c FROM Account WHERE id =: acc.Id LIMIT 1];

        System.assertEquals(returnedAcc.NumberOfOpenTasks__c, 2);

        List<Task> lstTaskToInsert2 = new List<Task>();
            lstTaskToInsert2.add(new Task(WhatId = acc.Id));
            lstTaskToInsert2.add(new Task(WhatId = acc.Id));
        insert lstTaskToInsert2;

        returnedAcc = [SELECT id, NumberOfOpenTasks__c FROM Account WHERE id =: acc.Id LIMIT 1];

        System.assertEquals(returnedAcc.NumberOfOpenTasks__c, 4);

        Account acc2 = new Account(Name = 'testAccount2', type = 'Affiliate', NumberOfOpenTasks__c = 3 );
        insert acc2;
        lstTaskToInsert2[0].WhatId = acc2.Id ;
        update lstTaskToInsert2;
    }

    @isTest
    public static void insertFromActionPlan_test() {

        Account acc = new Account(Name = 'testAccount', type = 'Affiliate', NumberOfOpenTasks__c = 3 );
        insert acc;

        ActionPlan__c actionPlan = new ActionPlan__c();
            actionPlan.Name			= 'test name' + Math.random();
            actionPlan.StartDate__c 	= Date.today();
            actionPlan.OwnerId		= Userinfo.getUserId();
            actionPlan.Account__c = acc.Id; 		
 		insert actionPlan;

        APTaskTemplate__c APTask = new APTaskTemplate__c();
            APTask.Subject__c           = 'test subject' + Math.random();
            APTask.DaysFromStart__c     = 2;
            APTask.Dependent__c         = '2';
            APTask.Type__c              = 'Email';
            APTask.Priority__c          = 'Hight';
            APTask.Action_Plan__c       = actionPlan.Id;
        insert APTask;

        List<APTaskTemplate__c> returnedAAPTask = [SELECT id FROM APTaskTemplate__c WHERE id =: APTask.Id ];

        System.assertEquals(returnedAAPTask.size(), 1);

        List<Task> lstTaskToInsert = new List<Task>();
            lstTaskToInsert.add(new Task(WhatId = APTask.Id));
        insert lstTaskToInsert;

        List<Task> afterInsert = [SELECT id, Action_Plan_Task__c FROM Task];
        System.assertEquals(afterInsert[0].Action_Plan_Task__c, true);
    }

    @isTest
    public static void update_test() {
        
         Account acc = new Account(Name = 'testAccount', type = 'Affiliate', NumberOfOpenTasks__c = 3 );
        insert acc;

        ActionPlan__c actionPlan = new ActionPlan__c();
            actionPlan.Name			= 'test name' + Math.random();
            actionPlan.StartDate__c 	= Date.today();
            actionPlan.OwnerId		= Userinfo.getUserId();
            actionPlan.Account__c = acc.Id; 		
 		insert actionPlan;

        APTaskTemplate__c APTask = new APTaskTemplate__c();
            APTask.Subject__c           = 'test subject' + Math.random();
            APTask.DaysFromStart__c     = 2;
            APTask.Dependent__c         = '2';
            APTask.Type__c              = 'Email';
            APTask.Priority__c          = 'Hight';
            APTask.Action_Plan__c       = actionPlan.Id;
        insert APTask;

        List<Task> lstTaskToInsert = new List<Task>();
            lstTaskToInsert.add(new Task(WhatId = APTask.Id, ActivityDate = date.today().addDays(-1)));
        insert lstTaskToInsert;

        List<Task> afterInsert = [SELECT id, ActivityDate FROM Task];
        for (Integer i = 0; i < afterInsert.size(); i++) {
            System.assertEquals(afterInsert[0].ActivityDate, date.today().addDays(-1));
        }

        
        Profile p = [select id from profile where name='System Administrator'];
        User u2 = new User(alias = 'standt', email='SFDCadmin@ngam.natixis.com', 
                            emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
                            localesidkey='en_US', profileid = p.id, 
                            timezonesidkey='America/Los_Angeles', username='SFDCadmin@ngam.natixis.com',UserID__c='SFDCadmin');
        
        System.runAs(u2){

            lstTaskToInsert[0].Status = 'Completed';
            update lstTaskToInsert;
        }
        afterInsert = [SELECT id, ActivityDate FROM Task];
        for (Integer i = 0; i < afterInsert.size(); i++) {
            System.assertEquals(afterInsert[0].ActivityDate, date.today());
        }
    }
}