objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>The MARS status of the account, Data Flow: Mars -&gt; SF</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Source: MARS na_load_rep.StatCd
Loaded by a nightly job.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>Community__c</fullName>
        <label>Community</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Effective_Datetime__c</fullName>
        <label>Effective Datetime</label>
        <type>DateTime</type>
    </fields>
</CustomObject>

objects/ExternalCommunitySettings__c.object
<CustomObject>
    <fields>
        <fullName>PermissionSetsForFAUser__c</fullName>
        <description>Permission set for FA user</description>
        <inlineHelpText>Permission Set that is assigned to Financial Advisor contact user records during setup of Financial Account Contact (type = Financial Advisor).</inlineHelpText>
        <label>PermissionSetsForFAUser</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProfileForEndClient__c</fullName>
        <description>profile for end client or 3 party</description>
        <inlineHelpText>Profile that is assigned to End Client contact user records during setup of Financial Account Contact (type = End Client).</inlineHelpText>
        <label>ProfileForEndClient</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProfileForFAUser__c</fullName>
        <description>Profile name for FA</description>
        <inlineHelpText>Profile that is assigned to Financial Advisor contact user records during setup of Financial Account Contact (type = Financial Advisor).</inlineHelpText>
        <label>ProfileForFAUser</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TestUserEmail__c</fullName>
        <description>Use Test email to create user</description>
        <inlineHelpText>If UseTestEmail is set to 'Y', this is the "to" email that will be used in the place of all community user email addresses.</inlineHelpText>
        <label>TestUserEmail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UseMPANamedCredential__c</fullName>
        <description>UseMPANamedCredential  , use the url from MPA or MPA_TEST based on the value from this field</description>
        <label>UseMPANamedCredential</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserNameFormat__c</fullName>
        <description>UserNameFormat for user record</description>
        <label>UserNameFormat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>To the custom setting for external communities</description>
    <label>ExternalCommunitySettings</label>
</CustomObject>

objects/FinancialAccount__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <description>Integration: NTXS_CUST_ACCOUNTS.Account_Id</description>
        <externalId>true</externalId>
        <inlineHelpText>Id of the Financial Account in Data Central. DEPRECATED will be removed in Version 8.0.</inlineHelpText>
        <label>Account Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>AccountNameEncrypted__c</fullName>
        <description>Unique Vestmark Account name</description>
        <inlineHelpText>Unique Vestmark Account name</inlineHelpText>
        <label>Account Name</label>
        <length>30</length>
        <maskChar>X</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>RSAAccount__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, indicates that this Financial Account is an RSA account.  Checking this box will affect how the Financial Account appears in the community.</description>
        <inlineHelpText>If checked, indicates that this Financial Account is an RSA account.  Checking this box will affect how the Financial Account appears in the community.</inlineHelpText>
        <label>RSA Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ViewableinCommunity__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If checked, this Financial Account can be viewed in Community</description>
        <inlineHelpText>If checked, this Financial Account can be viewed in Community</inlineHelpText>
        <label>Viewable in Community</label>
        <type>Checkbox</type>
    </fields>
    <description>Used in community to display Financial Account data to community users.  This object's data is sourced from Data Central and maintained via integration.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/FinancialAccountContact__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact related to the Financial Account</description>
        <inlineHelpText>Contact related to the Financial Account</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Financial Account Contact</relationshipLabel>
        <relationshipName>Financial_Account_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Indicates the status of the contact's relationship to the Financial Account</description>
        <inlineHelpText>Indicate the status of the contact's relationship to the Financial Account</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                    <default>true</default>
                    <label>Current</label>
                </value>
                <value>
                    <fullName>Former</fullName>
                </value>
                <value>
                    <fullName>Inactivated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>View_Financial_Account_in_Community__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates if this contact should see the Financial Account in the community.</description>
        <inlineHelpText>If checked, the contact will be able to see the Financial Account in the community</inlineHelpText>
        <label>View Financial Account in Community?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <description>Financial Account to which this contact is related</description>
        <inlineHelpText>Financial Account to which this contact is related</inlineHelpText>
        <label>Financial Account</label>
        <referenceTo>FinancialAccount__c</referenceTo>
        <relationshipLabel>Financial Account Contact</relationshipLabel>
        <relationshipName>Financial_Account_Contact</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <description>Tracks contacts associated with a Financial Account.  Dictates which contacts (community users) can see a particular Financial Account in the community.</description>
    <label>Financial Account Contact</label>
    <nameField>
        <displayFormat>FAC-{000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/FinancialAccountFile__c.object
<CustomObject>
    <fields>
        <fullName>DoNotDisplayReason__c</fullName>
        <description>Reason this file should not be displayed to community members</description>
        <inlineHelpText>Reason this file should not be displayed to community members</inlineHelpText>
        <label>Do Not Display Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DoNotDisplayinCommunity__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, this file will not be viewable by community members</description>
        <inlineHelpText>If checked, this file will not be viewable by community members</inlineHelpText>
        <label>Do Not Display in Community</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DocumentDate__c</fullName>
        <description>The effective date of the document.  For example, the Document Date would be 3/31 for a Q2 document even though the file record might have a created date of 4/15.</description>
        <inlineHelpText>The effective date of the document.  For example, the Document Date would be 3/31 for a Q2 document even though the Financial Account File record might have a created date of 4/15.</inlineHelpText>
        <label>Document Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DocumentQuarter__c</fullName>
        <description>Calculates the quarter of the document based on the Document Date</description>
        <formula>CASE( MONTH( DocumentDate__c )  ,
1,"Q1",
2,"Q1",
3,"Q1",
4,"Q2",
5,"Q2",
6,"Q2",
7,"Q3",
8,"Q3",
9,"Q3",
10,"Q4",
11,"Q4",
12,"Q4",
"Q4")</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Calculates the quarter of the document based on the Document Date</inlineHelpText>
        <label>Document Quarter</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DocumentType__c</fullName>
        <description>The type of document/file that this record represents.</description>
        <inlineHelpText>The type of document/file that this record represents</inlineHelpText>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Quarterly Performance Report</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OriginalFileName__c</fullName>
        <description>Name of the original file as stored on the shared directory.</description>
        <inlineHelpText>Name of the original file as stored on the shared directory.</inlineHelpText>
        <label>Original File Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FinancialAccount__c</fullName>
        <description>The Financial Account to which this file belongs</description>
        <inlineHelpText>The Financial Account to which this file belongs</inlineHelpText>
        <label>Financial Account</label>
        <referenceTo>FinancialAccount__c</referenceTo>
        <relationshipLabel>Financial Account Files</relationshipLabel>
        <relationshipName>FinancialAccountFiles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <description>Used as a "holding object" for files related to Financial Account.  Files are posted to this record rather than directly to the Financial Account record so that we can carry data about the file in the system.  Note, at current development time it was not possible to use API calls to write data about the file to Content object.</description>
    <label>Financial Account File</label>
    <nameField>
        <displayFormat>FAF-{0000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Files</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/NGAMSettings__c.object
<CustomObject>
    <fields>
        <fullName>ProfileSystemAdministrator__c</fullName>
        <description>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</description>
        <inlineHelpText>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</inlineHelpText>
        <label>Profile: System Administrator</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Holds the NGAM settings</description>
    <label>NGAM Settings</label>
</CustomObject>

objects/NGAMSettingsHierarchy__c.object
<CustomObject>
    <fields>
        <fullName>ByPassAccountValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows entity to by-pass validation rules on Account</description>
        <inlineHelpText>Allows entity to by-pass validation rules on Account</inlineHelpText>
        <label>By-Pass Account Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NGAM Settings - Hierarchy</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Used in the Affiliate Request Flow to filter 'Requested on Behalf' of. Can not use Out of Box field for end users.</description>
        <formula>IF( IsActive = True, True, False)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UserID__c</fullName>
        <defaultValue>"Populate This Field"</defaultValue>
        <externalId>true</externalId>
        <label>UserID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CommunitiesEstatementController_Test.cls
@isTest 

public class CommunitiesEstatementController_Test { 

    static testMethod void CommunitiesEstatementController_Test() { 
    
        NGAMSettingsHierarchy__c hsettings = NGAMSettingsHierarchy__c.getOrgDefaults();
        hsettings.ByPassAccountValidationRules__c  = TRUE;
        upsert hsettings NGAMSettingsHierarchy__c.Id;
    
        String Community = 'eStatement'; 
        DataFactory.CreateNGAMCustomSettings(); 
        
        ExternalCommunitySettings__c ECS = new ExternalCommunitySettings__c(); 
        ECS.Name = 'EstatementCommunity'; 
        ECS.UseMPANamedCredential__c = 'testugng'; 
        ECS.UserNameFormat__c = 'TEstcom'; 
        ECS.TestUserEmail__c = 'TEst@gmail.com'; 
        ECS.ProfileForFAUser__c ='NGAM Community Plus Login User'; 
        ECS.ProfileForEndClient__c ='NGAM Community Plus Login User'; 
        ECS.PermissionSetsForFAUser__c='Community_login_User_eStatement'; 
        insert ECS; 
        
        ExternalCommunitySettings__c myCustomSetting = ExternalCommunitySettings__c.getValues('EstatementCommunity'); 
        String PermSetForFAName = myCustomSetting.PermissionSetsForFAUser__c; 
        String ProfileForFAUser = myCustomSetting.ProfileForFAUser__c; 
        String ProfileForEndClient = myCustomSetting.ProfileForEndClient__c; 
        string FAprofileId = Util.getCustomSettingProfileId(ProfileForFAUser); 
        
        NGAMSettings__c ngamSettings = [select id,ProfileSystemAdministrator__c from NGAMSettings__c limit 1]; 
        string SAprofileId = Util.getCustomSettingProfileId(ngamSettings.ProfileSystemAdministrator__c); 
           
        Account a = new Account(Name = 'TEST Account'); 
        insert a; 
        
        contact con = new contact(FirstName='ABC',LastName = 'TEST Account',AccountId = a.Id); 
        insert con;         
        
        User user = new User(alias = 'test123', email='test123@noemail.com', 
                                emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
                                localesidkey='en_US', profileid = FAprofileId, country='United States',IsActive =true, 
                                ContactId = con.Id,userId__c ='sstfr', 
                                timezonesidkey='America/Los_Angeles', username='tester@noemail.com'); 
        insert user; 
        
        FinancialAccount__c testAcc = new FinancialAccount__c(Name='Test Name',AccountID__c=123); 
        testAcc.RSAAccount__c = false; 
        testAcc.AccountNameEncrypted__c ='abc'; 
        insert testAcc; 
        
        FinancialAccountContact__c FAC = new FinancialAccountContact__c(); 
        FAC.Financial_Account__c = testAcc.Id; 
        FAC.contact__c = con.Id; 
        FAC.Status__c = 'Current'; 
        FAC.View_Financial_Account_in_Community__c = true; 
        insert FAC; 
        
        
        //Get a list of ALL FeedItems where their parent Financial Account File records are viewable in the community 
        List<FeedItem> feedItemList = [SELECT Id, ParentId, Type, Title, Body, CommentCount, LikeCount, LinkUrl, RelatedRecordId 
                                        FROM FeedItem WHERE Type='ContentPost' 
                                        AND ParentId IN (SELECT Id FROM FinancialAccountFile__c WHERE DoNotDisplayinCommunity__c = FALSE 
                                        AND FinancialAccount__r.ViewableinCommunity__c = TRUE)]; 
        system.debug('feedItemList: ' + feedItemList); 
        
        Set<Id> finAccountFileIdSet = new Set<Id>(); 
        for (FeedItem fi : feedItemList) { 
            finAccountFileIdSet.add(fi.ParentId); 
        } 
        
        finAccountFileIdSet.add(testAcc.Id); 
        
        //Get the FeedItems' corresponding Financial Accounts 
        List<FinancialAccount__c> finAcct = [SELECT Id FROM FinancialAccount__c WHERE Id IN (SELECT FinancialAccount__c FROM FinancialAccountFile__c WHERE Id IN :finAccountFileIdSet)]; 
        system.debug('finAcct: ' + finAcct); 
        
        //Get one Financial Account Contact records with a contact who has access to any of the Financial Accounts in the list 
        //Select from Financial Account Contact where criteria makes him have sharing and where the user is active, etc. 
        FinancialAccountContact__c finAcctContact = [SELECT Id, Financial_Account__c, Contact__c, Financial_Account__r.Name, Contact__r.LastName 
                                                        FROM FinancialAccountContact__c WHERE Status__c = 'Current' 
                                                        AND View_Financial_Account_in_Community__c = TRUE 
                                                        LIMIT 1]; 
        
        //This is the Financial Account Id that will be used in sharing, querying files, etc. below 
        Id financialAccountId = finAcctContact.Financial_Account__c; 
        
        FinancialAccountFile__c FAF = new FinancialAccountFile__c(); 
        FAF.FinancialAccount__c = financialAccountId; 
        
        insert FAF; 
        
        //Get a Financial Account File record for the Financial Account that has a feedItem 
        FinancialAccountFile__c finAcctFile = [SELECT Id, Name FROM FinancialAccountFile__c WHERE FinancialAccount__c =: financialAccountId LIMIT 1]; 
        
        FeedItem feed = new FeedItem (parentid = finAcctFile.id, 
                                        type = 'ContentPost', 
                                        Body = 'Hello'); 
        
        insert feed; 
        
        FeedItem finAcctFileFeedItem = [SELECT Id 
        FROM FeedItem WHERE ParentId =: finAcctFile.Id LIMIT 1]; 
        
        //Get the corresponding User from the Financial Account Contact Record; note we have already filtered for active and profile in the Financial Account Contact select 
        User checkForFileAccessUser = [SELECT Id, LastName FROM User WHERE ContactId =: finAcctContact.Contact__c LIMIT 1]; 
        system.debug('checkForFileAccessUser: ' + checkForFileAccessUser); 
        
        //Just to be sure, apply sharing rules for this user to the Financial Account 
        FinancialAccount__Share shareToCreate = new FinancialAccount__Share(AccessLevel='Read',ParentId=financialAccountId, 
        RowCause=Schema.FinancialAccount__Share.RowCause.Manual, 
        UserOrGroupId=checkForFileAccessUser.Id); 
        insert shareToCreate; 
        
        //Just to be sure, apply permissionset to this user 
        /*PermissionSet PermSetForFA = [SELECT Id FROM PermissionSet WHERE Name = :PermSetForFAName LIMIT 1]; 
        List<PermissionSetAssignment> permSetCheck = [SELECT Id FROM PermissionSetAssignment WHERE PermissionSetId =:PermSetForFA.Id AND AssigneeId =:checkForFileAccessUser.Id]; 
        if (permSetCheck.size() == 0) { 
        PermissionSetAssignment permSetAssignmentInsert = new PermissionSetAssignment(PermissionSetId = PermSetForFA.Id, AssigneeId = checkForFileAccessUser.Id); 
        insert permSetAssignmentInsert; 
        } */ 
        
        
        //One more check of shares after insert 
        List<FinancialAccount__Share> finAcctShareCheck = [SELECT Id FROM FinancialAccount__Share WHERE UserOrGroupId =: checkForFileAccessUser.Id]; 
        
        //At this point we should have a user with access to a Feed Item on a Financial Account File that belongs to a Financial Account that he has sharing on 
        system.debug('---Financial Account and User Details---'); 
        system.debug(' Financial Account: ' + financialAccountId + ' - ' + finAcctContact.Financial_Account__r.Name); 
        system.debug(' Financial Account Contact: ' + finAcctContact.Contact__c + ' - ' + finAcctContact.Contact__r.LastName); 
        system.debug(' Financial Account Contact User: ' + checkForFileAccessUser.Id + ' - ' + checkForFileAccessUser.LastName); 
        system.debug(' Financial Account Share Record Id: ' + finAcctShareCheck[0].Id); 
        system.debug(' Financial Account File: ' + finAcctFile.Id + ' - ' + finAcctFile.Name); 
        system.debug(' Financial Account FeedItem: ' + finAcctFileFeedItem.Id); 
        
        //Get sysAdmin user 
        User sysAdmin = [SELECT Id FROM User WHERE ProfileId =:SAprofileId AND IsActive = TRUE LIMIT 1 ]; 
        
        //Get FAUser -- why? 
        User FAUser = [SELECT Id,ContactId FROM User WHERE IsActive = TRUE 
                      and ContactId !=:finAcctContact.Contact__c LIMIT 1]; 
        
        //Insert new FeedItem for Financial Account File on checkForFileAccessUser's Financial Account File 
        ContentVersion cv = new ContentVersion(); 
        cv.Title = 'Test file'; 
        cv.Description = 'Test file'; 
        Blob bodyBlob=Blob.valueOf('Unit Test ContentVersion Body'); 
        cv.VersionData=bodyBlob; 
        cv.PathOnClient = 'Test drive'; 
        insert cv; 
        
        FeedItem item = new FeedItem(); 
        item.ParentId = finAcctFile.Id; 
        item.Body = 'Test'; 
        item.Type = 'ContentPost'; 
        item.Visibility = 'AllUsers'; 
        insert item; 
        
        FeedAttachment feedAtt = new FeedAttachment(); 
        feedAtt.Title = 'Test'; 
        feedAtt.Type = 'CONTENT'; 
        feedAtt.RecordId = cv.Id; 
        feedAtt.FeedEntityId = item.Id; 
        insert feedAtt; 
        
        Test.startTest(); 
        System.runAs(sysAdmin) { 
            communitiesEstatementController ctrl = new communitiesEstatementController(); 
            PageReference pr = ctrl.forwardToCustomAuthPage(); 
            
            Map<String, Object> clientsnull = communitiesEstatementController.queryFinancialAccountByClients(FAUser.Id); 
            Map<String, Object> clientsnull1 = communitiesEstatementController.queryFinancialAccountByClients(null); 
            Map<String, Object> terms = communitiesEstatementController.queryTermsConditionsHistory(); 
            Map<String, Object> tcList = communitiesEstatementController.queryUserInfo(Community); 
            Map<String, Object> latest = communitiesEstatementController.GetLatestTCData(Community); 
            Map<String, Object> qat = communitiesEstatementController.queryAcceptedTerms(Community); 
            Map<String, Object> pg = communitiesEstatementController.CommunityLogout(); 
            Map<String, Object> communityPrivatePolicy = communitiesEstatementController.CommunityPrivatePolicy(Community); 
            
            String Msg = communitiesEstatementController.SendEmail('Community'); 
            String CommunityContact = communitiesEstatementController.CommunityContactUs(); 
            String tesFile = communitiesEstatementController.ReadStaticResourceFile('TEST'); 
            
            List<List<SObject>> searchResult = communitiesEstatementController.SearchText('abc'); 
            Map<String, Object> CommunityFAQList = communitiesEstatementController.CommunityFAQ(Community); 
            Map<String, Object> pwd = communitiesEstatementController.CommunityForgotPassword(); 
        } 
        
        System.runAs(sysAdmin) { 
            String ContentVersionId = null; 
            
            Map<String, Object> updateUser = communitiesEstatementController.updateUserInfo(ContentVersionId, 1); 
            Map<String, Object> updateUser_1 = communitiesEstatementController.updateUserInfo(cv.Id, 1); 
            Map<String, Object> updateUser_2 = communitiesEstatementController.updateUserInfo(cv.Id, 0); 
            
            List<ContentWorkspace> workspaceList = [SELECT Id FROM ContentWorkspace WHERE Name = 'Terms and Conditions']; 
            if((workspaceList != null) && (!workspaceList.isEmpty())){ 
            
                Id workspaceId = workspaceList[0].Id; 
                List<ContentVersion> versionList = [SELECT Id, ContentDocumentId, ContentUrl, IsLatest, VersionNumber, Title, Description, ReasonForChange, SharingOption, 
                PathOnClient, NetworkId, Origin, FileExtension, ContentSize, VersionData, PublishStatus, FileType, CreatedDate, 
                ContentLocation, TextPreview, IsMajorVersion, Effective_Datetime__c, Community__c FROM ContentVersion 
                where Community__c=:Community and IsLatest = true and PublishStatus ='P' 
                and ContentDocument.ParentId = :workspaceId and RecordType.NAME ='Community Files' 
                order by Effective_Datetime__c desc]; 
                if(!versionList.isEmpty()){ 
                    Map<String, Object> updateUser1 = communitiesEstatementController.updateUserInfo(versionList[0].Id, 1); 
                    Map<String, Object> updateUser2 = communitiesEstatementController.updateUserInfo(versionList[0].Id, 0); 
                } 
            } 
            Map<String, Object> pass = communitiesEstatementController.CommunityChangePassword('Abc1@1234','Abc1@1234'); 
        
        } 
        
        System.runAs(sysAdmin) { 
            // Note that this was originally meant to run as community user to test row-level security on FeedItem, but the test class wouldn't pass due 
            // to an error that said we need an ID to query FeedItem. SFDC responded to a case saying that aliases (including sets, lists, etc.) 
            // cannot be used in a SOQL of FeedItem in a test class and that the system is working as designed. The functionality we need 
            // does work when running with a real user signed into the UI. I had to change runAs to sysAdmin to 
            // get the code in production. TJB 7/28/17 
            
            system.debug('financialAccountId: ' + financialAccountId); 
            
            List<object> l = communitiesEstatementController.queryChatterFilesByFilesList(financialAccountId,null,finAcctFileFeedItem.Id); 
            
            List<FinancialAccountFile__c> l2 = new List<FinancialAccountFile__c>([SELECT Id, IsDeleted, Name, FinancialAccount__c, DoNotDisplayReason__c, DoNotDisplayinCommunity__c, 
                                                                                    DocumentQuarter__c, DocumentDate__c, DocumentType__c, OriginalFileName__c,DocumentYear__c 
                                                                                    FROM FinancialAccountFile__c WHERE FinancialAccount__c=:financialAccountId Limit 1]); 
            
            List<object> f1 = communitiesEstatementController.queryChatterFilesByFilesList(financialAccountId,l2,finAcctFileFeedItem.Id); 
        } 
        
        Test.stopTest(); 
        
    } 
    
}