objects/Account.object
<CustomObject>
    <fields>
        <fullName>FirmType__c</fullName>
        <description>MARS Firm Type picklist, Data Flow: Mars -&gt; SF</description>
        <label>Firm Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ADU BANK TRUST</fullName>
                </value>
                <value>
                    <fullName>ASSET MGR</fullName>
                </value>
                <value>
                    <fullName>BACK OFFICE</fullName>
                </value>
                <value>
                    <fullName>BANK TRUST B</fullName>
                </value>
                <value>
                    <fullName>BANK TRUST PW</fullName>
                </value>
                <value>
                    <fullName>BROKER DEALER B</fullName>
                </value>
                <value>
                    <fullName>CLEARING</fullName>
                </value>
                <value>
                    <fullName>CONSULTANT</fullName>
                </value>
                <value>
                    <fullName>DCIO</fullName>
                </value>
                <value>
                    <fullName>DC PLATFORM</fullName>
                </value>
                <value>
                    <fullName>DIRECT H</fullName>
                </value>
                <value>
                    <fullName>DIRECT L</fullName>
                </value>
                <value>
                    <fullName>DIRECT N</fullName>
                </value>
                <value>
                    <fullName>DIRECT O</fullName>
                </value>
                <value>
                    <fullName>EDJ</fullName>
                </value>
                <value>
                    <fullName>INDEPENDENT BD A</fullName>
                </value>
                <value>
                    <fullName>INDEPENDENT BD B</fullName>
                </value>
                <value>
                    <fullName>INDEPENDENT BD C</fullName>
                </value>
                <value>
                    <fullName>INSTITUTIONAL A</fullName>
                </value>
                <value>
                    <fullName>INSTITUTIONAL P</fullName>
                </value>
                <value>
                    <fullName>INSTITUTIONAL PW</fullName>
                </value>
                <value>
                    <fullName>INTNL GKA</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>OFFSHORE</fullName>
                </value>
                <value>
                    <fullName>PLAN SPONSOR</fullName>
                </value>
                <value>
                    <fullName>RCDU BANK TRUST</fullName>
                </value>
                <value>
                    <fullName>RCDU BD</fullName>
                </value>
                <value>
                    <fullName>RCDU GKA</fullName>
                </value>
                <value>
                    <fullName>RIA A</fullName>
                </value>
                <value>
                    <fullName>RIA ADU PW</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HomeOfficeId__c</fullName>
        <description>MARS Home Office Id, Data Flow: Mars -&gt; SF</description>
        <label>Home Office Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MarsAccountId__c</fullName>
        <description>The unique Account Identifier for MARS; used in integrations, Data Flow: Mars -&gt; SF</description>
        <externalId>true</externalId>
        <label>MARS Account Id</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>WCMRelationshipFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Maintained by loading firms identified by Data Ops, the data is not integrated. This field is used in formulas at the office and contact level and indicates that the related advisers should not have WCM products discussed with them or related material emailed to them.</description>
        <label>WCM Relationship Flag</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Firm</fullName>
        <active>true</active>
        <description>Firms, offices, and reps are organized into a hierarchy. This means that each rep must be assigned to an office, and each office must be assigned to a firm. Firm is the highest level in the hierarchy.</description>
        <label>Firm</label>
    </recordTypes>
    <recordTypes>
        <fullName>Office</fullName>
        <active>true</active>
        <description>An individual branch location for a firm. Each firm must have a home office, which is the firm's primary location. Additionally, a firm can have multiple branch offices.</description>
        <label>Office</label>
    </recordTypes>
</CustomObject>

objects/NGAMSettingsHierarchy__c.object
<CustomObject>
    <fields>
        <fullName>ByPassAccountValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows entity to by-pass validation rules on Account</description>
        <inlineHelpText>Allows entity to by-pass validation rules on Account</inlineHelpText>
        <label>By-Pass Account Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NGAM Settings - Hierarchy</label>
</CustomObject>

classes/AccountTriggerHandlerTest.cls
@isTest
public class AccountTriggerHandlerTest {
    
    static testmethod void AccountTriggerHandlerTest() {
        
        Id firmRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Firm').getRecordTypeId();
        Id officeRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Office').getRecordTypeId();
        
        NGAMSettingsHierarchy__c settings = NGAMSettingsHierarchy__c.getOrgDefaults();
        settings.ByPassAccountValidationRules__c  = TRUE;
        upsert settings NGAMSettingsHierarchy__c.Id;
        
        List<Account> firms = DataFactory.createTestFirms(2);
        firms[0].Name = 'firms[0]';
        firms[0].WCMRelationshipFlag__c = TRUE;
        firms[0].Type = 'Firm';
        firms[0].FirmType__c = 'FIRMTYPE';
        firms[0].RecordTypeId = firmRecTypeId;
        firms[1].Name = 'firms[1]';
        firms[1].WCMRelationshipFlag__c = FALSE;
        firms[1].Type = 'Firm';
        firms[1].RecordTypeId = firmRecTypeId;        
        insert firms;   
        
        List<Account> homeoffices = DataFactory.createTestAccounts(2);
        homeoffices[0].Name = 'homeoffices[0]';
        homeoffices[0].RecordTypeId = officeRecTypeId;
        homeoffices[0].Type = 'Home';
        homeoffices[0].ParentId = firms[0].Id;
        homeoffices[1].Name = 'homeoffices[1]';
        homeoffices[1].RecordTypeId = officeRecTypeId;
        homeoffices[1].Type = 'Home';
        homeoffices[1].ParentId = firms[1].Id;
        insert homeoffices;
        
        homeoffices[0].MarsAccountId__c = 'MARS12345';
        homeoffices[1].MarsAccountId__c = 'MARS54321';
        update homeoffices;
        
        List<Account> asserts = [SELECT Id, Name, WCMRelationshipFlag__c, HomeOfficeId__c, FirmType__c FROM Account];
        
        for (Account a : asserts) {
            SWITCH ON a.Name {
                
                WHEN 'firms[0]' {
                    system.assertEquals(a.HomeOfficeId__c,'MARS12345','Set HomeOfficeId__c');    
                }                
                
                WHEN 'firms[1]' {
                    system.assertEquals(a.HomeOfficeId__c,'MARS54321','Set HomeOfficeId__c');
                }                
                
                WHEN 'homeoffices[0]' {
                    system.assertEquals(a.WCMRelationshipFlag__c, TRUE ,'Set WCMRelationshipFlag__c');
                    system.assertEquals(a.FirmType__c, 'FIRMTYPE','Set FirmType__c');
                }                
                
                WHEN 'homeoffices[1]' {
                    system.assertEquals(a.WCMRelationshipFlag__c, FALSE ,'Set WCMRelationshipFlag__c');
                }                
                
            }
            
        }
        
    }
    
}