objects/Account.object
<CustomObject>
    <fields>
        <fullName>BPL__c</fullName>
        <defaultValue>false</defaultValue>
        <description>No Longer Used; if Account is part of the Blue Print List, true; manually updated/updated via data load</description>
        <label>BPL</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <description>No Longer Used; Fiduciary Services field to indicate subchannel</description>
        <label>Channel</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BANK TRUST</fullName>
                </value>
                <value>
                    <fullName>BANK TRUST WHSE</fullName>
                </value>
                <value>
                    <fullName>DCIO</fullName>
                </value>
                <value>
                    <fullName>DCIO SUB ADV</fullName>
                </value>
                <value>
                    <fullName>DC REGIONAL</fullName>
                </value>
                <value>
                    <fullName>FID FOCUS</fullName>
                </value>
                <value>
                    <fullName>FIDUCIARY BD</fullName>
                </value>
                <value>
                    <fullName>FIDUCIARY SERVICES</fullName>
                </value>
                <value>
                    <fullName>GLOBAL RELATIONS</fullName>
                </value>
                <value>
                    <fullName>GLOBAL RELATIONS IND</fullName>
                </value>
                <value>
                    <fullName>GLOBAL RELATIONS WHSE</fullName>
                </value>
                <value>
                    <fullName>IAG IND</fullName>
                </value>
                <value>
                    <fullName>IAG RIA</fullName>
                </value>
                <value>
                    <fullName>IND ADV GRP</fullName>
                </value>
                <value>
                    <fullName>OVERLAY</fullName>
                </value>
                <value>
                    <fullName>RETIREMENT</fullName>
                </value>
                <value>
                    <fullName>RIA FIDUCIARY</fullName>
                </value>
                <value>
                    <fullName>RIA PLATFORM</fullName>
                </value>
                <value>
                    <fullName>SUB ADV</fullName>
                </value>
                <value>
                    <fullName>WIREHOUSE</fullName>
                </value>
                <value>
                    <fullName>ADU</fullName>
                </value>
                <value>
                    <fullName>IDU</fullName>
                </value>
                <value>
                    <fullName>RCDU</fullName>
                </value>
                <value>
                    <fullName>RADU</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FocusFirmFS__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Target for delete; Focus Firm for Fiduciary Services</description>
        <label>Focus Firm FS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FocusFirmIAG__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Target for delete; focus firm for IAG</description>
        <label>Focus Firm IAG</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FocusFirmRS__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Target for delete; focus firm for RS</description>
        <label>Focus Firm RS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FocusFirmWHSE__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Target for delete; focus firm for Wirehouse</description>
        <label>Focus Firm WHSE</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ActivityContact__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Activity Contacts</relationshipLabel>
        <relationshipName>Activity_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by the trigger from Task.OwnerChannelId__c (=Owner:User.ActivityChannelId__c)</description>
        <label>Channel</label>
        <referenceTo>Channel__c</referenceTo>
        <relationshipLabel>Activity Contacts</relationshipLabel>
        <relationshipName>Activity_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is entered through the Gridbuddy Form and is set to the id of the contact entered through the form. It is used by the trigger to create the TaskRelation entry to the related Task</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Activity Contacts</relationshipLabel>
        <relationshipName>ActivityContacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Owner_Channel__c</fullName>
        <description>This field shows the current Task / ActivityContact__c owner Channel, which could be different from the Channel of the Owner at the time the activity was created</description>
        <formula>Owner:User.ActivityChannelName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Owner Channel</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OwnerChannelId__c</fullName>
        <formula>Owner:User.ActivityChannelId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Owner Channel Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OwnerCurrentTerritory__c</fullName>
        <formula>Owner:User.ActivityTerritoryName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Owner Current Territory</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OwnerCurrentZoneId__c</fullName>
        <formula>Owner:User.ActivityZoneId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Owner Current Zone Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RepCurrentBPLStatus__c</fullName>
        <formula>Contact__r.BPL__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rep Current BPL Status</label>
        <type>Checkbox</type>
    </fields>
    <description>Each activity will have 1 to Many contacts. These activity related contacts are stored in this object along necessary attributes to allow for advanced activity reporting. This Table is synched up with the TaskRelation standard object through the "ActivityContactTrigger" trigger and the "ActivityContactTriggerHandler" Class.
This object is "virtually" related to Task through the use of the "ActivityId__c" field. This fake Id field is binded to Task through the use of the "Contacts" Grid build in the GridBuddy application.</description>
    <label>Activity Contact</label>
    <nameField>
        <displayFormat>AC-{0000000000}</displayFormat>
        <label>Activity Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Contacts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>BPL__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Source: Updates will be made on a quarterly basis and submitted by sales to john Scuzzarella and then we bulk update</description>
        <inlineHelpText>Indicates that the Rep/Contact is at a Top 200</inlineHelpText>
        <label>Top 200 Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <description>Wells FA data in Salesforce requested by Joseph Labresh. This field labels each FA by what channel they work in: “PCG”, “WBS”, and “Finet”.</description>
        <inlineHelpText>This field is about Wells FA data, it labels each FA by what channel they work in: “PCG”, “WBS”, and “Finet”.</inlineHelpText>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PCG</fullName>
                </value>
                <value>
                    <fullName>WBS</fullName>
                </value>
                <value>
                    <fullName>FiNet</fullName>
                </value>
                <value>
                    <fullName>RIA Hybrid</fullName>
                </value>
                <value>
                    <fullName>Independent</fullName>
                </value>
                <value>
                    <fullName>Bank</fullName>
                </value>
                <value>
                    <fullName>RIA IFA Advisor</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Licensed Branch Employee</fullName>
                </value>
                <value>
                    <fullName>Insurance Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FocusFirmFS__c</fullName>
        <description>Custom field no longer used</description>
        <formula>Account.Parent.FocusFirmFS__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Focus Firm FS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FocusFirmIAG__c</fullName>
        <description>Custom field no longer used</description>
        <formula>Account.Parent.FocusFirmIAG__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Focus Firm IAG</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FocusFirmRS__c</fullName>
        <description>Custom field no longer used</description>
        <formula>Account.Parent.FocusFirmRS__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Focus Firm RS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FocusFirmWHSE__c</fullName>
        <description>Custom field no longer used</description>
        <formula>Account.Parent.FocusFirmWHSE__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Focus Firm WHSE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PROTierFS__c</fullName>
        <description>N/A No longer used.</description>
        <inlineHelpText>1=Top Producer, 8 activities per year 
2=Elevate, 6 activities per year 
3=Potential to elevate based on capacity, 2+ activities per year 
DNC=Do Not Call 
P=Prospect 
T=Team, Tier 1,2,3 but not the person you talk to</inlineHelpText>
        <label>Tier FS</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>DNC</fullName>
                </value>
                <value>
                    <fullName>P</fullName>
                </value>
                <value>
                    <fullName>T</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PROTierIAG__c</fullName>
        <description>N/A No longer used.</description>
        <inlineHelpText>1=Top Producer, 8 activities per year 
2=Elevate, 6 activities per year
3=Potential to elevate based on capacity, 2+ activities per year
DNC=Do Not Call
P=Prospect
T=Team, Tier 1,2,3 but not the person you talk to</inlineHelpText>
        <label>Tier IAG</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>DNC</fullName>
                </value>
                <value>
                    <fullName>P</fullName>
                </value>
                <value>
                    <fullName>T</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PROTierWHSE__c</fullName>
        <description>N/A No longer used.</description>
        <inlineHelpText>1=Top Producer, 8 activities per year 
2=Elevate, 6 activities per year
3=Potential to elevate based on capacity, 2+ activities per year
DNC=Do Not Call
P=Prospect
T=Team, Tier 1,2,3 but not the person you talk to</inlineHelpText>
        <label>Tier Wirehouse</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>DNC</fullName>
                </value>
                <value>
                    <fullName>P</fullName>
                </value>
                <value>
                    <fullName>T</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PROZoneFS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>N/A No longer used. Previously used to carve out bigger territories.</description>
        <label>Zone FS</label>
        <referenceTo>Zone__c</referenceTo>
        <relationshipLabel>Contacts (Zone FS)</relationshipLabel>
        <relationshipName>Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PROZoneIAG__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>N/A No longer used. Previously used to carve out bigger territories.</description>
        <label>Zone IAG</label>
        <referenceTo>Zone__c</referenceTo>
        <relationshipLabel>Contacts (Zone IAG)</relationshipLabel>
        <relationshipName>Contacts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PROZoneWHSE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>N/A No longer used. Previously used to carve out bigger territories.</description>
        <label>Zone Wirehouse</label>
        <referenceTo>Zone__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TaskUpdateBatch.cls
global class TaskUpdateBatch implements Database.Batchable<sObject>, Database.Stateful{

    public integer CScount = 0;
    // 'Select id, Current_Owner_Channel__c, OwnerCurrentTerritory__c, OwnerCurrentZoneId__c, RepCurrentBPLStatus__c, contact__r.BPL__c, Account__r.Parent.FocusFirmFS__c, Account__r.Parent.FocusFirmIAG__c, Account__r.Parent.FocusFirmRS__c, Account__r.Parent.FocusFirmWHSE__c, Contact__r.PROTierFS__c, Contact__r.PROTierIAG__c, Contact__r.PROTierRS__c, Contact__r.PROTierWHSE__c, Contact__r.PROZoneFS__c, Contact__r.PROZoneIAG__c, Contact__r.PROZoneRS__c, Contact__r.PROZoneWHSE__c, OwnerChannelId__c from ActivityContact__c ';
	public String query ;
    public static Map<id,Channel__c> ChannelMap {
          get {
               if (ChannelMap == null) {
                    ChannelMap = new Map<id,Channel__c>([Select Id, Name, TierField__c, ZoneField__c, FocusFirmField__c from Channel__c limit 20]);
                    }
               return ChannelMap;
          }
          set;
     } 

    global Database.querylocator start(Database.BatchableContext BC){   
            return Database.getQueryLocator(query);
    		}

   	global void execute(Database.BatchableContext BC, List<ActivityContact__c> scope)
   			{ 
            List<ActivityContact__c> reprocessedACs = new List<ActivityContact__c>();
                
            for (ActivityContact__c curAC : scope)
            	{
                CScount = CScount + 1;
                ActivityContact__c reprocessedAC = new ActivityContact__c(); 
                
                reprocessedAC.id = curAC.Id;  
                reprocessedAC.OwnerChannel__c = curAC.Current_Owner_Channel__c;   
                reprocessedAC.Channel__c = curAC.OwnerChannelId__c;
				reprocessedAC.OwnerTerritory__c = curAC.OwnerCurrentTerritory__c;
				reprocessedAC.OwnerZone__c = curAC.OwnerCurrentZoneId__c;
				reprocessedAC.RepBPL__c = curAC.RepCurrentBPLStatus__c;              

               	String UserPrimaryChannelId = '';
               	UserPrimaryChannelId = curAC.OwnerChannelId__c;
               	String FieldName = '';
               if (UserPrimaryChannelId <> null)   
                      {        
                       FieldName = (String)ChannelMap.get(UserPrimaryChannelId).FocusFirmField__c; 
                       if (FieldName <> null)   
                            {  
                            reprocessedAC.ChannelFocusFirm__c = (Boolean)curAC.getSobject('Account__r').getSobject('Parent').get(FieldName);
                            } 
                       FieldName = (String)ChannelMap.get(UserPrimaryChannelId).TierField__c; 
                       if (FieldName <> null)   
                            {  
                            reprocessedAC.RepTier__c = (String)curAC.getSobject('Contact__r').get(FieldName);
                            } 
                       FieldName = (String)ChannelMap.get(UserPrimaryChannelId).ZoneField__c; 
                       if (FieldName <> null)   
                            {  
                            reprocessedAC.RepZone__c = (ID)curAC.getSobject('Contact__r').get(FieldName);
                            } 
                       }   
               reprocessedACs.add(reprocessedAC);   
               } 

		if (!reprocessedACs.isEmpty())
        		{
           		update reprocessedACs;
           		}  
           }
    
	global void finish(Database.BatchableContext BC)
			{
            /*try{
			Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
			String[] toAddresses = new String[] {'dat@ngam.natixis.com'};
			mail.setToAddresses(toAddresses);
			mail.setReplyTo('dat@ngam.natixis.com');
			mail.setSenderDisplayName('DAT');
			mail.setSubject('ActivityContact__c processing Completed');
			mail.setPlainTextBody('ActivityContact__c processed: ' + CSCount + '\n\nSOQL source :' + query);
          if (!Test.IsRunningTest())  Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail }); 
           }
           catch (Exception e) {
           System.debug('Exception: ' + e);            
           }  */  
         }
 
}