objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>The MARS status of the account, Data Flow: Mars -&gt; SF</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Source: MARS na_load_rep.StatCd
Loaded by a nightly job.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ExternalCommunitySettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To the custom setting for external communities</description>
    <label>ExternalCommunitySettings</label>
</CustomObject>

objects/FinancialAccount__c.object
<CustomObject>
    <fields>
        <fullName>ViewableinCommunity__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If checked, this Financial Account can be viewed in Community</description>
        <inlineHelpText>If checked, this Financial Account can be viewed in Community</inlineHelpText>
        <label>Viewable in Community</label>
        <type>Checkbox</type>
    </fields>
    <description>Used in community to display Financial Account data to community users.  This object's data is sourced from Data Central and maintained via integration.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/FinancialAccountContact__c.object
<CustomObject>
    <fields>
        <fullName>ContactName__c</fullName>
        <formula>Contact__r.LastName &amp; ", " &amp; Contact__r.FirstName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact related to the Financial Account</description>
        <inlineHelpText>Contact related to the Financial Account</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Financial Account Contact</relationshipLabel>
        <relationshipName>Financial_Account_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Indicates the status of the contact's relationship to the Financial Account</description>
        <inlineHelpText>Indicate the status of the contact's relationship to the Financial Account</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                    <default>true</default>
                    <label>Current</label>
                </value>
                <value>
                    <fullName>Former</fullName>
                </value>
                <value>
                    <fullName>Inactivated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Indicates the type of relationship this contact has to the Financial Account</description>
        <inlineHelpText>Indicate the type of relationship this contact has to the Financial Account</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>End Client</fullName>
                </value>
                <value>
                    <fullName>Financial Advisor</fullName>
                    <default>true</default>
                    <label>Financial Advisor</label>
                </value>
                <value>
                    <fullName>Interested 3rd Party</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>View_Financial_Account_in_Community__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates if this contact should see the Financial Account in the community.</description>
        <inlineHelpText>If checked, the contact will be able to see the Financial Account in the community</inlineHelpText>
        <label>View Financial Account in Community?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <description>Financial Account to which this contact is related</description>
        <inlineHelpText>Financial Account to which this contact is related</inlineHelpText>
        <label>Financial Account</label>
        <referenceTo>FinancialAccount__c</referenceTo>
        <relationshipLabel>Financial Account Contact</relationshipLabel>
        <relationshipName>Financial_Account_Contact</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <description>Tracks contacts associated with a Financial Account.  Dictates which contacts (community users) can see a particular Financial Account in the community.</description>
    <label>Financial Account Contact</label>
    <nameField>
        <displayFormat>FAC-{000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Used in the Affiliate Request Flow to filter 'Requested on Behalf' of. Can not use Out of Box field for end users.</description>
        <formula>IF( IsActive = True, True, False)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/FinancialAccountTriggerHandler.cls
public without sharing class FinancialAccountTriggerHandler {
    
    static ExternalCommunitySettings__c myCustomSetting = ExternalCommunitySettings__c.getValues('EstatementCommunity');    
  
    public static void TriggerAfterUpdate (  Map<Id,FinancialAccount__c> myNewFA, Map<Id,FinancialAccount__c> myOldFA) { 
         
      
         for( Id fa :myNewFA.keySet())
        { 
            FinancialAccount__c newValue = myNewFA.get(fa);
            if(myOldFA.containsKey(fa))
               {
                   FinancialAccount__c oldValue = myOldFA.get(fa);
                   if(oldValue.ViewableinCommunity__c !=  newValue.ViewableinCommunity__c)
                   {
                       if(newValue.ViewableinCommunity__c == false)
                       {
                           // remove all the manual sharing
                          system.debug ('-----------------------delete shate' + fa ); 
                          List<FinancialAccount__Share> sharesToDelete =
                          [SELECT Id, ParentId, UserOrGroupId, AccessLevel, RowCause, LastModifiedDate, LastModifiedById, IsDeleted 
                           FROM FinancialAccount__Share where ParentID=:fa and RowCause='Manual' ];
                          delete sharesToDelete;
                           
                       }
                       else
                       {
                               if(newValue.ViewableinCommunity__c == true)
                           {
                               // add all the sharing for Finacial account contact
                                Map<Id,FinancialAccountContact__c> clients = new Map<Id,FinancialAccountContact__c>([ SELECT Id, Name, Contact__r.Name, 
                                                                                                     Contact__r.Id, Financial_Account__c,
                                                                                                     Contact__c, 
                                                                                                     Type__c, Status__c, 
                                                                                                     View_Financial_Account_in_Community__c,
                                                                                                     ContactName__c 
                                                                                                     From  FinancialAccountContact__c 
                                                                                                     where Financial_Account__c=:fa
                                                                                                     and Status__c = 'Current' and View_Financial_Account_in_Community__c = true]);
                                List<Id> ContactList = new List<Id>();
                                for( FinancialAccountContact__c c :clients.values())
                                    { 
                                        ContactList.add(c.Contact__c);
                                    }
                               
                               List<User> users = [SELECT Id, Username, LastName, FirstName, Name, ContactId, AccountId, PortalRole, IsPortalEnabled FROM User
                                    where  ContactId=:ContactList
                                                  ];
                               // Create Share
                                 CreateShare(users,fa) ;                                                                                  
                           }
                       }
                   }
               }
               
        }
    }
//    
   
    public static void CreateShare(List<User> UserList, String AccountId){   
        system.debug ('-----------------------Create share user' + AccountId ); 
        List<FinancialAccount__Share> sharesToCreate = new List<FinancialAccount__Share>();
         for( User u :UserList)
        { 

        FinancialAccount__Share cs = new FinancialAccount__Share();
        
        cs.AccessLevel = 'Read';
        cs.ParentID = AccountId;
        cs.RowCause =Schema.FinancialAccount__Share.RowCause.Manual;
        cs.UserOrGroupId = u.Id;
        sharesToCreate.add(cs);   
        
        }
        
        if(!sharesToCreate.isEmpty())
        {
            upsert  sharesToCreate;
        }
    }
   
}