objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>The MARS status of the account, Data Flow: Mars -&gt; SF</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Source: MARS na_load_rep.StatCd
Loaded by a nightly job.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ExternalCommunitySettings__c.object
<CustomObject>
    <fields>
        <fullName>EndClientCommunityAccountName__c</fullName>
        <description>The name of the Account (Firms Office) to which End Client/Interested 3rd Party community contacts will belong.</description>
        <inlineHelpText>The name of the Account (Firms Office) to which new End Client/Interested 3rd Party community contacts belong.  This should always be NGAM DISTRIBUTION, L.P., PORTAL END CLIENTS</inlineHelpText>
        <label>EndClientCommunityAccountName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InactivateDaysForUserLogin__c</fullName>
        <defaultValue>180</defaultValue>
        <description>Inactivate the users after x numbers of days</description>
        <inlineHelpText>Users that have not logged in after this number of days are inactivated in a nightly batch job.</inlineHelpText>
        <label>InactivateDaysForUserLogin</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PemissionSetForEndClient__c</fullName>
        <description>Permission set for end user, Comma delimited string wth permission set's api names</description>
        <inlineHelpText>Permission Set that is assigned to End Client contact user records during setup of Financial Account Contact (type = End Client).</inlineHelpText>
        <label>PemissionSetForEndClient</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PermissionSetsForFAUser__c</fullName>
        <description>Permission set for FA user</description>
        <inlineHelpText>Permission Set that is assigned to Financial Advisor contact user records during setup of Financial Account Contact (type = Financial Advisor).</inlineHelpText>
        <label>PermissionSetsForFAUser</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PotalUserName__c</fullName>
        <description>Portal user name</description>
        <label>PotalUserName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProfileForEndClient__c</fullName>
        <description>profile for end client or 3 party</description>
        <inlineHelpText>Profile that is assigned to End Client contact user records during setup of Financial Account Contact (type = End Client).</inlineHelpText>
        <label>ProfileForEndClient</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProfileForFAUser__c</fullName>
        <description>Profile name for FA</description>
        <inlineHelpText>Profile that is assigned to Financial Advisor contact user records during setup of Financial Account Contact (type = Financial Advisor).</inlineHelpText>
        <label>ProfileForFAUser</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>To the custom setting for external communities</description>
    <label>ExternalCommunitySettings</label>
</CustomObject>

objects/FinancialAccount__c.object
<CustomObject>
    <description>Used in community to display Financial Account data to community users.  This object's data is sourced from Data Central and maintained via integration.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/FinancialAccountContact__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact related to the Financial Account</description>
        <inlineHelpText>Contact related to the Financial Account</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Financial Account Contact</relationshipLabel>
        <relationshipName>Financial_Account_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Indicates the status of the contact's relationship to the Financial Account</description>
        <inlineHelpText>Indicate the status of the contact's relationship to the Financial Account</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                    <default>true</default>
                    <label>Current</label>
                </value>
                <value>
                    <fullName>Former</fullName>
                </value>
                <value>
                    <fullName>Inactivated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Tracks contacts associated with a Financial Account.  Dictates which contacts (community users) can see a particular Financial Account in the community.</description>
    <label>Financial Account Contact</label>
    <nameField>
        <displayFormat>FAC-{000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/NGAMSettingsHierarchy__c.object
<CustomObject>
    <fields>
        <fullName>ByPassAccountValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows entity to by-pass validation rules on Account</description>
        <inlineHelpText>Allows entity to by-pass validation rules on Account</inlineHelpText>
        <label>By-Pass Account Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NGAM Settings - Hierarchy</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>CommunityStatus__c</fullName>
        <description>For community users who have been inactivated, this field contains the reason for inactivation.  If the user is active, it contains "Active".</description>
        <inlineHelpText>For community users who have been inactivated, this field contains the reason for inactivation.  If the user is active, it contains "Active".</inlineHelpText>
        <label>Community Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Used in the Affiliate Request Flow to filter 'Requested on Behalf' of. Can not use Out of Box field for end users.</description>
        <formula>IF( IsActive = True, True, False)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TermsandConditionsLastDeclined__c</fullName>
        <description>Datetime stamp set each time a community user declines the Terms and Conditions.</description>
        <inlineHelpText>Datetime stamp set each time a community user declines the Terms and Conditions.</inlineHelpText>
        <label>Terms and Conditions Last Declined</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>UserID__c</fullName>
        <defaultValue>"Populate This Field"</defaultValue>
        <externalId>true</externalId>
        <label>UserID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CommunitiesInactivateUserBatch_Test.cls
@isTest
public class CommunitiesInactivateUserBatch_Test {
    
    @testSetup static void SetupTest() {
    
        NGAMSettingsHierarchy__c hsettings = NGAMSettingsHierarchy__c.getOrgDefaults();
        hsettings.ByPassAccountValidationRules__c  = TRUE;
        upsert hsettings NGAMSettingsHierarchy__c.Id;

    
        DataFactory.CreateNGAMCustomSettings(); 
        DataFactory.insertEstatementCommunityCustomSettings();
        List<Account> myAccounts = DataFactory.createTestAccounts(3);
        insert myAccounts;
        
        Id ECRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('End Client').getRecordTypeId();
        
        List<Contact> myContacts = DataFactory.createTestContacts(3, myAccounts, false);
        List<Contact> contacts = new List<Contact>();
        List<Contact> contactsWithFAC = new List<Contact>();
        
        myContacts[0].RecordTypeId = ECRecordTypeId;
        myContacts[0].LastName = 'Test for T&C';
        
        myContacts[1].RecordTypeId = ECRecordTypeId;
        myContacts[1].LastName = 'Test for remain Active';    
        
        myContacts[2].RecordTypeId = ECRecordTypeId;
        myContacts[2].LastName = 'Test for No Fin Accounts';
        
        insert myContacts;
        system.debug('myContacts 1 ID: ' + myContacts[1].Id);
        
        contactsWithFAC.add(myContacts[0]);        
        contactsWithFAC.add(myContacts[1]);
        
        List<FinancialAccount__c> faList =  DataFactory.createFinancialAccounts(1) ;
        insert faList;
        
        List<FinancialAccountContact__c> facList = DataFactory.createFinancialAccountContacts(faList,contactsWithFAC);
        insert facList;
        system.debug('facList: ' + facList);
        
    }
    
    
    static testMethod void CommunitiesInactivateUserBatchTesting() {
        
        ExternalCommunitySettings__c myCustomSetting = ExternalCommunitySettings__c.getValues('EstatementCommunity');
        string EStatementFirmName = myCustomSetting.EndClientCommunityAccountName__c;
        string PortalUserName = myCustomSetting.PotalUserName__c;
        string PermissionSetForEndClient =   myCustomSetting.PemissionSetForEndClient__c;
        String ProfileForEndClient = myCustomSetting.ProfileForEndClient__c;
        string ProfileForFAUser =  myCustomSetting.ProfileForFAUser__c;
        String PermissionSetsForFAUser = myCustomSetting.PermissionSetsForFAUser__c;
        Integer InactivateDaysForUserLogin = (Integer)myCustomSetting.InactivateDaysForUserLogin__c;
        Map<String,Id> profPermSetIdMap = new Map<String,Id>();
        PermissionSet FAPS = [SELECT Name, Id FROM PermissionSet WHERE name=:PermissionSetsForFAUser LIMIT 1];
        PermissionSet ECPS = [SELECT Name, Id FROM PermissionSet WHERE name=:PermissionSetForEndClient LIMIT 1];
        Profile FAProfile = [SELECT Name, Id FROM Profile WHERE name=:ProfileForFAUser LIMIT 1];  
        Profile EndClientProfile = [SELECT Name, Id FROM profile WHERE name=:ProfileForEndClient LIMIT 1]; 
        profPermSetIdMap.put(FAProfile.Name, FAProfile.Id);
        profPermSetIdMap.put(EndClientProfile.Name, EndClientProfile.Id);
        profPermSetIdMap.put(FAPS.Name, FAPS.Id);
        profPermSetIdMap.put(ECPS.Name, ECPS.Id);
        
        Profile p = [select id from profile where name='System Administrator']; 
        UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        User u2 = new User(alias = 'standt', email='SFDCadmin@ngam.natixis.com', 
                           UserRoleId = portalRole.Id,
                           emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
                           localesidkey='en_US', profileid = p.Id,
                           isActive = TRUE,
                           timezonesidkey='America/Los_Angeles', username='SFDCadmin@ngam.natixis.com',UserID__c='SFDCadmin');
        
        System.runAs(u2) 
        {
            Profile UserProfile = [select id from profile where name = :ProfileForEndClient];
            Contact conCU1 = [SELECT id, FirstName, LastName from Contact WHERE LastName = 'Test for T&C' LIMIT 1];
            Contact conCU2 = [SELECT id, FirstName, LastName from Contact WHERE LastName = 'Test for remain Active' LIMIT 1];
            Contact conCU3 = [SELECT id, FirstName, LastName from Contact WHERE LastName = 'Test for No Fin Accounts' LIMIT 1];
            
            List<User> users = new List<User>(); 
            User communityUser1 = new User(contactId=conCU1.Id,
                                           username='Email@emal.com.crmstage123', 
                                           firstname=conCU1.FirstName,
                                           lastname=conCU1.LastName, 
                                           email= 'Email@emal.com.crmstage',
                                           communityNickname = 'uesrid123456',
                                           alias = 'uesrid43', 
                                           UserID__c  = 'uesrid43', 
                                           profileid =UserProfile.Id, 
                                           emailencodingkey='UTF-8',
                                           languagelocalekey='en_US', 
                                           localesidkey='en_US', 
                                           timezonesidkey='America/Los_Angeles',
                                           CommunityStatus__c = 'Active',
                                           TermsandConditionsLastDeclined__c =  System.now());  
            users.add(communityUser1);
            
            User communityUser2 = new User(contactId=conCU2.Id,
                                           username='Email@emal.com.crmstage1234', 
                                           firstname=conCU2.FirstName,
                                           lastname=conCU2.LastName, 
                                           email= 'Email@emal.com.crmstage',
                                           communityNickname = 'uesrid123',
                                           alias = 'uesrid4', 
                                           UserID__c  = 'uesrid4', 
                                           profileid =UserProfile.Id, 
                                           emailencodingkey='UTF-8',
                                           languagelocalekey='en_US', 
                                           localesidkey='en_US', 
                                           timezonesidkey='America/Los_Angeles',
                                           CommunityStatus__c = 'Active');  
            users.add(communityUser2);
            
            User communityUser3 = new User(contactId=conCU3.Id,
                                           username='Email@emal.com.crmstageX', 
                                           firstname=conCU3.FirstName,
                                           lastname=conCU3.LastName, 
                                           email= 'Email@emal.com.crmstage',
                                           communityNickname = 'uesridX',
                                           alias = 'uesridX', 
                                           UserID__c  = 'uesridX', 
                                           profileid =UserProfile.Id, 
                                           emailencodingkey='UTF-8',
                                           languagelocalekey='en_US', 
                                           localesidkey='en_US', 
                                           timezonesidkey='America/Los_Angeles',
                                           CommunityStatus__c = 'Active');  
            users.add(communityUser3);
            insert users;
            
            List<PermissionSetAssignment> permSetToAssign = New List<PermissionSetAssignment>();
            
            PermissionSetAssignment permassign1 = new PermissionSetAssignment(PermissionSetId = profPermSetIdMap.get(PermissionSetForEndClient), AssigneeId=communityUser1.Id);
            PermissionSetAssignment permassign2 = new PermissionSetAssignment(PermissionSetId = profPermSetIdMap.get(PermissionSetForEndClient), AssigneeId=communityUser2.Id);
            permSetToAssign.add(permassign1);            
            permSetToAssign.add(permassign2);
            insert permSetToAssign;            
            
            Test.startTest(); 
            System.Debug(' ########## -Test Started ');
            CommunitiesInactivateUserBatch usersBtach = new CommunitiesInactivateUserBatch();
            usersBtach.execute(null, users) ;
            ID tracid = database.executeBatch(usersBtach,2000); 
            System.Debug(' ########## -Test Ended ');
            Test.stopTest();
            
            User cu1 = [SELECT Id, IsActive, CommunityStatus__c FROM User WHERE ContactId =: conCU1.Id LIMIT 1];
            User cu2 = [SELECT Id, IsActive, CommunityStatus__c FROM User WHERE ContactId =: conCU2.Id LIMIT 1];
            User cu3 = [SELECT Id, IsActive, CommunityStatus__c FROM User WHERE ContactId =: conCU3.Id LIMIT 1];
            
            List<FinancialAccountContact__c> activeCU1 = [SELECT Id FROM FinancialAccountContact__c 
                                                          WHERE Contact__c =: conCU1.Id 
                                                          AND Status__c != 'Inactivated'];
            
            List<FinancialAccountContact__c> activeCU2 = [SELECT Id FROM FinancialAccountContact__c 
                                                          WHERE Contact__c =: conCU2.Id 
                                                          AND Status__c != 'Inactivated'];
            
            List<FinancialAccountContact__c> activeCU3 = [SELECT Id FROM FinancialAccountContact__c 
                                                          WHERE Contact__c =: conCU3.Id 
                                                          AND Status__c != 'Inactivated'];
            
            
            system.assertEquals(cu1.IsActive,FALSE);
            system.assertEquals(cu1.CommunityStatus__c,'Inactive: Declined Terms and Conditions');
            system.assertEquals(activeCU1.size(),0);
            
            system.assertEquals(cu2.IsActive,TRUE);
            system.assertEquals(cu2.CommunityStatus__c,'Active');
            system.assertNotEquals(activeCU2.size(),0);
            
            system.assertEquals(cu3.IsActive,FALSE);
            system.assertEquals(cu3.CommunityStatus__c,'Inactive: No Financial Accounts');            
            system.assertEquals(activeCU3.size(),0);            
            
        }        
    }
}