objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>The MARS status of the account, Data Flow: Mars -&gt; SF</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Source: MARS na_load_rep.StatCd
Loaded by a nightly job.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VestmarkEmail__c</fullName>
        <description>This field store the email address of the FA in VestMark system and used for Estatement project</description>
        <inlineHelpText>This field store the email address of the FA in VestMark system.</inlineHelpText>
        <label>Vestmark Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ExternalCommunitySettings__c.object
<CustomObject>
    <fields>
        <fullName>BatchJobCCemails__c</fullName>
        <description>Additional emails addresses for statement notify batch jobs , separated by ; ( semicolon)</description>
        <inlineHelpText>Additional emails addresses for statement notify batch jobs , separated by ; ( semicolon)</inlineHelpText>
        <label>BatchJobCCemails</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BatchNotifyFAJobNumberOfDays__c</fullName>
        <description>BatchNotifyFAJobNumberOfDays  - number of days for FA  to include in the query.  Used in CommunitiesNotifyNewStatementsBatch.apxc</description>
        <inlineHelpText>FA's and End Clients will be notified of files created within the last 'n' days.  Since we run the batch job nightly, this should be set to 1.  If we run the batch job weekly, it should be set to 7.</inlineHelpText>
        <label>BatchNotifyFAJobNumberOfDays</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BatchNotifyFASendAllorNone__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When submitting the emails for delivery, if this flag is true then whole batch is submitted but in case error in any submission in any email nothing will be submitted. 
If this flag is false then individual errors would not impact the whole batch.</description>
        <inlineHelpText>When submitting the emails for delivery, if this flag is true then whole batch is submitted but in case error in any submission in any email nothing will be submitted. If this flag is false then individual errors would not impact the whole batch.</inlineHelpText>
        <label>BatchNotifyFASendAllorNone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CommunityInternalSender__c</fullName>
        <description>To addresses for Batch jobs</description>
        <inlineHelpText>Determines the email address that batch completion emails should go to.  This should be dat@ngam.natixis.com unless you are testing.</inlineHelpText>
        <label>CommunityInternalSender</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CommunitySenderDisplayName__c</fullName>
        <description>CommunitySenderDisplayName for emails.  Necessary for sending the notification that new statements have been posted.</description>
        <inlineHelpText>Indicates the email from name on the notification to FA's that new statements have been posted.  This should always be Portal Solutions unless branding changes.</inlineHelpText>
        <label>CommunitySenderDisplayName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CommunitySenderEmail__c</fullName>
        <description>Email for sending the comunity email</description>
        <inlineHelpText>Indicates the email from address on the notification to FA's that new statements have been posted. This should always be Portal Solutions unless branding changes</inlineHelpText>
        <label>CommunitySenderEmail</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndClientCommunityAccountName__c</fullName>
        <description>The name of the Account (Firms Office) to which End Client/Interested 3rd Party community contacts will belong.</description>
        <inlineHelpText>The name of the Account (Firms Office) to which new End Client/Interested 3rd Party community contacts belong.  This should always be NGAM DISTRIBUTION, L.P., PORTAL END CLIENTS</inlineHelpText>
        <label>EndClientCommunityAccountName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExternalEmailTemplate__c</fullName>
        <description>Email's template developer name use for sending the emails to EndClient</description>
        <inlineHelpText>The email template used for notifying community users of new statements.</inlineHelpText>
        <label>ExternalEmailTemplateDevName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PemissionSetForEndClient__c</fullName>
        <description>Permission set for end user, Comma delimited string wth permission set's api names</description>
        <inlineHelpText>Permission Set that is assigned to End Client contact user records during setup of Financial Account Contact (type = End Client).</inlineHelpText>
        <label>PemissionSetForEndClient</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PermissionSetsForFAUser__c</fullName>
        <description>Permission set for FA user</description>
        <inlineHelpText>Permission Set that is assigned to Financial Advisor contact user records during setup of Financial Account Contact (type = Financial Advisor).</inlineHelpText>
        <label>PermissionSetsForFAUser</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PotalUserName__c</fullName>
        <description>Portal user name</description>
        <label>PotalUserName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProfileForFAUser__c</fullName>
        <description>Profile name for FA</description>
        <inlineHelpText>Profile that is assigned to Financial Advisor contact user records during setup of Financial Account Contact (type = Financial Advisor).</inlineHelpText>
        <label>ProfileForFAUser</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>To the custom setting for external communities</description>
    <label>ExternalCommunitySettings</label>
</CustomObject>

objects/FinancialAccount__c.object
<CustomObject>
    <fields>
        <fullName>AccountNameEncrypted__c</fullName>
        <description>Unique Vestmark Account name</description>
        <inlineHelpText>Unique Vestmark Account name</inlineHelpText>
        <label>Account Name</label>
        <length>30</length>
        <maskChar>X</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>AccountShortName__c</fullName>
        <description>Integration: NTXS_CUST_ACCOUNTS.Account_Short_Name</description>
        <inlineHelpText>Short name of the account</inlineHelpText>
        <label>Account Short Name</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountTitleEncrypted__c</fullName>
        <description>Integration: NTXS_CUST_ACCOUNTS.Account_Title</description>
        <inlineHelpText>Legal title of the account</inlineHelpText>
        <label>Account Title</label>
        <length>175</length>
        <maskChar>X</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>AccountType__c</fullName>
        <description>Integration: NTXS_CUST_ACCOUNTS</description>
        <inlineHelpText>Account Type (e.g. Standard, Model, user-defined)</inlineHelpText>
        <label>Account Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndClients__c</fullName>
        <description>Concatenated field of all End Clients with Status = Current in Financial Account Contact.  Maintained by Rollup Summaries.</description>
        <inlineHelpText>Concatenated field of all current End Clients in Financial Account Contact.</inlineHelpText>
        <label>End Client(s)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <description>Used in community to display Financial Account data to community users.  This object's data is sourced from Data Central and maintained via integration.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/FinancialAccountContact__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact related to the Financial Account</description>
        <inlineHelpText>Contact related to the Financial Account</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Financial Account Contact</relationshipLabel>
        <relationshipName>Financial_Account_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Indicates the status of the contact's relationship to the Financial Account</description>
        <inlineHelpText>Indicate the status of the contact's relationship to the Financial Account</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                    <default>true</default>
                    <label>Current</label>
                </value>
                <value>
                    <fullName>Former</fullName>
                </value>
                <value>
                    <fullName>Inactivated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <description>Financial Account to which this contact is related</description>
        <inlineHelpText>Financial Account to which this contact is related</inlineHelpText>
        <label>Financial Account</label>
        <referenceTo>FinancialAccount__c</referenceTo>
        <relationshipLabel>Financial Account Contact</relationshipLabel>
        <relationshipName>Financial_Account_Contact</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <description>Tracks contacts associated with a Financial Account.  Dictates which contacts (community users) can see a particular Financial Account in the community.</description>
    <label>Financial Account Contact</label>
    <nameField>
        <displayFormat>FAC-{000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/FinancialAccountFile__c.object
<CustomObject>
    <fields>
        <fullName>DoNotDisplayReason__c</fullName>
        <description>Reason this file should not be displayed to community members</description>
        <inlineHelpText>Reason this file should not be displayed to community members</inlineHelpText>
        <label>Do Not Display Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DoNotDisplayinCommunity__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, this file will not be viewable by community members</description>
        <inlineHelpText>If checked, this file will not be viewable by community members</inlineHelpText>
        <label>Do Not Display in Community</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DocumentDate__c</fullName>
        <description>The effective date of the document.  For example, the Document Date would be 3/31 for a Q2 document even though the file record might have a created date of 4/15.</description>
        <inlineHelpText>The effective date of the document.  For example, the Document Date would be 3/31 for a Q2 document even though the Financial Account File record might have a created date of 4/15.</inlineHelpText>
        <label>Document Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DocumentType__c</fullName>
        <description>The type of document/file that this record represents.</description>
        <inlineHelpText>The type of document/file that this record represents</inlineHelpText>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Quarterly Performance Report</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OriginalFileName__c</fullName>
        <description>Name of the original file as stored on the shared directory.</description>
        <inlineHelpText>Name of the original file as stored on the shared directory.</inlineHelpText>
        <label>Original File Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FinancialAccount__c</fullName>
        <description>The Financial Account to which this file belongs</description>
        <inlineHelpText>The Financial Account to which this file belongs</inlineHelpText>
        <label>Financial Account</label>
        <referenceTo>FinancialAccount__c</referenceTo>
        <relationshipLabel>Financial Account Files</relationshipLabel>
        <relationshipName>FinancialAccountFiles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <description>Used as a "holding object" for files related to Financial Account.  Files are posted to this record rather than directly to the Financial Account record so that we can carry data about the file in the system.  Note, at current development time it was not possible to use API calls to write data about the file to Content object.</description>
    <label>Financial Account File</label>
    <nameField>
        <displayFormat>FAF-{0000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Files</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CommunitiesNotifyNewStatementsBatch.cls
global class CommunitiesNotifyNewStatementsBatch implements Database.Batchable<sObject>, Database.Stateful{
    
    // This Batch job inactivate the users whcih does not any accounts assocuated with them
    Public integer Count = 0;
    
    // Get info from Custom setting
    static ExternalCommunitySettings__c myCustomSetting = ExternalCommunitySettings__c.getValues('EstatementCommunity');
    
    static string EStatementFirmName = myCustomSetting.EndClientCommunityAccountName__c;
    static string PortalUserName = myCustomSetting.PotalUserName__c;
    
    static string PermissionSetForEndClient =   myCustomSetting.PemissionSetForEndClient__c;
    static string ProfileForFAUser =  myCustomSetting.ProfileForFAUser__c;
    static String PermissionSetsForFAUser = myCustomSetting.PermissionSetsForFAUser__c;
    static String EmailSenderAddress = myCustomSetting.CommunitySenderEmail__c;
    static String ExternalEmailTemplateDevName = myCustomSetting.ExternalEmailTemplate__c;  
    static String CommunityInternalSender = myCustomSetting.CommunityInternalSender__c;
    static String CommunitySenderDisplayName = myCustomSetting.CommunitySenderDisplayName__c;
    static String CompareNDays = '1';
    static string CCEmailsAddress = myCustomSetting.BatchJobCCemails__c;
    static Boolean BatchNotifyFASendAllorNone = myCustomSetting.BatchNotifyFASendAllorNone__c;
    public String query = ' SELECT Id, IsDeleted, Name, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, FinancialAccount__c, DoNotDisplayReason__c, DoNotDisplayinCommunity__c, DocumentDate__c, DocumentType__c, OriginalFileName__c FROM FinancialAccountFile__c where DoNotDisplayinCommunity__c != true  and  createddate >= LAST_N_DAYS:@Ndays ';
    
    Public String msg = '';
    
    public Map<String, List<String>> m = new Map<String,  List<String>>();
    
    global CommunitiesNotifyNewStatementsBatch() {
        System.Debug('CommunityNotifyNewStatements - Notify users for new statements');       
        CompareNDays = myCustomSetting.BatchNotifyFAJobNumberOfDays__c;       
        query = query.replace('@Ndays', CompareNDays);
    }
    
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        
        System.Debug('CommunityNotifyNewStatements Synching New Statements Users - Using Query');          
        System.Debug('Query - ' + query);      
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<FinancialAccountFile__c> scope) {
        
        List<String> temp = new List<String>();
        Id emailTemplateId;  
        try {emailTemplateId = [select id, name from EmailTemplate where developername = : ExternalEmailTemplateDevName].id;}
        catch (Exception e) { throw new emailException ('Unable to locate EmailTemplate using name: ' + ExternalEmailTemplateDevName +   ' refer to Setup | Communications Templates ' + ExternalEmailTemplateDevName); }
        
        
        Map<id,List<FinancialAccountFile__c>> FAccountList = new Map<id,List<FinancialAccountFile__c>>();        
        for (FinancialAccountFile__c  c : scope)
        {
            if(!FAccountList.containsKey(c.FinancialAccount__c))
            {
                List<FinancialAccountFile__c> tempList = new List<FinancialAccountFile__c>();
                tempList.Add(c);
                FAccountList.put(c.FinancialAccount__c,tempList);
            }
            else
            {
                List<FinancialAccountFile__c> tempList1 = FAccountList.get(c.FinancialAccount__c);
                tempList1.Add(c);
                FAccountList.remove(c.FinancialAccount__c);
                FAccountList.put(c.FinancialAccount__c,tempList1);
                
            }
        }
        System.Debug('FAccountList - ' + FAccountList.size());   
        for (Id  c : FAccountList.keySet())
        {
            System.Debug('FAccountList - ' + c); 
        }
        // query Fiancial account for new upated files
        Map<id,FinancialAccount__c> FAMaps =  new Map<Id,FinancialAccount__c>([
            SELECT Id, Name,    EndClients__c,  AccountNameEncrypted__c, AccountTitleEncrypted__c, AccountShortName__c, AccountType__c, 
            ( select Contact__r.Id, Contact__r.VestMarkEmail__c, Contact__r.Name,Name from Financial_Account_Contact__r where   Status__c = 'Current'
             and View_Financial_Account_in_Community__c = True ) 
            , ( select Id,Name,DocumentDate__c, DoNotDisplayReason__c,DocumentQuarter__c ,DocumentYear__c from FinancialAccountFiles__r  where DoNotDisplayReason__c != 'true'
              ) 
            FROM FinancialAccount__c where Id in:FAccountList.keySet()] );
        
        Map<id,List<FinancialAccount__c>> emailList = new Map<id,List<FinancialAccount__c>>();
        Map<id,Contact> contactMap = new Map<id,Contact>();
        for (FinancialAccount__c  a : FAMaps.values())
        {
            for (FinancialAccountContact__c fc : a.Financial_Account_Contact__r) 
            {
                if(!contactMap.containsKey(fc.Contact__r.id))
                    contactMap.put(fc.Contact__r.id, fc.Contact__r);
                if(!emailList.containsKey(fc.Contact__r.id))
                {
                    List<FinancialAccount__c> tempList2 = new List<FinancialAccount__c>();
                    tempList2.Add(a);
                    emailList.put(fc.Contact__r.id,tempList2);
                }
                else
                {
                    List<FinancialAccount__c> tempList3 = emailList.get(fc.Contact__r.id);  
                    tempList3.Add(a);  emailList.remove(fc.Contact__r.id);   emailList.put(fc.Contact__r.id,tempList3);
                }
            }
            
        }
        
        Map<id,User> usermap =  new Map<Id,USer>([  SELECT Id, Name, Email ,ContactId FROM User where ContactId in:emailList.keySet()] );  
        List<Messaging.SingleEmailMessage>  emailMessageList = new List<Messaging.SingleEmailMessage>();       
        String TempMsg='';        
        for (Id contactId  : emailList.keySet())
        {
            List<FinancialAccount__c> tempList4 = emailList.get(contactId);
            // compose email msg and send the email          
            for (User  u : usermap.values())
            { 
                if(u.ContactId == contactId)
                {                  
                    List<String> ToAddress = new List<String>();
                    ToAddress.add(u.Email);
                    List<String> CCAddress =null;
                    if(!String.isBlank(CCEmailsAddress)) CCAddress = CCEmailsAddress.split(';');		
                    System.debug('Sending Email to : ' + u.Email);
                    Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                    email.setToAddresses(ToAddress);
                    email.setCcAddresses(CCAddress);
                    email.setTargetObjectId(u.Id);    
                    email.setTemplateId(emailTemplateId);
                    //email.set(FromEmail);
                    email.setReplyTo(EmailSenderAddress);
                    email.setSenderDisplayName(CommunitySenderDisplayName);   
                    email.setSaveAsActivity(false);      // save email as activity on the targetObjId (i.e. Contact). Note activity can't be saved on Users                    
                    System.debug(LoggingLevel.INFO,'** entered sendTemplatedEmail, to:' + ToAddress + ' cc:' + CCAddress +  ' templateId:' + emailTemplateId 
                                 + ' tagetObjId:' + u.Id  + ' FromEmail:' + EmailSenderAddress +  + ' UserId:' + u.Id  );
                    emailMessageList.Add(email);  
                }
            }                       
        }         
        Messaging.SendEmailResult[] results =   CommunitiesEmailHelper.sendTemplatedEmailByList(emailMessageList,BatchNotifyFASendAllorNone);        
        Map<id,String> errorList =  new Map<Id,String>();
        if (results !=  null && results.size() > 0) {
            for (Messaging.SendEmailResult  r : results)
            { 
                if(!r.isSuccess())
                {                   
                    System.Debug('errors - ' + r.getErrors()); 
                    for(Messaging.SendEmailError er :r.getErrors())
                    {
                        if(!errorList.containsKey(er.getTargetObjectId())) errorList.put(er.getTargetObjectId(), er.getMessage());
                        else                        
                            errorList.put(er.getTargetObjectId(), errorList.get(er.getTargetObjectId()) + ' '+  er.getMessage());
                        
                    }
                }
            }                           
        }      
        if (usermap !=  null && usermap.size() > 0) {
            msg = msg + '<p>Sent notification to Community Members, Total Count - ' + usermap.size() +  '</p>';
            //  msg = msg + '<br/><p>Please note that emails were successfully submitted for delivery for this list. It does not mean the intended recipients received the email, as there could have been a problem with the email address or it could have bounced or been blocked by a spam blocker. </p>';
            TempMsg = '<br/><table  border= "1" >';
            TempMsg = TempMsg + '<tr><th> Contact Id </th><th> Contact Name </th><th> Email Sent to </th></tr>';
            for (User  u : usermap.values())
            { 
                if(contactMap.containsKey(u.ContactId))
                    TempMsg = TempMsg + '<tr><td> ' +contactMap.get(u.ContactId).Id + ' </td><td> ' + contactMap.get(u.ContactId).Name + ' </td><td> ' + u.Email + ' </td></tr>';
            }             
            TempMsg = TempMsg + '</table><br/>';
            msg = msg +TempMsg;
        } 
        
        if (errorList !=  null && errorList.size() > 0) {
            msg = '<p>Errors in submitting the emails for delivery: ' + errorList.size() +  '</p>';
            TempMsg = '<br/><table  border= "1" >' + '<tr><th> User Id  </th><th> User Email Address </th><th> Error Msg  </th></tr>';
            for (Id  key : errorList.keySet())
            {               
                if(userMap.containsKey(key)) TempMsg = TempMsg + '<tr><td> ' +key + ' </td><td> ' +  + ' </td>' + userMap.get(key).Email  +'<td> ' +errorList.get(key) + ' </td></tr>'; 
            }
        }
    }
    
    public  Static  void SendFinishEmail(String msg,string subject)
    {
        if (msg != null) {
            List<String> toAddresses = CommunityInternalSender.Split(',');            
            CommunitiesEmailHelper.sendEmail(toAddresses, null, EmailSenderAddress, CommunitySenderDisplayName, msg, subject,true);
        }
    }    
    global void finish(Database.BatchableContext BC) {
        try{
            System.debug('query : ' + query );
            SendFinishEmail(msg,'New Statement Notifications Sent to Community Members');            
        }  
        catch (Exception e) {
            System.debug('CommunityNotifyNewStatements - Exception: ' + e);            
        }        
    }
}