objects/AccountTerritory__c.object
<CustomObject>
    <fields>
        <fullName>AccountTerrId__c</fullName>
        <externalId>true</externalId>
        <label>AccountTerrId</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Territories</relationshipLabel>
        <relationshipName>Account_Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GroupId__c</fullName>
        <formula>Territory__r.GroupId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GroupId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RoleId__c</fullName>
        <formula>Territory__r.RoleId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Role Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Territory__c.RoleId__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Account Territories</relationshipLabel>
        <relationshipName>Account_Territories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <description>Stores the Account Territory assignment records. 
These records are used to drive the AccountShare table and provide visibility to corresponding Roles in the Role Hierarchy.</description>
    <label>Account Territory</label>
    <nameField>
        <displayFormat>AT-{0000000000}</displayFormat>
        <label>Account Territory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Territories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/NGAMSettings__c.object
<CustomObject>
    <fields>
        <fullName>ProfileSystemAdministrator__c</fullName>
        <description>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</description>
        <inlineHelpText>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</inlineHelpText>
        <label>Profile: System Administrator</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Holds the NGAM settings</description>
    <label>NGAM Settings</label>
</CustomObject>

objects/NGAMSettingsHierarchy__c.object
<CustomObject>
    <fields>
        <fullName>ByPassAccountValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows entity to by-pass validation rules on Account</description>
        <inlineHelpText>Allows entity to by-pass validation rules on Account</inlineHelpText>
        <label>By-Pass Account Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NGAM Settings - Hierarchy</label>
</CustomObject>

objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>GroupId__c</fullName>
        <externalId>true</externalId>
        <label>Group Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RoleGroupId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Role Group Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RoleId__c</fullName>
        <externalId>true</externalId>
        <label>Role Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TerritoryName__c</fullName>
        <defaultValue>"Update Me"</defaultValue>
        <externalId>true</externalId>
        <label>MARS Territory Name</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>UserID__c</fullName>
        <defaultValue>"Populate This Field"</defaultValue>
        <externalId>true</externalId>
        <label>UserID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/AccountShareBatch_Test.cls
@isTest
private class AccountShareBatch_Test {
    static testMethod void AccountShareBatchTesting() {
    
        NGAMSettingsHierarchy__c settings = NGAMSettingsHierarchy__c.getOrgDefaults();
        settings.ByPassAccountValidationRules__c  = TRUE;
        upsert settings NGAMSettingsHierarchy__c.Id;


       //Profile p = [select id from profile where name='System Administrator'];
       DataFactory.CreateNGAMCustomSettings(); 
       NGAMSettings__c ngamSettings = [select id,ProfileSystemAdministrator__c from NGAMSettings__c limit 1]; 
       string p = Util.getCustomSettingProfileId(ngamSettings.ProfileSystemAdministrator__c);

       User u2 = new User(alias = 'standt', email='SFDCadmin@ngam.natixis.com', 
                            emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
                            localesidkey='en_US', profileid = p, 
                            timezonesidkey='America/Los_Angeles', username='SFDCadmin@ngam.natixis.com',UserID__c='SFDCadmin');
        
        System.runAs(u2){
                //Creating the Territory
                Territory__c Terr = new Territory__c(Name='Test',TerritoryName__c='Test'); 
                insert Terr; 
                    
                // Creating the Corresponding Role
                UserRole Ur = new UserRole();
                Ur.Name = Terr.Name;
                Ur.DeveloperName = Terr.Id;
                Ur.CaseAccessForAccountOwner = 'Read';
                Ur.OpportunityAccessForAccountOwner = 'Read';
                Ur.ContactAccessForAccountOwner = 'Read';
                insert Ur; 
                    
                Group UrGroup = [select id, relatedid from group where relatedid=:Ur.id limit 1][0];    
                
                Terr.RoleID__c = ur.id;   
                Terr.RoleGroupId__c = UrGroup.id;    
                update Terr;     
               
                Account myA = new Account(name='test me') ;   
                insert MyA;     
                
                Test.StartTest();
     
                AccountTerritory__c myAC = new  AccountTerritory__c(account__c =MyA.id, territory__c=Terr.id, AccountTerrId__c = 'FR231176A507' );
                insert myAC ;
                      
                AccountShareBatch ASI = new AccountShareBatch();
                ASI.query = 'select Account__c, Territory__r.RoleGroupId__c, RoleId__c, GroupId__c from AccountTerritory__c';
                ID ASIid = database.executeBatch(ASI); 
                test.stopTest();
                    
                delete myAC;                                                                
                    
                }
        }
}