objects/Account.object
<CustomObject>
    <fields>
        <fullName>BPL__c</fullName>
        <defaultValue>false</defaultValue>
        <description>No Longer Used; if Account is part of the Blue Print List, true; manually updated/updated via data load</description>
        <label>BPL</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Zone__c</fullName>
        <description>Target for deletion; Original Zone field that aggregated data for FS but will become moot</description>
        <formula>CASE( $User.ActivityChannelName__c , 
'ADU', ZoneADU_IDU__r.Name, 
'IDU', ZoneADU_IDU__r.Name, 
'RCDU', ZoneRCDU__r.Name, 
'RADU', ZoneRADU__r.Name, 
'FIDUCIARY SERVICES', ZoneFS__r.Name , 
'DC REGIONAL', ZoneRADU__r.Name , 
'DCIO', ZoneRADU__r.Name , 
'DCIO SUB ADV', ZoneRADU__r.Name , 
'No Zone')</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Zone Aggregated</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>BPL__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Source: Updates will be made on a quarterly basis and submitted by sales to john Scuzzarella and then we bulk update</description>
        <inlineHelpText>Indicates that the Rep/Contact is at a Top 200</inlineHelpText>
        <label>Top 200 Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Zone__c</fullName>
        <description>Populates the Zone field with the logged in users Activity Channel.  The logic needs to look at the Users Activity Channel so that only values relevant to the user are returned.</description>
        <formula>CASE( $User.ActivityChannelName__c , 
'RCDU DIRECT',ZoneRCDU__r.Name,
'RCDU BACK OFFICE',ZoneRCDU__r.Name,
'RCDU GKA',ZoneRCDU__r.Name, 
'RCDU INSTL',ZoneRCDU__r.Name, 
'RCDU WHSE BT',ZoneRCDU__r.Name,
'RCDU WHSE/IND',ZoneRCDU__r.Name, 
'RADU REGIONAL',ZoneRADU__r.Name,  
'RADU',ZoneRADU__r.Name, 
'No Zone')</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Channel Specific Zone, based on Logged in User Activity Channel</inlineHelpText>
        <label>Zone Aggregated</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ExternalCommunitySettings__c.object
<CustomObject>
    <fields>
        <fullName>UseMPANamedCredential__c</fullName>
        <description>UseMPANamedCredential  , use the url from MPA or MPA_TEST based on the value from this field</description>
        <label>UseMPANamedCredential</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>To the custom setting for external communities</description>
    <label>ExternalCommunitySettings</label>
</CustomObject>

objects/NGAMSettings__c.object
<CustomObject>
    <fields>
        <fullName>ProfileSystemAdministrator__c</fullName>
        <description>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</description>
        <inlineHelpText>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</inlineHelpText>
        <label>Profile: System Administrator</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Holds the NGAM settings</description>
    <label>NGAM Settings</label>
</CustomObject>

objects/NGAMSettingsHierarchy__c.object
<CustomObject>
    <fields>
        <fullName>ByPassAccountValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows entity to by-pass validation rules on Account</description>
        <inlineHelpText>Allows entity to by-pass validation rules on Account</inlineHelpText>
        <label>By-Pass Account Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NGAM Settings - Hierarchy</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ActivityZoneId__c</fullName>
        <description>Used To Tag the Activities and Opportunities created by the user.</description>
        <inlineHelpText>READ ONLY FIELD : This Will be populated by the UserTerritory__c assignment when the Territory Assignment is tagged as an Activity Territory. Please never update this field directly. Instead Delete/Insert the relevant UserTerritory__c record.</inlineHelpText>
        <label>Activity Zone Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryChannelId__c</fullName>
        <label>Primary Channel Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryChannel__c</fullName>
        <label>Primary Channel</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserID__c</fullName>
        <defaultValue>"Populate This Field"</defaultValue>
        <externalId>true</externalId>
        <label>UserID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ZoneID__c</fullName>
        <externalId>true</externalId>
        <label>Zone ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Zone__c.object
<CustomObject>
    <fields>
        <fullName>Zone__c</fullName>
        <externalId>true</externalId>
        <label>Zone</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TaskExtension_Test.cls
@isTest 
public class TaskExtension_Test {
 
    @testSetup static void setup() {
        NGAMSettingsHierarchy__c hsettings = NGAMSettingsHierarchy__c.getOrgDefaults();
        hsettings.ByPassAccountValidationRules__c  = TRUE;
        upsert hsettings NGAMSettingsHierarchy__c.Id;
    }
    
   static testMethod void TaskExtensionTestNonIc(){
   

            
            ExternalCommunitySettings__c ECS = new ExternalCommunitySettings__c(); 
            ECS.Name = 'EstatementCommunity'; 
            ECS.UseMPANamedCredential__c = 'testugng'; 
            insert ECS;
            
            //Profile p = [select id from profile where name='System Administrator'];
            DataFactory.CreateNGAMCustomSettings(); 
            NGAMSettings__c ngamSettings = [select id,ProfileSystemAdministrator__c from NGAMSettings__c limit 1]; 
            string p = Util.getCustomSettingProfileId(ngamSettings.ProfileSystemAdministrator__c);
            
            Zone__c z=new Zone__c(Name ='Test Zone', Zone__c=12);
            insert z;
            
            Zone__c myZOne = [select id from zone__c limit 1][0];  
            
            User u2 = new User(alias = 'standt', email='SFDCadmin@ngam.natixis.com', 
                                emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
                                localesidkey='en_US', profileid = p, 
                                timezonesidkey='America/Los_Angeles', 
                                username='SFDCadmin@ngam.natixis.com',
                                UserID__c='SFDCadmin',
                                PrimaryChannelId__c='a1EF00000005Ws3MAE',
                                PrimaryChannel__c='WIREHOUSE',
                                ZoneId__c = myZOne.id,
                                ActivityZoneId__c = myZOne.id);
        
            System.runAs(u2){
                    Account testAccount = new Account(name='test');   
                    insert testAccount;
                        
                    Contact testContact = new Contact(lastname='Last Name',firstname='Test', accountid=testAccount.id,BPL__c=true);   
                    insert testContact;
                        
                    Task testTask = new Task(Subject='Test', status='Completed',type='Call - Informative', whoid=testContact.id, whatid=testAccount.id, description='test',ActivitySource__c ='',activitydate=date.today());  
                    insert TestTask;
                        
                  //start the test execution context
                    Test.startTest();
    
                    // set the test's page to your VF page (or pass in a PageReference)
                    Test.setCurrentPage(Page.TaskView);
                     
                    ApexPages.currentPage().getParameters().put('what_id', TestTask.whatid);
                    TestTask.whatid = null;
                     
                    ApexPages.currentPage().getParameters().put('who_id', TestTask.whoid);
                    TestTask.whoid= null;
                     
                    ApexPages.currentPage().getParameters().put('tsk12', TestTask.status);
                    TestTask.status= null;
                     
                    ApexPages.currentPage().getParameters().put('type', TestTask.type);
                    TestTask.type= null;
                     
                    ApexPages.currentPage().getParameters().put('retURL', testcontact.id);
                    // TestTask.type= null;                                             
                    TaskExtension controller = new TaskExtension(new ApexPages.StandardController(TestTask));
                    controller.retURL = testcontact.id;
                    
                    boolean ic = controller.is_ic_inbound;
                    boolean institutionalProfile= controller.InstitutionalProfile;
                                        
                 //TaskExtension controller = new TaskExtension();   
                    controller.unisave();
                    controller.TaskEdit();
                    controller.del();
                    system.assert(controller.isSF1 != null);
                    controller.SaveComplete();
                    controller.FollowUpActivity();
                    controller.upload();
                    controller.SaveEdit();                                                            
                    TestTask.Status = 'Open';
    
                    
                    TaskExtension.jsRemote(new Map<String, String>{'event' => 'upload', 'id' => '' + TestTask.id});
                    TaskExtension.jsRemote(new Map<String, String>{'event' => 'followup', 'id' => '' + TestTask.id});
                    TaskExtension.jsRemote(new Map<String, String>{'event' => 'del', 'id' => '' + TestTask.id});
                    
                    controller.del();
            
                    Test.stopTest();    
                    }   
            }    
    
      static testMethod void TaskExtensionTestIc() {
            //Profile p = [select id from profile where name='System Administrator']; 
            DataFactory.CreateNGAMCustomSettings(); 
            NGAMSettings__c ngamSettings = [select id,ProfileSystemAdministrator__c from NGAMSettings__c limit 1]; 
            string p = Util.getCustomSettingProfileId(ngamSettings.ProfileSystemAdministrator__c);
          
            Zone__c z=new Zone__c(Name ='Test Zone', Zone__c=12);
            insert z;
            Zone__c myZOne = [select id from zone__c limit 1][0];  
            User u2 = new User(alias = 'standt', email='SFDCadmin@ngam.natixis.com', 
                                emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
                                localesidkey='en_US', profileid = p, 
                                timezonesidkey='America/Los_Angeles', 
                                username='SFDCadmin@ngam.natixis.com',
                                UserID__c='SFDCadmin',
                                PrimaryChannelId__c='a1EF00000005Ws3MAE',
                                PrimaryChannel__c='WIREHOUSE',
                                ZoneId__c = myZOne.id,
                                ActivityZoneId__c = myZOne.id);
        
        System.runAs(u2) 
                {
                Account testAccount = new Account(name='test');   
                insert testAccount;
                    
                Contact testContact = new Contact(lastname='Last Name',firstname='Test', accountid=testAccount.id,BPL__c=true);   
                insert testContact;
                    
                Task testTask = new Task(Subject='Test', status='Completed',type='Call - Informative', whoid=testContact.id, whatid=testAccount.id, description='test',ActivitySource__c ='' );  
                insert TestTask;
                    
                 //start the test execution context
                Test.startTest();

                // set the test's page to your VF page (or pass in a PageReference)
                Test.setCurrentPage(Page.TaskView);
                 
                 ApexPages.currentPage().getParameters().put('what_id', TestTask.whatid);
                 TestTask.whatid = null;
                 
                  ApexPages.currentPage().getParameters().put('who_id', TestTask.whoid);
                 TestTask.whoid= null;
                 
                  ApexPages.currentPage().getParameters().put('tsk12', TestTask.status);
                 TestTask.status= null;
                 
                  ApexPages.currentPage().getParameters().put('type', TestTask.type);
                 TestTask.type= null;
                 
                    ApexPages.currentPage().getParameters().put('retURL', testcontact.id);
                    
                    ApexPages.currentPage().getParameters().put('subject', TestTask.subject);
                    ApexPages.currentPage().getParameters().put('description', TestTask.description);
                    
                    ApexPages.currentPage().getParameters().put('retURL', testcontact.id);
                // TestTask.type= null;
                 
                TaskExtension controller = new TaskExtension(new ApexPages.StandardController(TestTask));
                controller.retURL = testcontact.id;
                
                boolean ic = controller.is_ic_inbound;
                boolean institutionalProfile= controller.InstitutionalProfile;
                
                
             //TaskExtension controller = new TaskExtension();   
               // controller.unisave();
               // controller.TaskEdit();
               // controller.del();
               
                controller.is_ic_inbound = true;
                
                 controller.unisave();
                controller.TaskEdit();
                controller.del();
                
                controller.SaveComplete();
                controller.FollowUpActivity();
                controller.upload();
                controller.SaveEdit();
                
                TestTask.Status = 'Open';

                
                controller.del();
        
                Test.stopTest();    
                }   
            }    

}