objects/Account.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <description>No Longer Used; Fiduciary Services field to indicate subchannel</description>
        <label>Channel</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BANK TRUST</fullName>
                </value>
                <value>
                    <fullName>BANK TRUST WHSE</fullName>
                </value>
                <value>
                    <fullName>DCIO</fullName>
                </value>
                <value>
                    <fullName>DCIO SUB ADV</fullName>
                </value>
                <value>
                    <fullName>DC REGIONAL</fullName>
                </value>
                <value>
                    <fullName>FID FOCUS</fullName>
                </value>
                <value>
                    <fullName>FIDUCIARY BD</fullName>
                </value>
                <value>
                    <fullName>FIDUCIARY SERVICES</fullName>
                </value>
                <value>
                    <fullName>GLOBAL RELATIONS</fullName>
                </value>
                <value>
                    <fullName>GLOBAL RELATIONS IND</fullName>
                </value>
                <value>
                    <fullName>GLOBAL RELATIONS WHSE</fullName>
                </value>
                <value>
                    <fullName>IAG IND</fullName>
                </value>
                <value>
                    <fullName>IAG RIA</fullName>
                </value>
                <value>
                    <fullName>IND ADV GRP</fullName>
                </value>
                <value>
                    <fullName>OVERLAY</fullName>
                </value>
                <value>
                    <fullName>RETIREMENT</fullName>
                </value>
                <value>
                    <fullName>RIA FIDUCIARY</fullName>
                </value>
                <value>
                    <fullName>RIA PLATFORM</fullName>
                </value>
                <value>
                    <fullName>SUB ADV</fullName>
                </value>
                <value>
                    <fullName>WIREHOUSE</fullName>
                </value>
                <value>
                    <fullName>ADU</fullName>
                </value>
                <value>
                    <fullName>IDU</fullName>
                </value>
                <value>
                    <fullName>RCDU</fullName>
                </value>
                <value>
                    <fullName>RADU</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MarsAccountId__c</fullName>
        <description>The unique Account Identifier for MARS; used in integrations, Data Flow: Mars -&gt; SF</description>
        <externalId>true</externalId>
        <label>MARS Account Id</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Office</fullName>
        <active>true</active>
        <description>An individual branch location for a firm. Each firm must have a home office, which is the firm's primary location. Additionally, a firm can have multiple branch offices.</description>
        <label>Office</label>
    </recordTypes>
</CustomObject>

objects/Channel__c.object
<CustomObject>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/NGAMSettings__c.object
<CustomObject>
    <fields>
        <fullName>ProfileSales__c</fullName>
        <description>Indicates the profile that should be used for Sales User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</description>
        <inlineHelpText>Indicates the profile that should be used for Sales User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</inlineHelpText>
        <label>Profile: Sales</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProfileSystemAdministrator__c</fullName>
        <description>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</description>
        <inlineHelpText>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</inlineHelpText>
        <label>Profile: System Administrator</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Holds the NGAM settings</description>
    <label>NGAM Settings</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>UserID__c</fullName>
        <defaultValue>"Populate This Field"</defaultValue>
        <externalId>true</externalId>
        <label>UserID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/UtilTest.cls
@isTest
private class UtilTest {
    
    @testSetup static void setup() {
        DataFactory.CreateNGAMCustomSettings(); 
        NGAMSettings__c ngamSettings = [select id,ProfileSystemAdministrator__c,ProfileSales__c from NGAMSettings__c limit 1]; 
    }
    
    @isTest static void testGetCustomSettingProfileId() {

        NGAMSettings__c ngamSettings = [select id,ProfileSystemAdministrator__c,ProfileSales__c from NGAMSettings__c limit 1]; 
        string p = Util.getCustomSettingProfileId(ngamSettings.ProfileSystemAdministrator__c);
                
    }
    
    @isTest static void testGetUserTerritoryMap() {

        NGAMSettings__c ngamSettings = [select id,ProfileSystemAdministrator__c,ProfileSales__c from NGAMSettings__c limit 1]; 
        string p = Util.getCustomSettingProfileId(ngamSettings.ProfileSystemAdministrator__c);
        
        List<User> users = new List<User>();
        users.add(new User(alias = 'standt', email='SFDCadmin@ngam.natixis.com', 
                          emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
                          localesidkey='en_US', profileid = p,
                          timezonesidkey='America/Los_Angeles', username='SFDCadmin@ngam.natixis.com',UserID__c='SFDCadmin'));
        users.add(new User(alias = 'standt2', email='SFDCadmin2@ngam.natixis.com', 
                          emailencodingkey='UTF-8', lastname='Testing2', languagelocalekey='en_US', 
                          localesidkey='en_US', profileid = p,
                          timezonesidkey='America/Los_Angeles', username='SFDCadmin2@ngam.natixis.com',UserID__c='SFDC2admin'));        
        insert users;

        Map<Id,User> userMap = Util.getUserTerritoryMap();
        Boolean containsRightUsers = (userMap.containsKey(users[0].Id) && userMap.containsKey(users[1].Id));
        system.assertEquals(containsRightUsers, TRUE, 'getUserTerritoryMap() does not contain right users');

        Set<Id> userIdSet = new Set<Id>();
        userIdSet.add(users[0].Id);
        userMap = Util.getUserTerritoryMap(userIdSet);
        containsRightUsers = (userMap.containsKey(users[0].Id) && userMap.size() == 1);
        system.assertEquals(containsRightUsers, TRUE, 'getUserTerritoryMap(userIdSet) does not contain right users');        

    }    
    
    @isTest static void testGetAccountFirmIdMap() {
        
        Set<Id> accountIdSet = new Set<Id>();
        
        List<Account> firm0 = DataFactory.createTestFirms(1);
        insert firm0;
        accountIdSet.add(firm0[0].Id);
        
        List<Account> firm1 = DataFactory.createTestAccountswithFirms(1, firm0);
        firm1[0].ParentId = firm0[0].Id;
        firm1[0].MarsAccountId__c = 'TESTCHILD';
        insert firm1;
        accountIdSet.add(firm1[0].Id);
        
        List<Account> office = DataFactory.createTestAccountswithFirms(1, firm1);
        insert office;
        accountIdSet.add(office[0].Id);
        
        Map<Id,Id> accountFirmIdMap = Util.getAccountFirmIdMap(accountIdSet);
        
    }
    
    @isTest static void testGetChannelMap() {
        
		Map<Id,Channel__c> channelMap = Util.getChannelMap();
        
    }    
    
}