objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>The MARS status of the account, Data Flow: Mars -&gt; SF</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Source: MARS na_load_rep.StatCd
Loaded by a nightly job.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ExternalCommunitySettings__c.object
<CustomObject>
    <fields>
        <fullName>TestUserEmail__c</fullName>
        <description>Use Test email to create user</description>
        <inlineHelpText>If UseTestEmail is set to 'Y', this is the "to" email that will be used in the place of all community user email addresses.</inlineHelpText>
        <label>TestUserEmail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UseMPANamedCredential__c</fullName>
        <description>UseMPANamedCredential  , use the url from MPA or MPA_TEST based on the value from this field</description>
        <label>UseMPANamedCredential</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserNameFormat__c</fullName>
        <description>UserNameFormat for user record</description>
        <label>UserNameFormat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>To the custom setting for external communities</description>
    <label>ExternalCommunitySettings</label>
</CustomObject>

objects/FinancialAccount__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <description>Integration: NTXS_CUST_ACCOUNTS.Account_Id</description>
        <externalId>true</externalId>
        <inlineHelpText>Id of the Financial Account in Data Central. DEPRECATED will be removed in Version 8.0.</inlineHelpText>
        <label>Account Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>AccountNameEncrypted__c</fullName>
        <description>Unique Vestmark Account name</description>
        <inlineHelpText>Unique Vestmark Account name</inlineHelpText>
        <label>Account Name</label>
        <length>30</length>
        <maskChar>X</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>RSAAccount__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, indicates that this Financial Account is an RSA account.  Checking this box will affect how the Financial Account appears in the community.</description>
        <inlineHelpText>If checked, indicates that this Financial Account is an RSA account.  Checking this box will affect how the Financial Account appears in the community.</inlineHelpText>
        <label>RSA Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ViewableinCommunity__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If checked, this Financial Account can be viewed in Community</description>
        <inlineHelpText>If checked, this Financial Account can be viewed in Community</inlineHelpText>
        <label>Viewable in Community</label>
        <type>Checkbox</type>
    </fields>
    <description>Used in community to display Financial Account data to community users.  This object's data is sourced from Data Central and maintained via integration.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/FinancialAccountContact__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact related to the Financial Account</description>
        <inlineHelpText>Contact related to the Financial Account</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Financial Account Contact</relationshipLabel>
        <relationshipName>Financial_Account_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Indicates the status of the contact's relationship to the Financial Account</description>
        <inlineHelpText>Indicate the status of the contact's relationship to the Financial Account</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                    <default>true</default>
                    <label>Current</label>
                </value>
                <value>
                    <fullName>Former</fullName>
                </value>
                <value>
                    <fullName>Inactivated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>View_Financial_Account_in_Community__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates if this contact should see the Financial Account in the community.</description>
        <inlineHelpText>If checked, the contact will be able to see the Financial Account in the community</inlineHelpText>
        <label>View Financial Account in Community?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <description>Financial Account to which this contact is related</description>
        <inlineHelpText>Financial Account to which this contact is related</inlineHelpText>
        <label>Financial Account</label>
        <referenceTo>FinancialAccount__c</referenceTo>
        <relationshipLabel>Financial Account Contact</relationshipLabel>
        <relationshipName>Financial_Account_Contact</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <description>Tracks contacts associated with a Financial Account.  Dictates which contacts (community users) can see a particular Financial Account in the community.</description>
    <label>Financial Account Contact</label>
    <nameField>
        <displayFormat>FAC-{000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/NGAMSettingsHierarchy__c.object
<CustomObject>
    <fields>
        <fullName>ByPassAccountValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows entity to by-pass validation rules on Account</description>
        <inlineHelpText>Allows entity to by-pass validation rules on Account</inlineHelpText>
        <label>By-Pass Account Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NGAM Settings - Hierarchy</label>
</CustomObject>

classes/FinancialAccountTriggerHandler_Test.cls
@isTest  
public class FinancialAccountTriggerHandler_Test {
    
    static testMethod void FinancialAccountTriggerHandlerTest() {    
    
        NGAMSettingsHierarchy__c hsettings = NGAMSettingsHierarchy__c.getOrgDefaults();
        hsettings.ByPassAccountValidationRules__c  = TRUE;
        upsert hsettings NGAMSettingsHierarchy__c.Id;
            
        ExternalCommunitySettings__c ECS = new ExternalCommunitySettings__c(); 
        ECS.Name = 'EstatementCommunity'; 
        ECS.UseMPANamedCredential__c = 'testugng'; 
        ECS.UserNameFormat__c = 'TEstcom'; 
        ECS.TestUserEmail__c = 'TEst@gmail.com'; 
        insert ECS; 
        
        Account a = new Account(Name = 'TEST Account'); 
        insert a; 

        contact con = new contact(FirstName='ABC', LastName = 'TEST Account',AccountId = a.Id); 
        insert con; 
        
        FinancialAccount__c testAcc = new FinancialAccount__c(Name='Test Name',AccountID__c=123); 
        testAcc.RSAAccount__c = false; 
        testAcc.AccountNameEncrypted__c ='abc'; 
        testAcc.ViewableinCommunity__c = TRUE; 
        insert testAcc; 
        
        FinancialAccountContact__c FAC = new FinancialAccountContact__c(); 
        FAC.Financial_Account__c = testAcc.Id; 
        FAC.contact__c = con.Id; 
        FAC.Status__c = 'Current'; 
        FAC.View_Financial_Account_in_Community__c = true; 
        insert FAC; 
        
        FinancialAccountContact__c finAcctContact = [SELECT Financial_Account__r.Id,Contact__c FROM FinancialAccountContact__c WHERE Status__c = 'Current'
                                                           AND View_Financial_Account_in_Community__c = TRUE
                                                           AND Financial_Account__r.ViewableinCommunity__c = TRUE LIMIT 1];
        
        FinancialAccount__c finAcct = [SELECT Id FROM FinancialAccount__c WHERE Id = :finAcctContact.Financial_Account__r.Id LIMIT 1];
       
        //start the test execution context
        Test.startTest();
                
        finAcct.ViewableinCommunity__c = false;
        update finAcct;
    
        finAcct.ViewableinCommunity__c = true;
        update finAcct;
        
      
        
        Test.stopTest();    
    }
}