objects/Account.object
<CustomObject>
    <fields>
        <fullName>MktOppMarketShareAUM__c</fullName>
        <description>Integrated from EDW</description>
        <label>Mkt Opp Market Share AUM</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>MktOppPYIndustryNetSales__c</fullName>
        <description>Integrated from EDW</description>
        <label>Mkt Opp PY Industry Net Sales</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MktOppPYMarketSharePurchases__c</fullName>
        <description>Integrated from EDW</description>
        <label>Mkt Opp PY Market Share Purchases</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>NumberOfOpenTasks__c</fullName>
        <description>The number of open tasks this Account has. Controlled by a trigger on task.</description>
        <inlineHelpText>The number of open tasks this Account has.</inlineHelpText>
        <label>Number of Open Tasks</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PotentialScore__c</fullName>
        <description>Integrated from EDW and calculated by DIG</description>
        <label>Potential Score</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <default>true</default>
                    <label>0</label>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RiskScore__c</fullName>
        <description>Integrated from EDW and calculated by DIG</description>
        <label>Risk Score</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Affiliate</fullName>
        <active>true</active>
        <label>Affiliate</label>
    </recordTypes>
</CustomObject>

objects/FilteredListColumn__mdt.object
<CustomObject>
    <fields>
        <fullName>ColumnLabel__c</fullName>
        <description>The label that will display in the column header for this column.</description>
        <inlineHelpText>The label that will display in the column header for this column.</inlineHelpText>
        <label>Column Label</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldName__c</fullName>
        <description>The name of the field on the object to display. May not be used by custom lightning components but is required in most cases.</description>
        <inlineHelpText>The name of the field on the object to display. May not be used by custom lightning components but is required in most cases.</inlineHelpText>
        <label>Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Value_Add_Symb__c</fullName>
        <description>Show Additional symbol to each value in column (For exmaple: % or $)</description>
        <inlineHelpText>Show Additional symbol to each value in column (For exmaple: % or $)</inlineHelpText>
        <label>Field Value Add Symb</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FilteredListConfiguration__c</fullName>
        <description>The filtered list to display this column on.</description>
        <inlineHelpText>The filtered list to display this column on.</inlineHelpText>
        <label>Filtered List Configuration</label>
        <referenceTo>FilteredListConfiguration__mdt</referenceTo>
        <relationshipLabel>Filtered List Columns</relationshipLabel>
        <relationshipName>FilteredListColumns</relationshipName>
        <required>true</required>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>IsLink__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this is checked and the field is a lookup it will display in the component as a clickable link that will direct the user to that record.</description>
        <inlineHelpText>If this is checked and the field is a lookup it will display in the component as a clickable link that will direct the user to that record.</inlineHelpText>
        <label>Is Link</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LightningComponentName__c</fullName>
        <description>If this column is controlled by a lightning component add it's name here and it will show up in the column instead of the field.</description>
        <inlineHelpText>If this column is controlled by a lightning component add it's name here and it will show up in the column instead of the field.</inlineHelpText>
        <label>Lightning Component Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LightningComponentParams__c</fullName>
        <label>Lightning Component Params</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ordering__c</fullName>
        <description>Where should this column be? Higher numbers are later in the columns.</description>
        <inlineHelpText>Where should this column be? Higher numbers are later in the columns.</inlineHelpText>
        <label>Ordering</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <description>A configuration record for a filtered list column.</description>
    <label>Filtered List Column</label>
    <pluralLabel>Filtered List Columns</pluralLabel>
</CustomObject>

objects/FilteredListConfiguration__mdt.object
<CustomObject>
    <fields>
        <fullName>ObjectName__c</fullName>
        <description>Name of the SObject that this table displays.</description>
        <inlineHelpText>Name of the SObject that this table displays.</inlineHelpText>
        <label>Object Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <description>A collection of filtered list column records that are used to configure a filtered list.</description>
    <label>Filtered List Configuration</label>
    <pluralLabel>Filtered List Configurations</pluralLabel>
</CustomObject>

objects/FilteredListParam__mdt.object
<CustomObject>
    <fields>
        <fullName>FieldName__c</fullName>
        <label>Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FilterDefaultValue__c</fullName>
        <label>Filter Default Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FilterLabel__c</fullName>
        <label>Filter Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FilterOperation__c</fullName>
        <label>Filter Operation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>equals</fullName>
                    <default>true</default>
                    <label>equals</label>
                </value>
                <value>
                    <fullName>not equal to</fullName>
                </value>
                <value>
                    <fullName>less than</fullName>
                </value>
                <value>
                    <fullName>greater than</fullName>
                </value>
                <value>
                    <fullName>less or equal</fullName>
                </value>
                <value>
                    <fullName>greater or equal</fullName>
                </value>
                <value>
                    <fullName>contains</fullName>
                </value>
                <value>
                    <fullName>does not contain</fullName>
                </value>
                <value>
                    <fullName>starts with</fullName>
                </value>
                <value>
                    <fullName>includes</fullName>
                </value>
                <value>
                    <fullName>excludes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FilteredListConfiguration__c</fullName>
        <label>Filtered List Configuration</label>
        <referenceTo>FilteredListConfiguration__mdt</referenceTo>
        <relationshipLabel>Filtered List Params</relationshipLabel>
        <relationshipName>Filtered_List_Params</relationshipName>
        <required>true</required>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>IsEnableb__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Enableb</label>
        <type>Checkbox</type>
    </fields>
    <description>A configuration filter for a filter list column (right block in main list).</description>
    <label>Filtered List Param</label>
    <pluralLabel>Filtered List Params</pluralLabel>
</CustomObject>

classes/SL_ctrl_ListViewHomePage_test.cls
/**
*  Test name   :   SL_ctrl_ListViewHomePage_test
*  Created by  :   Alex Zhurylo
*  Created on  :   7/26/2019
*  Description :   test class for SL_ctrl_ListViewHomePage
**/
@isTest
public class SL_ctrl_ListViewHomePage_test {

    /*  init
        1) create new Account() record with all required fields;
     */
    @TestSetup
    public static void init(){
        
        Double rand = Math.random() * 1000;
        Account acc = new Account();
            acc.Name = 'test' + rand;
            acc.PotentialScore__c = '1';
            acc.RiskScore__c = '1';
            acc.MktOppMarketShareAUM__c = 1.0;
            acc.MktOppPYIndustryNetSales__c = 1.0;
            acc.MktOppPYMarketSharePurchases__c = 1.0;
            acc.NumberOfOpenTasks__c = 1.0;
            acc.type = 'Affiliate';
        insert acc;
    }
    
    /*  getListOfColumns_test check getListOfColumns
        1) call getListOfColumns with Main Dashboard parameter and assign to returnedResult variable;
        2) return metadata record with name Main Dashboard from FilteredListConfiguration__mdt;
        3) return records from FilteredListParam__mdt and FilteredListColumn__mdt where FilteredListConfiguration__c
            = id from record returned in step 2;
        4) create RecordsWrapper wrapper with all 3 records(step 2 and 3);
        5) compare returnedResult and expectedResult;
        6) expected result => strings are equal;
     */
    @isTest
    public static void getListOfColumns_test() {
        
        String nameOfmetadata = 'Main Dashboard';

        String returnedResult = SL_ctrl_ListViewHomePage.getListOfColumns(nameOfmetadata);

        FilteredListConfiguration__mdt record = [SELECT id, MasterLabel, ObjectName__c
                                                 FROM FilteredListConfiguration__mdt  
                                                 WHERE Label =: nameOfmetadata LIMIT 1];
        
        String objectApiName = record.ObjectName__c;
        String recordId = record.id;

        List<FilteredListColumn__mdt> filterListRecords = [SELECT ColumnLabel__c, FieldName__c, FilteredListConfiguration__c, IsLink__c, 
                                                    LightningComponentName__c, LightningComponentParams__c, Ordering__c, Field_Value_Add_Symb__c 
                                                    FROM FilteredListColumn__mdt WHERE FilteredListConfiguration__c =: recordId];
        
        List<FilteredListParam__mdt> filterListParams = [SELECT FieldName__c, FilterDefaultValue__c, FilteredListConfiguration__c, FilterLabel__c,
                                                        FilterOperation__c, IsEnableb__c FROM FilteredListParam__mdt 
                                                        WHERE FilteredListConfiguration__c =: recordId ];
        SL_ctrl_ListViewHomePage.RecordsWrapper wrapper = new SL_ctrl_ListViewHomePage.RecordsWrapper(record, filterListRecords, filterListParams);
        String expectedResult = JSON.serialize(wrapper);

        System.assertEquals(expectedResult, returnedResult);
    }

    /*  getAllRecordsThrougthColumns_test check getAllRecordsThrougthColumns
        1) call getListOfColumns with Main Dashboard parameter and assign to serializeListOfRecord variable;
        2) create listRecords and desiarialize string from step 1;
        3) iterate throught list of filterListRecords from step 2 and find all FieldName__c and LightningComponentParams__c. 
            Assign them to  list lstHeaderItems;
        4) call getAllRecordsThrougthColumns with all required parameters and assign to returnedResult;
        5) call private getAllRecordsThrougthColumns with all required parameters and assign to expectedResult;
        6) compare returnedResult and expectedResult;
        7) expected result => strings are equal;
     */
    @isTest
    public static void getAllRecordsThrougthColumns_test() {
        
        String nameOfmetadata = 'Main Dashboard';
        String serializeListOfRecord = SL_ctrl_ListViewHomePage.getListOfColumns(nameOfmetadata);

        SL_ctrl_ListViewHomePage.RecordsWrapper listRecords = (SL_ctrl_ListViewHomePage.RecordsWrapper) JSON.deserialize(serializeListOfRecord,  SL_ctrl_ListViewHomePage.RecordsWrapper.class);

        List<FilteredListColumn__mdt> filterListRecords = listRecords.filterListRecords;

        List<String> lstHeaderItems = new List<String>();
        for (Integer i = 0; i < filterListRecords.size(); i++) {
            if (filterListRecords[i].FieldName__c != null) {
                lstHeaderItems.add(filterListRecords[i].FieldName__c);
            } else {
                lstHeaderItems.add(filterListRecords[i].LightningComponentParams__c);
            }
        }

        String objName = 'Account';
        String listOfHeaderElements = JSON.serialize(lstHeaderItems);        
        String numberOfRecords = '10';
        String defaultOrder = 'Name';
        Boolean isAsc = false;

        String returnedResult = SL_ctrl_ListViewHomePage.getAllRecordsThrougthColumns(objName, listOfHeaderElements, numberOfRecords, defaultOrder, isAsc);
        String expectedResult = getAllRecordsThrougthColumns(objName, listOfHeaderElements, numberOfRecords, defaultOrder, isAsc);
        System.assertEquals(expectedResult, returnedResult);

        returnedResult = SL_ctrl_ListViewHomePage.getAllRecordsThrougthColumns(objName, listOfHeaderElements, numberOfRecords, defaultOrder, true);
        expectedResult = getAllRecordsThrougthColumns(objName, listOfHeaderElements, numberOfRecords, defaultOrder, true);
        System.assertEquals(expectedResult, returnedResult);
    }

    /*  createTaskRecords_test check createTaskRecords
        1) return account record;
        2) create new listOfIds and add account id;
        3) return all tasks where WhatId =: acc.Id;
        4) expected result list of tasks equals 0;
        5) call createTaskRecords with created list of ids in step 2;
        6) return all tasks where WhatId =: acc.Id;
        7) expected result list of tasks equals 1;
        8) call createTaskRecords with incorrect id;
        9) expected result string doen't equal SUCCESS;
     */
    @isTest
    public static void createTaskRecords_test() {
        
        Account acc = [SELECT id FROM Account LIMIT 1];

        List<String> listOfIds = new List<String>{acc.Id};

        List<Task> lstTasks = [SELECT Id FROM Task WHERE WhatId =: acc.Id];
        System.assertEquals(lstTasks.size(), 0);

        String returnedResult = SL_ctrl_ListViewHomePage.createTaskRecords(listOfIds);
        System.assertEquals(returnedResult, 'SUCCESS');

        lstTasks = [SELECT Id FROM Task WHERE WhatId =: acc.Id];
        System.assertEquals(lstTasks.size(), 1);

        String returnedResultError = SL_ctrl_ListViewHomePage.createTaskRecords(new List<String>{lstTasks[0].Id});
        System.assertNotEquals(returnedResultError, 'SUCCESS');
    }

    /*  getAllRecordsThrougthColumns
        return all records due to incoming parameters
     */
    private static String getAllRecordsThrougthColumns(String objName, String listOfHeaderElements, String numberOfRecords, 
                                                    String defaultOrder,  Boolean isAsc){

// TJB 20190827                                                       
/*        String strAsc = '';
        if (isAsc) {
            strAsc = ' desc';
        } else {
            strAsc = ' asc';
        } */

        List<String> lstDeserialize = (List<String>)JSON.deserialize(listOfHeaderElements, List<String>.class);
        String elementsToSlect = '';
        for (Integer i = 0; i < lstDeserialize.size(); i++) {
            
            elementsToSlect += lstDeserialize[i] ;

            if(lstDeserialize.size() != i+1){
                elementsToSlect +=  ',';
            }
        }

// TJB 20190827                                                       
//        String query = 'SELECT ' + elementsToSlect +' FROM ' + objName + ' ORDER By ' + defaultOrder + ' '+ strAsc + ' NULLS LAST  LIMIT 2000' ;
        String query = 'SELECT ' + elementsToSlect +' FROM ' + objName + ' ORDER By ' + defaultOrder + ' LIMIT 2000' ;        
        List<sObject> lstObject = Database.query(query);

        List<SL_ctrl_ListViewHomePage.ListSerachWrapper> lstWrappers = new List<SL_ctrl_ListViewHomePage.ListSerachWrapper>();
        
        for (Integer i = 0; i < lstObject.size(); i++) {
            lstWrappers.add(new SL_ctrl_ListViewHomePage.ListSerachWrapper(lstObject[i])); 
        }
        
        return JSON.serialize(lstWrappers);
    }

}