objects/Account.object
<CustomObject>
    <fields>
        <fullName>PrivateWealth__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Populated by the process builder if any related contact has the Private Wealth flag checked</description>
        <inlineHelpText>Auto populated if any related contact has the Private Wealth flag checked.</inlineHelpText>
        <label>Private Wealth</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Firm</fullName>
        <active>true</active>
        <description>Firms, offices, and reps are organized into a hierarchy. This means that each rep must be assigned to an office, and each office must be assigned to a firm. Firm is the highest level in the hierarchy.</description>
        <label>Firm</label>
    </recordTypes>
    <recordTypes>
        <fullName>Office</fullName>
        <active>true</active>
        <description>An individual branch location for a firm. Each firm must have a home office, which is the firm's primary location. Additionally, a firm can have multiple branch offices.</description>
        <label>Office</label>
    </recordTypes>
    <recordTypes>
        <fullName>ParentFirm</fullName>
        <active>true</active>
        <label>ParentFirm</label>
    </recordTypes>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>FirmNameText__c</fullName>
        <description>Used in sharing rules because formula fields and lookups cannot be used.</description>
        <label>Firm Name Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InitiateEmailOptIn__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, sets Email Opt-out to false and initiates an automation rule in Pardot.  Pardot will uncheck after automation rule completes.</description>
        <inlineHelpText>Only check if the client has opted-out or snoozed and specifically requested opt-in. Contact will be sent Pref Center email within 20 minutes.  Your selection is tracked for compliance reasons.</inlineHelpText>
        <label>Initiate Email Opt-In</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PardotPrefCenterOptOut1__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Synced with Pardot Preference Center; drives what shows in Email Preferences text box via the field label.</description>
        <label>Client Comm Opt-out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PardotPrefCenterOptOut2__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Synced with Pardot Preference Center; drives what shows in Email Preferences text box via the field label.</description>
        <label>Conferences Opt-out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PardotPrefCenterOptOut3__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Synced with Pardot Preference Center; drives what shows in Email Preferences text box via field label.</description>
        <label>Research/Insights Opt-out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PardotPrefCenterOptOut4__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Synced with Pardot Preference Center; drives what shows in Email Preferences text box via the field label.</description>
        <label>Products/Strategies Opt-out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SnoozeEmails__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that the contact has snoozed their marketing emails.  This field is controlled by the Pardot preference center.  There is time-based logic that reverts the snooze to false after 90 days.  It works in tandem with Event Opt-Out.</description>
        <label>Snooze Emails</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>VestmarkEmail__c</fullName>
        <description>This field store the email address of the FA in VestMark system and used for Estatement project</description>
        <inlineHelpText>This field store the email address of the FA in VestMark system.</inlineHelpText>
        <label>Vestmark Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ExternalCommunitySettings__c.object
<CustomObject>
    <fields>
        <fullName>EndClientCommunityAccountName__c</fullName>
        <description>The name of the Account (Firms Office) to which End Client/Interested 3rd Party community contacts will belong.</description>
        <inlineHelpText>The name of the Account (Firms Office) to which new End Client/Interested 3rd Party community contacts belong.  This should always be NGAM DISTRIBUTION, L.P., PORTAL END CLIENTS</inlineHelpText>
        <label>EndClientCommunityAccountName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>To the custom setting for external communities</description>
    <label>ExternalCommunitySettings</label>
</CustomObject>

objects/NGAMSettingsHierarchy__c.object
<CustomObject>
    <fields>
        <fullName>ByPassAccountValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows entity to by-pass validation rules on Account</description>
        <inlineHelpText>Allows entity to by-pass validation rules on Account</inlineHelpText>
        <label>By-Pass Account Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NGAM Settings - Hierarchy</label>
</CustomObject>

classes/ContactTriggerHandlerTest.cls
@istest
public class ContactTriggerHandlerTest {

    // Could not write coverage for Vestmark Email change due to issues with setting up community user records
    
    static testmethod void test() {
    
        NGAMSettingsHierarchy__c hsettings = NGAMSettingsHierarchy__c.getOrgDefaults();
        hsettings.ByPassAccountValidationRules__c  = TRUE;
        upsert hsettings NGAMSettingsHierarchy__c.Id;

        
        Id ECrecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('End Client').getRecordTypeId();
        Id CRrecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Rep/Contact').getRecordTypeId();    
        
        DataFactory.insertEstatementCommunityCustomSettings();
        ExternalCommunitySettings__c myCustomSetting = ExternalCommunitySettings__c.getValues('EstatementCommunity');
        
        List<Account> a = DataFactory.createTestAccounts(1);
        insert a;
        
        List<Account> f = DataFactory.createTestFirms(3);
        f[0].Name = myCustomSetting.EndClientCommunityAccountName__c;
        f[1].Name = 'ParentParentFirm-MS';
        f[2].Name = 'ParentFirm-AA';
        insert f;
        
        Account LG = new Account(Name='ParentFirm-LG', ParentId = f[1].Id);
        insert LG;
        Account LGoffice = new Account(Name='Office-LG', ParentId = LG.Id);
        insert LGoffice;
        Account AAoffice = new Account(Name='Office-AA', ParentId = f[2].Id);
        insert AAoffice;
        
        List<Contact> contacts = DataFactory.createTestContacts(10, a, FALSE);
        for (Contact c : contacts) {
            c.RecordTypeId = CRrecordTypeId; 
        }
        //Vestmark Email
        contacts[0].RecordTypeId = ECrecordTypeId;
        contacts[0].VestmarkEmail__c = 'test1@foo.com';
        contacts[0].AccountId = null;
        
        //Firm Name Text
        contacts[1].AccountId = LGoffice.Id;
        contacts[1].LastName = 'Test-MS';
        contacts[2].AccountId = AAoffice.Id;
        contacts[2].LastName = 'Test-AA';
        contacts[9].HasOptedOutOfEmail = TRUE;
        insert contacts;
        
        List<Contact> contactCheck = [SELECT LastName, FirmNameText__c from Contact];
        List<Account> accountCheck = [SELECT Id, Name, PrivateWealth__c FROM Account];
        
        for (Contact c : contactCheck) {
            if (c.LastName == 'Test-MS') system.assertEquals(c.FirmNameText__c,'ParentParentFirm-MS');
            if (c.LastName == 'Test-AA') system.assertEquals(c.FirmNameText__c,'ParentFirm-AA');
        }
        
        contacts[0].VestmarkEmail__c = 'test2@foo.com';
        contacts[2].AccountId = LGoffice.Id;
        contacts[1].AccountId = AAoffice.Id;
        
        //Email Preferences
        //No Emails
        contacts[3].SnoozeEmails__c = TRUE;
        contacts[3].HasOptedOutOfEmail = TRUE;
        contacts[3].Email = '';
        contacts[3].pi__pardot_hard_bounced__c = TRUE;
        //All Emails
        contacts[4].Email = 'foo@foo.com';
        //Mixed Opt-in and Opt-out
        contacts[5].Email = 'foo@foo.com';
        contacts[5].PardotPrefCenterOptOut1__c = TRUE;
        contacts[6].Email = 'foo@foo.com';
        contacts[6].PardotPrefCenterOptOut2__c = TRUE;
        contacts[7].Email = 'foo@foo.com';
        contacts[7].PardotPrefCenterOptOut3__c = TRUE;
        contacts[8].Email = 'foo@foo.com';
        contacts[8].PardotPrefCenterOptOut4__c = TRUE;
        contacts[9].Email = 'foo@foo.com';
        contacts[9].InitiateEmailOptIn__c = TRUE;
        

        update contacts;

        List<Contact> contactCheck2 = [SELECT LastName, FirmNameText__c from Contact];
        for (Contact c : contactCheck2) {
            if (c.LastName == 'Test-MS') system.assertEquals(c.FirmNameText__c,'ParentFirm-AA');
            if (c.LastName == 'Test-AA') system.assertEquals(c.FirmNameText__c,'ParentParentFirm-MS');
        }
        
    }
    
}