objects/Account.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <description>No Longer Used; Fiduciary Services field to indicate subchannel</description>
        <label>Channel</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BANK TRUST</fullName>
                </value>
                <value>
                    <fullName>BANK TRUST WHSE</fullName>
                </value>
                <value>
                    <fullName>DCIO</fullName>
                </value>
                <value>
                    <fullName>DCIO SUB ADV</fullName>
                </value>
                <value>
                    <fullName>DC REGIONAL</fullName>
                </value>
                <value>
                    <fullName>FID FOCUS</fullName>
                </value>
                <value>
                    <fullName>FIDUCIARY BD</fullName>
                </value>
                <value>
                    <fullName>FIDUCIARY SERVICES</fullName>
                </value>
                <value>
                    <fullName>GLOBAL RELATIONS</fullName>
                </value>
                <value>
                    <fullName>GLOBAL RELATIONS IND</fullName>
                </value>
                <value>
                    <fullName>GLOBAL RELATIONS WHSE</fullName>
                </value>
                <value>
                    <fullName>IAG IND</fullName>
                </value>
                <value>
                    <fullName>IAG RIA</fullName>
                </value>
                <value>
                    <fullName>IND ADV GRP</fullName>
                </value>
                <value>
                    <fullName>OVERLAY</fullName>
                </value>
                <value>
                    <fullName>RETIREMENT</fullName>
                </value>
                <value>
                    <fullName>RIA FIDUCIARY</fullName>
                </value>
                <value>
                    <fullName>RIA PLATFORM</fullName>
                </value>
                <value>
                    <fullName>SUB ADV</fullName>
                </value>
                <value>
                    <fullName>WIREHOUSE</fullName>
                </value>
                <value>
                    <fullName>ADU</fullName>
                </value>
                <value>
                    <fullName>IDU</fullName>
                </value>
                <value>
                    <fullName>RCDU</fullName>
                </value>
                <value>
                    <fullName>RADU</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Activity.object
<CustomObject>
    <fields>
        <fullName>ActivityId__c</fullName>
        <formula>CaseSafeId( Id )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ActivityId</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ActivityContact__c.object
<CustomObject>
    <fields>
        <fullName>ActivityContact__c</fullName>
        <description>This Field is populated by the trigger and contains ActivityId__c + Contact__c, it is used to ensure that no duplicate contact on an activity (does not allow duplicate)</description>
        <label>ActivityContact</label>
        <length>37</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ActivityId__c</fullName>
        <description>This fake Id field is binded to Task through the use of the "Contacts" Grid build in the GridBuddy application. It is populated by GB with Task.Id</description>
        <externalId>true</externalId>
        <label>ActivityId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by the trigger from Task.OwnerChannelId__c (=Owner:User.ActivityChannelId__c)</description>
        <label>Channel</label>
        <referenceTo>Channel__c</referenceTo>
        <relationshipLabel>Activity Contacts</relationshipLabel>
        <relationshipName>Activity_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is entered through the Gridbuddy Form and is set to the id of the contact entered through the form. It is used by the trigger to create the TaskRelation entry to the related Task</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Activity Contacts</relationshipLabel>
        <relationshipName>ActivityContacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <description>Each activity will have 1 to Many contacts. These activity related contacts are stored in this object along necessary attributes to allow for advanced activity reporting. This Table is synched up with the TaskRelation standard object through the "ActivityContactTrigger" trigger and the "ActivityContactTriggerHandler" Class.
This object is "virtually" related to Task through the use of the "ActivityId__c" field. This fake Id field is binded to Task through the use of the "Contacts" Grid build in the GridBuddy application.</description>
    <label>Activity Contact</label>
    <nameField>
        <displayFormat>AC-{0000000000}</displayFormat>
        <label>Activity Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Contacts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Channel__c.object
<CustomObject>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <description>Wells FA data in Salesforce requested by Joseph Labresh. This field labels each FA by what channel they work in: “PCG”, “WBS”, and “Finet”.</description>
        <inlineHelpText>This field is about Wells FA data, it labels each FA by what channel they work in: “PCG”, “WBS”, and “Finet”.</inlineHelpText>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PCG</fullName>
                </value>
                <value>
                    <fullName>WBS</fullName>
                </value>
                <value>
                    <fullName>FiNet</fullName>
                </value>
                <value>
                    <fullName>RIA Hybrid</fullName>
                </value>
                <value>
                    <fullName>Independent</fullName>
                </value>
                <value>
                    <fullName>Bank</fullName>
                </value>
                <value>
                    <fullName>RIA IFA Advisor</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Licensed Branch Employee</fullName>
                </value>
                <value>
                    <fullName>Insurance Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/NGAMSettings__c.object
<CustomObject>
    <fields>
        <fullName>ProfileSystemAdministrator__c</fullName>
        <description>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</description>
        <inlineHelpText>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</inlineHelpText>
        <label>Profile: System Administrator</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Holds the NGAM settings</description>
    <label>NGAM Settings</label>
</CustomObject>

objects/NGAMSettingsHierarchy__c.object
<CustomObject>
    <fields>
        <fullName>ByPassAccountValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows entity to by-pass validation rules on Account</description>
        <inlineHelpText>Allows entity to by-pass validation rules on Account</inlineHelpText>
        <label>By-Pass Account Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NGAM Settings - Hierarchy</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ActivityChannelId__c</fullName>
        <description>Used To Tag the Activities and Opportunities created by the user.</description>
        <externalId>true</externalId>
        <inlineHelpText>READ ONLY FIELD : This Will be populated by the UserTerritory__c assignment when the Territory Assignment is tagged as an Activity Territory. Please never update this field directly. Instead Delete/Insert the relevant UserTerritory__c record.</inlineHelpText>
        <label>Activity Channel Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserID__c</fullName>
        <defaultValue>"Populate This Field"</defaultValue>
        <externalId>true</externalId>
        <label>UserID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TaskRelationChangeEventTHTest.cls
@isTest
public class TaskRelationChangeEventTHTest {
    
    @testSetup
    static void setup() {
        
        NGAMSettingsHierarchy__c hsettings = NGAMSettingsHierarchy__c.getOrgDefaults();
        hsettings.ByPassAccountValidationRules__c  = TRUE;
        upsert hsettings NGAMSettingsHierarchy__c.Id;
        DataFactory.CreateNGAMCustomSettings(); 

        NGAMSettings__c ngamSettings = [select id,ProfileSystemAdministrator__c from NGAMSettings__c limit 1]; 
        string p = Util.getCustomSettingProfileId(ngamSettings.ProfileSystemAdministrator__c);
        
        List<Channel__c> channels = DataFactory.createChannels();
        insert channels;
        
        User u = new User(alias = 'standt', email='SFDCadmin@ngam.natixis.com', 
                          emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
                          localesidkey='en_US', profileid = p, 
                          timezonesidkey='America/Los_Angeles', username='SFDCadmin@ngam.natixis.com',UserID__c='SFDCadmin',
                          ActivityChannelId__c = channels[0].Id);
        insert u;
        
    }
    
    @isTest static void test() {
        
        User u = [SELECT Id FROM User where username = 'SFDCadmin@ngam.natixis.com' LIMIT 1];
        
        System.runAs(u) {

	        Test.enableChangeDataCapture();

            List<Account> myAccounts = DataFactory.createTestAccounts(3);
            insert myAccounts;
            
            List<Contact> myContacts = DataFactory.createTestContacts(1, myAccounts, false);
            insert myContacts;     
            
            List<Contact> myContacts2 = DataFactory.createTestContacts(2, myAccounts, false);
            insert myContacts2;     
            
            List<Task> myTasks = DataFactory.createTestTasks_outlookPlugin(1,myContacts,'Email');  
            insert myTasks; 
            
            List<TaskRelation> myTRs = new List<TaskRelation>();
            myTRs.add(new TaskRelation(RelationId = myContacts2[0].Id, TaskId = myTasks[0].Id));
            myTRs.add(new TaskRelation(RelationId = myContacts2[1].Id, TaskId = myTasks[0].Id));
			insert myTRs;

            Test.getEventBus().deliver();
            
            List<ActivityContact__c> checkAC = [SELECT Id, Contact__c FROM ActivityContact__c WHERE ActivityId__c = :myTasks[0].Id];
            system.AssertEquals(checkAC.size(),3,'checkAC.size() - Number of Activity Contacts after insert is not correct');
            Map<Id,ActivityContact__c> checkACMap = new Map<Id,ActivityContact__c>();
            for (ActivityContact__c ac : checkAC) {
                checkACMap.put(ac.Contact__c,ac);
            }
            system.Assert(checkACMap.containsKey(myContacts2[0].Id),'myContacts2[0].Id is missing from Activity Contacts');
            system.Assert(checkACMap.containsKey(myContacts2[1].Id),'myContacts2[1].Id is missing from Activity Contacts');
            
            Test.enableChangeDataCapture();
            delete myTRs;
            Test.getEventBus().deliver();
                     
            List<ActivityContact__c> checkACdel = [SELECT Id, Contact__c FROM ActivityContact__c WHERE ActivityId__c = :myTasks[0].Id];
            system.AssertEquals(checkACdel.size(),1,'checkACDel.size() - Number of Activity Contacts after delete is not correct');

        }
               
    }
    
}