objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>The MARS status of the account, Data Flow: Mars -&gt; SF</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Source: MARS na_load_rep.StatCd
Loaded by a nightly job.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ExternalCommunitySettings__c.object
<CustomObject>
    <fields>
        <fullName>BatchUserJobNumberOfDays__c</fullName>
        <description>BatchUserJobNumberOfDays  to query for job.  Used in the parameter LAST_N_DAYS.  By default , it is one.  Used in CommunitiesReactivateUserBatch</description>
        <inlineHelpText>Users that were modified in the last 'n' days get picked up for processing to determine if they should be reactivated. Since we run the batch job nightly, this should be set to 1. If we run the batch job weekly, it should be set to 7.</inlineHelpText>
        <label>BatchUserJobNumberOfDays</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CommunityInternalSender__c</fullName>
        <description>To addresses for Batch jobs</description>
        <inlineHelpText>Determines the email address that batch completion emails should go to.  This should be dat@ngam.natixis.com unless you are testing.</inlineHelpText>
        <label>CommunityInternalSender</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CommunitySenderDisplayName__c</fullName>
        <description>CommunitySenderDisplayName for emails.  Necessary for sending the notification that new statements have been posted.</description>
        <inlineHelpText>Indicates the email from name on the notification to FA's that new statements have been posted.  This should always be Portal Solutions unless branding changes.</inlineHelpText>
        <label>CommunitySenderDisplayName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CommunitySenderEmail__c</fullName>
        <description>Email for sending the comunity email</description>
        <inlineHelpText>Indicates the email from address on the notification to FA's that new statements have been posted. This should always be Portal Solutions unless branding changes</inlineHelpText>
        <label>CommunitySenderEmail</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndClientCommunityAccountName__c</fullName>
        <description>The name of the Account (Firms Office) to which End Client/Interested 3rd Party community contacts will belong.</description>
        <inlineHelpText>The name of the Account (Firms Office) to which new End Client/Interested 3rd Party community contacts belong.  This should always be NGAM DISTRIBUTION, L.P., PORTAL END CLIENTS</inlineHelpText>
        <label>EndClientCommunityAccountName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExternalEmailTemplate__c</fullName>
        <description>Email's template developer name use for sending the emails to EndClient</description>
        <inlineHelpText>The email template used for notifying community users of new statements.</inlineHelpText>
        <label>ExternalEmailTemplateDevName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InactivateDaysForUserLogin__c</fullName>
        <defaultValue>180</defaultValue>
        <description>Inactivate the users after x numbers of days</description>
        <inlineHelpText>Users that have not logged in after this number of days are inactivated in a nightly batch job.</inlineHelpText>
        <label>InactivateDaysForUserLogin</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PemissionSetForEndClient__c</fullName>
        <description>Permission set for end user, Comma delimited string wth permission set's api names</description>
        <inlineHelpText>Permission Set that is assigned to End Client contact user records during setup of Financial Account Contact (type = End Client).</inlineHelpText>
        <label>PemissionSetForEndClient</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PermissionSetsForFAUser__c</fullName>
        <description>Permission set for FA user</description>
        <inlineHelpText>Permission Set that is assigned to Financial Advisor contact user records during setup of Financial Account Contact (type = Financial Advisor).</inlineHelpText>
        <label>PermissionSetsForFAUser</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PotalUserName__c</fullName>
        <description>Portal user name</description>
        <label>PotalUserName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProfileForFAUser__c</fullName>
        <description>Profile name for FA</description>
        <inlineHelpText>Profile that is assigned to Financial Advisor contact user records during setup of Financial Account Contact (type = Financial Advisor).</inlineHelpText>
        <label>ProfileForFAUser</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>To the custom setting for external communities</description>
    <label>ExternalCommunitySettings</label>
</CustomObject>

objects/FinancialAccountContact__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact related to the Financial Account</description>
        <inlineHelpText>Contact related to the Financial Account</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Financial Account Contact</relationshipLabel>
        <relationshipName>Financial_Account_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Indicates the status of the contact's relationship to the Financial Account</description>
        <inlineHelpText>Indicate the status of the contact's relationship to the Financial Account</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                    <default>true</default>
                    <label>Current</label>
                </value>
                <value>
                    <fullName>Former</fullName>
                </value>
                <value>
                    <fullName>Inactivated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>View_Financial_Account_in_Community__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates if this contact should see the Financial Account in the community.</description>
        <inlineHelpText>If checked, the contact will be able to see the Financial Account in the community</inlineHelpText>
        <label>View Financial Account in Community?</label>
        <type>Checkbox</type>
    </fields>
    <description>Tracks contacts associated with a Financial Account.  Dictates which contacts (community users) can see a particular Financial Account in the community.</description>
    <label>Financial Account Contact</label>
    <nameField>
        <displayFormat>FAC-{000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ActiveUserProxy__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Just to avoid DML Mixed operation exception</description>
        <label>ActiveUserProxy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <description>This field will be populated by EPAT-SFDC job with ITSM# - Effective Date - EPAT Request Type. Every new request will append to the previous comments. If manually added, please add teh SR# or Incident task#.</description>
        <inlineHelpText>This field will be populated by EPAT-SFDC job with ITSM# - Effective Date - EPAT Request Type. Every new request will append to the previous comments. If manually added, please add teh SR# or Incident task#.</inlineHelpText>
        <label>Comments</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CommunityStatus__c</fullName>
        <description>For community users who have been inactivated, this field contains the reason for inactivation.  If the user is active, it contains "Active".</description>
        <inlineHelpText>For community users who have been inactivated, this field contains the reason for inactivation.  If the user is active, it contains "Active".</inlineHelpText>
        <label>Community Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReactivatedDatetime__c</fullName>
        <description>Set by trigger when existing user goes from Inactive to Active</description>
        <label>Reactivated Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Used in the Affiliate Request Flow to filter 'Requested on Behalf' of. Can not use Out of Box field for end users.</description>
        <formula>IF( IsActive = True, True, False)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TermsConditionsAcceptAfterDecline__c</fullName>
        <formula>IF( TermsConditionsLastAccepted__c &gt;  TermsandConditionsLastDeclined__c , TRUE, FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Terms Conditions Accept After Decline</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TermsandConditionsLastDeclined__c</fullName>
        <description>Datetime stamp set each time a community user declines the Terms and Conditions.</description>
        <inlineHelpText>Datetime stamp set each time a community user declines the Terms and Conditions.</inlineHelpText>
        <label>Terms and Conditions Last Declined</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CommunitiesInactivateUserBatch.cls
global class CommunitiesInactivateUserBatch implements Database.Batchable<sObject>, Database.Stateful{
    
    // This Batch job inactivates users:
    //  - who do not any financial accounts associated with them and who are not part of any other community
    //  - who have not logged in for x days where x is set in Custom Settings
    //  - who have declined T&C
    
    Public integer Count = 0;
    public String query = ' SELECT Id, Username,isActive, LastName, FirstName, Name, ContactId, AccountId, PortalRole, IsPortalEnabled FROM User where IsPortalEnabled = true and isActive =true  ';
    
    // Get info from Custom setting
    static ExternalCommunitySettings__c myCustomSetting = ExternalCommunitySettings__c.getValues('EstatementCommunity');
    static string EStatementFirmName = myCustomSetting.EndClientCommunityAccountName__c;
    static string PortalUserName = myCustomSetting.PotalUserName__c;
    static string PermissionSetForEndClient =   myCustomSetting.PemissionSetForEndClient__c;
    static string ProfileForFAUser =  myCustomSetting.ProfileForFAUser__c;
    static String PermissionSetsForFAUser = myCustomSetting.PermissionSetsForFAUser__c;
    static Integer InactivateDaysForUserLogin = (Integer)myCustomSetting.InactivateDaysForUserLogin__c;
    
    Public String msg = '';
    Public String logmsg = '';
    
    static String EmailSenderAddress = myCustomSetting.CommunitySenderEmail__c;
    static String ExternalEmailTemplateDevName = myCustomSetting.ExternalEmailTemplate__c;  
    static String CommunityInternalSender = myCustomSetting.CommunityInternalSender__c;
    static String CommunitySenderDisplayName = myCustomSetting.CommunitySenderDisplayName__c;
    static String CompareNDays = '1';
    
    //static List<FinancialAccountContact__c> facToInactivate = new List<FinancialAccountContact__c>();
    
    global CommunitiesInactivateUserBatch() {
        System.Debug('CommunitiesInactivateUserBatch - Update Potal Users Inactive');
        try
        {
            CompareNDays = myCustomSetting.BatchUserJobNumberOfDays__c;
        }
        catch(Exception ex)
        {
            CompareNDays='1';
        }
        
        query = query.replace('@Ndays', CompareNDays);
        
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {       
        System.Debug('CommunitiesInactivateUserBatch Synching  for InActivating Community Users - Using Query');          
        System.Debug('Query - ' + query);      
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<User> scope) {
        system.debug('scope: ' + scope);
        
        List<String> temp = new List<String>();
        List<PermissionSetAssignment> AssignmentToDelete = new List<PermissionSetAssignment>();		
        Map<Id,PermissionSetAssignment> AssignmentToDeleteMap = new Map<Id,PermissionSetAssignment>();
        
        Map<id,User> UserIds = new Map<id,User>();
        Map<id,User> ContactIds = new Map<id,User>();        
        for (User u : scope)
        {
            if(!UserIds.containsKey(u.Id)) UserIds.put(u.Id,u);
            if(!ContactIds.containsKey(u.ContactId)) ContactIds.put(u.ContactId,u); 
        }
        
        // Create msg to include in the log table
        logmsg = 'ContactIds Ids Count ' +  ContactIds.size();
        System.Debug(logmsg);
        
        logmsg = 'UserIds Ids Count ' +  UserIds.size();
        System.Debug(logmsg);
        
        Map<Id,PermissionSetAssignment> permAssignmentsFA = new Map<Id,PermissionSetAssignment>();
        Map<Id,PermissionSetAssignment> permAssignmentsEC = new Map<Id,PermissionSetAssignment>();
        Map<Id,PermissionSetAssignment> permAssignmentsOther = new Map<Id,PermissionSetAssignment>();
        
        List<PermissionSetAssignment> pSA = [SELECT PermissionSet.Name,PermissionSet.Id,Assignee.Id,Id 
                                             FROM PermissionSetAssignment
                                             WHERE AssigneeId in: UserIds.keySet()];
        
        for (PermissionSetAssignment pSS : pSA) {
            
            system.debug('pSS: ' + pSS.PermissionSet.Name);
            system.debug('PermissionSetForEndClient: ' + PermissionSetForEndClient);
            system.debug('PermissionSetsForFAUser: ' + PermissionSetsForFAUser);
            
            
            if (pSS.PermissionSet.Name == PermissionSetForEndClient) {
                permAssignmentsEC.put(pSS.Assignee.Id,pSS);
            }
            
            if (pSS.PermissionSet.Name == PermissionSetsForFAUser) {
                permAssignmentsFA.put(pSS.Assignee.Id,pSS);
            }
            
            if (pSS.PermissionSet.Name != PermissionSetsForFAUser &&
                pSS.PermissionSet.Name != PermissionSetForEndClient &&
                pSS.PermissionSet.Name.left(3) != 'X00') {
                    permAssignmentsOther.put(pSS.Assignee.Id,pSS);    
                }
            
        }
        
        List<User> UsersToUdpate = new List<User>(); 
        Map<Id,User> UsersToUdpateMap = new Map<Id,User>(); 
        List<Id> AssignmentToRemove = new List<Id>(); 
        
        // Inactivate User that has no Current, Viewable Financial Account Contact records
        Set<Id> currentFAC = new Set<Id>();
        AggregateResult[] gFAC = [SELECT Contact__c, Count(Id) FROM FinancialAccountContact__c
                                  WHERE Status__c = 'Current'
                                  AND View_Financial_Account_in_Community__c = TRUE
                                  GROUP BY Contact__c];
        
        for (AggregateResult ar : gFAC)  {
            currentFAC.add((Id)ar.get('Contact__c'));
        }
        
        system.debug('currentFAC: ' + currentFAC);
        
        for (User u : scope) {
            
            Boolean OtherCommunities = FALSE;
            if (permAssignmentsOther.containsKey(u.Id)) OtherCommunities = TRUE;
            
            system.debug('User Id: ' + u.Id);
            system.debug('Contact Id: ' + u.ContactId);
            
            if (!currentFAC.contains(u.ContactId)) {
                system.debug('No Current FAC');
                if (permAssignmentsEC.containsKey(u.Id)) AssignmentToDeleteMap.put(permAssignmentsEC.get(u.Id).Id, permAssignmentsEC.get(u.Id));
                if (permAssignmentsFA.containsKey(u.Id)) AssignmentToDeleteMap.put(permAssignmentsEC.get(u.Id).Id, permAssignmentsFA.get(u.Id));
                if(!OtherCommunities)
                {
                    User n = new User(id=u.Id, IsActive=false, ActiveUserProxy__c = false, CommunityStatus__c = 'Inactive: No Financial Accounts', Comments__c ='No active Financial Accounts, Updated to Inactive ' + system.now());
                    if(UsersToUdpateMap.containsKey(n.Id) == false) 
                    {
                        system.debug('Adding User: ' + n.Id);
                        UsersToUdpateMap.put(n.Id,u);
                        UsersToUdpate.add(n); 
                    }
                }
                
            }
        }
        
        // Declined Terms and have not accepted since decline
        Map<Id,User> TermsDeclinedList = new map<Id,User>([SELECT Id, Username,isActive, LastName, FirstName, Name, ContactId, AccountId, PortalRole, 
                                                           IsPortalEnabled 
                                                           FROM User 
                                                           WHERE IsPortalEnabled = TRUE
                                                           AND isActive = TRUE 
                                                           AND TermsandConditionsLastDeclined__c != null
                                                           AND TermsConditionsAcceptAfterDecline__c = FALSE]);
        
        for (User u : TermsDeclinedList.values()) 
        {    
            if (permAssignmentsEC.containsKey(u.Id)) AssignmentToDeleteMap.put(permAssignmentsEC.get(u.Id).Id, permAssignmentsEC.get(u.Id));
            if (permAssignmentsFA.containsKey(u.Id)) AssignmentToDeleteMap.put(permAssignmentsEC.get(u.Id).Id, permAssignmentsFA.get(u.Id));
            User n =  new User(id=u.Id, IsActive=false, ActiveUserProxy__c = false ,CommunityStatus__c = 'Inactive: Declined Terms and Conditions',Comments__c ='Declined Terms and conditions, Updated to Inactive, ' + system.now());
            if(!UsersToUdpateMap.containsKey(n.Id)) {
                UsersToUdpateMap.put(n.Id,u);
                UsersToUdpate.add(n); 
            }
        }        
        
        // Haven't logged in
        if(InactivateDaysForUserLogin > 0)
        {
            Date d = System.today() - InactivateDaysForUserLogin;
            String CommentText = 'Inactivating user who has not logged in for ' + InactivateDaysForUserLogin +' days';
            Map<Id,User> NotLoggedIn = new Map<Id,User>([SELECT Id, CreatedDate, Username,LastName,FirstName, lastloginDate
                                                         FROM User 
                                                         WHERE  IsActive = TRUE
                                                         AND IsPortalEnabled = TRUE
                                                         AND CreatedDate < :d
                                                         AND (ReactivatedDateTime__c < :d OR ReactivatedDateTime__c = null)
                                                         AND (LastLoginDate = null OR lastloginDate < : d)]); 
            
            for (User u : NotLoggedIn.values()) {
                Boolean OtherCommunities = FALSE;
                if (permAssignmentsOther.containsKey(u.Id)) OtherCommunities = TRUE;
                { 
                    if (permAssignmentsEC.containsKey(u.Id)) AssignmentToDeleteMap.put(permAssignmentsEC.get(u.Id).Id, permAssignmentsEC.get(u.Id));
                    if (permAssignmentsFA.containsKey(u.Id)) AssignmentToDeleteMap.put(permAssignmentsEC.get(u.Id).Id, permAssignmentsFA.get(u.Id));
                    if(!OtherCommunities)
                    {
                        User n =  new User(id=u.Id, ActiveUserProxy__c = false,IsActive=false, CommunityStatus__c = 'Inactive: User Did Not Log In',Comments__c = CommentText + system.now());
                        if(!UsersToUdpateMap.containsKey(n.Id)) 
                        {UsersToUdpateMap.put(u.Id,u);
                         UsersToUdpate.add(n); }   
                    }
                    
                }
            }
        }
        
        for (User rePS : UsersToUdpate) {
        }
        
        if ( !UsersToUdpate.isEmpty())
        {
            msg = 'Inactivate Users  Count for Today' +  UsersToUdpate.size();
            System.Debug(msg);update UsersToUdpate;
        } 
        
        for (PermissionSetAssignment atd : AssignmentToDeleteMap.values()) {
            AssignmentToDelete.add(atd);
        }
        
        if(!AssignmentToDelete.isEmpty())
        { 
            msg = 'Total Permission sets Needs to be removed  for Today' +  AssignmentToDelete.size();
            System.Debug(msg);Database.delete(AssignmentToDelete,false); 
        }
        
/*        Set<Id> financialAccountContactsSet = new Set<Id>();
        List<User> finAcctUser = [SELECT Id, ContactId FROM User WHERE Id IN :UsersToUdpate];
        
        for (User uti : finAcctUser) {
            financialAccountContactsSet.add(uti.ContactId);
        }
        
        facToInactivate = [SELECT Id FROM FinancialAccountContact__c WHERE Contact__c IN :financialAccountContactsSet
                           AND Status__c != 'Inactivated'];
        for (FinancialAccountContact__c f : facToInactivate) {
            f.Status__c = 'Inactivated';
        }*/
        
        if (UsersToUdpate.size() > 0) {
            msg = '<p>Inactivated users : ' + UsersToUdpate.size() +  '</p><p>PermissionAssignmentToRemoved : ' + AssignmentToRemove.size() + '</p>';
            String TempMsg = '<br/><table  border= "1" >';
            TempMsg = TempMsg + '<tr><th> User Id  </th><th> User Name </th><th> Reason For Deactivation </th></tr>';
            for (User u: UsersToUdpate)
            {   User old = UsersToUdpateMap.get(u.Id);
             TempMsg = TempMsg + '<tr><td>' +u.Id + '</td><td>' + old.FirstName + ' ' + old.LastName + '</td><td>' +u.CommunityStatus__c + '</td></tr>';
            }             
            TempMsg = TempMsg + '</table><br/>';
            msg = msg +TempMsg;
        }
    }
    
    public  Static  void SendFinishEmail(String msg,string subject)
    {
        if (msg != null) {
            List<String> toAddresses = CommunityInternalSender.Split(',');            
            CommunitiesEmailHelper.sendEmail(toAddresses, null, EmailSenderAddress, CommunitySenderDisplayName, msg, subject,true);
        }
    }
    
    global void finish(Database.BatchableContext BC) {
        
        Datetime d = Datetime.now().addDays(-1);
        
        List<User> InactivatedUsers = [SELECT Id, Username,isActive, LastName, FirstName, Name, 
                                       ContactId, AccountId, PortalRole, IsPortalEnabled 
                                       FROM User 
                                       WHERE IsPortalEnabled = TRUE 
                                       AND isActive = FALSE
                                       AND LastModifiedDate >: d];
        Set<Id> IUContactIdSet = new Set<Id>();
        
        for (User u : InactivatedUsers) {
            IUContactIdSet.add(u.ContactId);
        }
        
        List<FinancialAccountContact__c> FACToInactivate = [SELECT Id FROM FinancialAccountContact__c 
                                                            WHERE Contact__c IN :IUContactIdSet
                                                            AND Status__c != 'Inactivated'];
        
        for (FinancialAccountContact__c f : FACToInactivate) {
            f.Status__c = 'Inactivated';
        }
        
        system.debug('FACToInactivate: ' + FACToInactivate);

        update FACToInactivate;
        
        try{
            
            System.debug('query : ' + query );      
            //String logMsg = msg;
            if(logMsg.length() > 250)logMsg=logMsg.substring(1,250);
            ApexActivitiesStatsLogger.logMessage('CommunitiesEstatementInactivateUserBatch', 'CommunitiesEstatementInactivateUserBatch', logMsg, query, '', 'User,FinacialAccountContact__c');
            System.debug('sending finish Email : ' ); 
            system.debug('msg: ' + msg);
            if (!String.isblank(msg)) {
                SendFinishEmail(msg,'Inactivate User batch job ');
            }
            
        } catch (Exception e) {
            System.debug('CommunitiesEstatementInactivateUserBatch - Exception: ' + e);            
        }         
    }
    
}