objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Affiliate</fullName>
        <active>true</active>
        <label>Affiliate</label>
    </recordTypes>
</CustomObject>

objects/ActivityContact__c.object
<CustomObject>
    <fields>
        <fullName>ActivityContact__c</fullName>
        <description>This Field is populated by the trigger and contains ActivityId__c + Contact__c, it is used to ensure that no duplicate contact on an activity (does not allow duplicate)</description>
        <label>ActivityContact</label>
        <length>37</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ActivityId__c</fullName>
        <description>This fake Id field is binded to Task through the use of the "Contacts" Grid build in the GridBuddy application. It is populated by GB with Task.Id</description>
        <externalId>true</externalId>
        <label>ActivityId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityType__c</fullName>
        <description>Used to control the Sub Type field and not displayed in the UI. The out of box field Type is displayed in the UI.</description>
        <label>Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Meeting</fullName>
                </value>
                <value>
                    <fullName>Call</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is entered through the Gridbuddy Form and is set to the id of the contact entered through the form. It is used by the trigger to create the TaskRelation entry to the related Task</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Activity Contacts</relationshipLabel>
        <relationshipName>ActivityContacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <description>Each activity will have 1 to Many contacts. These activity related contacts are stored in this object along necessary attributes to allow for advanced activity reporting. This Table is synched up with the TaskRelation standard object through the "ActivityContactTrigger" trigger and the "ActivityContactTriggerHandler" Class.
This object is "virtually" related to Task through the use of the "ActivityId__c" field. This fake Id field is binded to Task through the use of the "Contacts" Grid build in the GridBuddy application.</description>
    <label>Activity Contact</label>
    <nameField>
        <displayFormat>AC-{0000000000}</displayFormat>
        <label>Activity Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Contacts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>CaseCreatedviaFlow__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this case was created via a flow, the value will be true.  This is used for a validation rule to ensure that cases come through the flow rather than being entered directly by users.</description>
        <label>Case Created via Flow</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Artemus.Request.requestor_id
varchar(100)</description>
        <label>Requester</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Requestor</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel><enableHistory>true</enableHistory>
</CustomObject>

objects/Contact.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Affiliate</fullName>
        <active>true</active>
        <label>Affiliate</label>
    </recordTypes>
</CustomObject>

objects/NGAMSettingsHierarchy__c.object
<CustomObject>
    <fields>
        <fullName>ByPassAccountValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows entity to by-pass validation rules on Account</description>
        <inlineHelpText>Allows entity to by-pass validation rules on Account</inlineHelpText>
        <label>By-Pass Account Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NGAM Settings - Hierarchy</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ActivityChannelName__c</fullName>
        <description>Used To Tag the Activities and Opportunities created by the user.</description>
        <inlineHelpText>READ ONLY FIELD : This Will be populated by the UserTerritory__c assignment when the Territory Assignment is tagged as an Activity Territory. Please never update this field directly. Instead Delete/Insert the relevant UserTerritory__c record.</inlineHelpText>
        <label>Activity Channel Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryName__c</fullName>
        <description>Used To Tag the Activities and Opportunities created by the user.</description>
        <inlineHelpText>READ ONLY FIELD : This Will be populated by the UserTerritory__c assignment when the Territory Assignment is tagged as an Activity Territory. Please never update this field directly. Instead Delete/Insert the relevant UserTerritory__c record.</inlineHelpText>
        <label>Activity Territory Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EventRelationSyncBatch_Test.cls
@isTest
private class EventRelationSyncBatch_Test {
    static testMethod void EventRelationSyncBatchTesting() {
        
/*20190707 - No Longer Need this since using trigger on EventRelationChangeEvent    
        NGAMSettingsHierarchy__c hsettings = NGAMSettingsHierarchy__c.getOrgDefaults();
        hsettings.ByPassAccountValidationRules__c  = TRUE;
        upsert hsettings NGAMSettingsHierarchy__c.Id;

        
        User u = DataFactory.createSystemAdminUser();
        insert u; 
        
        List<Account> myAccounts = DataFactory.createTestAccounts(1);
        insert myAccounts;
        
        List<Contact> myContacts = DataFactory.createTestContacts(201, myAccounts, false);
        insert myContacts;   
        
        //Setup Data
        Id affiliateEventRecTypeId = Schema.SObjectType.Event.getRecordTypeInfosByName().get('Affiliate Event').getRecordTypeId();
        Id affiliateCaseRecTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Affiliate Request').getRecordTypeId();
        Id affiliateAccountRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Affiliate').getRecordTypeId();
        
        List<Account> myAffiliateAccounts = DataFactory.createTestAccounts(1);
        myAffiliateAccounts[0].Type = 'Affiliate';
        myAffiliateAccounts[0].RecordTypeId = affiliateAccountRecTypeId;
        insert myAffiliateAccounts;
        
        List<Contact> myAffiliateContacts = DataFactory.createTestContacts(1, myAffiliateAccounts, false);
        insert myAffiliateContacts;   
        
        List<Account> affiliateAccountId = [SELECT Id,Name FROM Account WHERE Type = 'Affiliate' LIMIT 1]; 
        List<Contact> contacts = DataFactory.createTestContacts(1, affiliateAccountId, false);
        insert contacts;
        
        List<User> OwnerId = [SELECT Id,ActivityTerritoryName__c,ActivityChannelName__c
                              FROM User
                              WHERE IsActive = TRUE
                              AND UserType = 'Standard'
                              AND ActivityTerritoryName__c != null
                              AND ActivityChannelName__c != null
                              LIMIT 1];
        
        List<User> RequestorId = [SELECT Id 
                                  FROM User
                                  WHERE IsActive = TRUE
                                  AND UserType = 'Standard'
                                  LIMIT 1];
        
        Case c1 = New Case(OwnerId=u.Id,Requestor__c = u.Id,Type='Travel',Contact=contacts[0],RecordTypeId=affiliateCaseRecTypeId,AccountId=myAffiliateAccounts[0].Id,CaseCreatedviaFlow__c=TRUE);
        insert c1;
        
        Datetime myDateTime = DateTime.Now();
        //BeforeInsert
        Event e00 = New Event(OwnerId=u.Id,WhatId=c1.Id,
                              ShortSubject__c='Test1',Type='Meeting',
                              StartDateTime=myDateTime,
                              EndDateTime=myDateTime.addMinutes(30), WhoId=contacts[0].Id);
        insert e00;
        
        List<EventRelation> listEr= new List<EventRelation>();
        for(Contact cur:myContacts)
        {
            listEr.Add(new eventrelation(eventid=e00.id,relationid=cur.id,status='Accepted'));
        }
        insert listEr;    */        
        
        Test.startTest(); 
        EventRelationSyncBatch trac = new EventRelationSyncBatch();
        
/*20190707 - No Longer Need this since using trigger on TaskRelationChangeEvent
        DateTime X30MinutesAgo = myDateTime.addMinutes(-15);
        String dateTimeFormat = X30MinutesAgo.format('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'');
        
        trac.query = 'Select Product__c,Type,id,ActivityType__c,Whoid,WhatId,EventWhoIds,Subject,ActivityDate,OwnerId,recordTypeID, (select id, RelationId,EventId from EventRelations where iswhat=false) from Event Where LastModifiedDate = TODAY AND  LastModifiedDate > ' + dateTimeFormat;
*/      
        trac.query = 'Select Id FROM EventRelation WHERE Id = null';
        ID tracid = database.executeBatch(trac,2000); 
        Test.stopTest();
/*20190707 - No Longer Need this since using trigger on TaskRelationChangeEvent
        List<ActivityContact__c> aCTest = [SELECT Id,ActivityId__c FROM ActivityContact__c WHERE Contact__c in :myContacts];
        system.assertEquals(acTest.size(),myContacts.size());
*/
    }
}