objects/Account.object
<CustomObject>
    <fields>
        <fullName>ActiveCDRQualitativeData__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used in CDR processing; this field refers to the Contact's active CDR Qualitative Data record.  Set by Apex.</description>
        <label>Active CDR Qualitative Data</label>
        <referenceTo>CDRQualitativeData__c</referenceTo>
        <relationshipLabel>Firms</relationshipLabel>
        <relationshipName>Firms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FirmOfficeID18__c</fullName>
        <description>Case Safe 18-digit SFID of the Account</description>
        <formula>CASESAFEID(Id)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Firm/Office ID 18</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LegalName__c</fullName>
        <description>The Legal Name from CDR Qualitative Data; set by trigger</description>
        <label>Legal Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The MARS status of the account, Data Flow: Mars -&gt; SF</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Firm</fullName>
        <active>true</active>
        <description>Firms, offices, and reps are organized into a hierarchy. This means that each rep must be assigned to an office, and each office must be assigned to a firm. Firm is the highest level in the hierarchy.</description>
        <label>Firm</label>
    </recordTypes>
</CustomObject>

objects/AdditionalInfo__c.object
<CustomObject>
    <fields>
        <fullName>ActiveCDRQualitativeData__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Active CDR Qualitative Data</label>
        <referenceTo>CDRQualitativeData__c</referenceTo>
        <relationshipLabel>Additional Info</relationshipLabel>
        <relationshipName>AdditionalInfos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CaseSafeId__c</fullName>
        <formula>CASESAFEID(Id)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Safe Id</label>
        <type>Text</type>
    </fields>
    <description>Tracks additional information for CDR Qualitative Data</description>
    <label>Additional Info</label>
    <nameField>
        <label>Additional Info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional Info</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CDRQualitativeData__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Firm</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CDR Qualitative Data (Firm)</relationshipLabel>
        <relationshipName>CDRQualitativeData</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AdditionalInfo__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Additional Info</label>
        <referenceTo>AdditionalInfo__c</referenceTo>
        <relationshipLabel>CDR Qualitative Data (Additional Info)</relationshipLabel>
        <relationshipName>CDRQualitativeData</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ApprovalStatus__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Submitted</fullName>
                    <default>true</default>
                    <label>Not Submitted</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Benchmark__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Benchmark</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>CDR Qualitative Data (Benchmark)</relationshipLabel>
        <relationshipName>CDRQualitativeDataBenchmarks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CUSIP__c</fullName>
        <label>CUSIP</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CaseSafeId__c</fullName>
        <formula>CASESAFEID(Id)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Safe Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChildAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Child Firm</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CDR Qualitative Data (Child Firm)</relationshipLabel>
        <relationshipName>CDRQualitativeDataChildFirms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ChildProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Child Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>CDR Qualitative Data (Child Product)</relationshipLabel>
        <relationshipName>CDRQualitativeDataChildProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CDR Qualitative Data (Contact)</relationshipLabel>
        <relationshipName>CDRQualitativeData</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EffectiveDate__c</fullName>
        <defaultValue>NOW()+30</defaultValue>
        <label>Effective Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>HasPendingActivationRow__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Pending Activation Row</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HasStagingRow__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Staging Row</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HistoricalDate__c</fullName>
        <label>Historical Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ISIN__c</fullName>
        <label>ISIN</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InceptionDate__c</fullName>
        <label>Inception Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NextPendingActivationDate__c</fullName>
        <label>Next Pending Activation Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>NextStagingDate__c</fullName>
        <label>Next Staging Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ParentKey__c</fullName>
        <formula>CASE( RecordType.Name,
"Additional Info", AdditionalInfo__c,
"Benchmark", Benchmark__c,
"Benchmark-Additional Info", Benchmark__c &amp; AdditionalInfo__c,
"Contact", Contact__c,
"Contact-Additional Info", Contact__c &amp; AdditionalInfo__c,
"ETF", Product__c,
"Firm", Account__c,
"Firm-Additional Info", Account__c &amp; AdditionalInfo__c,
"Firm-Child Firm", Account__c &amp; ChildAccount__c,
"Firm-Contact", Account__c &amp; Contact__c,
"Firm-Product", Account__c &amp; Product__c,
"Mutual Fund", Product__c,
"Product-Additional Info", Product__c &amp; AdditionalInfo__c,
"Product-Benchmark", Product__c &amp; Benchmark__c,
"Product-Child Product", Product__c &amp; ChildProduct__c,
"Product-Contact", Product__c &amp; Contact__c,
"Share Class", Product__c,
"")</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Key</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>CDR Qualitative Data (Product)</relationshipLabel>
        <relationshipName>CDRQualitativeDataProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ShareClass__c</fullName>
        <label>Share Class</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ShareClass</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SortOrder__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Staging</fullName>
                </value>
                <value>
                    <fullName>Pending Activation</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Historical</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TradingSymbol__c</fullName>
        <label>Trading Symbol</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <description>This object stores qualitative data about contacts, firms, products, additional information and their relationships to one another.</description>
    <label>CDR Qualitative Data</label>
    <nameField>
        <label>CDR Qualitative Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CDR Qualitative Data</pluralLabel>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Benchmark</fullName>
        <active>true</active>
        <description>Use this for Benchmark CDR Qualitative Data</description>
        <label>Benchmark</label>
    </recordTypes>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Use this for Contact CDR Qualitative Data</description>
        <label>Contact</label>
    </recordTypes>
    <recordTypes>
        <fullName>ETF</fullName>
        <active>true</active>
        <description>Use this for ETFs</description>
        <label>ETF</label>
    </recordTypes>
    <recordTypes>
        <fullName>Firm</fullName>
        <active>true</active>
        <description>Use this for Firm CDR Qualitative Data</description>
        <label>Firm</label>
    </recordTypes>
</CustomObject>

objects/CDRSettings__c.object
<CustomObject>
    <fields>
        <fullName>OverrideSetStatusOnCreate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Keeps the trigger from assigning a new record to Draft status on creation.  Can be used for data loading directly into a specific status.</description>
        <inlineHelpText>Keeps the trigger from assigning a new record to Draft status on creation.  Can be used for data loading directly into a specific status.</inlineHelpText>
        <label>Override Set Status On Create</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OverrideTriggerValidations__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Overrides trigger validations on status changes, effective dates, etc. when editing or creating CDR Qualitative Data records</description>
        <inlineHelpText>Overrides trigger validations on status changes, effective dates, etc. when editing or creating CDR Qualitative Data records</inlineHelpText>
        <label>Override Trigger Validations</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Settings that control CDR processes</description>
    <label>CDR Settings</label>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ActiveCDRQualitativeData__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field used in the CDR Process</description>
        <label>Active CDR Qualitative Data</label>
        <referenceTo>CDRQualitativeData__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CaseSafeId__c</fullName>
        <description>18 digit unique Saleforce ID</description>
        <formula>CASESAFEID(Id)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Safe Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Source: MARS na_load_rep.StatCd
Loaded by a nightly job.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>ActiveCDRQualitativeData__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Active CDR Qualitative Data</label>
        <referenceTo>CDRQualitativeData__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CUSIP__c</fullName>
        <externalId>true</externalId>
        <label>CUSIP</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CaseSafeId__c</fullName>
        <formula>CASESAFEID(Id)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Safe Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ISIN__c</fullName>
        <label>ISIN</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InceptionDate__c</fullName>
        <label>Inception Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LegalName__c</fullName>
        <label>Legal Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShareClass__c</fullName>
        <label>Share Class</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ShareClass</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACTIVE</fullName>
                </value>
                <value>
                    <fullName>CLOSED TO NEW INVESTORS</fullName>
                </value>
                <value>
                    <fullName>INACTIVE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TradingSymbol__c</fullName>
        <externalId>true</externalId>
        <label>Trading Symbol</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Benchmark</fullName>
        <active>true</active>
        <description>Use this for Benchmarks</description>
        <label>Benchmark</label>
    </recordTypes>
    <recordTypes>
        <fullName>ETF</fullName>
        <active>true</active>
        <description>Use this for ETFs</description>
        <label>ETF</label>
    </recordTypes>
</CustomObject>

globalValueSets/ShareClass.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
    </customValue>
    <customValue>
        <fullName>B</fullName>
    </customValue>
    <customValue>
        <fullName>C</fullName>
    </customValue>
    <customValue>
        <fullName>N</fullName>
    </customValue>
    <customValue>
        <fullName>T</fullName>
    </customValue>
    <customValue>
        <fullName>Y</fullName>
    </customValue>
    <customValue>
        <fullName>Admin</fullName>
    </customValue>
    <customValue>
        <fullName>Advisor</fullName>
    </customValue>
    <customValue>
        <fullName>Institutional</fullName>
    </customValue>
    <customValue>
        <fullName>Investor</fullName>
    </customValue>
    <customValue>
        <fullName>Retail</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <masterLabel>Share Class</masterLabel>
</GlobalValueSet>

classes/CDRQualitativeDataTriggerHandler.cls
public class CDRQualitativeDataTriggerHandler {
    
    public static void dateDupeChecks (List<CDRQualitativeData__c> myNewCDR, Map<Id,CDRQualitativeData__c> myOldCDRMap) {
        
        CDRSettings__c settings = CDRSettings__c.getvalues('NGAM');
        
        if (settings.OverrideTriggerValidations__c == FALSE) {
            Map<String, CDRQualitativeData__c> cdrMap= new Map<String, CDRQualitativeData__c>();
            Map<String,CDRQualitativeData__c> parentKeyDraftMap = new Map<String,CDRQualitativeData__c>();
            Map<String,CDRQualitativeData__c> parentKeyActHistMap = new Map<String,CDRQualitativeData__c>();
            Set<String> parentKeySet = new Set<String>();
            Map<String,CDRQualitativeData__c> parentKeyEffDtMap = new Map<String,CDRQualitativeData__c>();
            
            for (CDRQualitativeData__c ahm : myNewCDR) {
                parentKeySet.add(ahm.ParentKey__c);
                if ((ahm.Status__c == 'Active' || ahm.Status__c == 'Historical' || ahm.Status__c == 'Pending Activation')  
                    && System.Trigger.isInsert) {
                        parentKeyActHistMap.put(ahm.ParentKey__c, ahm);
                    }
            }
            
            for (CDRQualitativeData__c cdr : myNewCDR) {
                
                if (cdr.Status__c == 'Draft') {
                    if (parentKeyDraftMap.containsKey(cdr.ParentKey__c)) {
                        cdr.addError('There is another Draft record already; please coordinate updates');
                    } else {
                        parentKeyDraftMap.put(cdr.ParentKey__c, cdr);
                    }
                }
                
                if (cdr.Status__c == 'Draft') {
                    if (parentKeyActHistMap.containsKey(cdr.ParentKey__c)) {
                        if (parentKeyActHistMap.get(cdr.ParentKey__c).EffectiveDate__c > cdr.EffectiveDate__c)    
                            cdr.addError('There is a Pending Activation, Active, or Historical record with a greater Effective Date; inserting into the past is not allowed');
                    } else {
                        parentKeyActHistMap.put(cdr.ParentKey__c, cdr);
                    }                    
                    
                }
                
                if (parentKeyEffDtMap.containsKey(cdr.ParentKey__c + cdr.EffectiveDate__c.format())) {
                    cdr.addError('There is another row with the exact same Effective Date; please change the Effective Date on this record');
                } else {
                    parentKeyEffDtMap.put(cdr.ParentKey__c + cdr.EffectiveDate__c.format(), cdr);
                }
                
            }
            
            for (CDRQualitativeData__c cdr : [SELECT ParentKey__c 
                                              FROM CDRQualitativeData__c
                                              WHERE Status__c = 'Draft'
                                              AND ParentKey__c IN :parentKeyDraftMap.KeySet()
                                              AND Id NOT IN :myNewCDR]) {
                                                  if (parentKeyDraftMap.containsKey(cdr.ParentKey__c)) {
                                                      CDRQualitativeData__c newCDR = parentKeyDraftMap.get(cdr.ParentKey__c);
                                                      newCDR.addError('There is another Draft record already; please coordinate updates');
                                                  }
                                              }
            
            for (CDRQualitativeData__c cdr : [SELECT ParentKey__c, EffectiveDate__c, Name
                                              FROM CDRQualitativeData__c
                                              WHERE ParentKey__c IN :parentKeyDraftMap.KeySet()
                                              AND Id NOT IN :myNewCDR
                                              AND Status__c IN ('Active','Historical','Pending Activation')]) {
                                                  system.debug('ParentKey__c: ' + cdr.ParentKey__c);
                                                  system.debug('Effdt: ' + cdr.EffectiveDate__c);
                                                  if (parentKeyDraftMap.containsKey(cdr.ParentKey__c)) {
                                                      CDRQualitativeData__c newCDR = parentKeyDraftMap.get(cdr.ParentKey__c);
                                                      if (cdr.EffectiveDate__c > newCDR.EffectiveDate__c) {
                                                          newCDR.addError('There is a Pending Activation, Active, or Historical record with a greater Effective Date; inserting into the past is not allowed');
                                                      }
                                                  }
                                              }
            
            for (CDRQualitativeData__c cdr : [SELECT Id, ParentKey__c, EffectiveDate__c, Name
                                              FROM CDRQualitativeData__c
                                              WHERE ParentKey__c IN :parentKeySet
                                              AND Id NOT IN :myNewCDR]) {
                                                  system.debug('Found: ' + cdr.Name);
                                                  if (parentKeyEffDtMap.containsKey(cdr.ParentKey__c + cdr.EffectiveDate__c.format())) {
                                                      CDRQualitativeData__c newCDR = parentKeyEffDtMap.get(cdr.ParentKey__c + cdr.EffectiveDate__c.format());
                                                      if (newCDR.Id != cdr.Id) {                                                      
                                                          newCDR.addError('There is another row with the exact same Effective Date; please change the Effective Date on this record');
                                                      }
                                                  }
                                              }
        }
    }
    
    public static void setFieldValuesBefore (List<CDRQualitativeData__c> myNewCDR) {
        
        Boolean containsContacts = FALSE;
        Boolean containsAccounts = FALSE;
        Boolean containsProducts = FALSE;
        Boolean containsAddlInfo = FALSE;
        
        CDRSettings__c settings = CDRSettings__c.getvalues('NGAM');
        
        Map<Id,Schema.RecordTypeInfo> recTypeMap = CDRQualitativeData__c.sObjectType.getDescribe().getRecordTypeInfosById();
        Set<String> relatedRecordIdSet = new Set<String>();
        Map<Id,String> nameMap = new Map<Id,String>();
        
        for (CDRQualitativeData__c cdr : myNewCDR) {
            
            if (system.trigger.isInsert && settings.OverrideSetStatusOnCreate__c == FALSE) {
                cdr.Status__c = 'Draft';
            }
            
            if (cdr.Status__c == 'Pending Activation' && cdr.EffectiveDate__c <= datetime.now()) {
                cdr.Status__c = 'Active';
            } 
            
            if (cdr.Status__c == 'Draft') {
                cdr.ApprovalStatus__c = 'Not Submitted';
            }
            
            if (cdr.AdditionalInfo__c != null) {
                relatedRecordIdSet.add(cdr.AdditionalInfo__c);
                containsAddlInfo = TRUE;
            }
            if (cdr.Product__c != null) {
                relatedRecordIdSet.add(cdr.Product__c);
                containsProducts = TRUE;
            }
            if (cdr.Benchmark__c != null) {
                relatedRecordIdSet.add(cdr.Benchmark__c);
                containsProducts = TRUE;
            }
            if (cdr.ChildProduct__c != null) {
                relatedRecordIdSet.add(cdr.ChildProduct__c);
                containsProducts = TRUE;
            }
            if (cdr.ChildAccount__c != null) {
                relatedRecordIdSet.add(cdr.ChildAccount__c); 
                containsAccounts = TRUE;
            }
            if (cdr.Account__c != null) {
                relatedRecordIdSet.add(cdr.Account__c);
                containsAccounts = TRUE;
            }
            if (cdr.Contact__c != null) {
                relatedRecordIdSet.add(cdr.Contact__c); 
                containsContacts = TRUE;
            }
            
        }
        
        // gets for Product, Benchmark, Child Product
        if (containsProducts){
            for (Product2 nm : [SELECT Id, Name, CaseSafeId__c FROM Product2 WHERE Id in :relatedRecordIdSet]) {
                nameMap.put(nm.Id,nm.Name);
            }
        }
        
        if (containsAddlInfo) {
            for (AdditionalInfo__c nm : [SELECT Id, Name, CaseSafeId__c FROM AdditionalInfo__c WHERE Id in :relatedRecordIdSet]) {
                nameMap.put(nm.Id,nm.Name);
            }
        }
        
        if (containsAccounts) {
            for (Account nm : [SELECT Id, Name, FirmOfficeID18__c FROM Account WHERE Id in :relatedRecordIdSet]) {
                nameMap.put(nm.Id,nm.Name);
            }
        }
        
        if (containsContacts) {
            for (Contact nm : [SELECT Id, Name, CaseSafeId__c FROM Contact WHERE Id in :relatedRecordIdSet]) {
                nameMap.put(nm.Id,nm.Name);
            }
        }
        
        
        for (CDRQualitativeData__c cdr : myNewCDR) {
            
            String newName = cdr.EffectiveDate__c.format('yyyy-MM-dd') + ' (' + cdr.Status__c.left(1) + ') '; 
            if (recTypeMap.get(cdr.RecordTypeId).getName().equals('Additional Info')) newName += nameMap.get(cdr.AdditionalInfo__c);
            if (recTypeMap.get(cdr.RecordTypeId).getName().equals('Benchmark')) newName += nameMap.get(cdr.Benchmark__c);
            if (recTypeMap.get(cdr.RecordTypeId).getName().equals('Benchmark-Additional Info')) newName += nameMap.get(cdr.Benchmark__c).left(30) + ' - ' + nameMap.get(cdr.AdditionalInfo__c).left(30);
            if (recTypeMap.get(cdr.RecordTypeId).getName().equals('Contact')) newName += nameMap.get(cdr.Contact__c);
            if (recTypeMap.get(cdr.RecordTypeId).getName().equals('Contact-Additional Info')) newName += nameMap.get(cdr.Contact__c).left(30) + ' - ' + nameMap.get(cdr.AdditionalInfo__c).left(30);
            if (recTypeMap.get(cdr.RecordTypeId).getName().equals('ETF')) newName += nameMap.get(cdr.Product__c);
            if (recTypeMap.get(cdr.RecordTypeId).getName().equals('Firm')) newName += nameMap.get(cdr.Account__c);
            if (recTypeMap.get(cdr.RecordTypeId).getName().equals('Firm-Additional Info')) newName += nameMap.get(cdr.Account__c).left(30) + ' - ' + nameMap.get(cdr.AdditionalInfo__c).left(30);
            if (recTypeMap.get(cdr.RecordTypeId).getName().equals('Firm-Child Firm')) newName += nameMap.get(cdr.Account__c).left(30) + ' - ' + nameMap.get(cdr.ChildAccount__c).left(30);            
            if (recTypeMap.get(cdr.RecordTypeId).getName().equals('Firm-Contact')) newName += nameMap.get(cdr.Account__c).left(30) + '-' + nameMap.get(cdr.Contact__c).left(30);
            if (recTypeMap.get(cdr.RecordTypeId).getName().equals('Firm-Product')) newName += nameMap.get(cdr.Account__c).left(30) + '-' + nameMap.get(cdr.Product__c).left(30);
            if (recTypeMap.get(cdr.RecordTypeId).getName().equals('Mutual Fund')) newName += nameMap.get(cdr.Product__c);
            if (recTypeMap.get(cdr.RecordTypeId).getName().equals('Product-Additional Info')) newName += nameMap.get(cdr.Product__c).left(30) + '-' + nameMap.get(cdr.AdditionalInfo__c).left(30);
            if (recTypeMap.get(cdr.RecordTypeId).getName().equals('Product-Benchmark')) newName += nameMap.get(cdr.Product__c).left(30) + ' - ' + nameMap.get(cdr.Benchmark__c).left(30);
            if (recTypeMap.get(cdr.RecordTypeId).getName().equals('Product-Child Product')) newName += nameMap.get(cdr.Product__c).left(30) + ' - ' + nameMap.get(cdr.ChildProduct__c).left(30);
            if (recTypeMap.get(cdr.RecordTypeId).getName().equals('Product-Contact')) newName += nameMap.get(cdr.Product__c).left(30) + ' - ' + nameMap.get(cdr.Contact__c).left(30);
            if (recTypeMap.get(cdr.RecordTypeId).getName().equals('Share Class')) newName += nameMap.get(cdr.Product__c);            
            cdr.Name = newName;
            
        }       
        
    }
    
    
    public static void bumpCDRRecordStatus(Map<Id,CDRQualitativeData__c> newCDRMap, Map<Id,CDRQualitativeData__c> oldCDRMap) {
        
        Map<String,CDRQualitativeData__c> newStatusMap = new Map<String,CDRQualitativeData__c>();
        List<CDRQualitativeData__c> toBeBumped = new List<CDRQualitativeData__c>();
        List<CDRQualitativeData__c> setDates = new List<CDRQualitativeData__c>();
        Map<String,CDRQualitativeData__c> stagingMap = new Map<String,CDRQualitativeData__c>();
        Map<String,CDRQualitativeData__c> pendingMap = new Map<String,CDRQualitativeData__c>();
        List<CDRQualitativeData__c> activeAndHistoricalList = new List<CDRQualitativeData__c>();
        List<CDRQualitativeData__c> toBeLocked = new List<CDRQualitativeData__c>();
        List<CDRQualitativeData__c> toBeUnlocked = new List<CDRQualitativeData__c>();
        
        for (CDRQualitativeData__c cdr : newCDRMap.values()) {
            if (cdr.Status__c != oldCDRMap.get(cdr.Id).Status__c && cdr.Status__c != 'Historical' && cdr.Status__c != 'Inactive') {
                newStatusMap.put(cdr.ParentKey__c, cdr);
            }
        }
        
        for (CDRQualitativeData__c b : [SELECT Id, SortOrder__c, ParentKey__c, Status__c, EffectiveDate__c, Name
                                        FROM CDRQualitativeData__c
                                        WHERE ParentKey__c in :newStatusMap.keySet()
                                        AND Status__c in ('Active', 'Pending Activation','Staging')
                                        AND Id NOT in: newCDRMap.keySet()
                                        ORDER BY ParentKey__c, Status__c]) {
                                            
                                            if (newStatusMap.containsKey(b.ParentKey__c)) {
                                                // Coming from Staging to Active bumps any currently Active rows to Historical
                                                
                                                if (b.Status__c == 'Active' && newStatusMap.get(b.ParentKey__c).Status__c == 'Active' ) {
                                                    b.Status__c = 'Historical';
                                                    b.NextPendingActivationDate__c = null;
                                                    b.NextStagingDate__c = null;
                                                    toBeLocked.add(b);
                                                    toBeBumped.add(b);
                                                }
                                                // Coming from Staging to Pending Activation bumps any currently Pending Activation rows to Draft
                                                if (b.Status__c == 'Pending Activation' && newStatusMap.get(b.ParentKey__c).Status__c == 'Pending Activation') {
                                                    b.Status__c = 'Inactive';                
                                                    toBeLocked.add(b);
                                                    toBeBumped.add(b);
                                                }
                                                // Coming from Draft to Staging bumps any currently Staging rows to Draft
                                                if (b.Status__c == 'Staging' && newStatusMap.get(b.ParentKey__c).Status__c == 'Staging') {
                                                    b.Status__c = 'Draft';
                                                    toBeUnlocked.add(b);
                                                    toBeBumped.add(b);
                                                }
                                            }
                                        }
        
        update toBeBumped;
        
        // setting up map after bump to pick up any new Staging and Pending Activation records
        for (CDRQualitativeData__c m : [SELECT Id, SortOrder__c, ParentKey__c, Status__c, EffectiveDate__c, Name, HistoricalDate__c
                                        FROM CDRQualitativeData__c
                                        WHERE ParentKey__c in :newStatusMap.keySet()
                                        AND Status__c IN ('Staging', 'Pending Activation', 'Historical','Active')
                                        ORDER BY ParentKey__c, EffectiveDate__c DESC]) {
                                            if (m.Status__c == 'Staging') stagingMap.put(m.ParentKey__c,m);
                                            if (m.Status__c == 'Pending Activation') pendingMap.put(m.ParentKey__c,m);
                                            if (m.Status__c == 'Active' || m.Status__c == 'Historical') activeAndHistoricalList.add(m);
                                            if (m.SortOrder__c == 124) system.debug('Adding 124');
                                        }
        
        // for All currently Active or Historical rows, set Historical Date
        for (CDRQualitativeData__c hdo : activeAndHistoricalList) {
            
            for (CDRQualitativeData__c hdi : activeAndHistoricalList) {
                
                if (hdo.EffectiveDate__c < hdi.EffectiveDate__c && hdo.ParentKey__c == hdi.ParentKey__c) {
                    hdo.HistoricalDate__c = hdi.EffectiveDate__c;
                }
                
            }
            
            if (hdo.Status__c == 'Historical') {
                hdo.EffectiveDate__c = (hdo.EffectiveDate__c == null) ? Datetime.now() : hdo.EffectiveDate__c;
                setDates.add(hdo);                
            }
        }
        
        // for all currently Active or Pending Activation rows, set or reset 'next' dates
        for (CDRQualitativeData__c d : [SELECT Id, SortOrder__c, ParentKey__c, Status__c, EffectiveDate__c, Name
                                        FROM CDRQualitativeData__c
                                        WHERE ParentKey__c in :newStatusMap.keySet()
                                        AND Status__c IN ('Active', 'Pending Activation')]) {
                                            
                                            // if status is Active, set NextStagingDate and NextPendingActivationDate
                                            if (d.Status__c == 'Active') {
                                                if (stagingMap.containsKey(d.ParentKey__c)) {
                                                    d.NextStagingDate__c = stagingMap.get(d.ParentKey__c).EffectiveDate__c;
                                                    d.HasStagingRow__c = TRUE;
                                                } else {
                                                    d.NextStagingDate__c = null;
                                                    d.HasStagingRow__c = FALSE;
                                                }
                                                if (pendingMap.containsKey(d.ParentKey__c)) {
                                                    d.NextPendingActivationDate__c = pendingMap.get(d.ParentKey__c).EffectiveDate__c;
                                                    d.HasPendingActivationRow__c  = TRUE;
                                                } else {
                                                    d.NextPendingActivationDate__c = null;
                                                    d.HasPendingActivationRow__c  = FALSE;
                                                }
                                                setDates.add(d);
                                            }
                                            
                                            // if status is Pending Activation, set NextStagingDate 
                                            if (d.Status__c == 'Pending Activation') {
                                                if (stagingMap.containsKey(d.ParentKey__c)) {
                                                    d.NextStagingDate__c = stagingMap.get(d.ParentKey__c).EffectiveDate__c;
                                                    d.HasStagingRow__c = TRUE;
                                                } else {
                                                    d.NextStagingDate__c = null;
                                                    d.HasStagingRow__c = FALSE;
                                                }
                                                setDates.add(d);
                                            }
                                            
                                        }
        
        update setDates;
        
    }    
    
    public static void updateParentsOnActive (List<CDRQualitativeData__c> myNewCDR) {
        
        Boolean containsContacts = FALSE;
        Boolean containsAccounts = FALSE;
        Boolean containsProducts = FALSE;
        Boolean containsAddlInfo = FALSE;
        
        Map<Id,Schema.RecordTypeInfo> recTypeMap = CDRQualitativeData__c.sObjectType.getDescribe().getRecordTypeInfosById();
        Map<Id,CDRQualitativeData__c> parentCDRMap = new Map<Id,CDRQualitativeData__c>();
        
        for (CDRQualitativeData__c cdr : myNewCDR) {
            
            if (cdr.Status__c == 'Active') {
                if (recTypeMap.get(cdr.RecordTypeId).getName().equals('Benchmark')) parentCDRMap.put(cdr.Benchmark__c, cdr); containsProducts = TRUE;
                if (recTypeMap.get(cdr.RecordTypeId).getName().equals('Mutual Fund')) parentCDRMap.put(cdr.Product__c, cdr); containsProducts = TRUE;
                if (recTypeMap.get(cdr.RecordTypeId).getName().equals('Share Class')) parentCDRMap.put(cdr.Product__c, cdr); containsProducts = TRUE;
                if (recTypeMap.get(cdr.RecordTypeId).getName().equals('ETF')) parentCDRMap.put(cdr.Product__c, cdr); containsProducts = TRUE;               
                if (recTypeMap.get(cdr.RecordTypeId).getName().equals('Firm')) parentCDRMap.put(cdr.Account__c, cdr); containsAccounts = TRUE;
                if (recTypeMap.get(cdr.RecordTypeId).getName().equals('Contact')) parentCDRMap.put(cdr.Contact__c, cdr); containsContacts = TRUE;               
                if (recTypeMap.get(cdr.RecordTypeId).getName().equals('Additional Info')) parentCDRMap.put(cdr.AdditionalInfo__c, cdr); containsAddlInfo = TRUE;
            }
            
        }
        
        List<Product2> prodToUpdate = new List<Product2>();
        List<Account> accountToUpdate = new List<Account>();
        List<Contact> contactToUpdate = new List<Contact>();
        List<AdditionalInfo__c> AddlInfoToUpdate = new List<AdditionalInfo__c>();
        
        if (containsProducts) {
            prodToUpdate = [SELECT ActiveCDRQualitativeData__c, TradingSymbol__c FROM Product2 WHERE Id in :parentCDRMap.keySet()];
        }
        if (containsAccounts) {
            accountToUpdate = [SELECT ActiveCDRQualitativeData__c FROM Account WHERE Id in :parentCDRMap.keySet()];
        }
        if (containsContacts) {
            contactToUpdate = [SELECT ActiveCDRQualitativeData__c FROM Contact WHERE Id in :parentCDRMap.keySet()];
        }
        if (containsAddlInfo) {
            AddlInfoToUpdate = [SELECT ActiveCDRQualitativeData__c FROM AdditionalInfo__c WHERE Id in :parentCDRMap.keySet()];        
        }
        
        for (Product2 p : prodToUpdate) {
            p.ActiveCDRQualitativeData__c = parentCDRMap.get(p.Id).Id;
            p.TradingSymbol__c = parentCDRMap.get(p.Id).TradingSymbol__c;
            p.InceptionDate__c = parentCDRMap.get(p.Id).InceptionDate__c;     
            p.CUSIP__c = parentCDRMap.get(p.Id).CUSIP__c;
            p.ISIN__c = parentCDRMap.get(p.Id).ISIN__c;            
            p.ShareClass__c = parentCDRMap.get(p.Id).ShareClass__c;
            
            if (recTypeMap.get(parentCDRMap.get(p.Id).RecordTypeId).getName().equals('Benchmark')) {
                p.LegalName__c = (parentCDRMap.get(p.Id).BenchmarkLegalName__c != null) ? parentCDRMap.get(p.Id).BenchmarkLegalName__c.stripHtmlTags() : p.LegalName__c;  
                p.RichTextName__c = (parentCDRMap.get(p.Id).BenchmarkLegalName__c != null) ? parentCDRMap.get(p.Id).BenchmarkLegalName__c : p.RichTextName__c; 
            } else {
                p.LegalName__c = (parentCDRMap.get(p.Id).ProductLegalName__c != null) ? parentCDRMap.get(p.Id).ProductLegalName__c.stripHtmlTags() : p.LegalName__c;  
                p.RichTextName__c = (parentCDRMap.get(p.Id).ProductLegalName__c != null) ? parentCDRMap.get(p.Id).ProductLegalName__c : p.RichTextName__c; 
            }
            
        }        
        
        for (Account a : accountToUpdate) {
            a.ActiveCDRQualitativeData__c = parentCDRMap.get(a.Id).Id;
            if (parentCDRMap.get(a.Id).FirmLegalName__c != null) a.LegalName__c = parentCDRMap.get(a.Id).FirmLegalName__c.stripHtmlTags();
        }        
        
        for (Contact c : contactToUpdate) {
            c.ActiveCDRQualitativeData__c = parentCDRMap.get(c.Id).Id;
        }        
        
        for (AdditionalInfo__c i : AddlInfoToUpdate) {
            i.ActiveCDRQualitativeData__c = parentCDRMap.get(i.Id).Id;
        }        
        
        if (!prodToUpdate.isEmpty()) update prodToUpdate;
        if (!accountToUpdate.isEmpty()) update accountToUpdate;
        if (!contactToUpdate.isEmpty()) update contactToUpdate;
        if (!AddlInfoToUpdate.isEmpty()) update AddlInfoToUpdate;        
        
    }
    
    public static void lockAndUnlockRecords (List<CDRQualitativeData__c> myNewCDR) {
        //Set up to account for all approval and recall actions, bump actions, etc.
        
        List<CDRQualitativeData__c> toBeLocked = new List<CDRQualitativeData__c>();
        List<CDRQualitativeData__c> toBeUnlocked = new List<CDRQualitativeData__c>();
        
        for (CDRQualitativeData__c cdr : myNewCDR) {
            
            if (cdr.Status__c == 'Draft') {
                toBeUnlocked.add(cdr);
            } else {
                toBeLocked.add(cdr);
            }
        }
        
        List<Approval.LockResult> ur = Approval.lock(toBeLocked);
        List<Approval.UnLockResult> ulr = Approval.unLock(toBeUnlocked);
        
    }
    
}