objects/Account.object
<CustomObject>
    <fields>
        <fullName>WCMRelationshipFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Maintained by loading firms identified by Data Ops, the data is not integrated. This field is used in formulas at the office and contact level and indicates that the related advisers should not have WCM products discussed with them or related material emailed to them.</description>
        <label>WCM Relationship Flag</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>WCMRelationshipFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox populated by systematically based on the flag on the account.</description>
        <label>WCM Relationship Flag</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/NGAMSettingsHierarchy__c.object
<CustomObject>
    <fields>
        <fullName>ByPassAccountValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows entity to by-pass validation rules on Account</description>
        <inlineHelpText>Allows entity to by-pass validation rules on Account</inlineHelpText>
        <label>By-Pass Account Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NGAM Settings - Hierarchy</label>
</CustomObject>

classes/WCMRelationshipContactBatchTest.cls
@isTest
public class WCMRelationshipContactBatchTest {
    
    @isTest static void test() {
        
        NGAMSettingsHierarchy__c hsettings = NGAMSettingsHierarchy__c.getOrgDefaults();
        hsettings.ByPassAccountValidationRules__c  = TRUE;
        upsert hsettings NGAMSettingsHierarchy__c.Id; 
        
        List<Account> accts1 = DataFactory.createTestAccounts(1);
        accts1[0].WCMRelationshipFlag__c = FALSE;
        insert accts1;
        
        List<Account> accts2 = DataFactory.createTestAccounts(1);
        accts2[0].WCMRelationshipFlag__c = FALSE;
        insert accts2;        
        
        List<Contact> contacts1 = DataFactory.createTestContacts(2, accts1, False);
        insert contacts1;
        List<Contact> contacts2 = DataFactory.createTestContacts(2, accts2, False);
        insert contacts2;
        
        accts1[0].WCMRelationshipFlag__c = TRUE;
        update accts1;
        
        Test.startTest();
        Id batchJobId = Database.executeBatch(new WCMRelationshipContactSyncBatch());
        Test.stopTest();
        
        List<Contact> checkTrue = [SELECT Id, Name, WCMRelationshipFlag__c FROM Contact WHERE Id = :contacts1[0].Id];
        List<Contact> checkFalse = [SELECT Id, Name, WCMRelationshipFlag__c FROM Contact WHERE Id = :contacts2[0].Id];
        
        system.assertEquals(checkTrue[0].WCMRelationshipFlag__c,TRUE,'WCM should be TRUE');
        system.assertEquals(checkFalse[0].WCMRelationshipFlag__c,FALSE,'WCM should be FALSE');
        
        
        }
        
    }