objects/Account.object
<CustomObject>
    <fields>
        <fullName>Zone__c</fullName>
        <description>Target for deletion; Original Zone field that aggregated data for FS but will become moot</description>
        <formula>CASE( $User.ActivityChannelName__c , 
'ADU', ZoneADU_IDU__r.Name, 
'IDU', ZoneADU_IDU__r.Name, 
'RCDU', ZoneRCDU__r.Name, 
'RADU', ZoneRADU__r.Name, 
'FIDUCIARY SERVICES', ZoneFS__r.Name , 
'DC REGIONAL', ZoneRADU__r.Name , 
'DCIO', ZoneRADU__r.Name , 
'DCIO SUB ADV', ZoneRADU__r.Name , 
'No Zone')</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Zone Aggregated</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Artemus.Request.requestor_id
varchar(100)</description>
        <label>Requester</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Requestor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubmittedOnBehalfOf__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to support the Affiliate Request Process</description>
        <label>Submitted on behalf of</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.ActivityReporting__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>User.ActivityZoneId__c</field>
                <operation>notEqual</operation>
                <value>a1bF0000003XUiW,a1bF00000053bto</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>SubmitedOnBehalfOf</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <description>Artemus.Request.territory
varchar(255)</description>
        <label>Territory</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel><enableHistory>true</enableHistory>
</CustomObject>

objects/NGAMSettings__c.object
<CustomObject>
    <fields>
        <fullName>ProfileIntegration__c</fullName>
        <description>Indicates the profile that should be used for Integration User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</description>
        <inlineHelpText>Indicates the profile that should be used for Integration User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</inlineHelpText>
        <label>Profile: Integration</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProfileSystemAdministrator__c</fullName>
        <description>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</description>
        <inlineHelpText>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</inlineHelpText>
        <label>Profile: System Administrator</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Holds the NGAM settings</description>
    <label>NGAM Settings</label>
</CustomObject>

objects/NGAMSettingsHierarchy__c.object
<CustomObject>
    <fields>
        <fullName>ByPassAccountValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows entity to by-pass validation rules on Account</description>
        <inlineHelpText>Allows entity to by-pass validation rules on Account</inlineHelpText>
        <label>By-Pass Account Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NGAM Settings - Hierarchy</label>
</CustomObject>

objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>GroupId__c</fullName>
        <externalId>true</externalId>
        <label>Group Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ParentTerritory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Territories</relationshipLabel>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RoleGroupId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Role Group Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RoleId__c</fullName>
        <externalId>true</externalId>
        <label>Role Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TerritoryName__c</fullName>
        <defaultValue>"Update Me"</defaultValue>
        <externalId>true</externalId>
        <label>MARS Territory Name</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TerritoryType__c</fullName>
        <label>Territory Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Territory</fullName>
                </value>
                <value>
                    <fullName>Region</fullName>
                </value>
                <value>
                    <fullName>Department</fullName>
                </value>
                <value>
                    <fullName>Division</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ActivityTerritoryType__c</fullName>
        <description>The type of territory for the Activity Territory</description>
        <label>Activity Territory Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryTerritory__c</fullName>
        <label>Primary Territory</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserID__c</fullName>
        <defaultValue>"Populate This Field"</defaultValue>
        <externalId>true</externalId>
        <label>UserID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/UserTerritory__c.object
<CustomObject>
    <fields>
        <fullName>ActivityTerritory__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activity Territory</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PrimaryTerritory__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Territory</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RoleId__c</fullName>
        <formula>Territory__r.RoleId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Role Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TerritoryName__c</fullName>
        <formula>Territory__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Territory Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TerritoryType__c</fullName>
        <formula>TEXT(Territory__r.TerritoryType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Territory Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>User Territories</relationshipLabel>
        <relationshipName>User_Territories1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Territories1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zoning__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Zone</label>
        <referenceTo>Zone__c</referenceTo>
        <relationshipLabel>User Territories</relationshipLabel>
        <relationshipName>User_Territories</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>User Territory</label>
    <nameField>
        <displayFormat>UT-{00000000}</displayFormat>
        <label>User Territory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Zone__c.object
<CustomObject>
    <fields>
        <fullName>Zone__c</fullName>
        <externalId>true</externalId>
        <label>Zone</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CaseInvocableTest.cls
@isTest
public class CaseInvocableTest {
    
    @isTest
    public static void validateInvocable(){
    
        NGAMSettingsHierarchy__c hsettings = NGAMSettingsHierarchy__c.getOrgDefaults();
        hsettings.ByPassAccountValidationRules__c  = TRUE;
        upsert hsettings NGAMSettingsHierarchy__c.Id;

        
        //Profile p = [select id from profile where name='System Administrator']; 
        //Profile pSales = [select id from profile where name='NGAM Integration'];
        
        DataFactory.CreateNGAMCustomSettings(); 
        NGAMSettings__c ngamSettings = [select id, 
                                        ProfileIntegration__c, 
                                        ProfileSystemAdministrator__c from NGAMSettings__c limit 1];
        string p = Util.getCustomSettingProfileId(ngamSettings.ProfileSystemAdministrator__c); 
        string pSales = Util.getCustomSettingProfileId(ngamSettings.ProfileIntegration__c);
        
        User u = new User(alias = 'standt', email='SFDCadmin@ngam.natixis.com', 
                          emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
                          localesidkey='en_US', profileid = p, ActivityTerritoryType__c = 'Region',
                          timezonesidkey='America/Los_Angeles', username='SFDCadmin@ngam.natixis.com',UserID__c='SFDCadmin');
        
        System.runAs(u) {
            User u0 = new User(alias = 's0', email='Sales0@ngam.natixis.com', 
                               emailencodingkey='UTF-8', lastname='Testing0', languagelocalekey='en_US', 
                               localesidkey='en_US', profileid = p, ActivityTerritoryType__c = 'Region',
                               timezonesidkey='America/Los_Angeles', username='Sales0@ngam.natixis.com',UserID__c='Sales0');    
            
            insert u0;                   
            
            //Creating the Territory
            Territory__c Terr = new Territory__c(Name='Test',TerritoryName__c='Test',RoleID__c = '',GroupID__c = '',TerritoryType__c = 'Region'); 
            insert Terr;        
            
            Territory__c Terr2 = new Territory__c(Name='Test2',TerritoryName__c='Test2',RoleID__c = '',GroupID__c = '',TerritoryType__c = 'Territory', ParentTerritory__c = Terr.Id); 
            insert Terr2;        


            // Creating the Corresponding Role
            UserRole Ur = new UserRole();
            Ur.Name = Terr.Name;
            Ur.DeveloperName = Terr.Id;
            Ur.CaseAccessForAccountOwner = 'Read';
            Ur.OpportunityAccessForAccountOwner = 'Read';
            Ur.ContactAccessForAccountOwner = 'Read';
            insert Ur;
            
            UserRole Ur2 = new UserRole();
            Ur2.Name = Terr2.Name;
            Ur2.DeveloperName = Terr2.Id;
            Ur2.CaseAccessForAccountOwner = 'Read';
            Ur2.OpportunityAccessForAccountOwner = 'Read';
            Ur2.ContactAccessForAccountOwner = 'Read';
            insert Ur2; 

            Group urGroup=[select id from group where RelatedId =:ur.id][0];                     
            Group urGroup2=[select id from group where RelatedId =:ur2.id][0];                     
            
            // Creating the Corresponding Group
            Group Gr = new Group();
            Gr.name = Terr.Name;
            Gr.DeveloperName = Terr.Id;
            Gr.Type = 'Regular';
            insert Gr;     

            Group Gr2 = new Group();
            Gr2.name = Terr2.Name;
            Gr2.DeveloperName = Terr2.Id;
            Gr2.Type = 'Regular';
            insert Gr2;     

            Territory__Share TsR = new  Territory__Share(AccessLevel='Read',UserOrGroupId=urGroup.id,ParentId=terr.id );    
            insert TsR;      

            Territory__Share TsR2 = new  Territory__Share(AccessLevel='Read',UserOrGroupId=urGroup2.id,ParentId=terr2.id );    
            insert TsR2;      
            
            //Territory__c uTerr = new Territory__c(id=Terr.id,RoleID__c = ur.id,GroupID__c = gr.id ); 
            Terr.RoleID__c = ur.id;
            Terr.RoleGroupId__c = urGroup.id;
            Terr.GroupID__c = gr.id;    
            update Terr;
            
            Terr2.RoleID__c = ur2.id;
            Terr2.RoleGroupId__c = urGroup2.id;
            Terr2.GroupID__c = gr2.id;    
            update Terr2;
            
            List<zone__c> AllZones = DataFactory.createAllZones();
            List<UserTerritory__c> ut = new List<UserTerritory__c>();
            
            ut.add(new  UserTerritory__c(user__c=u0.id, territory__c=Terr.Id, PrimaryTerritory__c=true, ActivityTerritory__c=true,  Zoning__c=AllZones.get(0).id));  
            ut.add(new  UserTerritory__c(user__c=u.id, territory__c=Terr.Id, PrimaryTerritory__c=true, ActivityTerritory__c=true,  Zoning__c=AllZones.get(0).id));              
            insert ut; 
            
            Account a = new Account(Name = 'TestAccount');
            insert a;    
            
            List<Case> cases = new List<Case>();
            cases.add(new Case(ownerid= u0.id, AccountId = a.Id, Requestor__c = u0.id, SubmittedOnBehalfOf__c = u.Id));
            insert cases;
            
            RunCaseAssignmentRules.runCaseAssignmentRules(cases);
            RunCaseSharing.runCaseSharing(cases);
            
        }         
        
    }
    
}