objects/Account.object
<CustomObject>
    <fields>
        <fullName>Firm__c</fullName>
        <description>Displays either the name of the Firm or the Parent Firm name, depending on the type of Account</description>
        <formula>IF(ISPICKVAL(Type, 'Firm'),  Name,  
IF(ISPICKVAL(Type, 'Consultant'),  Name, 
IF(ISPICKVAL(Type, 'Affiliate'),  Name, 
Parent.Name )))</formula>
        <label>Firm</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WCMRelationshipFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Maintained by loading firms identified by Data Ops, the data is not integrated. This field is used in formulas at the office and contact level and indicates that the related advisers should not have WCM products discussed with them or related material emailed to them.</description>
        <label>WCM Relationship Flag</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Firm</fullName>
        <active>true</active>
        <description>Firms, offices, and reps are organized into a hierarchy. This means that each rep must be assigned to an office, and each office must be assigned to a firm. Firm is the highest level in the hierarchy.</description>
        <label>Firm</label>
    </recordTypes>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EmailPreferencesRecalc__c</fullName>
        <description>When changed, the Email Preferences field (Pardot Pref Center) will be recalculated for this contact.  Can be used for mass recalcs if Preference Center categories or field labels change.</description>
        <label>Marketing Email Preferences Recalc</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmailPreferences__c</fullName>
        <description>Lists the email preferences of the contact, based on Pardot Preference Center and opt-out fields.</description>
        <inlineHelpText>Marketing email preferences as selected by the contact/rep via the Email Preference Center.</inlineHelpText>
        <label>Marketing Email Preferences</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FirmNameText__c</fullName>
        <description>Used in sharing rules because formula fields and lookups cannot be used.</description>
        <label>Firm Name Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to the related Firm record</description>
        <label>Firm</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Offices Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InitiateEmailOptIn__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, sets Email Opt-out to false and initiates an automation rule in Pardot.  Pardot will uncheck after automation rule completes.</description>
        <inlineHelpText>Only check if the client has opted-out or snoozed and specifically requested opt-in. Contact will be sent Pref Center email within 20 minutes.  Your selection is tracked for compliance reasons.</inlineHelpText>
        <label>Initiate Email Opt-In</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MarsRepId__c</fullName>
        <description>Source: MARS na_load_rep.Id
Loaded by a nightly job. Unique identifier for MARS. Data Flow: Mars -&gt; SF</description>
        <externalId>true</externalId>
        <label>MARS Rep Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PardotPrefCenterOptOut1__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Synced with Pardot Preference Center; drives what shows in Email Preferences text box via the field label.</description>
        <label>Client Comm Opt-out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PardotPrefCenterOptOut2__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Synced with Pardot Preference Center; drives what shows in Email Preferences text box via the field label.</description>
        <label>Conferences Opt-out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PardotPrefCenterOptOut3__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Synced with Pardot Preference Center; drives what shows in Email Preferences text box via field label.</description>
        <label>Research/Insights Opt-out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PardotPrefCenterOptOut4__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Synced with Pardot Preference Center; drives what shows in Email Preferences text box via the field label.</description>
        <label>Products/Strategies Opt-out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SnoozeEmails__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that the contact has snoozed their marketing emails.  This field is controlled by the Pardot preference center.  There is time-based logic that reverts the snooze to false after 90 days.  It works in tandem with Event Opt-Out.</description>
        <label>Snooze Emails</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>VestmarkEmail__c</fullName>
        <description>This field store the email address of the FA in VestMark system and used for Estatement project</description>
        <inlineHelpText>This field store the email address of the FA in VestMark system.</inlineHelpText>
        <label>Vestmark Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>WCMRelationshipFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox populated by systematically based on the flag on the account.</description>
        <label>WCM Relationship Flag</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ExternalCommunitySettings__c.object
<CustomObject>
    <fields>
        <fullName>AccountPrefix__c</fullName>
        <description>Used to prefix the Account.Name for End Client contact accounts. These accounts are automatically created for community users to control sharing.</description>
        <inlineHelpText>Used to prefix the Account.Name for End Client contact accounts. These accounts are automatically created for community users to control sharing.</inlineHelpText>
        <label>AccountPrefix</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndClientCommunityAccountName__c</fullName>
        <description>The name of the Account (Firms Office) to which End Client/Interested 3rd Party community contacts will belong.</description>
        <inlineHelpText>The name of the Account (Firms Office) to which new End Client/Interested 3rd Party community contacts belong.  This should always be NGAM DISTRIBUTION, L.P., PORTAL END CLIENTS</inlineHelpText>
        <label>EndClientCommunityAccountName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndClientOwnerId__c</fullName>
        <description>Specify the owner of end client accounts and contacts (OwnerId)</description>
        <inlineHelpText>The OwnerId of End Client accounts and contacts.  This should be set to "Portal Natixis" user SFID.  It controls row-level security for viewing and editing End Client contacts/accounts through a sharing rule.</inlineHelpText>
        <label>EndClientOwnerId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PotalUserName__c</fullName>
        <description>Portal user name</description>
        <label>PotalUserName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UpdateVestMarkEmailInUserRecord__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If this field is checked and vestmark email is updated on  contact record,  update the community user record with this new email.vestmark</description>
        <label>UpdateVestMarkEmailInUserRecord</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>To the custom setting for external communities</description>
    <label>ExternalCommunitySettings</label>
</CustomObject>

objects/WCMRelationshipSyncOverride__mdt.object
<CustomObject>
    <fields>
        <fullName>SFID__c</fullName>
        <description>The SFID of the account or contact that should not have their WCM Relationship Flag inherited from parent.  Use the 18-digit ID.</description>
        <inlineHelpText>The SFID of the account or contact that should not have their WCM Relationship Flag inherited from parent.  Use the 18-digit ID.</inlineHelpText>
        <label>SFID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <description>If an account or contact is in this list, their record will not inherit the WCM Relationship Flag field value from their parent account.</description>
    <label>WCM Relationship Sync Override</label>
    <pluralLabel>WCM Relationship Sync Overrides</pluralLabel>
</CustomObject>

classes/ContactTriggerHandler.cls
public class ContactTriggerHandler {
    
    static ExternalCommunitySettings__c myCustomSetting = ExternalCommunitySettings__c.getValues('EstatementCommunity');
    static Boolean updateUserOnVestMarkEmail = false; 
    static String eStatementFirmName = '';
    static String portalUserName = '';
    static String communityAccountPrefix = ''; 
    static String endClientOwnerId = '';
    static Account portalFirm;
    static Id ECrecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('End Client').getRecordTypeId();
    static Id CRrecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Rep/Contact').getRecordTypeId();    
    static Map<String, Schema.SObjectField> fieldMap = Schema.getGlobalDescribe().get('Contact').getDescribe().fields.getMap();
    
    public static void onBeforeInsert(List<Contact> newContacts) {
        
        createAccountForEndClients(newContacts);
        newContacts = setFirm(newContacts);
        newContacts = setEmailPreferencesFieldBeforeInsert(newContacts); 
        newContacts = setWCMRelationshipFlag(newContacts);
        
    }
    
    public static void onAfterInsert(List<Contact> newContacts) {
        addRepToMARS(newContacts);
    }    
    
    public static void onBeforeUpdate(List<Contact> newContacts, Map<Id,Contact> oldMap) {
        newContacts = setFirm(newContacts);
        newContacts = setEmailPreferencesFieldBeforeUpdate(newContacts, oldMap);
		newContacts = setWCMRelationshipFlag(newContacts);
    }       
    
    public static List<Contact> setWCMRelationshipFlag(List<Contact> contacts) {

		Set<Id> wcmOverrideSet = new Set<Id>();
        WCMRelationshipSyncOverride__mdt[] wcmOverrides = [SELECT SFID__c FROM WCMRelationshipSyncOverride__mdt];

		for (WCMRelationshipSyncOverride__mdt w : wcmOverrides) {
			wcmOverrideSet.add(w.SFID__c);
		}    

        Set<Id> acctIdSet = new Set<Id>();
        
        for (Contact c : contacts) {
            acctIdSet.add(c.AccountId);
        }        
        
        Map<Id,Account> acctMap = new Map<Id,Account>([SELECT Id, WCMRelationshipFlag__c
                                                       FROM Account
                                                       WHERE Id in: acctIdSet]);
        
        for (Contact c : contacts) {
            if (acctMap.containsKey(c.AccountId) && c.AccountId != null  && !wcmOverrideSet.contains(c.Id)) {
            	c.WCMRelationshipFlag__c = acctMap.get(c.AccountId).WCMRelationshipFlag__c;
            }
        }
        
        return contacts;
    }
    
    public static List<Contact> setEmailPreferencesFieldBeforeInsert(List<Contact> myContactList) {
        
        for (Contact c : myContactList) {            
            getEmailPreferences(c);             
        }
        
        return myContactList;  
        
    }    
    
    public static List<Contact> setEmailPreferencesFieldBeforeUpdate(List<Contact> myContactList, Map<Id,Contact> oldContactMap) {
        
        for (Contact c : myContactList) {
            
            //if any of the key fields have changed, run the logic
            if ((c.HasOptedOutOfEmail != oldContactMap.get(c.Id).HasOptedOutOfEmail) ||
                (c.SnoozeEmails__c != oldContactMap.get(c.Id).SnoozeEmails__c) ||
                (c.PardotPrefCenterOptOut1__c != oldContactMap.get(c.Id).PardotPrefCenterOptOut1__c) ||
                (c.PardotPrefCenterOptOut2__c != oldContactMap.get(c.Id).PardotPrefCenterOptOut2__c) ||
                (c.PardotPrefCenterOptOut3__c != oldContactMap.get(c.Id).PardotPrefCenterOptOut3__c) ||
                (c.PardotPrefCenterOptOut4__c != oldContactMap.get(c.Id).PardotPrefCenterOptOut4__c) ||
                (c.EmailPreferencesRecalc__c != oldContactMap.get(c.Id).EmailPreferencesRecalc__c) ||
                (c.Email != oldContactMap.get(c.Id).Email) ||
                (c.InitiateEmailOptIn__c != oldContactMap.get(c.Id).InitiateEmailOptIn__c) ||
                (c.pi__pardot_hard_bounced__c != oldContactMap.get(c.Id).pi__pardot_hard_bounced__c))   {
                    
                    getEmailPreferences(c); 
                    
                }
            
        }
        
        return myContactList;  
        
    }
    
    public static void getEmailPreferences(Contact c) {
        
        c.EmailPreferences__c = '';
        
        if (c.InitiateEmailOptIn__c) {
            c.HasOptedOutOfEmail = FALSE;
            c.EmailPreferences__c = 'Email Opt-In Initiated';
        }    
        
        List<String> reasonForNoEmailsList = new List<String>();
        
        if (c.SnoozeEmails__c) reasonForNoEmailsList.add('Snoozed');
        if (c.HasOptedOutOfEmail) reasonForNoEmailsList.add('Global Opt-out');
        if (c.Email == null) reasonForNoEmailsList.add('No address');
        if (c.pi__pardot_hard_bounced__c) reasonForNoEmailsList.add('Hard Bounce');
        
        if (!reasonForNoEmailsList.isEmpty()) {
            c.EmailPreferences__c = 'No Emails: ' + String.join(reasonForNoEmailsList,', ');
        }
        
        if (String.isBlank(c.EmailPreferences__c)) {                 
            
            //is this a client with mixed preferences?
            Set<Boolean> mixedPrefSet = new Set<Boolean>();
            mixedPrefSet.add(c.PardotPrefCenterOptOut1__c);
            mixedPrefSet.add(c.PardotPrefCenterOptOut2__c);
            mixedPrefSet.add(c.PardotPrefCenterOptOut3__c);
            mixedPrefSet.add(c.PardotPrefCenterOptOut4__c);
            
            Boolean mixedPref = FALSE;
            
            if (mixedPrefSet.contains(TRUE) && mixedPrefSet.contains(FALSE)) mixedPref = TRUE;
            
            if (!mixedPref) {
                if (!c.InitiateEmailOptIn__c) {
                    c.EmailPreferences__c = 'All Emails';
                }
            } else {
                List<String> optInList = new List<String>();
                List<String> optOutList = new List<String>();
                String ppc1Label = fieldMap.get('PardotPrefCenterOptOut1__c').getDescribe().getLabel().removeEnd('Opt-out').trim();
                String ppc2Label = fieldMap.get('PardotPrefCenterOptOut2__c').getDescribe().getLabel().removeEnd('Opt-out').trim();
                String ppc3Label = fieldMap.get('PardotPrefCenterOptOut3__c').getDescribe().getLabel().removeEnd('Opt-out').trim();
                String ppc4Label = fieldMap.get('PardotPrefCenterOptOut4__c').getDescribe().getLabel().removeEnd('Opt-out').trim();
                
                if (c.PardotPrefCenterOptOut1__c) {
                    optOutList.add(ppc1Label);
                } else {
                    optInList.add(ppc1Label);
                }
                
                if (c.PardotPrefCenterOptOut2__c) {
                    optOutList.add(ppc2Label);
                } else {
                    optInList.add(ppc2Label);
                }
                
                if (c.PardotPrefCenterOptOut3__c) {
                    optOutList.add(ppc3Label);
                } else {
                    optInList.add(ppc3Label);
                }
                
                if (c.PardotPrefCenterOptOut4__c) {
                    optOutList.add(ppc4Label);
                } else {
                    optInList.add(ppc4Label);
                }
                
                c.EmailPreferences__c = 'Opted-in: ' + String.join(optInList,', ');
                c.EmailPreferences__c = c.EmailPreferences__c +  '\n' + 'Opted-out: ' + String.join(optOutList,', ');
                
            }
            
        }
    }
    
    public static void getCommunitySettings() { 
        
        if(myCustomSetting != null) {
            updateUserOnVestMarkEmail = myCustomSetting.UpdateVestMarkEmailInUserRecord__c;
            eStatementFirmName = myCustomSetting.EndClientCommunityAccountName__c;
            portalUserName = myCustomSetting.PotalUserName__c;
            communityAccountPrefix = myCustomSetting.AccountPrefix__c;
            endClientOwnerId = myCustomSetting.EndClientOwnerId__c;
            
            List<Account> portalFirmTemp = [SELECT Id, Name, Type, RecordTypeId 
                                            FROM Account 
                                            WHERE Name =:EStatementFirmName 
                                            AND Type='Firm'
                                            LIMIT 1];
            
            if(!portalFirmTemp.isEmpty() && portalFirmTemp != null) portalFirm = portalFirmTemp[0];
        }
    }
    
    public static List<Contact> createAccountForEndClients (list<Contact> newContacts) { 
        
        getCommunitySettings();
        map<Contact,Account> c2a = new map<Contact,Account>();
        
        for(Contact c:newContacts) {
            if(c.recordTypeId==ECrecordTypeId && c.AccountId==null) {
                Account a = new Account(Name=CommunityAccountPrefix+' '+c.FirstName+' '+c.LastName, OwnerId = EndClientOwnerId, ParentId=portalFirm.Id);
                c2a.put(c,a);
            }
        }
        
        insert c2a.values();
        
        for(Contact c:c2a.keySet()) {
            c.AccountId = c2a.get(c).Id;
        }
        
        return newContacts;
    }
    
    public static void updateVestmarkEmail (List<Contact> myContacts, Map<Id,Contact> myOldContactMap) { 
        
        getCommunitySettings();
        Map<Id,User> communityContactUserMap = new Map<Id,User>(); 
        
        for (User u : [SELECT Id, ContactId, Email
                       FROM User
                       WHERE ContactId IN :myContacts
                       AND isActive=TRUE]) {
                           communityContactUserMap.put(u.ContactId,u);
                       }
        
        List<User> usersToUpdate = new List<User>();
        
        if(UpdateUserOnVestMarkEmail && !communityContactUserMap.isEmpty()) {
            for (Contact c : myContacts) {
                if (c.VestMarkEmail__c != myOldContactMap.get(c.Id).VestMarkEmail__c 
                    && communityContactUserMap.containsKey(c.Id)) {
                        usersToUpdate.add(new User(Id=communityContactUserMap.get(c.Id).Id,
                                                   Email = c.VestMarkEmail__c));
                        
                    }
            }
        }
        
        if (!usersToUpdate.isEmpty()) update usersToUpdate;
        
    }
    
    public static List<Contact> setFirm(List<Contact> myContacts) {
        
        Set<Id> accountIdSet = new Set<Id>();
        
        for (Contact c : myContacts) {
            accountIdSet.add(c.AccountId);
        }
        
        Map<Id,Account> firmMap = new Map<Id,Account>([SELECT Id, Account.Name, ParentId, Parent.Name, 
                                                       Parent.ParentId, Parent.Parent.Name
                                                       FROM Account
                                                       WHERE Id IN :accountIdSet]);
        
        for (Contact c : myContacts) {
            
            if (firmMap.containsKey(c.AccountId)) {
                system.debug('Parent Parent: ' + firmMap.get(c.AccountId).Parent.ParentId);
                system.debug('Parent : ' + firmMap.get(c.AccountId).ParentId);
                
                if (firmMap.get(c.AccountId).Parent.ParentId == null) {
                    c.Firm__c = firmMap.get(c.AccountId).ParentId;
                    c.FirmNameText__c = firmMap.get(c.AccountId).Parent.Name;
                } else {
                    c.Firm__c = firmMap.get(c.AccountId).Parent.ParentId;
                    c.FirmNameText__c = firmMap.get(c.AccountId).Parent.Parent.Name;
                }
            }
        }
        
        return myContacts;
    }
    
    public static void addRepToMARS(List<Contact> myContacts) {
        
        getCommunitySettings();     
        
        for (Contact c : myContacts) {
            if (c.MarsRepId__c == null && c.RecordTypeId == CRrecordTypeId && !test.isRunningTest()) {
                AddRepToMarsWSC.addRepMarsById(c.Id);  
            }
        }
        
        
    }
    
}