objects/Account.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Affiliate</fullName>
        <active>true</active>
        <label>Affiliate</label>
    </recordTypes>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>AffiliateFirmName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A customized look up field</description>
        <label>Affiliate Firm Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Affiliate</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CaseChannel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The requester's Activity Channel.  This only changes when the requester value changes - not when the requester moves around the role hierarchy.  Set by trigger.</description>
        <label>Case Channel</label>
        <referenceTo>Channel__c</referenceTo>
        <relationshipLabel>Cases (Case Channel)</relationshipLabel>
        <relationshipName>ChannelCases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CaseRegionDept__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The requester's Activity Region or Department.  This only changes when the requester value changes - not when the requester moves around the role hierarchy.  Set by trigger.</description>
        <label>Case Region/Dept</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Cases (Case Region/Dept)</relationshipLabel>
        <relationshipName>RegionCases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CaseTerritory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The requester's Activity Territory.  This only changes when the requester value changes - not when the requester moves around the role hierarchy.  Set by trigger.</description>
        <label>Case Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Cases (Case Territory)</relationshipLabel>
        <relationshipName>TerritoryCases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FirstEventStartDatetime__c</fullName>
        <description>Set by trigger to be the first start date time of the all events associated with the case.</description>
        <inlineHelpText>The first start datetime of the any events associated with the case</inlineHelpText>
        <label>First Event Start Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>IsIPMCase__c</fullName>
        <description>If a case record type is one of the IPM Case record types, true; else false.  Used in process builders, etc. for easy maintenance and reporting.</description>
        <formula>IF(OR(RecordType.Name = 'RFI',RecordType.Name = 'DDQ',RecordType.Name = 'IPM External Request',RecordType.Name = 'IPM Internal Request',RecordType.Name = 'RFP'),TRUE,FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IPM Case?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsPrivateWealthCase__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Private Wealth Case?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LastCommentDatetime__c</fullName>
        <description>Datetime of the last comment made on the case.  Filled by process builder.</description>
        <inlineHelpText>Datetime of the last comment made on the case</inlineHelpText>
        <label>Last Comment Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LastCommentText__c</fullName>
        <description>Stores the first 255 characters of the last comment made on the case.  Filled by workflow.</description>
        <inlineHelpText>Stores the first 255 characters of the last comment made on the case.</inlineHelpText>
        <label>Last Comment Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastEventEndDatetime__c</fullName>
        <description>Set by trigger to be the last end date time of the all events associated with the case.  Used by time-based workflow to automatically close the case after the last even has occurred.</description>
        <inlineHelpText>The last end datetime of the any events associated with the case</inlineHelpText>
        <label>Last Event End Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ProductStrategyMutualFund__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product/Strategy or Mutual Fund related to the RFI/RFP</description>
        <inlineHelpText>Product/Strategy or Mutual Fund related to the RFI/RFP</inlineHelpText>
        <label>Product/Strategy/Mutual Fund</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestFirm__c</fullName>
        <description>A field to support the Affiliate Request process.</description>
        <inlineHelpText>This request is for the following Firms.</inlineHelpText>
        <label>Request for Firm(s)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RequestedSpeakers__c</fullName>
        <description>Field to be populated to start the Affiliate Request process.  Once the requests are approved then the actual Affiliate speakers are captured in the Events associated to the Request. Lookup Rollup Summary: https://globalplatform.my.salesforce.com/a0m2A00000MwtJm</description>
        <inlineHelpText>Field to be populated to start the Affiliate Request process.  Once the requests are approved then the actual Affiliate speakers are captured in the Events associated to the Request.</inlineHelpText>
        <label>Requested Speaker(s)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Artemus.Request.requestor_id
varchar(100)</description>
        <label>Requester</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Requestor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RunCaseAssignmentRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, the case assignment rules will run upon save.</description>
        <label>Run Case Assignment Rules</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RunCaseSharing__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If checked, runs apex case sharing upon save.  Used primarily for realignments.  This should be default of checked.  Apex handles the sharing of cases based on record type, user, etc.and will not share cases that shouldn't be shared.</description>
        <label>Run Case Sharing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SubmittedOnBehalfOf__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to support the Affiliate Request Process</description>
        <label>Submitted on behalf of</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.ActivityReporting__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>User.ActivityZoneId__c</field>
                <operation>notEqual</operation>
                <value>a1bF0000003XUiW,a1bF00000053bto</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>SubmitedOnBehalfOf</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel><enableHistory>true</enableHistory>
    <recordTypes>
        <fullName>RFP</fullName>
        <active>true</active>
        <businessProcess>IPM Standard</businessProcess>
        <description>Used for Request for Proposal (RFP) requests for IPM</description>
        <label>RFP</label>
    </recordTypes>
    <recordTypes>
        <fullName>Termination</fullName>
        <active>true</active>
        <businessProcess>Private Wealth Portal</businessProcess>
        <description>Private Wealth Portal cases that request an account termination</description>
        <label>Termination</label>
    </recordTypes>
    <recordTypes>
        <fullName>Withdrawal</fullName>
        <active>true</active>
        <businessProcess>Private Wealth Portal</businessProcess>
        <description>Private Wealth Portal cases that request an account withdrawal</description>
        <label>Withdrawal</label>
    </recordTypes>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>MARSAffiliate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Affiliate as integrated from MARS; found by looking up Fund Company on Account</description>
        <label>MARS Affiliate</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products (MARS Affiliate)</relationshipLabel>
        <relationshipName>MARSAffiliateProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ActivityChannelId__c</fullName>
        <description>Used To Tag the Activities and Opportunities created by the user.</description>
        <externalId>true</externalId>
        <inlineHelpText>READ ONLY FIELD : This Will be populated by the UserTerritory__c assignment when the Territory Assignment is tagged as an Activity Territory. Please never update this field directly. Instead Delete/Insert the relevant UserTerritory__c record.</inlineHelpText>
        <label>Activity Channel Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryId__c</fullName>
        <description>Used To Tag the Activities and Opportunities created by the user.</description>
        <externalId>true</externalId>
        <inlineHelpText>READ ONLY FIELD : This Will be populated by the UserTerritory__c assignment when the Territory Assignment is tagged as an Activity Territory. Please never update this field directly. Instead Delete/Insert the relevant UserTerritory__c record.</inlineHelpText>
        <label>Activity Territory Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryParentId__c</fullName>
        <description>The Activity Territory's parent Id</description>
        <label>Activity Territory Parent Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CaseTriggerHandler.cls
public class CaseTriggerHandler {    
    
    public static void runCaseSharing (List<Case> myCases, Map<Id,Case> myOldCaseMap) { 
        
        List<Case> casesToShare = new List<Case>();
        List<Case> casesToUpdate = new List<Case>();
        
        for (Case c : myCases) {
           
            if (Trigger.isInsert || 
                c.OwnerId != myOldCaseMap.get(c.Id).OwnerId ||
                 c.Requestor__c != myOldCaseMap.get(c.Id).Requestor__c || 
                 c.SubmittedOnBehalfOf__c != myOldCaseMap.get(c.Id).SubmittedOnBehalfOf__c ||
                c.RunCaseSharing__c == TRUE) {
                    casesToShare.add(c);
            }
            
        }
        
        if (!casesToShare.IsEmpty()) RunCaseSharing.runCaseSharing(casesToShare);
        
    }
    
    public static void setFieldValues (List<Case> myCases, Map<Id,Case> myOldCaseMap) {     
        
        Set<Id> pWCaseRecIds = getPwCaseRecIds();
        
        Id affRequestRecTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Affiliate Request').getRecordTypeId();
        Id IPMRFPRecTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('RFP').getRecordTypeId();
        Id IPMIntReqRecTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('IPM Internal Request').getRecordTypeId();
        Map<Id,Schema.RecordTypeInfo> recordTypeNameMapById = Schema.SObjectType.Case.getRecordTypeInfosById();
        Map<String,Schema.RecordTypeInfo> recordTypeIdMapByName = Schema.SObjectType.Case.getRecordTypeInfosByName();
        
        Set<Id> requestorIdSet = new Set<Id>();
        Set<Id> accountIdSet = new Set<Id>();
        Set<Id> productIdSet = new Set<Id>();
        Map<Id,Product2> productAffiliateMap = new Map<Id,Product2>();
        
        for (Case c : myCases) {
            if (c.Requestor__c == null) c.Requestor__c = c.CreatedById;
            if (c.Requestor__c != null) requestorIdSet.add(c.Requestor__c);
            if (c.AccountId != null) accountIdSet.add(c.AccountId);
            if (c.ProductStrategyMutualFund__c != null) productIdSet.add(c.ProductStrategyMutualFund__c);
        }
        
        if (productIdSet.size()>0) {
            
            productAffiliateMap = new Map<Id,Product2>([SELECT Id, MARSAffiliate__c
                                                        FROM Product2
                                                        WHERE Id in : productIdSet]);
        }
        
        Map<Id,User> userMap = new Map<Id,User>([SELECT ActivityTerritoryId__c, ActivityTerritoryParentId__c, ActivityChannelId__c, LastName, FirstName
                                                 FROM User
                                                 WHERE Id in :requestorIdSet]);
        
        
        Map<Id,Account> accountMap = new Map<Id,Account>([SELECT Name
                                                          FROM Account
                                                          WHERE Id in :accountIdSet]);
        
        for (Case c : myCases) {
            
            if (userMap.containsKey(c.Requestor__c)) {
                c.CaseChannel__c = userMap.get(c.Requestor__c).ActivityChannelId__c;                
                c.CaseTerritory__c = userMap.get(c.Requestor__c).ActivityTerritoryId__c;     
                c.CaseRegionDept__c = userMap.get(c.Requestor__c).ActivityTerritoryParentId__c;     
            }
            
            if (Trigger.IsInsert) {
                c.LastEventEndDatetime__c = null;
                c.FirstEventStartDatetime__c = null;
                c.LastCommentDatetime__c = null;
                c.LastCommentText__c = null;
                c.RunCaseSharing__c = TRUE;
            } 
            
            if (Trigger.IsInsert || c.Requestor__c != myOldCaseMap.get(c.Id).Requestor__c || c.SubmittedOnBehalfOf__c != myOldCaseMap.get(c.Id).SubmittedOnBehalfOf__c) {
                c.RunCaseSharing__c = TRUE;
            }
            
            if ((c.ProductStrategyMutualFund__c != null) && (productAffiliateMap.containsKey(c.ProductStrategyMutualFund__c)) && 
                (Trigger.IsInsert || c.ProductStrategyMutualFund__c != myOldCaseMap.get(c.Id).ProductStrategyMutualFund__c))  {
                    c.AffiliateFirmName__c = productAffiliateMap.get(c.ProductStrategyMutualFund__c).MARSAffiliate__c;
                }
            
            //Set Subject for Affiliate Request Cases   
            If (c.AccountId != null && c.Requestor__c != null && c.RecordTypeId == affRequestRecTypeId) {
                c.Subject = accountMap.get(c.AccountId).Name + '-' + c.RequestedSpeakers__c + '-' +  c.RequestFirm__c + '-' + userMap.get(c.Requestor__c).FirstName + ' ' + userMap.get(c.Requestor__c).LastName;
            }
            
            //Set Subject for IPM Cases
            If (c.AccountId != null && c.Requestor__c != null && c.IsIPMCase__c && c.RecordTypeId != IPMIntReqRecTypeId ) {
                c.Subject = recordTypeNameMapById.get(c.RecordTypeId).Name + ': ' + accountMap.get(c.AccountId).Name;
            }
            
            //Private Wealth Cases
            if (Trigger.IsInsert &&
                recordTypeIdMapByName.containsKey(c.Type)) {
                   if (PwCaseRecIds.contains(recordTypeIdMapByName.get(c.Type).getRecordTypeId())){   
                       c.RecordTypeId = recordTypeIdMapByName.get(c.Type).getRecordTypeId();
                   }
               }
            
            if (pWCaseRecIds.contains(c.RecordTypeId)) {
                c.IsPrivateWealthCase__c = TRUE;
                c.Type = recordTypeNameMapById.get(c.RecordTypeId).getName();
            }
            
        }
    }
    
    public static void runCaseAssignmentRules(List<Case> myCases) {
        
        List<Case> runRules = new List<Case>();
        
        for (Case c : myCases) {
            if (c.RunCaseAssignmentRules__c == TRUE) runRules.add(c);
        }
        
        if (!runRules.isEmpty()) RunCaseAssignmentRules.runCaseAssignmentRules(runRules);
        
    }
    
    public static Set<Id> getPwCaseRecIds() {
        
        Set<Id> PwCaseRecIds = new Set<Id>();
        
        PwCaseRecIds.add(Schema.SObjectType.Case.getRecordTypeInfosByName().get('Private Wealth Portal').getRecordTypeId());
        PwCaseRecIds.add(Schema.SObjectType.Case.getRecordTypeInfosByName().get('Account Investment Change').getRecordTypeId());
        PwCaseRecIds.add(Schema.SObjectType.Case.getRecordTypeInfosByName().get('Account Opening').getRecordTypeId());
        PwCaseRecIds.add(Schema.SObjectType.Case.getRecordTypeInfosByName().get('Ad Hoc Request').getRecordTypeId());
        PwCaseRecIds.add(Schema.SObjectType.Case.getRecordTypeInfosByName().get('Bulk Investment Strategy Swap').getRecordTypeId());
        PwCaseRecIds.add(Schema.SObjectType.Case.getRecordTypeInfosByName().get('Model Update Request').getRecordTypeId());
        PwCaseRecIds.add(Schema.SObjectType.Case.getRecordTypeInfosByName().get('New Model Request').getRecordTypeId());
        PwCaseRecIds.add(Schema.SObjectType.Case.getRecordTypeInfosByName().get('New Requestor').getRecordTypeId());
        PwCaseRecIds.add(Schema.SObjectType.Case.getRecordTypeInfosByName().get('Tax Harvest').getRecordTypeId());
        PwCaseRecIds.add(Schema.SObjectType.Case.getRecordTypeInfosByName().get('Termination').getRecordTypeId());
        PwCaseRecIds.add(Schema.SObjectType.Case.getRecordTypeInfosByName().get('Update to Requestor').getRecordTypeId());
        PwCaseRecIds.add(Schema.SObjectType.Case.getRecordTypeInfosByName().get('Withdrawal').getRecordTypeId());
        
        return PwCaseRecIds;
    }
    
}