objects/Account.object
<CustomObject>
    <fields>
        <fullName>WCMRelationshipFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Maintained by loading firms identified by Data Ops, the data is not integrated. This field is used in formulas at the office and contact level and indicates that the related advisers should not have WCM products discussed with them or related material emailed to them.</description>
        <label>WCM Relationship Flag</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>WCMRelationshipFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox populated by systematically based on the flag on the account.</description>
        <label>WCM Relationship Flag</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/WCMRelationshipSyncOverride__mdt.object
<CustomObject>
    <fields>
        <fullName>SFID__c</fullName>
        <description>The SFID of the account or contact that should not have their WCM Relationship Flag inherited from parent.  Use the 18-digit ID.</description>
        <inlineHelpText>The SFID of the account or contact that should not have their WCM Relationship Flag inherited from parent.  Use the 18-digit ID.</inlineHelpText>
        <label>SFID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <description>If an account or contact is in this list, their record will not inherit the WCM Relationship Flag field value from their parent account.</description>
    <label>WCM Relationship Sync Override</label>
    <pluralLabel>WCM Relationship Sync Overrides</pluralLabel>
</CustomObject>

classes/WCMRelationshipContactSyncBatch.cls
global class WCMRelationshipContactSyncBatch implements Database.batchable<sObject>{

    public String query = ' SELECT Account.WCMRelationshipFlag__c, WCMRelationshipFlag__c ' +
        				  ' FROM Contact ' +
        				  ' WHERE AccountId != null ';
    
    global Database.querylocator start(Database.BatchableContext BC){   
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Contact> scope) {
        
		Set<Id> wcmOverrideSet = new Set<Id>();
        WCMRelationshipSyncOverride__mdt[] wcmOverrides = [SELECT SFID__c FROM WCMRelationshipSyncOverride__mdt];

		for (WCMRelationshipSyncOverride__mdt w : wcmOverrides) {
			wcmOverrideSet.add(w.SFID__c);
		}            
        
        List<Contact> contactsToUpdate = new List<Contact>();
        
        for (Contact c : scope) {
            
            if (c.WCMRelationshipFlag__c != c.Account.WCMRelationshipFlag__c) {
                if (!wcmOverrideSet.contains(c.Id)) {
            		c.WCMRelationshipFlag__c = c.Account.WCMRelationshipFlag__c;
            		contactsToUpdate.add(c);
                }
            }
            
        }
        
        if (!contactsToUpdate.isEmpty()) update contactsToUpdate;
        
    }
    
    global void finish(Database.BatchableContext BC) {

    }
    
    
}