objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>The MARS status of the account, Data Flow: Mars -&gt; SF</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Source: MARS na_load_rep.StatCd
Loaded by a nightly job.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ExternalCommunitySettings__c.object
<CustomObject>
    <fields>
        <fullName>ContactObjectEmailField__c</fullName>
        <description>The field on conatct obejct to use for user email address</description>
        <inlineHelpText>When values in this field change, the email address on the associated community user is updated.</inlineHelpText>
        <label>ContactObjectEmailField</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PemissionSetForEndClient__c</fullName>
        <description>Permission set for end user, Comma delimited string wth permission set's api names</description>
        <inlineHelpText>Permission Set that is assigned to End Client contact user records during setup of Financial Account Contact (type = End Client).</inlineHelpText>
        <label>PemissionSetForEndClient</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PermissionSetsForFAUser__c</fullName>
        <description>Permission set for FA user</description>
        <inlineHelpText>Permission Set that is assigned to Financial Advisor contact user records during setup of Financial Account Contact (type = Financial Advisor).</inlineHelpText>
        <label>PermissionSetsForFAUser</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProfileForEndClient__c</fullName>
        <description>profile for end client or 3 party</description>
        <inlineHelpText>Profile that is assigned to End Client contact user records during setup of Financial Account Contact (type = End Client).</inlineHelpText>
        <label>ProfileForEndClient</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProfileForFAUser__c</fullName>
        <description>Profile name for FA</description>
        <inlineHelpText>Profile that is assigned to Financial Advisor contact user records during setup of Financial Account Contact (type = Financial Advisor).</inlineHelpText>
        <label>ProfileForFAUser</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TestUserEmail__c</fullName>
        <description>Use Test email to create user</description>
        <inlineHelpText>If UseTestEmail is set to 'Y', this is the "to" email that will be used in the place of all community user email addresses.</inlineHelpText>
        <label>TestUserEmail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UseTestEmail__c</fullName>
        <description>For testing use, test email from custom setting Value Y or N</description>
        <inlineHelpText>If set to 'Y', the email address in TestUserEmail setting will be used for all email communications that would normally be sent to the community user.  IMPORTANT: This should be set to Y for all sandbox instances!</inlineHelpText>
        <label>UseTestEmail</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserNameFormat__c</fullName>
        <description>UserNameFormat for user record</description>
        <label>UserNameFormat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>To the custom setting for external communities</description>
    <label>ExternalCommunitySettings</label>
</CustomObject>

objects/FinancialAccountContact__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact related to the Financial Account</description>
        <inlineHelpText>Contact related to the Financial Account</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Financial Account Contact</relationshipLabel>
        <relationshipName>Financial_Account_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Indicates the status of the contact's relationship to the Financial Account</description>
        <inlineHelpText>Indicate the status of the contact's relationship to the Financial Account</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                    <default>true</default>
                    <label>Current</label>
                </value>
                <value>
                    <fullName>Former</fullName>
                </value>
                <value>
                    <fullName>Inactivated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>View_Financial_Account_in_Community__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates if this contact should see the Financial Account in the community.</description>
        <inlineHelpText>If checked, the contact will be able to see the Financial Account in the community</inlineHelpText>
        <label>View Financial Account in Community?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <description>Financial Account to which this contact is related</description>
        <inlineHelpText>Financial Account to which this contact is related</inlineHelpText>
        <label>Financial Account</label>
        <referenceTo>FinancialAccount__c</referenceTo>
        <relationshipLabel>Financial Account Contact</relationshipLabel>
        <relationshipName>Financial_Account_Contact</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <description>Tracks contacts associated with a Financial Account.  Dictates which contacts (community users) can see a particular Financial Account in the community.</description>
    <label>Financial Account Contact</label>
    <nameField>
        <displayFormat>FAC-{000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Used in the Affiliate Request Flow to filter 'Requested on Behalf' of. Can not use Out of Box field for end users.</description>
        <formula>IF( IsActive = True, True, False)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TermsandConditionsLastDeclined__c</fullName>
        <description>Datetime stamp set each time a community user declines the Terms and Conditions.</description>
        <inlineHelpText>Datetime stamp set each time a community user declines the Terms and Conditions.</inlineHelpText>
        <label>Terms and Conditions Last Declined</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/FinancialAccountContactTriggerHandler.cls
public class FinancialAccountContactTriggerHandler {
    
    static ExternalCommunitySettings__c myCustomSetting = ExternalCommunitySettings__c.getValues('EstatementCommunity');
    static string ContactObjectEmailField = myCustomSetting.ContactObjectEmailField__c;
    static string UserNameFormat = myCustomSetting.UserNameFormat__c;
    public static String UseTestEmail = myCustomSetting.UseTestEmail__c;
    static String TestUserEmail  = myCustomSetting.TestUserEmail__c;
    static string PermissionSetForEndClient =   myCustomSetting.PemissionSetForEndClient__c;
    static string ProfileForFAUser =  myCustomSetting.ProfileForFAUser__c;
    static String PermissionSetsForFAUser = myCustomSetting.PermissionSetsForFAUser__c;
    static String ProfileForEndClient = myCustomSetting.ProfileForEndClient__c;
    
    public static void TriggerAfterInsert(List<FinancialAccountContact__c> myFAC){
        
        // Share Financial Account only if the user record for the inserted contact already exists
        // If user doesn't exist, the active, portal enabled user will be created and the FA will be shared durin the batch job
        
        Set<Id> contactSet = new Set<Id>();
        for (FinancialAccountContact__c fac : myFAC) {
            contactSet.add(fac.Contact__c);
        }
        
        List<FinancialAccount__Share> sharesToCreate = new List<FinancialAccount__Share>();
        List<User> contactUserList = new List<User>([SELECT ContactId, Id FROM User
                                                     WHERE IsPortalEnabled = TRUE
                                                     AND ContactId in :contactSet
                                                     AND IsActive = TRUE]);
        Map<Id,Id> contactUserMap = new Map<Id,Id>();
        for (User cu : contactUserList) {
            contactUserMap.put(cu.ContactId,cu.Id);
        }


        List<User> contactUserTCList = new List<User>([SELECT ContactId, Id FROM User
                                                     WHERE IsPortalEnabled = TRUE
                                                     AND ContactId in :contactSet
                                                       AND TermsandConditionsLastDeclined__c != null
                                                     AND IsActive = FALSE]);
        for (User u : contactUserTCList) {
        	removeTCDeclined(u.Id);
            }

        
        for (FinancialAccountContact__c fac : myFAC) {
            if (contactUserMap.containsKey(fac.Contact__c) && fac.Status__c == 'Current' && fac.View_Financial_Account_in_Community__c == TRUE) {
                
                FinancialAccount__Share cs = new FinancialAccount__Share(AccessLevel='Read',ParentId=fac.Financial_Account__c,
                                                                         RowCause=Schema.FinancialAccount__Share.RowCause.Manual,
                                                                         UserOrGroupId=contactUserMap.get(fac.Contact__c));
                sharesToCreate.add(cs);  
            }
            
            if(!sharesToCreate.isEmpty()) {
                upsert  sharesToCreate;
            }
        }
    }

	@future
    public static void removeTCDeclined(String userId) {
        User u = [SELECT Id, TermsandConditionsLastDeclined__c FROM User WHERE Id =: userId LIMIT 1];
        u.TermsandConditionsLastDeclined__c = null;
        update u;
    }
    
    public static void TriggerAfterDelete(List<FinancialAccountContact__c> myFAC){
        
        // Unshare Financial Account
        String RowCauseManual = Schema.FinancialAccount__Share.RowCause.Manual;
        
        Set<Id> financialAccountSet = new Set<Id>();
        Set<Id> contactSet = new Set<Id>();
        for (FinancialAccountContact__c fac : myFAC) {
            financialAccountSet.add(fac.Financial_Account__c);
            contactSet.add(fac.Contact__c);
        }
        
        List<User> contactUserList = new List<User>([SELECT ContactId, Id FROM User
                                                     WHERE ContactId in :contactSet]);
        
        Set<Id> contactUserSet = new Set<Id>();
        for (User cu : contactUserList) {
            contactUserSet.add(cu.Id);
        }
        
        List<FinancialAccount__share> sharesToDelete = new List<FinancialAccount__share>([SELECT Id, ParentId, UserOrGroupId
                                                                                          FROM FinancialAccount__Share
                                                                                          WHERE ParentId in : financialAccountSet
                                                                                          AND UserOrGroupId in : contactUserSet
                                                                                          AND RowCause = :RowCauseManual
                                                                                          AND AccessLevel = 'Read']);
        if(!sharesToDelete.isEmpty()) {
            delete sharesToDelete;
        }
    }
    
    
    //-----------------------------------------------------------------------------------------------------------------------------------------------
    // TriggerAfterUpdate
    //-----------------------------------------------------------------------------------------------------------------------------------------------
    public static void TriggerAfterUpdate(List<FinancialAccountContact__c> myFAC, Map<Id,FinancialAccountContact__c> myFACOldMap)
    {  
        String RowCauseManual = Schema.FinancialAccount__Share.RowCause.Manual;
        Set<Id> financialAccountSet = new Set<Id>();
        Set<Id> contactSetDel = new Set<Id>();
        Set<Id> contactSetAdd = new Set<Id>();
        
        for (FinancialAccountContact__c fac : myFAC) {
            financialAccountSet.add(fac.Financial_Account__c);
            if (fac.Status__c == 'Former' || fac.View_Financial_Account_in_Community__c == FALSE) {
                contactSetDel.add(fac.Contact__c);
            }
            if (fac.Status__c == 'Current' || fac.View_Financial_Account_in_Community__c == TRUE) {
                contactSetAdd.add(fac.Contact__c);
            }
       }
        
        List<User> contactUserListDel = new List<User>([SELECT ContactId, Id FROM User
                                                        WHERE ContactId in :contactSetDel]);
        
        Set<Id> contactUserSetDel = new Set<Id>();
        for (User cu : contactUserListDel) {
            contactUserSetDel.add(cu.Id);
        }
        
        List<FinancialAccount__share> sharesToDelete = new List<FinancialAccount__share>([SELECT Id, ParentId, UserOrGroupId
                                                                                          FROM FinancialAccount__Share
                                                                                          WHERE ParentId in : financialAccountSet
                                                                                          AND UserOrGroupId in : contactUserSetDel
                                                                                          AND RowCause = :RowCauseManual
                                                                                          AND AccessLevel = 'Read']);
        if(!sharesToDelete.isEmpty()) {
            delete sharesToDelete;
        }

        List<FinancialAccount__Share> sharesToCreate = new List<FinancialAccount__Share>();
        List<User> contactUserList = new List<User>([SELECT ContactId, Id FROM User
                                                     WHERE IsPortalEnabled = TRUE
                                                     AND ContactId in :contactSetAdd
                                                     AND IsActive = TRUE]);
        Map<Id,Id> contactUserMap = new Map<Id,Id>();
        for (User cu : contactUserList) {
            contactUserMap.put(cu.ContactId,cu.Id);
        }

        /*List<User> contactUserTCList = new List<User>([SELECT ContactId, Id FROM User
                                                     WHERE IsPortalEnabled = TRUE
                                                     AND ContactId in :contactSetAdd
                                                       AND TermsandConditionsLastDeclined__c != null
                                                     AND IsActive = FALSE]);
        for (User u : contactUserTCList) {
        	removeTCDeclined(u.Id);
            }*/

        for (FinancialAccountContact__c fac : myFAC) {
            if (contactUserMap.containsKey(fac.Contact__c) && fac.Status__c == 'Current' && fac.View_Financial_Account_in_Community__c == TRUE) {
                
                FinancialAccount__Share cs = new FinancialAccount__Share(AccessLevel='Read',ParentId=fac.Financial_Account__c,
                                                                         RowCause=Schema.FinancialAccount__Share.RowCause.Manual,
                                                                         UserOrGroupId=contactUserMap.get(fac.Contact__c));
                sharesToCreate.add(cs);  
            }
            
            if(!sharesToCreate.isEmpty()) {
                upsert  sharesToCreate;
            }
        }
        
    }
}