objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>The MARS status of the account, Data Flow: Mars -&gt; SF</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Source: MARS na_load_rep.StatCd
Loaded by a nightly job.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VestmarkEmail__c</fullName>
        <description>This field store the email address of the FA in VestMark system and used for Estatement project</description>
        <inlineHelpText>This field store the email address of the FA in VestMark system.</inlineHelpText>
        <label>Vestmark Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ExternalCommunitySettings__c.object
<CustomObject>
    <fields>
        <fullName>CommunityInternalSender__c</fullName>
        <description>To addresses for Batch jobs</description>
        <inlineHelpText>Determines the email address that batch completion emails should go to.  This should be dat@ngam.natixis.com unless you are testing.</inlineHelpText>
        <label>CommunityInternalSender</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CommunitySenderDisplayName__c</fullName>
        <description>CommunitySenderDisplayName for emails.  Necessary for sending the notification that new statements have been posted.</description>
        <inlineHelpText>Indicates the email from name on the notification to FA's that new statements have been posted.  This should always be Portal Solutions unless branding changes.</inlineHelpText>
        <label>CommunitySenderDisplayName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CommunitySenderEmail__c</fullName>
        <description>Email for sending the comunity email</description>
        <inlineHelpText>Indicates the email from address on the notification to FA's that new statements have been posted. This should always be Portal Solutions unless branding changes</inlineHelpText>
        <label>CommunitySenderEmail</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndClientCommunityAccountName__c</fullName>
        <description>The name of the Account (Firms Office) to which End Client/Interested 3rd Party community contacts will belong.</description>
        <inlineHelpText>The name of the Account (Firms Office) to which new End Client/Interested 3rd Party community contacts belong.  This should always be NGAM DISTRIBUTION, L.P., PORTAL END CLIENTS</inlineHelpText>
        <label>EndClientCommunityAccountName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExternalEmailTemplate__c</fullName>
        <description>Email's template developer name use for sending the emails to EndClient</description>
        <inlineHelpText>The email template used for notifying community users of new statements.</inlineHelpText>
        <label>ExternalEmailTemplateDevName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InactivateDaysForUserLogin__c</fullName>
        <defaultValue>180</defaultValue>
        <description>Inactivate the users after x numbers of days</description>
        <inlineHelpText>Users that have not logged in after this number of days are inactivated in a nightly batch job.</inlineHelpText>
        <label>InactivateDaysForUserLogin</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PemissionSetForEndClient__c</fullName>
        <description>Permission set for end user, Comma delimited string wth permission set's api names</description>
        <inlineHelpText>Permission Set that is assigned to End Client contact user records during setup of Financial Account Contact (type = End Client).</inlineHelpText>
        <label>PemissionSetForEndClient</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PermissionSetsForFAUser__c</fullName>
        <description>Permission set for FA user</description>
        <inlineHelpText>Permission Set that is assigned to Financial Advisor contact user records during setup of Financial Account Contact (type = Financial Advisor).</inlineHelpText>
        <label>PermissionSetsForFAUser</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PotalUserName__c</fullName>
        <description>Portal user name</description>
        <label>PotalUserName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProfileForEndClient__c</fullName>
        <description>profile for end client or 3 party</description>
        <inlineHelpText>Profile that is assigned to End Client contact user records during setup of Financial Account Contact (type = End Client).</inlineHelpText>
        <label>ProfileForEndClient</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProfileForFAUser__c</fullName>
        <description>Profile name for FA</description>
        <inlineHelpText>Profile that is assigned to Financial Advisor contact user records during setup of Financial Account Contact (type = Financial Advisor).</inlineHelpText>
        <label>ProfileForFAUser</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TestUserEmail__c</fullName>
        <description>Use Test email to create user</description>
        <inlineHelpText>If UseTestEmail is set to 'Y', this is the "to" email that will be used in the place of all community user email addresses.</inlineHelpText>
        <label>TestUserEmail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UseTestEmail__c</fullName>
        <description>For testing use, test email from custom setting Value Y or N</description>
        <inlineHelpText>If set to 'Y', the email address in TestUserEmail setting will be used for all email communications that would normally be sent to the community user.  IMPORTANT: This should be set to Y for all sandbox instances!</inlineHelpText>
        <label>UseTestEmail</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserNameFormat__c</fullName>
        <description>UserNameFormat for user record</description>
        <label>UserNameFormat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>To the custom setting for external communities</description>
    <label>ExternalCommunitySettings</label>
</CustomObject>

objects/FinancialAccount__c.object
<CustomObject>
    <description>Used in community to display Financial Account data to community users.  This object's data is sourced from Data Central and maintained via integration.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/FinancialAccountContact__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact related to the Financial Account</description>
        <inlineHelpText>Contact related to the Financial Account</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Financial Account Contact</relationshipLabel>
        <relationshipName>Financial_Account_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Indicates the status of the contact's relationship to the Financial Account</description>
        <inlineHelpText>Indicate the status of the contact's relationship to the Financial Account</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                    <default>true</default>
                    <label>Current</label>
                </value>
                <value>
                    <fullName>Former</fullName>
                </value>
                <value>
                    <fullName>Inactivated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Indicates the type of relationship this contact has to the Financial Account</description>
        <inlineHelpText>Indicate the type of relationship this contact has to the Financial Account</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>End Client</fullName>
                </value>
                <value>
                    <fullName>Financial Advisor</fullName>
                    <default>true</default>
                    <label>Financial Advisor</label>
                </value>
                <value>
                    <fullName>Interested 3rd Party</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>View_Financial_Account_in_Community__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates if this contact should see the Financial Account in the community.</description>
        <inlineHelpText>If checked, the contact will be able to see the Financial Account in the community</inlineHelpText>
        <label>View Financial Account in Community?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <description>Financial Account to which this contact is related</description>
        <inlineHelpText>Financial Account to which this contact is related</inlineHelpText>
        <label>Financial Account</label>
        <referenceTo>FinancialAccount__c</referenceTo>
        <relationshipLabel>Financial Account Contact</relationshipLabel>
        <relationshipName>Financial_Account_Contact</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <description>Tracks contacts associated with a Financial Account.  Dictates which contacts (community users) can see a particular Financial Account in the community.</description>
    <label>Financial Account Contact</label>
    <nameField>
        <displayFormat>FAC-{000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <description>This field will be populated by EPAT-SFDC job with ITSM# - Effective Date - EPAT Request Type. Every new request will append to the previous comments. If manually added, please add teh SR# or Incident task#.</description>
        <inlineHelpText>This field will be populated by EPAT-SFDC job with ITSM# - Effective Date - EPAT Request Type. Every new request will append to the previous comments. If manually added, please add teh SR# or Incident task#.</inlineHelpText>
        <label>Comments</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CommunityStatus__c</fullName>
        <description>For community users who have been inactivated, this field contains the reason for inactivation.  If the user is active, it contains "Active".</description>
        <inlineHelpText>For community users who have been inactivated, this field contains the reason for inactivation.  If the user is active, it contains "Active".</inlineHelpText>
        <label>Community Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Used in the Affiliate Request Flow to filter 'Requested on Behalf' of. Can not use Out of Box field for end users.</description>
        <formula>IF( IsActive = True, True, False)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TermsConditionFileVersionID__c</fullName>
        <description>Field to store latest  ContentVersion Id for Terms and Conditions File that is accepted by community user</description>
        <inlineHelpText>Field to store latest  ContentVersion Id for Terms and Conditions File that is accepted by community user</inlineHelpText>
        <label>Terms and Conditions File Version ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TermsConditionsAcceptAfterDecline__c</fullName>
        <formula>IF( TermsConditionsLastAccepted__c &gt;  TermsandConditionsLastDeclined__c , TRUE, FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Terms Conditions Accept After Decline</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TermsConditionsLastAccepted__c</fullName>
        <description>Last time the user has accepted the Terms and Conditions of the community site.  This is set by Community User T&amp;C Log-in Flow</description>
        <inlineHelpText>Last time the user has accepted the Terms and Conditions of the community site.</inlineHelpText>
        <label>Terms Conditions Last Accepted</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>TermsandConditionsLastDeclined__c</fullName>
        <description>Datetime stamp set each time a community user declines the Terms and Conditions.</description>
        <inlineHelpText>Datetime stamp set each time a community user declines the Terms and Conditions.</inlineHelpText>
        <label>Terms and Conditions Last Declined</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>UserID__c</fullName>
        <defaultValue>"Populate This Field"</defaultValue>
        <externalId>true</externalId>
        <label>UserID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CommunitiesReactivateUserBatch.cls
global class CommunitiesReactivateUserBatch implements Database.Batchable<sObject>, Database.Stateful{
    
    // This Batch job inactivates the users that do not any accounts associated with them
    Public integer Count = 0;
    
    // Get info from Custom setting
    static ExternalCommunitySettings__c myCustomSetting = ExternalCommunitySettings__c.getValues('EstatementCommunity');
    static string UserNameFormat = myCustomSetting.UserNameFormat__c;
    static string EStatementFirmName = myCustomSetting.EndClientCommunityAccountName__c;
    static string PortalUserName = myCustomSetting.PotalUserName__c;
    static string PermissionSetForEndClient =   myCustomSetting.PemissionSetForEndClient__c;
    static string ProfileForFAUser =  myCustomSetting.ProfileForFAUser__c;
    static String PermissionSetsForFAUser = myCustomSetting.PermissionSetsForFAUser__c;
    static Integer InactivateDaysForUserLogin = (Integer)myCustomSetting.InactivateDaysForUserLogin__c;
    static String ProfileForEndClient = myCustomSetting.ProfileForEndClient__c;
    static String EmailSenderAddress = myCustomSetting.CommunitySenderEmail__c;
    static String ExternalEmailTemplateDevName = myCustomSetting.ExternalEmailTemplate__c;  
    static String CommunityInternalSender = myCustomSetting.CommunityInternalSender__c;
    static String CommunitySenderDisplayName = myCustomSetting.CommunitySenderDisplayName__c;
    static String UseTestEmail = myCustomSetting.UseTestEmail__c;
    static String TestUserEmail = myCustomSetting.TestUserEmail__c;
    static String CompareNDays = '1';
    
    public String query = 'SELECT Id, Financial_Account__c, Contact__c, Type__c, Status__c, View_Financial_Account_in_Community__c FROM FinancialAccountContact__c WHERE Status__c = \'Current\' AND View_Financial_Account_in_Community__c = TRUE';
    
    List<FinancialAccount__Share> sharesToCreate = new List<FinancialAccount__Share>();
    List<PermissionSetAssignment> PA = new List<PermissionSetAssignment>();
    Public String msg = '';
    
    global CommunitiesReactivateUserBatch() {
        
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {       
        System.Debug('Query - ' + query);      
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<FinancialAccountContact__c> scope) {
        
        Map<Id,String> facType = new Map<Id,String>();
        for (FinancialAccountContact__c t : scope) {
            facType.put(t.Contact__c, t.Type__c);
        }
        
        Map<Id,Id> contactUserMap = new Map<Id,Id>();
        Map<Id,Id> createdUserMap = new Map<Id,Id>();
        Map<String,Id> profPermSetIdMap = new Map<String,Id>();
        Profile FAProfile = [SELECT Name, Id FROM Profile WHERE name=:ProfileForFAUser LIMIT 1];  
        Profile EndClientProfile = [SELECT Name, Id FROM profile WHERE name=:ProfileForEndClient LIMIT 1]; 
        PermissionSet FAPS = [SELECT Name, Id FROM PermissionSet WHERE name=:PermissionSetsForFAUser LIMIT 1];
        PermissionSet ECPS = [SELECT Name, Id FROM PermissionSet WHERE name=:PermissionSetForEndClient LIMIT 1];
        
        profPermSetIdMap.put(FAProfile.Name, FAProfile.Id);
        profPermSetIdMap.put(EndClientProfile.Name, EndClientProfile.Id);
        profPermSetIdMap.put(FAPS.Name, FAPS.Id);
        profPermSetIdMap.put(ECPS.Name, ECPS.Id);
        
        List<PermissionSetAssignment> permSetToAssign = New List<PermissionSetAssignment>();
        List<PermissionSetAssignment> permSetToAssignR = New List<PermissionSetAssignment>();
        List<User> usersToUpdate = new List<User>();
        List<User> usersToCreate = new List<User>();
        
        Set<Id> contactSet = new Set<Id>();
        Set<Id> financialAccountSet = new Set<Id>();
        Set<Id> contactAlreadyUserSet = new Set<Id>();
        Set<Id> inActiveUserSet = new Set<Id>();
        Set<Id> ActiveUserSet = new Set<Id>();

        for (FinancialAccountContact__c facSet : scope) {
            contactSet.add(facSet.Contact__c);
            financialAccountSet.add(facSet.Financial_Account__c);
        }

        // Reactivate Users
        List<User> contactAlreadyUser = new List<User>([SELECT ContactId, IsActive, FirstName, LastName, Id FROM User
                                                        WHERE IsPortalEnabled = TRUE
                                                        AND ContactId in :contactSet]);
        
        for (User uAA : contactAlreadyUser) {
            contactAlreadyUserSet.add(uAA.ContactId);
            contactUserMap.put(uAA.ContactId,uAA.Id);
        }
        
        Date d = System.today() - InactivateDaysForUserLogin;

        system.debug('d: ' + d);
		        
        List<User> userToActivate = new List<User>([SELECT ContactId, IsActive, FirstName, LastName, Id FROM User
                                                    WHERE IsPortalEnabled = TRUE
                                                    AND ContactId in :contactSet
                                                    // Inactivated users now have their CommunityStatus__c set to Inactive so these criteria are unnessary.
                                                    // When an internal user resets the Finanical Account Contact to Current this job automatically removes the
                                                    // TermsandConditionsLastDeclined__c to null and we don't care about the LastLoginDate for reactivation.
                                                    //AND (TermsandConditionsLastDeclined__c = null 
                                                    //     OR TermsConditionsAcceptAfterDecline__c = TRUE)
                                                    //AND ((LastLoginDate = null AND CreatedDate < :d) OR lastloginDate < : d)
                                                    AND IsActive = FALSE]);
        
        for (User uTa : userToActivate) {
            inActiveUserSet.add(uTa.ContactId);
            uTa.IsActive = TRUE;
            uTa.CommunityStatus__c = 'Active';
            uTa.Comments__c = uta.Comments__c + '-Reactivated ' + Datetime.now();
            uTa.TermsandConditionsLastDeclined__c = null;
            uTa.TermsConditionsLastAccepted__c = null;
            uTa.TermsConditionFileVersionID__c = null;
            usersToUpdate.add(uTa);
        }
        
        system.debug('usersToUpdate: ' + usersToUpdate);
        
        if (usersToUpdate.size() > 0) {
            update usersToUpdate;
        }
        
        // Recreate Permission Sets
        List<PermissionSetAssignment> cps = [SELECT Id,PermissionSetId,AssigneeId FROM PermissionSetAssignment WHERE AssigneeId IN :usersToUpdate]; 
        Map<Id,Id> cpsMapFA = new Map<Id,Id>();
        Map<Id,Id> cpsMapEC = new Map<Id,Id>();
        
        for (PermissionSetAssignment pa : cps) {
            
            if (pa.PermissionSetId == profPermSetIdMap.get(PermissionSetsForFAUser)) {
                cpsMapFA.put(pa.AssigneeId,pa.PermissionSetId);
            } else {
                cpsMapEC.put(pa.AssigneeId,pa.PermissionSetId);
            }
            
        }
        
        
        for (User psa : usersToUpdate) {
            
            if (facType.get(psa.ContactId) == 'Financial Advisor' && !cpsMAPFA.containsKey(psa.Id)) {
                PermissionSetAssignment permassign = new PermissionSetAssignment(PermissionSetId = profPermSetIdMap.get(PermissionSetsForFAUser), AssigneeId=psa.Id);
                permSetToAssignR.add(permassign);            
            }
            
            if (facType.get(psa.ContactId) == 'End Client' && !cpsMAPEC.containsKey(psa.Id)) {
                PermissionSetAssignment permassign = new PermissionSetAssignment(PermissionSetId = profPermSetIdMap.get(PermissionSetForEndClient), AssigneeId=psa.Id);
                permSetToAssignR.add(permassign);            
            }
        }
        
        system.debug('permSetToAssignR: '+ permSetToAssignR);
        if (!permSetToAssignR.isEmpty()){
            insert permSetToAssignR;            
        }
        
        
        // Create Users
        for (Contact contactNewUsers : [SELECT Id, IsDeleted, AccountId, LastName, Salutation, FirstName, Name, 
                                        RecordTypeId, MailingStreet, MailingCity, MailingState, MailingPostalCode, 
                                        MailingCountry, MailingStateCode, MailingCountryCode, MailingLatitude, MailingLongitude, 
                                        MailingGeocodeAccuracy, Phone, Fax, MobilePhone, HomePhone, Email, Title, Status__c, VestMarkEmail__c 
                                        FROM Contact 
                                        WHERE Id IN :contactSet 
                                        AND Id NOT IN :contactAlreadyUserSet]) {
                                            
                                            Id profileId = (facType.get(contactNewUsers.Id) == 'Financial Advisor') ? profPermSetIdMap.get(ProfileForFAUser) : profPermSetIdMap.get(ProfileForEndClient);
                                            String username = GetUniqueUsername(contactNewUsers.FirstName,contactNewUsers.LastName);
                                            String userId = GetUserId(contactNewUsers.FirstName,contactNewUsers.LastName);
                                            
                                            String Email = TestUserEmail;
                                            if (UseTestEmail != 'Y') {Email = contactNewUsers.VestMarkEmail__c;}
                                            if (Email == null) {Email = contactNewUsers.Email;}
                                            
                                            User nCU = new User(contactId=contactNewUsers.Id, 
                                                                username=username, 
                                                                IsActive=TRUE,
                                                                firstname=contactNewUsers.FirstName,
                                                                lastname=contactNewUsers.LastName, 
                                                                email= Email,
                                                                communityNickname = contactNewUsers.LastName + '_'+getRandomNumber(),
                                                                alias = UserID, 
                                                                UserID__c  = username, 
                                                                profileid = profileId, 
                                                                emailencodingkey='UTF-8',
                                                                languagelocalekey='en_US', 
                                                                localesidkey='en_US', 
                                                                timezonesidkey='America/Los_Angeles',
                                                                CommunityStatus__c = 'Active');  
                                            usersToCreate.add(nCU); 
                                        }
        if (usersToCreate.size() > 0) {
			insert usersToCreate;
        }
        
        for (User cUMap : usersToCreate) {
            createdUserMap.put(cUMap.ContactId,cUMap.Id);
        }            
        
        // Create Permission Sets
        for (User psa : usersToCreate) {
            Id permSetId = (facType.get(psa.ContactId) == 'Financial Advisor') ? profPermSetIdMap.get(PermissionSetsForFAUser) : profPermSetIdMap.get(PermissionSetForEndClient);            
            PermissionSetAssignment permassign = new PermissionSetAssignment (PermissionSetId = permSetId, AssigneeId = psa.Id);
            permSetToAssign.add(permassign);
        }
        
        if (permSetToAssign.size() > 0) {
            Database.DMLOptions dlo = new Database.DMLOptions();
			dlo.EmailHeader.triggerUserEmail = true;
            database.insert(permSetToAssign, dlo);
        }
        
        for (User cuMap : usersToCreate) {
            contactUserMap.put(cuMap.ContactId,cuMap.Id);
        }
        
        // Financial Account Shares
        List<FinancialAccount__Share> alreadySharedList = [SELECT Id,UserOrGroupId,ParentId FROM FinancialAccount__Share 
                                                           WHERE UserOrGroupId IN (SELECT Id FROM User WHERE ContactId in :contactSet)
                                                           AND ParentId IN (SELECT Id FROM FinancialAccount__c where Id in :financialAccountSet)];
        Map<String,String> sharedMap = new Map<String,String>();
        for (FinancialAccount__Share ash : alreadySharedList) {
            sharedMap.put((String)ash.ParentId+':'+(String)ash.UserOrGroupId,'foo');
        } 
         
        
        for (FinancialAccountContact__c fac : scope) {
            if (contactUserMap.containsKey(fac.Contact__c) && !sharedMap.containsKey(fac.Financial_Account__c+':'+fac.Contact__c)) {
                FinancialAccount__Share cs = new FinancialAccount__Share(AccessLevel='Read',ParentId=fac.Financial_Account__c,
                                                                         RowCause=Schema.FinancialAccount__Share.RowCause.Manual,
                                                                         UserOrGroupId=contactUserMap.get(fac.Contact__c));
                sharesToCreate.add(cs);  
            }
        }
        
        system.debug('sharesToCreate: ' + sharesToCreate);
        
        // Prepare email and Share list
        String TempMsg = '';
        if (usersToUpdate.size()>0){ 
            TempMsg = TempMsg + '<br/><table  border= "1" >';
            TempMsg = TempMsg + '<tr><th> Reactivated </th></tr>';
            TempMsg = TempMsg + '<tr><th> Contact Id  </th><th> User Name </th></tr>';
            for (User uTA : userToActivate)
            {
                TempMsg = TempMsg + '<tr><td>' +uTA.ContactId + '</td><td>' +uTA.FirstName + ' ' + uTA.LastName + '</td></tr>';
            }   
            TempMsg = TempMsg + '</table><br/><br/>';
        }
        
        if (usersToCreate.size()>0){
            TempMsg = TempMsg + '<br/><table  border= "1" >';
            TempMsg = TempMsg + '<tr><th> Created </th></tr>';
            TempMsg = TempMsg + '<tr><th> Contact Id  </th><th> User Name </th></tr>';
            for (User uTA : usersToCreate)
            {
                TempMsg = TempMsg + '<tr><td>' +uTA.ContactId + '</td><td>' +uTA.FirstName + ' ' + uTA.LastName + '</td></tr>';
            }   
            TempMsg = TempMsg + '</table><br/>';
        }
        msg = TempMsg;
    }
    
    public static String GetUniqueUsername(String FN,String LN )
    {
        String username = '';
        String UserID = GetUserID(FN,LN);
        Integer count = 1;
        Boolean exist = true;
        while (exist == true && count < 20) {
            System.debug(count);
            // if(FN != null)  UserID = FN.trim().deleteWhitespace().leftpad(1).replace('  ','f');
            // if(LN != null)  UserID = UserID + LN.trim().deleteWhitespace().leftpad(1).replace('  ','l'); 
            String random =   string.valueof(getRandomNumber()).deleteWhitespace();
            System.debug('random' + random);
            random = random.leftPad(5).replace(' ','0').substring(0,5);
            System.debug('random' + random);
            username =  UserNameFormat.replace('{0}',  UserID );
            username = username.replace('{1}', random);
            // check user name exist
            List<User> users = [SELECT Id,Name,ContactId,IsPortalEnabled FROM User where Username=:username];
            if(!users.isEmpty())
            {
                exist = true;
                System.debug('INFO - ' + username + ' already exist');
            }
            else
            {
                exist = false;
                System.debug('INFO ' + username + ' is new user name.');
            }
            count++;
        }
        
        return username;
    }
    
    
    public  Static  void SendFinishEmail(String msg,string subject)
    {
        If (msg != '') {
            List<String> toAddresses = CommunityInternalSender.Split(',');            
            CommunitiesEmailHelper.sendEmail(toAddresses, null, EmailSenderAddress, CommunitySenderDisplayName, msg, subject,true);
        }
    }
    
    public static Integer getRandomNumber(){
        Double d = math.random() * 100000000;
        return d.intValue();
    }
    
    public static String GetUserID(String FN,String LN )
    {
        String UserID = '';
        if(FN != null)  
            UserID = FN.trim().deleteWhitespace().leftpad(1).replace('  ','f').substring(0,1);
        else UserID = 'f';
        if(LN != null) 
            UserID = UserID + LN.trim().deleteWhitespace().leftpad(1).replace('  ','l').substring(0,1); 
        else
            UserID = UserID +'l';
        System.debug(UserID + ' UserID');  
        return UserID;  
    }
    
    
    global void finish(Database.BatchableContext BC) {
        system.debug('sharesToCreate finish: ' + sharesToCreate);
        
        if (sharesToCreate.size() > 0) {
            insert sharesToCreate;
        }
        SendFinishEmail(msg,'Activate Portal User Batch Job');
    }
    
    
    
    
}