objects/Account.object
<CustomObject>
    <fields>
        <fullName>Zone__c</fullName>
        <description>Target for deletion; Original Zone field that aggregated data for FS but will become moot</description>
        <formula>CASE( $User.ActivityChannelName__c , 
'ADU', ZoneADU_IDU__r.Name, 
'IDU', ZoneADU_IDU__r.Name, 
'RCDU', ZoneRCDU__r.Name, 
'RADU', ZoneRADU__r.Name, 
'FIDUCIARY SERVICES', ZoneFS__r.Name , 
'DC REGIONAL', ZoneRADU__r.Name , 
'DCIO', ZoneRADU__r.Name , 
'DCIO SUB ADV', ZoneRADU__r.Name , 
'No Zone')</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Zone Aggregated</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Zone__c</fullName>
        <description>Populates the Zone field with the logged in users Activity Channel.  The logic needs to look at the Users Activity Channel so that only values relevant to the user are returned.</description>
        <formula>CASE( $User.ActivityChannelName__c , 
'RCDU DIRECT',ZoneRCDU__r.Name,
'RCDU BACK OFFICE',ZoneRCDU__r.Name,
'RCDU GKA',ZoneRCDU__r.Name, 
'RCDU INSTL',ZoneRCDU__r.Name, 
'RCDU WHSE BT',ZoneRCDU__r.Name,
'RCDU WHSE/IND',ZoneRCDU__r.Name, 
'RADU REGIONAL',ZoneRADU__r.Name,  
'RADU',ZoneRADU__r.Name, 
'No Zone')</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Channel Specific Zone, based on Logged in User Activity Channel</inlineHelpText>
        <label>Zone Aggregated</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/NGAMSettings__c.object
<CustomObject>
    <fields>
        <fullName>ProfileSystemAdministrator__c</fullName>
        <description>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</description>
        <inlineHelpText>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</inlineHelpText>
        <label>Profile: System Administrator</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Holds the NGAM settings</description>
    <label>NGAM Settings</label>
</CustomObject>

objects/NGAMSettingsHierarchy__c.object
<CustomObject>
    <fields>
        <fullName>ByPassAccountValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows entity to by-pass validation rules on Account</description>
        <inlineHelpText>Allows entity to by-pass validation rules on Account</inlineHelpText>
        <label>By-Pass Account Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NGAM Settings - Hierarchy</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>PrimaryChannelId__c</fullName>
        <label>Primary Channel Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryChannel__c</fullName>
        <label>Primary Channel</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserID__c</fullName>
        <defaultValue>"Populate This Field"</defaultValue>
        <externalId>true</externalId>
        <label>UserID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ZoneID__c</fullName>
        <externalId>true</externalId>
        <label>Zone ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Zone__c.object
<CustomObject>
    <fields>
        <fullName>Zone__c</fullName>
        <externalId>true</externalId>
        <label>Zone</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TopProducers_Test.cls
@isTest(SeeAllData=false)
public class TopProducers_Test {
    
    
            static testMethod void TopProducersTest() 
            {
            
        NGAMSettingsHierarchy__c hsettings = NGAMSettingsHierarchy__c.getOrgDefaults();
        hsettings.ByPassAccountValidationRules__c  = TRUE;
        upsert hsettings NGAMSettingsHierarchy__c.Id;

            //Profile p = [select id from profile where name='System Administrator']; 
            DataFactory.CreateNGAMCustomSettings(); 
            NGAMSettings__c ngamSettings = [select id,ProfileSystemAdministrator__c from NGAMSettings__c limit 1]; 
            string p = Util.getCustomSettingProfileId(ngamSettings.ProfileSystemAdministrator__c);   
            //Zone__c myZOne = [select id from zone__c limit 1][0];  
            User u2 = new User(alias = 'standt', email='SFDCadmin@ngam.natixis.com', 
                                emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
                                localesidkey='en_US', profileid = p, 
                                timezonesidkey='America/Los_Angeles', 
                                username='SFDCadmin@ngam.natixis.com',
                                UserID__c='SFDCadmin',
                                PrimaryChannelId__c='a1EF00000005Ws3MAE',
                                PrimaryChannel__c='WIREHOUSE'
                                //ZoneId__c = myZOne.id
                             );
        
        System.runAs(u2) 
                {
              List<Account> myAccounts = DataFactory.createTestAccounts(3);
             insert myAccounts;
                    
                List<Contact> myContacts = DataFactory.createTestContacts(3, myAccounts, false);
                insert myContacts;    
                 //start the test execution context
                Test.startTest();
                TopProducers topproducers = new TopProducers(); 
                List<Contact> c  = topproducers.getContacts() ;
                 Test.stopTest();  
                }
                }

}