objects/Account.object
<CustomObject>
    <fields>
        <fullName>Zone__c</fullName>
        <description>Target for deletion; Original Zone field that aggregated data for FS but will become moot</description>
        <formula>CASE( $User.ActivityChannelName__c , 
'ADU', ZoneADU_IDU__r.Name, 
'IDU', ZoneADU_IDU__r.Name, 
'RCDU', ZoneRCDU__r.Name, 
'RADU', ZoneRADU__r.Name, 
'FIDUCIARY SERVICES', ZoneFS__r.Name , 
'DC REGIONAL', ZoneRADU__r.Name , 
'DCIO', ZoneRADU__r.Name , 
'DCIO SUB ADV', ZoneRADU__r.Name , 
'No Zone')</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Zone Aggregated</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Affiliate</fullName>
        <active>true</active>
        <label>Affiliate</label>
    </recordTypes>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>ProductStrategyMutualFund__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product/Strategy or Mutual Fund related to the RFI/RFP</description>
        <inlineHelpText>Product/Strategy or Mutual Fund related to the RFI/RFP</inlineHelpText>
        <label>Product/Strategy/Mutual Fund</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Artemus.Request.requestor_id
varchar(100)</description>
        <label>Requester</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Requestor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RunCaseAssignmentRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, the case assignment rules will run upon save.</description>
        <label>Run Case Assignment Rules</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RunCaseSharing__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If checked, runs apex case sharing upon save.  Used primarily for realignments.  This should be default of checked.  Apex handles the sharing of cases based on record type, user, etc.and will not share cases that shouldn't be shared.</description>
        <label>Run Case Sharing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <description>Artemus.Request.territory
varchar(255)</description>
        <label>Territory</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel><enableHistory>true</enableHistory>
    <recordTypes>
        <fullName>RFP</fullName>
        <active>true</active>
        <businessProcess>IPM Standard</businessProcess>
        <description>Used for Request for Proposal (RFP) requests for IPM</description>
        <label>RFP</label>
    </recordTypes>
</CustomObject>

objects/NGAMSettings__c.object
<CustomObject>
    <fields>
        <fullName>ProfileIntegration__c</fullName>
        <description>Indicates the profile that should be used for Integration User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</description>
        <inlineHelpText>Indicates the profile that should be used for Integration User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</inlineHelpText>
        <label>Profile: Integration</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProfileSystemAdministrator__c</fullName>
        <description>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</description>
        <inlineHelpText>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</inlineHelpText>
        <label>Profile: System Administrator</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Holds the NGAM settings</description>
    <label>NGAM Settings</label>
</CustomObject>

objects/NGAMSettingsHierarchy__c.object
<CustomObject>
    <fields>
        <fullName>ByPassAccountValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows entity to by-pass validation rules on Account</description>
        <inlineHelpText>Allows entity to by-pass validation rules on Account</inlineHelpText>
        <label>By-Pass Account Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NGAM Settings - Hierarchy</label>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>MARSAffiliate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Affiliate as integrated from MARS; found by looking up Fund Company on Account</description>
        <label>MARS Affiliate</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products (MARS Affiliate)</relationshipLabel>
        <relationshipName>MARSAffiliateProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>GroupId__c</fullName>
        <externalId>true</externalId>
        <label>Group Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ParentTerritory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Territories</relationshipLabel>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RoleGroupId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Role Group Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RoleId__c</fullName>
        <externalId>true</externalId>
        <label>Role Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TerritoryName__c</fullName>
        <defaultValue>"Update Me"</defaultValue>
        <externalId>true</externalId>
        <label>MARS Territory Name</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TerritoryType__c</fullName>
        <label>Territory Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Territory</fullName>
                </value>
                <value>
                    <fullName>Region</fullName>
                </value>
                <value>
                    <fullName>Department</fullName>
                </value>
                <value>
                    <fullName>Division</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>PrimaryTerritory__c</fullName>
        <label>Primary Territory</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserID__c</fullName>
        <defaultValue>"Populate This Field"</defaultValue>
        <externalId>true</externalId>
        <label>UserID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/UserTerritory__c.object
<CustomObject>
    <fields>
        <fullName>ActivityTerritory__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activity Territory</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PrimaryTerritory__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Territory</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RoleId__c</fullName>
        <formula>Territory__r.RoleId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Role Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TerritoryName__c</fullName>
        <formula>Territory__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Territory Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TerritoryType__c</fullName>
        <formula>TEXT(Territory__r.TerritoryType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Territory Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>User Territories</relationshipLabel>
        <relationshipName>User_Territories1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Territories1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zoning__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Zone</label>
        <referenceTo>Zone__c</referenceTo>
        <relationshipLabel>User Territories</relationshipLabel>
        <relationshipName>User_Territories</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>User Territory</label>
    <nameField>
        <displayFormat>UT-{00000000}</displayFormat>
        <label>User Territory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Zone__c.object
<CustomObject>
    <fields>
        <fullName>Zone__c</fullName>
        <externalId>true</externalId>
        <label>Zone</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CaseTriggerHandler_Test.cls
@isTest

private class CaseTriggerHandler_Test {
    static testMethod void CaseTriggerHandlerValidateAll() {

        NGAMSettingsHierarchy__c hsettings = NGAMSettingsHierarchy__c.getOrgDefaults();
        hsettings.ByPassAccountValidationRules__c  = TRUE;
        upsert hsettings NGAMSettingsHierarchy__c.Id;

        Id affRequestRecTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Affiliate Request').getRecordTypeId();
        Id IPMRFPRecTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('RFP').getRecordTypeId();
        Id AffiliateRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Affiliate').getRecordTypeId();
        Id PWPRecTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Private Wealth Portal').getRecordTypeId();

        
        DataFactory.CreateNGAMCustomSettings(); 
        NGAMSettings__c ngamSettings = [select id, 
                                        ProfileIntegration__c, 
                                        ProfileSystemAdministrator__c from NGAMSettings__c limit 1]; 

        List<Case> caseList = new List<case>();
        //Profile p = [select id from profile where name='System Administrator']; 
        //Profile pSales = [select id from profile where name='NGAM Integration']; 
        string sysAdminId = Util.getCustomSettingProfileId(ngamSettings.ProfileSystemAdministrator__c); 
        string pSales = Util.getCustomSettingProfileId(ngamSettings.ProfileIntegration__c);
        
        User u = new User(alias = 'standt', email='SFDCadmin@ngam.natixis.com', 
                          emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
                          localesidkey='en_US', profileid = sysAdminId, 
                          timezonesidkey='America/Los_Angeles', username='SFDCadmin@ngam.natixis.com',UserID__c='SFDCadmin');
        //insert u;
        System.runAs(u){
            User u0 = new User(alias = 's0', email='Sales0@ngam.natixis.com', 
                               emailencodingkey='UTF-8', lastname='Testing0', languagelocalekey='en_US', 
                               localesidkey='en_US', profileid = sysAdminId, 
                               timezonesidkey='America/Los_Angeles', username='Sales0@ngam.natixis.com',UserID__c='Sales0');    
            
            insert u0;                   
            
            //Creating the Territory
            Territory__c Region = new Territory__c(Name='1-Region',TerritoryName__c='Region',RoleID__c = '',GroupID__c = '',TerritoryType__c = 'Region'); 
            insert Region;        
            Territory__c Terr = new Territory__c(Name='2-Territory',TerritoryName__c='Territory',RoleID__c = '',GroupID__c = '', TerritoryType__c = 'Territory', ParentTerritory__c = Region.Id); 
            insert Terr;        
            
            // Creating the Corresponding Role
            List<UserRole> Ur = new List<UserRole>(); 
            
            Ur.add(new UserRole(Name = Terr.Name, 
                                DeveloperName = Terr.Id, 
                                CaseAccessForAccountOwner = 'Read', 
                                OpportunityAccessForAccountOwner = 'Read',
                                ContactAccessForAccountOwner = 'Read'));
            
            Ur.add(new UserRole(Name = Region.Name, 
                                DeveloperName = Region.Id, 
                                CaseAccessForAccountOwner = 'Read', 
                                OpportunityAccessForAccountOwner = 'Read',
                                ContactAccessForAccountOwner = 'Read'));
            insert Ur;   
            
            List<Group> urGroup = [SELECT Id FROM Group WHERE RelatedId in : Ur ORDER BY Name];
            
            // Creating the Corresponding Group
            List<Group> Gr = new List<Group>();
            Gr.add(new Group(Name = Terr.Name,DeveloperName = Terr.Id,Type = 'Regular'));
            Gr.add(new Group(Name = Region.Name,DeveloperName = Region.Id,Type = 'Regular'));
            insert Gr;     

            List<Territory__Share> TsR = new List<Territory__Share>();            
            TsR.add(new Territory__Share(AccessLevel='Read',UserOrGroupId=urGroup[1].id,ParentId=terr.id));
            TsR.add(new Territory__Share(AccessLevel='Read',UserOrGroupId=urGroup[0].id,ParentId=terr.id));
            insert TsR;      
            
            //Territory__c uTerr = new Territory__c(id=Terr.id,RoleID__c = ur.id,GroupID__c = gr.id ); 
            Terr.RoleID__c = ur[0].id;
            Terr.RoleGroupId__c = urGroup[1].id;
            Terr.GroupID__c = gr[0].id;    
            update Terr;
            
            Region.RoleID__c = ur[1].id;
            Region.RoleGroupId__c = urGroup[0].id;
            Region.GroupID__c = gr[1].id;    
            update Region;

            List<zone__c> AllZones = DataFactory.createAllZones();
            
            UserTerritory__c ut0 = new  UserTerritory__c(user__c=u0.id, territory__c=Region.Id, PrimaryTerritory__c=true, ActivityTerritory__c=true,  Zoning__c=AllZones.get(0).id);  
            insert ut0; 
            
            system.debug ('u0.UserRoleId' + u0.UserRoleId);
            Account a = new Account(Name = 'TestAccount');
            insert a;   
            
            List<Account> affiliates = DataFactory.createTestFirms(1);
            affiliates[0].RecordTypeId = AffiliateRecTypeId;
            insert affiliates;
            
            List<Product2> products = DataFactory.createProduct2(1, 'Test');
            products[0].MARSAffiliate__c = affiliates[0].Id;
            insert products;

            
            List<Case> cases = new List<Case>();
            cases.add(new Case(RecordTypeId = affRequestRecTypeId,ownerid= u0.id, AccountId = a.Id, Requestor__c = u0.id, RunCaseSharing__c = TRUE, RunCaseAssignmentRules__c = TRUE));
            cases.add(new Case(RecordTypeId = IPMRFPRecTypeId,ownerid= u0.id, AccountId = a.Id, ProductStrategyMutualFund__c = products[0].Id, Requestor__c = u0.id, RunCaseSharing__c = TRUE, RunCaseAssignmentRules__c = TRUE));
            cases.add(new Case(RecordTypeId = PWPRecTypeId, AccountId = a.Id, Type = 'Account Opening'));
            insert cases;
            caseList.addAll(cases);
            Caseshare cs2 = new caseshare(caseid = cases[0].id, UserOrGroupId = Gr[1].id,  CaseAccessLevel= 'Edit');
            insert cs2;
            
            //CaseTriggerHandler.CaseTriggerAfterInsert(caseList);
            
        }         
    }
    
    /*static testMethod void CaseTriggerHandlerValidateAll2() {
        List<Case> caseList = new List<case>();
        set<id> caseIds = new set<id>();
        Case cs;
        DataFactory.CreateNGAMCustomSettings(); 
        NGAMSettings__c ngamSettings = [select id, 
                                        ProfileIntegration__c, 
                                        ProfileSystemAdministrator__c from NGAMSettings__c limit 1]; 

        string sysAdminId = Util.getCustomSettingProfileId(ngamSettings.ProfileSystemAdministrator__c); 
        string pSales = Util.getCustomSettingProfileId(ngamSettings.ProfileIntegration__c);

        User u = new User(alias = 'standt', email='SFDCadmin@ngam.natixis.com', 
                          emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
                          localesidkey='en_US', profileid = p, 
                          timezonesidkey='America/Los_Angeles', username='SFDCadmin@ngam.natixis.com',UserID__c='SFDCadmin');
        //insert u;
        System.runAs(u) 
        {
            User u0 = new User(alias = 's0', email='Sales0@ngam.natixis.com', 
                               emailencodingkey='UTF-8', lastname='Testing0', languagelocalekey='en_US', 
                               localesidkey='en_US', profileid = p, 
                               timezonesidkey='America/Los_Angeles', username='Sales0@ngam.natixis.com',UserID__c='Sales0');    
            
            insert u0;
            
            system.debug('u0======'+u0);
            
            User u2 = new User(alias = 's02', email='Sales02@ngam.natixis.com', 
                               emailencodingkey='UTF-8', lastname='Testing02', languagelocalekey='en_US', 
                               localesidkey='en_US', profileid = pSales, 
                               timezonesidkey='America/Los_Angeles', username='Sales02@ngam.natixis.com',UserID__c='Sales02');    
            
            insert u2;                
            
            //Creating the Territory
            Territory__c Terr = new Territory__c(Name='Test',TerritoryName__c='Test',RoleID__c = '',GroupID__c = ''); 
            insert Terr;                     
            
            // Creating the Corresponding Role
            UserRole Ur = new UserRole();
            Ur.Name = Terr.Name;
            Ur.DeveloperName = Terr.Id;
            Ur.CaseAccessForAccountOwner = 'Read';
            Ur.OpportunityAccessForAccountOwner = 'Read';
            Ur.ContactAccessForAccountOwner = 'Read';
            insert Ur;   
            
            Group urGroup=[select id from group where RelatedId =:ur.id][0];
            
            // Creating the Corresponding Group
            Group Gr = new Group();
            Gr.name = Terr.Name;
            Gr.DeveloperName = Terr.Id;
            Gr.Type = 'Regular';
            insert Gr;     
            
            Territory__Share TsR = new  Territory__Share(AccessLevel='Read',UserOrGroupId=urGroup.id,ParentId=terr.id );    
            insert TsR;      
            
            //Territory__c uTerr = new Territory__c(id=Terr.id,RoleID__c = ur.id,GroupID__c = gr.id ); 
            Terr.RoleID__c = ur.id;
            Terr.RoleGroupId__c = urGroup.id;
            Terr.GroupID__c = gr.id;    
            update Terr;
            
            List<zone__c> AllZones = DataFactory.createAllZones();
            
            UserTerritory__c ut0 = new  UserTerritory__c(user__c=u0.id, territory__c=Terr.Id, PrimaryTerritory__c=true, ActivityTerritory__c=true,  Zoning__c=AllZones.get(0).id);  
            
            insert ut0; 
            
            Map<String,Schema.RecordTypeInfo> RecordTypesByName = Case.SObjectType.getDescribe().getRecordTypeInfosByName();
            
            Account a = new Account(Name = 'TestAccount');
            insert a;
            System.debug('Account Id:  '+a.Id);
            id rtypeid = [Select id, developername, sobjecttype from recordtype where sobjecttype = 'Case' and IsActive = TRUE LIMIT 1].id;                       
            
            system.debug ('rtypeid========' +rtypeid);
            system.debug ('rtypeid========' +rtypeid);
            system.debug ('u0========' +u0);
            system.debug ('u2========' +u2);
            Case Case1 = new Case(ownerid= u0.id,recordtypeid =rtypeid, Requestor__c = u0.id, AccountId = a.Id) ;
            
            insert Case1; 
            
            system.debug('Hello::::'+Case1.Id);
            List<case> csrec = [Select id,recordtype.DeveloperName, Requestor__c, AccountId from case where id =: Case1.id];
            
            system.debug('Hello1');
            system.debug('csrec size: '+csrec.size());
            system.debug('csrec[0]::::::'+csrec[0]);
            
            Caseshare cs2 = new caseshare(caseid = csrec[0].id, UserOrGroupId = Gr.id,  CaseAccessLevel= 'Edit');
            insert cs2;
            csrec[0].ownerid = u2.id;
            
            Update csrec[0];
            caseList.add(csrec[0]); 
            System.debug('caseList size:'+caseList.size());
            System.debug('csrec::::::'+csrec[0]);
            CaseTriggerHandler.CaseTriggerAfterUpdate(caseList); 
            
        }
        
    }*/
    
}