objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>The MARS status of the account, Data Flow: Mars -&gt; SF</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>YTDNumberOfMeetings__c</fullName>
        <description>YTD count of activities with Type = Meeting Group &amp; Meeting One on One based on the Activity Contact table. Populated by a declarative lookup</description>
        <label>YTD Number of Meetings</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>YTDNumberofCalls__c</fullName>
        <description>YTD count of activities with Type = Call – Informative &amp; Call – Substantive based on the Activity Contact table</description>
        <label>YTD Number of Calls</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ActivityContact__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Activity Contacts</relationshipLabel>
        <relationshipName>Activity_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ActivityContact__c</fullName>
        <description>This Field is populated by the trigger and contains ActivityId__c + Contact__c, it is used to ensure that no duplicate contact on an activity (does not allow duplicate)</description>
        <label>ActivityContact</label>
        <length>37</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is entered through the Gridbuddy Form and is set to the id of the contact entered through the form. It is used by the trigger to create the TaskRelation entry to the related Task</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Activity Contacts</relationshipLabel>
        <relationshipName>ActivityContacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Count__c</fullName>
        <description>This field is meant to be used in reports, just a formula field that defaults to 1</description>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>This is populated by the trigger with Task.ActivityDate</description>
        <label>Activity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <description>Each activity will have 1 to Many contacts. These activity related contacts are stored in this object along necessary attributes to allow for advanced activity reporting. This Table is synched up with the TaskRelation standard object through the "ActivityContactTrigger" trigger and the "ActivityContactTriggerHandler" Class.
This object is "virtually" related to Task through the use of the "ActivityId__c" field. This fake Id field is binded to Task through the use of the "Contacts" Grid build in the GridBuddy application.</description>
    <label>Activity Contact</label>
    <nameField>
        <displayFormat>AC-{0000000000}</displayFormat>
        <label>Activity Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Contacts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Source: MARS na_load_rep.StatCd
Loaded by a nightly job.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>YTDNumberOfCalls__c</fullName>
        <description>This number is populated by this DLRS :https://globalplatform.my.salesforce.com/a0mF000000Agn0h based on the Activity Contact table. (type__c like 'Call%' and Date__c = THIS_YEAR and status__c='completed')</description>
        <label>YTD Number of Calls</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>YTDNumberOfMeetings__c</fullName>
        <description>Number of Meeting – Group &amp; Meeting - One on One activities based on the Activity Contact table. This number is populated by this DLRS : https://globalplatform.my.salesforce.com/a0mF000000Agn0i  based on the Activity Contact table. (type__c like 'Meeting%' and Date__c = THIS_YEAR and status__c='completed')</description>
        <label>YTD Number of Meetings</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/NGAMSettings__c.object
<CustomObject>
    <fields>
        <fullName>ActivityContactRollupBatchFromDate__c</fullName>
        <description>Used by ActivityContactRollupBatch as the starting date for AC roll up.  Can be set to any date within last 30 days, but must be before Activity Contact Rollup Batch To Date.  Value normally maintained automatically by batch.</description>
        <inlineHelpText>Used by ActivityContactRollupBatch as the starting date for AC roll up.  Can be set to any date within last 30 days, but must be before Activity Contact Rollup Batch To Date.  Value normally maintained automatically by batch.</inlineHelpText>
        <label>Activity Contact Rollup Batch From Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>FailureNotificationEmailAddress__c</fullName>
        <description>Used in apex to notify via email when processes fail. Separate multiple email addresses with semi-colons.</description>
        <inlineHelpText>Used in apex to notify via email when processes fail. Separate multiple email addresses with semi-colons.</inlineHelpText>
        <label>Failure Notification Email Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Holds the NGAM settings</description>
    <label>NGAM Settings</label>
</CustomObject>

objects/NGAMSettingsHierarchy__c.object
<CustomObject>
    <fields>
        <fullName>ByPassAccountValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows entity to by-pass validation rules on Account</description>
        <inlineHelpText>Allows entity to by-pass validation rules on Account</inlineHelpText>
        <label>By-Pass Account Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NGAM Settings - Hierarchy</label>
</CustomObject>

classes/ActivityContactRollupBatch_Test.cls
@isTest 
public class ActivityContactRollupBatch_Test {
    static testMethod void ActivityContactRollupBatchTesting() {
        
        NGAMSettingsHierarchy__c settings = NGAMSettingsHierarchy__c.getOrgDefaults();
        settings.ByPassAccountValidationRules__c  = TRUE;
        upsert settings NGAMSettingsHierarchy__c.Id;        
        
        NGAMSettings__c NS = new NGAMSettings__c(Name='test1'); 
        NS.ActivityContactRollupBatchFromDate__c = system.today();
        NS.FailureNotificationEmailAddress__c = 'dat@natixis.com';
        insert NS; 
        
        List<dlrs__LookupRollupSummary__c> lrs = new List<dlrs__LookupRollupSummary__c>();
        
        lrs.add(new dlrs__LookupRollupSummary__c(dlrs__Active__c = TRUE, dlrs__AggregateOperation__c = 'Count', dlrs__aggregateresultfield__c = 'YTDNumberOfMeetings__c',
                                                 dlrs__calculationmode__c = 'Developer', dlrs__childobject__c = 'ActivityContact__c', dlrs__fieldtoaggregate__c = 'Count__c',
                                                 dlrs__parentobject__c = 'Account',dlrs__relationshipcriteria__c = 'type__c like \'Meeting%\' and Date__c = THIS_QUARTER and status__c=\'completed\'',
                                                 dlrs__relationshipcriteriafields__c = 'Type__c\r\nDate__c\r\nStatus__c', dlrs__relationshipfield__c = 'Account__c', name = 'AccQTDNumberOfMeetings'));
        
        lrs.add(new dlrs__LookupRollupSummary__c(dlrs__Active__c = TRUE, dlrs__AggregateOperation__c = 'Count', dlrs__aggregateresultfield__c = 'YTDNumberOfCalls__c',
                                                 dlrs__calculationmode__c = 'Developer', dlrs__childobject__c = 'ActivityContact__c', dlrs__fieldtoaggregate__c = 'Count__c',
                                                 dlrs__parentobject__c = 'Account',dlrs__relationshipcriteria__c = 'type__c like \'Call%\' and Date__c = THIS_QUARTER and status__c=\'completed\'',
                                                 dlrs__relationshipcriteriafields__c = 'Type__c\r\nDate__c\r\nStatus__c', dlrs__relationshipfield__c = 'Account__c', name = 'AccQTDNumberOfCalls'));
        
        lrs.add(new dlrs__LookupRollupSummary__c(dlrs__Active__c = TRUE, dlrs__AggregateOperation__c = 'Count', dlrs__aggregateresultfield__c = 'YTDNumberOfMeetings__c',
                                                 dlrs__calculationmode__c = 'Developer', dlrs__childobject__c = 'ActivityContact__c', dlrs__fieldtoaggregate__c = 'Count__c',
                                                 dlrs__parentobject__c = 'Contact',dlrs__relationshipcriteria__c = 'type__c like \'Meeting%\' and Date__c = THIS_YEAR and status__c=\'completed\'',
                                                 dlrs__relationshipcriteriafields__c = 'Type__c\r\nDate__c\r\nStatus__c', dlrs__relationshipfield__c = 'Contact__c', name = 'RepYTDNumberOfMeetings'));
        
        lrs.add(new dlrs__LookupRollupSummary__c(dlrs__Active__c = TRUE, dlrs__AggregateOperation__c = 'Count', dlrs__aggregateresultfield__c = 'YTDNumberOfCalls__c',
                                                 dlrs__calculationmode__c = 'Developer', dlrs__childobject__c = 'ActivityContact__c', dlrs__fieldtoaggregate__c = 'Count__c',
                                                 dlrs__parentobject__c = 'Contact',dlrs__relationshipcriteria__c = 'type__c like \'Call%\' and Date__c = THIS_YEAR and status__c=\'completed\'',
                                                 dlrs__relationshipcriteriafields__c = 'Type__c\r\nDate__c\r\nStatus__c', dlrs__relationshipfield__c = 'Contact__c', name = 'RepNumberOfCallsThisYear'));
        
        insert lrs;
        
        List<Account> myAccounts = DataFactory.createTestAccounts(3);
        insert myAccounts;
        
        List<Contact> myTaskContacts = DataFactory.createTestContacts(3, myAccounts, false);
        insert myTaskContacts;     
        
        List<Task> myTasks = DataFactory.createTestTasks(3,myTaskContacts,'Test Task'); 
        myTasks[0].Type = 'Meeting';
        myTasks[0].Status = 'Complete';
        myTasks[1].Type = 'Call';
        myTasks[1].Status = 'Complete';        
        insert myTasks;
        
        List<Contact> myACContacts = DataFactory.createTestContacts(15, myAccounts, false);
        insert myACContacts;

        List<ActivityContact__c> myActivityContacts = DataFactory.createActivityContacts(myTasks,myACContacts);
        insert myActivityContacts;

        delete myTasks[2];
        
        Test.startTest();    
        ActivityContactRollupBatch batch = new ActivityContactRollupBatch();
        ID tracid = database.executeBatch(batch,10000); 
        Test.stopTest();
                
    }
}