objects/Account.object
<CustomObject>
    <fields>
        <fullName>CommentsModified__c</fullName>
        <description>Updated by Apex when a user updates the Comments field (sets who modified comments).</description>
        <label>Comments Modified By</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CommentsModified__c</fullName>
        <inlineHelpText>Custom field to capture who last updated the description field</inlineHelpText>
        <label>Description Modified By</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PrimaryContact__c</fullName>
        <description>Fiduciary Services requested this field and the requirements are in SAL-169</description>
        <formula>IF (   Account.PrimaryOfficeContact__r.Id = Id , True, False)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Flag the main Contact that is called or emailed at the related Office.</inlineHelpText>
        <label>Primary Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RoleMultiSelect__c</fullName>
        <description>N/A No longer used.</description>
        <label>OLDRole</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Advisor/Consultant</fullName>
                </value>
                <value>
                    <fullName>Analyst/Investment Staff</fullName>
                </value>
                <value>
                    <fullName>Analyst - Alternatives</fullName>
                </value>
                <value>
                    <fullName>Analyst - Balanced</fullName>
                </value>
                <value>
                    <fullName>Analyst - Equity</fullName>
                </value>
                <value>
                    <fullName>Analyst - Fixed Income</fullName>
                </value>
                <value>
                    <fullName>Analyst - Fixed Income-Money Market</fullName>
                </value>
                <value>
                    <fullName>Analyst - Fixed Income-Municipal</fullName>
                </value>
                <value>
                    <fullName>Analyst - Fixed Income-Taxable</fullName>
                </value>
                <value>
                    <fullName>Analyst - Multi Asset</fullName>
                </value>
                <value>
                    <fullName>Client Portfolio Manager</fullName>
                </value>
                <value>
                    <fullName>Investment Committee/Board Member</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Natixis ISG Strategist</fullName>
                </value>
                <value>
                    <fullName>Portfolio Manager</fullName>
                </value>
                <value>
                    <fullName>Product/Operations</fullName>
                </value>
                <value>
                    <fullName>Product Manager</fullName>
                </value>
                <value>
                    <fullName>Product Specialist</fullName>
                </value>
                <value>
                    <fullName>Sales/Field Consultant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ContactExtension.cls
public class ContactExtension {
    private final Account acct;
    
    public ContactExtension(ApexPages.StandardController stdController) {
        this.acct = (Account)stdController.getRecord();
    }

    public List<Contact> getContacts() {       
    	List<Contact> ceList = [SELECT PrimaryContact__c, Name, Phone, Email, RoleMultiSelect__c, 
                            		CommentsModified__c 
                            		FROM Contact 
                                    where Account.Id =: acct.Id limit 5];
        return ceList;
     }
}