objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>The MARS status of the account, Data Flow: Mars -&gt; SF</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Firm</fullName>
        <active>true</active>
        <description>Firms, offices, and reps are organized into a hierarchy. This means that each rep must be assigned to an office, and each office must be assigned to a firm. Firm is the highest level in the hierarchy.</description>
        <label>Firm</label>
    </recordTypes>
</CustomObject>

objects/AdditionalInfo__c.object
<CustomObject>
    <description>Tracks additional information for CDR Qualitative Data</description>
    <label>Additional Info</label>
    <nameField>
        <label>Additional Info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional Info</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CDRQualitativeData__c.object
<CustomObject>
    <fields>
        <fullName>AdditionalInfo__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Additional Info</label>
        <referenceTo>AdditionalInfo__c</referenceTo>
        <relationshipLabel>CDR Qualitative Data (Additional Info)</relationshipLabel>
        <relationshipName>CDRQualitativeData</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EffectiveDate__c</fullName>
        <defaultValue>NOW()+30</defaultValue>
        <label>Effective Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SortOrder__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Staging</fullName>
                </value>
                <value>
                    <fullName>Pending Activation</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Historical</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>This object stores qualitative data about contacts, firms, products, additional information and their relationships to one another.</description>
    <label>CDR Qualitative Data</label>
    <nameField>
        <label>CDR Qualitative Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CDR Qualitative Data</pluralLabel>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Benchmark</fullName>
        <active>true</active>
        <description>Use this for Benchmark CDR Qualitative Data</description>
        <label>Benchmark</label>
    </recordTypes>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Use this for Contact CDR Qualitative Data</description>
        <label>Contact</label>
    </recordTypes>
    <recordTypes>
        <fullName>ETF</fullName>
        <active>true</active>
        <description>Use this for ETFs</description>
        <label>ETF</label>
    </recordTypes>
    <recordTypes>
        <fullName>Firm</fullName>
        <active>true</active>
        <description>Use this for Firm CDR Qualitative Data</description>
        <label>Firm</label>
    </recordTypes>
</CustomObject>

objects/CDRSettings__c.object
<CustomObject>
    <fields>
        <fullName>OverrideTriggerValidations__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Overrides trigger validations on status changes, effective dates, etc. when editing or creating CDR Qualitative Data records</description>
        <inlineHelpText>Overrides trigger validations on status changes, effective dates, etc. when editing or creating CDR Qualitative Data records</inlineHelpText>
        <label>Override Trigger Validations</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Settings that control CDR processes</description>
    <label>CDR Settings</label>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Source: MARS na_load_rep.StatCd
Loaded by a nightly job.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/NGAMSettingsHierarchy__c.object
<CustomObject>
    <fields>
        <fullName>ByPassAccountValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows entity to by-pass validation rules on Account</description>
        <inlineHelpText>Allows entity to by-pass validation rules on Account</inlineHelpText>
        <label>By-Pass Account Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NGAM Settings - Hierarchy</label>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACTIVE</fullName>
                </value>
                <value>
                    <fullName>CLOSED TO NEW INVESTORS</fullName>
                </value>
                <value>
                    <fullName>INACTIVE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Benchmark</fullName>
        <active>true</active>
        <description>Use this for Benchmarks</description>
        <label>Benchmark</label>
    </recordTypes>
    <recordTypes>
        <fullName>ETF</fullName>
        <active>true</active>
        <description>Use this for ETFs</description>
        <label>ETF</label>
    </recordTypes>
</CustomObject>

classes/CDRQualitativeDataSummaryExtTest.cls
@isTest
public class CDRQualitativeDataSummaryExtTest {
    
    @testSetup
    static void testSetup() {
    
        NGAMSettingsHierarchy__c hsettings = NGAMSettingsHierarchy__c.getOrgDefaults();
        hsettings.ByPassAccountValidationRules__c  = TRUE;
        upsert hsettings NGAMSettingsHierarchy__c.Id;

        
        CDRSettings__c settings = new CDRSettings__c(Name = 'NGAM', 
                                                     OverrideTriggerValidations__c = TRUE);
        insert settings;
        
        Id nullId;
        
        List<Product2> products = DataFactory.createProduct2(4,'CDR Test');
        products[0].Name = 'Mutual Fund';
        products[1].Name = 'Share Class';
        products[2].Name = 'Benchmark';
        products[3].Name = 'ETF';
        insert products;
        
        List<Account> firms = DataFactory.createTestFirms(1);
        insert firms;
        
        List<Account> accounts = DataFactory.createTestAccountswithFirms(2,firms);
        insert accounts;
        
        List<Contact> contacts = DataFactory.createTestContacts(1,accounts,FALSE);
        insert contacts;
        
        List<AdditionalInfo__c> addlInfos = new List<AdditionalInfo__c>();
        AdditionalInfo__c addlInfo = new AdditionalInfo__c(Name='Test Addl Info');
        addlInfos.add(addlInfo);
        insert addlInfos;
        
        List<CDRQualitativeData__c> CDRs = new List<CDRQualitativeData__c>();
        
        List<CDRQualitativeData__c> CDRMutualFunds = DataFactory.createCDRQualitativeData (1, 'Mutual Fund', products[0].Id, nullId);
        CDRMutualFunds[0].SortOrder__c = 10;
        CDRMutualFunds[0].EffectiveDate__c = datetime.newInstance(1977,1,1);
        CDRs.addAll(CDRMutualFunds);
        
        List<CDRQualitativeData__c> CDRAddlInfos = DataFactory.createCDRQualitativeData (1, 'Additional Info', addlInfos[0].Id, nullId);
        CDRAddlInfos[0].SortOrder__c = 20;
        CDRAddlInfos[0].EffectiveDate__c = datetime.newInstance(1977,1,1);
        CDRs.addAll(CDRAddlInfos);
        
        List<CDRQualitativeData__c> CDRAccounts = DataFactory.createCDRQualitativeData (1, 'Firm', accounts[0].Id, nullId);
        CDRAccounts[0].SortOrder__c = 30;
        CDRAccounts[0].EffectiveDate__c = datetime.newInstance(1977,1,1);
        CDRs.addAll(CDRAccounts);
        
        List<CDRQualitativeData__c> CDRFirmAdditionalInfos = DataFactory.createCDRQualitativeData (1, 'Firm-Additional Info', accounts[0].Id, addlInfos[0].Id);
        CDRFirmAdditionalInfos[0].SortOrder__c = 40;
        CDRFirmAdditionalInfos[0].EffectiveDate__c = datetime.newInstance(1977,1,1);
        CDRs.addAll(CDRFirmAdditionalInfos);
        
        List<CDRQualitativeData__c> CDRFirmContacts = DataFactory.createCDRQualitativeData (1, 'Firm-Contact', accounts[0].Id, contacts[0].Id);
        CDRFirmContacts[0].SortOrder__c = 50;
        CDRFirmContacts[0].EffectiveDate__c = datetime.newInstance(1977,1,1);
        CDRs.addAll(CDRFirmContacts);
        
        List<CDRQualitativeData__c> CDRFirmProducts = DataFactory.createCDRQualitativeData (1, 'Firm-Product', accounts[0].Id, products[0].Id);
        CDRFirmProducts[0].SortOrder__c = 60;
        CDRFirmProducts[0].EffectiveDate__c = datetime.newInstance(1977,1,1);
        CDRs.addAll(CDRFirmProducts);
        
        List<CDRQualitativeData__c> CDRBenchmarks = DataFactory.createCDRQualitativeData (1, 'Benchmark', products[2].Id, nullId);
        CDRBenchmarks[0].SortOrder__c = 70;
        CDRBenchmarks[0].EffectiveDate__c = datetime.newInstance(1977,1,1);
        CDRs.addAll(CDRBenchmarks);
        
        List<CDRQualitativeData__c> CDRContacts = DataFactory.createCDRQualitativeData (1, 'Contact', contacts[0].Id, nullId);
        CDRContacts[0].SortOrder__c = 80;
        CDRContacts[0].EffectiveDate__c = datetime.newInstance(1977,1,1);
        CDRs.addAll(CDRContacts);
        
        List<CDRQualitativeData__c> CDRContactAdditionalInfos = DataFactory.createCDRQualitativeData (1, 'Contact-Additional Info', contacts[0].Id, addlInfos[0].Id);
        CDRContactAdditionalInfos[0].SortOrder__c = 90;
        CDRContactAdditionalInfos[0].EffectiveDate__c = datetime.newInstance(1977,1,1);
        CDRs.addAll(CDRContactAdditionalInfos);
        
        List<CDRQualitativeData__c> CDRProductAdditionalInfos = DataFactory.createCDRQualitativeData (1, 'Product-Additional Info', products[0].Id, addlInfos[0].Id);
        CDRProductAdditionalInfos[0].SortOrder__c = 100;
        CDRProductAdditionalInfos[0].EffectiveDate__c = datetime.newInstance(1977,1,1);
        CDRs.addAll(CDRProductAdditionalInfos);
        
        List<CDRQualitativeData__c> CDRProductBenchmarks = DataFactory.createCDRQualitativeData (1, 'Product-Benchmark', products[0].Id, products[2].Id);
        CDRProductBenchmarks[0].SortOrder__c = 110;
        CDRProductBenchmarks[0].EffectiveDate__c = datetime.newInstance(1977,1,1);
        CDRs.addAll(CDRProductBenchmarks);
        
        List<CDRQualitativeData__c> CDRProductChildProducts = DataFactory.createCDRQualitativeData (1, 'Product-Child Product', products[0].Id, products[1].Id);
        CDRProductChildProducts[0].SortOrder__c = 120;
        CDRProductChildProducts[0].EffectiveDate__c = datetime.newInstance(1977,1,1);
        CDRs.addAll(CDRProductChildProducts);
        
        List<CDRQualitativeData__c> CDRProductContacts = DataFactory.createCDRQualitativeData (1, 'Product-Contact', products[0].Id, contacts[0].Id);
        CDRProductContacts[0].SortOrder__c = 130;
        CDRProductContacts[0].EffectiveDate__c = datetime.newInstance(1977,1,1);
        CDRs.addAll(CDRProductContacts);
        
        List<CDRQualitativeData__c> CDRShareClasses = DataFactory.createCDRQualitativeData (1, 'Share Class', products[1].Id, nullId);
        CDRShareClasses[0].SortOrder__c = 140;
        CDRShareClasses[0].EffectiveDate__c = datetime.newInstance(1977,1,1);
        CDRs.addAll(CDRShareClasses);
        
        List<CDRQualitativeData__c> CDRETFs = DataFactory.createCDRQualitativeData (1, 'ETF', products[3].Id, nullId);
        CDRETFs[0].SortOrder__c = 150;
        CDRETFs[0].EffectiveDate__c = datetime.newInstance(1977,1,1);
        CDRs.addAll(CDRETFs);
        
        List<CDRQualitativeData__c> CDRFirmChildFirms = DataFactory.createCDRQualitativeData (1, 'Firm-Child Firm', accounts[0].Id, accounts[1].Id);
        CDRFirmChildFirms[0].SortOrder__c = 160;
        CDRFirmChildFirms[0].EffectiveDate__c = datetime.newInstance(1977,1,1);
        
        CDRs.addAll(CDRFirmChildFirms);
        
        insert CDRs;
        
        List<CDRQualitativeData__c> cdrToUpdate = new List<CDRQualitativeData__c>();
        
        for (CDRQualitativeData__c c : CDRs) {
                c.Status__c = 'Active';
                cdrToUpdate.add(c);
        }
        
        update cdrToUpdate; 
        
    }
    
    static testMethod void myTests() {
        
        List<Product2> products = [SELECT Id, Name FROM Product2];
        List<Account> accounts = [SELECT Id, Name FROM Account];
        List<Contact> contacts = [SELECT Id, Name FROM Contact];
        List<AdditionalInfo__c> addlInfos = [SELECT Id, Name FROM AdditionalInfo__c];
        
        Test.setCurrentPage(Page.CDRQualitativeDataSummaryAccount);
        CDRQualitativeDataSummaryExt controller1 = new CDRQualitativeDataSummaryExt(new ApexPages.StandardController(products[0]));
        controller1.effdt = Datetime.newInstance(2017,11,6);
        controller1.dispStaging = TRUE;
        controller1.getQualitativeDataRecords();
    }
    
}