objects/ActivityContact__c.object
<CustomObject>
    <fields>
        <fullName>ActivityComments__c</fullName>
        <description>This is populated by the trigger as the first 255 characters of the Task.Description field</description>
        <label>Activity Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ActivityContact__c</fullName>
        <description>This Field is populated by the trigger and contains ActivityId__c + Contact__c, it is used to ensure that no duplicate contact on an activity (does not allow duplicate)</description>
        <label>ActivityContact</label>
        <length>37</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ActivityId__c</fullName>
        <description>This fake Id field is binded to Task through the use of the "Contacts" Grid build in the GridBuddy application. It is populated by GB with Task.Id</description>
        <externalId>true</externalId>
        <label>ActivityId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivitySubType__c</fullName>
        <description>The dependent field on Type IC to drive value visibility , Copied from Task object  in insert trigger.</description>
        <label>Activity Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ActivityType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Product/Promotional</fullName>
                </value>
                <value>
                    <fullName>Follow-Up/Service</fullName>
                </value>
                <value>
                    <fullName>Solutions</fullName>
                </value>
                <value>
                    <fullName>Roadshow</fullName>
                </value>
                <value>
                    <fullName>Other/Voicemail</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ActivityType__c</fullName>
        <description>Used to control the Sub Type field and not displayed in the UI. The out of box field Type is displayed in the UI.</description>
        <label>Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Meeting</fullName>
                </value>
                <value>
                    <fullName>Call</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is entered through the Gridbuddy Form and is set to the id of the contact entered through the form. It is used by the trigger to create the TaskRelation entry to the related Task</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Activity Contacts</relationshipLabel>
        <relationshipName>ActivityContacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <description>Each activity will have 1 to Many contacts. These activity related contacts are stored in this object along necessary attributes to allow for advanced activity reporting. This Table is synched up with the TaskRelation standard object through the "ActivityContactTrigger" trigger and the "ActivityContactTriggerHandler" Class.
This object is "virtually" related to Task through the use of the "ActivityId__c" field. This fake Id field is binded to Task through the use of the "Contacts" Grid build in the GridBuddy application.</description>
    <label>Activity Contact</label>
    <nameField>
        <displayFormat>AC-{0000000000}</displayFormat>
        <label>Activity Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Contacts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ActivityProduct__c.object
<CustomObject>
    <fields>
        <fullName>ActivityComments__c</fullName>
        <description>The shortened version of the Description from the parent Task</description>
        <label>Activity Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ActivityId__c</fullName>
        <externalId>true</externalId>
        <label>ActivityId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityProduct__c</fullName>
        <label>ActivityProduct</label>
        <length>37</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ActivitySubType__c</fullName>
        <label>Activity SubType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Affiliate Request</fullName>
                </value>
                <value>
                    <fullName>Product/Promotional</fullName>
                </value>
                <value>
                    <fullName>Follow-Up/Service</fullName>
                </value>
                <value>
                    <fullName>Solutions</fullName>
                </value>
                <value>
                    <fullName>Roadshow</fullName>
                </value>
                <value>
                    <fullName>Other/Voicemail</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ActivityType__c</fullName>
        <label>Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Call</fullName>
                </value>
                <value>
                    <fullName>Meeting</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Activity Product</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Activity Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>FirstEventStartDatetime__c</fullName>
        <description>Set by trigger to be the first start date time of the all events associated with the case.</description>
        <inlineHelpText>The first start datetime of the any events associated with the case</inlineHelpText>
        <label>First Event Start Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LastEventEndDatetime__c</fullName>
        <description>Set by trigger to be the last end date time of the all events associated with the case.  Used by time-based workflow to automatically close the case after the last even has occurred.</description>
        <inlineHelpText>The last end datetime of the any events associated with the case</inlineHelpText>
        <label>Last Event End Datetime</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Private</sharingModel><enableHistory>true</enableHistory>
</CustomObject>

objects/Contact.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Affiliate</fullName>
        <active>true</active>
        <label>Affiliate</label>
    </recordTypes>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ActivityChannelName__c</fullName>
        <description>Used To Tag the Activities and Opportunities created by the user.</description>
        <inlineHelpText>READ ONLY FIELD : This Will be populated by the UserTerritory__c assignment when the Territory Assignment is tagged as an Activity Territory. Please never update this field directly. Instead Delete/Insert the relevant UserTerritory__c record.</inlineHelpText>
        <label>Activity Channel Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryId__c</fullName>
        <description>Used To Tag the Activities and Opportunities created by the user.</description>
        <externalId>true</externalId>
        <inlineHelpText>READ ONLY FIELD : This Will be populated by the UserTerritory__c assignment when the Territory Assignment is tagged as an Activity Territory. Please never update this field directly. Instead Delete/Insert the relevant UserTerritory__c record.</inlineHelpText>
        <label>Activity Territory Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryMARSName__c</fullName>
        <description>The MARS Name of the Activity Territory (Territory__c.TerritoryName__c)</description>
        <label>Activity Territory MARS Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryName__c</fullName>
        <description>Used To Tag the Activities and Opportunities created by the user.</description>
        <inlineHelpText>READ ONLY FIELD : This Will be populated by the UserTerritory__c assignment when the Territory Assignment is tagged as an Activity Territory. Please never update this field directly. Instead Delete/Insert the relevant UserTerritory__c record.</inlineHelpText>
        <label>Activity Territory Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryZoneName__c</fullName>
        <description>Activity Territory Zone Name is derived from the Activity Zone Id.</description>
        <formula>IF( ActivityZoneId__c = "a1bF0000003XUiWIAW", "All Zones", 
IF( ActivityZoneId__c = "a1bF0000003XRz5IAG", "MRD", 
IF( ActivityZoneId__c = "a1bF0000003XTBCIA4", "RD1", 
IF( ActivityZoneId__c = "a1bF0000003XTBRIA4", "RD2", 
IF( ActivityZoneId__c = "a1bF0000003XTBWIA4", "RD3", 
IF( ActivityZoneId__c = "a1bF0000003XTBgIAO", "IC", 
IF( ActivityZoneId__c = "a1b2A000005HHBpQAO", "IC1", 
IF( ActivityZoneId__c = "a1b2A000005HHBqQAO", "IC2", 
IF( ActivityZoneId__c = "a1b2A000005HHBrQAO", "IC3", 
IF( ActivityZoneId__c = "a1b2A000005HHBsQAO", "IC4", 
IF( ActivityZoneId__c = "a1b2A000005HHBtQAO", "RD1", 
IF( ActivityZoneId__c = "a1b2A000005HHBuQAO", "RD2", 
IF( ActivityZoneId__c = "a1b2A000005HHBvQAO", "DIR1", 
IF( ActivityZoneId__c = "a1b2A000005HHBwQAO", "DIR2", 
IF( ActivityZoneId__c = "a1b2A000005HHBxQAO", "DIR3", 
IF( ActivityZoneId__c = "a1b2A000005HHByQAO", "DIR4", 
IF( ActivityZoneId__c = "a1b2A000005HHBzQAO", "DIR5", 
IF( ActivityZoneId__c = "a1b2A000005HHC0QAO", "MRD1", 
IF( ActivityZoneId__c = "a1b2A000005HHC1QAO", "MRD2", 
IF( ActivityZoneId__c = "a1b2A000005HHC2QAO", "MRD3", 
IF( ActivityZoneId__c = "a1b2A000005HHC3QAO", "MRD4", 
IF( ActivityZoneId__c = "a1b2A000005HHC4QAO", "MRD5", 
IF( ActivityZoneId__c = "a1b2A000005HHC5QAO", "MRD6", 
IF( ActivityZoneId__c = "a1b2A0000070V1JQAU", "MRD7", 
IF( ActivityZoneId__c = "a1b2A0000070V1OQAU", "MRD8", 
IF( ActivityZoneId__c = "a1b2A0000070V1TQAU", "MRD9",
IF( ActivityZoneId__c = "a1b2A000005HHC6QAO", "MD", 
IF( ActivityZoneId__c = "a1bF00000053btoIAA", "Inbound", NULL ))))))))))))))))))))))))))))</formula>
        <label>Activity Territory Zone Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EventTriggerHandler.cls
public class EventTriggerHandler {

    public static String AffiliateRecordType = 'Affiliate Request';
    
    public static Map<Id,User> userMap = new Map<Id,User>([SELECT Id,ActivityTerritoryName__c, ActivityChannelName__c,ActivityTerritoryZoneName__c,
                                                           ActivityTerritoryMARSName__c, ActivityTerritoryId__c
                                                           FROM User
                                                           WHERE UserType = 'Standard']);
    
    public static Id affiliateRequestEventRecordTypeId = Schema.SObjectType.Event.getRecordTypeInfosByName().get('Affiliate Event').getRecordTypeId();
    
    public static void EventTriggerBeforeInsert(List<Event> myEvents, Map<Id,Event> eventNewMap){
        eventFieldsPreset(myEvents, eventNewMap);  
    }
    
    public static void EventTriggerAfterInsert(List<Event> myEvents){
        SetLastEventDatetime(myEvents);
    } 
    
    
    public static void EventTriggerBeforeUpdate(List<Event> myEvents, Map<Id,Event> eventNewMap, Map<Id,Event> eventOldMap){
        eventFieldsPreset(myEvents, eventNewMap); 
    } 
    
    
    public static void EventTriggerAfterUpdate(List<Event> myEvents, Map<Id,Event> eventNewMap, Map<Id,Event> eventOldMap){
        setLastEventDatetime(myEvents);
        syncActivityContacts(myEvents, eventNewMap, eventOldMap);        
    } 
    
    public static void EventTriggerAfterDelete(Map<Id,Event> oldEventMap) {

        SetLastEventDatetimeDelete(oldEventMap.values());
        delete [SELECT Id from ActivityContact__c WHERE ActivityId__c IN :oldEventMap.keySet()];
        //delete [SELECT Id from ActivityProduct__c WHERE ActivityId__c IN :oldEventMap.keySet()];
        
    }    

    public static void eventFieldsPreset(List<Event> myEvents, Map<Id,Event> eventMap){
        
        if (trigger.IsUpdate) myEvents = eventMap.values();
        
        Id pardotUserId;
        Map<Id,User> userMap = Util.getUserTerritoryMap();
        for (User u : userMap.values()) {
            if (u.Username.startsWith('pnatixis')) pardotUserId = u.Id;
        }
        
        Map<Id, ActivityContact__c> activityContactMap = new Map<Id, ActivityContact__c>();
        
        if (trigger.IsUpdate) activityContactMap = UtilActivity.getActivityContactMap(eventMap);

        Set<Id> contactIdSet = new Set<Id>();
        for (ActivityContact__c ac : activityContactMap.values()) {
            contactIdSet.add(ac.Contact__c);
        }
        Map<Id,Contact> contactMap = UtilActivity.getContactPrimaryTerritoryMap(contactIdSet);

        for (Event e : myEvents) {
            
            e = UtilActivity.setUserFields(e, userMap);
            e = UtilActivity.syncWhatIdToLookupFields(e);
            e.LastAssignedOwner__c = e.OwnerId;
            
            e.ActivityType__c = e.ActivityType__c == null ? e.Type : e.ActivityType__c;
            e.ActivityDateProxy__c = e.ActivityDate;
            e.ActivitySubType__c = 'Product/Promotional';
            e.ActivityComments__c = String.isBlank(e.Description) ? null : e.Description.left(255).trim();
            
            SWITCH ON e.Type {
                WHEN 'Meeting','WebEx' {
                    e.ActivityType__c = 'Meeting';
                }
                WHEN 'Call' {
                    e.ActivityType__c = 'Call';
                }
            }      
            
        }
        myEvents = UtilActivity.setActivityPoints(myEvents);
    }


    public static void setLastEventDatetime(List<Event> myEvents) {
        
        List<Case> casesToUpdate = new List<Case>();
        Set<Id> relatedCasesSet = new Set<Id>();
        for(Event eId : myEvents){
            if ('Case' == eId.WhatId.getSObjectType().getDescribe().getName()) relatedCasesSet.add(eId.WhatId);
        }
        
        if(!relatedCasesSet.isEmpty()){
            Map<string, Case> cMap = new Map<string, Case>();
            AggregateResult[] events = [select WhatId, Max(EndDateTime), MIN(StartDateTime) from Event where WhatId IN :relatedCasesSet GROUP BY WhatId];
            if(events.size()>0){
                for(AggregateResult e: events){
                    If (e.get('expr0')!=null && e.get('expr1') != null) {
                        cMap.put((string)e.get('WhatId'), new Case(Id=(string)e.get('WhatId'), LastEventEndDatetime__c=(datetime)e.get('expr0'), FirstEventStartDatetime__c=(datetime)e.get('expr1')));
                    } else {
                        cMap.put((string)e.get('WhatId'), new Case(Id=(string)e.get('WhatId'), LastEventEndDatetime__c=null,FirstEventStartDatetime__c=null));
                    }
                }
            }
            update(cMap.values());
        }  
        
    }
    
    public static void SetLastEventDatetimeDelete(List<Event> myEvents) {
        
        List<Case> casesToUpdate = new List<Case>();
        Set<Id> relatedCasesSet = new Set<Id>();
        for(Event eId : myEvents){
            if ('Case' == eId.WhatId.getSObjectType().getDescribe().getName()) relatedCasesSet.add(eId.WhatId);
        }
        
        if(!relatedCasesSet.isEmpty()){
            Map<string, Case> cMap = new Map<string, Case>();
            
            AggregateResult[] events = [select WhatId, Max(EndDateTime) from Event where WhatId IN :relatedCasesSet GROUP BY WhatId];
            if(events.size()>0){
                for(AggregateResult e: events){
                    If (e.get('expr0')!=null) {
                        cMap.put((string)e.get('WhatId'), new Case(Id=(string)e.get('WhatId'), LastEventEndDatetime__c=(datetime)e.get('expr0')));
                    } else {
                        cMap.put((string)e.get('WhatId'), new Case(Id=(string)e.get('WhatId'), LastEventEndDatetime__c=null));
                    }
                }
            }
            update(cMap.values());
        }  
    }
    
    public static void syncActivityContacts(List<Event> myNewEvents, Map<Id,Event> myNewEventMap, Map<Id,Event> myOldEventMap) {
        
        Map<Id, ActivityContact__c> activityContactMap = UtilActivity.getActivityContactMap(myNewEventMap);
        List<ActivityContact__c> activityContactToUpdate = new List<ActivityContact__c>();
                
        Map<String, List<ActivityContact__c>> activityContactToUpdateMap = new Map<String, List<ActivityContact__c>>();
        
        for (ActivityContact__c ac : activityContactMap.values()) {
            if (activityContactToUpdateMap.containsKey(ac.ActivityId__c)) {
                List<ActivityContact__c> tempAC = activityContactToUpdateMap.get(ac.ActivityId__c);
                tempAC.add(ac);
                activityContactToUpdateMap.put(ac.ActivityId__c, tempAC);
            } else {
                List<ActivityContact__c> tempAC = new List<ActivityContact__c>();
                tempAC.add(ac);
                activityContactToUpdateMap.put(ac.ActivityId__c, tempAC);
            }
        }
        
        for (Event e : myNewEvents) {
            
            if (activityContactToUpdateMap.containsKey(e.Id)) {
                List<ActivityContact__c> acList = activityContactToUpdateMap.get(e.Id);
                
                for (ActivityContact__c ac : acList) {
                    if (ac.ActivityId__c.startsWith('00U')) ac = UtilActivity.activityContactEventFieldPreset(ac, e);
                    activityContactToUpdate.add(ac);
                }
            }
        }
        
        update activityContactToUpdate;

    } 
    
  
    
}