objects/Activity.object
<CustomObject>
    <fields>
        <fullName>ActivityId__c</fullName>
        <formula>CaseSafeId( Id )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ActivityId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivitySource__c</fullName>
        <description>Captures the Source of the Activity</description>
        <label>Activity Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Artemus</fullName>
                </value>
                <value>
                    <fullName>BlackBerryCRM</fullName>
                </value>
                <value>
                    <fullName>Broadridge</fullName>
                </value>
                <value>
                    <fullName>Civicomm</fullName>
                </value>
                <value>
                    <fullName>FI360</fullName>
                </value>
                <value>
                    <fullName>GlobalConnect</fullName>
                </value>
                <value>
                    <fullName>GPS</fullName>
                </value>
                <value>
                    <fullName>Harte Hanks</fullName>
                </value>
                <value>
                    <fullName>Outlook Integration</fullName>
                </value>
                <value>
                    <fullName>Portfolio</fullName>
                </value>
                <value>
                    <fullName>User Created</fullName>
                </value>
                <value>
                    <fullName>Process CPE</fullName>
                </value>
                <value>
                    <fullName>Outlook Email Svc</fullName>
                </value>
                <value>
                    <fullName>Salesforce1</fullName>
                </value>
                <value>
                    <fullName>Seismic</fullName>
                </value>
                <value>
                    <fullName>Digital Campaign</fullName>
                </value>
                <value>
                    <fullName>Engage</fullName>
                </value>
                <value>
                    <fullName>Break Out</fullName>
                </value>
                <value>
                    <fullName>Small Conf. Follow Up</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OwnerChannelId__c</fullName>
        <formula>Owner:User.ActivityChannelId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Owner Channel Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OwnerChannel__c</fullName>
        <label>Owner Channel</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OwnerTerritoryId__c</fullName>
        <description>The owner's activity territory id at the time of activity creation</description>
        <label>Owner Territory Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OwnerTerritoryMARS__c</fullName>
        <description>The owner activity territory based on the MARS name at the time of activity creation</description>
        <label>Owner Territory MARS</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OwnerTerritory__c</fullName>
        <label>Owner Territory</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OwnerZoneFormula__c</fullName>
        <formula>Owner:User.ActivityZoneId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Owner Zone Formula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OwnerZone__c</fullName>
        <label>Owner Zone</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ActivityContact__c.object
<CustomObject>
    <fields>
        <fullName>ActivityContact__c</fullName>
        <description>This Field is populated by the trigger and contains ActivityId__c + Contact__c, it is used to ensure that no duplicate contact on an activity (does not allow duplicate)</description>
        <label>ActivityContact</label>
        <length>37</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ActivityId__c</fullName>
        <description>This fake Id field is binded to Task through the use of the "Contacts" Grid build in the GridBuddy application. It is populated by GB with Task.Id</description>
        <externalId>true</externalId>
        <label>ActivityId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivitySource__c</fullName>
        <description>This is populated by the trigger from Task.ActivitySource__c</description>
        <label>Activity Source</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by the trigger from Task.OwnerChannelId__c (=Owner:User.ActivityChannelId__c)</description>
        <label>Channel</label>
        <referenceTo>Channel__c</referenceTo>
        <relationshipLabel>Activity Contacts</relationshipLabel>
        <relationshipName>Activity_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>This is populated by the trigger with Task.ActivityDate</description>
        <label>Activity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OwnerChannelId__c</fullName>
        <formula>Owner:User.ActivityChannelId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Owner Channel Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OwnerChannel__c</fullName>
        <label>Owner Channel</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OwnerTerritoryId__c</fullName>
        <description>The owner's activity territory id at the time of activity creation</description>
        <label>Owner Territory Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OwnerTerritoryMARS__c</fullName>
        <description>The activity territory of the owner at the time of activity creation based on MARS territory name</description>
        <label>Owner Territory MARS</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OwnerTerritory__c</fullName>
        <label>Owner Territory</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OwnerZone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner Zone</label>
        <referenceTo>Zone__c</referenceTo>
        <relationshipLabel>Activity Contacts</relationshipLabel>
        <relationshipName>Activity_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <description>Each activity will have 1 to Many contacts. These activity related contacts are stored in this object along necessary attributes to allow for advanced activity reporting. This Table is synched up with the TaskRelation standard object through the "ActivityContactTrigger" trigger and the "ActivityContactTriggerHandler" Class.
This object is "virtually" related to Task through the use of the "ActivityId__c" field. This fake Id field is binded to Task through the use of the "Contacts" Grid build in the GridBuddy application.</description>
    <label>Activity Contact</label>
    <nameField>
        <displayFormat>AC-{0000000000}</displayFormat>
        <label>Activity Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Contacts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ActivityProduct__c.object
<CustomObject>
    <fields>
        <fullName>ActivityId__c</fullName>
        <externalId>true</externalId>
        <label>ActivityId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityProduct__c</fullName>
        <label>ActivityProduct</label>
        <length>37</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ActivitySource__c</fullName>
        <label>Activity Source</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Channel</label>
        <referenceTo>Channel__c</referenceTo>
        <relationshipLabel>Activity Products</relationshipLabel>
        <relationshipName>Activity_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OwnerChannel__c</fullName>
        <label>Owner Channel</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OwnerTerritoryId__c</fullName>
        <description>The owner's activity territory id at the time of activity creation</description>
        <label>Owner Territory Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OwnerTerritoryMARS__c</fullName>
        <description>The owner's activity territory at the time of activity creation based on MARS Territory Name</description>
        <label>Owner Territory MARS</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OwnerTerritory__c</fullName>
        <label>Owner Territory</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OwnerZone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner Zone</label>
        <referenceTo>Zone__c</referenceTo>
        <relationshipLabel>Activity Products</relationshipLabel>
        <relationshipName>Activity_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Product2.ProductVisible__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Activity Products</relationshipLabel>
        <relationshipName>Activity_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Activity Product</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Activity Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/NGAMSettingsHierarchy__c.object
<CustomObject>
    <fields>
        <fullName>CannotCUDActivityAfterDays__c</fullName>
        <description>Controls how many days after the activity date of a task or date of a corresponding activity contact or activity product a user can create, update, or delete an activity.  Used in trigger and validation rules.</description>
        <inlineHelpText>Controls how many days after the activity date of a task or date of a corresponding activity contact or activity product a user can create, update, or delete an activity.</inlineHelpText>
        <label>Cannot CUD Activity After Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NGAM Settings - Hierarchy</label>
</CustomObject>

objects/ProductOfInterest__c.object
<CustomObject>
    <fields>
        <fullName>ActivityId__c</fullName>
        <externalId>true</externalId>
        <label>ActivityId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityProductId__c</fullName>
        <externalId>true</externalId>
        <label>ActivityProductId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products of Interest</relationshipLabel>
        <relationshipName>Products_of_Interest</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>TEXT( Product__r.Status__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Product of Interest</label>
    <nameField>
        <displayFormat>PI-{0000000000}</displayFormat>
        <label>Products of Interest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products of Interest</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ActivityProductTriggerHandler.cls
public class ActivityProductTriggerHandler {
    
    public static void PreventDeletionOfOldRecords (List<ActivityProduct__c> ActivityProducts)  {
        
        Integer cannotCUDActivityAfterDays = (Integer)NGAMSettingsHierarchy__c.getInstance().CannotCUDActivityAfterDays__c;      
        system.debug('cannotCUDActivityAfterDays: ' + CannotCUDActivityAfterDays);
        
        for (ActivityProduct__c acd : ActivityProducts) {
            if (acd.date__c.daysBetween(Date.Today()) >= cannotCUDActivityAfterDays) {
                acd.addError('Cannot Delete Activity Product more than '+ cannotCUDActivityAfterDays + ' days after Activity Date');
            }
        } 
    }
    
    
    //-----------------------------------------------------------------------------------------------------------------------------------------------
    // ActivityProductAfterDelete
    // Will Delete all related ProductofInterest__c records
    //-----------------------------------------------------------------------------------------------------------------------------------------------
    public static void ActivityProductAfterDelete (List<ActivityProduct__c> ActivityProducts)  
        // Deletes all related  ProductofInterest__c records 
    {
        set <id> ActivityProductIds = new set<Id>();    
        
        for (ActivityProduct__c actProd : ActivityProducts)
        {    
            ActivityProductIds.add(actProd.id);    
        }
        
        List<ProductofInterest__c> POI_ToDelete = [select id from ProductofInterest__c where ActivityProductId__c in: ActivityProductIds];     
        
        if (!POI_ToDelete.isEmpty())
        {
            delete POI_ToDelete;
        } 
    }
    
    //-----------------------------------------------------------------------------------------------------------------------------------------------
    //  ActivityProductBeforeUpdate
    //  Sets the ActivityProduct__c key on the records
    //-----------------------------------------------------------------------------------------------------------------------------------------------
    public static void ActivityProductBeforeUpdate (List<ActivityProduct__c> ActivityProducts)  
    {
        for (ActivityProduct__c act : ActivityProducts)
        {
            act.ActivityProduct__c = act.ActivityId__c + '-' + act.Product__c;
        } 
    } 
    
    //-----------------------------------------------------------------------------------------------------------------------------------------------
    // ActivityProductBeforeInsert
    // Sets the ActivityProduct__c key on the records
    // Takes all the needed attributes from the related Task and copies them to the ActivityProduct__c records
    //-----------------------------------------------------------------------------------------------------------------------------------------------
    public static void ActivityProductBeforeInsert (List<ActivityProduct__c> ActivityProducts)  
    {         
        set <id> ActivityIds = new set<Id>();
        //set <id> ProductIds = new set<Id>();    
        
        for (ActivityProduct__c act : ActivityProducts)
        {
            act.ActivityProduct__c = act.ActivityId__c + '-' + act.Product__c;
            ActivityIds.add(act.ActivityId__c);
            //ProductIds.add(act.Product__c);   
        }
        
        Map<Id, Task> TaskMap = new Map<Id, Task>([Select Id, 
                                                   type, 
                                                   Subject, 
                                                   Status, 
                                                   ActivityDate, 
                                                   ActivitySource__c,                                  
                                                   OwnerChannel__c,
                                                   OwnerChannelId__c,
                                                   OwnerTerritory__c,
                                                   OwnerTerritoryMARS__c,
                                                   OwnerTerritoryId__c,
                                                   OwnerZoneFormula__c,
                                                   ownerid 
                                                   from Task where id in: ActivityIds]); 
        
        Map<Id, Event> EventMap = new Map<Id, Event>([Select Id, 
                                                      type, 
                                                      Subject, 
                                                      //Status, 
                                                      ActivityDate, 
                                                      ActivitySource__c,                                  
                                                      OwnerChannel__c,
                                                      OwnerChannelId__c,
                                                      OwnerTerritory__c,
                                                      OwnerTerritoryMARS__c,
                                                      OwnerTerritoryId__c,
                                                      OwnerZoneFormula__c,
                                                      ownerid 
                                                      from Event where id in: ActivityIds]); 
        
        for (ActivityProduct__c actProd : ActivityProducts)
        {
            if( TaskMap.containsKey(actProd.ActivityId__c))
            {
                actProd.Date__c = TaskMap.get(actProd.ActivityId__c).ActivityDate;
                actProd.Subject__c = TaskMap.get(actProd.ActivityId__c).Subject;
                actProd.Type__c = TaskMap.get(actProd.ActivityId__c).Type;
                actProd.Status__c = TaskMap.get(actProd.ActivityId__c).Status;
                actProd.ActivitySource__c = TaskMap.get(actProd.ActivityId__c).ActivitySource__c;  
                actProd.OwnerId = TaskMap.get(actProd.ActivityId__c).ownerid;     
                actProd.OwnerChannel__c = TaskMap.get(actProd.ActivityId__c).OwnerChannel__c;
                actProd.Channel__c = TaskMap.get(actProd.ActivityId__c).OwnerChannelId__c;
                actProd.OwnerTerritory__c = TaskMap.get(actProd.ActivityId__c).OwnerTerritory__c;
                actProd.OwnerTerritoryMARS__c = TaskMap.get(actProd.ActivityId__c).OwnerTerritoryMARS__c;
                actProd.OwnerTerritoryId__c = TaskMap.get(actProd.ActivityId__c).OwnerTerritoryId__c;
                actProd.OwnerZone__c = (id)TaskMap.get(actProd.ActivityId__c).OwnerZoneFormula__c; 
                
            }
            else
            {
                if( EventMap.containsKey(actProd.ActivityId__c))
                {
                    actProd.Date__c = EventMap.get(actProd.ActivityId__c).ActivityDate;
                    actProd.Subject__c = EventMap.get(actProd.ActivityId__c).Subject;
                    actProd.Type__c = EventMap.get(actProd.ActivityId__c).Subject;
                    
                    actProd.ActivitySource__c = EventMap.get(actProd.ActivityId__c).ActivitySource__c;  
                    actProd.OwnerId = EventMap.get(actProd.ActivityId__c).ownerid;     
                    actProd.OwnerChannel__c = EventMap.get(actProd.ActivityId__c).OwnerChannel__c;
                    actProd.Channel__c = EventMap.get(actProd.ActivityId__c).OwnerChannelId__c;
                    actProd.OwnerTerritory__c = EventMap.get(actProd.ActivityId__c).OwnerTerritory__c;
                    actProd.OwnerTerritoryMARS__c = EventMap.get(actProd.ActivityId__c).OwnerTerritoryMARS__c;
                    actProd.OwnerTerritoryId__c = EventMap.get(actProd.ActivityId__c).OwnerTerritoryId__c;
                    actProd.OwnerZone__c = (id)TaskMap.get(actProd.ActivityId__c).OwnerZoneFormula__c; 
                } 
            }
        }        
    }
    
    //-----------------------------------------------------------------------------------------------------------------------------------------------
    // ActivityProductAfterInsert
    // Trigger finds all the ActivityContact__c related to the related tasks  
    // Generate / attaches the Product of Interest Records to these Contacts and to their related Accounts
    //-----------------------------------------------------------------------------------------------------------------------------------------------
    public static void ActivityProductAfterInsert (List<ActivityProduct__c> activityProducts)  
    {      
        set <id> ActivityIds = new set<Id>();  
        List<ProductofInterest__c> POI_ToInsert = new List<ProductofInterest__c>();   
        
        for (ActivityProduct__c act : ActivityProducts)
        {
            ActivityIds.add(act.ActivityId__c);   
        }   
        
        List<TaskRelation> taskRelationList = [SELECT Id, RelationId, AccountId, TaskId FROM TaskRelation WHERE TaskId IN: activityIds];
        
        for (ActivityProduct__c ap : activityProducts) {
            
            for (TaskRelation tr : taskRelationList) {
                Id activityId = (Id)ap.ActivityId__c;
                String realtionId = (String)tr.RelationId;
                if (tr.TaskId == activityId && realtionId.startsWith('003')) {
                    
                    ProductofInterest__c PoI = new ProductofInterest__c();
                    Poi.Subject__c = ap.Subject__c;
                    Poi.RepContact__c = tr.RelationId;
                    Poi.FirmBranch__c = tr.AccountId;
                    Poi.ActivityProductId__c = ap.id;
                    Poi.RelationId__c = tr.Id;
                    Poi.Product__c = ap.Product__c;
                    Poi.ActivityId__c = ap.ActivityId__c;
                    Poi.Date__c = ap.Date__c;
                    POI_ToInsert.add(PoI);
                }
                
            }
        }
        
        if (!POI_ToInsert.isEmpty()) insert POI_ToInsert;
    }
    
}