objects/ActivityContact__c.object
<CustomObject>
    <fields>
        <fullName>ActivityContact__c</fullName>
        <description>This Field is populated by the trigger and contains ActivityId__c + Contact__c, it is used to ensure that no duplicate contact on an activity (does not allow duplicate)</description>
        <label>ActivityContact</label>
        <length>37</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ActivityId__c</fullName>
        <description>This fake Id field is binded to Task through the use of the "Contacts" Grid build in the GridBuddy application. It is populated by GB with Task.Id</description>
        <externalId>true</externalId>
        <label>ActivityId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AffiliateContactFlag__c</fullName>
        <description>Formula that displays the Affiliate Contact value from the Contact Object. Used in the Declarative Roll Up 'CaseActivityContactRequestedSpeakersFlag'</description>
        <formula>Contact__r.AffiliateContactFlag__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Affiliate Contact Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>This is populated by the trigger with Task.ActivityDate</description>
        <label>Activity Date</label>
        <type>Date</type>
    </fields>
    <description>Each activity will have 1 to Many contacts. These activity related contacts are stored in this object along necessary attributes to allow for advanced activity reporting. This Table is synched up with the TaskRelation standard object through the "ActivityContactTrigger" trigger and the "ActivityContactTriggerHandler" Class.
This object is "virtually" related to Task through the use of the "ActivityId__c" field. This fake Id field is binded to Task through the use of the "Contacts" Grid build in the GridBuddy application.</description>
    <label>Activity Contact</label>
    <nameField>
        <displayFormat>AC-{0000000000}</displayFormat>
        <label>Activity Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Contacts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>RequestedSpeakers__c</fullName>
        <description>Field to be populated to start the Affiliate Request process.  Once the requests are approved then the actual Affiliate speakers are captured in the Events associated to the Request. Lookup Rollup Summary: https://globalplatform.my.salesforce.com/a0m2A00000MwtJm</description>
        <inlineHelpText>Field to be populated to start the Affiliate Request process.  Once the requests are approved then the actual Affiliate speakers are captured in the Events associated to the Request.</inlineHelpText>
        <label>Requested Speaker(s)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel><enableHistory>true</enableHistory>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>AffiliateContactFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Auto populated by process builder for all new Affiliate Contacts added but can be manually maintained to control who is brought into the Declarative Roll-up that populates the Requested Speaker on the Case from the related Events</description>
        <inlineHelpText>Auto populated by process builder for all new Affiliate Contacts added but can be manually maintained to control who is brought into the Declarative Roll-up that populates the Requested Speaker on the Case from the related Events</inlineHelpText>
        <label>Affiliate Contact Flag</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/NGAMSettingsHierarchy__c.object
<CustomObject>
    <fields>
        <fullName>ByPassAccountValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows entity to by-pass validation rules on Account</description>
        <inlineHelpText>Allows entity to by-pass validation rules on Account</inlineHelpText>
        <label>By-Pass Account Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CannotCUDActivityAfterDays__c</fullName>
        <description>Controls how many days after the activity date of a task or date of a corresponding activity contact or activity product a user can create, update, or delete an activity.  Used in trigger and validation rules.</description>
        <inlineHelpText>Controls how many days after the activity date of a task or date of a corresponding activity contact or activity product a user can create, update, or delete an activity.</inlineHelpText>
        <label>Cannot CUD Activity After Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NGAM Settings - Hierarchy</label>
</CustomObject>

classes/ActivityContactTriggerHandlerTest.cls
@isTest
public class ActivityContactTriggerHandlerTest {
    
    @testSetup
    public static void testSetup() {
        
        
        NGAMSettingsHierarchy__c hsettings = NGAMSettingsHierarchy__c.getOrgDefaults();
        hsettings.ByPassAccountValidationRules__c  = TRUE;
        hsettings.CannotCUDActivityAfterDays__c = 5;
        upsert hsettings NGAMSettingsHierarchy__c.Id;
        DataFactory.CreateNGAMCustomSettings(); 
        
        List<Account> myAccounts = DataFactory.createTestAccounts(1);
        insert myAccounts;
        
        List<Contact> myContacts = DataFactory.createTestContacts(4, myAccounts, false);
        insert myContacts;     
        
        List<Task> myTasks = DataFactory.createTestTasks_outlookPlugin(3,myContacts,'Email');  
        insert myTasks; 
        
        //Added by Prabhpreet
        List<Event> myEvents = DataFactory.createTestEvents(3,myContacts,'Call');  
        insert myEvents; 

        //Added by Prabhpreet
        List<Case> myCases = DataFactory.createCases(3,myAccounts);  
        insert myCases; 

        List<ActivityContact__c> myACs = DataFactory.createActivityContacts(myTasks, myContacts);
        insert myACs;

        //Added by Prabhpreet
        List<ActivityContact__c> lstEventACs = DataFactory.createActivityContactsEvents(myEvents, myContacts);
        insert lstEventACs;

        

    }
    
    @isTest
    public static void testAll() {
        
        List<ActivityContact__c> myACs = [SELECT Id
                                          FROM ActivityContact__c];
        
        myACs[0].Date__c = Date.today().addDays(-1);
        update myACs;
        delete myACs[0];
        undelete myACs[0];
        
        myACs[1].Date__c = Date.today().addDays(-10);
        update myACs[1];
        
        try {
            delete myACs[1]; 
        } catch(DmlException e) {        
        }
        
        
    }

    // Added by Prabhpreet
    @isTest
    public static void testCaseSpeakersUpdate() {
        
        List<Contact> lstContacts = [SELECT Name, AffiliateContactFlag__c
                                          FROM Contact];

        
        lstContacts[0].AffiliateContactFlag__c = true;
        
        update lstContacts[0];

        List<Case> lstCase = [SELECT Id
                                          FROM Case];

        List<Event> lstEvent = [SELECT WhatId, WhoId
                                          FROM Event];


        lstEvent[0].WhatId = lstCase[0].Id;
        lstEvent[0].WhoId = lstContacts[0].Id;

        update lstEvent[0];

        List<ActivityContact__c> myACs = [SELECT ActivityId__c
                                          FROM ActivityContact__c];
        
        myACs[0].ActivityId__c = lstEvent[0].Id;
        update myACs[0];

        Case objCase = [SELECT Id,RequestedSpeakers__c
                                          FROM Case WHERE Id =: lstCase[0].Id ];

        
       System.assertEquals(lstContacts[0].Name, objCase.RequestedSpeakers__c);
    }
    
}