objects/ActivityContact__c.object
<CustomObject>
    <fields>
        <fullName>ActivityContact__c</fullName>
        <description>This Field is populated by the trigger and contains ActivityId__c + Contact__c, it is used to ensure that no duplicate contact on an activity (does not allow duplicate)</description>
        <label>ActivityContact</label>
        <length>37</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ActivitySource__c</fullName>
        <description>This is populated by the trigger from Task.ActivitySource__c</description>
        <label>Activity Source</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <description>Each activity will have 1 to Many contacts. These activity related contacts are stored in this object along necessary attributes to allow for advanced activity reporting. This Table is synched up with the TaskRelation standard object through the "ActivityContactTrigger" trigger and the "ActivityContactTriggerHandler" Class.
This object is "virtually" related to Task through the use of the "ActivityId__c" field. This fake Id field is binded to Task through the use of the "Contacts" Grid build in the GridBuddy application.</description>
    <label>Activity Contact</label>
    <nameField>
        <displayFormat>AC-{0000000000}</displayFormat>
        <label>Activity Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Contacts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/MassEmailBatch.cls
global class MassEmailBatch implements Database.Batchable<sObject>, Database.Stateful{

    Public String query = 'select id from Task where Id = null';
    
    global MassEmailBatch() {
        System.Debug('MassEmailBatch');
    }
    
 
   global Database.QueryLocator start(Database.BatchableContext BC) {
       return Database.getQueryLocator(query);
   }
 
   global void execute(Database.BatchableContext BC, List<Task> scope) {
       
/*      List<Task> TasksToUpdate = new List<Task>();
       
      for (Task tsk : scope)
            {
			TasksToUpdate.add(new Task(id=tsk.id,Type = 'Mass Email',Description=tsk.Subject,Subject = 'Mass Email', ActivitySource__c = 'SFDC Mass Email'));
            }  
       
        if (TasksToUpdate.size()>0)
        	{
            // This is to Perform the Before Update / After Update
        	update TasksToUpdate;
            } 
       
       // This is to Insert ONE ActivityContact__c record
       If (!test.isRunningTest())
       {
       	TaskTriggerHandler.TaskTriggerAfterInsert(scope);
       }*/
   }
 
   global void finish(Database.BatchableContext BC) {
       /*try 
       {
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            String[] toAddresses = new String[] {'dat@ngam.natixis.com'};
            mail.setToAddresses(toAddresses);
            //mail.setReplyTo('dat@ngam.natixis.com');
            mail.setSenderDisplayName('NGAM SFDC');
            mail.setSubject('MassEmailBatch');
            String EmailBody =   'SOQL='+ query + ' <br/>'; 
            mail.setHTMLBody(EmailBody);
            System.Debug('EmailBody '  + EmailBody);             
            if (!Test.IsRunningTest())  Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail }); 
       }
      catch (Exception e) {
           System.debug('Exception: ' + e);            
           }     */
   }


    
}