objects/Activity.object
<CustomObject>
    <fields>
        <fullName>ActivityId__c</fullName>
        <formula>CaseSafeId( Id )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ActivityId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivitySource__c</fullName>
        <description>Captures the Source of the Activity</description>
        <label>Activity Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Artemus</fullName>
                </value>
                <value>
                    <fullName>BlackBerryCRM</fullName>
                </value>
                <value>
                    <fullName>Broadridge</fullName>
                </value>
                <value>
                    <fullName>Civicomm</fullName>
                </value>
                <value>
                    <fullName>FI360</fullName>
                </value>
                <value>
                    <fullName>GlobalConnect</fullName>
                </value>
                <value>
                    <fullName>GPS</fullName>
                </value>
                <value>
                    <fullName>Harte Hanks</fullName>
                </value>
                <value>
                    <fullName>Outlook Integration</fullName>
                </value>
                <value>
                    <fullName>Portfolio</fullName>
                </value>
                <value>
                    <fullName>User Created</fullName>
                </value>
                <value>
                    <fullName>Process CPE</fullName>
                </value>
                <value>
                    <fullName>Outlook Email Svc</fullName>
                </value>
                <value>
                    <fullName>Salesforce1</fullName>
                </value>
                <value>
                    <fullName>Seismic</fullName>
                </value>
                <value>
                    <fullName>Digital Campaign</fullName>
                </value>
                <value>
                    <fullName>Engage</fullName>
                </value>
                <value>
                    <fullName>Break Out</fullName>
                </value>
                <value>
                    <fullName>Small Conf. Follow Up</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ActivitySubType__c</fullName>
        <description>The dependent field on Type IC to drive value visibility</description>
        <inlineHelpText>Select a Type field to view valid Sub Types</inlineHelpText>
        <label>Activity Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ActivityType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Affiliate Request</fullName>
                </value>
                <value>
                    <fullName>Product/Promotional</fullName>
                </value>
                <value>
                    <fullName>Follow-Up/Service</fullName>
                </value>
                <value>
                    <fullName>Solutions</fullName>
                </value>
                <value>
                    <fullName>Roadshow</fullName>
                </value>
                <value>
                    <fullName>Other/Voicemail</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ActivityType__c</fullName>
        <description>Used to control the Sub Type field and not displayed in the UI. The out of box field Type is displayed in the UI.</description>
        <label>Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Meeting</fullName>
                </value>
                <value>
                    <fullName>Call</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
                <value>
                    <fullName>Transportation</fullName>
                </value>
                <value>
                    <fullName>Hotel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProductList__c</fullName>
        <description>A Semicolon Separated Group of Product Ids.</description>
        <inlineHelpText>A Semicolon Separated Group of Product Ids.</inlineHelpText>
        <label>Product List</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ActivityContact__c.object
<CustomObject>
    <fields>
        <fullName>ActivityContact__c</fullName>
        <description>This Field is populated by the trigger and contains ActivityId__c + Contact__c, it is used to ensure that no duplicate contact on an activity (does not allow duplicate)</description>
        <label>ActivityContact</label>
        <length>37</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ActivityId__c</fullName>
        <description>This fake Id field is binded to Task through the use of the "Contacts" Grid build in the GridBuddy application. It is populated by GB with Task.Id</description>
        <externalId>true</externalId>
        <label>ActivityId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityRelationId__c</fullName>
        <description>Either the TaskRelation Id or EventRelation Id that is associated with this row</description>
        <externalId>true</externalId>
        <label>Activity Relation Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivitySource__c</fullName>
        <description>This is populated by the trigger from Task.ActivitySource__c</description>
        <label>Activity Source</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivitySubType__c</fullName>
        <description>The dependent field on Type IC to drive value visibility , Copied from Task object  in insert trigger.</description>
        <label>Activity Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ActivityType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Product/Promotional</fullName>
                </value>
                <value>
                    <fullName>Follow-Up/Service</fullName>
                </value>
                <value>
                    <fullName>Solutions</fullName>
                </value>
                <value>
                    <fullName>Roadshow</fullName>
                </value>
                <value>
                    <fullName>Other/Voicemail</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ActivityType__c</fullName>
        <description>Used to control the Sub Type field and not displayed in the UI. The out of box field Type is displayed in the UI.</description>
        <label>Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Meeting</fullName>
                </value>
                <value>
                    <fullName>Call</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is entered through the Gridbuddy Form and is set to the id of the contact entered through the form. It is used by the trigger to create the TaskRelation entry to the related Task</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Activity Contacts</relationshipLabel>
        <relationshipName>ActivityContacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <description>Each activity will have 1 to Many contacts. These activity related contacts are stored in this object along necessary attributes to allow for advanced activity reporting. This Table is synched up with the TaskRelation standard object through the "ActivityContactTrigger" trigger and the "ActivityContactTriggerHandler" Class.
This object is "virtually" related to Task through the use of the "ActivityId__c" field. This fake Id field is binded to Task through the use of the "Contacts" Grid build in the GridBuddy application.</description>
    <label>Activity Contact</label>
    <nameField>
        <displayFormat>AC-{0000000000}</displayFormat>
        <label>Activity Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Contacts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ActivityProduct__c.object
<CustomObject>
    <fields>
        <fullName>ActivityId__c</fullName>
        <externalId>true</externalId>
        <label>ActivityId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityProduct__c</fullName>
        <label>ActivityProduct</label>
        <length>37</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ActivityRelationId__c</fullName>
        <description>The TaskRelation or EventRelation that is associated with this row</description>
        <label>Activity Relation Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivitySource__c</fullName>
        <label>Activity Source</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivitySubType__c</fullName>
        <label>Activity SubType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Affiliate Request</fullName>
                </value>
                <value>
                    <fullName>Product/Promotional</fullName>
                </value>
                <value>
                    <fullName>Follow-Up/Service</fullName>
                </value>
                <value>
                    <fullName>Solutions</fullName>
                </value>
                <value>
                    <fullName>Roadshow</fullName>
                </value>
                <value>
                    <fullName>Other/Voicemail</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ActivityType__c</fullName>
        <label>Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Call</fullName>
                </value>
                <value>
                    <fullName>Meeting</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Product2.ProductVisible__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Activity Products</relationshipLabel>
        <relationshipName>Activity_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Activity Product</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Activity Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/LEXTaskBatch.cls
global class LEXTaskBatch implements Database.Batchable<sObject>, Database.Stateful{
    
    //confirm translation map
    //update activity points settings
    //ALWAYS send the where clause, or this will run for all tasks
    //Turn off validation rule for updating old tasks
    
    global String whereCriteria;
    
    global Database.querylocator start(Database.BatchableContext BC){   
	    String query = 'SELECT Id, ActivityType__c, Status, ActivitySubType__c, ProductList__c, ActivitySource__c FROM Task ' + whereCriteria;
        system.debug('query: ' + query);
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Task> scope) { 
        
        LEXConversionContext.runningConversion = TRUE;

        Map<String,String> typeSubTypeTranslation = new Map<String,String>();
        typeSubTypeTranslation.put('Call - Informative|null','Call|Product/Promotional');
        typeSubTypeTranslation.put('Call - Left Message|null','Call|Other/Voicemail');
        typeSubTypeTranslation.put('Call - Substantive|null','Call|Product/Promotional');
        typeSubTypeTranslation.put('Email - Contact|null','Email|Product/Promotional');
        typeSubTypeTranslation.put('Email - Contact|Email','Email|Email');        
        typeSubTypeTranslation.put('Meeting - Group|null','Meeting|Product/Promotional');
        typeSubTypeTranslation.put('Meeting - One on One|null','Meeting|Product/Promotional');
        typeSubTypeTranslation.put('High Impact|AIA','Call|Product/Promotional');
        typeSubTypeTranslation.put('High Impact|IDU/RADU Prospecting','Research|Research');
        typeSubTypeTranslation.put('High Impact|IDU/RADU Research','Research|Research');
        typeSubTypeTranslation.put('High Impact|ISG/CPM/DCG Call','Call|Product/Promotional');
        typeSubTypeTranslation.put('High Impact|PRCG - Comprehensive Portfolio Review','Call|Solutions');
        typeSubTypeTranslation.put('High Impact|Retirement/RSA Client Call','Call|Product/Promotional');
        typeSubTypeTranslation.put('High Impact|Sales Desk Focus','Call|Product/Promotional');
        typeSubTypeTranslation.put('High Impact|Sales Interaction','Call|Product/Promotional');
        typeSubTypeTranslation.put('High Impact|Sales Interaction Converted from Service','Call|Product/Promotional');
        typeSubTypeTranslation.put('High Impact|Sales Interaction Converted from Follow Up','Call|Product/Promotional');
        typeSubTypeTranslation.put('Servicing|Phone Servicing an Asset','Call|Follow-Up/Service');
        typeSubTypeTranslation.put('Servicing|Email Servicing an Asset','Email|Follow-Up/Service');
        typeSubTypeTranslation.put('Servicing|Call Scheduling Meetings for the field','Call|Follow-Up/Service');
        typeSubTypeTranslation.put('Servicing|Email Scheduling Meetings for the field','Email|Follow-Up/Service');
        typeSubTypeTranslation.put('Servicing|Gathering Territory/Client Intell','Research|Research');
        typeSubTypeTranslation.put('Servicing|Advisor Web Portal','Call|Follow-Up/Service');
        typeSubTypeTranslation.put('Follow Up|Phone Call Follow up','Call|Follow-Up/Service');
        typeSubTypeTranslation.put('Follow Up|Email Follow Up','Email|Follow-Up/Service');
        typeSubTypeTranslation.put('Follow Up|Territory Email Campaign','Email|Follow-Up/Service');
        typeSubTypeTranslation.put('Follow Up|CPE Pre Calls','Call|Follow-Up/Service');
        typeSubTypeTranslation.put('Follow Up|Natixis Resource Lead In or Follow Up','Call|Follow-Up/Service');
        typeSubTypeTranslation.put('Meeting|One-On-One','Meeting|Product/Promotional');
        typeSubTypeTranslation.put('Meeting|Group','Meeting|Product/Promotional');
        typeSubTypeTranslation.put('Left Message|Left Message','Call|Other/Voicemail');
        typeSubTypeTranslation.put('Email|Email','Email|Email');
        typeSubTypeTranslation.put('Seismic - Contact|Email Follow Up','Email|Follow-Up/Service');
        typeSubTypeTranslation.put('Seismic - Contact|Email Servicing an Asset','Email|Follow-Up/Service');
        typeSubTypeTranslation.put('Seismic LiveSend|Seismic LiveSend','Email|Marketing');

        typeSubTypeTranslation.put('Call - Informative|Email','Call|Product/Promotional');
        typeSubTypeTranslation.put('Call - Informative|Seismic LiveSend','Call|Product/Promotional');
        typeSubTypeTranslation.put('Call - Left Message|Phone Call Follow up','Call|Other/Voicemail');
        typeSubTypeTranslation.put('Meeting - Group|ISG/CPM/DCG Call','Meeting|Product/Promotional');
        typeSubTypeTranslation.put('Meeting - Group|Phone Servicing an Asset','Meeting|Follow-Up/Service');
        typeSubTypeTranslation.put('Seismic - Contact|Email','Email|Product/Promotional');
        typeSubTypeTranslation.put('Seismic - Contact|Seismic LiveSend','Email|Product/Promotional');
        typeSubTypeTranslation.put('Follow Up|Email','Email|Follow-Up/Service');
        typeSubTypeTranslation.put('Left Message|Phone Call Follow up','Call|Other/Voicemail');
        typeSubTypeTranslation.put('Email - Contact|Email Servicing an Asset','Email|Follow-Up/Service');        
        typeSubTypeTranslation.put('Email - Contact|Phone Call Follow up','Call|Follow-Up/Service');        
        typeSubTypeTranslation.put('Email - Contact|Email Follow Up','Follow-Up/Service');        
        typeSubTypeTranslation.put('Email - Contact|Seismic LiveSend','Email|Product/Promotional');        
        typeSubTypeTranslation.put('Call - Substantive|Email','Call|Product/Promotional');

        Map<Id,Task> taskMap = new Map<Id,Task>();
        for (Task t : scope) {
            taskMap.put(t.Id, t); 
        }
        
        Map<String,ActivityProduct__c> activityProductKeyMap = UtilActivity.getActivityProductKeyMap(taskMap);
        Map<Id,List<Id>> taskProductMap = new Map<Id,List<Id>>();
        
        for (ActivityProduct__c ap : activityProductKeyMap.values()) {
            
            if (taskProductMap.containsKey(ap.ActivityId__c)) {
                List<Id> tempList = taskProductMap.get(ap.ActivityId__c);
                tempList.add(ap.Product__c);
                taskProductMap.put(ap.ActivityId__c, tempList);
            } else {
                List<Id> tempList = new List<Id>();
                tempList.add(ap.Product__c);
                taskProductMap.put(ap.ActivityId__c, tempList);
            }
        }
        
        for (Task t : scope) {
//            String typeSubTypeOld = t.ActivitySubType__c == null ? t.ActivityType__c + '|' : t.ActivityType__c + '|' + t.ActivitySubType__c;
            String typeSubTypeOld = t.ActivityType__c + '|' + t.ActivitySubType__c;
            system.debug('old subtype: ' + typeSubTypeOld);
            
            if (typeSubTypeTranslation.containsKey(typeSubTypeOld)) {
                system.debug('found it');
                String typeSubTypeNew = typeSubTypeTranslation.get(typeSubTypeOld);
                t.ActivityType__c = typeSubTypeNew.substringBefore('|');
                t.ActivitySubType__c = typeSubTypeNew.substringAfter('|');
                t.Type = t.ActivityType__c;
            }
        }
        
        update scope;
        
        for (Task t : scope) {
            if (taskProductMap.containsKey(t.Id)) {
                List<Id> productIdList = taskProductMap.get(t.Id);
                t.ProductList__c = String.join(productIdList,';');
            }
        }

        update scope;
            
        Map<String,ActivityContact__c> acContactMap = UtilActivity.getActivityContactKeyMap(taskMap);
        Map<String,TaskRelation> taskRelMap = new Map<String,TaskRelation>();
        Set<String> acActivityIdSet = new Set<String>();
        Set<String> acContactIdSet = new Set<String>();
        List<TaskRelation> trToInsert = new List<TaskRelation>();
        List<ActivityContact__c> acToUpdate = new List<ActivityContact__c>();
        
        for (ActivityContact__c ac : acContactMap.values()) {
            acActivityIdSet.add(ac.ActivityId__c);
            acContactIdSet.add(ac.Contact__c);
        }
        
        for (TaskRelation tr :[SELECT Id, TaskId, RelationId
                               FROM TaskRelation
                               WHERE TaskId IN :acActivityIdSet
                               AND RelationId IN :acContactIdSet]) {
                                   taskRelMap.put((String)tr.TaskId + (String)tr.RelationId, tr);
                               }
        
        for (ActivityContact__c ac : acContactMap.values()) {
            if (ac.ActivityId__c.startsWith('00T')) {
                if(!taskRelMap.containsKey(ac.ActivityId__c+ac.Contact__c)) {
                    trToInsert.add(new TaskRelation(RelationId = ac.Contact__c, TaskId = ac.ActivityId__c, IsWhat = FALSE));
                }
            } 
            
        }  
        
        if (!trToInsert.isEmpty()) insert trToInsert;
        
        for (TaskRelation tr : [SELECT Id, TaskId, RelationId
                                FROM TaskRelation
                                WHERE TaskId IN :acActivityIdSet
                                AND RelationId IN :acContactIdSet]) {
                                    if (acContactMap.containsKey((String)tr.TaskId + (String)tr.RelationId)) {
                                        ActivityContact__c ac = acContactMap.get((String)tr.TaskId + (String)tr.RelationId);
                                        ac.ActivityRelationId__c = tr.Id;
                                        acToUpdate.add(ac);
                                    }
                                }
        
        if (!acToUpdate.isEmpty()) update acToUpdate;
        
        update scope;
        
    }
    
    global void finish(Database.BatchableContext BC){
        
    }
    
}