objects/Activity.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ActivityContact__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Activity Contacts</relationshipLabel>
        <relationshipName>Activity_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ActivityContact__c</fullName>
        <description>This Field is populated by the trigger and contains ActivityId__c + Contact__c, it is used to ensure that no duplicate contact on an activity (does not allow duplicate)</description>
        <label>ActivityContact</label>
        <length>37</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For the Affiliate Request Process</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Activity Contacts</relationshipLabel>
        <relationshipName>Activity_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is entered through the Gridbuddy Form and is set to the id of the contact entered through the form. It is used by the trigger to create the TaskRelation entry to the related Task</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Activity Contacts</relationshipLabel>
        <relationshipName>ActivityContacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>This is populated by the trigger with Task.ActivityDate</description>
        <label>Activity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <description>Each activity will have 1 to Many contacts. These activity related contacts are stored in this object along necessary attributes to allow for advanced activity reporting. This Table is synched up with the TaskRelation standard object through the "ActivityContactTrigger" trigger and the "ActivityContactTriggerHandler" Class.
This object is "virtually" related to Task through the use of the "ActivityId__c" field. This fake Id field is binded to Task through the use of the "Contacts" Grid build in the GridBuddy application.</description>
    <label>Activity Contact</label>
    <nameField>
        <displayFormat>AC-{0000000000}</displayFormat>
        <label>Activity Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Contacts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Team</fullName>
        <active>true</active>
        <label>Team</label>
    </recordTypes>
</CustomObject>

objects/NGAMSettings__c.object
<CustomObject>
    <fields>
        <fullName>ActivityContactRollupBatchFromDate__c</fullName>
        <description>Used by ActivityContactRollupBatch as the starting date for AC roll up.  Can be set to any date within last 30 days, but must be before Activity Contact Rollup Batch To Date.  Value normally maintained automatically by batch.</description>
        <inlineHelpText>Used by ActivityContactRollupBatch as the starting date for AC roll up.  Can be set to any date within last 30 days, but must be before Activity Contact Rollup Batch To Date.  Value normally maintained automatically by batch.</inlineHelpText>
        <label>Activity Contact Rollup Batch From Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ActivityContactRollupBatchToDate__c</fullName>
        <description>Used by ActivityContactRollupBatch as the end date for AC roll up.  Can be set to any date within last 30 days, but must be after Activity Contact Rollup Batch From Date.  Value normally maintained automatically by batch.</description>
        <inlineHelpText>Used by ActivityContactRollupBatch as the end date for AC roll up.  Can be set to any date within last 30 days, but must be after Activity Contact Rollup Batch From Date.  Value normally maintained automatically by batch.</inlineHelpText>
        <label>Activity Contact Rollup Batch To Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>FailureNotificationEmailAddress__c</fullName>
        <description>Used in apex to notify via email when processes fail. Separate multiple email addresses with semi-colons.</description>
        <inlineHelpText>Used in apex to notify via email when processes fail. Separate multiple email addresses with semi-colons.</inlineHelpText>
        <label>Failure Notification Email Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Holds the NGAM settings</description>
    <label>NGAM Settings</label>
</CustomObject>

classes/ActivityContactRollupBatch.cls
global class ActivityContactRollupBatch implements Database.Batchable<sObject>, Database.Stateful{
    
    //public String query = ' select Id, Type__c, Contact__c, Account__c, Case__c, Lastmodifieddate, Date__c from ActivityContact__c where SystemModStamp >= LAST_N_DAYS:1 order by Account__c, Contact__c'; 
    
    global Database.querylocator start(Database.BatchableContext BC){  
        NGAMSettings__c NamRecord =[select id,ActivityContactRollupBatchFromDate__c,ActivityContactRollupBatchToDate__c  from NGAMSettings__c  limit 1];
        Datetime fromDate = NamRecord.ActivityContactRollupBatchFromDate__c != null ? NamRecord.ActivityContactRollupBatchFromDate__c : system.today().adddays(-1);
        Datetime toDate = NamRecord.ActivityContactRollupBatchToDate__c != null ? NamRecord.ActivityContactRollupBatchToDate__c : system.today().adddays(1);
        
        NamRecord.ActivityContactRollupBatchFromDate__c  = system.now();
        update NamRecord;
        return Database.getQueryLocator([select Id, 
                                         Type__c, 
                                         Contact__c, 
                                         Account__c, 
                                         Case__c, 
                                         Lastmodifieddate,
                                         Date__c from ActivityContact__c 
                                         where SystemModStamp >=:fromDate and SystemModStamp <=:toDate
                                         order by Account__c, Contact__c]); 
    } 
    
    global void execute(Database.BatchableContext BC, List<ActivityContact__c> scope) { 
        
        List<ActivityContact__C> ACs = [select id, type__c, contact__c, case__c, account__c from ActivityContact__C where id in: scope];
        
        //List<SObject> parents = (List<SObject>) dlrs.RollupService.rollup(ACs);
        List<SObject> parents = new List<SObject>();
        Map<Id,SObject> distinctParents = new Map<Id,SObject>();
        
        for (SObject s : parents) {
            distinctParents.put(s.Id,s);
        }
        
        update distinctParents.values(); 
        
    }
    
    global void finish(Database.BatchableContext BC){
        
        NGAMSettings__c NamRecord =[select id,
                                    ActivityContactRollupBatchFromDate__c,
                                    FailureNotificationEmailAddress__c,
                                    ActivityContactRollupBatchToDate__c  from NGAMSettings__c  limit 1];
        NamRecord.ActivityContactRollupBatchToDate__c = null;
        update NamRecord;
        
        AsyncApexJob a = [Select Id, 
                          Status,
                          ExtendedStatus,
                          NumberOfErrors,     
                          JobItemsProcessed,
                          TotalJobItems, CreatedBy.Email from AsyncApexJob where Id =:BC.getJobId()];
        
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {NamRecord.FailureNotificationEmailAddress__c};
        mail.setToAddresses(toAddresses);
        mail.setSubject('ActivityContactRollupBatch ' + a.Status);
        mail.setHtmlBody('Hi Team,<br/>Records processed ' + a.TotalJobItems +
                         ' with '+ a.NumberOfErrors + ' failures. <br/><br/> Start Date: '+NamRecord.ActivityContactRollupBatchFromDate__c+'.<br/>' +
                         'Update Custom Setting Activity Contact Rollup Batch From Date with the above Start Date and run another batch from the Dev Console with the following command: <br/>' + 
                         '  Id batchJobId = Database.executeBatch(new ActivityContactRollupBatch(), 100); <br/><br/>' +
                         'If the job fails again, use the Custom Setting Activity Contact Rollup Batch To Date (and Start Date) to limit the number of batches in the run.');
        if(a.NumberOfErrors  > 0){
        	Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        }
    }    
}