objects/ActivityContact__c.object
<CustomObject>
    <fields>
        <fullName>ActivityContact__c</fullName>
        <description>This Field is populated by the trigger and contains ActivityId__c + Contact__c, it is used to ensure that no duplicate contact on an activity (does not allow duplicate)</description>
        <label>ActivityContact</label>
        <length>37</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ActivityType__c</fullName>
        <description>Used to control the Sub Type field and not displayed in the UI. The out of box field Type is displayed in the UI.</description>
        <label>Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Meeting</fullName>
                </value>
                <value>
                    <fullName>Call</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Each activity will have 1 to Many contacts. These activity related contacts are stored in this object along necessary attributes to allow for advanced activity reporting. This Table is synched up with the TaskRelation standard object through the "ActivityContactTrigger" trigger and the "ActivityContactTriggerHandler" Class.
This object is "virtually" related to Task through the use of the "ActivityId__c" field. This fake Id field is binded to Task through the use of the "Contacts" Grid build in the GridBuddy application.</description>
    <label>Activity Contact</label>
    <nameField>
        <displayFormat>AC-{0000000000}</displayFormat>
        <label>Activity Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Contacts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EventRelationSyncSchedule.cls
global class EventRelationSyncSchedule implements Schedulable{
    
    global static String scheduleMe() 
    {
        
        String jobname1 = !Test.isRunningTest() ? 'Hourly EventRelationSyncSchedule 1' : 'Hourly EventRelationSyncSchedule 1' + Datetime.now();
        String jobname2 = !Test.isRunningTest() ? 'Hourly EventRelationSyncSchedule 2' : 'Hourly EventRelationSyncSchedule 2' + Datetime.now();
        String jobname3 = !Test.isRunningTest() ? 'Hourly EventRelationSyncSchedule 3' : 'Hourly EventRelationSyncSchedule 3' + Datetime.now();
        String jobname4 = !Test.isRunningTest() ? 'Hourly EventRelationSyncSchedule 4' : 'Hourly EventRelationSyncSchedule 4' + Datetime.now();
        
        EventRelationSyncSchedule SC = new EventRelationSyncSchedule(); 
        System.schedule(jobname1, '0 0 * * * ?', SC);
        System.schedule(jobname2, '0 15 * * * ?', SC);
        System.schedule(jobname3, '0 30 * * * ?', SC);
        System.schedule(jobname4, '0 45 * * * ?', SC); 
        
        return 'Done';    
    }
    
    global void execute(SchedulableContext sc) {
        
        // ActivityContact__c rollup (where ActivityContact__c is child)
        EventRelationSyncBatch myevents = new EventRelationSyncBatch();
        Datetime xminutesBack = Datetime.now().addMinutes(-15);
        String formattedDt = xminutesBack.format('yyyy-MM-dd\'T\'hh:mm:ss\'Z\'');
        myevents.query = ' Select Product__c,Type,id,ActivityType__c,Whoid,WhatId,EventWhoIds,Subject,ActivityDate,OwnerId,recordTypeID, (select id, RelationId,EventId from EventRelations where iswhat=false) from Event Where SystemModStamp >= LAST_N_DAYS:1  AND SystemModStamp >=' + formattedDt ;
        Database.executeBatch(myevents,100);
        
        
    }
}