objects/Activity.object
<CustomObject>
    <fields>
        <fullName>ActivityId__c</fullName>
        <formula>CaseSafeId( Id )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ActivityId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductList__c</fullName>
        <description>A Semicolon Separated Group of Product Ids.</description>
        <inlineHelpText>A Semicolon Separated Group of Product Ids.</inlineHelpText>
        <label>Product List</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ActivityContact__c.object
<CustomObject>
    <fields>
        <fullName>ActivityContact__c</fullName>
        <description>This Field is populated by the trigger and contains ActivityId__c + Contact__c, it is used to ensure that no duplicate contact on an activity (does not allow duplicate)</description>
        <label>ActivityContact</label>
        <length>37</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ActivityId__c</fullName>
        <description>This fake Id field is binded to Task through the use of the "Contacts" Grid build in the GridBuddy application. It is populated by GB with Task.Id</description>
        <externalId>true</externalId>
        <label>ActivityId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is entered through the Gridbuddy Form and is set to the id of the contact entered through the form. It is used by the trigger to create the TaskRelation entry to the related Task</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Activity Contacts</relationshipLabel>
        <relationshipName>ActivityContacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <description>Each activity will have 1 to Many contacts. These activity related contacts are stored in this object along necessary attributes to allow for advanced activity reporting. This Table is synched up with the TaskRelation standard object through the "ActivityContactTrigger" trigger and the "ActivityContactTriggerHandler" Class.
This object is "virtually" related to Task through the use of the "ActivityId__c" field. This fake Id field is binded to Task through the use of the "Contacts" Grid build in the GridBuddy application.</description>
    <label>Activity Contact</label>
    <nameField>
        <displayFormat>AC-{0000000000}</displayFormat>
        <label>Activity Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Contacts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ActivityProduct__c.object
<CustomObject>
    <fields>
        <fullName>ActivityId__c</fullName>
        <externalId>true</externalId>
        <label>ActivityId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityProduct__c</fullName>
        <label>ActivityProduct</label>
        <length>37</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Activity Product</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Activity Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/NGAMSettingsHierarchy__c.object
<CustomObject>
    <fields>
        <fullName>ByPassAccountValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows entity to by-pass validation rules on Account</description>
        <inlineHelpText>Allows entity to by-pass validation rules on Account</inlineHelpText>
        <label>By-Pass Account Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CannotCUDActivityAfterDays__c</fullName>
        <description>Controls how many days after the activity date of a task or date of a corresponding activity contact or activity product a user can create, update, or delete an activity.  Used in trigger and validation rules.</description>
        <inlineHelpText>Controls how many days after the activity date of a task or date of a corresponding activity contact or activity product a user can create, update, or delete an activity.</inlineHelpText>
        <label>Cannot CUD Activity After Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NGAM Settings - Hierarchy</label>
</CustomObject>

classes/TaskTriggerHandler_Test.cls
@isTest
private class TaskTriggerHandler_Test {
    
    @testSetup
    static void testSetup() {
        insert new NGAMSettingsHierarchy__c(SetupOwnerId=UserInfo.getOrganizationId(), CannotCUDActivityAfterDays__c = 60);

        NGAMSettingsHierarchy__c hsettings = NGAMSettingsHierarchy__c.getOrgDefaults();
        hsettings.ByPassAccountValidationRules__c  = TRUE;
        hsettings.CannotCUDActivityAfterDays__c = 120;
        upsert hsettings NGAMSettingsHierarchy__c.Id;
        
    }
    
    static testMethod void myTest() {
    
        NGAMSettingsHierarchy__c hsettings = NGAMSettingsHierarchy__c.getOrgDefaults();
        
        Integer CannotCUDActivityAfterDays = (Integer)NGAMSettingsHierarchy__c.getInstance().CannotCUDActivityAfterDays__c;        
        Date cutOffDateForActivityChanges = Date.Today().addDays(-CannotCUDActivityAfterDays);
        
        List<Account> myAccounts = DataFactory.createTestAccounts(1);
        insert myAccounts;
        
        List<Contact> myContacts = DataFactory.createTestContacts(2, myAccounts, false) ;
        insert myContacts; 

        List<Product2> testProducts = DataFactory.createProduct2(2,'Test Prod');
        insert testProducts;

        List<Task> myTasks = DataFactory.createTestTasks(1,myContacts,'Call - Informative'); 
        insert myTasks;
        
            List<ActivityContact__c> myACs = new List<ActivityContact__c>();
            myACs.add(new ActivityContact__c(ActivityId__c = (String)myTasks[0].Id, Contact__c = myContacts[0].Id));
            myACs.add(new ActivityContact__c(ActivityId__c = (String)myTasks[0].Id, Contact__c = myContacts[1].Id));
            myACs.add(new ActivityContact__c(ActivityId__c = (String)myTasks[1].Id, Contact__c = myContacts[0].Id));
            myACs.add(new ActivityContact__c(ActivityId__c = (String)myTasks[1].Id, Contact__c = myContacts[1].Id));
        insert myACs;
                
        myTasks[1].ProductList__c = testProducts[0].Id;
        update myTasks[1];
        List<ActivityProduct__c> apCheck = [SELECT Id FROM ActivityProduct__c WHERE ActivityId__c =: myTasks[1].Id];
        system.AssertEquals(apCheck.size(),1,'Activity Product update with one product did not work');

        myTasks[1].ProductList__c = testProducts[0].Id + ';' + testProducts[1].Id;
        update myTasks[1];
        List<ActivityProduct__c> apCheck3 = [SELECT Id FROM ActivityProduct__c WHERE ActivityId__c =: myTasks[1].Id];
        system.AssertEquals(apCheck3.size(),2,'Activity Product update with two products did not work');

        delete myTasks[1];
        List<ActivityProduct__c> apCheck4 = [SELECT Id FROM ActivityProduct__c WHERE ActivityId__c =: myTasks[1].Id];
        system.AssertEquals(apCheck4.size(),0,'Activity Product delete did not work');
        
        undelete myTasks[1];
        List<ActivityProduct__c> apCheck5 = [SELECT Id FROM ActivityProduct__c WHERE ActivityId__c =: myTasks[1].Id];
        system.AssertEquals(apCheck5.size(),2,'Activity Product undelete did not work');        
        
        myTasks[1].ProductList__c = '';
        update myTasks[1];
        List<ActivityProduct__c> apCheck2 = [SELECT Id FROM ActivityProduct__c WHERE ActivityId__c =: myTasks[1].Id];
        system.AssertEquals(apCheck2.size(),0,'Activity Product update with no products did not work');
                      
    }
    
}