objects/Activity.object
<CustomObject>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>RunCampaignSharing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, campaign sharing will execute.  After campaign sharing has run, the checkbox is set to false.</description>
        <label>Run Campaign Sharing</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>ParentTerritory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Territories</relationshipLabel>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RoleGroupId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Role Group Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zone1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Zone 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ActivityTerritoryId__c</fullName>
        <description>Used To Tag the Activities and Opportunities created by the user.</description>
        <externalId>true</externalId>
        <inlineHelpText>READ ONLY FIELD : This Will be populated by the UserTerritory__c assignment when the Territory Assignment is tagged as an Activity Territory. Please never update this field directly. Instead Delete/Insert the relevant UserTerritory__c record.</inlineHelpText>
        <label>Activity Territory Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryParentId__c</fullName>
        <description>The Activity Territory's parent Id</description>
        <label>Activity Territory Parent Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryRoleGroupId__c</fullName>
        <description>The RoleGroupId from the activity territory's territory</description>
        <label>Activity Territory RoleGroupId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryType__c</fullName>
        <description>The type of territory for the Activity Territory</description>
        <label>Activity Territory Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/RunCampaignSharing.cls
public class RunCampaignSharing {
    
    @InvocableMethod(label='Run Campaign Sharing' description='Runs campaign sharing')
    public static void runCampaignSharing(List<Campaign> campaigns) {
        
        Set<Id> campaignIds = new Set<Id>();
        List<Campaign> setRunSharingFalse = new List<Campaign>();
        
        for (Campaign c: campaigns) {
            campaignIds.add(c.Id);
            setRunSharingFalse.add(new Campaign(Id=c.Id));
        }
        
        List<CampaignShare> sharesToDelete = [SELECT Id FROM CampaignShare WHERE CampaignId in :campaignIds AND RowCause = 'Manual'];
        delete sharesToDelete;
        
        List<CampaignShare> sharesToCreate = new List<CampaignShare>();
        Set<Id> ownerIds = new Set<Id>();
        
        for (Campaign c : campaigns) {
            ownerIds.add(c.OwnerId);
        }
        
        Map<Id,User> userMap = new Map<Id,User>([SELECT Id, ActivityTerritoryId__c, ActivityTerritoryRoleGroupId__c, ActivityTerritoryParentId__c, ActivityTerritoryType__c
                                                 FROM User
                                                 WHERE Id in: ownerIds]);
        
        for (Campaign sc: campaigns) {            
            if (userMap.containsKey(sc.OwnerId)) {
                if (userMap.get(sc.OwnerId).ActivityTerritoryRoleGroupId__c != null && userMap.get(sc.OwnerId).ActivityTerritoryRoleGroupId__c != '') {
                    sharesToCreate.add(new CampaignShare(CampaignId=sc.id, 
                                                         UserOrGroupId=userMap.get(sc.OwnerId).ActivityTerritoryRoleGroupId__c, 
                                                         CampaignAccessLevel='Edit', 
                                                         RowCause = 'Manual'));     
                }
            }
        }
        
        //When the owner's Activity Territory is a region, we need to share with all other territories under the region
        Set<Id> regionIdSet = new Set<Id>();
        
        for (User u : userMap.values()) {
            if (u.ActivityTerritoryType__c == 'Region') {
                regionIdSet.add(u.ActivityTerritoryId__c);
            }
        }
        
        Map<Id,Territory__c> childTerritoriesMap = new Map<Id,Territory__c>([SELECT Id, (SELECT Id, RoleGroupId__c FROM Territories__r) FROM Territory__c WHERE Id in :regionIdSet]);       
        
        for (Campaign scr : campaigns) {            
            for (Id i : childTerritoriesMap.keyset()) {               
                List<Territory__c> ct = childTerritoriesMap.get(i).Territories__r;                
                for (Territory__c cts : ct) {                    
                    sharesToCreate.add(new CampaignShare(CampaignId=scr.id, 
                                                         UserOrGroupId=cts.RoleGroupId__c, 
                                                         CampaignAccessLevel='Edit', 
                                                         RowCause = 'Manual'));     
                }
                
            }
        }      
        
        insert sharesToCreate; 
        
        for (Campaign c : setRunSharingFalse) {
            c.RunCampaignSharing__c = FALSE;
        }
        
        update setRunSharingFalse;
        
    }    
    
}