objects/Activity.object
<CustomObject>
    <fields>
        <fullName>ActivityId__c</fullName>
        <formula>CaseSafeId( Id )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ActivityId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityType__c</fullName>
        <description>Used to control the Sub Type field and not displayed in the UI. The out of box field Type is displayed in the UI.</description>
        <label>Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Meeting</fullName>
                </value>
                <value>
                    <fullName>Call</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
                <value>
                    <fullName>Transportation</fullName>
                </value>
                <value>
                    <fullName>Hotel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ActivityContact__c.object
<CustomObject>
    <fields>
        <fullName>ActivityContact__c</fullName>
        <description>This Field is populated by the trigger and contains ActivityId__c + Contact__c, it is used to ensure that no duplicate contact on an activity (does not allow duplicate)</description>
        <label>ActivityContact</label>
        <length>37</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ActivityId__c</fullName>
        <description>This fake Id field is binded to Task through the use of the "Contacts" Grid build in the GridBuddy application. It is populated by GB with Task.Id</description>
        <externalId>true</externalId>
        <label>ActivityId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityType__c</fullName>
        <description>Used to control the Sub Type field and not displayed in the UI. The out of box field Type is displayed in the UI.</description>
        <label>Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Meeting</fullName>
                </value>
                <value>
                    <fullName>Call</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For the Affiliate Request Process</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Activity Contacts</relationshipLabel>
        <relationshipName>Activity_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is entered through the Gridbuddy Form and is set to the id of the contact entered through the form. It is used by the trigger to create the TaskRelation entry to the related Task</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Activity Contacts</relationshipLabel>
        <relationshipName>ActivityContacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>This is populated by the trigger with Task.ActivityDate</description>
        <label>Activity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsEvent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To differentiate between the Task activity contact and event activity contact</description>
        <inlineHelpText>To differentiate between the Task activity contact and event activity contact</inlineHelpText>
        <label>IsEvent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <description>Each activity will have 1 to Many contacts. These activity related contacts are stored in this object along necessary attributes to allow for advanced activity reporting. This Table is synched up with the TaskRelation standard object through the "ActivityContactTrigger" trigger and the "ActivityContactTriggerHandler" Class.
This object is "virtually" related to Task through the use of the "ActivityId__c" field. This fake Id field is binded to Task through the use of the "Contacts" Grid build in the GridBuddy application.</description>
    <label>Activity Contact</label>
    <nameField>
        <displayFormat>AC-{0000000000}</displayFormat>
        <label>Activity Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Contacts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Source: MARS na_load_rep.StatCd
Loaded by a nightly job.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Affiliate</fullName>
        <active>true</active>
        <label>Affiliate</label>
    </recordTypes>
</CustomObject>

classes/EventRelationSyncBatch.cls
global class EventRelationSyncBatch implements Database.Batchable<sObject>, Database.Stateful{
    
    // This Batch job synchs up TaskRelation and ActivityContact__c
    // 
/*20190707 - No Longer Need this since using trigger on TaskRelationChangeEvent
    Public integer Count = 0;
    
    public static String affiliateRequestEventRecordTypeId = Schema.SObjectType.Event.getRecordTypeInfosByName().get('Affiliate Event').getRecordTypeId();
    public String query = 'select  Product__c,Type,id,ActivityType__c,Whoid,WhatId,EventWhoIds,Subject,ActivityDate,OwnerId,recordTypeID, (select id, RelationId,EventId from EventRelations where iswhat=false) from Event Where SystemModStamp >= LAST_N_DAYS:1';
    
    Public String msg = '';
    
    public Map<String, List<String>> m = new Map<String,  List<String>>(); */

	Public String query = 'SELECT Id from Event WHERE Id = null';
    
    global EventRelationSyncBatch() {
        System.Debug('EventRelation to ActivityContact__c');
    }
    
    
    global Database.QueryLocator start(Database.BatchableContext BC) {   
        
        System.Debug('Query - ' + query);
        return Database.getQueryLocator(query);
    }
    
    
    global void execute(Database.BatchableContext BC, List<Event> scope) {
/*20190707 - No Longer Need this since using trigger on TaskRelationChangeEvent
        // global void execute(List<Event> scope) {
        List<String> temp = new List<String>();     
        set<id> ActivityIds = new set<id>();
        set<id> ContactIds = new set<id>();
        
        for (Event tsk : scope)
        {
            ActivityIds.add(tsk.id); 
            temp.Add(tsk.id );
        } 
        // Create msg to add in the email
        msg = 'Activity Ids Count ' +  ActivityIds.size();
        m.put('Task-Activity Ids' , temp );  
        
        List<Event> TaskToUdpate = new List<Event>();       
        List<ActivityContact__c> newRElatedAC = new List<ActivityContact__c>();
        
        for (Event e : scope)
        {   
            if((e.recordTypeID == affiliateRequestEventRecordTypeId) 
               && ((e.Type=='Call') || (e.Type=='Meeting') ||(e.Type=='Onsite') ||(e.Type=='Webex'))) 
            {
                String ActivityType = EventTriggerHandler.FindContactActivity(e);
                for (EventRelation cTr : e.EventRelations) 
                {
                    ActivityContact__c ac = new ActivityContact__c();
                    ac.ActivityId__c = e.Id;
                    ac.ActivityType__c = ActivityType;
                    ac.Status__c = 'Completed';
                    ac.Subject__c = e.Subject;
                    ac.Type__c = e.Subject;
                    ac.Date__c = e.ActivityDate;
                    ac.Contact__c = (id)cTr.RelationId; 
                    if( ac.Contact__c == e.WhoId)ac.Primary__c=true;else ac.Primary__c=false;
                    ac.case__c = e.WhatId;
                    ac.IsEvent__c = true;
                    ContactIds.add(ac.Contact__c);               
                    newRElatedAC.add(ac); 
                    Count = Count + 1;
                }
            }
            
        }
        
        List<ActivityContact__c> ActivityContactsToDelete = [select id from ActivityContact__c where ActivityId__c in: ActivityIds]; 
        // Create msg to add in the email
        msg = msg + '   ActivityContactsToDelete Count : ' + ActivityContactsToDelete.size();
        List<String> ActivityContactsToDeleteList = new List<String>();
        for(ActivityContact__c ac: ActivityContactsToDelete){
            ActivityContactsToDeleteList.add(ac.Id);
        }
        m.put('ActivityContacts - Delete - ActivityContact Ids' , ActivityContactsToDeleteList );  
        
        
        if (ActivityContactsToDelete.size()>0)
        {
            delete ActivityContactsToDelete;
        }
        
        
        
        // Create msg to add in the email
        msg = msg + '   newRElatedAC Count: ' + newRElatedAC.size();
        List<String> newRElatedACList = new List<String>();
        for(ActivityContact__c ac: newRElatedAC){
            newRElatedACList.add(ac.ActivityId__c);
        }
        m.put('Contact Activity - Create - Activity Ids' , newRElatedACList );  
        
        if (newRElatedAC.size()>0)
        {
            insert newRElatedAC;
            //ActivityContactTriggerHandler.rollupCId(ContactIds);
        }  */
    }
    
    
    global void finish(Database.BatchableContext BC) {
    
    }
    
}