objects/Activity.object
<CustomObject>
    <fields>
        <fullName>ActivityId__c</fullName>
        <formula>CaseSafeId( Id )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ActivityId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivitySubType__c</fullName>
        <description>The dependent field on Type IC to drive value visibility</description>
        <inlineHelpText>Select a Type field to view valid Sub Types</inlineHelpText>
        <label>Activity Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ActivityType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Affiliate Request</fullName>
                </value>
                <value>
                    <fullName>Product/Promotional</fullName>
                </value>
                <value>
                    <fullName>Follow-Up/Service</fullName>
                </value>
                <value>
                    <fullName>Solutions</fullName>
                </value>
                <value>
                    <fullName>Roadshow</fullName>
                </value>
                <value>
                    <fullName>Other/Voicemail</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ActivityType__c</fullName>
        <description>Used to control the Sub Type field and not displayed in the UI. The out of box field Type is displayed in the UI.</description>
        <label>Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Meeting</fullName>
                </value>
                <value>
                    <fullName>Call</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
                <value>
                    <fullName>Transportation</fullName>
                </value>
                <value>
                    <fullName>Hotel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProductList__c</fullName>
        <description>A Semicolon Separated Group of Product Ids.</description>
        <inlineHelpText>A Semicolon Separated Group of Product Ids.</inlineHelpText>
        <label>Product List</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ActivityContact__c.object
<CustomObject>
    <fields>
        <fullName>ActivityContact__c</fullName>
        <description>This Field is populated by the trigger and contains ActivityId__c + Contact__c, it is used to ensure that no duplicate contact on an activity (does not allow duplicate)</description>
        <label>ActivityContact</label>
        <length>37</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ActivityId__c</fullName>
        <description>This fake Id field is binded to Task through the use of the "Contacts" Grid build in the GridBuddy application. It is populated by GB with Task.Id</description>
        <externalId>true</externalId>
        <label>ActivityId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityRelationId__c</fullName>
        <description>Either the TaskRelation Id or EventRelation Id that is associated with this row</description>
        <externalId>true</externalId>
        <label>Activity Relation Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivitySubType__c</fullName>
        <description>The dependent field on Type IC to drive value visibility , Copied from Task object  in insert trigger.</description>
        <label>Activity Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ActivityType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Product/Promotional</fullName>
                </value>
                <value>
                    <fullName>Follow-Up/Service</fullName>
                </value>
                <value>
                    <fullName>Solutions</fullName>
                </value>
                <value>
                    <fullName>Roadshow</fullName>
                </value>
                <value>
                    <fullName>Other/Voicemail</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ActivityType__c</fullName>
        <description>Used to control the Sub Type field and not displayed in the UI. The out of box field Type is displayed in the UI.</description>
        <label>Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Meeting</fullName>
                </value>
                <value>
                    <fullName>Call</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is entered through the Gridbuddy Form and is set to the id of the contact entered through the form. It is used by the trigger to create the TaskRelation entry to the related Task</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Activity Contacts</relationshipLabel>
        <relationshipName>ActivityContacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <description>Each activity will have 1 to Many contacts. These activity related contacts are stored in this object along necessary attributes to allow for advanced activity reporting. This Table is synched up with the TaskRelation standard object through the "ActivityContactTrigger" trigger and the "ActivityContactTriggerHandler" Class.
This object is "virtually" related to Task through the use of the "ActivityId__c" field. This fake Id field is binded to Task through the use of the "Contacts" Grid build in the GridBuddy application.</description>
    <label>Activity Contact</label>
    <nameField>
        <displayFormat>AC-{0000000000}</displayFormat>
        <label>Activity Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Contacts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ActivityProduct__c.object
<CustomObject>
    <fields>
        <fullName>ActivityId__c</fullName>
        <externalId>true</externalId>
        <label>ActivityId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityProduct__c</fullName>
        <label>ActivityProduct</label>
        <length>37</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ActivityRelationId__c</fullName>
        <description>The TaskRelation or EventRelation that is associated with this row</description>
        <label>Activity Relation Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivitySubType__c</fullName>
        <label>Activity SubType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Affiliate Request</fullName>
                </value>
                <value>
                    <fullName>Product/Promotional</fullName>
                </value>
                <value>
                    <fullName>Follow-Up/Service</fullName>
                </value>
                <value>
                    <fullName>Solutions</fullName>
                </value>
                <value>
                    <fullName>Roadshow</fullName>
                </value>
                <value>
                    <fullName>Other/Voicemail</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ActivityType__c</fullName>
        <label>Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Call</fullName>
                </value>
                <value>
                    <fullName>Meeting</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Product2.ProductVisible__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Activity Products</relationshipLabel>
        <relationshipName>Activity_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Activity Product</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Activity Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/NGAMSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Holds the NGAM settings</description>
    <label>NGAM Settings</label>
</CustomObject>

objects/NGAMSettingsHierarchy__c.object
<CustomObject>
    <fields>
        <fullName>ByPassAccountValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows entity to by-pass validation rules on Account</description>
        <inlineHelpText>Allows entity to by-pass validation rules on Account</inlineHelpText>
        <label>By-Pass Account Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CannotCUDActivityAfterDays__c</fullName>
        <description>Controls how many days after the activity date of a task or date of a corresponding activity contact or activity product a user can create, update, or delete an activity.  Used in trigger and validation rules.</description>
        <inlineHelpText>Controls how many days after the activity date of a task or date of a corresponding activity contact or activity product a user can create, update, or delete an activity.</inlineHelpText>
        <label>Cannot CUD Activity After Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NGAM Settings - Hierarchy</label>
</CustomObject>

classes/LEXTaskBatchTest.cls
@isTest
private class LEXTaskBatchTest {
    
    @testSetup
    static void testSetup() {
        insert new NGAMSettingsHierarchy__c(SetupOwnerId=UserInfo.getOrganizationId(), CannotCUDActivityAfterDays__c = 60);
        
        NGAMSettingsHierarchy__c hsettings = NGAMSettingsHierarchy__c.getOrgDefaults();
        hsettings.ByPassAccountValidationRules__c  = TRUE;
        hsettings.CannotCUDActivityAfterDays__c = 120;
        upsert hsettings NGAMSettingsHierarchy__c.Id;
        
        LEXConversionContext.runningConversion = TRUE;
        
        //insert new NGAMSettings__c(Name='NGAM_ALL', RunningLEXConversion__c = TRUE);
        
    }
    
    static testMethod void myTest() {
        
        NGAMSettingsHierarchy__c hsettings = NGAMSettingsHierarchy__c.getOrgDefaults();
        
        Integer CannotCUDActivityAfterDays = (Integer)NGAMSettingsHierarchy__c.getInstance().CannotCUDActivityAfterDays__c;        
        Date cutOffDateForActivityChanges = Date.Today().addDays(-CannotCUDActivityAfterDays);
        
        List<Account> myAccounts = DataFactory.createTestAccounts(1);
        insert myAccounts;
        
        List<Contact> myContacts = DataFactory.createTestContacts(2, myAccounts, false) ;
        insert myContacts; 
        
        List<Product2> testProducts = DataFactory.createProduct2(3,'Test Prod');
        insert testProducts;
        
        List<Task> myTasks = DataFactory.createTestTasks(4,myContacts,'Call - Informative'); 
        myTasks[0].ActivityType__c = 'Call - Informative';
        myTasks[1].ActivityType__c = 'Follow Up';
        myTasks[1].ActivitySubType__c = 'Email Follow Up';
        insert myTasks;
        
        List<ActivityProduct__c> myAPs = new List<ActivityProduct__c>();
        myAPs.add(new ActivityProduct__c(ActivityId__c = (String)myTasks[1].Id, Product__c = testProducts[0].Id));
        myAPs.add(new ActivityProduct__c(ActivityId__c = (String)myTasks[2].Id, Product__c = testProducts[0].Id));
        myAPs.add(new ActivityProduct__c(ActivityId__c = (String)myTasks[2].Id, Product__c = testProducts[1].Id));
        insert myAPs;

        List<ActivityContact__c> myACs = new List<ActivityContact__c>();
        myACs.add(new ActivityContact__c(ActivityId__c = (String)myTasks[0].Id, Contact__c = myContacts[0].Id));
        myACs.add(new ActivityContact__c(ActivityId__c = (String)myTasks[0].Id, Contact__c = myContacts[1].Id));
        myACs.add(new ActivityContact__c(ActivityId__c = (String)myTasks[1].Id, Contact__c = myContacts[0].Id));
        myACs.add(new ActivityContact__c(ActivityId__c = (String)myTasks[1].Id, Contact__c = myContacts[1].Id));
        insert myACs;

        Test.startTest();
        LEXTaskBatch LTB = new LEXTaskBatch();
        LTB.whereCriteria = '';    
        Id LTBId = database.executeBatch(LTB);     
        Test.stopTest();
        
        for (Task t : [SELECT Id, ProductList__c, Type, ActivityType__c, ActivitySubType__c FROM Task]) {
            if (t.Id == myTasks[0].Id) system.assertEquals('Call', t.Type, 'Type should be Call');
            if (t.Id == myTasks[0].Id) system.assertEquals('Call', t.ActivityType__c, 'Type should be Call');            
            if (t.Id == myTasks[0].Id) system.assertEquals('Product/Promotional', t.ActivitySubType__c, 'Type should be Product/Promotional');                        
            if (t.Id == myTasks[1].Id) system.assertEquals('Email', t.Type, 'Type should be Email');
            if (t.Id == myTasks[1].Id) system.assertEquals('Email', t.ActivityType__c, 'Type should be Email');            
            if (t.Id == myTasks[1].Id) system.assertEquals('Follow-Up/Service', t.ActivitySubType__c, 'Type should be Follow-Up/Service');                        
            
            if (t.Id == myTasks[0].Id) system.assertEquals(null, t.ProductList__c, 'ProductList__c should be null - no activity products');
            if (t.Id == myTasks[1].Id) system.assertEquals(testProducts[0].Id, t.ProductList__c, 'ProductList__c should have one item with correct product');            
            if (t.Id == myTasks[2].Id) system.assertEquals(testProducts[0].Id + ';' + testProducts[1].Id, t.ProductList__c, 'ProductList__c should have two items with correct products');            
            if (t.Id == myTasks[3].Id) system.assertEquals(null, t.ProductList__c, 'ProductList__c should have been set to null - no activity products'); 
            
        }
        
        Map<Id,TaskRelation> taskRelationMap = new Map<Id,TaskRelation>([SELECT Id, TaskId, RelationId
                                FROM TaskRelation
                                WHERE TaskId IN :myTasks
                                AND RelationId IN :myContacts]);
        
        for (ActivityContact__c ac : [SELECT Id, ActivityId__c, ActivityRelationId__c, Contact__c FROM ActivityContact__c]) {
            system.debug(ac.ActivityRelationId__c + ' ' + ac.ActivityId__c + ' ' + ac.Contact__c);
            if (ac.ActivityRelationId__c != null) { 
            Id relId = taskRelationMap.get(ac.ActivityRelationId__c).RelationId;
            system.assert(ac.Contact__c == relId,'Activity Contact and Task Relation out-of-sync; ActivityContact__c Id: ' + ac.Id);
            }
        }
        
    }
    
}