objects/ActivityContact__c.object
<CustomObject>
    <fields>
        <fullName>ActivityComments__c</fullName>
        <description>This is populated by the trigger as the first 255 characters of the Task.Description field</description>
        <label>Activity Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ActivityContact__c</fullName>
        <description>This Field is populated by the trigger and contains ActivityId__c + Contact__c, it is used to ensure that no duplicate contact on an activity (does not allow duplicate)</description>
        <label>ActivityContact</label>
        <length>37</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ActivityId__c</fullName>
        <description>This fake Id field is binded to Task through the use of the "Contacts" Grid build in the GridBuddy application. It is populated by GB with Task.Id</description>
        <externalId>true</externalId>
        <label>ActivityId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is entered through the Gridbuddy Form and is set to the id of the contact entered through the form. It is used by the trigger to create the TaskRelation entry to the related Task</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Activity Contacts</relationshipLabel>
        <relationshipName>ActivityContacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <description>Each activity will have 1 to Many contacts. These activity related contacts are stored in this object along necessary attributes to allow for advanced activity reporting. This Table is synched up with the TaskRelation standard object through the "ActivityContactTrigger" trigger and the "ActivityContactTriggerHandler" Class.
This object is "virtually" related to Task through the use of the "ActivityId__c" field. This fake Id field is binded to Task through the use of the "Contacts" Grid build in the GridBuddy application.</description>
    <label>Activity Contact</label>
    <nameField>
        <displayFormat>AC-{0000000000}</displayFormat>
        <label>Activity Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Contacts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ActivityProduct__c.object
<CustomObject>
    <fields>
        <fullName>ActivityComments__c</fullName>
        <description>The shortened version of the Description from the parent Task</description>
        <label>Activity Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ActivityId__c</fullName>
        <externalId>true</externalId>
        <label>ActivityId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityProduct__c</fullName>
        <label>ActivityProduct</label>
        <length>37</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Product2.ProductVisible__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Activity Products</relationshipLabel>
        <relationshipName>Activity_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Activity Product</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Activity Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/NGAMSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Holds the NGAM settings</description>
    <label>NGAM Settings</label>
</CustomObject>

classes/TaskTriggerHandler.cls
public class TaskTriggerHandler {
    
    //public static Boolean runningLEXConversion = NGAMSettings__c.getValues('NGAM_ALL').RunningLEXConversion__c;
    public static Boolean runningLEXConversion = LEXConversionContext.runningConversion == null ? FALSE : LEXConversionContext.runningConversion;
    
    public static void taskFieldsPreset(List<Task> myTasks, Map<Id,Task> taskMap){
        
        if (runningLEXConversion != TRUE) {
        if (trigger.IsUpdate) myTasks = taskMap.values();
        
        Id pardotUserId;
        Map<Id,User> userMap = Util.getUserTerritoryMap();
        for (User u : userMap.values()) {
            if (u.Username.startsWith('pnatixis')) pardotUserId = u.Id;
        }
        
        Map<Id, ActivityContact__c> activityContactMap = new Map<Id, ActivityContact__c>();
        
        if (trigger.IsUpdate) activityContactMap = UtilActivity.getActivityContactMap(taskMap);
        
        Set<Id> contactIdSet = new Set<Id>();
        for (ActivityContact__c ac : activityContactMap.values()) {
            contactIdSet.add(ac.Contact__c);
        }
        
        Map<Id,Contact> contactMap = UtilActivity.getContactPrimaryTerritoryMap(contactIdSet);

        Map<Id, Product2> productMap = UtilActivity.getProductMapFromProductList(myTasks);
        system.debug('productMap: ' + productMap);

        system.debug('Number of Tasks coming in: ' + myTasks.size());
        
        for (Task eachTask : myTasks) {
            system.debug('-- Start new Task Iteration in TaskFieldsPreset');
            system.debug('---- Owner: ' + eachTask.OwnerId);
            system.debug('---- Subject: ' + eachTask.Subject);
            system.debug('---- Type: ' + eachTask.Type);
            system.debug('---- WhoId: ' + eachTask.WhoId);
            system.debug('---- WhatId: ' + eachTask.WhatId);
            system.debug('---- WhoCount: ' + eachTask.WhoCount);
            system.debug('---- Description: ' + eachTask.Description);
            
            eachTask = UtilActivity.setUserFields(eachTask, userMap);
            eachTask = UtilActivity.syncWhatIdToLookupFields(eachTask);
            eachTask.Status = eachTask.Status == null ? 'Completed' : eachTask.Status;
            eachTask.ActivityComments__c = String.isBlank(eachTask.Description) ? null : eachTask.Description.left(255).trim();
            eachTask.ActivityDateProxy__c = eachTask.ActivityDate;
            eachTask = UtilActivity.getTaskTypeSubtype(eachTask);
            system.debug('ProductList__c: ' + eachTask.ProductList__c);
            eachTask.Products__c = UtilActivity.convertProductListToProducts(eachTask.ProductList__c, productMap);
            
        }
        }

        myTasks = UtilActivity.setActivityPoints(myTasks);

    }
    
    /*    public static void updateTotalActivityPoints(List<Task> myTasks) {
List<Task> tasksToUpdateTotActPnts = UtilActivity.calculateTotalActivityPoints(myTasks);
update tasksToUpdateTotActPnts;
}*/
    
    public static void TaskTriggerBeforeUpdate(List<Task> myTasks, Map<Id,Task> taskMap){
        taskFieldsPreset(myTasks, taskMap);
    }
    
    public static void TaskTriggerBeforeInsert(List<Task> myTasks, Map<Id,Task> taskMap){
        taskFieldsPreset(myTasks, taskMap); 
    }    
    
    public static void syncActivityProducts(List<Task> myNewTasks, Map<Id,Task> myNewTaskMap, Map<Id,Task> myOldTaskMap) {
        
        if (!runningLEXConversion) {
        
        Map<Id, ActivityProduct__c> activityProductOldMap = new Map<Id, ActivityProduct__c>();
        if (trigger.isUpdate) activityProductOldMap = UtilActivity.getActivityProductMap(myNewTaskMap);
        Map<Id, ActivityContact__c> activityContactMap = UtilActivity.getActivityContactMap(myNewTaskMap);
        
        Map<String, ActivityProduct__c> activityProductOldStringMap = new Map<String, ActivityProduct__c>();
        Map<String, ActivityProduct__c> activityProductNewStringMap = new Map<String, ActivityProduct__c>();
        List<ActivityProduct__c> activityProductToDelete = new List<ActivityProduct__c>();
        Map<String, ActivityProduct__c> activityProductToUpsertStringMap = new Map<String, ActivityProduct__c>();
        Set<Id> activityProductToDeletebyTaskIdSet = new Set<Id>();
        
        for (ActivityProduct__c ap : activityProductOldMap.values()) {
            activityProductOldStringMap.put(ap.ActivityId__c + (String)ap.Product__c, ap);
        }
        
        for (Task t : myNewTasks) {
            
            if ((Trigger.isInsert && t.ProductList__c != null) ||
                (Trigger.isUnDelete && t.ProductList__c != null) ||
                (Trigger.isUpdate && t.ProductList__c != myOldTaskMap.get(t.Id).ProductList__c)) {
                    
                    List<String> products =new List<String>();
                    if (t.ProductList__c != null) {
                        
                        products = t.ProductList__c.split(';');
                        
                        for (String product : products) {
                            
                            ActivityProduct__c ap = new ActivityProduct__c();
                            
                            String activityProductString = (String)t.Id + product;
                            
                            if (activityProductOldStringMap.containsKey(activityProductString)) {
                                ap = activityProductOldStringMap.get(activityProductString);
                                ap.Product__c = product;
                                ap = UtilActivity.activityProductFieldPreset(ap,t);
                                activityProductToUpsertStringMap.put(activityProductString, ap);
                            } else {
                                ap.Product__c = product;
                                ap = UtilActivity.activityProductFieldPreset(ap,t);
                                activityProductToUpsertStringMap.put(activityProductString, ap);
                            }
                            
                        }
                        
                        for (String aps : activityProductOldStringMap.keySet()) {
                            
                            if (!activityProductToUpsertStringMap.containsKey(aps)) {
                                activityProductToDelete.add(activityProductOldStringMap.get(aps));
                            }
                            
                        }
                        
                        
                    } else {
                        
                        activityProductToDeletebyTaskIdSet.add(t.Id);
                        
                    }
                }
        }
        
        for (ActivityProduct__c ap : [SELECT Id from ActivityProduct__c WHERE ActivityId__c IN: activityProductToDeletebyTaskIdSet]) {
            activityProductToDelete.add(ap);
        }
        
        upsert activityProductToUpsertStringMap.values();
        delete activityProductToDelete;
        }
        
    }
    
    public static void syncActivityContacts(List<Task> myNewTasks, Map<Id,Task> myNewTaskMap, Map<Id,Task> myOldTaskMap) {
        
        Map<Id, ActivityContact__c> activityContactMap = UtilActivity.getActivityContactMap(myNewTaskMap);
        List<ActivityContact__c> activityContactToUpdate = new List<ActivityContact__c>();
        
        Map<String, List<ActivityContact__c>> activityContactToUpdateMap = new Map<String, List<ActivityContact__c>>();
        
        for (ActivityContact__c ac : activityContactMap.values()) {
            if (activityContactToUpdateMap.containsKey(ac.ActivityId__c)) {
                List<ActivityContact__c> tempAC = activityContactToUpdateMap.get(ac.ActivityId__c);
                tempAC.add(ac);
                activityContactToUpdateMap.put(ac.ActivityId__c, tempAC);
            } else {
                List<ActivityContact__c> tempAC = new List<ActivityContact__c>();
                tempAC.add(ac);
                activityContactToUpdateMap.put(ac.ActivityId__c, tempAC);
            }
        }
        
        for (Task t : myNewTasks) {
            
            if (activityContactToUpdateMap.containsKey(t.Id)) {
                List<ActivityContact__c> acList = activityContactToUpdateMap.get(t.Id);
                
                for (ActivityContact__c ac : acList) {
                    if (ac.ActivityId__c.startsWith('00T')) ac = UtilActivity.activityContactTaskFieldPreset(ac, t);
                    activityContactToUpdate.add(ac);
                }
            }
        }
        
        update activityContactToUpdate;
        
    }    
    
    public static void TaskTriggerAfterDelete(Map<Id,Task> myOldTaskMap) {
        
        delete [SELECT Id from ActivityContact__c WHERE ActivityId__c IN :myOldTaskMap.keySet()];
        delete [SELECT Id from ActivityProduct__c WHERE ActivityId__c IN :myOldTaskMap.keySet()];
        
    }   
    
}