objects/Activity.object
<CustomObject>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zone__c</fullName>
        <label>Zone</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Channel__c.object
<CustomObject>
    <fields>
        <fullName>DefaultProfileId__c</fullName>
        <externalId>true</externalId>
        <label>Default Profile Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Channel</label>
        <referenceTo>Channel__c</referenceTo>
        <relationshipLabel>Territories</relationshipLabel>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ParentTerritory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Territories</relationshipLabel>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RoleGroupId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Role Group Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RoleId__c</fullName>
        <externalId>true</externalId>
        <label>Role Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TerritoryName__c</fullName>
        <defaultValue>"Update Me"</defaultValue>
        <externalId>true</externalId>
        <label>MARS Territory Name</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TerritoryType__c</fullName>
        <label>Territory Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Territory</fullName>
                </value>
                <value>
                    <fullName>Region</fullName>
                </value>
                <value>
                    <fullName>Department</fullName>
                </value>
                <value>
                    <fullName>Division</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ActivityChannelId__c</fullName>
        <description>Used To Tag the Activities and Opportunities created by the user.</description>
        <externalId>true</externalId>
        <inlineHelpText>READ ONLY FIELD : This Will be populated by the UserTerritory__c assignment when the Territory Assignment is tagged as an Activity Territory. Please never update this field directly. Instead Delete/Insert the relevant UserTerritory__c record.</inlineHelpText>
        <label>Activity Channel Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityChannelName__c</fullName>
        <description>Used To Tag the Activities and Opportunities created by the user.</description>
        <inlineHelpText>READ ONLY FIELD : This Will be populated by the UserTerritory__c assignment when the Territory Assignment is tagged as an Activity Territory. Please never update this field directly. Instead Delete/Insert the relevant UserTerritory__c record.</inlineHelpText>
        <label>Activity Channel Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryId__c</fullName>
        <description>Used To Tag the Activities and Opportunities created by the user.</description>
        <externalId>true</externalId>
        <inlineHelpText>READ ONLY FIELD : This Will be populated by the UserTerritory__c assignment when the Territory Assignment is tagged as an Activity Territory. Please never update this field directly. Instead Delete/Insert the relevant UserTerritory__c record.</inlineHelpText>
        <label>Activity Territory Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryMARSName__c</fullName>
        <description>The MARS Name of the Activity Territory (Territory__c.TerritoryName__c)</description>
        <label>Activity Territory MARS Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryName__c</fullName>
        <description>Used To Tag the Activities and Opportunities created by the user.</description>
        <inlineHelpText>READ ONLY FIELD : This Will be populated by the UserTerritory__c assignment when the Territory Assignment is tagged as an Activity Territory. Please never update this field directly. Instead Delete/Insert the relevant UserTerritory__c record.</inlineHelpText>
        <label>Activity Territory Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryParentId__c</fullName>
        <description>The Activity Territory's parent Id</description>
        <label>Activity Territory Parent Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryParentMARSName__c</fullName>
        <description>The activity territory's parent's MARS Name</description>
        <label>Activity Territory Parent MARS Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryParentName__c</fullName>
        <description>The Activity Territory's parent's Name</description>
        <label>Activity Territory Parent Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryParentType__c</fullName>
        <description>Activity Territory's Parent Type</description>
        <label>Activity Territory Parent Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryRoleGroupId__c</fullName>
        <description>The RoleGroupId from the activity territory's territory</description>
        <label>Activity Territory RoleGroupId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryRoleId__c</fullName>
        <description>The role Id from the user's activity territory</description>
        <label>Activity Territory RoleId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryType__c</fullName>
        <description>The type of territory for the Activity Territory</description>
        <label>Activity Territory Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityZoneId__c</fullName>
        <description>Used To Tag the Activities and Opportunities created by the user.</description>
        <inlineHelpText>READ ONLY FIELD : This Will be populated by the UserTerritory__c assignment when the Territory Assignment is tagged as an Activity Territory. Please never update this field directly. Instead Delete/Insert the relevant UserTerritory__c record.</inlineHelpText>
        <label>Activity Zone Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DefaultTerritoryMARSName__c</fullName>
        <description>The Default Territory's MARS Name (Territory__c.TerritoryName__c)</description>
        <label>Default Territory MARS Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DefaultTerritory__c</fullName>
        <description>Used by Literature fulfillment application.</description>
        <inlineHelpText>Used by Literature fulfillment application.</inlineHelpText>
        <label>Default Territory</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryChannelId__c</fullName>
        <label>Primary Channel Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryChannel__c</fullName>
        <label>Primary Channel</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryTerritoryId__c</fullName>
        <externalId>true</externalId>
        <label>PrimaryTerritoryId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryTerritory__c</fullName>
        <label>Primary Territory</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProxyProfileId__c</fullName>
        <externalId>true</externalId>
        <label>ProxyProfileId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RoleProxy__c</fullName>
        <label>RoleProxy</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZoneID__c</fullName>
        <externalId>true</externalId>
        <label>Zone ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZoneLabel__c</fullName>
        <label>Zone Label</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZoneNumber__c</fullName>
        <label>Zone Number</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/UserTerritory__c.object
<CustomObject>
    <fields>
        <fullName>ActivityTerritory__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activity Territory</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PrimaryTerritory__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Territory</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RoleId__c</fullName>
        <formula>Territory__r.RoleId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Role Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TerrGroupId__c</fullName>
        <formula>Territory__r.GroupId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TerrGroupId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TerritoryName__c</fullName>
        <formula>Territory__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Territory Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TerritoryType__c</fullName>
        <formula>TEXT(Territory__r.TerritoryType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Territory Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>User Territories</relationshipLabel>
        <relationshipName>User_Territories1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Territories1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zoning__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Zone</label>
        <referenceTo>Zone__c</referenceTo>
        <relationshipLabel>User Territories</relationshipLabel>
        <relationshipName>User_Territories</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>User Territory</label>
    <nameField>
        <displayFormat>UT-{00000000}</displayFormat>
        <label>User Territory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Zone__c.object
<CustomObject>
    <fields>
        <fullName>Zone__c</fullName>
        <externalId>true</externalId>
        <label>Zone</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UserTerritoryTriggerHandler.cls
public class UserTerritoryTriggerHandler {
    
    public static boolean run = true;
    
    public static boolean runOnce(){
    	if(run)
        	{
     		run=false;
     		return true;
    		}else{
        return run;
    	}
    }

    
    public static void UserTerritoryAfterDelete (List<UserTerritory__c> myUserTerrs){
            List<User> UsersToUpdate = new List<User>();
            
            Map <String,id> AllGrpMember = new Map<String,id>();   
                
            for(UserTerritory__c currUserTerr : myUserTerrs)   
                {       
                if(currUserTerr.PrimaryTerritory__c)   
                    	{
                    	User usr = new User(Id=currUserTerr.user__c,RoleProxy__c=null, ZoneLabel__c= '',ZoneNumber__c= null, Zoneid__c = '',PrimaryTerritory__c='', PrimaryTerritoryId__c='', PrimaryChannel__c='', PrimaryChannelid__c='');   
                    	if(currUserTerr.ActivityTerritory__c)
                        	{
                            usr.ActivityChannelId__c = '';
                            usr.DefaultTerritory__c= '';
                            usr.ActivityChannelName__c ='';
                            usr.ActivityTerritoryId__c ='';
                            usr.ActivityTerritoryName__c ='';
                            usr.ActivityZoneId__c ='';
                            usr.ActivityTerritoryMARSName__c ='';    
                            usr.DefaultTerritoryMARSName__c = '';  
                            usr.ActivityTerritoryType__c = '';
                            usr.ActivityTerritoryParentId__c = '';
                            usr.ActivityTerritoryParentMARSName__c = '';
                            usr.ActivityTerritoryParentName__c = '';    
                            usr.ActivityTerritoryParentType__c = '';
                            usr.ActivityTerritoryRoleId__c = '';    
                            usr.ActivityTerritoryRoleGroupId__c = '';    
                        	}
                        UsersToUpdate.add(usr);
                        }   
                }
        
            if (!UsersToUpdate.isEmpty())
                {
 				update UsersToUpdate;
                }
            }
    
    
    public static void UserTerritoryAfterUpdate (List<UserTerritory__c> myUserTerrs){
        	// Only Primary Territory checkbox can be updated on a UserTerritory__c
   			if(runOnce())
            	{ 
                Set<id> PrimaryUserTerritories = new Set<id>();
                Set<id> UsersWithPrimaryTerritories = new Set<id>();
                List<UserTerritory__c> UserTerritoriesNotPrimaryAnymore = new List<UserTerritory__c>();
                List<User> UsersToUpdate = new List<User>();
            
                for (UserTerritory__c currUserTerr : [select id, 
															ownerid, 
                                                      		RoleId__c, 
                                                      		Territory__r.Channel__r.DefaultProfileId__c, 
                                                      		Zoning__c, 
                                                      		Zoning__r.Name, 
                                                      		Zoning__r.zone__c,
                                                      		Territory__r.name,
                                                      		Territory__c,
                                                      		Territory__r.Channel__r.name,
                                                      		Territory__r.Channel__r.id
                                                      		from UserTerritory__c where id in: myUserTerrs and PrimaryTerritory__c=true])
                    {
                    //system.debug('DEBUG ME------------------' + currUserTerr.Territory__r.name + ' ' + currUserTerr.Territory__c + ' ' + currUserTerr.Territory__r.Channel__r.name + ' ' + currUserTerr.Territory__r.Channel__r.id) ; 
                    
                    PrimaryUserTerritories.add(currUserTerr.id);
                    UsersWithPrimaryTerritories.add(currUserTerr.ownerid);
                    User usr = new User(	Id=currUserTerr.ownerid, 
                                        	RoleProxy__c=currUserTerr.RoleId__c, 
                                        	ProxyProfileId__c = currUserTerr.Territory__r.Channel__r.DefaultProfileId__c, 
                                        	ZoneID__c = currUserTerr.Zoning__c,
                                        	ZoneLabel__c= currUserTerr.Zoning__r.Name, 
                                        	ZoneNumber__c= currUserTerr.Zoning__r.zone__c, 
                                        	PrimaryTerritory__c=currUserTerr.Territory__r.name,
                                        	PrimaryTerritoryId__c=currUserTerr.Territory__c,
                                        	PrimaryChannel__c=currUserTerr.Territory__r.Channel__r.name,
                                        	PrimaryChannelid__c=currUserTerr.Territory__r.Channel__r.id);   
                    UsersToUpdate.add(usr);
                    }
            
                for (UserTerritory__c myUserTerritory : [select id from UserTerritory__c where ownerid in : UsersWithPrimaryTerritories and id not in:PrimaryUserTerritories and PrimaryTerritory__c=true])
                    {
                    UserTerritoriesNotPrimaryAnymore.add(new UserTerritory__c(id=myUserTerritory.id, PrimaryTerritory__c=false));
                    }
            
                if (!UserTerritoriesNotPrimaryAnymore.isEmpty())
                    {
                    update UserTerritoriesNotPrimaryAnymore;
                    } 
                if (!UsersToUpdate.isEmpty())
                    {
                    update UsersToUpdate;
                    } 
                    
                }
    }
    
    public static void UserTerritoryBeforeInsert (List<UserTerritory__c> myUserTerrs){
		for(UserTerritory__c currUserTerr : myUserTerrs)
       	 	{
            // Making Sure ownerid and user__c are same
			currUserTerr.ownerid=currUserTerr.user__c;  
            currUserTerr.PrimaryTerritory__c = currUserTerr.ActivityTerritory__c;
            }
    	}
        
    //-----------------------------------------------------------------------------------------------------------------------------------------------
    // After Inserting UserTerritory__c
    // If inserting where ActivityTerritory__c  = true, then assumption is that PrimaryTerritory__c = true as well.
    // Will grab all the UserTerritory__c where ActivityTerritory__c=false to unprime them
	//-----------------------------------------------------------------------------------------------------------------------------------------------
    public static void UserTerritoryAfterInsert (List<UserTerritory__c> myUserTerrs){
        List<User> UsersToUpdate = new List<User>();
        Set<id> UserIds = new Set<id>();
        
        for(UserTerritory__c currUserTerr : [select id, Territory__r.RoleGroupId__c, 
                                             ActivityTerritory__c,Territory__r.ParentTerritory__r.TerritoryType__c,
                                             Territory__r.ParentTerritory__c,Territory__r.ParentTerritory__r.Name,
                                             Territory__r.ParentTerritory__r.TerritoryName__c,name, user__c, 
                                             territory__c, Territory__r.RoleId__c,Territory__r.TerritoryType__c,
                                             RoleId__c, Territory__r.TerritoryName__c, Territory__r.Channel__r.DefaultProfileId__c, 
                                             TerrGroupId__c, PrimaryTerritory__c, Zoning__c, Territory__r.name, 
                                             Territory__r.Channel__r.name, Territory__r.Channel__r.id, ownerid, 
                                             Zoning__r.Name,Zoning__r.zone__c  from UserTerritory__c where id in: myUserTerrs])
        	{
            if(currUserTerr.ActivityTerritory__c)   
        		{
                UserIds.add(currUserTerr.user__c);
                //system.debug('currUserTerr.user__c' + currUserTerr.user__c);
                User usr = new User(Id=currUserTerr.user__c,
                                    RoleProxy__c=currUserTerr.RoleId__c,
                                    ProxyProfileId__c = currUserTerr.Territory__r.Channel__r.DefaultProfileId__c,
                                    ZoneID__c = currUserTerr.Zoning__c,
                                    ZoneLabel__c= currUserTerr.Zoning__r.Name,
                                    ZoneNumber__c= currUserTerr.Zoning__r.zone__c,
                                    PrimaryTerritory__c=currUserTerr.Name,
                                    PrimaryTerritoryId__c=currUserTerr.Territory__c,
                                    PrimaryChannel__c=currUserTerr.Territory__r.Channel__r.name,
                                    PrimaryChannelid__c=currUserTerr.Territory__r.Channel__r.id,
                                    DefaultTerritory__c = currUserTerr.Territory__r.Name,
                                    DefaultTerritoryMARSName__c = currUserTerr.Territory__r.TerritoryName__c,
                    				ActivityChannelId__c = currUserTerr.Territory__r.Channel__r.id,
                    				ActivityChannelName__c = currUserTerr.Territory__r.Channel__r.name,
                    				ActivityTerritoryId__c = currUserTerr.Territory__c,
                    				ActivityTerritoryName__c = currUserTerr.Territory__r.Name,
                                    ActivityTerritoryMARSName__c = currUserTerr.Territory__r.TerritoryName__c,
                                    ActivityTerritoryType__c = currUserTerr.Territory__r.TerritoryType__c,
                    				ActivityZoneId__c = currUserTerr.Zoning__c,
                                    ActivityTerritoryParentId__c = currUserTerr.Territory__r.ParentTerritory__c,
                            		ActivityTerritoryParentMARSName__c = currUserTerr.Territory__r.ParentTerritory__r.TerritoryName__c,
                            		ActivityTerritoryParentName__c = currUserTerr.Territory__r.ParentTerritory__r.Name,    
                            		ActivityTerritoryParentType__c = currUserTerr.Territory__r.ParentTerritory__r.TerritoryType__c,
                    				ActivityTerritoryRoleGroupId__c = currUserTerr.Territory__r.RoleGroupId__c,
                    				ActivityTerritoryRoleId__c = currUserTerr.Territory__r.RoleId__c);
                    			
                    
                UsersToUpdate.add(usr);
                }
            }
        
        if (!UsersToUpdate.isEmpty())
        	{ 
            //system.debug ('Came here');
            update UsersToUpdate;
        	}
        
        
        // This will grab all the UserTerritory__c where ActivityTerritory__c=false to unprime them
        List<UserTerritory__c> UserTerritoryToUnprime = new List<UserTerritory__c>([select id from UserTerritory__c where ActivityTerritory__c=false and User__c in: UserIds]);
        
        List<UserTerritory__c> ut = new List<UserTerritory__c>();
        
        for (UserTerritory__c curUserTerr : UserTerritoryToUnprime)
        	{
            ut.add(new UserTerritory__c(id=curUserTerr.id,ActivityTerritory__c=false,PrimaryTerritory__c=false));
        	}
        //This will update the UserTerritory__c records @future, allowing to get out of the runtime context.
		//system.debug('ut.size()' + ut.size());
        Async.updateSObjects(Async.prepare(ut));

    	}
    

    /*

    public static void UserTerritoryAfterInsert (List<UserTerritory__c> myUserTerrs){
   			if(runOnce())
                {   
                List<User> UsersToUpdate = new List<User>();
                List<UserTerritory__c> UserTerrToUpdate = new List<UserTerritory__c>();
                //List<GroupMember> MemberstoCreate = new List<GroupMember>();
                       
                for(UserTerritory__c currUserTerr : [select id, ActivityTerritory__c,name, user__c, territory__c, RoleId__c, Territory__r.Channel__r.DefaultProfileId__c, TerrGroupId__c, PrimaryTerritory__c, Zoning__c, Territory__r.name, Territory__r.Channel__r.name, Territory__r.Channel__r.id, ownerid, Zoning__r.Name,Zoning__r.zone__c  from UserTerritory__c where id in: myUserTerrs])
                    {
                    UserTerritory__c UserTerr = new UserTerritory__c(id=currUserTerr.id, ownerid=currUserTerr.user__c); 
                    UserTerrToUpdate.add(UserTerr); 
                    //system.debug(currUserTerr.PrimaryTerritory__c);
                    if(currUserTerr.PrimaryTerritory__c)   
                        {
                        User usr = new User(Id=currUserTerr.user__c,RoleProxy__c=currUserTerr.RoleId__c, ProxyProfileId__c = currUserTerr.Territory__r.Channel__r.DefaultProfileId__c , ZoneID__c = currUserTerr.Zoning__c ,ZoneLabel__c= currUserTerr.Zoning__r.Name, ZoneNumber__c= currUserTerr.Zoning__r.zone__c, PrimaryTerritory__c=currUserTerr.Territory__r.name,PrimaryTerritoryId__c=currUserTerr.Territory__c ,PrimaryChannel__c=currUserTerr.Territory__r.Channel__r.name,PrimaryChannelid__c=currUserTerr.Territory__r.Channel__r.id);   
                    	// Activity Tagging
                        if(currUserTerr.ActivityTerritory__c)   
                        	{
                            usr.ActivityChannelId__c = currUserTerr.Territory__r.Channel__r.id;
                            usr.ActivityChannelName__c = currUserTerr.Territory__r.Channel__r.name;
                            usr.ActivityTerritoryId__c = currUserTerr.Territory__c;
                            usr.ActivityTerritoryName__c = currUserTerr.Territory__r.name;
                            usr.ActivityZoneId__c = currUserTerr.Zoning__c;
                            }
                        UsersToUpdate.add(usr);
                        }  
                    }
                List<UserTerritory__c> RelatedUTRecords = [select id from UserTerritory__c where id not in: myUserTerrs and user__c in: UsersToUpdate];
                system.debug('RelatedUTRecords.size' + RelatedUTRecords.size());
                List<UserTerritory__c> UnPrime = new List<UserTerritory__c>();
                
                for(UserTerritory__c currUserTerr : RelatedUTRecords)
                    {
                    UserTerritory__c NotPrimaryUT = new UserTerritory__c(id=currUserTerr.id, PrimaryTerritory__c=false); 
                    UnPrime.add(NotPrimaryUT);    
                    }	
                
                if (!UnPrime.isEmpty())
                    {
                    update UnPrime;
                    }   
            
                if (!UsersToUpdate.isEmpty())
                    { 
                    update UsersToUpdate;
                    }
                if (!UserTerrToUpdate.isEmpty())
                    {
                    update UserTerrToUpdate; 
                    }
                }
            } */

     
}