objects/Activity.object
<CustomObject>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>IsPrivateWealthCase__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Private Wealth Case?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Artemus.Request.requestor_id
varchar(100)</description>
        <label>Requester</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Requestor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RunCaseSharing__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If checked, runs apex case sharing upon save.  Used primarily for realignments.  This should be default of checked.  Apex handles the sharing of cases based on record type, user, etc.and will not share cases that shouldn't be shared.</description>
        <label>Run Case Sharing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SubmittedOnBehalfOf__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to support the Affiliate Request Process</description>
        <label>Submitted on behalf of</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.ActivityReporting__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>User.ActivityZoneId__c</field>
                <operation>notEqual</operation>
                <value>a1bF0000003XUiW,a1bF00000053bto</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>SubmitedOnBehalfOf</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <description>Artemus.Request.territory
varchar(255)</description>
        <label>Territory</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel><enableHistory>true</enableHistory>
</CustomObject>

objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>ParentTerritory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Territories</relationshipLabel>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RoleGroupId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Role Group Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zone1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Zone 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ActivityTerritoryId__c</fullName>
        <description>Used To Tag the Activities and Opportunities created by the user.</description>
        <externalId>true</externalId>
        <inlineHelpText>READ ONLY FIELD : This Will be populated by the UserTerritory__c assignment when the Territory Assignment is tagged as an Activity Territory. Please never update this field directly. Instead Delete/Insert the relevant UserTerritory__c record.</inlineHelpText>
        <label>Activity Territory Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryParentId__c</fullName>
        <description>The Activity Territory's parent Id</description>
        <label>Activity Territory Parent Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryRoleGroupId__c</fullName>
        <description>The RoleGroupId from the activity territory's territory</description>
        <label>Activity Territory RoleGroupId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryType__c</fullName>
        <description>The type of territory for the Activity Territory</description>
        <label>Activity Territory Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/RunCaseSharing.cls
public class RunCaseSharing {
    
    @InvocableMethod(label='Run Case Sharing' description='Runs case sharing')
    public static void runCaseSharing(List<Case> cases) {
        
        Id PWRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Private Wealth Portal').getRecordTypeId(); //never share Private Wealth Cases
        
        Set<Id> caseIds = new Set<Id>();
        List<Case> setRunSharingFalse = new List<Case>();
        
        for (Case c: cases) {
            caseIds.add(c.Id);
            setRunSharingFalse.add(new Case(Id=c.Id));
        }
        
        List<CaseShare> sharesToDelete = [SELECT Id FROM CaseShare WHERE CaseId in :caseIds AND RowCause = 'Manual'];
        delete sharesToDelete;
        
        Map<Id,CaseShare> sharesToCreateMap = new Map<Id,CaseShare>();
        Set<Id> userIds = new Set<Id>();
        
        for (Case c : cases) {
            if (c.Requestor__c != null && String.valueOf(c.Requestor__c).startsWith('005')) userIds.add(c.Requestor__c);
            if (c.SubmittedOnBehalfOf__c != null && String.valueOf(c.SubmittedOnBehalfOf__c).startsWith('005')) userIds.add(c.SubmittedOnBehalfOf__c);
        }
        
        Map<Id,User> userMap = new Map<Id,User>([SELECT Id, ActivityTerritoryId__c, ActivityTerritoryRoleGroupId__c, ActivityTerritoryParentId__c, ActivityTerritoryType__c
                                                 FROM User
                                                 WHERE Id in: userIds]);
        
        for (Case sc: cases) {    
            if (!sc.IsPrivateWealthCase__c) {
                if (userMap.containsKey(sc.Requestor__c)) {
                    if (userMap.get(sc.Requestor__c).ActivityTerritoryRoleGroupId__c != null) {
                        sharesToCreateMap.put(userMap.get(sc.Requestor__c).ActivityTerritoryRoleGroupId__c,
                                              (new CaseShare(CaseId=sc.id, 
                                                             UserOrGroupId=userMap.get(sc.Requestor__c).ActivityTerritoryRoleGroupId__c, 
                                                             CaseAccessLevel='Edit', 
                                                             RowCause = 'Manual')));     
                    }
                }
                
                if (sc.SubmittedOnBehalfOf__c != null && userMap.containsKey(sc.SubmittedOnBehalfOf__c)) {
                    if (userMap.get(sc.SubmittedOnBehalfOf__c).ActivityTerritoryRoleGroupId__c != null) {
                        sharesToCreateMap.put(userMap.get(sc.SubmittedOnBehalfOf__c).ActivityTerritoryRoleGroupId__c,
                                              (new CaseShare(CaseId=sc.id, 
                                                             UserOrGroupId=userMap.get(sc.SubmittedOnBehalfOf__c).ActivityTerritoryRoleGroupId__c, 
                                                             CaseAccessLevel='Edit', 
                                                             RowCause = 'Manual')));                  }
                }
            }
            
            
            
        }
        
        //When the requestor's Activity Territory is a region, we need to share with all other territories under the region
        Set<Id> regionIdSet = new Set<Id>();
        
        for (User u : userMap.values()) {
            if (u.ActivityTerritoryType__c == 'Region') {
                regionIdSet.add(u.ActivityTerritoryId__c);
            }
        }
        
        Map<Id,Territory__c> childTerritoriesMap = new Map<Id,Territory__c>([SELECT Id, (SELECT Id, RoleGroupId__c FROM Territories__r) FROM Territory__c WHERE Id in :regionIdSet]);       
        
        for (Case scr : cases) {   
            if (scr.RecordTypeId != PWRecordTypeId) {
                for (Id i : childTerritoriesMap.keyset()) {               
                    List<Territory__c> ct = childTerritoriesMap.get(i).Territories__r;                
                    for (Territory__c cts : ct) { 
                        if (cts.RoleGroupId__c != null) { 
                            sharesToCreateMap.put(cts.RoleGroupId__c, (new CaseShare(CaseId=scr.id, 
                                                                                     UserOrGroupId=cts.RoleGroupId__c, 
                                                                                     CaseAccessLevel='Read', 
                                                                                     RowCause = 'Manual')));     
                        }
                    }
                    
                }
            }
        }      
        
        insert sharesToCreateMap.values(); 
        
        for (Case c : setRunSharingFalse) {
            c.RunCaseSharing__c = FALSE;
        }
        
        update setRunSharingFalse;
        
    }
    
    
}