objects/ActivityContact__c.object
<CustomObject>
    <fields>
        <fullName>ActivityContact__c</fullName>
        <description>This Field is populated by the trigger and contains ActivityId__c + Contact__c, it is used to ensure that no duplicate contact on an activity (does not allow duplicate)</description>
        <label>ActivityContact</label>
        <length>37</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ActivityId__c</fullName>
        <description>This fake Id field is binded to Task through the use of the "Contacts" Grid build in the GridBuddy application. It is populated by GB with Task.Id</description>
        <externalId>true</externalId>
        <label>ActivityId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityPoints__c</fullName>
        <description>This field is read-only and populated by an automated process that assigns points based on criteria that can vary and is set by sales management. If you feel the points are incorrect, update the activity record and the points will recalculate when saved.</description>
        <inlineHelpText>This field is read-only and populated by an automated process that assigns points based on criteria that can vary and is set by sales management. If you feel the points are incorrect, update the activity record and the points will recalculate when saved.</inlineHelpText>
        <label>Activity Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ActivitySource__c</fullName>
        <description>This is populated by the trigger from Task.ActivitySource__c</description>
        <label>Activity Source</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivitySubType__c</fullName>
        <description>The dependent field on Type IC to drive value visibility , Copied from Task object  in insert trigger.</description>
        <label>Activity Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ActivityType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Product/Promotional</fullName>
                </value>
                <value>
                    <fullName>Follow-Up/Service</fullName>
                </value>
                <value>
                    <fullName>Solutions</fullName>
                </value>
                <value>
                    <fullName>Roadshow</fullName>
                </value>
                <value>
                    <fullName>Other/Voicemail</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ActivityType__c</fullName>
        <description>Used to control the Sub Type field and not displayed in the UI. The out of box field Type is displayed in the UI.</description>
        <label>Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Meeting</fullName>
                </value>
                <value>
                    <fullName>Call</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by the trigger from Task.Campaign__c</description>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Activity Contacts</relationshipLabel>
        <relationshipName>Activity_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by the trigger from Task.OwnerChannelId__c (=Owner:User.ActivityChannelId__c)</description>
        <label>Channel</label>
        <referenceTo>Channel__c</referenceTo>
        <relationshipLabel>Activity Contacts</relationshipLabel>
        <relationshipName>Activity_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is entered through the Gridbuddy Form and is set to the id of the contact entered through the form. It is used by the trigger to create the TaskRelation entry to the related Task</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Activity Contacts</relationshipLabel>
        <relationshipName>ActivityContacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Firm__c</fullName>
        <description>Just a Formula so that AcivityContact__c records can be reported on based on Firm__c</description>
        <formula>Account__r.Firm__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Firm</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by the trigger from Task.Opportunity__c</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Activity Contacts</relationshipLabel>
        <relationshipName>Activity_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OwnerChannelId__c</fullName>
        <formula>Owner:User.ActivityChannelId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Owner Channel Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OwnerChannel__c</fullName>
        <label>Owner Channel</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OwnerTerritoryId__c</fullName>
        <description>The owner's activity territory id at the time of activity creation</description>
        <label>Owner Territory Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OwnerTerritoryMARS__c</fullName>
        <description>The activity territory of the owner at the time of activity creation based on MARS territory name</description>
        <label>Owner Territory MARS</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OwnerTerritory__c</fullName>
        <label>Owner Territory</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <description>Each activity will have 1 to Many contacts. These activity related contacts are stored in this object along necessary attributes to allow for advanced activity reporting. This Table is synched up with the TaskRelation standard object through the "ActivityContactTrigger" trigger and the "ActivityContactTriggerHandler" Class.
This object is "virtually" related to Task through the use of the "ActivityId__c" field. This fake Id field is binded to Task through the use of the "Contacts" Grid build in the GridBuddy application.</description>
    <label>Activity Contact</label>
    <nameField>
        <displayFormat>AC-{0000000000}</displayFormat>
        <label>Activity Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Contacts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Channel__c.object
<CustomObject>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <description>Wells FA data in Salesforce requested by Joseph Labresh. This field labels each FA by what channel they work in: “PCG”, “WBS”, and “Finet”.</description>
        <inlineHelpText>This field is about Wells FA data, it labels each FA by what channel they work in: “PCG”, “WBS”, and “Finet”.</inlineHelpText>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PCG</fullName>
                </value>
                <value>
                    <fullName>WBS</fullName>
                </value>
                <value>
                    <fullName>FiNet</fullName>
                </value>
                <value>
                    <fullName>RIA Hybrid</fullName>
                </value>
                <value>
                    <fullName>Independent</fullName>
                </value>
                <value>
                    <fullName>Bank</fullName>
                </value>
                <value>
                    <fullName>RIA IFA Advisor</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Licensed Branch Employee</fullName>
                </value>
                <value>
                    <fullName>Insurance Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to the related Firm record</description>
        <label>Firm</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Offices Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EventRelationChangeEventTriggerHandler.cls
public class EventRelationChangeEventTriggerHandler {
    
    public static void eventRelationChangeEventAfterInsert(List<EventRelationChangeEvent> events) {

        Map<Id,Event> eventMap = getEventMap(events);
        
        Set<Id> userIdSet = new Set<Id>();
        for (Event e : eventMap.values()) {
            userIdSet.add(e.OwnerId);
        }
        
        Map<Id,User> userMap = Util.getUserTerritoryMap(userIdSet);
        Map<Id,Channel__c> channelMap = Util.getChannelMap();

        Set<Id> contactIdSet = new Set<Id>();
        Set<String> activityContactKeySet = new Set<String>();
        for (EventRelationChangeEvent event : events) {
            contactIdSet.add(event.RelationId);
            activityContactKeySet.add((String)event.EventId + (String)event.RelationId);
        }
        Map<Id,Contact> contactMap = UtilActivity.getContactPrimaryTerritoryMap(contactIdSet);

        Map<String,ActivityContact__c> activityContactKeyMap = UtilActivity.getActivityContactKeyMap(activityContactKeySet);
        
        List<ActivityContact__c> activityContactToUpsert = new List<ActivityContact__c>();
        List<ActivityContact__c> activityContactToDelete = new List<ActivityContact__c>();
        Set<Id> activityRelatedIdsForDelete = new Set<Id>();

       
                                                    
                                                    
        for (EventRelationChangeEvent event : events) {
            EventBus.ChangeEventHeader header = event.ChangeEventHeader;
            System.debug('Received change event for ' + 
                         header.entityName +
                         ' for the ' + header.changeType + ' operation.'); 
            
            System.debug('Event Relation Changed Record Fields');
            if (event.EventId != null) {
                System.debug('EventId: ' + event.EventId);
            }
            if (event.IsWhat != null) {
                System.debug('IsWhat: ' + event.IsWhat);
            }           
            if (event.RelationId != null) {
                System.debug('RelationId: ' + event.RelationId);
            }
            if (event.AccountId != null) {
                System.debug('AccountId: ' + event.AccountId);
            }
            
            
            SWITCH ON header.changetype {
                WHEN 'CREATE', 'UPDATE', 'UNDELETE' {
                    
                    String relationIdString = (String)event.RelationId;
                    
                    if (relationIdString.startsWith('003')) {
                        ActivityContact__c myAC = new ActivityContact__c();
                        myAC.ActivityId__c = (String)event.EventId;     
                        myAC.Contact__c = (String)event.RelationId;
                        if (activityContactKeyMap.containsKey((String)event.EventId + (String)event.RelationId)) myAC = activityContactKeyMap.get((String)event.EventId + (String)event.RelationId);
                        
                        Event myEvent = new Event();
                        if (eventMap.containsKey(event.EventId)) myEvent = eventMap.get(event.EventId);
                        
                        myAC = UtilActivity.activityContactEventFieldPreset(myAC,myEvent,contactMap,userMap,channelMap);
                        activityContactToUpsert.add(myAC);
                    }
                    
                    
                            
                }
                WHEN 'DELETE' {
                    
                
                    for(Id delRecId : header.recordids) {
                        activityRelatedIdsForDelete.add(delRecId);
                    }
                    
                    
                        
                 
                    

                }
            }
        }
        
        if (!activityRelatedIdsForDelete.isEmpty()) activityContactToDelete = UtilActivity.getActivityContactsByRelatedIds(activityRelatedIdsForDelete);       
        if (!activityContactToUpsert.isEmpty()) upsert activityContactToUpsert;
        if (!activityContactToDelete.isEmpty()) delete activityContactToDelete;
        
    }
    
    
    private static Map<Id,Event> getEventMap(List<EventRelationChangeEvent> events) {
        
        Set<Id> eventIdSet = new Set<Id>();
        
        for (EventRelationChangeEvent event : events) {
            eventIdSet.add(event.EventId);
        }
        
        
        Map<Id,Event> eventMap = new Map<Id,Event>([SELECT Id, Subject, ShortSubject__c, ActivityDate, Type, ActivitySource__c,
                                                    OwnerChannel__c, OwnerChannelId__c, OwnerTerritory__c, OwnerTerritoryMARS__c,
                                                    OwnerTerritoryId__c, OwnerZoneFormula__c, Ownerid, WhatId, WhoId, Description,
                                                    ActivityType__c, ActivitySubType__c, ActivityPoints__c, RecordTypeId, WhoCount, WhatCount,
                                                    AccountId, Firm__c, MARSOfficeId__c, Campaign__c, Opportunity__c
                                                    FROM Event
                                                    WHERE Id IN :eventIdSet]);
        
        return eventMap;
        
    }    
    
}