objects/AdditionalInfo__c.object
<CustomObject>
    <description>Tracks additional information for CDR Qualitative Data</description>
    <label>Additional Info</label>
    <nameField>
        <label>Additional Info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional Info</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CDRQualitativeData__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Firm</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CDR Qualitative Data (Firm)</relationshipLabel>
        <relationshipName>CDRQualitativeData</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AdditionalInfoSFID__c</fullName>
        <formula>CASESAFEID (AdditionalInfo__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Additional Info SFID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AdditionalInfo__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Additional Info</label>
        <referenceTo>AdditionalInfo__c</referenceTo>
        <relationshipLabel>CDR Qualitative Data (Additional Info)</relationshipLabel>
        <relationshipName>CDRQualitativeData</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Benchmark__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Benchmark</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>CDR Qualitative Data (Benchmark)</relationshipLabel>
        <relationshipName>CDRQualitativeDataBenchmarks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ChildAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Child Firm</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CDR Qualitative Data (Child Firm)</relationshipLabel>
        <relationshipName>CDRQualitativeDataChildFirms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ChildProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Child Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>CDR Qualitative Data (Child Product)</relationshipLabel>
        <relationshipName>CDRQualitativeDataChildProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CDR Qualitative Data (Contact)</relationshipLabel>
        <relationshipName>CDRQualitativeData</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EffectiveDate__c</fullName>
        <defaultValue>NOW()+30</defaultValue>
        <label>Effective Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>HistoricalDate__c</fullName>
        <label>Historical Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>NextPendingActivationDate__c</fullName>
        <label>Next Pending Activation Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>NextStagingDate__c</fullName>
        <label>Next Staging Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ParentKey__c</fullName>
        <formula>CASE( RecordType.Name,
"Additional Info", AdditionalInfo__c,
"Benchmark", Benchmark__c,
"Benchmark-Additional Info", Benchmark__c &amp; AdditionalInfo__c,
"Contact", Contact__c,
"Contact-Additional Info", Contact__c &amp; AdditionalInfo__c,
"ETF", Product__c,
"Firm", Account__c,
"Firm-Additional Info", Account__c &amp; AdditionalInfo__c,
"Firm-Child Firm", Account__c &amp; ChildAccount__c,
"Firm-Contact", Account__c &amp; Contact__c,
"Firm-Product", Account__c &amp; Product__c,
"Mutual Fund", Product__c,
"Product-Additional Info", Product__c &amp; AdditionalInfo__c,
"Product-Benchmark", Product__c &amp; Benchmark__c,
"Product-Child Product", Product__c &amp; ChildProduct__c,
"Product-Contact", Product__c &amp; Contact__c,
"Share Class", Product__c,
"")</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Key</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductSFID__c</fullName>
        <formula>CASESAFEID( Product__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product SFID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>CDR Qualitative Data (Product)</relationshipLabel>
        <relationshipName>CDRQualitativeDataProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StagingDate__c</fullName>
        <label>Staging Date</label>
        <type>DateTime</type>
    </fields>
    <description>This object stores qualitative data about contacts, firms, products, additional information and their relationships to one another.</description>
    <label>CDR Qualitative Data</label>
    <nameField>
        <label>CDR Qualitative Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CDR Qualitative Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CDRQualitativeDataCompareExt.cls
public class CDRQualitativeDataCompareExt {
    
    public final CDRQualitativeData__c cdr {get;set;}
    public List<SelectOption> CDRSelectOptions {get;set;}
    public CDRQualitativeData__c controlCDR {get; set;}
    public CDRQualitativeData__c compareCDR {get; set;}
    public Id compareCDRId {get;set;}
    public Boolean dispAllValues {get;set;}
    public List<CompareCDRItem> comparison {get;set;}
    
    public class CompareCDRItem {
        public String FieldName { get; set; }
        public String ControlValue {get;set;}
        public String CompareValue {get;set;}
        
        public CompareCDRItem(String iFieldName, String iControlValue, String iCompareValue) {
            FieldName = iFieldName;
            ControlValue = iControlValue;
            CompareValue = iCompareValue;
        }
    }
    
    public CDRQualitativeDataCompareExt(ApexPages.StandardController controller) {
        this.cdr = (CDRQualitativeData__c)controller.getRecord();
        this.controlCDR = queryAllCDRFields(cdr.Id);
        this.CDRSelectOptions = getCDRSelectOptions();
        this.dispAllValues = getdispAllValues();
    }
    
    public Boolean getdispAllValues() {
        if (dispAllValues == null) dispAllValues = FALSE;
        return dispAllValues;
    }
    
    public List<SelectOption> getCDRSelectOptions() {
        
        CDRQualitativeData__c cdrIds = [SELECT RecordTypeId, Id, Product__c, Account__c, Benchmark__c, Contact__c, AdditionalInfo__c, 
                                        ChildAccount__c, ChildProduct__c
                                        FROM CDRQualitativeData__c
                                        WHERE Id =:cdr.Id
                                        LIMIT 1];
        
        List<SelectOption> cdrSelOpts = new List<SelectOption>();
        cdrSelOpts.add(new SelectOption(cdr.Id,' -- None -- '));
        
        for (CDRQualitativeData__c c : [SELECT Id, Name FROM CDRQualitativeData__c 
                                        WHERE Account__c = :cdrIds.Account__c
                                        AND Benchmark__c = :cdrIds.Benchmark__c
                                        AND Contact__c = :cdrIds.Contact__c
                                        AND AdditionalInfo__c = :cdrIds.AdditionalInfo__c
                                        AND ChildAccount__c = :cdrIds.ChildAccount__c
                                        AND ChildProduct__c = :cdrIds.ChildProduct__c
                                        AND Product__c = :cdrIds.Product__c
                                        AND RecordTypeId = :cdrIds.RecordTypeId
                                        AND Id != :cdr.Id
                                        ORDER BY EffectiveDate__c DESC])  {
                                            cdrSelOpts.add(new SelectOption(c.Id,c.Name));
                                        }
        return cdrSelOpts;
    }
    
    public PageReference compare() {
        
        compareCDR = queryAllCDRFields(compareCDRId);
        
        Map<String,Object> controlCDRFieldMap = controlCDR.getPopulatedFieldsAsMap();
        Map<String,Object> compareCDRFieldMap = compareCDR.getPopulatedFieldsAsMap();
        
        Map<String,CompareCDRItem> compareMap = new Map<String,CompareCDRItem>();
        
        
        for (String f : controlCDRFieldMap.keySet()) {
            
                if (compareMap.containsKey(f)) {
                    CompareCDRItem t = compareMap.get(f);
                    t.ControlValue = String.valueOf(controlCDRFieldMap.get(f));
                    compareMap.put(f,t);
                } else {
                    CompareCDRItem n = new CompareCDRItem(f,String.valueOf(controlCDRFieldMap.get(f)),' ');
                    compareMap.put(f,n);
                }
            }

        for (String f : compareCDRFieldMap.keySet()) {
                if (compareMap.containsKey(f)) {
                    CompareCDRItem t = compareMap.get(f);
                    t.CompareValue = String.valueOf(compareCDRFieldMap.get(f));
                    compareMap.put(f,t);
                } else {
                    CompareCDRItem n = new CompareCDRItem(f,' ',String.valueOf(compareCDRFieldMap.get(f)));
                    compareMap.put(f,n);
                }
        }
       
        Set<String> excludedFieldSet = new Set<String>();
        excludedFieldSet.add('Id');
        excludedFieldSet.add('OwnerId');
        excludedFieldSet.add('RecordTypeId');
        excludedFieldSet.add('CreatedDate');
        excludedFieldSet.add('CreatedById');
        excludedFieldSet.add('LastModifiedDate');
        excludedFieldSet.add('LastModifiedById');
        excludedFieldSet.add('LastViewedDate');        
        excludedFieldSet.add('LastReferencedDate');
        excludedFieldSet.add('CaseSafeSFID__c');
		excludedFieldSet.add('NextStagingDate__c');        
        excludedFieldSet.add('NextPendingActivationDate__c');
        excludedFieldSet.add('HistoricalDate__c');
        excludedFieldSet.add('IsDeleted');
        excludedFieldSet.add('ParentKey__c');
        excludedFieldSet.add('SystemModstamp');
        excludedFieldSet.add('StagingDate__c');       
        excludedFieldSet.add('Contact__c');
        excludedFieldSet.add('Account__c');
        excludedFieldSet.add('Product__c');
        excludedFieldSet.add('AdditionalInfo__c');
        excludedFieldSet.add('Benchmark__c');
        excludedFieldSet.add('ChildProduct__c');
        excludedFieldSet.add('ChildFirm__c');
        excludedFieldSet.add('ProductSFID__c');
		excludedFieldSet.add('ContactSFID__c');  
        excludedFieldSet.add('AdditionalInfoSFID__c'); 
        
        String type='CDRQualitativeData__c';
        Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
        Schema.SObjectType CDRSchema = schemaMap.get(type);
        Map<String, Schema.SObjectField> fieldMap = CDRSchema.getDescribe().fields.getMap();
        
        comparison = new List<CompareCDRItem>();
        
        for (CompareCDRItem ci : compareMap.values()) {

            if (!excludedFieldSet.contains(ci.FieldName)) {            
            ci.FieldName = fieldMap.get(ci.FieldName).getDescribe().getLabel();
            
            if (!dispAllValues && ci.ControlValue != ci.CompareValue) {
                comparison.add(ci); 
            }
            
            if (dispAllValues) comparison.add(ci);
            }
        }
        
        return null;
        
    }
    
    public CDRQualitativeData__c queryAllCDRFields(Id cdrId) {
        
        String query = 'SELECT ';
        Map<String, Schema.SObjectField> CDRFields = Schema.getGlobalDescribe().get('CDRQualitativeData__c').getDescribe().fields.getMap();
        
        for(String s : CDRFields.keySet()) {
            query += ' ' + s + ',';
        }
        
        if (query.subString(query.Length()-1,query.Length()) == ','){
            query = query.subString(0,query.Length()-1);
        }
        
        query += ' FROM CDRQualitativeData__c ';
        query += ' WHERE Id =: cdrId '; 
        
        List<CDRQualitativeData__c> CDRs = database.query(query);
        CDRQualitativeData__c CDR = CDRs[0];
        
        return CDR;
        
    }
    
    
}