objects/ApexActivitiesStatsLog__c.object
<CustomObject>
    <fields>
        <fullName>ClassName__c</fullName>
        <label>Class Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MethodName__c</fullName>
        <description>Method Name</description>
        <label>Method Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ObjectName__c</fullName>
        <description>Object Name</description>
        <label>Object Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QueryBatchJob__c</fullName>
        <description>Query Batch Job</description>
        <label>QueryBatchJob</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <description>Instead of sending emails for success\failure for background activities, we will populate the information in this object.</description>
    <label>Apex Activities Stats Log</label>
    <nameField>
        <label>ApexActivitiesStatsLog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ApexActivitiesStatsLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Source: MARS na_load_rep.StatCd
Loaded by a nightly job.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PardotSettings__c.object
<CustomObject>
    <fields>
        <fullName>Value__c</fullName>
        <description>This field holds the values.</description>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Settings to connect to pardot and perform operations.</description>
    <label>Pardot Settings</label>
</CustomObject>

classes/UpdateProspectInPardot.cls
global class UpdateProspectInPardot {
    
    @future (callout=true)
    public static void UpdateProspectOptoutInPardotByEmail(string email, boolean optOut) { 
    
        try {
            List<ApexActivitiesStatsLog__c> logs = new List<ApexActivitiesStatsLog__c>();
            
            // Extract and sort pardot custom settings
            Map<string, PardotSettings__c> settingsMap = PardotSettings__c.getAll();
            //List<String> settingsKeys = new List<String>(settingsMap.keySet()); 
            
            string loginUrl = settingsMap.get('LoginUrl').Value__c;
            string userEmail = settingsMap.get('Email').Value__c;
            string password = settingsMap.get('Password').Value__c;
            string userKey = settingsMap.get('UserKey').Value__c;
            string apiKey;
              
            system.debug('Hello:' + loginUrl + ':' + userEmail + ':' + password + ':' + userKey);
           
            // Format the request body for login to pardot
            string loginBody = string.format(settingsMap.get('LoginBody').Value__c, new string[] {userEmail, password, userKey});
            system.debug('Login Body:'+ loginBody);
            
            // Send the login request to pardot
            HttpResponse loginResponse = postHttp(loginUrl, loginBody);
                        
            PardotStatus loginStat = ParseHttpResponse(loginResponse, email, loginUrl, loginBody, logs);
                        
            if (loginStat.Success == false) {
                insert logs;
                return;
            }
            
            apiKey = loginStat.ApiKey;
                       
            // Send the update request to pardot with ApiKey obtained from the above request.
            string updateUrl = string.format(settingsMap.get('UpdateUrl').Value__c, new string[] { 'Prospect', 'email', email});
            string updateBody = 'api_key=' + apiKey  + '&user_key=' + userKey + '&opted_out=' + optOut;
             
            HttpResponse updateResponse = postHttp(updateUrl,updateBody);
                                                         
            PardotStatus stat = ParseHttpResponse(updateResponse, email, updateUrl, updateBody, logs); 
            insert logs;                                
        }
        catch (System.Exception ex){
            if (!Test.IsRunningTest()) SendEmail('Exception Error: ' + ex, 'Error in updating the prospect in pardot - ' + Email  );
        }
    }
    
    public static PardotStatus ParseHttpResponse(HttpResponse response, string email, string url, string body, List<ApexActivitiesStatsLog__c> logs) {
    
        // Log the http response
        system.debug('Response:' + response.getBody());            
   
        // Load the http response into dom document
        dom.Document responseDoc = response.getBodyDocument();
        dom.XmlNode rootNode = responseDoc.getRootElement();
        string status = rootNode.getAttributeValue('stat', rootNode.getNamespace());
        //system.debug('status:'+ status);
        
        // if status = 'fail'
        if (status == 'fail') {
            for(dom.XmlNode node : responseDoc.getRootElement().getChildElements()) {                         
                if (node.getName() == 'err') {
                    string msg = 'Error: ' + node.getText() + '\n Url: ' + url + '\n Body: ' + body + '\n';
                    if(!Test.isRunningTest()) SendEmail(msg, 'Error updating the prospect in pardot - ' + email  );
                    string code = node.getAttributeValue('code', node.getNamespace());
                    
                    // Send PardotStatus
                    PardotStatus ps = new PardotStatus ();
                    ps.Code = code;
                    ps.Message = node.getText();
                    ps.Success = false;
                    
                    // Log in ApexActivitiesStatsLog__c table
                    LogResponse(ps.Message, ps.Success, body, url, logs); 
                    
                    return ps;
                }
            }
        }   
        
        // if status = 'ok' get api_key for login
        if (status == 'ok') {
            for(dom.XmlNode node : responseDoc.getRootElement().getChildElements()) {                         
                if (node.getName() == 'api_key') { 
                                                                            
                    // Send PardotStatus              
                    PardotStatus ps = new PardotStatus (); 
                    ps.ApiKey = node.getText();
                    ps.Success = true;
                    ps.Message = 'Login is successful';
                    
                    // Log in ApexActivitiesStatsLog__c table
                    LogResponse(ps.Message, ps.Success, body, url, logs); 
                                        
                    return ps;
                }
            }
        }       
        
        PardotStatus ps = new PardotStatus ();
        ps.Success = true;
        ps.Message = 'Update is Successful';
        
        // Log in ApexActivitiesStatsLog__c table
        LogResponse(ps.Message, ps.Success, body, url,logs); 
                    
        return ps;
    }
    
    public class PardotStatus {
        public string Code { get; set; }
        public string Message { get; set; }
        public string ApiKey { get; set; }
        public boolean Success { get; set; }
    }
    
    // Send the request to pardot
    public static HttpResponse postHttp(string url, string body) {   
        system.debug('Url:' + url + 'Body:' + body);     
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint(url);
        request.setMethod('POST');
        request.setBody(body);
        HttpResponse response = http.send(request);
        return response;
    }
    
    // Log in ApexActivitiesStatsLog__c table
    public static void LogResponse(string message, boolean success, string body, string url, List<ApexActivitiesStatsLog__c> logs) {
    
        string status;
        
        if (success == true) {
            status = 'ok';
        }
        else {
            status = 'fail';
        }
        
        ApexActivitiesStatsLog__c l = new ApexActivitiesStatsLog__c (ClassName__c = 'UpdateProspectInPardot', Message__c = message, MethodName__c = url, ObjectName__c = 'Contact', QueryBatchJob__c = body, Status__c = status);
        logs.Add(l);
    }                     
    
    public static void SendEmail(string message, string subject) { 
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {'sireesha.meka@ngam.natixis.com'};
        mail.setToAddresses(toAddresses);
        mail.setReplyTo('sireesha.meka@ngam.natixis.com');
        mail.setSenderDisplayName('NGAM SFDC - Call Pardot service');
        mail.setSubject(subject);
        mail.setHTMLBody(message);
        if(!Test.isRunningTest()) Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }
}