objects/ApexActivitiesStatsLog__c.object
<CustomObject>
    <fields>
        <fullName>AdditionalStats__c</fullName>
        <label>AdditionalStats</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ClassName__c</fullName>
        <label>Class Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MethodName__c</fullName>
        <description>Method Name</description>
        <label>Method Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ObjectName__c</fullName>
        <description>Object Name</description>
        <label>Object Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QueryBatchJob__c</fullName>
        <description>Query Batch Job</description>
        <label>QueryBatchJob</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <description>Instead of sending emails for success\failure for background activities, we will populate the information in this object.</description>
    <label>Apex Activities Stats Log</label>
    <nameField>
        <label>ApexActivitiesStatsLog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ApexActivitiesStatsLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ApexActivitiesStatsLogger.cls
public class ApexActivitiesStatsLogger {
    
    public static void logMessage(String ClassName, String MethodName, STring Message, String QueryBatchJob, String AdditionalStats, String ObjectName){
       // to check the governece limits
                   System.debug('Limits.getDMLRows() ' + Limits.getDMLRows());
                     System.debug('Limits.getLimitDMLRows() ' + Limits.getLimitDMLRows());
        System.debug('Limits.getDMLStatements()  ' + Limits.getDMLStatements() );
                     System.debug('Limits.getLimitDMLStatements()  ' + Limits.getLimitDMLStatements() );
        if (  
            (Limits.getDMLRows() < Limits.getLimitDMLRows()) &&
            (Limits.getDMLStatements() < Limits.getLimitDMLStatements())
        ){           
            ApexActivitiesStatsLog__c newMsg =
                new ApexActivitiesStatsLog__c(
                   ClassName__c = ClassName,
                    MethodName__c = MethodName,
                   Message__c = Message, 
                    QueryBatchJob__c = QueryBatchJob,
                    AdditionalStats__c = AdditionalStats,
                    ObjectName__c = ObjectName                    
                );
        
        
            try{
                System.debug( 'insert new message ' + newMsg.ClassName__c);
                  Database.SaveResult results = Database.insert(newMsg, false);
                if(results != null)
                {
                  System.debug(  results.isSuccess());
                }
            }
            catch (Exception ex){
                System.debug(
                    'Failed to INSERT the ApexActivitiesStatsLog__c record. ' +
                    'Error: ' + ex.getMessage()
                );
            }
        }
       else {
            System.debug(
                'Failed to INSERT the ApexActivitiesStatsLog__c record. ' +
                'Error: The APEX RUNTIME GOVERNOR LIMITS has been reached.'
            );
        }
    }
}