objects/BenchmarkPerformance__c.object
<CustomObject>
    <fields>
        <fullName>AsOfDate__c</fullName>
        <description>Performance date that is represented on the Benchmark Performance row.  Direct load from integration.</description>
        <label>As Of Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Benchmark__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Benchmark that is represented on the Benchmark Performance row.  Direct loaded during integration based on Product's external id for source file.</description>
        <label>Benchmark</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Benchmark Performance</relationshipLabel>
        <relationshipName>BenchmarkPerformance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>External Id that provides uniqueness to the Benchmark Performance row.  Direct load from integration. Concatenation of Benchmark Id, Inception Date, and As Of Date.</description>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>InceptionDate__c</fullName>
        <description>Inception date that is represented on the Benchmark Performance row.  Direct load from integration.  Used to match share classes to correct row bc benchmark performance since inception is matched to share class inception date.</description>
        <label>Inception Date</label>
        <type>Date</type>
    </fields>
    <description>Stores performance for benchmarks</description>
    <label>Benchmark Performance</label>
    <nameField>
        <displayFormat>BP-{0000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benchmark Performance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>InceptionDate__c</fullName>
        <label>Inception Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ParentProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PrimaryBenchmark__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Benchmark</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.RecordTypeId</field>
                <operation>equals</operation>
                <value>Benchmark</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products (Primary Benchmark)</relationshipLabel>
        <relationshipName>PrimaryBenchmarks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SecondaryBenchmark__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary Benchmark</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.RecordTypeId</field>
                <operation>equals</operation>
                <value>Benchmark</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products (Secondary Benchmark)</relationshipLabel>
        <relationshipName>SeocndaryBenchmarks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TertiaryBenchmark__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tertiary Benchmark</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.RecordTypeId</field>
                <operation>equals</operation>
                <value>Benchmark</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products (Tertiary Benchmark)</relationshipLabel>
        <relationshipName>TertiaryBenchmarks</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Benchmark</fullName>
        <active>true</active>
        <description>Use this for Benchmarks</description>
        <label>Benchmark</label>
    </recordTypes>
</CustomObject>

objects/ProductPerformance__c.object
<CustomObject>
    <fields>
        <fullName>AsOfDate__c</fullName>
        <label>As of Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExternalID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>InceptionDate__c</fullName>
        <formula>Product__r.InceptionDate__c</formula>
        <label>Inception Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PrimaryBenchmarkPerformance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Benchmark Performance</label>
        <referenceTo>BenchmarkPerformance__c</referenceTo>
        <relationshipLabel>Product Performance (Primary)</relationshipLabel>
        <relationshipName>ProductPerformancePrimaryBenchmark</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PrimaryBenchmark__c</fullName>
        <description>Name of the Primary Benchmark value</description>
        <label>Primary Benchmark</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Performance</relationshipLabel>
        <relationshipName>ProductPerformance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SecondaryBenchmarkPerformance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary Benchmark Performance</label>
        <referenceTo>BenchmarkPerformance__c</referenceTo>
        <relationshipLabel>Product Performance (Secondary Benchmark)</relationshipLabel>
        <relationshipName>ProductPerformanceSecondaryBenchmark</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SecondaryBenchmark__c</fullName>
        <description>Name of the Secondary Benchmark</description>
        <label>Secondary Benchmark</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TertiaryBenchmarkPerformance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tertiary Benchmark Performance</label>
        <referenceTo>BenchmarkPerformance__c</referenceTo>
        <relationshipLabel>Product Performance (Tertiary Benchmark)</relationshipLabel>
        <relationshipName>ProductPerformanceTeritaryBenchmark</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TertiaryBenchmark__c</fullName>
        <description>Name of the Tertiary Benchmark</description>
        <label>Tertiary Benchmark</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Product Performance</label>
    <nameField>
        <displayFormat>PP-{0000000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Performance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/BenchmarkPerformanceTriggerHandler_Test.cls
/**
* @author: Tom Barad
* @Created Date: 09/06/2018
* @description : test class for BenchmarkPerformanceTriggerHandler class. 
**/

@isTest 
private class BenchmarkPerformanceTriggerHandler_Test{
    
    private static testmethod void methodOne(){
        
        Id SCRecTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('Share Class').getRecordTypeId();
        Id MFRecTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('Mutual Fund').getRecordTypeId();
        Id BMRecTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('Benchmark').getRecordTypeId();
        
        Date inceptionDate1 = Date.newInstance(2010,3,31);
        Date inceptionDate2 = Date.newInstance(2011,4,30);
        Date ppAsOfDate = Date.today();
        
        //Inserting 3 benchmark products
        List<Product2> bmp = DataFactory.createProduct2(3,'BM_');
        bmp[0].RecordTypeId = BMRecTypeId;
        bmp[1].RecordTypeId = BMRecTypeId;
        bmp[2].RecordTypeId = BMRecTypeId;
        insert bmp;
        
        //Inserting 2 mutual fund products
        List<Product2> mfp = DataFactory.createProduct2(2,'MF_');
        mfp[0].RecordTypeId = MFRecTypeId;
        mfp[0].PrimaryBenchmark__c = bmp[0].Id;
        mfp[0].SecondaryBenchmark__c = bmp[1].Id;
        mfp[0].TertiaryBenchmark__c = bmp[2].Id;
        mfp[1].RecordTypeId = MFRecTypeId;
        mfp[1].PrimaryBenchmark__c = bmp[1].Id;
        mfp[1].SecondaryBenchmark__c = bmp[2].Id;
        mfp[1].TertiaryBenchmark__c = bmp[0].Id;
        insert mfp;
        
        //Inserting 3 schare class products
        List<Product2> scp = DataFactory.createProduct2(3,'SC_');
        //Two Share Class with Parent Product of MF_1, different inception dates
        scp[0].RecordTypeId = SCRecTypeId;
        scp[0].ParentProduct__c = mfp[0].Id;
        scp[0].InceptionDate__c = inceptionDate1;
        scp[1].RecordTypeId = SCRecTypeId;
        scp[1].ParentProduct__c = mfp[0].Id;
        scp[1].InceptionDate__c = inceptionDate2;
        
        //One Share Class with Parent Product of MF_2
        scp[2].RecordTypeId = SCRecTypeId;
        scp[2].ParentProduct__c = mfp[1].Id;
        scp[2].InceptionDate__c = inceptionDate1;                
        insert scp;
        
        List<ProductPerformance__c> ppToInsert = new List<ProductPerformance__c>();
        
        //inserting the product performance records
        ppToInsert.add(new ProductPerformance__c(AsOfDate__c = ppAsOfDate, Product__c = scp[0].Id, 
                                                 ExternalID__c = scp[0].id + '|' + ppAsOfDate.format())); 
        ppToInsert.add(new ProductPerformance__c(AsOfDate__c = ppAsOfDate, Product__c = scp[1].Id, 
                                                 ExternalID__c = scp[1].id + '|' + ppAsOfDate.format())); 
        ppToInsert.add(new ProductPerformance__c(AsOfDate__c = ppAsOfDate, Product__c = scp[2].Id, 
                                                 ExternalID__c = scp[2].id + '|' + ppAsOfDate.format())); 
        insert ppToInsert;
        
        //inserting the benchmarkperformance records
        List<BenchmarkPerformance__c> bpToInsert = new List<BenchmarkPerformance__c>();
        
        bpToInsert.add(new BenchmarkPerformance__c(AsOfDate__c = ppAsOfDate, Benchmark__c = bmp[0].Id, InceptionDate__c = inceptionDate1,
                                                   ExternalID__c = bmp[0].id + ':' + inceptionDate1.format() + '|' + ppAsOfDate.format()));
        bpToInsert.add(new BenchmarkPerformance__c(AsOfDate__c = ppAsOfDate, Benchmark__c = bmp[1].Id, InceptionDate__c = inceptionDate1,
                                                   ExternalID__c = bmp[1].id + ':' + inceptionDate1.format() + '|' + ppAsOfDate.format()));
        bpToInsert.add(new BenchmarkPerformance__c(AsOfDate__c = ppAsOfDate, Benchmark__c = bmp[2].Id, InceptionDate__c = inceptionDate1,
                                                   ExternalID__c = bmp[2].id + ':' + inceptionDate1.format() + '|' + ppAsOfDate.format()));
        bpToInsert.add(new BenchmarkPerformance__c(AsOfDate__c = ppAsOfDate, Benchmark__c = bmp[0].Id, InceptionDate__c = inceptionDate2,
                                                   ExternalID__c = bmp[0].id + ':' + inceptionDate2.format() + '|' + ppAsOfDate.format()));
        bpToInsert.add(new BenchmarkPerformance__c(AsOfDate__c = ppAsOfDate, Benchmark__c = bmp[1].Id, InceptionDate__c = inceptionDate2,
                                                   ExternalID__c = bmp[1].id + ':' + inceptionDate2.format() + '|' + ppAsOfDate.format()));
        bpToInsert.add(new BenchmarkPerformance__c(AsOfDate__c = ppAsOfDate, Benchmark__c = bmp[2].Id, InceptionDate__c = inceptionDate2,
                                                   ExternalID__c = bmp[2].id + ':' + inceptionDate2.format() + '|' + ppAsOfDate.format()));
        insert bpToInsert;
        
        ProductPerformance__c pp0 = [SELECT Id, Product__c, PrimaryBenchmarkPerformance__c, SecondaryBenchmarkPerformance__c, TertiaryBenchmarkPerformance__c
                                                    FROM ProductPerformance__c WHERE Id = :ppToInsert[0].Id];
        ProductPerformance__c pp1 = [SELECT Id, Product__c, PrimaryBenchmarkPerformance__c, SecondaryBenchmarkPerformance__c, TertiaryBenchmarkPerformance__c
                                                    FROM ProductPerformance__c WHERE Id = :ppToInsert[1].Id];
        ProductPerformance__c pp2 = [SELECT Id, Product__c, PrimaryBenchmarkPerformance__c, SecondaryBenchmarkPerformance__c, TertiaryBenchmarkPerformance__c
                                                    FROM ProductPerformance__c WHERE Id = :ppToInsert[2].Id];
        
        system.assertEquals(bpToInsert[0].Id, pp0.PrimaryBenchmarkPerformance__c);
        system.assertEquals(bpToInsert[1].Id, pp0.SecondaryBenchmarkPerformance__c);
        system.assertEquals(bpToInsert[2].Id, pp0.TertiaryBenchmarkPerformance__c);
        system.assertEquals(bpToInsert[3].Id, pp1.PrimaryBenchmarkPerformance__c);
        system.assertEquals(bpToInsert[4].Id, pp1.SecondaryBenchmarkPerformance__c);
        system.assertEquals(bpToInsert[5].Id, pp1.TertiaryBenchmarkPerformance__c);
        system.assertEquals(bpToInsert[1].Id, pp2.PrimaryBenchmarkPerformance__c);
        system.assertEquals(bpToInsert[2].Id, pp2.SecondaryBenchmarkPerformance__c);
        system.assertEquals(bpToInsert[0].Id, pp2.TertiaryBenchmarkPerformance__c);        
    }
    
    private static testmethod void methodTwo(){ 

        Id SCRecTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('Share Class').getRecordTypeId(); 
        Id MFRecTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('Mutual Fund').getRecordTypeId(); 
        Id BMRecTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('Benchmark').getRecordTypeId(); 
        
        Date inceptionDate1 = Date.newInstance(2010,3,31); 
        Date inceptionDate2 = Date.newInstance(2011,4,30); 
        Date ppAsOfDate = Date.today(); 
        
        //Inserting 3 benchmark products 
        List<Product2> bmp = DataFactory.createProduct2(3,'BM_'); 
        bmp[0].RecordTypeId = BMRecTypeId; 
        bmp[1].RecordTypeId = BMRecTypeId; 
        bmp[2].RecordTypeId = BMRecTypeId; 
        insert bmp; 
        
        //Inserting 2 mutual fund products 
        List<Product2> mfp = DataFactory.createProduct2(2,'MF_'); 
        mfp[0].RecordTypeId = MFRecTypeId; 
        mfp[0].PrimaryBenchmark__c = bmp[0].Id; 
        mfp[0].SecondaryBenchmark__c = bmp[1].Id; 
        mfp[0].TertiaryBenchmark__c = bmp[2].Id; 
        mfp[1].RecordTypeId = MFRecTypeId; 
        mfp[1].PrimaryBenchmark__c = bmp[1].Id; 
        mfp[1].SecondaryBenchmark__c = bmp[2].Id; 
        mfp[1].TertiaryBenchmark__c = bmp[0].Id; 
        insert mfp; 
        
        //Inserting 3 schare class products 
        List<Product2> scp = DataFactory.createProduct2(3,'SC_'); 
        //Two Share Class with Parent Product of MF_1, different inception dates 
        scp[0].RecordTypeId = SCRecTypeId; 
        scp[0].ParentProduct__c = mfp[0].Id; 
        scp[0].InceptionDate__c = inceptionDate1; 
        scp[1].RecordTypeId = SCRecTypeId; 
        scp[1].ParentProduct__c = mfp[0].Id; 
        scp[1].InceptionDate__c = inceptionDate2; 
        
        //One Share Class with Parent Product of MF_2 
        scp[2].RecordTypeId = SCRecTypeId; 
        scp[2].ParentProduct__c = mfp[1].Id; 
        scp[2].InceptionDate__c = inceptionDate1; 
        insert scp; 
        
        //inserting the benchmarkperformance records 
        List<BenchmarkPerformance__c> bpToInsert = new List<BenchmarkPerformance__c>(); 
        
        bpToInsert.add(new BenchmarkPerformance__c(AsOfDate__c = ppAsOfDate, Benchmark__c = bmp[0].Id, InceptionDate__c = inceptionDate1, 
        ExternalID__c = bmp[0].id + ':' + inceptionDate1.format() + '|' + ppAsOfDate.format())); 
        bpToInsert.add(new BenchmarkPerformance__c(AsOfDate__c = ppAsOfDate, Benchmark__c = bmp[1].Id, InceptionDate__c = inceptionDate1, 
        ExternalID__c = bmp[1].id + ':' + inceptionDate1.format() + '|' + ppAsOfDate.format())); 
        bpToInsert.add(new BenchmarkPerformance__c(AsOfDate__c = ppAsOfDate, Benchmark__c = bmp[2].Id, InceptionDate__c = inceptionDate1, 
        ExternalID__c = bmp[2].id + ':' + inceptionDate1.format() + '|' + ppAsOfDate.format())); 
        bpToInsert.add(new BenchmarkPerformance__c(AsOfDate__c = ppAsOfDate, Benchmark__c = bmp[0].Id, InceptionDate__c = inceptionDate2, 
        ExternalID__c = bmp[0].id + ':' + inceptionDate2.format() + '|' + ppAsOfDate.format())); 
        bpToInsert.add(new BenchmarkPerformance__c(AsOfDate__c = ppAsOfDate, Benchmark__c = bmp[1].Id, InceptionDate__c = inceptionDate2, 
        ExternalID__c = bmp[1].id + ':' + inceptionDate2.format() + '|' + ppAsOfDate.format()));
        bpToInsert.add(new BenchmarkPerformance__c(AsOfDate__c = ppAsOfDate, Benchmark__c = bmp[2].Id, InceptionDate__c = inceptionDate2, 
        ExternalID__c = bmp[2].id + ':' + inceptionDate2.format() + '|' + ppAsOfDate.format())); 
        
        try{
          insert bpToInsert; 
        }catch(Exception e){
          system.assertEquals(e.getMessage().contains('No Product Performance Record found'),true); 
        }
    } 
}