objects/BenchmarkPerformance__c.object
<CustomObject>
    <fields>
        <fullName>Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AsOfDate__c</fullName>
        <description>Performance date that is represented on the Benchmark Performance row.  Direct load from integration.</description>
        <label>As Of Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Benchmark__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Benchmark that is represented on the Benchmark Performance row.  Direct loaded during integration based on Product's external id for source file.</description>
        <label>Benchmark</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Benchmark Performance</relationshipLabel>
        <relationshipName>BenchmarkPerformance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>External Id that provides uniqueness to the Benchmark Performance row.  Direct load from integration. Concatenation of Benchmark Id, Inception Date, and As Of Date.</description>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FileType__c</fullName>
        <label>File Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>InceptionDate__c</fullName>
        <description>Inception date that is represented on the Benchmark Performance row.  Direct load from integration.  Used to match share classes to correct row bc benchmark performance since inception is matched to share class inception date.</description>
        <label>Inception Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MTD__c</fullName>
        <label>MTD</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>QTD__c</fullName>
        <label>QTD</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ReturnSinceInceptionAnnualized__c</fullName>
        <label>Return Since Inception Annualized</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ReturnSinceInceptionCumulative__c</fullName>
        <label>Return Since Inception Cumulative</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SinceInception__c</fullName>
        <label>Since Inception</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SourceFile__c</fullName>
        <label>Source File</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IPM Manual Benchmark Performance File</fullName>
                </value>
                <value>
                    <fullName>FactSet Daily Benchmark Performance File</fullName>
                </value>
                <value>
                    <fullName>FactSet Monthly Benchmark Performance File</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tickers__c</fullName>
        <label>Tickers</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TotalGross__c</fullName>
        <label>Total Gross</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>TotalNet__c</fullName>
        <label>Total Net</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>X10Year__c</fullName>
        <label>10 Year</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>X1DayGross__c</fullName>
        <label>1 Day Gross</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>X1DayNet__c</fullName>
        <label>1 Day Net</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>X1DayPriceChange__c</fullName>
        <label>1 Day Price Change</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X1Month__c</fullName>
        <label>1 Month</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>X1Year__c</fullName>
        <label>1 Year</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>X3Month__c</fullName>
        <label>3 Month</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>X3Year__c</fullName>
        <label>3 Year</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>X5Year__c</fullName>
        <label>5 Year</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>YTD__c</fullName>
        <label>YTD</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <description>Stores performance for benchmarks</description>
    <label>Benchmark Performance</label>
    <nameField>
        <displayFormat>BP-{0000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benchmark Performance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/BenchmarkPerformanceApproval__c.object
<CustomObject>
    <fields>
        <fullName>Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AsOfDate__c</fullName>
        <label>As Of Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Benchmark__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Benchmark</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Benchmark Performance Approvals</relationshipLabel>
        <relationshipName>Benchmark_Performance_Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FileType__c</fullName>
        <label>File Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>InceptionDate__c</fullName>
        <label>Inception Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MTD__c</fullName>
        <label>MTD</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>QTD__c</fullName>
        <label>QTD</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ReturnSinceInceptionAnnualized__c</fullName>
        <label>Return Since Inception Annualized</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ReturnSinceInceptionCumulative__c</fullName>
        <label>Return Since Inception Cumulative</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SinceInception__c</fullName>
        <label>Since Inception</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SourceFile__c</fullName>
        <label>Source File</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IPM Manual Benchmark Performance File</fullName>
                </value>
                <value>
                    <fullName>FactSet Benchmark Daily Performance File</fullName>
                    <label>FactSet Daily Benchmark Performance File</label>
                </value>
                <value>
                    <fullName>FactSet Monthly Benchmark Performance File</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tickers__c</fullName>
        <label>Tickers</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TotalGross__c</fullName>
        <label>Total Gross</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>TotalNet__c</fullName>
        <label>Total Net</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>X10Year__c</fullName>
        <label>10 Year</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>X1DayGross__c</fullName>
        <label>1 Day Gross</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>X1DayNet__c</fullName>
        <label>1 Day Net</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>X1DayPriceChange__c</fullName>
        <label>1 Day Price Change</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X1Month__c</fullName>
        <label>1 Month</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>X1Year__c</fullName>
        <label>1 Year</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>X3Month__c</fullName>
        <label>3 Month</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>X3Year__c</fullName>
        <label>3 Year</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>X5Year__c</fullName>
        <label>5 Year</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>YTD__c</fullName>
        <label>YTD</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <description>Stores the performance for benchmark until approved</description>
    <label>Benchmark Performance Approval</label>
    <nameField>
        <displayFormat>BPA-{0000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benchmark Performance Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BenchmarkPerformApprovalTriggerHandler.cls
/**
 * @author Pratibha Potluri
 * @Created Date: 09/04/2018
 * @description : handler class for BenchmarkPerformanceApprovalTrigger. 
**/

public class BenchmarkPerformApprovalTriggerHandler {
    
    /**
    Method called after insert or after update to process Approved BenchmarkPerformanceApproval records 
    and create BenchmarkPerformance records 
    and delete BenchmarkPerformanceApproval records once converted
    **/
    
    public static void afterActions(List<BenchmarkPerformanceApproval__c> lstNew){
    
        List<BenchmarkPerformanceApproval__c> benchmarkApprovalsToDelete = new List<BenchmarkPerformanceApproval__c>(); 
        List<BenchmarkPerformance__c> lstToInsert = new List<BenchmarkPerformance__c>();
        
        for(BenchmarkPerformanceApproval__c ba:lstNew){
            
            if(ba.Approved__c){
            BenchmarkPerformanceApproval__c del = new BenchmarkPerformanceApproval__c();
            del.Id = ba.Id;
            benchmarkApprovalsToDelete.add(del);
            lstToInsert.add(frameBP(ba));
            }
        }
        
        if(!benchmarkApprovalsToDelete.IsEmpty()){
            delete benchmarkApprovalsToDelete; 
        }
        
        if(!lstTOInsert.IsEmpty()){  
           //  List<Database.UpsertResult> upsrtResultList = Database.upsert(s_targetRecordList, s_externalIdField, false);  
            Schema.SObjectField ftoken = BenchmarkPerformance__c.Fields.ExternalID__c;
            Database.UpsertResult[] srList = Database.upsert(lstTOInsert,ftoken);        
            //insert lstTOInsert;
        }
    }
    
    
    /** 
    Method framing the BenchmarkPerformance record from the values of 
    BenchmarkPerformanceApproval Record
    taking BenchmarkPerformanceApproval record as Input
    **/
    
    public static BenchmarkPerformance__c frameBP(BenchmarkPerformanceApproval__c bpa){
        
        BenchmarkPerformance__c  bp = new BenchmarkPerformance__c();
        bp.X10Year__c= bpa.X10Year__c;
        bp.X1DayGross__c= bpa.X1DayGross__c;
        bp.X1DayNet__c= bpa.X1DayNet__c;
        bp.X1DayPriceChange__c= bpa.X1DayPriceChange__c;
        bp.X1Month__c= bpa.X1Month__c;
        bp.X1Year__c= bpa.X1Year__c;
        bp.X3Month__c= bpa.X3Month__c;
        bp.X3Year__c= bpa.X3Year__c;
        bp.X5Year__c= bpa.X5Year__c;
        bp.Approved__c= bpa.Approved__c;
        bp.AsOfDate__c= bpa.AsOfDate__c;
        bp.Benchmark__c= bpa.Benchmark__c;
        bp.ExternalID__c= bpa.ExternalID__c;
        bp.InceptionDate__c= bpa.InceptionDate__c;
        bp.MTD__c = bpa.MTD__c;
        bp.price__c = bpa.price__c;
        bp.QTD__c = bpa.QTD__c;
        bp.SinceInception__c= bpa.SinceInception__c;
        bp.TotalGross__c= bpa.TotalGross__c;
        bp.TotalNet__c = bpa.TotalNet__c;
        bp.YTD__c = bpa.YTD__c;
        bp.Source__c = bpa.Source__c;
        bp.SourceFile__c = bpa.SourceFile__c;
        bp.FileType__c = bpa.FileType__c;
        bp.Tickers__c = bpa.Tickers__c;   
        bp.ReturnSinceInceptionCumulative__c = bpa.ReturnSinceInceptionCumulative__c;
        bp.ReturnSinceInceptionAnnualized__c = bpa.ReturnSinceInceptionAnnualized__c;     
        
        return bp;                
    }

}