objects/Campaign.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <description>Use this for cVent events</description>
        <label>Event</label>
    </recordTypes>
</CustomObject>

objects/NGAMSettings__c.object
<CustomObject>
    <fields>
        <fullName>ProfileSales__c</fullName>
        <description>Indicates the profile that should be used for Sales User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</description>
        <inlineHelpText>Indicates the profile that should be used for Sales User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</inlineHelpText>
        <label>Profile: Sales</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProfileSystemAdministrator__c</fullName>
        <description>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</description>
        <inlineHelpText>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</inlineHelpText>
        <label>Profile: System Administrator</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Holds the NGAM settings</description>
    <label>NGAM Settings</label>
</CustomObject>

objects/NGAMSettingsHierarchy__c.object
<CustomObject>
    <fields>
        <fullName>ApexSystemUserOrProfile__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox is used in Apex to determine if a user or profile has admin rights to bypass error messages. Normally, this is checked for System Administrator profile and NGAM Integration profile only.</description>
        <inlineHelpText>This checkbox is used in Apex to determine if a user or profile has admin rights to bypass error messages. Normally, this is checked for System Administrator profile and NGAM Integration profile only.</inlineHelpText>
        <label>Apex System User Or Profile</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ByPassAccountValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows entity to by-pass validation rules on Account</description>
        <inlineHelpText>Allows entity to by-pass validation rules on Account</inlineHelpText>
        <label>By-Pass Account Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ByPassEventCampMemberValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <label>By-Pass Event CampMember ValidationRules</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CannotCUDActivityAfterDays__c</fullName>
        <description>Controls how many days after the activity date of a task or date of a corresponding activity contact or activity product a user can create, update, or delete an activity.  Used in trigger and validation rules.</description>
        <inlineHelpText>Controls how many days after the activity date of a task or date of a corresponding activity contact or activity product a user can create, update, or delete an activity.</inlineHelpText>
        <label>Cannot CUD Activity After Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NGAM Settings - Hierarchy</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>UserID__c</fullName>
        <defaultValue>"Populate This Field"</defaultValue>
        <externalId>true</externalId>
        <label>UserID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CampaignMemberTriggerHandlerTest.cls
@isTest
public class CampaignMemberTriggerHandlerTest {
    
    static testMethod void ValidateAll() {
        
        NGAMSettingsHierarchy__c hsettings = NGAMSettingsHierarchy__c.getOrgDefaults();
        hsettings.ByPassAccountValidationRules__c  = TRUE; 
        hsettings.ByPassEventCampMemberValidationRules__c  = TRUE;
        hsettings.CannotCUDActivityAfterDays__c = 999;
        hsettings.ApexSystemUserOrProfile__c = TRUE;
        upsert hsettings NGAMSettingsHierarchy__c.Id;

        
        string EventRecTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Event').getRecordTypeId();

       // Profile p = [select id from profile where name='System Administrator']; 
       // Profile pSales = [select id from profile where name='NGAM Sales']; 
       
        DataFactory.CreateNGAMCustomSettings(); 
        NGAMSettings__c ngamSettings = [select id,ProfileSales__c,ProfileSystemAdministrator__c from NGAMSettings__c limit 1]; 
        string pSales = Util.getCustomSettingProfileId(ngamSettings.ProfileSales__c);
        string p = Util.getCustomSettingProfileId(ngamSettings.ProfileSystemAdministrator__c);
        
        User u = new User(alias = 'standt', email='SFDCadmin@ngam.natixis.com', 
                          emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
                          localesidkey='en_US', profileid = p, 
                          timezonesidkey='America/Los_Angeles', username='SFDCadmin@ngam.natixis.com',UserID__c='SFDCadmin');
        
        User u2 = new User(alias = 'standt2', email='SFDCSales@ngam.natixis.com', 
                           emailencodingkey='UTF-8', lastname='Testing2', languagelocalekey='en_US', 
                           localesidkey='en_US', profileid = pSales, 
                           timezonesidkey='America/Los_Angeles', username='SFDCSales@ngam.natixis.com',UserID__c='SFDCSales');
        
//        NGAMSettingsHierarchy__c settings = new NGAMSettingsHierarchy__c(SetupOwnerId=p, ApexSystemUserOrProfile__c = TRUE,
//                                                                        CannotCUDActivityAfterDays__c = 360);
//        insert settings;
        
        List<Campaign> campaigns = new List<Campaign>();
        campaigns.add(new Campaign(Name='Test Event',RecordTypeId=EventRecTypeId,Description='Test',StartDate=Date.today(),EndDate=Date.Today()));
        campaigns.add(new Campaign(Name='Test Event2',RecordTypeId=EventRecTypeId,Description='Test2',StartDate=Date.today(),EndDate=Date.Today()));
        insert campaigns;
        
        List<CampaignMemberStatus> cms = new List<CampaignMemberStatus>();
        cms.add(new CampaignMemberStatus(CampaignId = campaigns[0].Id, IsDefault=TRUE, Label = 'Added to List'));
        cms.add(new CampaignMemberStatus(CampaignId = campaigns[0].Id, IsDefault=FALSE, Label = 'Invitation Sent'));
        insert cms;

        List<Account> TestFirm = DataFactory.createTestFirms(1);
        insert TestFirm;
        
        List<Account> TestAccount = DataFactory.createTestAccountswithFirms(1,TestFirm);
        insert TestAccount;
        
        List<CampaignMember> cm = new List<CampaignMember>();
        
        List<Contact> TestContact = DataFactory.createTestContacts(5,TestAccount,false);
        for (Contact c : TestContact) {
            c.pi__url__c = 'www.google.com';
        }
        insert TestContact;
        
        for (Contact c : TestContact) {
            cm.add(new CampaignMember(CampaignId=campaigns[0].Id,ContactId=c.Id,Status='Added to List'));
        }
        insert cm;
        
        CampaignMember cmc = new CampaignMember(CampaignId=campaigns[1].Id,ContactId=TestContact[0].Id,Status='Added to List');
        
        try {
            insert cmc;
        } catch (Exception e) {
            
        }

        for (CampaignMember cmu : cm) {
            cmu.Status = 'Invitation Sent';
        }
        
        try {
        update cm;
        } catch (Exception e) {
            
        }
        
        try {
        delete cm[0];
        } catch (Exception e) {
            
        }
        
        System.runAs(u) {
            delete cm[1];
        }
        
    }
    
}