objects/Campaign.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <description>Use this for cVent events</description>
        <label>Event</label>
    </recordTypes>
</CustomObject>

objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>InvitedByChannel__c</fullName>
        <description>Channel of the user in the Invited By field.  Updated whenever Invited By is updated.</description>
        <inlineHelpText>Channel of the user in the Invited By field.  Updated whenever Invited By is updated.</inlineHelpText>
        <label>Invited By Channel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InvitedByPersonalizationText__c</fullName>
        <description>Text that will be included in event invitations</description>
        <inlineHelpText>Text that will be included in event invitations</inlineHelpText>
        <label>Invited By Personalization Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>InvitedByTerritory__c</fullName>
        <description>Activity Territory of the user in the Invited By field.  Updated whenever Invited By is updated.</description>
        <inlineHelpText>Territory of the user in the Invited By field.  Updated whenever Invited By is updated.</inlineHelpText>
        <label>Invited By Territory</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InvitedByZone__c</fullName>
        <description>Activity Zone of the user in the Invited By field.  Updated whenever Invited By is updated.</description>
        <inlineHelpText>Zone of the user in the Invited By field.  Updated whenever Invited By is updated.</inlineHelpText>
        <label>Invited By Zone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InvitedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User who invited the member to be in this campaign (i.e., invited the invitee to an event)</description>
        <inlineHelpText>User who invited the member to be in this campaign (i.e., invited the invitee to an event)</inlineHelpText>
        <label>Invited By</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or does not match filter criteria.  Invited by must be an active user of Salesforce.</errorMessage>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Campaign_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecordTypeOfCampaign__c</fullName>
        <formula>Campaign.RecordType.DeveloperName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record Type of Campaign</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RegistrationType__c</fullName>
        <label>Registration Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Invited Guest/Client</fullName>
                </value>
                <value>
                    <fullName>Retirement</fullName>
                </value>
                <value>
                    <fullName>NJF: Client (Fri Only or Sat a/o Sun)</fullName>
                    <isActive>false</isActive>
                    <label>NJF: Client (Fri Only or Sat a/o Sun)</label>
                </value>
                <value>
                    <fullName>NJF: Client (Fri Only)</fullName>
                    <isActive>false</isActive>
                    <label>NJF: Client (Fri Only)</label>
                </value>
                <value>
                    <fullName>NJF: Client (One-day)</fullName>
                    <isActive>false</isActive>
                    <label>NJF: Client (One-day)</label>
                </value>
                <value>
                    <fullName>NJF: Client (Sat AND Sun)</fullName>
                    <isActive>false</isActive>
                    <label>NJF: Client (Sat AND Sun)</label>
                </value>
                <value>
                    <fullName>NJF: Client (Sat or Sun)</fullName>
                    <isActive>false</isActive>
                    <label>NJF: Client (Sat or Sun)</label>
                </value>
                <value>
                    <fullName>NJF: Client (Three-day)</fullName>
                    <isActive>false</isActive>
                    <label>NJF: Client (Three-day)</label>
                </value>
                <value>
                    <fullName>NJF: Natixis Assoc/Affiliate/Partner</fullName>
                    <isActive>false</isActive>
                    <label>NJF: Natixis Assoc/Affiliate/Partner</label>
                </value>
                <value>
                    <fullName>NJF: Natixis Executive</fullName>
                    <isActive>false</isActive>
                    <label>NJF: Natixis Executive</label>
                </value>
                <value>
                    <fullName>NJF: Natixis Host/Staff</fullName>
                    <isActive>false</isActive>
                    <label>NJF: Natixis Host/Staff</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByCampaign</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EventCampaignFieldsLastUpdatedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Who initiated the process builder to update the Event Campaign fields last</description>
        <label>Event Campaign Fields Last Updated By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ContactCampaignFieldsUpdated</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EventCampaignFieldsLastUpdated__c</fullName>
        <description>When the last time Invited By, Event Personalization Text, or Invited By Current Campaign were updated</description>
        <label>Event Campaign Fields Last Updated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EventCampaignName__c</fullName>
        <description>Which event campaign do the Event Campaign fields represent</description>
        <label>Event Campaign Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EventRegistrationType__c</fullName>
        <description>Integrates to CVent's Contact Type field; set by process builder</description>
        <label>Event Registration Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InvitedByPersonalizationText__c</fullName>
        <description>Field updated when a Sales user associates a Contact to a Campaign</description>
        <label>Invited By Personalization Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>InvitedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The user who invited the person to an event.  Note this is filled by a process builder that fires with each insert into Campaign Member.  It represents the most recent add to Campaign Member for this individual.  Synced to Pardot for event emails.</description>
        <label>Invited By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>InvitedContacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/NGAMSettingsHierarchy__c.object
<CustomObject>
    <fields>
        <fullName>ApexSystemUserOrProfile__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox is used in Apex to determine if a user or profile has admin rights to bypass error messages. Normally, this is checked for System Administrator profile and NGAM Integration profile only.</description>
        <inlineHelpText>This checkbox is used in Apex to determine if a user or profile has admin rights to bypass error messages. Normally, this is checked for System Administrator profile and NGAM Integration profile only.</inlineHelpText>
        <label>Apex System User Or Profile</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NGAM Settings - Hierarchy</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ActivityChannelName__c</fullName>
        <description>Used To Tag the Activities and Opportunities created by the user.</description>
        <inlineHelpText>READ ONLY FIELD : This Will be populated by the UserTerritory__c assignment when the Territory Assignment is tagged as an Activity Territory. Please never update this field directly. Instead Delete/Insert the relevant UserTerritory__c record.</inlineHelpText>
        <label>Activity Channel Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryName__c</fullName>
        <description>Used To Tag the Activities and Opportunities created by the user.</description>
        <inlineHelpText>READ ONLY FIELD : This Will be populated by the UserTerritory__c assignment when the Territory Assignment is tagged as an Activity Territory. Please never update this field directly. Instead Delete/Insert the relevant UserTerritory__c record.</inlineHelpText>
        <label>Activity Territory Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryZoneName__c</fullName>
        <description>Activity Territory Zone Name is derived from the Activity Zone Id.</description>
        <formula>IF( ActivityZoneId__c = "a1bF0000003XUiWIAW", "All Zones", 
IF( ActivityZoneId__c = "a1bF0000003XRz5IAG", "MRD", 
IF( ActivityZoneId__c = "a1bF0000003XTBCIA4", "RD1", 
IF( ActivityZoneId__c = "a1bF0000003XTBRIA4", "RD2", 
IF( ActivityZoneId__c = "a1bF0000003XTBWIA4", "RD3", 
IF( ActivityZoneId__c = "a1bF0000003XTBgIAO", "IC", 
IF( ActivityZoneId__c = "a1b2A000005HHBpQAO", "IC1", 
IF( ActivityZoneId__c = "a1b2A000005HHBqQAO", "IC2", 
IF( ActivityZoneId__c = "a1b2A000005HHBrQAO", "IC3", 
IF( ActivityZoneId__c = "a1b2A000005HHBsQAO", "IC4", 
IF( ActivityZoneId__c = "a1b2A000005HHBtQAO", "RD1", 
IF( ActivityZoneId__c = "a1b2A000005HHBuQAO", "RD2", 
IF( ActivityZoneId__c = "a1b2A000005HHBvQAO", "DIR1", 
IF( ActivityZoneId__c = "a1b2A000005HHBwQAO", "DIR2", 
IF( ActivityZoneId__c = "a1b2A000005HHBxQAO", "DIR3", 
IF( ActivityZoneId__c = "a1b2A000005HHByQAO", "DIR4", 
IF( ActivityZoneId__c = "a1b2A000005HHBzQAO", "DIR5", 
IF( ActivityZoneId__c = "a1b2A000005HHC0QAO", "MRD1", 
IF( ActivityZoneId__c = "a1b2A000005HHC1QAO", "MRD2", 
IF( ActivityZoneId__c = "a1b2A000005HHC2QAO", "MRD3", 
IF( ActivityZoneId__c = "a1b2A000005HHC3QAO", "MRD4", 
IF( ActivityZoneId__c = "a1b2A000005HHC4QAO", "MRD5", 
IF( ActivityZoneId__c = "a1b2A000005HHC5QAO", "MRD6", 
IF( ActivityZoneId__c = "a1b2A0000070V1JQAU", "MRD7", 
IF( ActivityZoneId__c = "a1b2A0000070V1OQAU", "MRD8", 
IF( ActivityZoneId__c = "a1b2A0000070V1TQAU", "MRD9",
IF( ActivityZoneId__c = "a1b2A000005HHC6QAO", "MD", 
IF( ActivityZoneId__c = "a1bF00000053btoIAA", "Inbound", NULL ))))))))))))))))))))))))))))</formula>
        <label>Activity Territory Zone Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CampaignMemberTriggerHandler.cls
public class CampaignMemberTriggerHandler {
    
    public static void errorChecks(List<CampaignMember> myCampaignMembers, List<CampaignMember> myOldCampaignMembers){
        
        Set<Id> ContactIdSet = new Set<Id>();
        if (!Trigger.IsDelete) {
            for (CampaignMember cis : myCampaignMembers) {
                ContactIdSet.add(cis.ContactId);
            }
        }
        
        Map<Id, Contact> contactMap = new Map<Id, Contact>([SELECT Id, InvitedBy__c, EventCampaignName__c 
                                                            FROM Contact
                                                            WHERE Id in: ContactIdSet]);
        
        Boolean systemUser = (Boolean)NGAMSettingsHierarchy__c.getInstance().ApexSystemUserOrProfile__c; 
        
        if (Trigger.IsDelete) {
            for (CampaignMember cm : myOldCampaignMembers) {
                if (!systemUser && cm.RecordTypeOfCampaign__c == 'Event' && cm.Status != 'Added to List') {
                    cm.addError('You can only delete Event campaign members if they are in a status of Added to List');
                }
            }
        }
        
        if (!Trigger.IsDelete) {
            for (CampaignMember cm : myCampaignMembers) {
                if (contactMap.containsKey(cm.ContactId)) {
                    if  (contactMap.get(cm.ContactId).InvitedBy__c != null && cm.RecordTypeOfCampaign__c == 'Event' && Trigger.IsInsert) {
                        cm.addError('This contact is part of another event campaign (' + contactMap.get(cm.ContactId).EventCampaignName__c + ') and invitations have not yet gone out.  You cannot add this contact right now.  Please call Event Planning.');
                    }
                }
            }
        }
    }
    
    public static void setFieldValues (List<CampaignMember> myCampaignMembers, Map<Id,CampaignMember> myCampaignMembersOldMap) {
        
        Set<Id> userSet = new Set<Id>();
        
        for (CampaignMember cm : myCampaignMembers) {
            
            if (cm.InvitedBy__c == null && cm.RecordTypeOfCampaign__c == 'Event') {
                cm.InvitedBy__c = cm.CreatedById;
                userSet.add(cm.InvitedBy__c);
            }
        }
        
        Map<Id,User> userMap = new Map<Id,User>([SELECT Id, ActivityChannelName__c, ActivityTerritoryName__c, ActivityTerritoryZoneName__c
                                                 FROM User
                                                 WHERE Id IN :userSet]);
        
        for (CampaignMember cm : myCampaignMembers) {
            
            if (userMap.containsKey(cm.InvitedBy__c) && cm.RecordTypeOfCampaign__c == 'Event' &&
                (cm.InvitedBy__c != myCampaignMembersOldMap.get(cm.Id).InvitedBy__c || Trigger.IsInsert)) {
                    cm.InvitedByChannel__c = userMap.get(cm.InvitedBy__c).ActivityChannelName__c;
                    cm.InvitedByTerritory__c = userMap.get(cm.InvitedBy__c).ActivityTerritoryName__c;
                    cm.InvitedByZone__c = userMap.get(cm.InvitedBy__c).ActivityTerritoryZoneName__c;
                }
        }
        
    }
    
    public static void setContactFields (List<CampaignMember> myCampaignMembers, Map<Id,CampaignMember> myCampaignMembersOldMap) {
        
        Set<Id> eventContactSetId = new Set<Id>();
        
        if (!Trigger.IsDelete) {
            for (CampaignMember cm : myCampaignMembers) {
                if (cm.RecordTypeOfCampaign__c == 'Event') eventContactSetId.add(cm.ContactId);
            }
        } else {
            for (CampaignMember cm : myCampaignMembersOldMap.values()) {
                if (cm.RecordTypeOfCampaign__c == 'Event') eventContactSetId.add(cm.ContactId);
            }
        }
        
        Map<Id,Contact> contactsToUpdateMap = new Map<Id,Contact>([SELECT Id, 
                                                                   EventCampaignFieldsLastUpdatedBy__c, EventCampaignFieldsLastUpdated__c, 
                                                                   EventCampaignName__c, InvitedBy__c
                                                                   FROM Contact
                                                                   WHERE Id IN :eventContactSetId]);
        
        if (Trigger.IsDelete) {
            for (CampaignMember cm : myCampaignMembersOldMap.values()) {
                
                if (contactsToUpdateMap.containsKey(cm.ContactId)) {
                    Contact c = contactsToUpdateMap.get(cm.ContactId);
                    c.EventCampaignFieldsLastUpdatedBy__c = null;
                    c.EventCampaignFieldsLastUpdated__c = null;
                    c.EventCampaignName__c = null;
                    c.InvitedBy__c = null;
                    c.EventRegistrationType__c = null;
                    c.InvitedByPersonalizationText__c = null;
                    contactsToUpdateMap.put(c.Id,c);
                }
                
            }
        } else {
            
            for (CampaignMember cm : myCampaignMembers) {
                
                if (contactsToUpdateMap.containsKey(cm.ContactId)) {
                    Contact c = contactsToUpdateMap.get(cm.ContactId);
                    system.debug('Status: ' + cm.Status);
                    if (cm.Status == 'Added to List') {
                        c.EventCampaignFieldsLastUpdatedBy__c = UserInfo.getUserId();
                        c.EventCampaignFieldsLastUpdated__c = datetime.now();
                        c.EventCampaignName__c = cm.Name;
                        c.InvitedBy__c = cm.InvitedBy__c;
                        c.EventRegistrationType__c = cm.RegistrationType__c;
                        c.InvitedByPersonalizationText__c = cm.InvitedByPersonalizationText__c;
                    } else {
                        c.EventCampaignFieldsLastUpdatedBy__c = null;
                        c.EventCampaignFieldsLastUpdated__c = null;
                        c.EventCampaignName__c = null;
                        c.InvitedBy__c = null;
                        c.EventRegistrationType__c = null;
                        c.InvitedByPersonalizationText__c = null;
                    }
                    contactsToUpdateMap.put(c.Id,c);
                }
            }
            
        }
        
        if (!contactsToUpdateMap.isEmpty()) update contactsToUpdateMap.values();         
        
    }
    
    
}