objects/Case.object
<CustomObject>
    <fields>
        <fullName>RequestArtemusID__c</fullName>
        <externalId>true</externalId>
        <label>Artemus Request ID</label>
        <length>38</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel><enableHistory>true</enableHistory>
</CustomObject>

objects/PRCGModelSecurity__c.object
<CustomObject>
    <fields>
        <fullName>ModelSecurityId__c</fullName>
        <description>Artemus.request_portf.request_portf_id
numeric(38,0)</description>
        <externalId>true</externalId>
        <label>Model Security Id</label>
        <length>38</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Security__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Security</label>
        <referenceTo>Security__c</referenceTo>
        <relationshipName>RequestPortfoliosSecurity</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PRCGRequestModel__c</fullName>
        <label>PRCG Request Model</label>
        <referenceTo>PRCGRequestModel__c</referenceTo>
        <relationshipLabel>PRCG Model Securities</relationshipLabel>
        <relationshipName>PRCGModelSecurities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PRCG Model Security</label>
    <nameField>
        <displayFormat>PMS-{0000000000}</displayFormat>
        <label>Request Portfolio Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PRCG Model Securities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PRCGRequestModel__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>PRCG Request Models</relationshipLabel>
        <relationshipName>RequestModels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ModelId__c</fullName>
        <description>Artemus.request_model.model_id
numeric(38,0)</description>
        <externalId>true</externalId>
        <label>ModelId</label>
        <length>38</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>PRCG Request Model</label>
    <nameField>
        <displayFormat>PRM-{0000000000}</displayFormat>
        <label>PRCG Request Model Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PRCG Request Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PRCGResearchNote__c.object
<CustomObject>
    <fields>
        <fullName>Abstract__c</fullName>
        <label>Abstract</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>The approval status of the Security Research</description>
        <inlineHelpText>Enter or update the approval status of the Security Research</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Note__c</fullName>
        <label>Note</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Security__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Security</label>
        <referenceTo>Security__c</referenceTo>
        <relationshipLabel>PRCG Research Notes</relationshipLabel>
        <relationshipName>PRCGResearchNotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ticker__c</fullName>
        <description>The Security Ticker Symbol (identifier)</description>
        <formula>Security__r.Ticker__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Ticker Symbol from the Security object</inlineHelpText>
        <label>Ticker</label>
        <type>Text</type>
    </fields>
    <description>Holds research related to a Security; this data is authored by PRCG.</description>
    <label>PRCG Research Note</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PRCG Research Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Security__c.object
<CustomObject>
    <fields>
        <fullName>Ticker__c</fullName>
        <description>Artemus.security.ticker
varchar(255)</description>
        <label>Ticker</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Security</label>
    <nameField>
        <label>Security Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Securities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PRCGResearchNotes.cls
public with sharing class PRCGResearchNotes {
    public final Case thisCase;
    public Map<string, List<PRCGResearchNote__c>> noteMap {get; set; }
    public List<PRCGResearchNote__c> PRCGNotes {get; set;}
    
    public PRCGResearchNotes(ApexPages.StandardController stdController) {
        this.thisCase = (Case)stdController.getRecord();
        system.debug('case:' + this.thisCase);
        system.debug('case id:'+this.thisCase.Id);
        //getnoteMap(this.thisCase.Id);
        PRCGNotes = getnoteList(this.thisCase.Id);
    }
    
    public Map<string, List<PRCGResearchNote__c>> getnoteMap(string id) {
        
        noteMap = new Map<string, List<PRCGResearchNote__c>>();
        //system.debug('case id:'+this.thisCase.RequestArtemusId__c);
        system.debug('case id:'+id);
        Case c = [select Id, RequestArtemusId__C, (select ModelId__c, Id from RequestModels__r) from case where Id = :id];
        
        for (PRCGRequestModel__c rm: c.RequestModels__r) {
            PRCGRequestModel__c model = [select Id, (select Security__r.Name, Security__r.Ticker__c, Security__c, ModelSecurityId__c from PRCGModelSecurities__r) from PRCGRequestModel__c where ModelId__C = : rm.ModelId__c];
            for (PRCGModelSecurity__c ms: model.PRCGModelSecurities__r) {
                system.debug('Hi:' + ms.Security__r.Name + 'id:' + ms.Security__c);
                string sec = ms.security__r.Name != null ? ms.security__r.Name : ms.security__c;
                
                if (noteMap.containsKey(sec)) continue;                
                //PRCGResearchNote__c [] researchNotes = [SELECT Id, name, security__c, security__r.Name, security__r.Ticker__c, Note__c, Subject__c, Approval_Status__c, Owner.Name, CreatedDate from PRCGResearchNote__c where security__c =:ms.Security__c and Approval_Status__c= 'Approved'];
                List<PRCGResearchNote__c>  researchNotes = [SELECT Id, name, security__c, security__r.Name, security__r.Ticker__c, Abstract__c, 
                                                        Note__c, Approval_Status__c, RecordType.Name, Owner.Name, CreatedDate, LastModifiedDate 
                                                        from PRCGResearchNote__c 
                                                        where security__c =:ms.Security__c 
                                                        and Approval_Status__c= 'Approved'
                                                        ORDER BY Security__r.Name, CreatedDate DESC, RecordType.Name];
                
                if (researchNotes.size() > 0) {
                    system.debug('Hello:' + ms.Security__r.Name);
                    for (PRCGResearchNote__c n : researchNotes) {
                        system.debug('Note:'+ n.security__c);
                        
                        if (noteMap.containsKey(sec)) {  
                            system.debug('hhh');              
                            List<PRCGResearchNote__c> values = noteMap.get(sec);
                            values.add(n);
                            noteMap.put(sec, values);                    
                        }
                        else {
                            system.debug('ggg');
                            noteMap.put(sec, new List<PRCGResearchNote__c>{n});
                        }
                    }
                    
                    
                    
                    
                }
            } 
            
            
            
        }
        system.debug('Notes:'+ noteMap.size());
        return noteMap;
    }
    
    public List<PRCGResearchNote__c> getnoteList(string id) {
        
        PRCGNotes = new List<PRCGResearchNote__c>();
        Set<Id> securitySet = new Set<Id>();
        //system.debug('case id:'+this.thisCase.RequestArtemusId__c);
        system.debug('case id:'+id);
        Case c = [select Id, RequestArtemusId__C, (select ModelId__c, Id from RequestModels__r) from case where Id = :id];
        
        for (PRCGRequestModel__c rm: c.RequestModels__r) {
            PRCGRequestModel__c model = [select Id, (select Security__r.Name, Security__r.Ticker__c, Security__c, ModelSecurityId__c from PRCGModelSecurities__r) from PRCGRequestModel__c where ModelId__C = : rm.ModelId__c];
            for (PRCGModelSecurity__c ms: model.PRCGModelSecurities__r) {
                system.debug('Hi:' + ms.Security__r.Name + 'id:' + ms.Security__c);
                securitySet.add(ms.Security__c);
            }
        } 
        
        system.debug('securitySet: ' + securitySet);
        
		List<PRCGResearchNote__c> PRCGNotes = new List<PRCGResearchNote__c>();
        List<PRCGResearchNote__c> PRCGNotesSelect = [SELECT Id, name, security__c, security__r.Name, security__r.Ticker__c, Abstract__c, 
                                               Note__c, Approval_Status__c, RecordType.Name, Owner.LastName, CreatedDate, LastModifiedDate 
                                               from PRCGResearchNote__c 
                                               where security__c =:securitySet 
                                               and Approval_Status__c= 'Approved'
                                               ORDER BY Security__r.Name, CreatedDate DESC, RecordType.Name];
        
        system.debug('PRCGNotesSelect: ' + PRCGNotesSelect);
        
        integer noteCount = 1;
        Id oldSecurity;
        Boolean firstLoop = TRUE;
        for (PRCGResearchNote__c n : PRCGNotesSelect) {
            
            if (firstLoop) {
              firstLoop = FALSE;
              oldSecurity = n.security__c;
            }
            
            if (n.security__c == oldSecurity) {
                noteCount = noteCount + 1;
            } else {
                noteCount = 1;
            }
            
            if (noteCount <= 3) PRCGNotes.add(n);
            oldSecurity = n.security__c;
            
        }
        
        
        return PRCGNotes;
    }
    
}