objects/Case.object
<CustomObject>
    <fields>
        <fullName>AdTraxCode__c</fullName>
        <description>The AdTrax Code entered by Prod Mgt Ops when they close an RFI/RFP case.</description>
        <label>AdTrax Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AffiliateFirmName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A customized look up field</description>
        <label>Affiliate Firm Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Affiliate</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CaseRegionDept__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The requester's Activity Region or Department.  This only changes when the requester value changes - not when the requester moves around the role hierarchy.  Set by trigger.</description>
        <label>Case Region/Dept</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Cases (Case Region/Dept)</relationshipLabel>
        <relationshipName>RegionCases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CaseTerritory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The requester's Activity Territory.  This only changes when the requester value changes - not when the requester moves around the role hierarchy.  Set by trigger.</description>
        <label>Case Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Cases (Case Territory)</relationshipLabel>
        <relationshipName>TerritoryCases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CreateRecurrence__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Recurrence batch job only selects cases with Create Recurrence = true.  Set by process builder based on Frequency.</description>
        <inlineHelpText>If checked, the recurrence batch job will clone this case for the given Recurrence Request Date.</inlineHelpText>
        <label>Create Recurrence?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DeliveryMethod__c</fullName>
        <label>Delivery Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Online Database</fullName>
                </value>
                <value>
                    <fullName>Consultant Database</fullName>
                </value>
                <value>
                    <fullName>3rd Party Database</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <description>Artemus.Request.department
varchar(100)</description>
        <label>Department</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DueDate__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <description>For Affiliate Request Process</description>
        <label>Duration</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Format__c</fullName>
        <description>RFP Format</description>
        <inlineHelpText>RFP Format</inlineHelpText>
        <label>Format</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Customized</fullName>
                </value>
                <value>
                    <fullName>Standardized</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <description>Frequency of the RFI</description>
        <inlineHelpText>Frequency of the RFI</inlineHelpText>
        <label>Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>SemiAnnually</fullName>
                    <label>Semi-Annually</label>
                </value>
                <value>
                    <fullName>Annually</fullName>
                </value>
                <value>
                    <fullName>Ad Hoc</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <description>Indicates whether the RFI/RFP is at the Affiliate or Product/Strategy level</description>
        <inlineHelpText>Indicates whether the RFI/RFP is at the Affiliate or Product/Strategy level</inlineHelpText>
        <label>Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Affiliate</fullName>
                </value>
                <value>
                    <fullName>Product/Strategy</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NewOrExistingBusiness__c</fullName>
        <label>New Or Existing Business</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New Business</fullName>
                </value>
                <value>
                    <fullName>Existing Business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NewProductStrategy__c</fullName>
        <description>New institutional business product (as an alternative to specifying existing Product/Strategy)</description>
        <inlineHelpText>New institutional business product (as an alternative to specifying existing Product/Strategy)</inlineHelpText>
        <label>New Product/Strategy</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductStrategyMutualFund__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product/Strategy or Mutual Fund related to the RFI/RFP</description>
        <inlineHelpText>Product/Strategy or Mutual Fund related to the RFI/RFP</inlineHelpText>
        <label>Product/Strategy/Mutual Fund</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purpose__c</fullName>
        <label>Purpose</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Addition to Platform</fullName>
                </value>
                <value>
                    <fullName>Addition to Recommended List</fullName>
                </value>
                <value>
                    <fullName>Addition to Model</fullName>
                </value>
                <value>
                    <fullName>New or Existing Mandate</fullName>
                </value>
                <value>
                    <fullName>Due Diligence</fullName>
                </value>
                <value>
                    <fullName>Ad Hoc Inquiry</fullName>
                </value>
                <value>
                    <fullName>Performance Reporting</fullName>
                </value>
                <value>
                    <fullName>Marketing Deliverable</fullName>
                </value>
                <value>
                    <fullName>Shareholder Reporting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RecurrenceDate__c</fullName>
        <description>Set by the recurrence batch, can be overridden.</description>
        <inlineHelpText>The due date of the next occurrence of this case.  Override to change the due date if necessary.  The due date must be set before the next occurrence is created.</inlineHelpText>
        <label>Recurrence Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurrenceSourceCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If this case is automatically generated via the recurrence batch, this field indicates from which case it was cloned.</description>
        <label>Recurrence Source Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Cases (Recurrence Source Case)</relationshipLabel>
        <relationshipName>RecurrenceSourceCases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurrenceTargetCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If this case was created automatically via the recurrence batch, this field indicates which case was cloned from this case to set up the recurrence.</description>
        <label>Recurrence Target Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Cases (Recurrence Target Case)</relationshipLabel>
        <relationshipName>RecurrenceTargetCases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestDate__c</fullName>
        <description>Artemus.Request.request_dt
datetime</description>
        <label>Request Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>RequestFor__c</fullName>
        <description>Auto populated from the same field displayed on the Rep/Contact Details page.</description>
        <formula>TEXT(Contact.RequestFor__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Auto populated from the same field displayed on the Rep/Contact Details page.</inlineHelpText>
        <label>Request for</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RequesterChannel__c</fullName>
        <formula>IF(  ISBLANK(SubmittedOnBehalfOf__c) ,   Requestor__r.ActivityChannelName__c  ,   SubmittedOnBehalfOf__r.ActivityChannelName__c  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Requester Channel</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RequesterTerritory__c</fullName>
        <formula>IF(  ISBLANK(SubmittedOnBehalfOf__c) ,   Requestor__r.ActivityRegionDept__c  ,   SubmittedOnBehalfOf__r.ActivityRegionDept__c  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Requester Territory</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Artemus.Request.requestor_id
varchar(100)</description>
        <label>Requester</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Requestor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubmittedOnBehalfOf__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to support the Affiliate Request Process</description>
        <label>Submitted on behalf of</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.ActivityReporting__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>User.ActivityZoneId__c</field>
                <operation>notEqual</operation>
                <value>a1bF0000003XUiW,a1bF00000053bto</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>SubmitedOnBehalfOf</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <label>Vehicle</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Mutual Fund</fullName>
                </value>
                <value>
                    <fullName>SMA (Institutional)</fullName>
                </value>
                <value>
                    <fullName>SMA (Wrap)</fullName>
                </value>
                <value>
                    <fullName>ETF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel><enableHistory>true</enableHistory>
</CustomObject>

objects/NGAMSettings__c.object
<CustomObject>
    <fields>
        <fullName>CaseRecurrenceLeadTime__c</fullName>
        <description>Used in CaseRecurrenceBatch; determines the number of days before the Recurrence Due Date that a case should be cloned.</description>
        <inlineHelpText>Used in CaseRecurrenceBatch; determines the number of days before the Recurrence Due Date that a case should be cloned.</inlineHelpText>
        <label>Case Recurrence Lead Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseRecurrenceToEmail__c</fullName>
        <description>Used in CaseRecurrenceBatch to indicate who should receive the finish email; separate multiple recipients with a single comma.</description>
        <inlineHelpText>Indicate who should receive the CaseRecurrenceBatch finish email; separate multiple recipients with a single comma.</inlineHelpText>
        <label>Case Recurrence To Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Holds the NGAM settings</description>
    <label>NGAM Settings</label>
</CustomObject>

classes/CaseRecurrenceBatch.cls
global class CaseRecurrenceBatch implements Database.Batchable<sObject>, Database.Stateful{
    
    public String query = 'SELECT Id, AccountId, BusinessHoursId, Origin, OwnerId, Reason, RecordTypeId, ' +
        ' ContactId, Description, Priority, Status, Subject, Type, ' +
        ' AdTraxCode__c, AffiliateFirmName__c, CaseRegionDept__c, CaseTerritory__c, ' +
        ' CreateRecurrence__c, DeliveryMethod__c, Department__c, DueDate__c, Duration__c, ' +
        ' Format__c, Frequency__c, Level__c, Purpose__c, ' +
        ' NewOrExistingBusiness__c, NewProductStrategy__c, Opportunity__c, ' +
        ' ProductStrategyMutualFund__c, RecurrenceDate__c, RecurrenceSourceCase__c,' + 
        ' RecurrenceTargetCase__c, RequestDate__c, Requestor__c, RequesterChannel__c, ' +
        ' RequesterTerritory__c, RequestFor__c, ' +
        ' SubmittedOnBehalfOf__c, ' +
        ' Vehicle__c ' +
        ' FROM Case ' +
        ' WHERE CreateRecurrence__c = TRUE ';
    
    public Set<Id> clonedCasesIdSet = new Set<Id>();
    
    public static NGAMSettings__c settings = NGAMSettings__c.getValues('NGAM_ALL');
    public static Integer leadTime = (Integer)settings.CaseRecurrenceLeadTime__c;
    public static String emailToAddresses = settings.CaseRecurrenceToEmail__c;
    public static Group IPMQueue = [SELECT Id FROM Group WHERE Name = 'IPM' AND Type = 'Queue' LIMIT 1];
    public static User NGAMIntegrationId = [SELECT Id FROM User WHERE Username LIKE 'inatixis@%natixis%' LIMIT 1];
    public static List<Case> clonedCases = new List<Case>();
    public static List<Case> casesToClone = new List<Case>();
    
    global Database.querylocator start(Database.BatchableContext BC){   
        system.debug('query: ' + query);
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Case> scope)	{ 
        
        //        NGAMSettings__c settings = NGAMSettings__c.getValues('NGAM_ALL');
        //        Integer leadTime = (Integer)settings.CaseRecurrenceLeadTime__c;
        //        String emailToAddresses = settings.CaseRecurrenceToEmail__c;
        
        Date leadTimeDate = date.Today().addDays(leadTime);
        Map<Id,Case> casesToUpdateMap = new Map<Id,Case>();
        
        Set<Id> userCheckSet = new Set<Id>();
        
        for (Case c : scope) {
            userCheckSet.add(c.Requestor__c);
            userCheckSet.add(c.OwnerId);
        }
        
        Map<Id,User> userCheckMap = new Map<Id,User>([SELECT Id FROM User WHERE IsActive = TRUE AND Id IN :userCheckSet]);
        
        for (Case c : scope) {
            
            switch on c.Frequency__c {
                when 'Monthly' {
                    c.RecurrenceDate__c = c.DueDate__c.addMonths(1);
                }
                when 'Quarterly' {
                    c.RecurrenceDate__c = c.DueDate__c.addMonths(3);
                }
                when 'Semi-Annually' {
                    c.RecurrenceDate__c = c.DueDate__c.addMonths(6);
                }
                when 'Annually' {
                    c.RecurrenceDate__c = c.DueDate__c.addYears(1); 
                }
            }
            
            if (!userCheckMap.containsKey(c.OwnerId)) c.OwnerId = IPMQueue.Id;            
            if (!userCheckMap.containsKey(c.Requestor__c)) c.Requestor__c = NGAMIntegrationId.Id;
            
            casesToUpdateMap.put(c.Id, c);
            if (c.RecurrenceDate__c <= leadTimeDate) casesToClone.add(c); 
        }
        
        for (Case c : casesToClone) {
            Case cClone = c.clone(false,true,false,false);
            cClone.RecurrenceSourceCase__c = c.Id;
            cClone.Case_Closed_by__c = null;
            cClone.DateRequestCompleted__c = null;
            cClone.OtherReason__c = null;
            cClone.Reason_for_Late_Delivery__c = null;
            cClone.RecurrenceTargetCase__c = null;
            cClone.RushRequest__c = FALSE;
            cClone.RushRequestReason__c = null;
            cClone.Status = 'New';
            cClone.Origin = 'Recurrence Batch';
            cClone.DueDate__c = c.RecurrenceDate__c;
            
            switch on cClone.Frequency__c {
                when 'Monthly' {
                    cClone.RecurrenceDate__c = cClone.DueDate__c.addMonths(1);
                }
                when 'Quarterly' {
                    cClone.RecurrenceDate__c = cClone.DueDate__c.addMonths(3);
                }
                when 'Semi-Annually' {
                    cClone.RecurrenceDate__c = cClone.DueDate__c.addMonths(6);
                }
                when 'Annually' {
                    cClone.RecurrenceDate__c = cClone.DueDate__c.addYears(1); 
                }
            }

            clonedCases.add(cClone);
            
        }
        
        insert clonedCases;
        
        for (Case c : clonedCases) {
            Case tc = casesToUpdateMap.get(c.RecurrenceSourceCase__c);
            tc.RecurrenceTargetCase__c = c.Id;
            tc.CreateRecurrence__c = FALSE;
            casesToUpdateMap.put(c.RecurrenceSourceCase__c,tc);
            clonedCasesIdSet.add(c.Id);
        }
        
        update casesToUpdateMap.values();
        
    }
    
    global void finish(Database.BatchableContext BC){
        
        Datetime yesterdayDateTime = Datetime.now().addDays(-1);
        
        clonedCases = [SELECT Id, AccountId, BusinessHoursId, CaseNumber, Origin, OwnerId, Reason, RecordTypeId, ContactId, Description, Priority, Status, Subject, Type,
                       AdTraxCode__c, Client_Type__c, CompletedDate__c, CreateRecurrence__c, DateRequestCompleted__c, DeliveryMethod__c, DueDate__c, Format__c, Frequency__c, 
                       Level__c, NewProductStrategy__c, Opportunity__c, Reason_for_Late_Delivery__c, RecurrenceDate__c, OtherReason__c, RecurrenceSourceCase__c, RecurrenceTargetCase__c, 
                       Requestor__c, RushRequest__c, RushRequestReason__c, Vehicle__c, Case_Closed_by__c, RecurrenceSourceCase__r.CaseNumber, RecurrenceSourceCase__r.Subject 
                       FROM Case
                       WHERE Id in :clonedCasesIdSet];
        
        if (!clonedCases.isEmpty()) {
            String body = '<p>Number of Cases Cloned: ' + clonedCases.size() + '</p>';
            String tBody = '<br/><table  border= "1" >';
            tbody = tBody + '<tr><th> Case </th><th> Cloned From </th><th> Subject </th><th> Frequency </th><th> Due Date </th></tr>';
            
            for (Case c : clonedCases) {
                
                tBody = tBody + '<tr><td>' + c.CaseNumber + '</td><td>' + c.RecurrenceSourceCase__r.CaseNumber + '</td><td>' +  c.Subject + '</td><td>' + c.Frequency__c  + '</td><td>' + c.DueDate__c.format() + '</td></tr>';
                
            }    
            
            tBody = tBody + '</table><br/>';
            body = body +tBody;
            
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            //String[] toAddresses = emailToAddresses.Split(',');            
            String[] toAddresses = new String[] {'tom.barad@natixis.com'};            
                mail.setToAddresses(toAddresses);
            mail.setSubject('Clone Recurring Cases Batch');
            mail.setHTMLBody(body);
            
            try {
                if (!Test.IsRunningTest()) Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
                //Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
            } catch (EmailException e) {
                throw new emailException('SendEmail error. ' + e.getMessage());
            }
            
        }
    }
    
}