objects/Case.object
<CustomObject>
    <fields>
        <fullName>CreateRecurrence__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Recurrence batch job only selects cases with Create Recurrence = true.  Set by process builder based on Frequency.</description>
        <inlineHelpText>If checked, the recurrence batch job will clone this case for the given Recurrence Request Date.</inlineHelpText>
        <label>Create Recurrence?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DueDate__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <description>Frequency of the RFI</description>
        <inlineHelpText>Frequency of the RFI</inlineHelpText>
        <label>Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>SemiAnnually</fullName>
                    <label>Semi-Annually</label>
                </value>
                <value>
                    <fullName>Annually</fullName>
                </value>
                <value>
                    <fullName>Ad Hoc</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RecurrenceDate__c</fullName>
        <description>Set by the recurrence batch, can be overridden.</description>
        <inlineHelpText>The due date of the next occurrence of this case.  Override to change the due date if necessary.  The due date must be set before the next occurrence is created.</inlineHelpText>
        <label>Recurrence Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RecurrenceSourceCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If this case is automatically generated via the recurrence batch, this field indicates from which case it was cloned.</description>
        <label>Recurrence Source Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Cases (Recurrence Source Case)</relationshipLabel>
        <relationshipName>RecurrenceSourceCases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecurrenceTargetCase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If this case was created automatically via the recurrence batch, this field indicates which case was cloned from this case to set up the recurrence.</description>
        <label>Recurrence Target Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Cases (Recurrence Target Case)</relationshipLabel>
        <relationshipName>RecurrenceTargetCases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel><enableHistory>true</enableHistory>
</CustomObject>

objects/NGAMSettings__c.object
<CustomObject>
    <fields>
        <fullName>CaseRecurrenceLeadTime__c</fullName>
        <description>Used in CaseRecurrenceBatch; determines the number of days before the Recurrence Due Date that a case should be cloned.</description>
        <inlineHelpText>Used in CaseRecurrenceBatch; determines the number of days before the Recurrence Due Date that a case should be cloned.</inlineHelpText>
        <label>Case Recurrence Lead Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseRecurrenceToEmail__c</fullName>
        <description>Used in CaseRecurrenceBatch to indicate who should receive the finish email; separate multiple recipients with a single comma.</description>
        <inlineHelpText>Indicate who should receive the CaseRecurrenceBatch finish email; separate multiple recipients with a single comma.</inlineHelpText>
        <label>Case Recurrence To Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Holds the NGAM settings</description>
    <label>NGAM Settings</label>
</CustomObject>

objects/NGAMSettingsHierarchy__c.object
<CustomObject>
    <fields>
        <fullName>ByPassAccountValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows entity to by-pass validation rules on Account</description>
        <inlineHelpText>Allows entity to by-pass validation rules on Account</inlineHelpText>
        <label>By-Pass Account Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NGAM Settings - Hierarchy</label>
</CustomObject>

classes/CaseRecurrenceBatchTest.cls
@isTest
public class CaseRecurrenceBatchTest {
    
    @testSetup
    static void setup() {
        
        NGAMSettingsHierarchy__c hsettings = NGAMSettingsHierarchy__c.getOrgDefaults();
        hsettings.ByPassAccountValidationRules__c  = TRUE;
        upsert hsettings NGAMSettingsHierarchy__c.Id;


        NGAMSettings__c settings = new NGAMSettings__c(Name = 'NGAM_ALL', CaseRecurrenceLeadTime__c = 30, CaseRecurrenceToEmail__c = 'dat@natixis.com');
        insert settings;
        
        List<Account> firms = DataFactory.createTestFirms(1);
        insert firms;
        List<Account> accts = DataFactory.createTestAccountswithFirms(1,firms);
        insert accts;
        List<Contact> contacts = DataFactory.createTestContacts(1,accts,FALSE);
        insert contacts;
        
        Date duedate = Date.newInstance(2016,12,10);
        
        List<Case> cases = new List<Case>();
        Case monthly = new Case(Subject = 'Monthly', Frequency__c = 'Monthly', DueDate__c = duedate, AccountId = accts[0].Id, 
                               ContactId = contacts[0].Id, CreateRecurrence__c = TRUE);        
        cases.add(monthly);
        
        Case quarterly = new Case(Subject = 'Quarterly', Frequency__c = 'Quarterly', DueDate__c = duedate, AccountId = accts[0].Id, ContactId = contacts[0].Id,
                               CreateRecurrence__c = TRUE);        
        cases.add(quarterly);
        
        Case semiannual = new Case(Subject = 'Semi-Annually', Frequency__c = 'Semi-Annually', DueDate__c = duedate, AccountId = accts[0].Id, ContactId = contacts[0].Id,
                               CreateRecurrence__c = TRUE);        
        cases.add(semiannual);
        
        Case annual = new Case(Subject = 'Annually', Frequency__c = 'Annually', DueDate__c = duedate, AccountId = accts[0].Id, ContactId = contacts[0].Id,
                               CreateRecurrence__c = TRUE);        
        cases.add(annual);
        insert cases;
        
    }
    
    @isTest static void caseRecurrenceBatchTest() {
        
        Test.startTest();
        Id batchJobId = Database.executeBatch(new CaseRecurrenceBatch());
        Test.stopTest();
        
        List<Case> allCases = [SELECT Id, Frequency__c, Subject, CreateRecurrence__c, DueDate__c, RecurrenceDate__c, RecurrenceSourceCase__c, RecurrenceTargetCase__c
                               FROM Case];
        
        system.debug('allCases: ' + allCases);

        List<Case> mCases = [SELECT Id, Frequency__c, Subject, CreateRecurrence__c, DueDate__c, RecurrenceDate__c, RecurrenceSourceCase__c, RecurrenceTargetCase__c
                                  FROM Case WHERE Frequency__c = 'Monthly' ORDER BY DueDate__c];
        
        List<Case> qCases = [SELECT Id, Frequency__c, Subject, CreateRecurrence__c, DueDate__c, RecurrenceDate__c, RecurrenceSourceCase__c, RecurrenceTargetCase__c
                                  FROM Case WHERE Frequency__c = 'Quarterly' ORDER BY DueDate__c];

        List<Case> sCases = [SELECT Id, Frequency__c, Subject, CreateRecurrence__c, DueDate__c, RecurrenceDate__c, RecurrenceSourceCase__c, RecurrenceTargetCase__c
                                  FROM Case WHERE Frequency__c = 'Semi-Annually' ORDER BY DueDate__c];

        List<Case> aCases = [SELECT Id, Frequency__c, Subject, CreateRecurrence__c, DueDate__c, RecurrenceDate__c, RecurrenceSourceCase__c, RecurrenceTargetCase__c
                                  FROM Case WHERE Frequency__c = 'Annually' ORDER BY DueDate__c];

        system.assertequals(allCases.size(),8);
        system.assertEquals(mCases[0].Id,mCases[1].RecurrenceSourceCase__c);
        system.assertEquals(mCases[0].RecurrenceDate__c, mCases[1].DueDate__c);

        system.assertEquals(mCases[0].RecurrenceDate__c,Date.newInstance(2017,1,10));
        system.assertEquals(qCases[0].RecurrenceDate__c,Date.newInstance(2017,3,10));
        system.assertEquals(sCases[0].RecurrenceDate__c,Date.newInstance(2017,6,10));
        system.assertEquals(aCases[0].RecurrenceDate__c,Date.newInstance(2017,12,10));
                
    }
    
}