objects/Case.object
<CustomObject>
    <fields>
        <fullName>PWEmail__c</fullName>
        <description>For Private Wealth Case, display the requestor's information</description>
        <label>Requestor Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>Private</sharingModel><enableHistory>true</enableHistory>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PWEmail__c</fullName>
        <description>This field is used by the Docusign process and required if a Contact is flagged as PW Active</description>
        <inlineHelpText>This field is used by the Docusign process and required if a Contact is flagged as PW Active</inlineHelpText>
        <label>Private Wealth Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Docusign_Settings__c.object
<CustomObject>
    <fields>
        <fullName>DSXPartnerApplication__c</fullName>
        <description>Version of DocuSign</description>
        <label>DSXPartnerApplication</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmailBody__c</fullName>
        <label>Email Body</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmailSubject__c</fullName>
        <label>Email Subject</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Point__c</fullName>
        <label>End Point</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>IntegratorKey__c</fullName>
        <label>IntegratorKey</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SendDocuSignMessageFromAttachments__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox controls whether the trigger on attachments sends a message/document request to DocuSign on insert.</description>
        <inlineHelpText>This checkbox controls whether the trigger on attachments sends a message/document request to DocuSign on insert.</inlineHelpText>
        <label>Send DocuSign Message From Attachments</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SigningGroupID__c</fullName>
        <label>Signing Group ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <description>DocuSign Username - email address</description>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>Docusign Settings</label>
</CustomObject>

objects/NGAMSettingsHierarchy__c.object
<CustomObject>
    <fields>
        <fullName>ByPassAccountValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows entity to by-pass validation rules on Account</description>
        <inlineHelpText>Allows entity to by-pass validation rules on Account</inlineHelpText>
        <label>By-Pass Account Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NGAM Settings - Hierarchy</label>
</CustomObject>

objects/Signers__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Signers</relationshipLabel>
        <relationshipName>Signers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EmailAddress__c</fullName>
        <label>Email Address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Signers</label>
    <nameField>
        <label>Signer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Signers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DocuSignAPITest.cls
@isTest
Public class DocuSignAPITest {
    
    @isTest static void testDocuSignAPI() {
        // Set mock callout class 
        
        NGAMSettingsHierarchy__c hsettings = NGAMSettingsHierarchy__c.getOrgDefaults();
        hsettings.ByPassAccountValidationRules__c  = TRUE;
        upsert hsettings NGAMSettingsHierarchy__c.Id;

        Account acc=new Account(Name='Natixis'); insert acc;
        
        Contact con = new Contact(LastName='Natixis',FirstName='Natixis',Email='natixis@natixis.com',AccountId=acc.Id,PWEmail__c='natixis@natixis.com'); insert con;
        
        Id recTypeIdCase = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Private Wealth Portal').getRecordTypeId();
        
        Case cas = new Case(AccountId=acc.Id,ContactId=con.Id,RecordTypeId=recTypeIdCase,Status='Needs Signature'); insert cas;
        
        Signers__c sing = new Signers__c(Name='Natixis',EmailAddress__c='natixis@natixis.com',Case__c=cas.Id); insert sing;
        
        Docusign_Settings__c docu = new Docusign_Settings__c(Name ='PWPortal',EmailBody__c='You have received a document from the Natixis Investment Portal to review and sign',EmailSubject__c='Documents for you to sign'
                                                             ,End_Point__c='https://demo.docusign.net/restapi/v2/accounts/7b1892e3-2040-4603-b6b1-b9dabb617110/envelopes',IntegratorKey__c='TEST',
                                                             Password__c='TEST',SigningGroupID__c='84021',Username__c='qhoman@mpa.natixis.com',DSXPartnerApplication__c='DSFS 6.8',
                                                             SendDocuSignMessageFromAttachments__c = TRUE); insert docu;
        
        Attachment attach=new Attachment();    
        attach.Name='Unit Test Attachment';
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        attach.body=bodyBlob;
        attach.parentId=cas.id;
        insert attach;
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorDocuSignAPI());
        DocuSignAPITriggerHandler.DocuSigTriggerAfterInsert(attach.Id);
        Test.stoptest();
    }
    
}