objects/CDRQualitativeData__c.object
<CustomObject>
    <fields>
        <fullName>EffectiveDate__c</fullName>
        <defaultValue>NOW()+30</defaultValue>
        <label>Effective Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SortOrder__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Staging</fullName>
                </value>
                <value>
                    <fullName>Pending Activation</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Historical</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>This object stores qualitative data about contacts, firms, products, additional information and their relationships to one another.</description>
    <label>CDR Qualitative Data</label>
    <nameField>
        <label>CDR Qualitative Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CDR Qualitative Data</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CDRSettings__c.object
<CustomObject>
    <fields>
        <fullName>OverrideSetStatusOnCreate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Keeps the trigger from assigning a new record to Draft status on creation.  Can be used for data loading directly into a specific status.</description>
        <inlineHelpText>Keeps the trigger from assigning a new record to Draft status on creation.  Can be used for data loading directly into a specific status.</inlineHelpText>
        <label>Override Set Status On Create</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OverrideTriggerValidations__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Overrides trigger validations on status changes, effective dates, etc. when editing or creating CDR Qualitative Data records</description>
        <inlineHelpText>Overrides trigger validations on status changes, effective dates, etc. when editing or creating CDR Qualitative Data records</inlineHelpText>
        <label>Override Trigger Validations</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Settings that control CDR processes</description>
    <label>CDR Settings</label>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACTIVE</fullName>
                </value>
                <value>
                    <fullName>CLOSED TO NEW INVESTORS</fullName>
                </value>
                <value>
                    <fullName>INACTIVE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CDRQualitativeDataCompareExtTest.cls
@istest
public class CDRQualitativeDataCompareExtTest {
    
    static testMethod void myTests() {
        
        CDRSettings__c settings = new CDRSettings__c(Name = 'NGAM', 
                                                     OverrideTriggerValidations__c = TRUE,
                                                     OverrideSetStatusOnCreate__c = TRUE);
        insert settings;
        
        Id nullId;
        
        List<Product2> products = DataFactory.createProduct2(1,'CDR Test');
        products[0].Name = 'Product 0';
        insert products;
        
        List<CDRQualitativeData__c> cdrs = new List<CDRQualitativeData__c>();
        
        List<CDRQualitativeData__c> CDR1 = DataFactory.createCDRQualitativeData (1, 'Mutual Fund', products[0].Id, nullId);
        CDR1[0].Status__c = 'Draft';
        CDR1[0].SortOrder__c = 10;
        CDR1[0].EffectiveDate__c = datetime.newInstance(1977,1,1);
        cdrs.add(CDR1[0]);
        
        List<CDRQualitativeData__c> CDR2 = DataFactory.createCDRQualitativeData (1, 'Mutual Fund', products[0].Id, nullId);
        CDR2[0].Status__c = 'Staging';
        CDR2[0].SortOrder__c = 20;
        CDR2[0].EffectiveDate__c = datetime.newInstance(1977,1,2);
        cdrs.add(CDR2[0]);
        insert cdrs;        
        
        Test.startTest();
        Test.setCurrentPage(Page.CDRQualitativeDataCompare);
        CDRQualitativeDataCompareExt CDRSummary = new CDRQualitativeDataCompareExt(new ApexPages.StandardController(CDR1[0]));
        CDRSummary.compareCDRId = cdrs[1].Id;
        CDRSummary.dispAllValues = TRUE;
        
        Test.stopTest();
        
    }
    
    
    
    
    
    
}