objects/CDRSettings__c.object
<CustomObject>
    <fields>
        <fullName>BusinessHoursName__c</fullName>
        <description>Used in loading product performance data.  This should be a record that is 24-Hours, M-F, GMT.  The stock market holidays for each year must be associated with the Business Hours.</description>
        <inlineHelpText>Used in loading product performance data.  This should be a record that is 24-Hours, M-F, GMT.  The stock market holidays for each year must be associated with the Business Hours.</inlineHelpText>
        <label>Business Hours Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Settings that control CDR processes</description>
    <label>CDR Settings</label>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>LegalName__c</fullName>
        <label>Legal Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProductCharacteristic__c.object
<CustomObject>
    <fields>
        <fullName>Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used in PB to initiate time-based workflow which sets Published__c to TRUE 0 Days after PublishDate__c</description>
        <label>Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AsOfDate__c</fullName>
        <description>The as of date of the Product Characteristic; set via integrations during creation</description>
        <label>As Of Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Set via integrations during create.  Represents the Product to which this Product Characteristic belongs.</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Characteristics</relationshipLabel>
        <relationshipName>ProductCharacteristics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Set by integration on create</description>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FundAdmin Characteristics File</fullName>
                </value>
                <value>
                    <fullName>FundAdmin Expenses File</fullName>
                </value>
                <value>
                    <fullName>IPM ASG Characteristics File</fullName>
                </value>
                <value>
                    <fullName>IPM LSMAI Characteristics File</fullName>
                </value>
                <value>
                    <fullName>IPM LSSA Characteristics File</fullName>
                </value>
                <value>
                    <fullName>IPM LSSFR Characteristics File</fullName>
                </value>
                <value>
                    <fullName>IPM McDonnell Characteristics File</fullName>
                </value>
                <value>
                    <fullName>IPM Mirova Characteristics File</fullName>
                </value>
                <value>
                    <fullName>IPM MPT Port Stats File</fullName>
                </value>
                <value>
                    <fullName>IPM NSFF Characteristics File</fullName>
                </value>
                <value>
                    <fullName>Loomis Characteristics File</fullName>
                </value>
                <value>
                    <fullName>State Street Top 10 Holdings File</fullName>
                </value>
                <value>
                    <fullName>FactSet Equity Characteristics File</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Set via integrations during create.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asset Allocation</fullName>
                </value>
                <value>
                    <fullName>Asset Classes and Segments</fullName>
                </value>
                <value>
                    <fullName>Characteristics</fullName>
                </value>
                <value>
                    <fullName>Country</fullName>
                </value>
                <value>
                    <fullName>Coupon</fullName>
                </value>
                <value>
                    <fullName>Coupon detail</fullName>
                </value>
                <value>
                    <fullName>Credit quality</fullName>
                </value>
                <value>
                    <fullName>Currency</fullName>
                </value>
                <value>
                    <fullName>Duration</fullName>
                </value>
                <value>
                    <fullName>Duration detail</fullName>
                </value>
                <value>
                    <fullName>Environmental projects breakdown</fullName>
                </value>
                <value>
                    <fullName>ESG Opinion</fullName>
                </value>
                <value>
                    <fullName>Expenses</fullName>
                </value>
                <value>
                    <fullName>Exposure summary</fullName>
                </value>
                <value>
                    <fullName>Global Sector</fullName>
                </value>
                <value>
                    <fullName>Holdings</fullName>
                </value>
                <value>
                    <fullName>Industry</fullName>
                </value>
                <value>
                    <fullName>Long Positions</fullName>
                </value>
                <value>
                    <fullName>Market capitalization</fullName>
                </value>
                <value>
                    <fullName>Maturity</fullName>
                </value>
                <value>
                    <fullName>Maturity detail</fullName>
                </value>
                <value>
                    <fullName>Number of holdings</fullName>
                </value>
                <value>
                    <fullName>Portfolio composition</fullName>
                </value>
                <value>
                    <fullName>Portfolio exposures</fullName>
                </value>
                <value>
                    <fullName>Portfolio Factor Exposures Summary</fullName>
                </value>
                <value>
                    <fullName>Property Type</fullName>
                </value>
                <value>
                    <fullName>Region</fullName>
                </value>
                <value>
                    <fullName>Sector</fullName>
                </value>
                <value>
                    <fullName>Sector-LS</fullName>
                </value>
                <value>
                    <fullName>Short Positions</fullName>
                </value>
                <value>
                    <fullName>Top ten holdings</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Holds characteristics about products for the CDR</description>
    <label>Product Characteristic</label>
    <nameField>
        <displayFormat>PC-{0000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Characteristics</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ProductCharApprovalControllerTest.cls
@isTest
public class ProductCharApprovalControllerTest {
    
    static testMethod void myTest() {
        
        CDRSettings__c settings = new CDRSettings__c(Name = 'NGAM', 
                                                     BusinessHoursName__c = '24 Hours, Monday - Friday GMT');
        insert settings;
        
        Id MFRecTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('Mutual Fund').getRecordTypeId();
        List<Product2> mfp = DataFactory.createProduct2(2,'MF_');
        
        mfp[0].RecordTypeId = MFRecTypeId;
        mfp[0].LegalName__c = 'Mutual Fund Legal Name';
        mfp[1].RecordTypeId = MFRecTypeId;
        mfp[1].LegalName__c = '';
        insert mfp;
        
        List<ProductCharacteristic__c> prodChar = new List<ProductCharacteristic__c>();
        Date AsOfDate = Date.newInstance(2018,04,30);
        prodChar.add(new ProductCharacteristic__c(Type__c = 'Top ten holdings', AsOfDate__c = AsOfDate, Product__c = mfp[0].Id, Approved__c = FALSE, Source__c = 'State Street Top 10 Holdings File'));
        prodChar.add(new ProductCharacteristic__c(Type__c = 'Top ten holdings', AsOfDate__c = AsOfDate, Product__c = mfp[0].Id, Approved__c = TRUE, Source__c = 'State Street Top 10 Holdings File'));
        prodChar.add(new ProductCharacteristic__c(Type__c = 'Top ten holdings', AsOfDate__c = AsOfDate, Product__c = mfp[1].Id, Approved__c = FALSE, Source__c = 'State Street Top 10 Holdings File'));
        prodChar.add(new ProductCharacteristic__c(Type__c = 'Characteristics', AsOfDate__c = AsOfDate, Product__c = mfp[0].Id, Approved__c = FALSE, Source__c = 'State Street Top 10 Holdings File'));
        prodChar.add(new ProductCharacteristic__c(Type__c = 'Top ten holdings', AsOfDate__c = AsOfDate, Product__c = mfp[0].Id, Approved__c = FALSE, Source__c = 'IPM ASG Characteristics File'));
        insert prodChar;
        
        Test.startTest();                       

        Test.setCurrentPage(Page.ProductCharacteristicApproval);
        List<ProductCharacteristic__c> selectedProdCharList = new List<ProductCharacteristic__c>();

        ProductCharApprovalController c = new ProductCharApprovalController();
        c.go();
        c.choiceProduct = prodChar[0].Product__c;
		c.selections();
        c.choiceType = prodChar[0].Type__c;
        c.selections();
        c.choiceSource = prodChar[0].Source__c;
        c.selections();
        c.go();
        c.wrapProdCharList[0].selected = TRUE;
        selectedProdCharList.add(c.wrapProdCharList[0].pc);
        c.approveSelected();
        
        Test.stopTest();		        

        List<ProductCharacteristic__c> testCheck = [SELECT Id, Approved__c
                                                    FROM ProductCharacteristic__c];

        for (ProductCharacteristic__c tc : testCheck) {
            if (tc.Id == prodChar[0].Id) system.assertEquals(TRUE, tc.Approved__c, 'Newly Approved Product Characteristic');
            if (tc.Id == prodChar[1].Id) system.assertEquals(TRUE, tc.Approved__c, 'Still Approved Product Characteristic');
            if (tc.Id == prodChar[2].Id) system.assertEquals(FALSE, tc.Approved__c, 'Still Not Approved Product Characteristic');
            if (tc.Id == prodChar[3].Id) system.assertEquals(FALSE, tc.Approved__c, 'Still Not Approved Product Characteristic');
            if (tc.Id == prodChar[3].Id) system.assertEquals(FALSE, tc.Approved__c, 'Still Not Approved Product Characteristic');
        }
        
    }    
    

}