objects/CDRSettings__c.object
<CustomObject>
    <fields>
        <fullName>ProdPerfBatchLASTNDAYS__c</fullName>
        <description>In Product Peformance batches, this is used to select Product Performance records that have been modified in the "Last N Days".  This should be set to at least 7 days to catch Morningstar changes.  You must still use the date ranges for the Roll-up Batch</description>
        <inlineHelpText>In Product Peformance batches, this is used to select Product Performance records that have As Of Dates in the "Last N Days".  This should be set to at least 7 days to catch Morningstar changes.</inlineHelpText>
        <label>Prod Perf Batch LAST_N_DAYS</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Settings that control CDR processes</description>
    <label>CDR Settings</label>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>ParentProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProductPerformance__c.object
<CustomObject>
    <fields>
        <fullName>AsOfDate__c</fullName>
        <label>As of Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExternalID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Performance</relationshipLabel>
        <relationshipName>ProductPerformance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SharesOutstanding__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Shares Outstanding</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalNetAssets__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Net Assets</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Product Performance</label>
    <nameField>
        <displayFormat>PP-{0000000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Performance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ProdPerfMaintRollupBatch.cls
global class ProdPerfMaintRollupBatch implements Database.Batchable<sObject> {
    
    Id ShareClassRecTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('Share Class').getRecordTypeId();

    public CDRSettings__c settings = CDRSettings__c.getvalues('NGAM');
    String lastNDaysParm = settings.ProdPerfBatchLASTNDAYS__c;
    
    global final String query = ' SELECT Id, AsOfDate__c, Product__c, Product__r.ParentProduct__c ' +
        ' FROM ProductPerformance__c ' +
        ' WHERE Product__r.RecordTypeId = :ShareClassRecTypeId ' +
        ' AND AsOfDate__c = LAST_N_DAYS:' + lastNDaysParm + ' ' +
        ' ORDER BY Product__r.ParentProduct__c, AsOfDate__c DESC';
    
    global ProdPerfMaintRollupBatch() {
        
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {      
        System.Debug('Query - ' + query);
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<ProductPerformance__c> scope) {
        
        Set<Id> parentProductIdSet = new Set<Id>();
        Set<Date> asOfDateSet = new Set<Date>();
        Map<String,ProductPerformance__c> parentProdPerfMap = new Map<String,ProductPerformance__c>();
        
        for (ProductPerformance__c pp : scope) {
            parentProductIdSet.add(pp.Product__r.ParentProduct__c);
            asOfDateSet.add(pp.AsOfDate__c);
        }
        
        AggregateResult[] groupedResults = [SELECT Product__r.ParentProduct__c ppId, AsOfDate__c aod, SUM(TotalNetAssets__c) TNA, SUM(SharesOutstanding__c) SO
                                            FROM ProductPerformance__c
                                            WHERE Product__r.ParentProduct__c in :parentProductIdSet
                                            AND AsOfDate__c in :asOfDateSet
                                            GROUP BY Product__r.ParentProduct__c, AsOfDate__c];
        
        for (AggregateResult ar : groupedResults)  {
            String parentProductId = (String)ar.get('ppId');
            Date parentProductAsOfDate = (Date)ar.get('aod');
            String parentProdPerfExtId = parentProductId + '|' + parentProductAsOfDate.format();
            parentProdPerfMap.put(parentProdPerfExtId, new ProductPerformance__c(Product__c = parentProductId, TotalNetAssets__c = (Decimal)ar.get('TNA'), SharesOutstanding__c = (Decimal)ar.get('SO'),
                                                                                 AsOfDate__c = parentProductAsOfDate, ExternalId__c = parentProdPerfExtId));
        }
        
        upsert parentProdPerfMap.values() ExternalId__c;
        
    }
    
    
    global void finish(Database.BatchableContext BC) {
        
        Id batchJobId = Database.executeBatch(new ProdPerfMaintDateBatch());

    }
    
}