objects/CDRSettings__c.object
<CustomObject>
    <fields>
        <fullName>BusinessHoursName__c</fullName>
        <description>Used in loading product performance data.  This should be a record that is 24-Hours, M-F, GMT.  The stock market holidays for each year must be associated with the Business Hours.</description>
        <inlineHelpText>Used in loading product performance data.  This should be a record that is 24-Hours, M-F, GMT.  The stock market holidays for each year must be associated with the Business Hours.</inlineHelpText>
        <label>Business Hours Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Settings that control CDR processes</description>
    <label>CDR Settings</label>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>InceptionDate__c</fullName>
        <label>Inception Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MaxInternalProductPerformance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Max Internal Product Performance</label>
        <referenceTo>ProductPerformance__c</referenceTo>
        <relationshipLabel>Products (Max Internal Product Performance)</relationshipLabel>
        <relationshipName>ProductsMaxInternal</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ParentProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ShareClass__c</fullName>
        <label>Share Class</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ShareClass</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ThreadbackPerformanceShareClass__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to create the footnote that the given share class includes performance from another share class.</description>
        <inlineHelpText>If the product's performance includes performance data from another share class, choose the associated share class.</inlineHelpText>
        <label>Threadback Performance Share Class</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The associated share class must share the same parent mutual fund product</errorMessage>
            <filterItems>
                <field>$Source.ParentProduct__c</field>
                <operation>equals</operation>
                <valueField>$Source.ParentProduct__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products (Threadback Performance Share Class)</relationshipLabel>
        <relationshipName>ThreadbackProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProductPerformance__c.object
<CustomObject>
    <fields>
        <fullName>AsOfDate__c</fullName>
        <label>As of Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>InceptionDate__c</fullName>
        <formula>Product__r.InceptionDate__c</formula>
        <label>Inception Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsAsofDateBusinessDate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Business Date?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsMonthEnd__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Month End?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsQuarterEnd__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Quarter End?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsYearEnd__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Year End?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MSCYTD__c</fullName>
        <label>MSC YTD</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>NAVYTD__c</fullName>
        <label>NAV YTD</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>PriorBusinessDate__c</fullName>
        <label>Prior Business Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PriorMonthEndDate__c</fullName>
        <label>Prior Month End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PriorQuarterEndDate__c</fullName>
        <label>Prior Quarter End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PriorYearEndDate__c</fullName>
        <label>Prior Year End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Performance</relationshipLabel>
        <relationshipName>ProductPerformance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PublishInternally__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Publish Internally?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ShareClass__c</fullName>
        <formula>TEXT(Product__r.ShareClass__c)</formula>
        <label>Share Class</label>
        <type>Text</type>
    </fields>
    <label>Product Performance</label>
    <nameField>
        <displayFormat>PP-{0000000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Performance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/ShareClass.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
    </customValue>
    <customValue>
        <fullName>B</fullName>
    </customValue>
    <customValue>
        <fullName>C</fullName>
    </customValue>
    <customValue>
        <fullName>N</fullName>
    </customValue>
    <customValue>
        <fullName>T</fullName>
    </customValue>
    <customValue>
        <fullName>Y</fullName>
    </customValue>
    <customValue>
        <fullName>Admin</fullName>
    </customValue>
    <customValue>
        <fullName>Advisor</fullName>
    </customValue>
    <customValue>
        <fullName>Institutional</fullName>
    </customValue>
    <customValue>
        <fullName>Investor</fullName>
    </customValue>
    <customValue>
        <fullName>Retail</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <masterLabel>Share Class</masterLabel>
</GlobalValueSet>

classes/ProdPerfProductExtTest.cls
@isTest
public class ProdPerfProductExtTest {
    
    @isTest
    public static void myTest()
    {
        
        CDRSettings__c settings = new CDRSettings__c(name='NGAM', BusinessHoursName__c = '24 Hours, Monday - Friday GMT');
        insert settings;

        Id SCRecTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('Share Class').getRecordTypeId();
        Id MFRecTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('Mutual Fund').getRecordTypeId();
        
        Date inceptionDateOld = Date.newInstance(2001,1,15);
        Date inceptionDateNew = Date.newInstance(2015,1,15);
        Date asOfDate = Date.newInstance(2017,11,7);
        Date priorBusinessDate = Date.newInstance(2017,11,6);
        Date pMEDate = Date.newInstance(2017,10,31);
        Date pQEDate = Date.newInstance(2017,9,30);
        Date p0YEDate = Date.newInstance(2016,12,31);
        Date p1YEDate = Date.newInstance(2015,12,31);
        Date p2YEDate = Date.newInstance(2014,12,31);
        Date p3YEDate = Date.newInstance(2013,12,31);
        Date p4YEDate = Date.newInstance(2012,12,31);
        Date p5YEDate = Date.newInstance(2011,12,31);
        Date p6YEDate = Date.newInstance(2010,12,31);
        Date p7YEDate = Date.newInstance(2009,12,31);
        Date p8YEDate = Date.newInstance(2008,12,31);
        Date p9YEDate = Date.newInstance(2007,12,31);
                
        List<Product2> prod = DataFactory.createProduct2(2,'Test_');
        prod[0].InceptionDate__c = inceptionDateOld;
        prod[0].RecordTypeId = MFRecTypeId;
        prod[1].InceptionDate__c = inceptionDateOld;
        prod[1].RecordTypeId = MFRecTypeId;
        insert prod;
        
        Id MFProd0Id = prod[0].Id;
        Id MFProd1Id = prod[1].Id;
        
        List<Product2> cprod = DataFactory.createProduct2(2,'TestChild_');
        cprod[0].InceptionDate__c = inceptionDateOld;
        cprod[0].ParentProduct__c = prod[0].Id;
        cprod[0].ShareClass__c = 'A';
        cprod[0].RecordTypeId = SCRecTypeId;
        
        cprod[1].InceptionDate__c = inceptionDateNew;
        cprod[1].ParentProduct__c = prod[0].Id;
        cprod[1].ShareClass__c = 'Y';
        cprod[1].RecordTypeId = SCRecTypeId;
        insert cprod;

        cprod[0].ThreadbackPerformanceShareClass__c = cprod[1].Id;
        update cprod;

        Id SCProd0Id = cprod[0].Id;
        Id SCProd1Id = cprod[1].Id;
        
        List<ProductPerformance__c> pp = new List<ProductPerformance__c>();
        pp.add(new ProductPerformance__c(AsOfDate__c = asOfDate,Product__c=MFProd0Id, PriorBusinessDate__c = priorBusinessDate,IsAsOfDateBusinessDate__c = TRUE,PublishInternally__c=TRUE));
        pp.add(new ProductPerformance__c(AsOfDate__c = priorBusinessDate,Product__c=MFProd0Id, PriorBusinessDate__c = priorBusinessDate.addDays(-1),IsAsOfDateBusinessDate__c = FALSE,PublishInternally__c = TRUE));

        
        pp.add(new ProductPerformance__c(AsOfDate__c = asOfDate,Product__c=SCProd0Id, PriorBusinessDate__c = priorBusinessDate, PriorMonthEndDate__c = pMEDate, 
                                        PriorQuarterEndDate__c = pQEDate, PriorYearEndDate__c = p0YEDate, IsAsOfDateBusinessDate__c = TRUE,PublishInternally__c = TRUE));
        pp.add(new ProductPerformance__c(AsOfDate__c = priorBusinessDate,Product__c=SCProd0Id, PriorBusinessDate__c = priorBusinessDate.addDays(-1), PriorMonthEndDate__c = pMEDate, 
                                        PriorQuarterEndDate__c = pQEDate, PriorYearEndDate__c = p0YEDate, IsAsOfDateBusinessDate__c = FALSE,PublishInternally__c = TRUE));
        pp.add(new ProductPerformance__c(AsOfDate__c = pMEDate,Product__c=SCProd0Id,IsMonthEnd__c=TRUE,NAVYTD__c=.99,MSCYTD__c=.99,PublishInternally__c = TRUE));
        pp.add(new ProductPerformance__c(AsOfDate__c = pQEDate,Product__c=SCProd0Id,IsMonthEnd__c=TRUE,IsQuarterEnd__c=TRUE, NAVYTD__c=-.99,MSCYTD__c=-.99,PublishInternally__c = TRUE));
        pp.add(new ProductPerformance__c(AsOfDate__c = p0YEDate,Product__c=SCProd0Id,IsMonthEnd__c=TRUE,IsQuarterEnd__c=TRUE, IsYearEnd__c=TRUE,PublishInternally__c = TRUE));
        pp.add(new ProductPerformance__c(AsOfDate__c = p1YEDate,Product__c=SCProd0Id,IsMonthEnd__c=TRUE,IsQuarterEnd__c=TRUE, IsYearEnd__c=TRUE,PublishInternally__c = TRUE));
        pp.add(new ProductPerformance__c(AsOfDate__c = p2YEDate,Product__c=SCProd0Id,IsMonthEnd__c=TRUE,IsQuarterEnd__c=TRUE, IsYearEnd__c=TRUE,PublishInternally__c = TRUE));
        pp.add(new ProductPerformance__c(AsOfDate__c = p3YEDate,Product__c=SCProd0Id,IsMonthEnd__c=TRUE,IsQuarterEnd__c=TRUE, IsYearEnd__c=TRUE,PublishInternally__c = TRUE));
        pp.add(new ProductPerformance__c(AsOfDate__c = p4YEDate,Product__c=SCProd0Id,IsMonthEnd__c=TRUE,IsQuarterEnd__c=TRUE, IsYearEnd__c=TRUE,PublishInternally__c = TRUE));
        pp.add(new ProductPerformance__c(AsOfDate__c = p5YEDate,Product__c=SCProd0Id,IsMonthEnd__c=TRUE,IsQuarterEnd__c=TRUE, IsYearEnd__c=TRUE,PublishInternally__c = TRUE));
        pp.add(new ProductPerformance__c(AsOfDate__c = p6YEDate,Product__c=SCProd0Id,IsMonthEnd__c=TRUE,IsQuarterEnd__c=TRUE, IsYearEnd__c=TRUE,PublishInternally__c = TRUE));
        pp.add(new ProductPerformance__c(AsOfDate__c = p7YEDate,Product__c=SCProd0Id,IsMonthEnd__c=TRUE,IsQuarterEnd__c=TRUE, IsYearEnd__c=TRUE,PublishInternally__c = TRUE));
        pp.add(new ProductPerformance__c(AsOfDate__c = p8YEDate,Product__c=SCProd0Id,IsMonthEnd__c=TRUE,IsQuarterEnd__c=TRUE, IsYearEnd__c=TRUE,PublishInternally__c = TRUE));
        pp.add(new ProductPerformance__c(AsOfDate__c = p9YEDate,Product__c=SCProd0Id,IsMonthEnd__c=TRUE,IsQuarterEnd__c=TRUE, IsYearEnd__c=TRUE,PublishInternally__c = TRUE));
        insert pp;
        
        prod[0].MaxInternalProductPerformance__c = pp[0].Id;
        update prod;
        cprod[0].MaxInternalProductPerformance__c = pp[2].Id;
        update cprod;
        
        
        
        
        
       
        Test.StartTest();
        Test.setCurrentPage(Page.ProdPerfShareClass);
        ProdPerfProductExt controller1 = new ProdPerfProductExt(new ApexPages.StandardController(cprod[0]));
        controller1.ppcd = Date.newInstance(2017,11,6);
        PageReference nextPage1 = controller1.getProductPerf();
        controller1.ppcd = Date.newInstance(2017,11,3);
        PageReference nextPage2 = controller1.getProductPerf();        
        Test.setCurrentPage(Page.ProdPerfMutualFund);
        ProdPerfProductExt controller2 = new ProdPerfProductExt(new ApexPages.StandardController(prod[0]));
        controller2.ppcd = Date.newInstance(2017,11,6);
        PageReference nextPage3 = controller2.getChildProductPerf();
        Test.StopTest();
        
    } 
    
}