objects/CDRSettings__c.object
<CustomObject>
    <fields>
        <fullName>BusinessHoursName__c</fullName>
        <description>Used in loading product performance data.  This should be a record that is 24-Hours, M-F, GMT.  The stock market holidays for each year must be associated with the Business Hours.</description>
        <inlineHelpText>Used in loading product performance data.  This should be a record that is 24-Hours, M-F, GMT.  The stock market holidays for each year must be associated with the Business Hours.</inlineHelpText>
        <label>Business Hours Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProdPerfBatchLASTNDAYS__c</fullName>
        <description>In Product Peformance batches, this is used to select Product Performance records that have been modified in the "Last N Days".  This should be set to at least 7 days to catch Morningstar changes.  You must still use the date ranges for the Roll-up Batch</description>
        <inlineHelpText>In Product Peformance batches, this is used to select Product Performance records that have As Of Dates in the "Last N Days".  This should be set to at least 7 days to catch Morningstar changes.</inlineHelpText>
        <label>Prod Perf Batch LAST_N_DAYS</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Settings that control CDR processes</description>
    <label>CDR Settings</label>
</CustomObject>

objects/ProductPerformance__c.object
<CustomObject>
    <fields>
        <fullName>AsOfDate__c</fullName>
        <label>As of Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExternalID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IsAsofDateBusinessDate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Business Date?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsMonthEnd__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Month End?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsQuarterEnd__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Quarter End?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsYearEnd__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Year End?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MonthEndDate__c</fullName>
        <description>The Month End date associated with the row.  Used to simplify querying.</description>
        <label>Month End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NextBusinessDateProdPerfExtId__c</fullName>
        <externalId>true</externalId>
        <label>Next Business Date Prod Perf ExtId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NextBusinessDate__c</fullName>
        <label>Next Business Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PriorBusinessDate__c</fullName>
        <label>Prior Business Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PriorDate__c</fullName>
        <label>Prior Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PriorMonthEndBusinessDate__c</fullName>
        <label>Prior Month End Business Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PriorMonthEndDate__c</fullName>
        <label>Prior Month End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PriorMonthEndProdPerfExtId__c</fullName>
        <externalId>true</externalId>
        <label>Prior Month End Prod Perf ExtId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PriorPriorMonthEndBusinessDate__c</fullName>
        <label>Prior Prior Month End Business Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PriorPriorMonthEndDate__c</fullName>
        <label>Prior Prior Month End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PriorProductPerfExtId__c</fullName>
        <description>System field used by Informatica to do faster joins</description>
        <externalId>true</externalId>
        <label>Prior Product Perf ExtId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PriorQuarterEndBusinessDate__c</fullName>
        <label>Prior Quarter End Business Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PriorQuarterEndDate__c</fullName>
        <label>Prior Quarter End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PriorQuarterEndProdPerfExtId__c</fullName>
        <externalId>true</externalId>
        <label>Prior Quarter End Prod Perf ExtId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PriorYearEndBusinessDate__c</fullName>
        <label>Prior Year End Business Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PriorYearEndDate__c</fullName>
        <label>Prior Year End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PriorYearEndProdPerfExtId__c</fullName>
        <externalId>true</externalId>
        <label>Prior Year End Prod Perf ExtId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Performance</relationshipLabel>
        <relationshipName>ProductPerformance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QuarterEndDate__c</fullName>
        <description>Quarter End Date associated with the row.  Used to simplify querying.</description>
        <label>Quarter End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SharesOutstanding__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Shares Outstanding</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalNetAssets__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Net Assets</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>YearEndDate__c</fullName>
        <description>Year End date associated with the data row.  Used to simplify querying.</description>
        <label>Year End Date</label>
        <type>Date</type>
    </fields>
    <label>Product Performance</label>
    <nameField>
        <displayFormat>PP-{0000000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Performance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ProdPerfMaintDateBatch.cls
global class ProdPerfMaintDateBatch implements Database.Batchable<sObject> {
    
    public CDRSettings__c settings = CDRSettings__c.getvalues('NGAM');
    String BHName = settings.BusinessHoursName__c;
    String lastNDaysParm = settings.ProdPerfBatchLASTNDAYS__c;
    
    public String  query = ' SELECT Id, AsOfDate__c, Product__c, PriorDate__c, PriorBusinessDate__c, MonthEndDate__c, PriorMonthEndDate__c, PriorMonthEndBusinessDate__c, IsAsOfDateBusinessDate__c, ' +
        ' QuarterEndDate__c, PriorQuarterEndDate__c, PriorQuarterEndBusinessDate__c, YearEndDate__c, PriorYearEndDate__c, PriorYearEndBusinessDate__c, IsYearEnd__c, IsMonthEnd__c, ' +
        ' IsQuarterEnd__c, PriorProductPerfExtId__c, PriorMonthEndProdPerfExtId__c, PriorQuarterEndProdPerfExtId__c, PriorYearEndProdPerfExtId__c, ' +
        ' TotalNetAssets__c, SharesOutstanding__c, ExternalID__c, NextBusinessDate__c, NextBusinessDateProdPerfExtId__c ' +
        ' FROM ProductPerformance__c ' +
        ' WHERE AsOfDate__c = LAST_N_DAYS:' + lastNDaysParm + ' ' +
        ' ORDER BY AsOfDate__c ' ;
    
    public businessHours bh = [SELECT Id, MondayEndTime, MondayStartTime, TuesdayEndTime, TuesdayStartTime, WednesdayEndTime, 
                               WednesdayStartTime, ThursdayEndTime, ThursdayStartTime, FridayEndTime, FridayStartTime, SaturdayEndTime, 
                               SaturdayStartTime, SundayEndTime, SundayStartTime 
                               FROM BusinessHours WHERE Name = :BHName LIMIT 1];
    
    public List<Holiday> holidays = [SELECT Id, ActivityDate, RecurrenceType, RecurrenceDayOfMonth, RecurrenceMonthOfYear from Holiday];    
    
    global ProdPerfMaintDateBatch() {
        
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {      
        System.Debug('Query - ' + query);
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<ProductPerformance__c> scope) {
        
        Map<Date, ProductPerformance__c> dateMap = new Map<Date, ProductPerformance__c>();
        List<ProductPerformance__c> prodPerfToUpdate = new List<ProductPerformance__c>();
        
        for (ProductPerformance__c npp : scope) {
            
            if (!dateMap.containsKey(npp.AsOfDate__c)) {
                
                ProductPerformance__c ppDateWork = new ProductPerformance__c(AsOfDate__c = npp.AsOfDate__c);
                
                // Dates
                ppDateWork.PriorDate__c = ppDateWork.AsOfDate__c.addDays(-1);
                
                ppDateWork.PriorBusinessDate__c = getPriorBusinessDate(bh, holidays, ppDateWork.AsOfDate__c);
                ppDateWork.NextBusinessDate__c = getFutureBusinessDate(bh, holidays, ppDateWork.AsOfDate__c, 1);
                ppDateWork.IsAsOfDateBusinessDate__c = BusinessHours.isWithin(bh.Id, ppDateWork.AsOfDate__c);
                
                // Month-End Dates
                Integer daysInMonth = Date.daysInMonth(ppDateWork.AsOfDate__c.year(),ppDateWork.AsOfDate__c.month());
                ppDateWork.MonthEndDate__c = Date.newInstance(ppDateWork.AsOfDate__c.year(),ppDateWork.AsOfDate__c.month(),daysInMonth);    
                
                Date priorMonthDate = ppDateWork.AsOfDate__c.addMonths(-1);
                Date priorPriorMonthDate = ppDateWork.AsOfDate__c.addMonths(-2);
                Integer priorDaysInMonth = Date.daysInMonth(priorMonthDate.year(),priorMonthDate.month());
                Integer priorPriorDaysInMonth = Date.daysInMonth(priorPriorMonthDate.year(),priorPriorMonthDate.month());
                ppDateWork.PriorMonthEndDate__c = Date.newInstance(priorMonthDate.year(),priorMonthDate.month(),priorDaysInMonth);   
                ppDateWork.PriorMonthEndBusinessDate__c = getPriorBusinessDate(bh, holidays,ppDateWork.PriorMonthEndDate__c);
                ppDateWork.PriorPriorMonthEndDate__c = Date.newInstance(priorPriorMonthDate.year(),priorPriorMonthDate.month(),priorPriorDaysInMonth); 
                ppDateWork.PriorPriorMonthEndBusinessDate__c = getPriorBusinessDate(bh, holidays, priorPriorMonthDate);
                
                //Quarter End Dates
                If (ppDateWork.AsOfDate__c.month() == 1 || ppDateWork.AsOfDate__c.month() == 2 || ppDateWork.AsOfDate__c.month() == 3){
                    ppDateWork.QuarterEndDate__c = date.newInstance(ppDateWork.AsOfDate__c.year(),3,31);
                    ppDateWork.PriorQuarterEndDate__c = date.newInstance(ppDateWork.AsOfDate__c.year()-1,12,31);
                    ppDateWork.PriorQuarterEndBusinessDate__c = getPriorBusinessDate(bh, holidays, ppDateWork.PriorQuarterEndDate__c);
                }
                If (ppDateWork.AsOfDate__c.month() == 4 || ppDateWork.AsOfDate__c.month() == 5 || ppDateWork.AsOfDate__c.month() == 6){
                    ppDateWork.QuarterEndDate__c = date.newInstance(ppDateWork.AsOfDate__c.year(),6,30);
                    ppDateWork.PriorQuarterEndDate__c = date.newInstance(ppDateWork.AsOfDate__c.year(),3,31);
                    ppDateWork.PriorQuarterEndBusinessDate__c = getPriorBusinessDate(bh, holidays, ppDateWork.PriorQuarterEndDate__c);
                    
                }
                If (ppDateWork.AsOfDate__c.month() == 7 || ppDateWork.AsOfDate__c.month() == 8 || ppDateWork.AsOfDate__c.month() == 9){
                    ppDateWork.QuarterEndDate__c = date.newInstance(ppDateWork.AsOfDate__c.year(),9,30);
                    ppDateWork.PriorQuarterEndDate__c = date.newInstance(ppDateWork.AsOfDate__c.year(),6,30);
                    ppDateWork.PriorQuarterEndBusinessDate__c = getPriorBusinessDate(bh, holidays, ppDateWork.PriorQuarterEndDate__c);
                }
                If (ppDateWork.AsOfDate__c.month() == 10 || ppDateWork.AsOfDate__c.month() == 11 || ppDateWork.AsOfDate__c.month() == 12){
                    ppDateWork.QuarterEndDate__c = date.newInstance(ppDateWork.AsOfDate__c.year(),12,31);
                    ppDateWork.PriorQuarterEndDate__c = date.newInstance(ppDateWork.AsOfDate__c.year(),9,30);
                    ppDateWork.PriorQuarterEndBusinessDate__c = getPriorBusinessDate(bh, holidays, ppDateWork.PriorQuarterEndDate__c);
                }
                
                //Year End Dates            
                ppDateWork.YearEndDate__c = date.newInstance(ppDateWork.AsOfDate__c.year(),12,31);
                ppDateWork.PriorYearEndDate__c = date.newInstance(ppDateWork.AsOfDate__c.year()-1,12,31);
                ppDateWork.PriorYearEndBusinessDate__c = getPriorBusinessDate(bh, holidays, ppDateWork.PriorYearEndDate__c);
                
                //Period Checkboxes
                if (ppDateWork.AsOfDate__c.isSameDay(ppDateWork.YearEndDate__c)) ppDateWork.IsYearEnd__c = TRUE;
                if (ppDateWork.AsOfDate__c.isSameDay(ppDateWork.MonthEndDate__c)) ppDateWork.IsMonthEnd__c = TRUE;
                if (ppDateWork.AsOfDate__c.isSameDay(ppDateWork.QuarterEndDate__c)) ppDateWork.IsQuarterEnd__c = TRUE;
                
                dateMap.put(ppDateWork.AsOfDate__c, ppDateWork);
            }
            
            ProductPerformance__c ppDates = dateMap.get(npp.AsOfDate__c);
            
            npp.PriorDate__c = ppDates.PriorDate__c;
            npp.PriorBusinessDate__c = ppDates.PriorBusinessDate__c;
            npp.MonthEndDate__c = ppDates.MonthEndDate__c;   
            npp.PriorMonthEndDate__c = ppDates.PriorMonthEndDate__c;
            npp.PriorMonthEndBusinessDate__c = ppDates.PriorMonthEndBusinessDate__c;
            npp.IsAsOfDateBusinessDate__c = ppDates.IsAsOfDateBusinessDate__c;
            npp.QuarterEndDate__c = ppDates.QuarterEndDate__c;
            npp.PriorQuarterEndDate__c = ppDates.PriorQuarterEndDate__c;
            npp.PriorQuarterEndBusinessDate__c = ppDates.PriorQuarterEndBusinessDate__c;
            npp.YearEndDate__c = ppDates.YearEndDate__c;
            npp.PriorYearEndDate__c = ppDates.PriorYearEndDate__c;
            npp.PriorYearEndBusinessDate__c = ppDates.PriorYearEndBusinessDate__c;
            npp.IsYearEnd__c = ppDates.IsYearEnd__c;
            npp.IsMonthEnd__c = ppDates.IsMonthEnd__c;
            npp.IsQuarterEnd__c = ppDates.IsQuarterEnd__c;
            npp.PriorProductPerfExtId__c = ppDates.PriorProductPerfExtId__c;
            npp.PriorMonthEndProdPerfExtId__c = ppDates.PriorMonthEndProdPerfExtId__c;
            npp.PriorQuarterEndProdPerfExtId__c = ppDates.PriorQuarterEndProdPerfExtId__c;
            npp.PriorYearEndProdPerfExtId__c = ppDates.PriorYearEndProdPerfExtId__c;
            npp.PriorPriorMonthEndBusinessDate__c = ppDates.PriorPriorMonthEndBusinessDate__c;
            npp.PriorPriorMonthEndDate__c = ppDates.PriorPriorMonthEndDate__c;
            npp.NextBusinessDate__c = ppDates.NextBusinessDate__c;
            
            if (npp.IsAsofDateBusinessDate__c) {
                npp.NextBusinessDateProdPerfExtId__c = npp.Product__c + '|' + npp.NextBusinessDate__c.format();
            } else if (npp.IsMonthEnd__c && !npp.IsAsofDateBusinessDate__c) {
                npp.NextBusinessDateProdPerfExtId__c = npp.Product__c + '|' + npp.NextBusinessDate__c.format() + 'ME';
            }
            
            npp.PriorProductPerfExtId__c = npp.Product__c + '|' + npp.PriorBusinessDate__c.format();
            npp.PriorMonthEndProdPerfExtId__c = npp.Product__c + '|' + npp.PriorMonthEndDate__c.format();
            npp.PriorQuarterEndProdPerfExtId__c = npp.Product__c + '|' + npp.PriorQuarterEndDate__c.format();
            npp.PriorYearEndProdPerfExtId__c = npp.Product__c + '|' + npp.PriorYearEndDate__c.format();
            
            prodPerfToUpdate.add(npp);
            
        }
        
        upsert prodPerfToUpdate;
    }  
    
    public date getPriorBusinessDate(BusinessHours bh, List<Holiday> h, Date myDate) {
        
        BusinessHoursMath businessHoursMath = new BusinessHoursMath();
        businessHoursMath.setBusinessHours(bh);
        businessHoursMath.setHolidays(h);
        Date returnDate;
        
        Integer i = 1;
        while (1==1) {
            
            if (businessHoursMath.isBusinessDay(myDate.addDays(-i))) {
                returnDate = myDate.addDays(-i);
                break;
            }
            i++;
        }
        return returnDate;
    }
    
    global void finish(Database.BatchableContext BC) {
        
        Id batchJobId = Database.executeBatch(new ProdPerfMaintRefBatch());
        
    }
    
    public date getFutureBusinessDate(BusinessHours bh, List<Holiday> h, Date myDate, Integer numberOfBusinessDays) {
        
        BusinessHoursMath businessHoursMath = new BusinessHoursMath();
        businessHoursMath.setBusinessHours(bh);
        businessHoursMath.setHolidays(h);
        Date returnDate;
        
        Integer BDCount = 0;
        Integer i = 1;
        while (BDCount < numberOfBusinessDays) {
            
            if (businessHoursMath.isBusinessDay(myDate.addDays(i))) {
                returnDate = myDate.addDays(i);
                BDCount++;
            }
            i++;
        }
        
        return returnDate;
    }    
    
}