objects/CDRSettings__c.object
<CustomObject>
    <fields>
        <fullName>BusinessHoursName__c</fullName>
        <description>Used in loading product performance data.  This should be a record that is 24-Hours, M-F, GMT.  The stock market holidays for each year must be associated with the Business Hours.</description>
        <inlineHelpText>Used in loading product performance data.  This should be a record that is 24-Hours, M-F, GMT.  The stock market holidays for each year must be associated with the Business Hours.</inlineHelpText>
        <label>Business Hours Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Settings that control CDR processes</description>
    <label>CDR Settings</label>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Top10HoldingsPublishingSchedule__c</fullName>
        <description>Used in Apex to set the Product Characteristic publishing schedule for Top 10 Holdings.</description>
        <label>Top 10 Holdings Publishing Schedule</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CDRPublishingSchedule</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProductCharacteristic__c.object
<CustomObject>
    <fields>
        <fullName>Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used in PB to initiate time-based workflow which sets Published__c to TRUE 0 Days after PublishDate__c</description>
        <label>Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AsOfDate__c</fullName>
        <description>The as of date of the Product Characteristic; set via integrations during creation</description>
        <label>As Of Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CharacteristicsDataType__c</fullName>
        <description>Loaded during integration; used in trigger to formulate Product Characteristics Output Text and Index Characteristics Output Text</description>
        <label>Characteristics Data Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Integer</fullName>
                </value>
                <value>
                    <fullName>Decimal</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Percent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IndexCharacteristicsDecimal__c</fullName>
        <description>Holds the decimal (percent, integer, decimal) for the index from the characteristics file if the related value if a number; otherwise this is null.  Loaded from integration.</description>
        <label>Index Characteristics Decimal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IndexCharacteristicsInteger__c</fullName>
        <label>Index Characteristics Integer</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IndexCharacteristicsOutputText__c</fullName>
        <description>Created by trigger on insert</description>
        <label>Index Characteristics Output Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IndexCharacteristicsText__c</fullName>
        <description>Holds the text from the index characteristics file if the related value if a text; otherwise this is null.  Loaded from integration.</description>
        <label>Index Characteristics Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductCharacteristicsDecimal__c</fullName>
        <description>Holds the decimal (percent, integer, decimal) for the product from the characteristics file if the related value if a number; otherwise this is null.  Loaded from integration.</description>
        <label>Product Characteristics Decimal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProductCharacteristicsInteger__c</fullName>
        <label>Product Characteristics Integer</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProductCharacteristicsOutputText__c</fullName>
        <description>Created by trigger on insert</description>
        <label>Product Characteristics Output Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductCharacteristicsText__c</fullName>
        <description>Holds the text from the product characteristics file if the related value if a text; otherwise this is null.  Loaded from integration.</description>
        <label>Product Characteristics Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Set via integrations during create.  Represents the Product to which this Product Characteristic belongs.</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Characteristics</relationshipLabel>
        <relationshipName>ProductCharacteristics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PublishDate__c</fullName>
        <description>Set by Apex, used in PB to set Published__c</description>
        <label>Publish Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PublishingSchedule__c</fullName>
        <description>Used in Apex to set PublishDate__c</description>
        <label>Publishing Schedule</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CDRPublishingSchedule</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SecurityName__c</fullName>
        <description>Set via integrations during create if applicable</description>
        <label>Security Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Set via integrations during create.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asset Allocation</fullName>
                </value>
                <value>
                    <fullName>Asset Classes and Segments</fullName>
                </value>
                <value>
                    <fullName>Characteristics</fullName>
                </value>
                <value>
                    <fullName>Country</fullName>
                </value>
                <value>
                    <fullName>Coupon</fullName>
                </value>
                <value>
                    <fullName>Coupon detail</fullName>
                </value>
                <value>
                    <fullName>Credit quality</fullName>
                </value>
                <value>
                    <fullName>Currency</fullName>
                </value>
                <value>
                    <fullName>Duration</fullName>
                </value>
                <value>
                    <fullName>Duration detail</fullName>
                </value>
                <value>
                    <fullName>Environmental projects breakdown</fullName>
                </value>
                <value>
                    <fullName>ESG Opinion</fullName>
                </value>
                <value>
                    <fullName>Expenses</fullName>
                </value>
                <value>
                    <fullName>Exposure summary</fullName>
                </value>
                <value>
                    <fullName>Global Sector</fullName>
                </value>
                <value>
                    <fullName>Holdings</fullName>
                </value>
                <value>
                    <fullName>Industry</fullName>
                </value>
                <value>
                    <fullName>Long Positions</fullName>
                </value>
                <value>
                    <fullName>Market capitalization</fullName>
                </value>
                <value>
                    <fullName>Maturity</fullName>
                </value>
                <value>
                    <fullName>Maturity detail</fullName>
                </value>
                <value>
                    <fullName>Number of holdings</fullName>
                </value>
                <value>
                    <fullName>Portfolio composition</fullName>
                </value>
                <value>
                    <fullName>Portfolio exposures</fullName>
                </value>
                <value>
                    <fullName>Portfolio Factor Exposures Summary</fullName>
                </value>
                <value>
                    <fullName>Property Type</fullName>
                </value>
                <value>
                    <fullName>Region</fullName>
                </value>
                <value>
                    <fullName>Sector</fullName>
                </value>
                <value>
                    <fullName>Sector-LS</fullName>
                </value>
                <value>
                    <fullName>Short Positions</fullName>
                </value>
                <value>
                    <fullName>Top ten holdings</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Holds characteristics about products for the CDR</description>
    <label>Product Characteristic</label>
    <nameField>
        <displayFormat>PC-{0000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Characteristics</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/CDRPublishingSchedule.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Never</fullName>
        <default>true</default>
        <label>Never</label>
    </customValue>
    <customValue>
        <fullName>Immediately</fullName>
    </customValue>
    <customValue>
        <fullName>7th Business Day</fullName>
    </customValue>
    <customValue>
        <fullName>8th Calendar Day</fullName>
    </customValue>
    <customValue>
        <fullName>1st Business Day After the Following Month-End</fullName>
    </customValue>
    <customValue>
        <fullName>10th Business Day After Quarter-End</fullName>
    </customValue>
    <description>Used in Apex to control publishing schedule of product characteristics</description>
    <masterLabel>CDR Publishing Schedule</masterLabel>
</GlobalValueSet>

classes/ProductCharacteristicTriggerHandlerTest.cls
@isTest
public class ProductCharacteristicTriggerHandlerTest {
    
    static testMethod void SetPublishScheduleAndDate() {
        
        CDRSettings__c settings = new CDRSettings__c(Name = 'NGAM', 
                                                     BusinessHoursName__c = '24 Hours, Monday - Friday GMT');
        insert settings;
        
        Id MFRecTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('Mutual Fund').getRecordTypeId();
        List<Product2> mfp = DataFactory.createProduct2(7,'MF_');
        
        mfp[0].RecordTypeId = MFRecTypeId;
        mfp[0].Top10HoldingsPublishingSchedule__c = 'Never';
        
        mfp[1].RecordTypeId = MFRecTypeId;
        mfp[1].Top10HoldingsPublishingSchedule__c = 'Immediately';
        
        mfp[2].RecordTypeId = MFRecTypeId;
        mfp[2].Top10HoldingsPublishingSchedule__c = '7th Business Day';
        
        mfp[3].RecordTypeId = MFRecTypeId;
        mfp[3].Top10HoldingsPublishingSchedule__c = '8th Calendar Day';
        
        mfp[4].RecordTypeId = MFRecTypeId;
        mfp[4].Top10HoldingsPublishingSchedule__c = '1st Business Day After the Following Month-End';
        
        mfp[5].RecordTypeId = MFRecTypeId;
        mfp[5].Top10HoldingsPublishingSchedule__c = '10th Business Day After Quarter-End';
        
        insert mfp;
        
        List<ProductCharacteristic__c> prodChar = new List<ProductCharacteristic__c>();
        Date AsOfDate = Date.newInstance(2018,04,30);
        Date AsOfDateFirstIsNotBusiness = Date.newInstance(2018,05,31);
        Date AsOfDateQ1 = Date.newInstance(2018,01,31);
        Date AsOfDateQ2 = Date.newInstance(2018,05,31);
        Date AsOfDateQ3 = Date.newInstance(2018,08,30);        
        Date AsOfDateQ4 = Date.newInstance(2018,10,31);        
        prodChar.add(new ProductCharacteristic__c(Type__c = 'Top ten holdings', AsOfDate__c = AsOfDate, Product__c = mfp[0].Id));
        prodChar.add(new ProductCharacteristic__c(Type__c = 'Top ten holdings', AsOfDate__c = AsOfDate, Product__c = mfp[1].Id));
        prodChar.add(new ProductCharacteristic__c(Type__c = 'Top ten holdings', AsOfDate__c = AsOfDate, Product__c = mfp[2].Id));
        prodChar.add(new ProductCharacteristic__c(Type__c = 'Top ten holdings', AsOfDate__c = AsOfDate, Product__c = mfp[3].Id));
        prodChar.add(new ProductCharacteristic__c(Type__c = 'Top ten holdings', AsOfDate__c = AsOfDate, Product__c = mfp[4].Id, SecurityName__c = '1st is Business'));
        prodChar.add(new ProductCharacteristic__c(Type__c = 'Top ten holdings', AsOfDate__c = AsOfDateFirstIsNotBusiness, Product__c = mfp[4].Id, SecurityName__c = '1st is not Business'));
        prodChar.add(new ProductCharacteristic__c(Type__c = 'Top ten holdings', AsOfDate__c = AsOfDate, Product__c = mfp[5].Id));        
        prodChar.add(new ProductCharacteristic__c(Type__c = 'Top ten holdings', AsOfDate__c = AsOfDateQ1, Product__c = mfp[5].Id, SecurityName__c = 'Q1'));       
        prodChar.add(new ProductCharacteristic__c(Type__c = 'Top ten holdings', AsOfDate__c = AsOfDateQ2, Product__c = mfp[5].Id, SecurityName__c = 'Q2'));       
        prodChar.add(new ProductCharacteristic__c(Type__c = 'Top ten holdings', AsOfDate__c = AsOfDateQ3, Product__c = mfp[5].Id, SecurityName__c = 'Q3'));       
        prodChar.add(new ProductCharacteristic__c(Type__c = 'Top ten holdings', AsOfDate__c = AsOfDateQ4, Product__c = mfp[5].Id, SecurityName__c = 'Q4'));       
        prodChar.add(new ProductCharacteristic__c(Type__c = 'Foo', AsOfDate__c = AsOfDate, Product__c = mfp[5].Id, SecurityName__c = 'Not Top ten holdings'));       

        prodChar.add(new ProductCharacteristic__c(Type__c = 'Characteristics', AsOfDate__c = AsOfDate, Product__c = mfp[0].Id,CharacteristicsDataType__c='Integer',ProductCharacteristicsInteger__c=433,IndexCharacteristicsInteger__c=200));
        prodChar.add(new ProductCharacteristic__c(Type__c = 'Characteristics', AsOfDate__c = AsOfDate, Product__c = mfp[0].Id,CharacteristicsDataType__c='Decimal',ProductCharacteristicsDecimal__c=4.2,IndexCharacteristicsDecimal__c=4));
        prodChar.add(new ProductCharacteristic__c(Type__c = 'Characteristics', AsOfDate__c = AsOfDate, Product__c = mfp[0].Id,CharacteristicsDataType__c='Text',ProductCharacteristicsText__c='ABC',IndexCharacteristicsText__c='DEF'));
        prodChar.add(new ProductCharacteristic__c(Type__c = 'Characteristics', AsOfDate__c = AsOfDate, PublishDate__c = date.today(), Approved__c = TRUE, Product__c = mfp[0].Id,CharacteristicsDataType__c='Text',ProductCharacteristicsText__c='ABC',IndexCharacteristicsText__c='DEF'));
        prodChar.add(new ProductCharacteristic__c(Type__c = 'Characteristics', AsOfDate__c = AsOfDate, PublishDate__c = date.today(), Approved__c = FALSE, Product__c = mfp[0].Id,CharacteristicsDataType__c='Text',ProductCharacteristicsText__c='ABC',IndexCharacteristicsText__c='DEF'));        
        
        Test.startTest();
        insert prodChar;
        prodChar[15].Approved__c = TRUE;
        update prodChar;
        Test.stopTest();		        
        
        List<ProductCharacteristic__c> testCheck = [SELECT Id, Type__c,
                                                    Product__r.Top10HoldingsPublishingSchedule__c,
                                                    PublishingSchedule__c, 
                                                    PublishDate__c, 
                                                    SecurityName__c,
                                                    CharacteristicsDataType__c,
                                                    ProductCharacteristicsOutputText__c,
                                                    IndexCharacteristicsOutputText__c FROM ProductCharacteristic__c
                                                    WHERE Id in :prodChar];
        
        for (ProductCharacteristic__c tc : testCheck) {
            if (tc.Type__c == 'Top ten holdings') {
                if (tc.Product__r.Top10HoldingsPublishingSchedule__c == 'Never') {
                    system.assertEquals('Never', tc.PublishingSchedule__c, 'Top 10 Holdings Publishing Schedule - Never'); 
                    system.assertEquals(null, tc.PublishDate__c, 'Top 10 Holdings Publish Date - Never'); 
                }
                if (tc.Product__r.Top10HoldingsPublishingSchedule__c == 'Immediately') {
                    system.assertEquals('Immediately', tc.PublishingSchedule__c, 'Top 10 Holdings Publishing Schedule - Immediately'); 
                    system.assertEquals(AsOfDate, tc.PublishDate__c, 'Top 10 Holdings Publish Date - Never'); 
                } 
                if (tc.Product__r.Top10HoldingsPublishingSchedule__c == '7th Business Day') {
                    system.assertEquals('7th Business Day', tc.PublishingSchedule__c, 'Top 10 Holdings Publishing Schedule - 7th Business Day'); 
                    system.assertEquals(Date.newInstance(2018,05,09), tc.PublishDate__c, 'Top 10 Holdings Publish Date - 7th Business Day'); 
                }
                if (tc.Product__r.Top10HoldingsPublishingSchedule__c == '8th Calendar Day') {
                    system.assertEquals('8th Calendar Day', tc.PublishingSchedule__c, 'Top 10 Holdings Publishing Schedule - 8th Calendar Day'); 
                    system.assertEquals(Date.newInstance(2018,05,08), tc.PublishDate__c, 'Top 10 Holdings Publish Date - 8th Calendar Day'); 
                }
                if (tc.Product__r.Top10HoldingsPublishingSchedule__c == '1st Business Day After the Following Month-End') {
                    system.assertEquals('1st Business Day After the Following Month-End', tc.PublishingSchedule__c, 'Top 10 Holdings Publishing Schedule - 1st Business Day After the Following Month-End'); 
                    if (tc.SecurityName__c == '1st is not Business') system.assertEquals(Date.newInstance(2018,07,02), tc.PublishDate__c, 'Top 10 Holdings Publish Date - 1st Business Day After the Following Month-End - First Not Business'); 
                    if (tc.SecurityName__c == '1st is Business') system.assertEquals(Date.newInstance(2018,06,01), tc.PublishDate__c, 'Top 10 Holdings Publish Date - 1st Business Day After the Following Month-End'); 
                }
                if (tc.Product__r.Top10HoldingsPublishingSchedule__c == '10th Business Day After Quarter-End') {
                    system.assertEquals('10th Business Day After Quarter-End', tc.PublishingSchedule__c, 'Top 10 Holdings Publishing Schedule - 10th Business Day After Quarter-End'); 
                    if (String.isBlank(tc.SecurityName__c)) system.assertEquals(Date.newInstance(2018,07,16), tc.PublishDate__c, 'Top 10 Holdings Publish Date - 10th Business Day After Quarter-End'); 
                    if (tc.SecurityName__c == 'Q1') system.assertEquals(Date.newInstance(2018,04,13), tc.PublishDate__c, 'Top 10 Holdings Publish Date - 10th Business Day After Quarter-End');                 
                    if (tc.SecurityName__c == 'Q2') system.assertEquals(Date.newInstance(2018,07,16), tc.PublishDate__c, 'Top 10 Holdings Publish Date - 10th Business Day After Quarter-End'); 
                    if (tc.SecurityName__c == 'Q3') system.assertEquals(Date.newInstance(2018,10,12), tc.PublishDate__c, 'Top 10 Holdings Publish Date - 10th Business Day After Quarter-End'); 
                    if (tc.SecurityName__c == 'Q4') system.assertEquals(Date.newInstance(2019,01,15), tc.PublishDate__c, 'Top 10 Holdings Publish Date - 10th Business Day After Quarter-End'); 
                }
            }
            if (tc.Type__c == 'Foo') {
                system.assertEquals(Date.newInstance(2018,04,30), tc.PublishDate__c, 'Characteristics - Immediately'); 
            }

            if (tc.Type__c == 'Characteristics' && tc.CharacteristicsDataType__c == 'Integer') {
                system.assertEquals('433', tc.ProductCharacteristicsOutputText__c, 'Characteristics - Integer Product Output Text'); 
                system.assertEquals('200', tc.IndexCharacteristicsOutputText__c, 'Characteristics - Integer Index Output Text');                 
            }
            
            if (tc.Type__c == 'Characteristics' && tc.CharacteristicsDataType__c == 'Decimal') {
                system.assertEquals('4.20', tc.ProductCharacteristicsOutputText__c, 'Characteristics - Decimal Product Output Text'); 
                system.assertEquals('4.00', tc.IndexCharacteristicsOutputText__c, 'Characteristics - Decimal Index Output Text');                 
            }
            
            if (tc.Type__c == 'Characteristics' && tc.CharacteristicsDataType__c == 'Text') {
                system.assertEquals('ABC', tc.ProductCharacteristicsOutputText__c, 'Characteristics - Text Product Output Text'); 
                system.assertEquals('DEF', tc.IndexCharacteristicsOutputText__c, 'Characteristics - Text Index Output Text');                 
            }
            
        }        
    }        
}