objects/CDRSettings__c.object
<CustomObject>
    <fields>
        <fullName>DeleteFundstation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used in ProdPerfMainDeleteBatch to determine if Fundstation product performance should be deleted</description>
        <inlineHelpText>Used in ProdPerfMainDeleteBatch to determine if Fundstation product performance should be deleted</inlineHelpText>
        <label>Delete Fundstation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DeleteHarris__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used in ProdPerfMainDeleteBatch to determine if Harris product performance should be deleted</description>
        <inlineHelpText>Used in ProdPerfMainDeleteBatch to determine if Harris product performance should be deleted</inlineHelpText>
        <label>Delete Harris</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProdPerfMaintDeleteBatchFromDate__c</fullName>
        <description>Used in ProdPerfMainDeleteBatch to determine the date from which product performance rows should be deleted.</description>
        <inlineHelpText>Used in ProdPerfMainDeleteBatch to determine the date from which product performance rows should be deleted.</inlineHelpText>
        <label>Prod Perf Maint Delete Batch From Date</label>
        <type>Date</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Settings that control CDR processes</description>
    <label>CDR Settings</label>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>InceptionDate__c</fullName>
        <label>Inception Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MaxExternalProductPerformance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Max External Product Performance</label>
        <referenceTo>ProductPerformance__c</referenceTo>
        <relationshipLabel>Products (Max External Product Performance)</relationshipLabel>
        <relationshipName>ProductsMaxExternal</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MaxInternalProductPerformance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Max Internal Product Performance</label>
        <referenceTo>ProductPerformance__c</referenceTo>
        <relationshipLabel>Products (Max Internal Product Performance)</relationshipLabel>
        <relationshipName>ProductsMaxInternal</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ParentProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProductPerformance__c.object
<CustomObject>
    <fields>
        <fullName>AsOfDate__c</fullName>
        <label>As of Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AuditFlag__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Audit Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AuditMessage__c</fullName>
        <defaultValue>'Not Audited'</defaultValue>
        <label>Audit Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExternalID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>InceptionDate__c</fullName>
        <formula>Product__r.InceptionDate__c</formula>
        <label>Inception Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsAsofDateBusinessDate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Business Date?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsMonthEnd__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Month End?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsQuarterEnd__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Quarter End?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsYearEnd__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Year End?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MonthEndDate__c</fullName>
        <description>The Month End date associated with the row.  Used to simplify querying.</description>
        <label>Month End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PriorBusinessDate__c</fullName>
        <label>Prior Business Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PriorDate__c</fullName>
        <label>Prior Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PriorMonthEndBusinessDate__c</fullName>
        <label>Prior Month End Business Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PriorMonthEndDate__c</fullName>
        <label>Prior Month End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PriorMonthEndProdPerfExtId__c</fullName>
        <externalId>true</externalId>
        <label>Prior Month End Prod Perf ExtId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PriorMonthEndProductPerformance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prior Month End Product Performance</label>
        <referenceTo>ProductPerformance__c</referenceTo>
        <relationshipLabel>Product Performance (Prior Month End Product Performance)</relationshipLabel>
        <relationshipName>PriorMonthEndProductPerformance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PriorProductPerfExtId__c</fullName>
        <description>System field used by Informatica to do faster joins</description>
        <externalId>true</externalId>
        <label>Prior Product Perf ExtId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PriorProductPerformance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prior Product Performance</label>
        <referenceTo>ProductPerformance__c</referenceTo>
        <relationshipLabel>Product Performance</relationshipLabel>
        <relationshipName>ProductPerformance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PriorQuarterEndBusinessDate__c</fullName>
        <label>Prior Quarter End Business Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PriorQuarterEndDate__c</fullName>
        <label>Prior Quarter End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PriorQuarterEndProdPerfExtId__c</fullName>
        <externalId>true</externalId>
        <label>Prior Quarter End Prod Perf ExtId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PriorQuarterEndProductPerformance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prior Quarter End Product Performance</label>
        <referenceTo>ProductPerformance__c</referenceTo>
        <relationshipLabel>Product Performance (Prior Quarter End Product Performance)</relationshipLabel>
        <relationshipName>PriorQuarterEndProductPerformance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PriorYearEndBusinessDate__c</fullName>
        <label>Prior Year End Business Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PriorYearEndDate__c</fullName>
        <label>Prior Year End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PriorYearEndProdPerfExtId__c</fullName>
        <externalId>true</externalId>
        <label>Prior Year End Prod Perf ExtId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PriorYearEndProductPerformance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prior Year End Product Performance</label>
        <referenceTo>ProductPerformance__c</referenceTo>
        <relationshipLabel>Product Performance (Prior Year End Product Performance)</relationshipLabel>
        <relationshipName>PriorYearEndProductPerformance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Performance</relationshipLabel>
        <relationshipName>ProductPerformance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PublishExternally__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Publish Externally?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PublishInternally__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Publish Internally?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>QuarterEndDate__c</fullName>
        <description>Quarter End Date associated with the row.  Used to simplify querying.</description>
        <label>Quarter End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SourceSystem__c</fullName>
        <label>Source System</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fundstation</fullName>
                </value>
                <value>
                    <fullName>Harris</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>YearEndDate__c</fullName>
        <description>Year End date associated with the data row.  Used to simplify querying.</description>
        <label>Year End Date</label>
        <type>Date</type>
    </fields>
    <label>Product Performance</label>
    <nameField>
        <displayFormat>PP-{0000000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Performance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ProdPerfMaintDeleteBatch.cls
global class ProdPerfMaintDeleteBatch implements Database.Batchable<sObject>, Database.Stateful {
    
    global Set<Id> prodIdSet = new Set<Id>();
	global Set<Id> parentProdIdSet = new Set<Id>();        
    global Map<Id,Product2> pToUpdateMap = new Map<Id,Product2>();
    
    public CDRSettings__c settings = CDRSettings__c.getvalues('NGAM');
    Date fromDate = settings.ProdPerfMaintDeleteBatchFromDate__c;
    Boolean deleteHarris = settings.DeleteHarris__c;
    Boolean deleteFundstation = settings.DeleteFundstation__c;
    
    public String query = ' SELECT Id, AsOfDate__c, Product__c, Product__r.ParentProduct__c, PriorDate__c, PriorBusinessDate__c, MonthEndDate__c, PriorMonthEndDate__c, PriorMonthEndBusinessDate__c, IsAsOfDateBusinessDate__c, ' +
        ' QuarterEndDate__c, PriorQuarterEndDate__c, PriorQuarterEndBusinessDate__c, YearEndDate__c, PriorYearEndDate__c, PriorYearEndBusinessDate__c, IsYearEnd__c, IsMonthEnd__c, ' +
        ' IsQuarterEnd__c, PriorProductPerfExtId__c, PriorMonthEndProdPerfExtId__c, PriorQuarterEndProdPerfExtId__c, PriorYearEndProdPerfExtId__c, ' +
        ' PriorProductPerformance__c, PriorMonthEndProductPerformance__c, PriorQuarterEndProductPerformance__c, PriorYearEndProductPerformance__c, ExternalID__c, ' +
        ' PublishInternally__c, PublishExternally__c, AuditFlag__c, AuditMessage__c, Product__r.InceptionDate__c, SourceSystem__c ' +        
        ' FROM ProductPerformance__c ' +
        ' WHERE AsOfDate__c >= :fromDate ' ;
    
    global ProdPerfMaintDeleteBatch() {
        
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {      
        System.Debug('Query - ' + query);
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<ProductPerformance__c> scope) {
        
        List<ProductPerformance__c> ppToDelete = new List<ProductPerformance__c>();
        
        for (ProductPerformance__c pp : scope) {
            if (deleteHarris && pp.SourceSystem__c == 'Harris') {
                ppToDelete.add(pp);
                prodIdSet.add(pp.Product__c);
                parentProdIdSet.add(pp.Product__r.ParentProduct__c);
            }
            
            if (deleteFundstation && pp.SourceSystem__c == 'Fundstation') {
                ppToDelete.add(pp);
                prodIdSet.add(pp.Product__c);
                parentProdIdSet.add(pp.Product__r.ParentProduct__c);
            }
            
        }
        
        for (ProductPerformance__c parentPP : [SELECT Id, Product__c FROM ProductPerformance__c 
                                               WHERE Product__c in :parentProdIdSet
                                               AND AsOfDate__c >= :fromDate]) {
                                                   prodIdSet.add(parentPP.Product__c);                                        
                                                   ppToDelete.add(parentPP);                                                    
                                               }
        
        delete ppToDelete;
        
    }
    
    global void finish(Database.BatchableContext BC) {
        
        for (Product2 p : [SELECT Id, MaxInternalProductPerformance__c, MaxExternalProductPerformance__c, 
                           (SELECT Id
                            FROM ProductPerformance__r 
                            WHERE PublishInternally__c = TRUE
                            AND IsAsOfDateBusinessDate__c = TRUE
                            ORDER BY AsOfDate__c DESC LIMIT 1) 
                           FROM Product2
                           WHERE Id in :prodIdSet]) {
                               
                               for (ProductPerformance__c pp : p.ProductPerformance__r ) {
                                   
                                   if (pToUpdateMap.containsKey(p.Id)) {
                                       Product2 pt = pToUpdateMap.get(p.Id);
                                       pt.MaxInternalProductPerformance__c = pp.Id;
                                       pToUpdateMap.put(p.Id,pt);
                                   } else {
                                       Product2 pt = new Product2(Id = p.Id, MaxInternalProductPerformance__c = pp.Id);
                                       pToUpdateMap.put(p.Id,pt);
                                   }
                                   
                               }
                           }
        
        for (Product2 p : [SELECT Id, MaxInternalProductPerformance__c, MaxExternalProductPerformance__c, 
                           (SELECT Id 
                            FROM ProductPerformance__r 
                            WHERE PublishExternally__c = TRUE
                            AND IsAsOfDateBusinessDate__c = TRUE
                            ORDER BY AsOfDate__c DESC LIMIT 1) 
                           FROM Product2
                           WHERE Id in :prodIdSet]) {
                               
                               for (ProductPerformance__c pp : p.ProductPerformance__r ) {
                                   
                                   if (pToUpdateMap.containsKey(p.Id)) {
                                       Product2 pt = pToUpdateMap.get(p.Id);
                                       pt.MaxExternalProductPerformance__c = pp.Id;
                                       pToUpdateMap.put(p.Id,pt);
                                   } else {
                                       Product2 pt = new Product2(Id = p.Id, MaxExternalProductPerformance__c = pp.Id);
                                       pToUpdateMap.put(p.Id,pt);
                                   }
                                   
                               }
                           }
        
        update pToUpdateMap.values();             
        
    }
    
}