objects/CDRSettings__c.object
<CustomObject>
    <fields>
        <fullName>ProdPerfBatchLASTNDAYS__c</fullName>
        <description>In Product Peformance batches, this is used to select Product Performance records that have been modified in the "Last N Days".  This should be set to at least 7 days to catch Morningstar changes.  You must still use the date ranges for the Roll-up Batch</description>
        <inlineHelpText>In Product Peformance batches, this is used to select Product Performance records that have As Of Dates in the "Last N Days".  This should be set to at least 7 days to catch Morningstar changes.</inlineHelpText>
        <label>Prod Perf Batch LAST_N_DAYS</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Settings that control CDR processes</description>
    <label>CDR Settings</label>
</CustomObject>

objects/ProductPerformance__c.object
<CustomObject>
    <fields>
        <fullName>AsOfDate__c</fullName>
        <label>As of Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExternalID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IsAsofDateBusinessDate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Business Date?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsMonthEnd__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Month End?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsQuarterEnd__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Quarter End?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsYearEnd__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Year End?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MonthEndDate__c</fullName>
        <description>The Month End date associated with the row.  Used to simplify querying.</description>
        <label>Month End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PriorBusinessDate__c</fullName>
        <label>Prior Business Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PriorDate__c</fullName>
        <label>Prior Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PriorMonthEndBusinessDate__c</fullName>
        <label>Prior Month End Business Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PriorMonthEndDate__c</fullName>
        <label>Prior Month End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PriorMonthEndProdPerfExtId__c</fullName>
        <externalId>true</externalId>
        <label>Prior Month End Prod Perf ExtId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PriorMonthEndProductPerformance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prior Month End Product Performance</label>
        <referenceTo>ProductPerformance__c</referenceTo>
        <relationshipLabel>Product Performance (Prior Month End Product Performance)</relationshipLabel>
        <relationshipName>PriorMonthEndProductPerformance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PriorProductPerfExtId__c</fullName>
        <description>System field used by Informatica to do faster joins</description>
        <externalId>true</externalId>
        <label>Prior Product Perf ExtId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PriorProductPerformance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prior Product Performance</label>
        <referenceTo>ProductPerformance__c</referenceTo>
        <relationshipLabel>Product Performance</relationshipLabel>
        <relationshipName>ProductPerformance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PriorQuarterEndBusinessDate__c</fullName>
        <label>Prior Quarter End Business Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PriorQuarterEndDate__c</fullName>
        <label>Prior Quarter End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PriorQuarterEndProdPerfExtId__c</fullName>
        <externalId>true</externalId>
        <label>Prior Quarter End Prod Perf ExtId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PriorQuarterEndProductPerformance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prior Quarter End Product Performance</label>
        <referenceTo>ProductPerformance__c</referenceTo>
        <relationshipLabel>Product Performance (Prior Quarter End Product Performance)</relationshipLabel>
        <relationshipName>PriorQuarterEndProductPerformance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PriorYearEndBusinessDate__c</fullName>
        <label>Prior Year End Business Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PriorYearEndDate__c</fullName>
        <label>Prior Year End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PriorYearEndProdPerfExtId__c</fullName>
        <externalId>true</externalId>
        <label>Prior Year End Prod Perf ExtId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PriorYearEndProductPerformance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prior Year End Product Performance</label>
        <referenceTo>ProductPerformance__c</referenceTo>
        <relationshipLabel>Product Performance (Prior Year End Product Performance)</relationshipLabel>
        <relationshipName>PriorYearEndProductPerformance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Performance</relationshipLabel>
        <relationshipName>ProductPerformance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QuarterEndDate__c</fullName>
        <description>Quarter End Date associated with the row.  Used to simplify querying.</description>
        <label>Quarter End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>YearEndDate__c</fullName>
        <description>Year End date associated with the data row.  Used to simplify querying.</description>
        <label>Year End Date</label>
        <type>Date</type>
    </fields>
    <label>Product Performance</label>
    <nameField>
        <displayFormat>PP-{0000000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Performance</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ProdPerfMaintRefBatch.cls
global class ProdPerfMaintRefBatch implements Database.Batchable<sObject>, Database.Stateful {
    
    public CDRSettings__c settings = CDRSettings__c.getvalues('NGAM');
    String lastNDaysParm = settings.ProdPerfBatchLASTNDAYS__c;
    
    global Set<Id> prodIdSet = new Set<Id>();
    
    public String query = ' SELECT Id, AsOfDate__c, Product__c, PriorDate__c, PriorBusinessDate__c, MonthEndDate__c, PriorMonthEndDate__c, PriorMonthEndBusinessDate__c, IsAsOfDateBusinessDate__c, ' +
        ' QuarterEndDate__c, PriorQuarterEndDate__c, PriorQuarterEndBusinessDate__c, YearEndDate__c, PriorYearEndDate__c, PriorYearEndBusinessDate__c, IsYearEnd__c, IsMonthEnd__c, ' +
        ' IsQuarterEnd__c, PriorProductPerfExtId__c, PriorMonthEndProdPerfExtId__c, PriorQuarterEndProdPerfExtId__c, PriorYearEndProdPerfExtId__c, ' +
        ' PriorProductPerformance__c, PriorMonthEndProductPerformance__c, PriorQuarterEndProductPerformance__c, PriorYearEndProductPerformance__c, ExternalID__c ' +
        ' FROM ProductPerformance__c ' +
        ' WHERE AsOfDate__c = LAST_N_DAYS:' + lastNDaysParm + ' ';
    
    global ProdPerfMaintRefBatch() {
        
    }
    
    
    global Database.QueryLocator start(Database.BatchableContext BC) {      
        System.Debug('Query - ' + query);
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<ProductPerformance__c> scope) {
        
        List<ProductPerformance__c> ppToUpdate = new List<ProductPerformance__c>();
        
        Set<String> extIdSet = new Set<String>();
        Map<String,ProductPerformance__c> refMap = new Map<String,ProductPerformance__c>();
        
        for (ProductPerformance__c pp : scope) {
            extIdSet.add(pp.PriorProductPerfExtId__c);
            extIdSet.add(pp.PriorMonthEndProdPerfExtId__c);
            extIdSet.add(pp.PriorQuarterEndProdPerfExtId__c);
            extIdSet.add(pp.PriorYearEndProdPerfExtId__c);
            prodIdSet.add(pp.Product__c);
        }
        
        for (ProductPerformance__c pp : [SELECT Id, ExternalId__c, Product__c
                                         FROM ProductPerformance__c
                                         WHERE ExternalId__c in :extIdSet]) {
                                             refMap.put(pp.ExternalId__c,pp); 
                                         }
        
        for (ProductPerformance__c pp : scope) {
            if (refMap.containsKey(pp.PriorProductPerfExtId__c)) pp.PriorProductPerformance__c = refMap.get(pp.PriorProductPerfExtId__c).Id;
            if (refMap.containsKey(pp.PriorMonthEndProdPerfExtId__c)) pp.PriorMonthEndProductPerformance__c = refMap.get(pp.PriorMonthEndProdPerfExtId__c).Id;
            if (refMap.containsKey(pp.PriorQuarterEndProdPerfExtId__c)) pp.PriorQuarterEndProductPerformance__c = refMap.get(pp.PriorQuarterEndProdPerfExtId__c).Id;
            if (refMap.containsKey(pp.PriorYearEndProdPerfExtId__c)) pp.PriorYearEndProductPerformance__c = refMap.get(pp.PriorYearEndProdPerfExtId__c).Id;
            ppToUpdate.add(pp);
        }
        
        update ppToUpdate; 

    }
    
    global void finish(Database.BatchableContext BC) {
        
        Id batchJobId = Database.executeBatch(new ProdPerfMaintPublishBatch());
        
    }
    
}