objects/CDRSettings__c.object
<CustomObject>
    <fields>
        <fullName>BusinessHoursName__c</fullName>
        <description>Used in loading product performance data.  This should be a record that is 24-Hours, M-F, GMT.  The stock market holidays for each year must be associated with the Business Hours.</description>
        <inlineHelpText>Used in loading product performance data.  This should be a record that is 24-Hours, M-F, GMT.  The stock market holidays for each year must be associated with the Business Hours.</inlineHelpText>
        <label>Business Hours Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Settings that control CDR processes</description>
    <label>CDR Settings</label>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Top10HoldingsPublishingSchedule__c</fullName>
        <description>Used in Apex to set the Product Characteristic publishing schedule for Top 10 Holdings.</description>
        <label>Top 10 Holdings Publishing Schedule</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CDRPublishingSchedule</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProductCharacteristic__c.object
<CustomObject>
    <fields>
        <fullName>Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used in PB to initiate time-based workflow which sets Published__c to TRUE 0 Days after PublishDate__c</description>
        <label>Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AsOfDate__c</fullName>
        <description>The as of date of the Product Characteristic; set via integrations during creation</description>
        <label>As Of Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CharacteristicsDataType__c</fullName>
        <description>Loaded during integration; used in trigger to formulate Product Characteristics Output Text and Index Characteristics Output Text</description>
        <label>Characteristics Data Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Integer</fullName>
                </value>
                <value>
                    <fullName>Decimal</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Percent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IndexCharacteristicsDecimal__c</fullName>
        <description>Holds the decimal (percent, integer, decimal) for the index from the characteristics file if the related value if a number; otherwise this is null.  Loaded from integration.</description>
        <label>Index Characteristics Decimal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IndexCharacteristicsInteger__c</fullName>
        <label>Index Characteristics Integer</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IndexCharacteristicsOutputText__c</fullName>
        <description>Created by trigger on insert</description>
        <label>Index Characteristics Output Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IndexCharacteristicsText__c</fullName>
        <description>Holds the text from the index characteristics file if the related value if a text; otherwise this is null.  Loaded from integration.</description>
        <label>Index Characteristics Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductCharacteristicsDecimal__c</fullName>
        <description>Holds the decimal (percent, integer, decimal) for the product from the characteristics file if the related value if a number; otherwise this is null.  Loaded from integration.</description>
        <label>Product Characteristics Decimal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProductCharacteristicsInteger__c</fullName>
        <label>Product Characteristics Integer</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProductCharacteristicsOutputText__c</fullName>
        <description>Created by trigger on insert</description>
        <label>Product Characteristics Output Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductCharacteristicsText__c</fullName>
        <description>Holds the text from the product characteristics file if the related value if a text; otherwise this is null.  Loaded from integration.</description>
        <label>Product Characteristics Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Set via integrations during create.  Represents the Product to which this Product Characteristic belongs.</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Characteristics</relationshipLabel>
        <relationshipName>ProductCharacteristics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PublishDate__c</fullName>
        <description>Set by Apex, used in PB to set Published__c</description>
        <label>Publish Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Published__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Controls sharing for Product Characteristic records</description>
        <label>Published</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PublishingSchedule__c</fullName>
        <description>Used in Apex to set PublishDate__c</description>
        <label>Publishing Schedule</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CDRPublishingSchedule</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Set via integrations during create.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asset Allocation</fullName>
                </value>
                <value>
                    <fullName>Asset Classes and Segments</fullName>
                </value>
                <value>
                    <fullName>Characteristics</fullName>
                </value>
                <value>
                    <fullName>Country</fullName>
                </value>
                <value>
                    <fullName>Coupon</fullName>
                </value>
                <value>
                    <fullName>Coupon detail</fullName>
                </value>
                <value>
                    <fullName>Credit quality</fullName>
                </value>
                <value>
                    <fullName>Currency</fullName>
                </value>
                <value>
                    <fullName>Duration</fullName>
                </value>
                <value>
                    <fullName>Duration detail</fullName>
                </value>
                <value>
                    <fullName>Environmental projects breakdown</fullName>
                </value>
                <value>
                    <fullName>ESG Opinion</fullName>
                </value>
                <value>
                    <fullName>Expenses</fullName>
                </value>
                <value>
                    <fullName>Exposure summary</fullName>
                </value>
                <value>
                    <fullName>Global Sector</fullName>
                </value>
                <value>
                    <fullName>Holdings</fullName>
                </value>
                <value>
                    <fullName>Industry</fullName>
                </value>
                <value>
                    <fullName>Long Positions</fullName>
                </value>
                <value>
                    <fullName>Market capitalization</fullName>
                </value>
                <value>
                    <fullName>Maturity</fullName>
                </value>
                <value>
                    <fullName>Maturity detail</fullName>
                </value>
                <value>
                    <fullName>Number of holdings</fullName>
                </value>
                <value>
                    <fullName>Portfolio composition</fullName>
                </value>
                <value>
                    <fullName>Portfolio exposures</fullName>
                </value>
                <value>
                    <fullName>Portfolio Factor Exposures Summary</fullName>
                </value>
                <value>
                    <fullName>Property Type</fullName>
                </value>
                <value>
                    <fullName>Region</fullName>
                </value>
                <value>
                    <fullName>Sector</fullName>
                </value>
                <value>
                    <fullName>Sector-LS</fullName>
                </value>
                <value>
                    <fullName>Short Positions</fullName>
                </value>
                <value>
                    <fullName>Top ten holdings</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Holds characteristics about products for the CDR</description>
    <label>Product Characteristic</label>
    <nameField>
        <displayFormat>PC-{0000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Characteristics</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/CDRPublishingSchedule.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Never</fullName>
        <default>true</default>
        <label>Never</label>
    </customValue>
    <customValue>
        <fullName>Immediately</fullName>
    </customValue>
    <customValue>
        <fullName>7th Business Day</fullName>
    </customValue>
    <customValue>
        <fullName>8th Calendar Day</fullName>
    </customValue>
    <customValue>
        <fullName>1st Business Day After the Following Month-End</fullName>
    </customValue>
    <customValue>
        <fullName>10th Business Day After Quarter-End</fullName>
    </customValue>
    <description>Used in Apex to control publishing schedule of product characteristics</description>
    <masterLabel>CDR Publishing Schedule</masterLabel>
</GlobalValueSet>

classes/ProductCharacteristicTriggerHandler.cls
public class ProductCharacteristicTriggerHandler {
    
    public static List<ProductCharacteristic__c> SetPublishScheduleAndDate(List<ProductCharacteristic__c> myProdChar) {
        
        CDRSettings__c settings = CDRSettings__c.getvalues('NGAM');
        String BHName = settings.BusinessHoursName__c;
        businessHours bh = [SELECT Id, MondayEndTime, MondayStartTime, TuesdayEndTime, TuesdayStartTime, WednesdayEndTime, 
                            WednesdayStartTime, ThursdayEndTime, ThursdayStartTime, FridayEndTime, FridayStartTime, SaturdayEndTime, 
                            SaturdayStartTime, SundayEndTime, SundayStartTime 
                            FROM BusinessHours WHERE Name = :BHName LIMIT 1];
        
        List<Holiday> holidays = [SELECT Id, ActivityDate, RecurrenceType, RecurrenceDayOfMonth, RecurrenceMonthOfYear from Holiday];    
        
        Set<Id> productIdSet = new Set<Id>();
        for (ProductCharacteristic__c pc : myProdChar) {
            productIdSet.add(pc.Product__c);
        }
        
        Map<Id,Product2> prodMap = new Map<Id,Product2>([SELECT Id, Top10HoldingsPublishingSchedule__c
                                                         FROM Product2
                                                         WHERE Id in :productIdSet]);
        
        for (ProductCharacteristic__c pc : myProdChar) {
            
            switch on pc.Type__c {

                when 'Top ten holdings' {
                    pc.PublishingSchedule__c = prodMap.get(pc.Product__c).Top10HoldingsPublishingSchedule__c;
                }
                
                when else {
                    pc.PublishingSchedule__c = 'Immediately';
                } 
            }
         
            switch on pc.PublishingSchedule__c {                
                when 'Never' {
                    pc.PublishDate__c = null;  
                }
                when 'Immediately' {
                    pc.PublishDate__c = pc.AsOfDate__c;  
                }
                when '7th Business Day' {
                    Date startDate = pc.AsOfDate__c.addMonths(1).toStartOfMonth();
                    pc.PublishDate__c = getFutureBusinessDate(bh, holidays, startDate,7);    
                }
                when '8th Calendar Day' {
                    //setting to 7 because first day is the 1st day to which we are adding days               
                    pc.PublishDate__c = pc.AsOfDate__c.addMonths(1).toStartOfMonth().addDays(7);
                }
                when '1st Business Day After the Following Month-End' {
                    Date startDate = pc.AsOfDate__c.addMonths(2).toStartOfMonth();
                    pc.PublishDate__c = getFutureBusinessDate(bh, holidays, startDate,1);                
                }
                when '10th Business Day After Quarter-End' {
                    Date QEDate = getQuarterEndDate(pc.AsOfDate__c);
                    Date startDate = QEDate.addMonths(1).toStartOfMonth();
                    pc.PublishDate__c = getFutureBusinessDate(bh, holidays, startDate,10);
                }
            }
        }              
        return myProdChar;        
    }

    public static List<ProductCharacteristic__c> SetCharacteristicOutputText(List<ProductCharacteristic__c> myProdChar) {
                
        for (ProductCharacteristic__c pc : myProdChar) {
         
            switch on pc.CharacteristicsDataType__c {
                
                when 'Integer' {
                    if (pc.ProductCharacteristicsInteger__c != null) pc.ProductCharacteristicsOutputText__c = pc.ProductCharacteristicsInteger__c.format();
                    if (pc.IndexCharacteristicsInteger__c != null) pc.IndexCharacteristicsOutputText__c = pc.IndexCharacteristicsInteger__c.format();
                } 
                when 'Decimal' {
                    if (pc.ProductCharacteristicsDecimal__c != null) {
                        pc.ProductCharacteristicsOutputText__c = pc.ProductCharacteristicsDecimal__c.format();
                        pc.ProductCharacteristicsOutputText__c = pc.ProductCharacteristicsOutputText__c.substringBeforeLast('.') + '.' + pc.ProductCharacteristicsOutputText__c.substringAfterLast('.').rightpad(2,'0');
                    }
                    if (pc.IndexCharacteristicsDecimal__c != null) {
                        pc.IndexCharacteristicsOutputText__c = pc.IndexCharacteristicsDecimal__c.format();
                        pc.IndexCharacteristicsOutputText__c = pc.IndexCharacteristicsOutputText__c.substringBeforeLast('.') + '.' + pc.IndexCharacteristicsOutputText__c.substringAfterLast('.').rightpad(2,'0');
                    }
                }                                
                when 'Text' {
                    if (pc.ProductCharacteristicsText__c != null) pc.ProductCharacteristicsOutputText__c = pc.ProductCharacteristicsText__c;
                    if (pc.IndexCharacteristicsText__c != null) pc.IndexCharacteristicsOutputText__c = pc.IndexCharacteristicsText__c;
                }
            }            
        }       
        return myProdChar;
    }
    
    public static List<ProductCharacteristic__c> SetPublishedFlag(List<ProductCharacteristic__c> myProdChar) {
                
        for (ProductCharacteristic__c pc : myProdChar) {
            if (pc.PublishDate__c <= Date.today() && pc.Approved__c == TRUE) pc.Published__c = TRUE;
        }       
        return myProdChar;
    }    
    
    private static Date getQuarterEndDate(Date aod) {
        
        Date qed;
        
        switch on aod.month() {
            when 1,2,3 {
                qed = date.newInstance(aod.year(),3,31);  
            }
            when 4,5,6 {
                qed = date.newInstance(aod.year(),6,30);  
            }
            when 7,8,9 {
                qed = date.newInstance(aod.year(),9,30);  
            }
            when 10,11,12 {
                qed = date.newInstance(aod.year(),12,31);  
            }
        }
        return qed;
    }
    
    private static Date getFutureBusinessDate(BusinessHours bh, List<Holiday> h, Date myDate, Integer numberOfBusinessDays) {
        
        BusinessHoursMath businessHoursMath = new BusinessHoursMath();
        businessHoursMath.setBusinessHours(bh);
        businessHoursMath.setHolidays(h);
        Date returnDate;
          
        Integer BDCount = 0;
        Integer i = 0;
        while (BDCount < numberOfBusinessDays) {
            if (businessHoursMath.isBusinessDay(myDate.addDays(i))) {
                returnDate = myDate.addDays(i);
                BDCount++;
            }
            i++;
        }
        return returnDate;
    }            
}