objects/Channel__c.object
<CustomObject>
    <fields>
        <fullName>ChannelName__c</fullName>
        <externalId>true</externalId>
        <label>MARS Channel Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>ChannelName__c</fullName>
        <formula>Channel__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Channel Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Channel</label>
        <referenceTo>Channel__c</referenceTo>
        <relationshipLabel>Territories</relationshipLabel>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ParentTerritoryMARSName__c</fullName>
        <formula>ParentTerritory__r.TerritoryName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Territory MARS Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentTerritoryName__c</fullName>
        <description>Name of the Parent Territory</description>
        <formula>ParentTerritory__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Territory Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentTerritoryType__c</fullName>
        <formula>TEXT( ParentTerritory__r.TerritoryType__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Territory Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentTerritory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Territories</relationshipLabel>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RoleGroupId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Role Group Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Touch__c</fullName>
        <label>Touch</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ActivityChannelId__c</fullName>
        <description>Used To Tag the Activities and Opportunities created by the user.</description>
        <externalId>true</externalId>
        <inlineHelpText>READ ONLY FIELD : This Will be populated by the UserTerritory__c assignment when the Territory Assignment is tagged as an Activity Territory. Please never update this field directly. Instead Delete/Insert the relevant UserTerritory__c record.</inlineHelpText>
        <label>Activity Channel Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityChannelName__c</fullName>
        <description>Used To Tag the Activities and Opportunities created by the user.</description>
        <inlineHelpText>READ ONLY FIELD : This Will be populated by the UserTerritory__c assignment when the Territory Assignment is tagged as an Activity Territory. Please never update this field directly. Instead Delete/Insert the relevant UserTerritory__c record.</inlineHelpText>
        <label>Activity Channel Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryId__c</fullName>
        <description>Used To Tag the Activities and Opportunities created by the user.</description>
        <externalId>true</externalId>
        <inlineHelpText>READ ONLY FIELD : This Will be populated by the UserTerritory__c assignment when the Territory Assignment is tagged as an Activity Territory. Please never update this field directly. Instead Delete/Insert the relevant UserTerritory__c record.</inlineHelpText>
        <label>Activity Territory Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryName__c</fullName>
        <description>Used To Tag the Activities and Opportunities created by the user.</description>
        <inlineHelpText>READ ONLY FIELD : This Will be populated by the UserTerritory__c assignment when the Territory Assignment is tagged as an Activity Territory. Please never update this field directly. Instead Delete/Insert the relevant UserTerritory__c record.</inlineHelpText>
        <label>Activity Territory Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryParentId__c</fullName>
        <description>The Activity Territory's parent Id</description>
        <label>Activity Territory Parent Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryParentMARSName__c</fullName>
        <description>The activity territory's parent's MARS Name</description>
        <label>Activity Territory Parent MARS Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryParentName__c</fullName>
        <description>The Activity Territory's parent's Name</description>
        <label>Activity Territory Parent Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryParentType__c</fullName>
        <description>Activity Territory's Parent Type</description>
        <label>Activity Territory Parent Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DefaultTerritory__c</fullName>
        <description>Used by Literature fulfillment application.</description>
        <inlineHelpText>Used by Literature fulfillment application.</inlineHelpText>
        <label>Default Territory</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Touch__c</fullName>
        <description>This field does not carry any real data.  It is used so that it will kick off workflow, process builder, triggers, etc. when changed.</description>
        <inlineHelpText>This field does not carry any real data.  It is used so that it will kick off workflow, process builder, triggers, etc. when changed.</inlineHelpText>
        <label>Touch</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TerritoryTriggerHandler.cls
public with sharing class TerritoryTriggerHandler{
    
    public static void UpdateTerritorySharing(List<Territory__c> NewTerrs, Map<Id,Territory__c> MyoldTerrMap){
        
        List<Territory__Share> TerrShareToCreate = new List<Territory__Share>();
        List<Territory__Share> TerrShareToDelete = new List<Territory__Share>();
        
        Set<id> TerrWithChanges= new set<id>();
        
        for (Territory__c cTerr: NewTerrs) {
            if (cTerr.RoleGroupId__c != null &&
                (cTerr.RoleGroupId__c != MyoldTerrMap.get(cTerr.id).RoleGroupId__c || cTerr.Touch__c != MyoldTerrMap.get(cTerr.id).Touch__c) ) {
                TerrWithChanges.add(cTerr.id);  
                Territory__Share TsR = new  Territory__Share(AccessLevel='Read',UserOrGroupId=cTerr.RoleGroupId__c,ParentId=cTerr.id );    
                TerrShareToCreate.add(TsR);
            }
        }
        
        TerrShareToDelete = [select id from Territory__Share where RowCause = 'Manual' and parentid in: TerrWithChanges];
        
        if (!TerrShareToDelete.isEmpty()) {
            delete TerrShareToDelete;
        } 
        if (!TerrShareToCreate.isEmpty()) {
            insert TerrShareToCreate;
        } 
        
    }
    
    
    public static void UpdateUserTerritoryName(List<Territory__c> NewTerritories, Map<Id,Territory__c> OldTerritories){
        
        List<User> usersToUpdate = New List<User>(); 
        Set<Id> ActivityTerritoryIds = New Set<Id>();
        
        for (Territory__c sti : NewTerritories) {
            ActivityTerritoryIds.add(sti.Id);
        }
        
        List<User> userList = New List<User>([SELECT Id, ActivityChannelName__c, ActivityChannelId__c, ActivityTerritoryParentMARSName__c, ActivityTerritoryParentId__c, ActivityTerritoryParentType__c, ActivityTerritoryName__c, DefaultTerritory__c FROM User WHERE IsActive = TRUE AND ActivityTerritoryId__c IN : ActivityTerritoryIds]);
        
        for (Territory__c nt : NewTerritories){
            Territory__c ot = OldTerritories.get(nt.Id);
            if (nt.Name != ot.Name || ot.ParentTerritory__c == null || nt.ParentTerritory__c != ot.ParentTerritory__c || nt.Channel__c != ot.Channel__c || nt.Touch__c != ot.Touch__c) {
                for (User utu : userList) {
                    utu.ActivityTerritoryName__c = nt.Name;
                    utu.DefaultTerritory__c = nt.Name;
                    utu.ActivityChannelId__c = nt.Channel__c;
                    utu.ActivityChannelName__c = nt.ChannelName__c;
                    utu.ActivityTerritoryParentMARSName__c = nt.ParentTerritoryMARSName__c;
                    utu.ActivityTerritoryParentId__c = nt.ParentTerritory__c;
                    utu.ActivityTerritoryParentType__c = nt.ParentTerritoryType__c;
                    utu.ActivityTerritoryParentName__c = nt.ParentTerritoryName__c;
                    usersToUpdate.add(utu);                    
                }
            }
        }
        
        Update usersToUpdate;
    }
}