objects/Channel__c.object
<CustomObject>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Channel</label>
        <referenceTo>Channel__c</referenceTo>
        <relationshipLabel>Territories</relationshipLabel>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TerritoryName__c</fullName>
        <defaultValue>"Update Me"</defaultValue>
        <externalId>true</externalId>
        <label>MARS Territory Name</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ZipCode__c.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <formula>Territory__r.Channel__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Channel</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Zip Codes</relationshipLabel>
        <relationshipName>ZipCodes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Zone</label>
        <referenceTo>Community</referenceTo>
        <relationshipName>ZipCodes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Zip Code</label>
    <nameField>
        <displayFormat>ZC-{0000000000}</displayFormat>
        <label>Zip Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Zip Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Zone__c.object
<CustomObject>
    <fields>
        <fullName>Zone__c</fullName>
        <externalId>true</externalId>
        <label>Zone</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ZipcodeController.cls
public class ZipcodeController {
    
    @RemoteAction
    public static List<Zipcode__c> GetAllZipcodes(String city)
    {        
        List<Zipcode__c> zipCodeList = [SELECT Channel__c, Territory__r.TerritoryName__c, state__c, city__c, zip__c, county__c, Zone__c FROM Zipcode__c where city__c = :city];
        system.debug('size:'+zipCodeList.size());
        return zipCodeList;
    }
    
    @RemoteAction
    public static Set<String> GetAllCities()
    {      
        Set<String> distinctCities = new Set<String>();  
        //List<Zipcode__c> cityList = [SELECT city__c FROM Zipcode__c];
        
        for(Zipcode__c z : [SELECT city__c FROM Zipcode__c limit 40000]) {
            if (!distinctCities.Contains(z.city__c)) {
                distinctCities.add(z.city__c);
            }
        }
        system.debug('size:'+distinctCities.size());
        return distinctCities;
    }
}