objects/Channel__c.object
<CustomObject>
    <fields>
        <fullName>ChannelName__c</fullName>
        <externalId>true</externalId>
        <label>MARS Channel Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/NGAMSettings__c.object
<CustomObject>
    <fields>
        <fullName>ProfileSales__c</fullName>
        <description>Indicates the profile that should be used for Sales User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</description>
        <inlineHelpText>Indicates the profile that should be used for Sales User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</inlineHelpText>
        <label>Profile: Sales</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProfileSystemAdministrator__c</fullName>
        <description>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</description>
        <inlineHelpText>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</inlineHelpText>
        <label>Profile: System Administrator</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Holds the NGAM settings</description>
    <label>NGAM Settings</label>
</CustomObject>

objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>ChannelName__c</fullName>
        <formula>Channel__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Channel Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Channel</label>
        <referenceTo>Channel__c</referenceTo>
        <relationshipLabel>Territories</relationshipLabel>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ChildrenCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Children Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GroupId__c</fullName>
        <externalId>true</externalId>
        <label>Group Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RoleGroupId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Role Group Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RoleId__c</fullName>
        <externalId>true</externalId>
        <label>Role Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TerritoryName__c</fullName>
        <defaultValue>"Update Me"</defaultValue>
        <externalId>true</externalId>
        <label>MARS Territory Name</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TerritoryType__c</fullName>
        <label>Territory Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Territory</fullName>
                </value>
                <value>
                    <fullName>Region</fullName>
                </value>
                <value>
                    <fullName>Department</fullName>
                </value>
                <value>
                    <fullName>Division</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>PrimaryTerritory__c</fullName>
        <label>Primary Territory</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RoleProxy__c</fullName>
        <label>RoleProxy</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserID__c</fullName>
        <defaultValue>"Populate This Field"</defaultValue>
        <externalId>true</externalId>
        <label>UserID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/UserTerritory__c.object
<CustomObject>
    <fields>
        <fullName>ActivityTerritory__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activity Territory</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PrimaryTerritory__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Territory</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RoleId__c</fullName>
        <formula>Territory__r.RoleId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Role Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TerritoryName__c</fullName>
        <formula>Territory__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Territory Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TerritoryType__c</fullName>
        <formula>TEXT(Territory__r.TerritoryType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Territory Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>User Territories</relationshipLabel>
        <relationshipName>User_Territories1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Territories1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zoning__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Zone</label>
        <referenceTo>Zone__c</referenceTo>
        <relationshipLabel>User Territories</relationshipLabel>
        <relationshipName>User_Territories</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>User Territory</label>
    <nameField>
        <displayFormat>UT-{00000000}</displayFormat>
        <label>User Territory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Zone__c.object
<CustomObject>
    <fields>
        <fullName>Zone__c</fullName>
        <externalId>true</externalId>
        <label>Zone</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SL_TerritoryToggleButton_Test.cls
@isTest
private class SL_TerritoryToggleButton_Test {
    static testMethod void ValidateAll() {
        
        //Profile p = [select id from profile where name='System Administrator']; 
        //Profile pSales = [select id from profile where name='NGAM Sales Wirehouse'];
       DataFactory.CreateNGAMCustomSettings(); 
       NGAMSettings__c ngamSettings = [select id,ProfileSystemAdministrator__c,ProfileSales__c from NGAMSettings__c limit 1]; 
       string p = Util.getCustomSettingProfileId(ngamSettings.ProfileSystemAdministrator__c);
       string pSales = Util.getCustomSettingProfileId(ngamSettings.ProfileSales__c);
 
        User u = new User(alias = 'standt', email='SFDCadmin@ngam.natixis.com', 
                          emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
                          localesidkey='en_US', profileid = p, 
                          timezonesidkey='America/Los_Angeles', username='SFDCadmin@ngam.natixis.com',UserID__c='SFDCadmin');
        //insert u;
        System.runAs(u) 
        {   
            //Test.startTest();   
            //List<Zone__c> myZones = DataFactory.createAllZones();
            
            User u0 = new User(alias = 's0', email='Sales0@ngam.natixis.com', 
                               emailencodingkey='UTF-8', lastname='Testing0', languagelocalekey='en_US', 
                               localesidkey='en_US', profileid = pSales, 
                               timezonesidkey='America/Los_Angeles', username='Sales0@ngam.natixis.com',UserID__c='Sales0', RoleProxy__c=null,UserRoleid=null);    
            User u1 = new User(alias = 's1', email='Sales1@ngam.natixis.com', 
                               emailencodingkey='UTF-8', lastname='Testing1', languagelocalekey='en_US', 
                               localesidkey='en_US', profileid = pSales, 
                               timezonesidkey='America/Los_Angeles', username='Sales1@ngam.natixis.com',UserID__c='Sales1'); 
            User u2 = new User(alias = 's2', email='Sales2@ngam.natixis.com', 
                               emailencodingkey='UTF-8', lastname='Testing2', languagelocalekey='en_US', 
                               localesidkey='en_US', profileid = pSales, 
                               timezonesidkey='America/Los_Angeles', username='Sales2@ngam.natixis.com',UserID__c='Sales2'); 
            User u3 = new User(alias = 's3', email='Sales3@ngam.natixis.com', 
                               emailencodingkey='UTF-8', lastname='Testing3', languagelocalekey='en_US', 
                               localesidkey='en_US', profileid = pSales, 
                               timezonesidkey='America/Los_Angeles', username='Sales3@ngam.natixis.com',UserID__c='Sales3');  
            User u5 = new User(alias = 's5', email='Sales5@ngam.natixis.com', 
                               emailencodingkey='UTF-8', lastname='Testing5', languagelocalekey='en_US', 
                               localesidkey='en_US', profileid = pSales, 
                               timezonesidkey='America/Los_Angeles', username='Sales5@ngam.natixis.com',UserID__c='Sales5');  
            insert u0;
            insert u1;
            insert u2;
            insert u3;
            //insert u5;
            //Territory__c myTerr = [Select Id, Name, RoleId__c, Code__c FROM Territory__c where ChildrenCount__c=0 LIMIT 1];

            //Creating the Territory
            Channel__c channel = new Channel__c(Name='TestChannel',ChannelName__c='TestChannel');
            insert channel;
            
            Territory__c Terr = new Territory__c(Name='Test',TerritoryName__c='Test',RoleID__c = '',GroupID__c = '',TerritoryType__c = 'Territory',Channel__c=Channel.Id); 
            insert Terr; 
            
            //Creating the Territory
            Territory__c Terr2 = new Territory__c(Name='Test2',TerritoryName__c='Test2',RoleID__c = '',GroupID__c = '',TerritoryType__c = 'Territory',Channel__c=Channel.Id); 
            insert Terr2; 
            
            // Creating the Corresponding Role
            UserRole Ur = new UserRole();
            Ur.Name = Terr.Name;
            Ur.DeveloperName = Terr.Id;
            Ur.CaseAccessForAccountOwner = 'Read';
            Ur.OpportunityAccessForAccountOwner = 'Read';
            Ur.ContactAccessForAccountOwner = 'Read';
            insert Ur;   
            
            Group urGroup=[select id from group where RelatedId =:ur.id][0];
            
            // Creating the Corresponding Group
            //Group Gr = new Group();
            //Gr.name = Terr.Name;
            //Gr.DeveloperName = Terr.Id;
            //Gr.Type = 'Regular';
            //insert Gr;     
            
            Territory__Share TsR = new  Territory__Share(AccessLevel='Read',UserOrGroupId=urGroup.id,ParentId=terr.id );    
            insert TsR;      
            
            //Territory__c uTerr = new Territory__c(id=Terr.id,RoleID__c = ur.id,GroupID__c = gr.id ); 
            Terr.RoleID__c = ur.id;
            Terr.RoleGroupId__c = urGroup.id;
            //Terr.GroupID__c = gr.id;    
            update Terr;
            
            List<zone__c> AllZones = DataFactory.createAllZones();
            
            
            //system.debug('0 position allzone :' + AllZones.get(0).id);
            Test.startTest();       
            List<UserTerritory__c> newUserTerr = new List<UserTerritory__c>();    
            //test.startTest();
            UserTerritory__c ut0 = new  UserTerritory__c(user__c=u0.id, territory__c=Terr.Id, PrimaryTerritory__c=true, ActivityTerritory__c=true, Zoning__c=AllZones.get(0).id);  
            newUserTerr.add(ut0);  
            //insert ut0;
            //test.stopTest();
            
            //system.debug (ur.id + '   '+  u0.id+ '   '+  u0.userrole.name);
            
            //UserTerritoryTriggerHandler.run = true;    
            UserTerritory__c ut1 = new  UserTerritory__c(user__c=u0.id, territory__c=Terr.Id, PrimaryTerritory__c=false, ActivityTerritory__c=false, Zoning__c=AllZones.get(1).id);  
            newUserTerr.add(ut1); 
            //insert ut1; 
            
            //UserTerritoryTriggerHandler.run = true;
            UserTerritory__c ut2 = new  UserTerritory__c(user__c=u2.id, territory__c=Terr.Id, PrimaryTerritory__c=true, ActivityTerritory__c=true, Zoning__c=AllZones.get(2).id);  
            newUserTerr.add(ut2);  
            //insert ut2;
            
            //UserTerritoryTriggerHandler.run = true;    
            UserTerritory__c ut3 = new  UserTerritory__c(user__c=u3.id, territory__c=Terr.Id, PrimaryTerritory__c=true, ActivityTerritory__c=true, Zoning__c=AllZones.get(3).id);  
            newUserTerr.add(ut3);  
            //insert ut3;
            
            
            //UserTerritoryTriggerHandler.run = true;  
            //UserTerritory__c ut5 = new  UserTerritory__c(user__c=u5.id, territory__c=Terr.Id, PrimaryTerritory__c=true, ActivityTerritory__c=true, Zoning__c=AllZones.get(4).id);     
            //newUserTerr.add(ut5);   
            //insert ut5;
            
            insert newUserTerr;
            //Test.stopTest();    

            system.debug('u1' + u1.UserRoleId);
            system.debug('u2' + u2.UserRoleId);
            system.debug('u3' + u3.UserRoleId);
            system.debug('u5' + u5.UserRoleId);
            
            // Testing SL_TerritoryToggleButton Controller
            
            SL_TerritoryToggleButton controller = new SL_TerritoryToggleButton();
            SL_TerritoryToggleButton.getUserTerritory();
            SL_TerritoryToggleButton.getUserPrimTerritory();
            SL_TerritoryToggleButton.getIsShowMe();
            SL_TerritoryToggleButton.btnApply(ut0.id);

        }
    }
}