objects/Channel__c.object
<CustomObject>
    <fields>
        <fullName>ZoneField__c</fullName>
        <label>Zone Field</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <description>Wells FA data in Salesforce requested by Joseph Labresh. This field labels each FA by what channel they work in: “PCG”, “WBS”, and “Finet”.</description>
        <inlineHelpText>This field is about Wells FA data, it labels each FA by what channel they work in: “PCG”, “WBS”, and “Finet”.</inlineHelpText>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PCG</fullName>
                </value>
                <value>
                    <fullName>WBS</fullName>
                </value>
                <value>
                    <fullName>FiNet</fullName>
                </value>
                <value>
                    <fullName>RIA Hybrid</fullName>
                </value>
                <value>
                    <fullName>Independent</fullName>
                </value>
                <value>
                    <fullName>Bank</fullName>
                </value>
                <value>
                    <fullName>RIA IFA Advisor</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Licensed Branch Employee</fullName>
                </value>
                <value>
                    <fullName>Insurance Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PROTierFS__c</fullName>
        <description>N/A No longer used.</description>
        <inlineHelpText>1=Top Producer, 8 activities per year 
2=Elevate, 6 activities per year 
3=Potential to elevate based on capacity, 2+ activities per year 
DNC=Do Not Call 
P=Prospect 
T=Team, Tier 1,2,3 but not the person you talk to</inlineHelpText>
        <label>Tier FS</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>DNC</fullName>
                </value>
                <value>
                    <fullName>P</fullName>
                </value>
                <value>
                    <fullName>T</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PROTierIAG__c</fullName>
        <description>N/A No longer used.</description>
        <inlineHelpText>1=Top Producer, 8 activities per year 
2=Elevate, 6 activities per year
3=Potential to elevate based on capacity, 2+ activities per year
DNC=Do Not Call
P=Prospect
T=Team, Tier 1,2,3 but not the person you talk to</inlineHelpText>
        <label>Tier IAG</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>DNC</fullName>
                </value>
                <value>
                    <fullName>P</fullName>
                </value>
                <value>
                    <fullName>T</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PROTierWHSE__c</fullName>
        <description>N/A No longer used.</description>
        <inlineHelpText>1=Top Producer, 8 activities per year 
2=Elevate, 6 activities per year
3=Potential to elevate based on capacity, 2+ activities per year
DNC=Do Not Call
P=Prospect
T=Team, Tier 1,2,3 but not the person you talk to</inlineHelpText>
        <label>Tier Wirehouse</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>DNC</fullName>
                </value>
                <value>
                    <fullName>P</fullName>
                </value>
                <value>
                    <fullName>T</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PROZoneFS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>N/A No longer used. Previously used to carve out bigger territories.</description>
        <label>Zone FS</label>
        <referenceTo>Zone__c</referenceTo>
        <relationshipLabel>Contacts (Zone FS)</relationshipLabel>
        <relationshipName>Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PROZoneGR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used in logic to personalize emails in Pardot.</description>
        <label>Zone GR</label>
        <referenceTo>Zone__c</referenceTo>
        <relationshipLabel>Contacts (Zone GR)</relationshipLabel>
        <relationshipName>Contacts4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PROZoneIAG__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>N/A No longer used. Previously used to carve out bigger territories.</description>
        <label>Zone IAG</label>
        <referenceTo>Zone__c</referenceTo>
        <relationshipLabel>Contacts (Zone IAG)</relationshipLabel>
        <relationshipName>Contacts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PROZoneWHSE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>N/A No longer used. Previously used to carve out bigger territories.</description>
        <label>Zone Wirehouse</label>
        <referenceTo>Zone__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <description>Custom field no longer used</description>
        <label>ZZZTerritory</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BD FIDUCIARY NORTH CENTRAL</fullName>
                </value>
                <value>
                    <fullName>BD FIDUCIARY NORTHEAST</fullName>
                </value>
                <value>
                    <fullName>BD FIDUCIARY SOUTHEAST</fullName>
                </value>
                <value>
                    <fullName>BD FIDUCIARY TEAM</fullName>
                </value>
                <value>
                    <fullName>BD FIDUCIARY WEST</fullName>
                </value>
                <value>
                    <fullName>BT NORTH CENTRAL</fullName>
                </value>
                <value>
                    <fullName>BT NORTHEAST</fullName>
                </value>
                <value>
                    <fullName>BT SOUTHEAST</fullName>
                </value>
                <value>
                    <fullName>BT TEAM</fullName>
                </value>
                <value>
                    <fullName>BT WEST</fullName>
                </value>
                <value>
                    <fullName>BT WHSE TEAM</fullName>
                </value>
                <value>
                    <fullName>DC CENTRAL</fullName>
                </value>
                <value>
                    <fullName>DC EAST</fullName>
                </value>
                <value>
                    <fullName>DCIO</fullName>
                </value>
                <value>
                    <fullName>DCIO SUB ADV DC</fullName>
                </value>
                <value>
                    <fullName>DC WEST</fullName>
                </value>
                <value>
                    <fullName>FID FOCUS GREAT LAKES</fullName>
                </value>
                <value>
                    <fullName>FID FOCUS HEARTLAND</fullName>
                </value>
                <value>
                    <fullName>FID FOCUS MID AMERICA EAST</fullName>
                </value>
                <value>
                    <fullName>FID FOCUS NORTHWEST</fullName>
                </value>
                <value>
                    <fullName>FID FOCUS OTHER</fullName>
                </value>
                <value>
                    <fullName>FID FOCUS TEXAS</fullName>
                </value>
                <value>
                    <fullName>GLOBAL RELATIONSHIPS</fullName>
                </value>
                <value>
                    <fullName>IND ADV GRP BAY STATE</fullName>
                </value>
                <value>
                    <fullName>IND ADV GRP DELAWARE VALLEY</fullName>
                </value>
                <value>
                    <fullName>IND ADV GRP EAST CENTRAL</fullName>
                </value>
                <value>
                    <fullName>IND ADV GRP GREAT LAKES</fullName>
                </value>
                <value>
                    <fullName>IND ADV GRP GULF COAST</fullName>
                </value>
                <value>
                    <fullName>IND ADV GRP HEARTLAND</fullName>
                </value>
                <value>
                    <fullName>IND ADV GRP MID AMERICA EAST</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TierADU_IDU__c</fullName>
        <description>Used to Tier Advisor &amp; Institutional Distribution Unit data.</description>
        <inlineHelpText>Used to Tier Advisor &amp; Institutional Distribution Unit data. Tier is typically a quality designation and can correlate to how often an office should be contacted.</inlineHelpText>
        <label>Tier</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ZoneADU_IDU__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Zone field for the Advisor &amp; Institutional Distribution Unit</description>
        <inlineHelpText>Updating the Office level Zone will automatically update all related Contact/Reps records with the same Zone.</inlineHelpText>
        <label>Zone</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Zone__c.Zone__c</field>
                <operation>greaterOrEqual</operation>
                <value>7</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Zone__c</referenceTo>
        <relationshipLabel>Contacts (Zone ADU_IDU)</relationshipLabel>
        <relationshipName>ContactZoneADU_IDU</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Channel</label>
        <referenceTo>Channel__c</referenceTo>
        <relationshipLabel>Territories</relationshipLabel>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RoleGroupId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Role Group Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/TransactionTerr__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Transcations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ScrubDate__c</fullName>
        <label>Scrub Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Big Tickets</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TransactionType__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Purchases</fullName>
                </value>
                <value>
                    <fullName>Redemptions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>One day worth of data - Scrub Date of Last business day which includes manually scrubbed and auto resolved. Updated daily. Has data at the Territory level.</description>
    <label>Big Ticket</label>
    <nameField>
        <displayFormat>TR-{0000000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Big Tickets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TransactionTerrBatchWS.cls
@RestResource(urlMapping='/TransactionTerr/*')
global with sharing class TransactionTerrBatchWS {

    @HttpPost
    global static List<id> TransactionTerrBatchIds(DateTime LastTime) {
        List<id> TransactionTerrJobList = new List<id>();
        
		//DateTime SplitDate = system.now().addDays(-16);
        //String formatedDt = LastModidified.format('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'');
        
		//system.debug('------------------- Mid Date ' + formatedDt);
        
		TransactionTerrBatch ttj1 = new TransactionTerrBatch();
		//ttj1.query = 'select id, contact__r.PROTierWHSE__c,contact__r.PROTierFS__c,contact__r.PROTierIAG__c,contact__r.PROTierRS__c, contact__r.PROZoneWHSE__c, contact__r.PROZoneFS__c, contact__r.PROZoneIAG__c, contact__r.PROZoneRS__c, territory__r.Channel__c, territory__r.RoleGroupId__c from TransactionTerr__c where territory__r.Channel__r.ZoneField__c!=\'\' and TransactionType__c=\'Purchases\'';
        //ttj1.query = ttj1.query + ' and ScrubDate__c >='+ SplitDate.format('yyyy-MM-dd')+'T'+ SplitDate.format('HH:mm')+':00.000Z';
        /*ttj1.query = 'select id, contact__r.PROZoneGR__c,contact__r.PROTierWHSE__c,contact__r.PROTierFS__c,contact__r.PROTierIAG__c,contact__r.PROTierRS__c, contact__r.TierADU_IDU__c,contact__r.PROZoneWHSE__c, contact__r.PROZoneFS__c, contact__r.PROZoneIAG__c, contact__r.PROZoneRS__c, Contact__r.ZoneADU_IDU__c, territory__r.Channel__c, territory__r.RoleGroupId__c from TransactionTerr__c where TransactionType__c=\'Purchases\'';
        ttj1.query = ttj1.query + ' and LastModifiedDate >='+ LastTime.format('yyyy-MM-dd')+'T'+ LastTime.format('HH:mm')+':00.000Z';*/
        
        ttj1.query = ContactChannelHelper.ContactChannelFieldQuery();
        ttj1.query += ' territory__r.Channel__c, territory__r.RoleGroupId__c from TransactionTerr__c where TransactionType__c=\'Purchases\'';
        ttj1.query += ' and LastModifiedDate >='+ LastTime.format('yyyy-MM-dd')+'T'+ LastTime.format('HH:mm')+':00.000Z';
        system.debug(ttj1.query);
        ID ttjid1 = database.executeBatch(ttj1,2000); 
        TransactionTerrJobList.add(ttjid1);
 
        TransactionTerrBatch ttj2 = new TransactionTerrBatch();
        /*ttj2.query = 'select id, contact__r.PROZoneGR__c, contact__r.PROTierWHSE__c,contact__r.PROTierFS__c,contact__r.PROTierIAG__c,contact__r.PROTierRS__c, contact__r.TierADU_IDU__c,contact__r.PROZoneWHSE__c, contact__r.PROZoneFS__c, contact__r.PROZoneIAG__c, contact__r.PROZoneRS__c, Contact__r.ZoneADU_IDU__c, territory__r.Channel__c, territory__r.RoleGroupId__c from TransactionTerr__c where TransactionType__c=\'Redemptions\'';
        //ttj2.query = ttj2.query + ' and ScrubDate__c >='+ SplitDate.format('yyyy-MM-dd')+'T'+ SplitDate.format('HH:mm')+':00.000Z';
        ttj2.query = ttj2.query + ' and LastModifiedDate >='+ LastTime.format('yyyy-MM-dd')+'T'+ LastTime.format('HH:mm')+':00.000Z';*/
        ttj2.query = ContactChannelHelper.ContactChannelFieldQuery();
        ttj2.query += ' territory__r.Channel__c, territory__r.RoleGroupId__c from TransactionTerr__c where TransactionType__c=\'Redemptions\'';
        ttj2.query += ' and LastModifiedDate >='+ LastTime.format('yyyy-MM-dd')+'T'+ LastTime.format('HH:mm')+':00.000Z';
        system.debug(ttj2.query);
        ID ttjid2 = database.executeBatch(ttj2,2000); 
        TransactionTerrJobList.add(ttjid2);
        
        /*
        TransactionTerrBatch ttj3 = new TransactionTerrBatch();
        ttj3.query = 'select id, contact__r.PROTierWHSE__c,contact__r.PROTierFS__c,contact__r.PROTierIAG__c,contact__r.PROTierRS__c, contact__r.PROZoneWHSE__c, contact__r.PROZoneFS__c, contact__r.PROZoneIAG__c, contact__r.PROZoneRS__c, territory__r.Channel__c, territory__r.RoleGroupId__c from TransactionTerr__c where territory__r.Channel__r.ZoneField__c!=\'\' and TransactionType__c=\'Purchases\'';
        ttj3.query = ttj3.query + ' and ScrubDate__c <'+ SplitDate.format('yyyy-MM-dd')+'T'+ SplitDate.format('HH:mm')+':00.000Z';
        system.debug(ttj3.query);
        ID ttjid3 = database.executeBatch(ttj3,2000); 
        TransactionTerrJobList.add(ttjid3);
        
        TransactionTerrBatch ttj4 = new TransactionTerrBatch();
        ttj4.query = 'select id, contact__r.PROTierWHSE__c,contact__r.PROTierFS__c,contact__r.PROTierIAG__c,contact__r.PROTierRS__c, contact__r.PROZoneWHSE__c, contact__r.PROZoneFS__c, contact__r.PROZoneIAG__c, contact__r.PROZoneRS__c, territory__r.Channel__c, territory__r.RoleGroupId__c from TransactionTerr__c where territory__r.Channel__r.ZoneField__c!=\'\' and TransactionType__c=\'Redemptions\'';
        ttj4.query = ttj4.query + ' and ScrubDate__c <'+ SplitDate.format('yyyy-MM-dd')+'T'+ SplitDate.format('HH:mm')+':00.000Z';
        system.debug(ttj4.query);
        ID ttjid4 = database.executeBatch(ttj4,2000); 
        TransactionTerrJobList.add(ttjid4);*/

        
        return TransactionTerrJobList ;
    }
    
}