objects/Channel__c.object
<CustomObject>
    <fields>
        <fullName>FocusFirmField__c</fullName>
        <label>Focus Firm Field</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TierField__c</fullName>
        <label>Tier Field</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZoneField__c</fullName>
        <label>Zone Field</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <description>Wells FA data in Salesforce requested by Joseph Labresh. This field labels each FA by what channel they work in: “PCG”, “WBS”, and “Finet”.</description>
        <inlineHelpText>This field is about Wells FA data, it labels each FA by what channel they work in: “PCG”, “WBS”, and “Finet”.</inlineHelpText>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PCG</fullName>
                </value>
                <value>
                    <fullName>WBS</fullName>
                </value>
                <value>
                    <fullName>FiNet</fullName>
                </value>
                <value>
                    <fullName>RIA Hybrid</fullName>
                </value>
                <value>
                    <fullName>Independent</fullName>
                </value>
                <value>
                    <fullName>Bank</fullName>
                </value>
                <value>
                    <fullName>RIA IFA Advisor</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Licensed Branch Employee</fullName>
                </value>
                <value>
                    <fullName>Insurance Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PROTierFS__c</fullName>
        <description>N/A No longer used.</description>
        <inlineHelpText>1=Top Producer, 8 activities per year 
2=Elevate, 6 activities per year 
3=Potential to elevate based on capacity, 2+ activities per year 
DNC=Do Not Call 
P=Prospect 
T=Team, Tier 1,2,3 but not the person you talk to</inlineHelpText>
        <label>Tier FS</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>DNC</fullName>
                </value>
                <value>
                    <fullName>P</fullName>
                </value>
                <value>
                    <fullName>T</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PROTierIAG__c</fullName>
        <description>N/A No longer used.</description>
        <inlineHelpText>1=Top Producer, 8 activities per year 
2=Elevate, 6 activities per year
3=Potential to elevate based on capacity, 2+ activities per year
DNC=Do Not Call
P=Prospect
T=Team, Tier 1,2,3 but not the person you talk to</inlineHelpText>
        <label>Tier IAG</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>DNC</fullName>
                </value>
                <value>
                    <fullName>P</fullName>
                </value>
                <value>
                    <fullName>T</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PROTierWHSE__c</fullName>
        <description>N/A No longer used.</description>
        <inlineHelpText>1=Top Producer, 8 activities per year 
2=Elevate, 6 activities per year
3=Potential to elevate based on capacity, 2+ activities per year
DNC=Do Not Call
P=Prospect
T=Team, Tier 1,2,3 but not the person you talk to</inlineHelpText>
        <label>Tier Wirehouse</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>DNC</fullName>
                </value>
                <value>
                    <fullName>P</fullName>
                </value>
                <value>
                    <fullName>T</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PROZoneFS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>N/A No longer used. Previously used to carve out bigger territories.</description>
        <label>Zone FS</label>
        <referenceTo>Zone__c</referenceTo>
        <relationshipLabel>Contacts (Zone FS)</relationshipLabel>
        <relationshipName>Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PROZoneIAG__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>N/A No longer used. Previously used to carve out bigger territories.</description>
        <label>Zone IAG</label>
        <referenceTo>Zone__c</referenceTo>
        <relationshipLabel>Contacts (Zone IAG)</relationshipLabel>
        <relationshipName>Contacts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PROZoneWHSE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>N/A No longer used. Previously used to carve out bigger territories.</description>
        <label>Zone Wirehouse</label>
        <referenceTo>Zone__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <description>Custom field no longer used</description>
        <label>ZZZTerritory</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BD FIDUCIARY NORTH CENTRAL</fullName>
                </value>
                <value>
                    <fullName>BD FIDUCIARY NORTHEAST</fullName>
                </value>
                <value>
                    <fullName>BD FIDUCIARY SOUTHEAST</fullName>
                </value>
                <value>
                    <fullName>BD FIDUCIARY TEAM</fullName>
                </value>
                <value>
                    <fullName>BD FIDUCIARY WEST</fullName>
                </value>
                <value>
                    <fullName>BT NORTH CENTRAL</fullName>
                </value>
                <value>
                    <fullName>BT NORTHEAST</fullName>
                </value>
                <value>
                    <fullName>BT SOUTHEAST</fullName>
                </value>
                <value>
                    <fullName>BT TEAM</fullName>
                </value>
                <value>
                    <fullName>BT WEST</fullName>
                </value>
                <value>
                    <fullName>BT WHSE TEAM</fullName>
                </value>
                <value>
                    <fullName>DC CENTRAL</fullName>
                </value>
                <value>
                    <fullName>DC EAST</fullName>
                </value>
                <value>
                    <fullName>DCIO</fullName>
                </value>
                <value>
                    <fullName>DCIO SUB ADV DC</fullName>
                </value>
                <value>
                    <fullName>DC WEST</fullName>
                </value>
                <value>
                    <fullName>FID FOCUS GREAT LAKES</fullName>
                </value>
                <value>
                    <fullName>FID FOCUS HEARTLAND</fullName>
                </value>
                <value>
                    <fullName>FID FOCUS MID AMERICA EAST</fullName>
                </value>
                <value>
                    <fullName>FID FOCUS NORTHWEST</fullName>
                </value>
                <value>
                    <fullName>FID FOCUS OTHER</fullName>
                </value>
                <value>
                    <fullName>FID FOCUS TEXAS</fullName>
                </value>
                <value>
                    <fullName>GLOBAL RELATIONSHIPS</fullName>
                </value>
                <value>
                    <fullName>IND ADV GRP BAY STATE</fullName>
                </value>
                <value>
                    <fullName>IND ADV GRP DELAWARE VALLEY</fullName>
                </value>
                <value>
                    <fullName>IND ADV GRP EAST CENTRAL</fullName>
                </value>
                <value>
                    <fullName>IND ADV GRP GREAT LAKES</fullName>
                </value>
                <value>
                    <fullName>IND ADV GRP GULF COAST</fullName>
                </value>
                <value>
                    <fullName>IND ADV GRP HEARTLAND</fullName>
                </value>
                <value>
                    <fullName>IND ADV GRP MID AMERICA EAST</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tier__c</fullName>
        <description>N/A No longer used.</description>
        <formula>CASE( $User.ActivityChannelName__c ,  
'ADU', TEXT(TierADU_IDU__c ), 
'IDU', TEXT(TierADU_IDU__c ),
'FIDUCIARY SERVICES', Text( PROTierFS__c ) , 
'DC REGIONAL', Text( TierRADU__c ) , 
'DCIO', Text(TierRADU__c) , 
'No Tier')</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tier Aggregated</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Channel</label>
        <referenceTo>Channel__c</referenceTo>
        <relationshipLabel>Territories</relationshipLabel>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RoleGroupId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Role Group Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/TransactionTerr__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Transcations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RepZone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rep Zone</label>
        <referenceTo>Zone__c</referenceTo>
        <relationshipLabel>Big Tickets</relationshipLabel>
        <relationshipName>Big_Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Big Tickets</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tier__c</fullName>
        <label>Tier</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <description>One day worth of data - Scrub Date of Last business day which includes manually scrubbed and auto resolved. Updated daily. Has data at the Territory level.</description>
    <label>Big Ticket</label>
    <nameField>
        <displayFormat>TR-{0000000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Big Tickets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TransactionTerrBatch.cls
global class TransactionTerrBatch implements Database.Batchable<sObject>, Database.Stateful{ 
           // This Batch Zones, Tiers and Shares the TransactionTerr__c object 
           public String query; 
           public integer Count = 0; 
           public static Map<id,Channel__c> ChannelMap { 
                get { 
                    if (ChannelMap == null) { 
                         ChannelMap = new Map<id,Channel__c>([Select Id, Name, TierField__c, ZoneField__c, FocusFirmField__c from Channel__c]); 
                    } 
                    return ChannelMap; 
                } 
                set; 
           } 
                
           global Database.querylocator start(Database.BatchableContext BC){ 
                //query = 'select id, contact__r.PROTierWHSE__c,contact__r.PROTierFS__c,
                //contact__r.PROTierIAG__c,contact__r.PROTierRS__c, contact__r.PROZoneWHSE__c, 
                //contact__r.PROZoneFS__c, contact__r.PROZoneIAG__c, contact__r.PROZoneRS__c, territory__r.Channel__c, 
                //territory__r.RoleGroupId__c from TransactionTerr__c where territory__r.Channel__r.ZoneField__c!=\'\' LIMIT 550000'; 
                return Database.getQueryLocator(query); 
           } 
                
           global void execute(Database.BatchableContext BC, List<TransactionTerr__c> scope){ 
                List<TransactionTerr__c> TransactionTerrsToUpdate = new List<TransactionTerr__c>(); 
                List<TransactionTerr__Share> TransactionTerrShareToInsert = new List<TransactionTerr__Share>(); 
               
                for(TransactionTerr__c cTransactionTerr: scope){ 
                    TransactionTerr__Share ts = new TransactionTerr__Share(AccessLevel='Read',UserOrGroupId=cTransactionTerr.territory__r.RoleGroupId__c,ParentId=cTransactionTerr.id ); 
                    TransactionTerrShareToInsert.add(ts);                     
                    TransactionTerr__c myTT = new TransactionTerr__c(id=cTransactionTerr.id); 
                    //system.debug('Channel__c---------------------' + cTransactionTerr.territory__r.Channel__c ); 
                    //String FieldName = (String)ChannelMap.get(cTransactionTerr.territory__r.Channel__c).ZoneField__c;
                    String FieldName = (cTransactionTerr.territory__c != null && cTransactionTerr.territory__r.Channel__c != null && ChannelMap.containskey(cTransactionTerr.territory__r.Channel__c) &&  ChannelMap.get(cTransactionTerr.territory__r.Channel__c).ZoneField__c != null) ? (String)ChannelMap.get(cTransactionTerr.territory__r.Channel__c).ZoneField__c : null;
                    
                    if (FieldName <> null){ 
                        //system.debug('---------------------' + (id)cTransactionTerr.get(FieldName)); 
                        myTT.RepZone__c = (id)cTransactionTerr.getSObject('Contact__r').get(FieldName); 
                    } 
                   // FieldName = (String)ChannelMap.get(cTransactionTerr.territory__r.Channel__c).TierField__c;  
                    FieldName = (cTransactionTerr.territory__c != null && cTransactionTerr.territory__r.Channel__c != null && ChannelMap.containskey(cTransactionTerr.territory__r.Channel__c) && ChannelMap.get(cTransactionTerr.territory__r.Channel__c).TierField__c != null) ? (String)ChannelMap.get(cTransactionTerr.territory__r.Channel__c).TierField__c : null; 
                    
                    if (FieldName <> null){ 
                        //system.debug('---------------------' + (id)cTransactionTerr.get(FieldName)); 
                        myTT.Tier__c = (String)cTransactionTerr.getSObject('Contact__r').get(FieldName); 
                    } 
                    
                    TransactionTerrsToUpdate.add(myTT); 
                    Count = Count + 1; 
                } 
               
                if (!TransactionTerrsToUpdate.isEmpty()) {if(!test.isrunningtest()){update TransactionTerrsToUpdate;}} 
                if (!TransactionTerrShareToInsert.isEmpty()){if(!test.isrunningtest()){insert TransactionTerrShareToInsert;}}                 
           } 
                
           global void finish(Database.BatchableContext BC){ 
                /*Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage(); 
                String[] toAddresses = new String[] {'dat@ngam.natixis.com'}; 
                mail.setToAddresses(toAddresses); 
                mail.setReplyTo('dat@ngam.natixis.com'); 
                mail.setSenderDisplayName('NGAM SFDC'); 
                mail.setSubject('TransactionTerr__c Processed'); 
                mail.setPlainTextBody(Count + ' TransactionTerr__c records were processed'); 
                if (!Test.IsRunningTest()) Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail }); 
                */ 
           } 
}