objects/Channel__c.object
<CustomObject>
    <fields>
        <fullName>FocusFirmField__c</fullName>
        <label>Focus Firm Field</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RotationField__c</fullName>
        <label>Rotation Field</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TierField__c</fullName>
        <label>Tier Field</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZoneField__c</fullName>
        <label>Zone Field</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>BPL__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Source: Updates will be made on a quarterly basis and submitted by sales to john Scuzzarella and then we bulk update</description>
        <inlineHelpText>Indicates that the Rep/Contact is at a Top 200</inlineHelpText>
        <label>Top 200 Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <description>Wells FA data in Salesforce requested by Joseph Labresh. This field labels each FA by what channel they work in: “PCG”, “WBS”, and “Finet”.</description>
        <inlineHelpText>This field is about Wells FA data, it labels each FA by what channel they work in: “PCG”, “WBS”, and “Finet”.</inlineHelpText>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PCG</fullName>
                </value>
                <value>
                    <fullName>WBS</fullName>
                </value>
                <value>
                    <fullName>FiNet</fullName>
                </value>
                <value>
                    <fullName>RIA Hybrid</fullName>
                </value>
                <value>
                    <fullName>Independent</fullName>
                </value>
                <value>
                    <fullName>Bank</fullName>
                </value>
                <value>
                    <fullName>RIA IFA Advisor</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Licensed Branch Employee</fullName>
                </value>
                <value>
                    <fullName>Insurance Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PrimaryRegionName__c</fullName>
        <description>Primary Territory of the contact's parent territory name (region) - used in Apex</description>
        <formula>PrimaryTerritoryLookup__r.ParentTerritoryName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Region Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryRegion__c</fullName>
        <description>Based on the nightly job logic and Contact Territory., Mapped to Pardot.</description>
        <label>Primary Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryTerritoryName__c</fullName>
        <description>Name of the primary territory - used in Apex</description>
        <formula>PrimaryTerritoryLookup__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Territory Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryTerritory__c</fullName>
        <description>Populated by a nightly job based on contact territory and logic.</description>
        <label>Primary Territory</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ContactChannelHelper.cls
public class ContactChannelHelper {
    
    public static Map<id,Channel__c> ChannelMap {
        get {
            if (ChannelMap == null) {
                ChannelMap = new Map<id,Channel__c>([Select Id, Name, TierField__c, ZoneField__c, FocusFirmField__c from Channel__c ]);
            }
            return ChannelMap;
        }
        set;
    }
        
    public static Map<id,Contact> ContactChannelFieldMap(Set<Id> ContactIds) {
        //Takes a set of contact Ids and return a map of the the contact with channel-defined field data
        
        Set<String> channelContactFields = ChannelFieldSet();
        
        //Get all Contact fields from schema
        Map<String, Schema.SObjectField> fldObjMap = schema.SObjectType.Contact.fields.getMap();        
        List<Schema.SObjectField> fldObjMapValues = fldObjMap.values();
        
        //Build the query using fields from contact if they exist in the set of fields from channel
        String theQuery = 'SELECT Id, ';        
        for(Schema.SObjectField s : fldObjMapValues)        {           
            String theName = s.getDescribe().getName();
            if (channelContactFields.contains(theName)) {
                theQuery += theName + ',';       
            }
        }       
        theQuery += ' BPL__c, PrimaryTerritory__c, PrimaryRegion__c, PrimaryRegionName__c, PrimaryTerritoryName__c ';    
        // Finalize query string       
        theQuery += ' FROM Contact where id IN :ContactIds'; 
        
        system.debug('ContactMap Query: ' + theQuery);
        
		// Use the query string to get the contact map
        Map <Id, Contact> ccfm = new Map<Id, Contact>(
            (List<Contact>)Database.query(theQuery)
        );

        return ccfm;

    }

    public static String ContactChannelFieldQuery() {
        
        Set<String> channelContactFields = ChannelFieldSet();
        system.debug('ccf' + channelContactFields);
        
        //Get all Contact fields from schema
        Map<String, Schema.SObjectField> fldObjMap = schema.SObjectType.Contact.fields.getMap();        
        List<Schema.SObjectField> fldObjMapValues = fldObjMap.values();
        
        //Build the query using fields from contact if they exist in the set of fields from channel
        String theQuery = 'SELECT Id, ';        
        for(Schema.SObjectField s : fldObjMapValues)        {           
            String theName = s.getDescribe().getName();
            if (channelContactFields.contains(theName)) {
                theQuery += 'contact__r.' + theName + ',';       
            }
        }       
       
        system.debug('ContactMap Query: ' + theQuery);
        
        return theQuery;

    }

    public static Set<String> ChannelFieldSet() {
        
        //Get all the fieldnames in any of the contact channel fields
        Set<String> channelContactFields = new Set<String>();
        List<Channel__c> channels = new List<Channel__c>([SELECT Id, FocusFirmField__c, RotationField__c, TierField__c, ZoneField__c
                                                          FROM Channel__c]);
        
        for (Channel__c c : channels) {
            if (c.FocusFirmField__c != null) {
                channelContactFields.add(c.FocusFirmField__c);   
            }
            if (c.RotationField__c != null) {
                channelContactFields.add(c.RotationField__c);   
            }
            if (c.TierField__c != null) {
                channelContactFields.add(c.TierField__c);   
            }
            if (c.ZoneField__c != null) {
                channelContactFields.add(c.ZoneField__c);   
            }
        }
        
        return channelContactFields;
        
    }
    
}