objects/Channel__c.object
<CustomObject>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/NGAMSettings__c.object
<CustomObject>
    <fields>
        <fullName>ProfileSystemAdministrator__c</fullName>
        <description>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</description>
        <inlineHelpText>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</inlineHelpText>
        <label>Profile: System Administrator</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Holds the NGAM settings</description>
    <label>NGAM Settings</label>
</CustomObject>

objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Channel</label>
        <referenceTo>Channel__c</referenceTo>
        <relationshipLabel>Territories</relationshipLabel>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RoleGroupId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Role Group Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/TransactionTerr__c.object
<CustomObject>
    <fields>
        <fullName>ScrubDate__c</fullName>
        <label>Scrub Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Big Tickets</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TradeID__c</fullName>
        <externalId>true</externalId>
        <label>Trade ID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TransactionType__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Purchases</fullName>
                </value>
                <value>
                    <fullName>Redemptions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>One day worth of data - Scrub Date of Last business day which includes manually scrubbed and auto resolved. Updated daily. Has data at the Territory level.</description>
    <label>Big Ticket</label>
    <nameField>
        <displayFormat>TR-{0000000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Big Tickets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>UserID__c</fullName>
        <defaultValue>"Populate This Field"</defaultValue>
        <externalId>true</externalId>
        <label>UserID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TransactionTerrBatch_Test.cls
@isTest  
private class TransactionTerrBatch_Test {
    static testMethod void TransactionTerrBatchTesting() {
        
       // Profile p = [select id from profile where name='System Administrator']; 
        DataFactory.CreateNGAMCustomSettings(); 
        NGAMSettings__c ngamSettings = [select id,ProfileSystemAdministrator__c from NGAMSettings__c limit 1]; 
        string p = Util.getCustomSettingProfileId(ngamSettings.ProfileSystemAdministrator__c);
        
        User u2 = new User(alias = 'standt', email='SFDCadmin@ngam.natixis.com', 
                           emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
                           localesidkey='en_US', profileid = p, 
                           timezonesidkey='America/Los_Angeles', username='SFDCadmin@ngam.natixis.com',UserID__c='SFDCadmin');
        
        System.runAs(u2) {
            List<id> TransactionTerrJobList = new List<id>();
            
            DateTime SplitDate = system.now().addDays(-16);
            String formatedDt = SplitDate.format('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'');
            
            TransactionTerr__c tc = new TransactionTerr__c(TradeID__c ='test'); 
            insert tc;
            
            TransactionTerrBatch ttj1 = new TransactionTerrBatch();
            Map<id,Channel__c> channelMaps = TransactionTerrBatch.ChannelMap; 
            ttj1.query = ContactChannelHelper.ContactChannelFieldQuery();
            /*ttj1.query += ' territory__r.Channel__c, territory__r.RoleGroupId__c from TransactionTerr__c where TransactionType__c=\'Purchases\'';
            ttj1.query += ' and ScrubDate__c >='+ SplitDate.format('yyyy-MM-dd')+'T'+ SplitDate.format('HH:mm')+':00.000Z LIMIT 2000';*/
            ttj1.query += ' territory__r.Channel__c, territory__r.RoleGroupId__c from TransactionTerr__c LIMIT 2000'; 
            
            system.debug(ttj1.query);
            ID ttjid1 = database.executeBatch(ttj1,2000); 
            TransactionTerrJobList.add(ttjid1);
            
        }
    }
}