objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Territory__c</fullName>
        <description>Custom field no longer used</description>
        <label>ZZZTerritory</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BD FIDUCIARY NORTH CENTRAL</fullName>
                </value>
                <value>
                    <fullName>BD FIDUCIARY NORTHEAST</fullName>
                </value>
                <value>
                    <fullName>BD FIDUCIARY SOUTHEAST</fullName>
                </value>
                <value>
                    <fullName>BD FIDUCIARY TEAM</fullName>
                </value>
                <value>
                    <fullName>BD FIDUCIARY WEST</fullName>
                </value>
                <value>
                    <fullName>BT NORTH CENTRAL</fullName>
                </value>
                <value>
                    <fullName>BT NORTHEAST</fullName>
                </value>
                <value>
                    <fullName>BT SOUTHEAST</fullName>
                </value>
                <value>
                    <fullName>BT TEAM</fullName>
                </value>
                <value>
                    <fullName>BT WEST</fullName>
                </value>
                <value>
                    <fullName>BT WHSE TEAM</fullName>
                </value>
                <value>
                    <fullName>DC CENTRAL</fullName>
                </value>
                <value>
                    <fullName>DC EAST</fullName>
                </value>
                <value>
                    <fullName>DCIO</fullName>
                </value>
                <value>
                    <fullName>DCIO SUB ADV DC</fullName>
                </value>
                <value>
                    <fullName>DC WEST</fullName>
                </value>
                <value>
                    <fullName>FID FOCUS GREAT LAKES</fullName>
                </value>
                <value>
                    <fullName>FID FOCUS HEARTLAND</fullName>
                </value>
                <value>
                    <fullName>FID FOCUS MID AMERICA EAST</fullName>
                </value>
                <value>
                    <fullName>FID FOCUS NORTHWEST</fullName>
                </value>
                <value>
                    <fullName>FID FOCUS OTHER</fullName>
                </value>
                <value>
                    <fullName>FID FOCUS TEXAS</fullName>
                </value>
                <value>
                    <fullName>GLOBAL RELATIONSHIPS</fullName>
                </value>
                <value>
                    <fullName>IND ADV GRP BAY STATE</fullName>
                </value>
                <value>
                    <fullName>IND ADV GRP DELAWARE VALLEY</fullName>
                </value>
                <value>
                    <fullName>IND ADV GRP EAST CENTRAL</fullName>
                </value>
                <value>
                    <fullName>IND ADV GRP GREAT LAKES</fullName>
                </value>
                <value>
                    <fullName>IND ADV GRP GULF COAST</fullName>
                </value>
                <value>
                    <fullName>IND ADV GRP HEARTLAND</fullName>
                </value>
                <value>
                    <fullName>IND ADV GRP MID AMERICA EAST</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/NGAMSettings__c.object
<CustomObject>
    <fields>
        <fullName>ProfileSystemAdministrator__c</fullName>
        <description>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</description>
        <inlineHelpText>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</inlineHelpText>
        <label>Profile: System Administrator</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Holds the NGAM settings</description>
    <label>NGAM Settings</label>
</CustomObject>

objects/NGAMSettingsHierarchy__c.object
<CustomObject>
    <fields>
        <fullName>ByPassAccountValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows entity to by-pass validation rules on Account</description>
        <inlineHelpText>Allows entity to by-pass validation rules on Account</inlineHelpText>
        <label>By-Pass Account Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NGAM Settings - Hierarchy</label>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>RepContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For the PRCG Process to be populated with Rep/Contact associated to the request.</description>
        <label>Contact/Rep</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Do Not Show)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <description>Used in Reports to display the primary territory</description>
        <formula>Owner.ActivityTerritoryName__c</formula>
        <label>Territory</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>GroupId__c</fullName>
        <externalId>true</externalId>
        <label>Group Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RoleGroupId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Role Group Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RoleId__c</fullName>
        <externalId>true</externalId>
        <label>Role Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TerritoryName__c</fullName>
        <defaultValue>"Update Me"</defaultValue>
        <externalId>true</externalId>
        <label>MARS Territory Name</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TerritoryType__c</fullName>
        <label>Territory Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Territory</fullName>
                </value>
                <value>
                    <fullName>Region</fullName>
                </value>
                <value>
                    <fullName>Department</fullName>
                </value>
                <value>
                    <fullName>Division</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ActivityTerritoryId__c</fullName>
        <description>Used To Tag the Activities and Opportunities created by the user.</description>
        <externalId>true</externalId>
        <inlineHelpText>READ ONLY FIELD : This Will be populated by the UserTerritory__c assignment when the Territory Assignment is tagged as an Activity Territory. Please never update this field directly. Instead Delete/Insert the relevant UserTerritory__c record.</inlineHelpText>
        <label>Activity Territory Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryMARSName__c</fullName>
        <description>The MARS Name of the Activity Territory (Territory__c.TerritoryName__c)</description>
        <label>Activity Territory MARS Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryParentId__c</fullName>
        <description>The Activity Territory's parent Id</description>
        <label>Activity Territory Parent Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryRoleGroupId__c</fullName>
        <description>The RoleGroupId from the activity territory's territory</description>
        <label>Activity Territory RoleGroupId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryRoleId__c</fullName>
        <description>The role Id from the user's activity territory</description>
        <label>Activity Territory RoleId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryType__c</fullName>
        <description>The type of territory for the Activity Territory</description>
        <label>Activity Territory Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserID__c</fullName>
        <defaultValue>"Populate This Field"</defaultValue>
        <externalId>true</externalId>
        <label>UserID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/OpportunityTriggerHandler_Test.cls
@isTest
private class OpportunityTriggerHandler_Test {
    static testMethod void ValidateAll() {
    
        NGAMSettingsHierarchy__c hsettings = NGAMSettingsHierarchy__c.getOrgDefaults();
        hsettings.ByPassAccountValidationRules__c  = TRUE;
        upsert hsettings NGAMSettingsHierarchy__c.Id;
        
       // Profile p = [select id from profile where name='System Administrator']; 
        DataFactory.CreateNGAMCustomSettings(); 
        NGAMSettings__c ngamSettings = [select id,ProfileSystemAdministrator__c from NGAMSettings__c limit 1]; 
        string p = Util.getCustomSettingProfileId(ngamSettings.ProfileSystemAdministrator__c);
        
        User u = new User(alias = 'standt', email='SFDCadmin@ngam.natixis.com', 
                          emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
                          localesidkey='en_US', profileid = p, 
                          timezonesidkey='America/Los_Angeles', username='SFDCadmin@ngam.natixis.com',UserID__c='SFDCadmin');
        //insert u;
        System.runAs(u) 
        {
            List<Territory__c> territories = new List<Territory__c>();
            territories.add(new Territory__c(Name='Test',TerritoryName__c='Test',RoleID__c = '',GroupID__c = '',TerritoryType__c='Territory'));
            territories.add(new Territory__c(Name='Test2',TerritoryName__c='Test2',RoleID__c = '',GroupID__c = '',TerritoryType__c='Region'));
            territories.add(new Territory__c(Name='Test2',TerritoryName__c='Test3',RoleID__c = '',GroupID__c = '',TerritoryType__c='Company'));            
            insert territories;
            
            List<UserRole> userRoles = new List<UserRole>();
            UserRole ur1 = new UserRole(Name = territories[0].Name, DeveloperName = territories[0].Id, 
                                       CaseAccessForAccountOwner = 'Read', OpportunityAccessForAccountOwner = 'Read',
                                       ContactAccessForAccountOwner = 'Read');
            UserRoles.add(ur1);
            UserRole ur2 = new UserRole(Name = territories[1].Name, DeveloperName = territories[1].Id, 
                                       CaseAccessForAccountOwner = 'Read', OpportunityAccessForAccountOwner = 'Read',
                                       ContactAccessForAccountOwner = 'Read');
            userRoles.add(ur2);
            UserRole ur3 = new UserRole(Name = territories[1].Name, DeveloperName = territories[2].Id, 
                                       CaseAccessForAccountOwner = 'Read', OpportunityAccessForAccountOwner = 'Read',
                                       ContactAccessForAccountOwner = 'Read');
            userRoles.add(ur3);
            insert userRoles;

            Map<Id,Id> territoryGroupMap = new Map<Id,Id>();
            
            Group userGroup1=[SELECT Id FROM Group 
                              WHERE RelatedId = :userRoles[0].Id 
                              AND Type = 'RoleAndSubordinates'];
            
            Group userGroup2=[SELECT Id FROM Group 
                              WHERE RelatedId = :userRoles[1].Id 
                              AND Type = 'RoleAndSubordinates'];
            
            Group userGroup3=[SELECT Id FROM Group 
                              WHERE RelatedId = :userRoles[2].Id 
                              AND Type = 'RoleAndSubordinates'];

			List<Territory__Share> territoryShares = new List<Territory__Share>();          
            territoryShares.add(new Territory__Share(AccessLevel='Read',UserOrGroupId=userGroup1.Id,ParentId=territories[0].Id));
            territoryShares.add(new Territory__Share(AccessLevel='Read',UserOrGroupId=userGroup2.Id,ParentId=territories[1].Id));
            territoryShares.add(new Territory__Share(AccessLevel='Read',UserOrGroupId=userGroup3.Id,ParentId=territories[2].Id));
            insert territoryShares;   
            
            territories[0].RoleID__c = userRoles[0].Id;
            territories[0].RoleGroupId__c = userGroup1.id;
            territories[1].RoleID__c = userRoles[1].Id;
            territories[1].RoleGroupId__c = userGroup2.id;    
            territories[2].RoleID__c = userRoles[2].Id;
            territories[2].RoleGroupId__c = userGroup3.id;    
            update territories;
            
            u.ActivityTerritoryId__c = territories[0].id;
            u.ActivityTerritoryParentId__c = territories[1].id;
            u.ActivityTerritoryType__c = territories[0].TerritoryType__c;
            u.ActivityTerritoryMARSName__c = territories[0].TerritoryName__c;
            u.ActivityTerritoryRoleGroupId__c = territories[0].RoleGroupId__c;
            u.ActivityTerritoryRoleId__c = territories[0].RoleId__c;
            update u;

            List<Account> accts = DataFactory.createTestAccounts(1);
            insert accts;
            
            List<Contact> contacts = DataFactory.createTestContacts(3, accts, FALSE);
            insert contacts;
            
			List<Opportunity> opptys = new List<Opportunity>();
            opptys.add(new Opportunity(Name='test', AccountId=accts[0].Id, StageName='Prospect', CloseDate=system.today()));
            opptys.add(new Opportunity(Name='test2', AccountId=accts[0].Id, RepContact__c = contacts[0].Id,
                                       StageName='Prospect', CloseDate=system.today()));
			insert opptys;
            
            opptys[0].RepContact__c = contacts[0].Id;
            opptys[1].RepContact__c = contacts[1].Id;
            update opptys;
            
            opptys[0].RepContact__c = contacts[1].Id;
            opptys[1].RepContact__c = contacts[0].Id;
            update opptys;
            
        }
    }
}