objects/ContactTerritory__c.object
<CustomObject>
    <fields>
        <fullName>ContactTerritory__c</fullName>
        <formula>Contact__c +'-'+ Territory__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ContactTerritory</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Territories</relationshipLabel>
        <relationshipName>Contact_Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RoleId__c</fullName>
        <formula>Territory__r.RoleId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Role Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TerrGroupId__c</fullName>
        <formula>Territory__r.GroupId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TerrGroupId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Territory__c.RoleId__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Contact Territories</relationshipLabel>
        <relationshipName>Territory_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Contact Territory</label>
    <nameField>
        <displayFormat>CT-{0000000000}</displayFormat>
        <label>Contact Territory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Territories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>GroupId__c</fullName>
        <externalId>true</externalId>
        <label>Group Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RoleGroupId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Role Group Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RoleId__c</fullName>
        <externalId>true</externalId>
        <label>Role Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ContactShareBatch.cls
global class ContactShareBatch implements Database.Batchable<sObject>, Database.Stateful{
    
    public String query;
    public set<id> GContactIds = new set<id>();  
    public integer CScount = 0;
    
    global Database.querylocator start(Database.BatchableContext BC){   
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<ContactTerritory__c> scope)
    { 
        List<ContactShare> sharesToCreate = new List<ContactShare>();
        set<id> ContactIds = new set<id>();       
        
        for (ContactTerritory__c TA: scope)
        {
            if (!GContactIds.contains(TA.Contact__c))  
            {
                ContactIds.add(TA.Contact__c);    
            } 
            //ContactIds.add(TA.Contact__c); 
            //system.debug('TA.Contact__c' + TA.Contact__c);    
            
            ContactShare cs = new ContactShare();
            cs.ContactAccessLevel = 'Edit';
            cs.ContactId = TA.Contact__c;
            //cs.UserOrGroupId = MyGroups.get(TA.RoleId__c);
            cs.UserOrGroupId = TA.Territory__r.RoleGroupId__c;
            sharesToCreate.add(cs);  
            
            //ContactShare cs2 = new ContactShare();
            //cs2.ContactAccessLevel = 'Edit';
            //cs2.ContactId = TA.Contact__c;
            //cs2.UserOrGroupId = TA.TerrGroupId__c;
            //cs2.UserOrGroupId = TA.Territory__r.GroupId__c;
            //sharesToCreate.add(cs2);
            
            GContactIds.add(TA.Contact__c);      
        }    
        
        List<ContactShare> sharesToDelete = new List<ContactShare>([select id from ContactShare where Rowcause='Manual' and contactid in: ContactIds]);  
        //system.debug('vrdelete:' + sharesToDelete.size());
        
        if (!sharesToDelete.isEmpty())
        {   
            delete sharesToDelete;
        } 
        
        if (!sharesToCreate.isEmpty())
        {   
            insert sharesToCreate;
        }  
        
    }
    
    global void finish(Database.BatchableContext BC)
    {
        /*try{
Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
String[] toAddresses = new String[] {'dat@ngam.natixis.com'};
mail.setToAddresses(toAddresses);
mail.setReplyTo('dat@ngam.natixis.com');
mail.setSenderDisplayName('DAT');
mail.setSubject('ContactsShare computation Completed');
mail.setPlainTextBody('Batch Process has completed and ' + CSCount + ' Role Contactshare were created');
//mail.setPlainTextBody('All Good !');
if (!Test.IsRunningTest()) Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });  
}
catch (Exception e) {
System.debug('Exception: ' + e);            
} */   
    }
    
}