objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Territory__c</fullName>
        <description>Custom field no longer used</description>
        <label>ZZZTerritory</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BD FIDUCIARY NORTH CENTRAL</fullName>
                </value>
                <value>
                    <fullName>BD FIDUCIARY NORTHEAST</fullName>
                </value>
                <value>
                    <fullName>BD FIDUCIARY SOUTHEAST</fullName>
                </value>
                <value>
                    <fullName>BD FIDUCIARY TEAM</fullName>
                </value>
                <value>
                    <fullName>BD FIDUCIARY WEST</fullName>
                </value>
                <value>
                    <fullName>BT NORTH CENTRAL</fullName>
                </value>
                <value>
                    <fullName>BT NORTHEAST</fullName>
                </value>
                <value>
                    <fullName>BT SOUTHEAST</fullName>
                </value>
                <value>
                    <fullName>BT TEAM</fullName>
                </value>
                <value>
                    <fullName>BT WEST</fullName>
                </value>
                <value>
                    <fullName>BT WHSE TEAM</fullName>
                </value>
                <value>
                    <fullName>DC CENTRAL</fullName>
                </value>
                <value>
                    <fullName>DC EAST</fullName>
                </value>
                <value>
                    <fullName>DCIO</fullName>
                </value>
                <value>
                    <fullName>DCIO SUB ADV DC</fullName>
                </value>
                <value>
                    <fullName>DC WEST</fullName>
                </value>
                <value>
                    <fullName>FID FOCUS GREAT LAKES</fullName>
                </value>
                <value>
                    <fullName>FID FOCUS HEARTLAND</fullName>
                </value>
                <value>
                    <fullName>FID FOCUS MID AMERICA EAST</fullName>
                </value>
                <value>
                    <fullName>FID FOCUS NORTHWEST</fullName>
                </value>
                <value>
                    <fullName>FID FOCUS OTHER</fullName>
                </value>
                <value>
                    <fullName>FID FOCUS TEXAS</fullName>
                </value>
                <value>
                    <fullName>GLOBAL RELATIONSHIPS</fullName>
                </value>
                <value>
                    <fullName>IND ADV GRP BAY STATE</fullName>
                </value>
                <value>
                    <fullName>IND ADV GRP DELAWARE VALLEY</fullName>
                </value>
                <value>
                    <fullName>IND ADV GRP EAST CENTRAL</fullName>
                </value>
                <value>
                    <fullName>IND ADV GRP GREAT LAKES</fullName>
                </value>
                <value>
                    <fullName>IND ADV GRP GULF COAST</fullName>
                </value>
                <value>
                    <fullName>IND ADV GRP HEARTLAND</fullName>
                </value>
                <value>
                    <fullName>IND ADV GRP MID AMERICA EAST</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ContactTerritory__c.object
<CustomObject>
    <fields>
        <fullName>ContactTerrId__c</fullName>
        <externalId>true</externalId>
        <label>ContactTerrId</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ContactTerritory__c</fullName>
        <formula>Contact__c +'-'+ Territory__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ContactTerritory</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Territories</relationshipLabel>
        <relationshipName>Contact_Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RoleId__c</fullName>
        <formula>Territory__r.RoleId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Role Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TerritoryName__c</fullName>
        <formula>Territory__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TerritoryName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Territory__c.RoleId__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Contact Territories</relationshipLabel>
        <relationshipName>Territory_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Contact Territory</label>
    <nameField>
        <displayFormat>CT-{0000000000}</displayFormat>
        <label>Contact Territory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Territories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/NGAMSettings__c.object
<CustomObject>
    <fields>
        <fullName>ProfileSystemAdministrator__c</fullName>
        <description>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</description>
        <inlineHelpText>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</inlineHelpText>
        <label>Profile: System Administrator</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Holds the NGAM settings</description>
    <label>NGAM Settings</label>
</CustomObject>

objects/NGAMSettingsHierarchy__c.object
<CustomObject>
    <fields>
        <fullName>ByPassAccountValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows entity to by-pass validation rules on Account</description>
        <inlineHelpText>Allows entity to by-pass validation rules on Account</inlineHelpText>
        <label>By-Pass Account Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NGAM Settings - Hierarchy</label>
</CustomObject>

objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>GroupId__c</fullName>
        <externalId>true</externalId>
        <label>Group Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RoleGroupId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Role Group Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RoleId__c</fullName>
        <externalId>true</externalId>
        <label>Role Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TerritoryName__c</fullName>
        <defaultValue>"Update Me"</defaultValue>
        <externalId>true</externalId>
        <label>MARS Territory Name</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>UserID__c</fullName>
        <defaultValue>"Populate This Field"</defaultValue>
        <externalId>true</externalId>
        <label>UserID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ContactShareBatch_Test.cls
@isTest
private class ContactShareBatch_Test {
    static testMethod void ContactShareBatchTesting() {

       //Profile p = [select id from profile where name='System Administrator']; 
        NGAMSettingsHierarchy__c hsettings = NGAMSettingsHierarchy__c.getOrgDefaults();
        hsettings.ByPassAccountValidationRules__c  = TRUE;
        upsert hsettings NGAMSettingsHierarchy__c.Id;
    
       
       DataFactory.CreateNGAMCustomSettings(); 
       NGAMSettings__c ngamSettings = [select id,ProfileSystemAdministrator__c from NGAMSettings__c limit 1]; 
       string p = Util.getCustomSettingProfileId(ngamSettings.ProfileSystemAdministrator__c);
        
       User u2 = new User(alias = 'standt', email='SFDCadmin@ngam.natixis.com', 
                            emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
                            localesidkey='en_US', profileid = p, 
                            timezonesidkey='America/Los_Angeles', username='SFDCadmin@ngam.natixis.com',UserID__c='SFDCadmin');
        
        System.runAs(u2) 
                {
                //Creating the Territory
                Territory__c Terr = new Territory__c(Name='Test',TerritoryName__c='Test'); 
                insert Terr; 
                    
                // Creating the Corresponding Role
                UserRole Ur = new UserRole();
                Ur.Name = Terr.Name;
                Ur.DeveloperName = Terr.Id;
                Ur.CaseAccessForAccountOwner = 'Read';
                Ur.OpportunityAccessForAccountOwner = 'Read';
                Ur.ContactAccessForAccountOwner = 'Read';
                insert Ur; 
                    
                Group UrGroup = [select id, relatedid from group where relatedid=:Ur.id limit 1][0];    
                
                Terr.RoleID__c = ur.id;   
                Terr.RoleGroupId__c = UrGroup.id;    
                update Terr;     
               
                Account myA = new Account(name='test me') ;   
                insert MyA;  
                
                Contact myC = new Contact(firstname='test',lastname='test', accountid=MyA.id);
                insert myC; 
                
                Test.StartTest();
     
                ContactTerritory__c myAC = new  ContactTerritory__c(contact__c =myC.id, territory__c=Terr.id, COntactTerrId__c = 'CO231176A507' );
                insert myAC ;
                      
                ContactShareBatch CSI = new ContactShareBatch();
                CSI.query =  'select Contact__c, Territory__r.RoleGroupId__c, Territory__r.GroupId__c from ContactTerritory__c';    
                ID CSIid = database.executeBatch(CSI);     
                    
                test.stopTest();          
                delete myAC;    

                }
        }
}