objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EmailPreference__c</fullName>
        <description>Source: MARS na_load_rep.
Loaded by a nightly job. Data Flow: SF -&gt; Mars</description>
        <inlineHelpText>One-to-one email preference</inlineHelpText>
        <label>Email Preference</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ALWAYS</fullName>
                    <default>true</default>
                    <label>ALWAYS</label>
                </value>
                <value>
                    <fullName>NEVER</fullName>
                </value>
                <value>
                    <fullName>ON REQUEST</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ExchangeOptout__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email of the user opting out.</description>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <description>This object contains the opt-outs of the contacts done through exchange.</description>
    <label>Exchange Optout</label>
    <nameField>
        <displayFormat>EO-{0000000000}</displayFormat>
        <label>ExchangeOptout Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exchange Optouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ExchangeOptoutContact__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Exchange Optout Contacts</relationshipLabel>
        <relationshipName>Exchange_Optout_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExchangeOptout__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Exchange Optout</label>
        <referenceTo>ExchangeOptout__c</referenceTo>
        <relationshipLabel>Exchange Optout Contacts</relationshipLabel>
        <relationshipName>Exchange_Optout_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Exchange Optout Contact</label>
    <nameField>
        <displayFormat>EOC-{0000000000}</displayFormat>
        <label>Exchange Optout Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exchange Optout Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ExchangeOptoutTriggerHandler.cls
public class ExchangeOptoutTriggerHandler {
    
    //-----------------------------------------------------------------------------------------------------------------------------------------------
    // ExchangeOptout After Insert
    // 
	//-----------------------------------------------------------------------------------------------------------------------------------------------
    public static void ExchangeOptoutAfterInsert (List<ExchangeOptout__c> ExchangeOptouts)
    	{

            Set<String> Emails = new Set<String>();
            
            for (ExchangeOptout__c cEO : ExchangeOptouts)
                {    
                    if (cEO.Email__c != '')    
                    	{
                        Emails.add(cEO.Email__c);
                    	}
                }
            List<contact> ContactsToUpdate = new List<contact> ();
            
            List<contact> ContactsToOptOut = [select id, email from contact where email in : Emails];
            
            for (Contact cCont : ContactsToOptOut)
                {
                 ContactsToUpdate.add(new Contact(id=cCont.id,HasOptedOutOfEmail=true, EmailPreference__c='NEVER'));
                }
            
            List<ExchangeOptoutContact__c> ContactsToOptOutDetail = new List<ExchangeOptoutContact__c> ();
            
            for (ExchangeOptout__c cEO : ExchangeOptouts)
                {
                    for (contact mc : ContactsToOptOut) 
                        {
                            if (mc.email == cEO.Email__c)
                            {
                             ExchangeOptoutContact__c EOoC = new ExchangeOptoutContact__c(Contact__c = mc.id, ExchangeOptout__c=cEO.id);
                             ContactsToOptOutDetail.add(EOoC);
                            } 
                        }
                }
            
            if (!ContactsToUpdate.isEmpty())
            	{
                update ContactsToUpdate;    
            	}
            
            
            if (!ContactsToOptOutDetail.isEmpty())
            	{
                insert ContactsToOptOutDetail;    
            	}    

		}
    
}