objects/Contact.object
<CustomObject>
    <fields>
        <fullName>MarsRepId__c</fullName>
        <description>Source: MARS na_load_rep.Id
Loaded by a nightly job. Unique identifier for MARS. Data Flow: Mars -&gt; SF</description>
        <externalId>true</externalId>
        <label>MARS Rep Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/NGAMSettings__c.object
<CustomObject>
    <fields>
        <fullName>ProfileSystemAdministrator__c</fullName>
        <description>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</description>
        <inlineHelpText>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</inlineHelpText>
        <label>Profile: System Administrator</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Holds the NGAM settings</description>
    <label>NGAM Settings</label>
</CustomObject>

objects/NGAMSettingsHierarchy__c.object
<CustomObject>
    <fields>
        <fullName>ByPassAccountValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows entity to by-pass validation rules on Account</description>
        <inlineHelpText>Allows entity to by-pass validation rules on Account</inlineHelpText>
        <label>By-Pass Account Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NGAM Settings - Hierarchy</label>
</CustomObject>

objects/PortalActivity__c.object
<CustomObject>
    <fields>
        <fullName>RepId__c</fullName>
        <description>An additional Id of the contact to which this Portal Activity belongs (i.e., email, MARS Id, etc.)</description>
        <inlineHelpText>An additional Id of the contact to which this Portal Activity belongs (i.e., email, MARS Id, etc.)</inlineHelpText>
        <label>Rep Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <inlineHelpText>The SFID of the user that logging into the PRGC portal.</inlineHelpText>
        <label>User Id</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>code__c</fullName>
        <description>Artemus.dbo.Portal_Audit_Log.Code(100)</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique identifier for this Portal Activity record.  This is sometimes the SFID of the record and sometimes fed in through the system calling the activity creation.</inlineHelpText>
        <label>code</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <description>Tracks important web and portal activities.  Records created systematically by Apex/Web Services when events occur.</description>
    <label>Portal Activity</label>
    <nameField>
        <displayFormat>PA-{0000000000}</displayFormat>
        <label>Portal Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>UserID__c</fullName>
        <defaultValue>"Populate This Field"</defaultValue>
        <externalId>true</externalId>
        <label>UserID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/PortalActivityTriggerHandler_Test.cls
@isTest
private class PortalActivityTriggerHandler_Test {

    static testMethod void PortalActivityTriggerHandlerUpdateContactLookup() {
    
        NGAMSettingsHierarchy__c hsettings = NGAMSettingsHierarchy__c.getOrgDefaults();
        hsettings.ByPassAccountValidationRules__c  = TRUE;
        upsert hsettings NGAMSettingsHierarchy__c.Id;

        //Profile p = [select id from profile where name='System Administrator']; 
        DataFactory.CreateNGAMCustomSettings(); 
       NGAMSettings__c ngamSettings = [select id,ProfileSystemAdministrator__c from NGAMSettings__c limit 1]; 
       string p = Util.getCustomSettingProfileId(ngamSettings.ProfileSystemAdministrator__c);
        
        User u = new User(alias = 'standt', email='SFDCadmin@ngam.natixis.com', 
                          emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
                          localesidkey='en_US', profileid = p, 
                          timezonesidkey='America/Los_Angeles', username='SFDCadmin@ngam.natixis.com',UserID__c='SFDCadmin');
                          
        System.runAs(u) {
            // create test contact
            
            List<Account> myA = DataFactory.createTestAccounts(1);
            insert myA;
            
            contact c = new contact(MarsRepID__c = '1111', FirstName = 'user', LastName = 'test',AccountId=myA[0].Id);
            insert c;
            
             // create test user
            User user = new User(alias = 'test1', email='test1@ngam.natixis.com', 
                            emailencodingkey='UTF-8', lastname='test1', languagelocalekey='en_US', 
                            localesidkey='en_US', profileid = p, 
                            timezonesidkey='America/Los_Angeles', username='test1@ngam.natixis.com',UserID__c='test1' + Math.random());
                            
            insert(user);
            
            // create test portal activities
            List<PortalActivity__c> portalActivities = new List<PortalActivity__c>();
            portalActivities.add(new PortalActivity__c(Code__c='1111', RepId__c = c.MarsRepId__c, UserId__c = c.MarsRepId__c));    
            portalActivities.add(new PortalActivity__c(Code__c='1112', RepId__c = user.UserID__c, UserId__c = user.UserID__C)); 
            portalActivities.add(new PortalActivity__c( RepId__c = user.UserID__c, UserId__c = user.UserID__C));  
            insert portalActivities;           
        }   
    }    
}