objects/ContactTerritory__c.object
<CustomObject>
    <fields>
        <fullName>ContactTerritory__c</fullName>
        <formula>Contact__c +'-'+ Territory__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ContactTerritory</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Territories</relationshipLabel>
        <relationshipName>Contact_Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Territory__c.RoleId__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Contact Territories</relationshipLabel>
        <relationshipName>Territory_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Contact Territory</label>
    <nameField>
        <displayFormat>CT-{0000000000}</displayFormat>
        <label>Contact Territory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Territories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>GroupId__c</fullName>
        <externalId>true</externalId>
        <label>Group Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RoleGroupId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Role Group Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ContactShareWS.cls
@RestResource(urlMapping='/ContactTerritoryShare/*')
global with sharing class ContactShareWS {

    @HttpPost
    global static List<id> ComputeSharing(DateTime LastTime) {
        List<id> JobList = new List<id> ();
        
        String MyQuery = 'Select Contact__c, Territory__r.RoleGroupId__c, Territory__r.GroupId__c from ContactTerritory__c WHERE CreatedDate >'+LastTime.format('yyyy-MM-dd')+'T'+ LastTime.format('HH:mm')+':00.000Z';      
		ContactShareBatch CSI = new ContactShareBatch();
        CSI.query = MyQuery;
		ID CSIid = database.executeBatch(CSI,2000); 
        JobList.add(CSIid);
        return JobList ;
        
    }
    
}