objects/Contact.object
<CustomObject>
    <fields>
        <fullName>FullServiceSalesUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated with an evening job with Wholesaler 1 that is related to the Primary Sales Users Territory.</description>
        <label>Full Service Sales User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>FullServiceSalesUser</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MarsRepId__c</fullName>
        <description>Source: MARS na_load_rep.Id
Loaded by a nightly job. Unique identifier for MARS. Data Flow: Mars -&gt; SF</description>
        <externalId>true</externalId>
        <label>MARS Rep Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OverlapExternalUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Integrated with Pardot to display the sales user's name associated to the DCIO/DC Channel on the record.</description>
        <label>Overlap Sales User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OverlapExternalUser</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OverlapTerritory__c</fullName>
        <description>Populated by a nightly job based on the RADU Contact territories. Mapped to Pardot to segment RADU.</description>
        <label>Overlap Territory</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryMarketingUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by a nightly job based on associated Contact Territories and logic. Mapped to Pardot for personalization</description>
        <label>Primary Sales User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ContactPrimaryMarketingUser</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PrimaryRegion__c</fullName>
        <description>Based on the nightly job logic and Contact Territory., Mapped to Pardot.</description>
        <label>Primary Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryTerritoryLookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated by a nightly job based on contact territory and logic. It is populated with the territory ID.</description>
        <label>Primary Territory Lookup</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PrimaryTerritory__c</fullName>
        <description>Populated by a nightly job based on contact territory and logic.</description>
        <label>Primary Territory</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>TerritoryName__c</fullName>
        <defaultValue>"Update Me"</defaultValue>
        <externalId>true</externalId>
        <label>MARS Territory Name</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>PrimaryTerritory__c</fullName>
        <label>Primary Territory</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserID__c</fullName>
        <defaultValue>"Populate This Field"</defaultValue>
        <externalId>true</externalId>
        <label>UserID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ContactPrimaryTerritoryWS.cls
@RestResource(urlMapping='/ContactPrimaryTerritory/*')
global with sharing class ContactPrimaryTerritoryWS {

    @HttpPost
    global static List<id> ComputeSharing(DateTime LastTime) {
        List<id> JobList = new List<id> ();
        
        string myQuery = 'select Id, MarsRepId__c, PrimaryTerritory__c, PrimaryTerritoryLookup__r.TerritoryName__c, PrimaryRegion__c, PrimaryMarketingUser__r.UserId__c, FullServiceSalesUser__r.UserId__c, OverlapTerritory__c,OverlapExternalUser__r.UserId__c from contact';
                     
        ContactPrimaryTerritoryBatch cpt = new ContactPrimaryTerritoryBatch(myQuery);
        ID cptId = database.executeBatch(cpt,10000); 
        JobList.add(cptId);
        return JobList ;        
    }    
}