objects/Contact.object
<CustomObject>
    <fields>
        <fullName>MarsRepId__c</fullName>
        <description>Source: MARS na_load_rep.Id
Loaded by a nightly job. Unique identifier for MARS. Data Flow: Mars -&gt; SF</description>
        <externalId>true</externalId>
        <label>MARS Rep Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PortalActivity__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contact related to this Portal Activity.  If this value is blank, the contact has been deleted from the system.</description>
        <inlineHelpText>The contact related to this Portal Activity.  If this value is blank, the contact has been deleted from the system.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Portal Activities</relationshipLabel>
        <relationshipName>Portal_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RepId__c</fullName>
        <description>An additional Id of the contact to which this Portal Activity belongs (i.e., email, MARS Id, etc.)</description>
        <inlineHelpText>An additional Id of the contact to which this Portal Activity belongs (i.e., email, MARS Id, etc.)</inlineHelpText>
        <label>Rep Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <inlineHelpText>The SFID of the user that logging into the PRGC portal.</inlineHelpText>
        <label>User Id</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup to the User that has logged in to create this Portal Activity (PRGC)</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Portal_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>code__c</fullName>
        <description>Artemus.dbo.Portal_Audit_Log.Code(100)</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique identifier for this Portal Activity record.  This is sometimes the SFID of the record and sometimes fed in through the system calling the activity creation.</inlineHelpText>
        <label>code</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <description>Tracks important web and portal activities.  Records created systematically by Apex/Web Services when events occur.</description>
    <label>Portal Activity</label>
    <nameField>
        <displayFormat>PA-{0000000000}</displayFormat>
        <label>Portal Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>UserID__c</fullName>
        <defaultValue>"Populate This Field"</defaultValue>
        <externalId>true</externalId>
        <label>UserID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/PortalActivityTriggerHandler.cls
public class PortalActivityTriggerHandler {
    public static boolean isExecuting = false;
    
    public static void PortalActivityAfterInsert (List<PortalActivity__c> portalActivities) {           
        
        if(PortalActivityTriggerHandler.isExecuting ){
            // if was executed during the same context 
            // avoid recursion
            return;
        }
 
        PortalActivityTriggerHandler.isExecuting = true; 
    
        Set<string> repIds = new Set<string>();
        Set<string> userIds = new Set<string>();
        //Set<string> codeIds = new Set<string>();
        
        for (PortalActivity__c pa : portalActivities) {    
            if (pa.RepId__c != '' && pa.RepId__c != null) {
                repIds.add(pa.RepId__c);
            }
            if (pa.UserId__c != '' && pa.UserId__c != null) {
                userIds.add(pa.UserId__c);
            }
            //codeIds.add(pa.Code__c);
        }                  
               
        List<contact> contacts = [select Id, MarsRepId__c from contact where MarsRepId__c in : repIds];
                
        List<User> users = [select Id, UserId__c from User where UserId__c in : userIds];
      
        //List<PortalActivity__c> pas = [Select Id, RepId__c, UserId__c from PortalActivity__c where Code__c in : codeIds];               
        
        List<PortalActivity__c> l = new List<PortalActivity__c>();
        for (PortalActivity__c pa : portalActivities) {
            PortalActivity__c a = new PortalActivity__c(Id = pa.Id);
            system.debug('ff:' +pa);
            for (Contact c : contacts) {
                if (c.MarsRepId__c == pa.RepId__c) {
                    a.Contact__r = new Contact (MarsRepId__c = pa.RepId__c);
                    l.add(a);
                    break;
                }
            }  
            for (User u : users) {
                if (u.UserId__c == pa.UserId__c) {
                    a.User__r = new User (UserId__c = pa.UserId__c);
                    l.add(a);
                    break;
                }
            }                   
        }
        update l;          
    }
}