objects/DictionaryItem__c.object
<CustomObject>
    <fields>
        <fullName>APIName__c</fullName>
        <description>The API Name of the component</description>
        <label>API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Custom__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is a custom component</description>
        <label>Custom</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KeyPrefix__c</fullName>
        <description>The three-character prefix code for the object. Record IDs are prefixed with three-character codes that specify the type of the object (for example, accounts have a prefix of 001 and opportunities have a prefix of 006).</description>
        <label>Key Prefix</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <description>The label of the component</description>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MetadataIdentifier__c</fullName>
        <description>The unique id used to connect this component to SFDC standard metadata</description>
        <externalId>true</externalId>
        <label>Metadata Identifier</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PluralLabel__c</fullName>
        <description>The plural label of the component; used primarily for objects</description>
        <label>Plural Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <description>Data dictionary</description>
    <label>Dictionary Item</label>
    <nameField>
        <displayFormat>DI-{000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dictionary Items</pluralLabel>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Object</fullName>
        <active>true</active>
        <description>Use for objects</description>
        <label>Object</label>
    </recordTypes>
</CustomObject>

objects/DictionaryItemStandardObject__mdt.object
<CustomObject>
    <fields>
        <fullName>APIName__c</fullName>
        <description>The API Name of the standard object to be included in the Dictionary Item object</description>
        <inlineHelpText>The API Name of the standard object to be included in the Dictionary Item object</inlineHelpText>
        <label>API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <description>Lists all Standard Objects that should be included in the Dictionary Items object; if the standard object is not in this list, it will NOT be in the Dictionary Items object.</description>
    <label>Dictionary Item Standard Object</label>
    <pluralLabel>Dictionary Item Standard Objects</pluralLabel>
</CustomObject>

classes/DictionaryItemObjectBatch.cls
global class DictionaryItemObjectBatch implements Database.batchable<sObject>, Database.Stateful{
    
    global final Id objectRecordTypeId = Schema.SObjectType.DictionaryItem__c.getRecordTypeInfosByName().get('Object').getRecordTypeId();
    global final String query;
    global Set<String> schemaObjects = new Set<String>();
    
    global DictionaryItemObjectBatch(){
        query='SELECT Id, APIName__c FROM DictionaryItem__c WHERE RecordTypeId =: objectRecordTypeId';
    }    
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<DictionaryItem__c> scope){
        
        List<DictionaryItem__c> objectsToUpsert = new List<DictionaryItem__c>();
        List<DictionaryItem__c> objectsToDelete = new List<DictionaryItem__c>();
        Set<String> stdObjects = new Set<String>();
        
        for (DictionaryItemStandardObject__mdt so : [SELECT APIName__c
                                                     FROM DictionaryItemStandardObject__mdt                                                    ]) {
                                                         stdObjects.add(so.APIName__c);
                                                     }
        
        Map<String, Schema.SObjectType> globalDescribe = Schema.getGlobalDescribe();
        
        List<String> objectNames = new List<String>();
        
        if (!Test.isRunningTest()) {
        	objectNames = new List<String>(globalDescribe.keySet());
        } else {
            objectNames.add('Account');
        }
        
        List<Schema.DescribeSObjectResult> objectDescribeResultList = Schema.describeSObjects(objectNames);
        
        for (Schema.DescribeSObjectResult sr : objectDescribeResultList) {
            
            if (stdObjects.contains(sr.getName()) || sr.isCustom()) {
                schemaObjects.add(sr.getName());
                objectsToUpsert.add(new DictionaryItem__c(RecordTypeId = objectRecordTypeId,
                                                          APIName__c = sr.getName(),
                                                          Label__c = sr.getLabel(),
                                                          PluralLabel__c = sr.getLabelPlural(),
                                                          KeyPrefix__c = sr.getKeyPrefix(),
                                                          Custom__c = sr.isCustom(),
                                                          MetadataIdentifier__c = 'Object:' + sr.getName()
                                                         ));
            }
            
        }
        
        upsert objectsToUpsert MetadataIdentifier__c;
        
        for (DictionaryItem__c di : scope) {
            if (!schemaObjects.contains(di.APIName__c)) objectsToDelete.add(di);
        }
        
        delete objectsToDelete;
        
    }  
    
    global void finish(Database.BatchableContext BC){

        Id batchJobId = Database.executeBatch(new DictionaryItemFieldBatch(),10);
        
    }
    
}