objects/DictionaryItem__c.object
<CustomObject>
    <fields>
        <fullName>APIName__c</fullName>
        <description>The API Name of the component</description>
        <label>API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ByteLength__c</fullName>
        <description>For variable-length fields (including binary fields), returns the maximum size of the field, in bytes</description>
        <label>Byte Length</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CalculatedFormula__c</fullName>
        <description>The formula specified for this field</description>
        <label>Calculated Formula</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CompoundFieldName__c</fullName>
        <label>Compound Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Custom__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is a custom component</description>
        <label>Custom</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Digits__c</fullName>
        <description>The maximum number of digits specified for the field</description>
        <label>Digits</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FieldType__c</fullName>
        <description>The display type of the field</description>
        <label>Field Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Auto Number</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>Currency</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Date/Time</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Formula</fullName>
                </value>
                <value>
                    <fullName>Hierarchy</fullName>
                </value>
                <value>
                    <fullName>Long Text Area</fullName>
                </value>
                <value>
                    <fullName>Lookup</fullName>
                </value>
                <value>
                    <fullName>Master-Detail</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Percent</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
                <value>
                    <fullName>Picklist (Multi-Select)</fullName>
                </value>
                <value>
                    <fullName>Rich Text Area</fullName>
                </value>
                <value>
                    <fullName>Roll-Up Summary</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Text (Encrypted)</fullName>
                </value>
                <value>
                    <fullName>Text Area</fullName>
                </value>
                <value>
                    <fullName>Time</fullName>
                </value>
                <value>
                    <fullName>URL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HelpText__c</fullName>
        <description>The content of the field-level help</description>
        <label>Help Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsCalculated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is a formula field</description>
        <label>Calculated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <description>The label of the component</description>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MetadataIdentifier__c</fullName>
        <description>The unique id used to connect this component to SFDC standard metadata</description>
        <externalId>true</externalId>
        <label>Metadata Identifier</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ParentDictionaryItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent of Dictionary Item (i.e., a Field's Parent Dictionary Item is an Object)</description>
        <label>Parent Dictionary Item</label>
        <referenceTo>DictionaryItem__c</referenceTo>
        <relationshipLabel>Dictionary Items (Parent Dictionary Item)</relationshipLabel>
        <relationshipName>DictionaryItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Precision__c</fullName>
        <description>The maximum number of digits that can be stored, including all numbers to the left and to the right of the decimal point (but excluding the decimal point character)</description>
        <label>Precision</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ReferenceTo__c</fullName>
        <description>The parent object of this field</description>
        <label>Reference To</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scale__c</fullName>
        <description>The number of digits to the right of the decimal point</description>
        <label>Scale</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <description>Data dictionary</description>
    <label>Dictionary Item</label>
    <nameField>
        <displayFormat>DI-{000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dictionary Items</pluralLabel>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Field</fullName>
        <active>true</active>
        <description>Use for Fields</description>
        <label>Field</label>
    </recordTypes>
    <recordTypes>
        <fullName>Object</fullName>
        <active>true</active>
        <description>Use for objects</description>
        <label>Object</label>
    </recordTypes>
</CustomObject>

classes/DictionaryItemFieldBatch.cls
global class DictionaryItemFieldBatch implements Database.batchable<sObject>, Database.AllowsCallouts, Database.Stateful{
    
    global final Id objectRecordTypeId = Schema.SObjectType.DictionaryItem__c.getRecordTypeInfosByName().get('Object').getRecordTypeId();
    global final Id PVRecordTypeId = Schema.SObjectType.DictionaryItem__c.getRecordTypeInfosByName().get('Picklist Value').getRecordTypeId();
    global final Id fieldRecordTypeId = Schema.SObjectType.DictionaryItem__c.getRecordTypeInfosByName().get('Field').getRecordTypeId();
    global final Id RTRecordTypeId = Schema.SObjectType.DictionaryItem__c.getRecordTypeInfosByName().get('Record Type').getRecordTypeId();    
    global final String query;
    global Set<Id> doNotDeleteIds = new Set<Id>();
    
    global DictionaryItemFieldBatch(){
        query='SELECT Id, APIName__c, MetadataIdentifier__c FROM DictionaryItem__c WHERE RecordTypeId =: objectRecordTypeId';
    }    
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
        
    global void execute(Database.BatchableContext BC, List<DictionaryItem__c> scope){
        
        Map<String,Id> objectNameMap = new Map<String,Id>();
        List<String> objectNameList = new List<String>();
        Set<Id> objectDictionaryItemIdSet = new Set<Id>();
        
        List<DictionaryItem__c> fields = new List<DictionaryItem__c>();
        List<DictionaryItem__c> pvs = new List<DictionaryItem__c>();
        List<DictionaryItem__c> RTs = new List<DictionaryItem__c>();        
        
        
        for (DictionaryItem__c s : scope) {
            objectNameMap.put(s.APIName__c, s.Id);
            objectNameList.add(s.APIName__c);
            objectDictionaryItemIdSet.add(s.Id);  
            
        }
        
        List<Schema.DescribeSObjectResult> objectDescribeResultList = Schema.describeSObjects(objectNameList);
        
        for (Schema.DescribeSObjectResult sr : objectDescribeResultList) {            
           
            
            DictionaryItem__c objectMDIRef = new DictionaryItem__c(MetadataIdentifier__c = 'Object:' + sr.getName());
            
            Map<String,Schema.RecordTypeInfo> recordTypeMap = sr.getRecordTypeInfosByName();
            for (Schema.RecordTypeInfo r : recordTypeMap.values()) {
                String RTMDI = 'Record Type:' + sr.getName() + '.' + r.getName();
                DictionaryItem__c newRT = new  DictionaryItem__c(RecordTypeId = RTRecordTypeId,
                                                                 Label__c = r.getName(),
                                                                 APIName__c = r.getDeveloperName(),
                                                                 MetadataIdentifier__c = RTMDI);
                newRT.ParentDictionaryItem__r = objectMDIRef; 
                RTs.add(newRT);
           }
            
            String objectAPIName = sr.getName(); 
            Map<String,Schema.SObjectField> fieldMap = sr.fields.getMap();
            
            for (String fieldName : fieldMap.keySet()) {
                
                Schema.SObjectField field = fieldMap.get(fieldName);
                Schema.DescribeFieldResult fd = field.getDescribe();
                
                List<String> fieldPicklistValuesList = new List<String>();
                
                List<Schema.SObjectType> refToList = fd.getReferenceTo();
                String refTo;
                if (refToList.size() == 1) refTo = refToList[0].getDescribe().getName();
                
                String fieldLabel = fieldMap.get(fieldName).getDescribe().getLabel();
                String fieldAPIName = fieldMap.get(fieldName).getDescribe().getName();
                String fielddataDisplayType;
                
                String calcFormula;
                if (fd.isCalculated()) calcFormula = fd.getCalculatedFormula();
                
                String FMDI = 'Field:' + sr.getName() + '.' + fd.getName();                
                DictionaryItem__c newField = new  DictionaryItem__c(RecordTypeId = fieldRecordTypeId,
                                                                    APIName__c = fieldAPIName,
                                                                    Label__c = fd.getLabel(),
                                                                    Custom__c = fd.isCustom(),
                                                                    HelpText__c = fd.getinlineHelpText(),
                                                                    ByteLength__c = fd.getByteLength(),
                                                                    IsCalculated__c = fd.isCalculated(),
                                                                    CalculatedFormula__c = calcFormula,
                                                                    ReferenceTo__c = refTo,
                                                                    Precision__c = fd.getPrecision(),
                                                                    Scale__c = fd.getScale(),
                                                                    CompoundFieldName__c = fd.compoundfieldname,
                                                                    MetadataIdentifier__c = FMDI,
                                                                    FieldType__c = fd.getType().name(),
                                                                    Digits__c = fd.digits
                                                                   );
                newField.ParentDictionaryItem__r = objectMDIRef;                 
                
                fields.add(newField);
                
                DictionaryItem__c fieldMDIRef = new DictionaryItem__c(MetadataIdentifier__c = FMDI);
                
                List<PicklistEntry> pickListEntryList = fd.getPicklistValues();
                
                for (PicklistEntry ple : pickListEntryList) {
                    
                    String PVMDI = 'Picklist Value:' + sr.getName() + '.' + fd.getName() + '.' + ple.getValue() + '.' + ple.getLabel();
                    Boolean active = TRUE;
                    if (!ple.isActive()) active = FALSE;
                    DictionaryItem__c newPVS = new DictionaryItem__c( RecordTypeId = PVRecordTypeId,
                                                                      Label__c = ple.getLabel(), 
                                                                      APIName__c = ple.getValue(), 
                                                                      IsActive__c = active,
                                                                      MetadataIdentifier__c = PVMDI);
                    newPVS.ParentDictionaryItem__r = fieldMDIRef;   
                    pvs.add(newPVS);
                }
                
            }
            
        }        
        
        upsert fields MetadataIdentifier__c;
        upsert pvs MetadataIdentifier__c;
        upsert RTs MetadataIdentifier__c;
        
        for (DictionaryItem__c f : fields) {
            doNotDeleteIds.add(f.Id);
        }
        
        for (DictionaryItem__c p : pvs) {
            doNotDeleteIds.add(p.Id);
        }
        
        for (DictionaryItem__c r : RTs) {
            doNotDeleteIds.add(r.Id);
        }
        
    }     
    
    global void finish(Database.BatchableContext BC){
        delete [SELECT Id FROM DictionaryItem__c WHERE (ParentDictionaryItem__c = null OR Id NOT IN :doNotDeleteIds)
                                                        AND RecordTypeId != :objectRecordTypeId];
    }
    
}