objects/DictionaryItem__c.object
<CustomObject>
    <fields>
        <fullName>APIName__c</fullName>
        <description>The API Name of the component</description>
        <label>API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Custom__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is a custom component</description>
        <label>Custom</label>
        <type>Checkbox</type>
    </fields>
    <description>Data dictionary</description>
    <label>Dictionary Item</label>
    <nameField>
        <displayFormat>DI-{000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dictionary Items</pluralLabel>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Object</fullName>
        <active>true</active>
        <description>Use for objects</description>
        <label>Object</label>
    </recordTypes>
</CustomObject>

classes/DictionaryItemBatchTest.cls
@isTest
public class DictionaryItemBatchTest {
    
    
    static testMethod void DictionaryItemBatchTest() {
        
    
        Id objectRecordTypeId = Schema.SObjectType.DictionaryItem__c.getRecordTypeInfosByName().get('Object').getRecordTypeId();
        DictionaryItem__c di = new DictionaryItem__c(APIName__c = 'Test__c', RecordTypeId = objectRecordTypeId, Custom__c = TRUE);
        insert di;
        
        Test.startTest(); 
        TestContext.testCase = 'YES';    
        Id batchJobId = Database.executeBatch(new DictionaryItemObjectBatch());
        Test.stopTest();		        
        
    }        
    
}