objects/DictionaryItem__c.object
<CustomObject>
    <fields>
        <fullName>FieldTripName__c</fullName>
        <description>Name of the FieldTrip analysis that was run to produce the "Populated On" data</description>
        <inlineHelpText>Name of the FieldTrip analysis that was run to produce the "Populated On" data</inlineHelpText>
        <label>FieldTrip Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MetadataIdentifier__c</fullName>
        <description>The unique id used to connect this component to SFDC standard metadata</description>
        <externalId>true</externalId>
        <label>Metadata Identifier</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PopulatedOnPercent__c</fullName>
        <label>Populated On (%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>PopulatedOn__c</fullName>
        <label>Populated On</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PopulationLastAnalyzed__c</fullName>
        <label>Population Last Analyzed</label>
        <type>DateTime</type>
    </fields>
    <description>Data dictionary</description>
    <label>Dictionary Item</label>
    <nameField>
        <displayFormat>DI-{000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dictionary Items</pluralLabel>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Field</fullName>
        <active>true</active>
        <description>Use for Fields</description>
        <label>Field</label>
    </recordTypes>
    <recordTypes>
        <fullName>Object</fullName>
        <active>true</active>
        <description>Use for objects</description>
        <label>Object</label>
    </recordTypes>
</CustomObject>

classes/FieldTripFieldAnalysisTriggerHandler.cls
/** 
* @author : Pratibha Potluri 
* @Created Date: 10/02/2018 
* @description : handler class for FieldTripFieldAnalysisTrigger. 
**/ 

public class FieldTripFieldAnalysisTriggerHandler{

      public static void populateStatistics(List<Field_Trip__Field_Analysis__c> lstFTFA,Map<Id,Field_Trip__Field_Analysis__c> mapRecords){
        
        // Query the Field_Trip__Field_Analysis__c records on After Insert to get Field_Trip__Object_Analysis__c field values
        Map<Id,Field_Trip__Field_Analysis__c> mapFTRecords = new  Map<Id,Field_Trip__Field_Analysis__c>(
                                                            [select id,
                                                                    name,
                                                                    Field_Trip__Object_Analysis__c,
                                                                    Field_Trip__Object_Analysis__r.Field_Trip__Object_Name__c,
                                                             		Field_Trip__Object_Analysis__r.Name,
                                                                    Field_Trip__Populated_On__c,
                                                                    Field_Trip__Populated_On_Percent__c,
                                                                    Field_Trip__Object_Analysis__r.Field_Trip__Last_Analyzed__c from Field_Trip__Field_Analysis__c where Id In:mapRecords.keySet()]);
        
        // Map to store the Field_Trip__Field_Analysis__c records with unique key
        Map<string,Field_Trip__Field_Analysis__c> mapFT = new Map<string,Field_Trip__Field_Analysis__c>();
        
        // Looping all the records we got in Map
        for(Field_Trip__Field_Analysis__c fa:mapFTRecords.values()){
            
            // framing unique Key value with Field and field trip object analysis object name and  field trip field analysis name
            string keyValue = 'Field:'+fa.Field_Trip__Object_Analysis__r.Field_Trip__Object_Name__c+'.'+fa.Name;
            keyValue = keyValue.toUpperCase();
            
            // adding to map with unique key and value
            mapFT.put(keyValue,fa);
        }
        
        
        // Querying Dictionary Item  records with MapFT keyset as in Dictionary Item MetadataIdentifier
        List<DictionaryItem__c> lstDI = [select id,
                                                MetadataIdentifier__c,
                                                PopulatedOn__c,
                                                PopulatedOnPercent__c,
                                         		FieldTripName__c,
                                                PopulationLastAnalyzed__c from DictionaryItem__c where MetadataIdentifier__c IN:mapFT.keyset() and MetadataIdentifier__c != null];
        
            
            if(!lstDI.isEmpty()){ 
                // looping all the Dictionary Items queried
                for(DictionaryItem__c DI:lstDI){
                    // checking whether metadataIdentifier is in Map as key or not
                    String MetadataIdentifierUpper = DI.MetadataIdentifier__c.toUpperCase();
                    if(mapFT.containsKey(MetadataIdentifierUpper)){ 
                                                
                        DI.PopulatedOn__c = mapFT.get(MetadataIdentifierUpper).Field_Trip__Populated_On__c;                                             
                        DI.PopulatedOnPercent__c = mapFT.get(MetadataIdentifierUpper).Field_Trip__Populated_On_Percent__c;                       
                        DI.PopulationLastAnalyzed__c = mapFT.get(MetadataIdentifierUpper).Field_Trip__Object_Analysis__r.Field_Trip__Last_Analyzed__c;
                        DI.FieldTripName__c = mapFT.get(MetadataIdentifierUpper).Field_Trip__Object_Analysis__r.Name;
                    }
                }                
                update lstDI;
           }
    }    
}