objects/DictionaryItem__c.object
<CustomObject>
    <fields>
        <fullName>FieldType__c</fullName>
        <description>The display type of the field</description>
        <label>Field Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Auto Number</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>Currency</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Date/Time</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Formula</fullName>
                </value>
                <value>
                    <fullName>Hierarchy</fullName>
                </value>
                <value>
                    <fullName>Long Text Area</fullName>
                </value>
                <value>
                    <fullName>Lookup</fullName>
                </value>
                <value>
                    <fullName>Master-Detail</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Percent</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
                <value>
                    <fullName>Picklist (Multi-Select)</fullName>
                </value>
                <value>
                    <fullName>Rich Text Area</fullName>
                </value>
                <value>
                    <fullName>Roll-Up Summary</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Text (Encrypted)</fullName>
                </value>
                <value>
                    <fullName>Text Area</fullName>
                </value>
                <value>
                    <fullName>Time</fullName>
                </value>
                <value>
                    <fullName>URL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <description>The label of the component</description>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentDictionaryItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent of Dictionary Item (i.e., a Field's Parent Dictionary Item is an Object)</description>
        <label>Parent Dictionary Item</label>
        <referenceTo>DictionaryItem__c</referenceTo>
        <relationshipLabel>Dictionary Items (Parent Dictionary Item)</relationshipLabel>
        <relationshipName>DictionaryItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>Data dictionary</description>
    <label>Dictionary Item</label>
    <nameField>
        <displayFormat>DI-{000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dictionary Items</pluralLabel>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Field</fullName>
        <active>true</active>
        <description>Use for Fields</description>
        <label>Field</label>
    </recordTypes>
    <recordTypes>
        <fullName>Object</fullName>
        <active>true</active>
        <description>Use for objects</description>
        <label>Object</label>
    </recordTypes>
    <recordTypes>
        <fullName>RecordType</fullName>
        <active>true</active>
        <description>Use for objects</description>
        <label>Record Type</label>
    </recordTypes>
</CustomObject>

classes/DictionaryItemExtension_Test.cls
@isTest
private class DictionaryItemExtension_Test{
    
    @TestSetup
    static void setup(){
        
        DictionaryItem__c DObject = new DictionaryItem__c();
        DObject.RecordtypeId = Schema.SObjectType.DictionaryItem__c.getRecordTypeInfosByName().get('Object').getRecordTypeId();
        DObject.Label__c ='Account';
        insert DObject;
        
        DictionaryItem__c DRt = new DictionaryItem__c();
        DRt.RecordtypeId = Schema.SObjectType.DictionaryItem__c.getRecordTypeInfosByName().get('Record Type').getRecordTypeId();
        DRt.Label__c ='Account';
        DRt.ParentDictionaryItem__c = DObject.Id;
        insert DRt;
        
        DictionaryItem__c DFd = new DictionaryItem__c();
        DFd.RecordtypeId = Schema.SObjectType.DictionaryItem__c.getRecordTypeInfosByName().get('Field').getRecordTypeId();
        DFd.Label__c ='Account';
        DFd.fieldType__c ='Text';
        DFd.ParentDictionaryItem__c = DObject.Id;
        insert DFd;
        
        DictionaryItem__c DFdp = new DictionaryItem__c();
        DFdp.RecordtypeId = Schema.SObjectType.DictionaryItem__c.getRecordTypeInfosByName().get('Field').getRecordTypeId();
        DFdp.Label__c ='Account';
        DFdp.fieldType__c ='Picklist';
        DFdp.ParentDictionaryItem__c = DObject.Id;
        insert DFdp;
        
        DictionaryItem__c DFdpv = new DictionaryItem__c();
        DFdpv.RecordtypeId = Schema.SObjectType.DictionaryItem__c.getRecordTypeInfosByName().get('Picklist Value').getRecordTypeId();
        DFdpv.Label__c ='Account';
        DFdpv.ParentDictionaryItem__c = DFdp.Id;
        insert DFdpv;
    }
    
    private static testMethod void objectMethod(){
        
        DictionaryItem__c DI = [select id from DictionaryItem__c where Recordtype.Name = 'Object' LIMIT 1];    
          PageReference pageRef = Page.DictionaryItemVF;
          Test.setCurrentPage(pageRef);
          System.currentPageReference().getParameters().put('Id', String.ValueOf(DI.id));
          
          ApexPages.StandardController sc = new ApexPages.StandardController(DI);
          DictionaryItemExtension DIE = new DictionaryItemExtension(sc);
          DIE.intialCheck();
          DIE.getFieldsInfoPagination();
          DIE.first();
          DIE.Last();
          DIE.Next();
          DIE.Previous();
    }
     
     private static testMethod void PLMethod(){
        
        DictionaryItem__c DI = [select id from DictionaryItem__c where Recordtype.Name = 'Field' and FieldType__c =:'Picklist' LIMIT 1];    
          PageReference pageRef = Page.DictionaryItemVF;
          Test.setCurrentPage(pageRef);
          System.currentPageReference().getParameters().put('Id', String.ValueOf(DI.id));
          
          ApexPages.StandardController sc = new ApexPages.StandardController(DI);
          DictionaryItemExtension DIE = new DictionaryItemExtension(sc);
          DIE.intialCheck();
          
    }   
    
	private static testMethod void RTMethod(){
        
        DictionaryItem__c DI = [select id from DictionaryItem__c where Recordtype.Name = 'Record Type' LIMIT 1];    
          PageReference pageRef = Page.DictionaryItemVF;
          Test.setCurrentPage(pageRef);
          System.currentPageReference().getParameters().put('Id', String.ValueOf(DI.id));
          
          ApexPages.StandardController sc = new ApexPages.StandardController(DI);
          DictionaryItemExtension DIE = new DictionaryItemExtension(sc);
          DIE.intialCheck();
          
    }   
    
	private static testMethod void FieldMethod(){
        
        DictionaryItem__c DI = [select id from DictionaryItem__c where Recordtype.Name = 'Field' LIMIT 1];    
          PageReference pageRef = Page.DictionaryItemVF;
          Test.setCurrentPage(pageRef);
          System.currentPageReference().getParameters().put('Id', String.ValueOf(DI.id));
          
          ApexPages.StandardController sc = new ApexPages.StandardController(DI);
          DictionaryItemExtension DIE = new DictionaryItemExtension(sc);
          DIE.intialCheck();
          
    }   
    
	private static testMethod void PLVMethod(){
        
        DictionaryItem__c DI = [select id from DictionaryItem__c where Recordtype.Name = 'Picklist Value' LIMIT 1];    
          PageReference pageRef = Page.DictionaryItemVF;
          Test.setCurrentPage(pageRef);
          System.currentPageReference().getParameters().put('Id', String.ValueOf(DI.id));
          
          ApexPages.StandardController sc = new ApexPages.StandardController(DI);
          DictionaryItemExtension DIE = new DictionaryItemExtension(sc);
          DIE.intialCheck();
          
    }    
    
}