objects/ExchangeOptout__c.object
<CustomObject>
    <description>This object contains the opt-outs of the contacts done through exchange.</description>
    <label>Exchange Optout</label>
    <nameField>
        <displayFormat>EO-{0000000000}</displayFormat>
        <label>ExchangeOptout Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exchange Optouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/NGAMSettings__c.object
<CustomObject>
    <fields>
        <fullName>ProfileSystemAdministrator__c</fullName>
        <description>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</description>
        <inlineHelpText>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</inlineHelpText>
        <label>Profile: System Administrator</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Holds the NGAM settings</description>
    <label>NGAM Settings</label>
</CustomObject>

objects/NGAMSettingsHierarchy__c.object
<CustomObject>
    <fields>
        <fullName>ByPassAccountValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows entity to by-pass validation rules on Account</description>
        <inlineHelpText>Allows entity to by-pass validation rules on Account</inlineHelpText>
        <label>By-Pass Account Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NGAM Settings - Hierarchy</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>UserID__c</fullName>
        <defaultValue>"Populate This Field"</defaultValue>
        <externalId>true</externalId>
        <label>UserID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ExchangeOptoutTriggerHandler_Test.cls
@isTest
private class ExchangeOptoutTriggerHandler_Test {

    static testMethod void ExchangeOptoutTriggerHandlerTesting() 
        {
        
        NGAMSettingsHierarchy__c hsettings = NGAMSettingsHierarchy__c.getOrgDefaults();
        hsettings.ByPassAccountValidationRules__c  = TRUE;
        upsert hsettings NGAMSettingsHierarchy__c.Id;

            //Profile p = [select id from profile where name='System Administrator']; 
            DataFactory.CreateNGAMCustomSettings(); 
            NGAMSettings__c ngamSettings = [select id,ProfileSystemAdministrator__c from NGAMSettings__c limit 1]; 
            string p = Util.getCustomSettingProfileId(ngamSettings.ProfileSystemAdministrator__c);
            
            User u = new User(alias = 'standt', email='SFDCadmin@ngam.natixis.com', 
                              emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
                              localesidkey='en_US', profileid = p, 
                              timezonesidkey='America/Los_Angeles', username='SFDCadmin@ngam.natixis.com',UserID__c='SFDCadmin');
        System.runAs(u) 
                {
                List<Account> myAccounts = DataFactory.createTestAccounts(1);
                insert myAccounts;  
                
                List<Contact> myContacts =  DataFactory.createTestContacts(1, myAccounts, false);
                insert myContacts;
                
                List<ExchangeOptout__c> myExchangeOptouts = DataFactory.createExchangeOptouts(10);
                insert myExchangeOptouts;
                
                delete myExchangeOptouts;
                delete myContacts;
                delete myAccounts;
                }
    
    
        }
    
}