objects/ExternalCommunitySettings__c.object
<CustomObject>
    <fields>
        <fullName>AccountPrefix__c</fullName>
        <description>Used to prefix the Account.Name for End Client contact accounts. These accounts are automatically created for community users to control sharing.</description>
        <inlineHelpText>Used to prefix the Account.Name for End Client contact accounts. These accounts are automatically created for community users to control sharing.</inlineHelpText>
        <label>AccountPrefix</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndClientCommunityAccountName__c</fullName>
        <description>The name of the Account (Firms Office) to which End Client/Interested 3rd Party community contacts will belong.</description>
        <inlineHelpText>The name of the Account (Firms Office) to which new End Client/Interested 3rd Party community contacts belong.  This should always be NGAM DISTRIBUTION, L.P., PORTAL END CLIENTS</inlineHelpText>
        <label>EndClientCommunityAccountName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndClientOwnerId__c</fullName>
        <description>Specify the owner of end client accounts and contacts (OwnerId)</description>
        <inlineHelpText>The OwnerId of End Client accounts and contacts.  This should be set to "Portal Natixis" user SFID.  It controls row-level security for viewing and editing End Client contacts/accounts through a sharing rule.</inlineHelpText>
        <label>EndClientOwnerId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PotalUserName__c</fullName>
        <description>Portal user name</description>
        <label>PotalUserName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>To the custom setting for external communities</description>
    <label>ExternalCommunitySettings</label>
</CustomObject>

objects/NGAMSettingsHierarchy__c.object
<CustomObject>
    <fields>
        <fullName>ByPassAccountValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows entity to by-pass validation rules on Account</description>
        <inlineHelpText>Allows entity to by-pass validation rules on Account</inlineHelpText>
        <label>By-Pass Account Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NGAM Settings - Hierarchy</label>
</CustomObject>

classes/ContactEndClientNewExtensionTest.cls
@isTest
public class ContactEndClientNewExtensionTest {
    
    static testMethod void ContactEndClientNewTest() 
    
    {
        NGAMSettingsHierarchy__c hsettings = NGAMSettingsHierarchy__c.getOrgDefaults();
        hsettings.ByPassAccountValidationRules__c  = TRUE;
        upsert hsettings NGAMSettingsHierarchy__c.Id;

        
        User ecu = [SELECT Id from User WHERE Username LIKE 'portalnatixis@ngam.natixis.com%' LIMIT 1];
        
        ExternalCommunitySettings__c settings = new ExternalCommunitySettings__c(name = 'EstatementCommunity',
                                                                                 EndClientCommunityAccountName__c = 'eStatementFirmName',
                                                                                 PotalUserName__c = 'portalnatixis@ngam.natixis.com',
                                                                                 AccountPrefix__c = 'EstatementCommunity',
                                                                                 EndClientOwnerId__c = ecu.Id);
        insert settings;
        
        List<Account> firms = DataFactory.createTestFirms(1);
        firms[0].Name = 'eStatementFirmName';
        insert firms;
        
        Id endClientRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('End Client').getRecordTypeId();
        Contact objContact = new Contact(FirstName = 'Test', LastName='Test', RecordTypeId = endClientRecordTypeId, Email='foo@foo.com');
        insert objContact;
        
        Test.startTest();
        Test.setCurrentPage(Page.ContactEndClientNew);
        ApexPages.currentPage().getParameters().put('FirstName', 'EC First Name');
        ApexPages.currentPage().getParameters().put('LastName', 'EC Last Name');
        ApexPages.StandardController stdContact = new ApexPages.StandardController(objContact);
        ContactEndClientNewExtension controller = new ContactEndClientNewExtension(stdContact);
        controller.SaveEndClient();
        PageReference n = controller.nextPage();        
        Test.stopTest();    
    }    
    
    
}