objects/ExternalCommunitySettings__c.object
<CustomObject>
    <fields>
        <fullName>CommunityInternalSender__c</fullName>
        <description>To addresses for Batch jobs</description>
        <inlineHelpText>Determines the email address that batch completion emails should go to.  This should be dat@ngam.natixis.com unless you are testing.</inlineHelpText>
        <label>CommunityInternalSender</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CommunitySenderDisplayName__c</fullName>
        <description>CommunitySenderDisplayName for emails.  Necessary for sending the notification that new statements have been posted.</description>
        <inlineHelpText>Indicates the email from name on the notification to FA's that new statements have been posted.  This should always be Portal Solutions unless branding changes.</inlineHelpText>
        <label>CommunitySenderDisplayName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CommunitySenderEmail__c</fullName>
        <description>Email for sending the comunity email</description>
        <inlineHelpText>Indicates the email from address on the notification to FA's that new statements have been posted. This should always be Portal Solutions unless branding changes</inlineHelpText>
        <label>CommunitySenderEmail</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndClientCommunityAccountName__c</fullName>
        <description>The name of the Account (Firms Office) to which End Client/Interested 3rd Party community contacts will belong.</description>
        <inlineHelpText>The name of the Account (Firms Office) to which new End Client/Interested 3rd Party community contacts belong.  This should always be NGAM DISTRIBUTION, L.P., PORTAL END CLIENTS</inlineHelpText>
        <label>EndClientCommunityAccountName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExternalEmailTemplate__c</fullName>
        <description>Email's template developer name use for sending the emails to EndClient</description>
        <inlineHelpText>The email template used for notifying community users of new statements.</inlineHelpText>
        <label>ExternalEmailTemplateDevName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProfileForFAUser__c</fullName>
        <description>Profile name for FA</description>
        <inlineHelpText>Profile that is assigned to Financial Advisor contact user records during setup of Financial Account Contact (type = Financial Advisor).</inlineHelpText>
        <label>ProfileForFAUser</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TestUserEmail__c</fullName>
        <description>Use Test email to create user</description>
        <inlineHelpText>If UseTestEmail is set to 'Y', this is the "to" email that will be used in the place of all community user email addresses.</inlineHelpText>
        <label>TestUserEmail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>To the custom setting for external communities</description>
    <label>ExternalCommunitySettings</label>
</CustomObject>

classes/CommunitiesEmailHelper_Test.cls
@isTest
private class CommunitiesEmailHelper_Test {
    
    
    @testSetup static void SetupTest() {        
        DataFactory.insertEstatementCommunityCustomSettings();
        ExternalCommunitySettings__c myCustomSetting = ExternalCommunitySettings__c.getValues('EstatementCommunity');
    }
    
    static testMethod void sendEmailTesting() {        
        
        ExternalCommunitySettings__c myCustomSetting = ExternalCommunitySettings__c.getValues('EstatementCommunity');
        string EStatementFirmName = myCustomSetting.EndClientCommunityAccountName__c;
        String EmailSenderAddress = myCustomSetting.CommunitySenderEmail__c;
        String ExternalEmailTemplateDevName = myCustomSetting.ExternalEmailTemplate__c;  
        String CommunityInternalSender = myCustomSetting.CommunityInternalSender__c;
        String TestUserEmail = myCustomSetting.TestUserEmail__c;
        String ProfileForFAUser = myCustomSetting.ProfileForFAUser__c;
        String CommunitySenderDisplayName = myCustomSetting.CommunitySenderDisplayName__c;
        
        Id emailTemplateId =  [select id, name from EmailTemplate where developername = :ExternalEmailTemplateDevName].id;
        Map<Id,Profile> usermap = new Map<id,profile>([SELECT Id,UserLicenseId FROM Profile where name =:ProfileForFAUser]);
        
        List<user> users = [select id,Email from user where profileId in:usermap.Keyset() LIMIT 5];    
        Test.startTest();
        for (User  u : users)
        {
            List<String> ToAddress = new List<String>(); ToAddress.add(u.Email);
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            email.setToAddresses(ToAddress);   
            email.setCcAddresses(ToAddress);
            email.setTargetObjectId(u.Id);    
            email.setTemplateId(emailTemplateId);                   
            email.setReplyTo(EmailSenderAddress);
            email.setSenderDisplayName(CommunitySenderDisplayName);   
            email.setSaveAsActivity(false);      // save email as activity on the targetObjId (i.e. Contact). Note activity can't be saved on Users                             
            CommunitiesEmailHelper.sendTemplatedEmail(ToAddress, ToAddress, 
                                                      ExternalEmailTemplateDevName,
                                                      u.Id, u.Id, EmailSenderAddress, 
                                                      CommunitySenderDisplayName, 'Statement Available');
            
            CommunitiesEmailHelper.sendEmail(ToAddress, ToAddress,
                                             EmailSenderAddress , CommunitySenderDisplayName,
                                             'Statement Available','Statement Available', true);
            
            CommunitiesEmailHelper.sendEmail(ToAddress, ToAddress,
                                             EmailSenderAddress , CommunitySenderDisplayName,
                                             'Statement Available','Statement Available', false);
            
            
        }
        
        Test.stopTest();
        
    }
    
    
    static testMethod void CommunitiesEmailHelperTesting() {        
        
        ExternalCommunitySettings__c myCustomSetting = ExternalCommunitySettings__c.getValues('EstatementCommunity');
        string EStatementFirmName = myCustomSetting.EndClientCommunityAccountName__c;
        String EmailSenderAddress = myCustomSetting.CommunitySenderEmail__c;
        String ExternalEmailTemplateDevName = myCustomSetting.ExternalEmailTemplate__c;  
        String CommunityInternalSender = myCustomSetting.CommunityInternalSender__c;
        String TestUserEmail = myCustomSetting.TestUserEmail__c;
        String ProfileForFAUser = myCustomSetting.ProfileForFAUser__c;
        String CommunitySenderDisplayName = myCustomSetting.CommunitySenderDisplayName__c;
        
        Id emailTemplateId =  [select id, name from EmailTemplate where developername = :ExternalEmailTemplateDevName].id;
        Map<Id,Profile> usermap = new Map<id,profile>([SELECT Id,UserLicenseId FROM Profile where name =:ProfileForFAUser]);
        
        List<user> users = [select id,Email from user where profileId in:usermap.Keyset() LIMIT 50];    
        Test.startTest();
        List<Messaging.SingleEmailMessage> emailMessageList = new List<Messaging.SingleEmailMessage>();
        for (User  u : users)
        {
            List<String> ToAddress = new List<String>();
            ToAddress.add(u.Email);
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            email.setToAddresses(ToAddress);                   
            email.setTargetObjectId(u.Id);    
            email.setTemplateId(emailTemplateId);                   
            email.setReplyTo(EmailSenderAddress);
            email.setSenderDisplayName(CommunitySenderDisplayName);   
            email.setSaveAsActivity(false);      // save email as activity on the targetObjId (i.e. Contact). Note activity can't be saved on Users                  
            emailMessageList.Add(email);
        }
        Messaging.SendEmailResult[] allornone =  CommunitiesEmailHelper.sendTemplatedEmailByList(emailMessageList,true);
        // Add invalid email address
        List<String> ToAddress = new List<String>();
        ToAddress.add('test.Test.com=test');
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        email.setToAddresses(ToAddress);                             
        email.setTemplateId(emailTemplateId);                   
        email.setReplyTo(EmailSenderAddress);
        email.setSenderDisplayName(CommunitySenderDisplayName);   
        email.setSaveAsActivity(false);      // save email as activity on the targetObjId (i.e. Contact). Note activity can't be saved on Users                  
        emailMessageList.Add(email);
        Messaging.SendEmailResult[] results =  CommunitiesEmailHelper.sendTemplatedEmailByList(emailMessageList,false);
        if (results !=  null && results.size() > 0) {
            for (Messaging.SendEmailResult  r : results)
            { 
                if(!r.isSuccess())
                {
                    Messaging.SendEmailError[] errArr = r.getErrors();                      
                    for(Messaging.SendEmailError er :errArr)
                    {
                        System.Debug('error - ' + er.getTargetObjectId()+' ' +  er.getMessage()); 
                    }
                }
            }                           
        }      
        Test.stopTest();
        
    }
}