objects/ExternalCommunitySettings__c.object
<CustomObject>
    <fields>
        <fullName>ProfileForFAUser__c</fullName>
        <description>Profile name for FA</description>
        <inlineHelpText>Profile that is assigned to Financial Advisor contact user records during setup of Financial Account Contact (type = Financial Advisor).</inlineHelpText>
        <label>ProfileForFAUser</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>To the custom setting for external communities</description>
    <label>ExternalCommunitySettings</label>
</CustomObject>

objects/FinancialAccount__c.object
<CustomObject>
    <description>Used in community to display Financial Account data to community users.  This object's data is sourced from Data Central and maintained via integration.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/FinancialAccountContact__c.object
<CustomObject>
    <description>Tracks contacts associated with a Financial Account.  Dictates which contacts (community users) can see a particular Financial Account in the community.</description>
    <label>Financial Account Contact</label>
    <nameField>
        <displayFormat>FAC-{000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/FinancialAccountFile__c.object
<CustomObject>
    <fields>
        <fullName>DoNotDisplayReason__c</fullName>
        <description>Reason this file should not be displayed to community members</description>
        <inlineHelpText>Reason this file should not be displayed to community members</inlineHelpText>
        <label>Do Not Display Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DoNotDisplayinCommunity__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, this file will not be viewable by community members</description>
        <inlineHelpText>If checked, this file will not be viewable by community members</inlineHelpText>
        <label>Do Not Display in Community</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DocumentDate__c</fullName>
        <description>The effective date of the document.  For example, the Document Date would be 3/31 for a Q2 document even though the file record might have a created date of 4/15.</description>
        <inlineHelpText>The effective date of the document.  For example, the Document Date would be 3/31 for a Q2 document even though the Financial Account File record might have a created date of 4/15.</inlineHelpText>
        <label>Document Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DocumentType__c</fullName>
        <description>The type of document/file that this record represents.</description>
        <inlineHelpText>The type of document/file that this record represents</inlineHelpText>
        <label>Document Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Quarterly Performance Report</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OriginalFileName__c</fullName>
        <description>Name of the original file as stored on the shared directory.</description>
        <inlineHelpText>Name of the original file as stored on the shared directory.</inlineHelpText>
        <label>Original File Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FinancialAccount__c</fullName>
        <description>The Financial Account to which this file belongs</description>
        <inlineHelpText>The Financial Account to which this file belongs</inlineHelpText>
        <label>Financial Account</label>
        <referenceTo>FinancialAccount__c</referenceTo>
        <relationshipLabel>Financial Account Files</relationshipLabel>
        <relationshipName>FinancialAccountFiles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <description>Used as a "holding object" for files related to Financial Account.  Files are posted to this record rather than directly to the Financial Account record so that we can carry data about the file in the system.  Note, at current development time it was not possible to use API calls to write data about the file to Content object.</description>
    <label>Financial Account File</label>
    <nameField>
        <displayFormat>FAF-{0000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Files</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/NGAMSettingsHierarchy__c.object
<CustomObject>
    <fields>
        <fullName>ByPassAccountValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows entity to by-pass validation rules on Account</description>
        <inlineHelpText>Allows entity to by-pass validation rules on Account</inlineHelpText>
        <label>By-Pass Account Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NGAM Settings - Hierarchy</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>CommunityStatus__c</fullName>
        <description>For community users who have been inactivated, this field contains the reason for inactivation.  If the user is active, it contains "Active".</description>
        <inlineHelpText>For community users who have been inactivated, this field contains the reason for inactivation.  If the user is active, it contains "Active".</inlineHelpText>
        <label>Community Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserID__c</fullName>
        <defaultValue>"Populate This Field"</defaultValue>
        <externalId>true</externalId>
        <label>UserID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CommunitiesNotifyNewStatementsBatch_Test.cls
@isTest 
private class CommunitiesNotifyNewStatementsBatch_Test {
    
     @testSetup static void SetupTest() {      
     
        NGAMSettingsHierarchy__c hsettings = NGAMSettingsHierarchy__c.getOrgDefaults();
        hsettings.ByPassAccountValidationRules__c  = TRUE;
        upsert hsettings NGAMSettingsHierarchy__c.Id;
  
        DataFactory.insertEstatementCommunityCustomSettings();
        ExternalCommunitySettings__c myCustomSetting = ExternalCommunitySettings__c.getValues('EstatementCommunity');
        String ProfileForFAUser = myCustomSetting.ProfileForFAUser__c;
         
          DataFactory.insertEstatementCommunityCustomSettings();
        List<Account> myAccounts = DataFactory.createTestAccounts(3);
        insert myAccounts;
        
        Id ECRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('End Client').getRecordTypeId();
        
        List<Contact> myContacts = DataFactory.createTestContacts(3, myAccounts, false);
        List<Contact> contacts = new List<Contact>();
        List<Contact> contactsWithFAC = new List<Contact>();
        
        myContacts[0].RecordTypeId = ECRecordTypeId;
        myContacts[0].LastName = 'Test 1';
        
        myContacts[1].RecordTypeId = ECRecordTypeId;
        myContacts[1].LastName = 'Test 2';    
        
        myContacts[2].RecordTypeId = ECRecordTypeId;
        myContacts[2].LastName = 'Test 3';
        
        insert myContacts;
        system.debug('myContacts 1 ID: ' + myContacts[1].Id);
        
        contactsWithFAC.add(myContacts[0]);        
        contactsWithFAC.add(myContacts[1]);
        
        List<FinancialAccount__c> faList =  DataFactory.createFinancialAccounts(1) ;
        insert faList;
        
        List<FinancialAccountContact__c> facList = DataFactory.createFinancialAccountContacts(faList,contactsWithFAC);
        insert facList;
        Profile FAProfile = [SELECT Name, Id FROM Profile WHERE name=:ProfileForFAUser LIMIT 1];  
     
        system.debug('facList: ' + facList);
         
           User nCU = new User(contactId=myContacts[0].Id, 
                                                                username='username@test.com', 
                                                                IsActive=TRUE,
                                                                firstname=myContacts[0].FirstName,
                                                                lastname=myContacts[0].LastName, 
                                                                email= myContacts[0].Email,
                                                                communityNickname = myContacts[0].LastName + '_12345',
                                                                alias = 'test123', 
                                                                UserID__c  = 'test123', 
                                                                profileid = FAProfile.Id, 
                                                                emailencodingkey='UTF-8',
                                                                languagelocalekey='en_US', 
                                                                localesidkey='en_US', 
                                                                timezonesidkey='America/Los_Angeles',
                                                                CommunityStatus__c = 'Active');  
         insert nCU;
         
                
         List<FinancialAccountFile__c>  fafList = DataFactory.createFinancialAccountFiles( 5,faList                                                                                    );
         insert fafList;
    }
    
    
    static testMethod void CommunitiesNotifyNewStatementsBatchTesting() {        
       
            List<FinancialAccountFile__c>  fafList = [SELECT Id, IsDeleted, Name, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, FinancialAccount__c, DoNotDisplayReason__c, DoNotDisplayinCommunity__c, DocumentDate__c, DocumentType__c, OriginalFileName__c FROM FinancialAccountFile__c where OriginalFileName__c like 'Test %' ];                          
            Test.startTest(); 
            System.Debug(' ########## -Test Started ');           
            CommunitiesNotifyNewStatementsBatch usersBtach = new CommunitiesNotifyNewStatementsBatch();           
            ID tracid = database.executeBatch(usersBtach,2000); 
            System.Debug(' ########## -Test Ended ');
            Test.stopTest();
             
    }
    
     
    
    
    
   }