objects/ExternalCommunitySettings__c.object
<CustomObject>
    <fields>
        <fullName>TestUserEmail__c</fullName>
        <description>Use Test email to create user</description>
        <inlineHelpText>If UseTestEmail is set to 'Y', this is the "to" email that will be used in the place of all community user email addresses.</inlineHelpText>
        <label>TestUserEmail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UseMPANamedCredential__c</fullName>
        <description>UseMPANamedCredential  , use the url from MPA or MPA_TEST based on the value from this field</description>
        <label>UseMPANamedCredential</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserNameFormat__c</fullName>
        <description>UserNameFormat for user record</description>
        <label>UserNameFormat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>To the custom setting for external communities</description>
    <label>ExternalCommunitySettings</label>
</CustomObject>

objects/FinancialAccount__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <description>Integration: NTXS_CUST_ACCOUNTS.Account_Id</description>
        <externalId>true</externalId>
        <inlineHelpText>Id of the Financial Account in Data Central. DEPRECATED will be removed in Version 8.0.</inlineHelpText>
        <label>Account Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RSAAccount__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, indicates that this Financial Account is an RSA account.  Checking this box will affect how the Financial Account appears in the community.</description>
        <inlineHelpText>If checked, indicates that this Financial Account is an RSA account.  Checking this box will affect how the Financial Account appears in the community.</inlineHelpText>
        <label>RSA Account</label>
        <type>Checkbox</type>
    </fields>
    <description>Used in community to display Financial Account data to community users.  This object's data is sourced from Data Central and maintained via integration.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/NGAMSettings__c.object
<CustomObject>
    <fields>
        <fullName>ProfileSystemAdministrator__c</fullName>
        <description>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</description>
        <inlineHelpText>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</inlineHelpText>
        <label>Profile: System Administrator</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Holds the NGAM settings</description>
    <label>NGAM Settings</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>UserID__c</fullName>
        <defaultValue>"Populate This Field"</defaultValue>
        <externalId>true</externalId>
        <label>UserID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/FAGetAccountWSCCallout_Test.cls
@isTest 
public class FAGetAccountWSCCallout_Test {
    
    static testMethod void FAGetAccountWSCCalloutTesting() {
        
       // Profile p = [select id from profile where name='System Administrator'];
        DataFactory.CreateNGAMCustomSettings(); 
        NGAMSettings__c ngamSettings = [select id,ProfileSystemAdministrator__c from NGAMSettings__c limit 1]; 
        string p = Util.getCustomSettingProfileId(ngamSettings.ProfileSystemAdministrator__c);  
        
        ExternalCommunitySettings__c ECS = new ExternalCommunitySettings__c(); 
        ECS.Name = 'EstatementCommunity'; 
        ECS.UseMPANamedCredential__c = 'testugng'; 
        ECS.UserNameFormat__c = 'TEstcom'; 
        ECS.TestUserEmail__c = 'TEst@gmail.com'; 
        insert ECS; 
        
        User u2 = new User(alias = 'standt', email='SFDCadmin@ngam.natixis.com', 
                           emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
                           localesidkey='en_US', profileid = p, 
                           timezonesidkey='America/Los_Angeles', username='SFDCadmin@ngam.natixis.com',UserID__c='SFDCadmin');
        
        System.runAs(u2) 
        {
            FinancialAccount__c testAcc =   new FinancialAccount__c(Name='Test Name',AccountID__c=123);  
            testAcc.RSAAccount__c = true;
            insert testAcc;
            // Set mock callout class 
            Test.setMock(HttpCalloutMock.class, new FAGetAccountWSCCallout_Mock());
            Test.startTest();
            // Call method to test.
            // This causes a fake response to be sent
            // from the class that implements HttpCalloutMock. 
            String Search = '';
            String response = FinancialAccountGetAccountWSCCallout.getDataSync(Search);
            // String expectedValue = '{"accountId":26,"accountNumber":"32000380","accountName":"BSM32000380","accountTitle":"ELIZABETH GROSSMAN TRUST","accountType":"TRUST","sponsor":"JP Morgan","program":"Stratis","manager":"AEW","modelName":"AEWREI","modelDescription":"AEW REIT","inceptionValue":140028,"inceptionDate":null,"terminationDate":null,"terminationValue":0,"firstTradeDate":null,"firstTradeValue":140028,"lifeCycleStep":"Active","faName":"PHYLLIS TABACHNICK","faEmail":null}';
            String expectedValue = '[{"accountId":26,"accountNumber":"32000380","accountName":"BSM32000380","accountTitle":"ELIZABETH GROSSMAN TRUST","accountType":"TRUST","sponsor":"JP Morgan","program":"Stratis","manager":"AEW","modelName":"AEWREI","modelDescription":"AEW REIT","inceptionValue":140028,"inceptionDate":1136246400000,"terminationDate":4386355200000,"terminationValue":0,"firstTradeDate":1136419200000,"firstTradeValue":140028,"lifeCycleStep":"Active","faName":"PHYLLIS TABACHNICK","faEmail":null}]';
            
            List<FAAccountDetailResponse> obj = FAAccountDetailResponse.parse(expectedValue);
            System.assertEquals(response, expectedValue);
     
            // set the test's page to your VF page (or pass in a PageReference)
            Test.setCurrentPage(Page.FinancialAccountPage);
            
            ApexPages.currentPage().getParameters().put('id', testAcc.id);
            
            
            FinancialAccountNewController controller = new FinancialAccountNewController(new ApexPages.StandardController(testAcc));
            Continuation conti = (Continuation)controller.getData();
            // Verify that the continuation has the proper requests
            Map<String, HttpRequest> requests = conti.getRequests();
            system.assert(requests.size() == 1);
            system.assert(requests.get(controller.requestLabel) != null);
            
            HttpResponse response1 = new HttpResponse();
            response1.setBody(FAAccountDetailResponse_Test.json);  
            // Set the fake response for the continuation    
            Test.setContinuationResponse(controller.requestLabel, response1);
            // Invoke callback method
            Object result = Test.invokeContinuationMethod(controller, conti);
            // result is the return value of the callback
            System.assertEquals(null, result);
            
            FinancialAccountGetAccountWSCCallout.getData(null,'test',0,'test');
            
            Test.stopTest();
        }
    }
    
}