objects/ExternalCommunitySettings__c.object
<CustomObject>
    <fields>
        <fullName>UseMPANamedCredential__c</fullName>
        <description>UseMPANamedCredential  , use the url from MPA or MPA_TEST based on the value from this field</description>
        <label>UseMPANamedCredential</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>To the custom setting for external communities</description>
    <label>ExternalCommunitySettings</label>
</CustomObject>

objects/FinancialAccount__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <description>Integration: NTXS_CUST_ACCOUNTS.Account_Id</description>
        <externalId>true</externalId>
        <inlineHelpText>Id of the Financial Account in Data Central. DEPRECATED will be removed in Version 8.0.</inlineHelpText>
        <label>Account Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>AccountNameEncrypted__c</fullName>
        <description>Unique Vestmark Account name</description>
        <inlineHelpText>Unique Vestmark Account name</inlineHelpText>
        <label>Account Name</label>
        <length>30</length>
        <maskChar>X</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>RSAAccount__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, indicates that this Financial Account is an RSA account.  Checking this box will affect how the Financial Account appears in the community.</description>
        <inlineHelpText>If checked, indicates that this Financial Account is an RSA account.  Checking this box will affect how the Financial Account appears in the community.</inlineHelpText>
        <label>RSA Account</label>
        <type>Checkbox</type>
    </fields>
    <description>Used in community to display Financial Account data to community users.  This object's data is sourced from Data Central and maintained via integration.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/NGAMSettings__c.object
<CustomObject>
    <fields>
        <fullName>ProfileSystemAdministrator__c</fullName>
        <description>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</description>
        <inlineHelpText>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</inlineHelpText>
        <label>Profile: System Administrator</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Holds the NGAM settings</description>
    <label>NGAM Settings</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ActivityZoneId__c</fullName>
        <description>Used To Tag the Activities and Opportunities created by the user.</description>
        <inlineHelpText>READ ONLY FIELD : This Will be populated by the UserTerritory__c assignment when the Territory Assignment is tagged as an Activity Territory. Please never update this field directly. Instead Delete/Insert the relevant UserTerritory__c record.</inlineHelpText>
        <label>Activity Zone Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryChannelId__c</fullName>
        <label>Primary Channel Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimaryChannel__c</fullName>
        <label>Primary Channel</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserID__c</fullName>
        <defaultValue>"Populate This Field"</defaultValue>
        <externalId>true</externalId>
        <label>UserID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ZoneID__c</fullName>
        <externalId>true</externalId>
        <label>Zone ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Zone__c.object
<CustomObject>
    <fields>
        <fullName>Zone__c</fullName>
        <externalId>true</externalId>
        <label>Zone</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FinancialAccountNewController_Test.cls
@isTest 
public class FinancialAccountNewController_Test {
    
    static testMethod void FinancialAccountNewControllerTesting() {
        
        ExternalCommunitySettings__c ECS = new ExternalCommunitySettings__c(); 
        ECS.Name = 'EstatementCommunity'; 
        ECS.UseMPANamedCredential__c = 'testugng'; 
        insert ECS; 
        
        //Profile p = [select id from profile where name='System Administrator'];
        DataFactory.CreateNGAMCustomSettings(); 
        NGAMSettings__c ngamSettings = [select id,ProfileSystemAdministrator__c from NGAMSettings__c limit 1]; 
        string p = Util.getCustomSettingProfileId(ngamSettings.ProfileSystemAdministrator__c);
        
        Zone__c z=new Zone__c(Name ='Test Zone', Zone__c=12);
        insert z;
        Zone__c myZOne = [select id from zone__c limit 1][0];  
        User u2 = new User(alias = 'standt', 
                           email='SFDCadmin@ngam.natixis.com', 
                           emailencodingkey='UTF-8', 
                           lastname='Testing', 
                           languagelocalekey='en_US', 
                           localesidkey='en_US', 
                           profileid = p, 
                           timezonesidkey='America/Los_Angeles', 
                           username='SFDCadmin@ngam.natixis.com',
                           UserID__c='SFDCadmin',
                           PrimaryChannelId__c='a1EF00000005Ws3MAE',
                           PrimaryChannel__c='WIREHOUSE',
                           ZoneId__c = myZOne.id,
                           ActivityZoneId__c = myZOne.id);
        
        System.runAs(u2) {           
            FinancialAccount__c testAcc =   new FinancialAccount__c(Name='Test Name',AccountID__c=123);  
            testAcc.RSAAccount__c = false;
            testAcc.AccountNameEncrypted__c ='abc';
            insert testAcc;
                                   
            //start the test execution context
            Test.startTest();
            FinancialAccountNewController controller = new FinancialAccountNewController(new ApexPages.StandardController(testAcc));
            ApexPages.currentPage().getParameters().put('id', testAcc.id);
            Test.setMock(HttpCalloutMock.class, new FAGetAccountWSCCallout_Mock());
            String Search = '';
            controller.getDataSync();
            //String expectedValue = '[{"accountId":26,"accountNumber":"32000380","accountName":"BSM32000380","accountTitle":"ELIZABETH GROSSMAN TRUST","accountType":"TRUST","sponsor":"JP Morgan","program":"Stratis","manager":"AEW","modelName":"AEWREI","modelDescription":"AEW REIT","inceptionValue":140028,"inceptionDate":1136246400000,"terminationDate":4386355200000,"terminationValue":0,"firstTradeDate":1136419200000,"firstTradeValue":140028,"lifeCycleStep":"Active","faName":"PHYLLIS TABACHNICK","faEmail":null}]';
            String expectedValue = '[{"accountId":26,"accountNumber":"32000380","accountName":"BSM32000380","accountTitle":"ELIZABETH GROSSMAN TRUST","accountType":"TRUST","sponsor":"JP Morgan","program":"Stratis","manager":"AEW","modelName":"AEWREI","modelDescription":"AEW REIT","inceptionValue":140028,"inceptionDate":1136246400000,"terminationDate":4386355200000,"terminationValue":0,"firstTradeDate":1136419200000,"firstTradeValue":140028,"lifeCycleStep":"Active","faName":"PHYLLIS TABACHNICK","faEmail":null}]';
            
            List<FAAccountDetailResponse> obj = FAAccountDetailResponse.parse(expectedValue);     
            //System.assertEquals(response1, expectedValue);
            
            // set the test's page to your VF page (or pass in a PageReference)
            Test.setCurrentPage(Page.FinancialAccountPage);
                                                
            Continuation conti = (Continuation)controller.getData();
            // Verify that the continuation has the proper requests
            Map<String, HttpRequest> requests = conti.getRequests();
            system.assert(requests.size() == 1);
            system.assert(requests.get(controller.requestLabel) != null);
            
            HttpResponse response = new HttpResponse();
            response.setBody(FAAccountDetailResponse_Test.json);  
            // Set the fake response for the continuation    
            Test.setContinuationResponse(controller.requestLabel, response);
            // Invoke callback method
            Object result = Test.invokeContinuationMethod(controller, conti);
            // result is the return value of the callback
            System.assertEquals(null, result);
            List<SelectOption> l = controller.responseRecords;
            controller.save();
            controller.Cancel();
                        
            Test.stopTest();    
        }  
    }    
        
}