objects/ExternalCommunitySettings__c.object
<CustomObject>
    <fields>
        <fullName>EndClientCommunityAccountName__c</fullName>
        <description>The name of the Account (Firms Office) to which End Client/Interested 3rd Party community contacts will belong.</description>
        <inlineHelpText>The name of the Account (Firms Office) to which new End Client/Interested 3rd Party community contacts belong.  This should always be NGAM DISTRIBUTION, L.P., PORTAL END CLIENTS</inlineHelpText>
        <label>EndClientCommunityAccountName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndClientOwnerId__c</fullName>
        <description>Specify the owner of end client accounts and contacts (OwnerId)</description>
        <inlineHelpText>The OwnerId of End Client accounts and contacts.  This should be set to "Portal Natixis" user SFID.  It controls row-level security for viewing and editing End Client contacts/accounts through a sharing rule.</inlineHelpText>
        <label>EndClientOwnerId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InactivateDaysForUserLogin__c</fullName>
        <defaultValue>180</defaultValue>
        <description>Inactivate the users after x numbers of days</description>
        <inlineHelpText>Users that have not logged in after this number of days are inactivated in a nightly batch job.</inlineHelpText>
        <label>InactivateDaysForUserLogin</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PemissionSetForEndClient__c</fullName>
        <description>Permission set for end user, Comma delimited string wth permission set's api names</description>
        <inlineHelpText>Permission Set that is assigned to End Client contact user records during setup of Financial Account Contact (type = End Client).</inlineHelpText>
        <label>PemissionSetForEndClient</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PermissionSetsForFAUser__c</fullName>
        <description>Permission set for FA user</description>
        <inlineHelpText>Permission Set that is assigned to Financial Advisor contact user records during setup of Financial Account Contact (type = Financial Advisor).</inlineHelpText>
        <label>PermissionSetsForFAUser</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PotalUserName__c</fullName>
        <description>Portal user name</description>
        <label>PotalUserName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProfileForEndClient__c</fullName>
        <description>profile for end client or 3 party</description>
        <inlineHelpText>Profile that is assigned to End Client contact user records during setup of Financial Account Contact (type = End Client).</inlineHelpText>
        <label>ProfileForEndClient</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProfileForFAUser__c</fullName>
        <description>Profile name for FA</description>
        <inlineHelpText>Profile that is assigned to Financial Advisor contact user records during setup of Financial Account Contact (type = Financial Advisor).</inlineHelpText>
        <label>ProfileForFAUser</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>To the custom setting for external communities</description>
    <label>ExternalCommunitySettings</label>
</CustomObject>

objects/FinancialAccount__c.object
<CustomObject>
    <description>Used in community to display Financial Account data to community users.  This object's data is sourced from Data Central and maintained via integration.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/FinancialAccountContact__c.object
<CustomObject>
    <description>Tracks contacts associated with a Financial Account.  Dictates which contacts (community users) can see a particular Financial Account in the community.</description>
    <label>Financial Account Contact</label>
    <nameField>
        <displayFormat>FAC-{000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/NGAMSettingsHierarchy__c.object
<CustomObject>
    <fields>
        <fullName>ByPassAccountValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows entity to by-pass validation rules on Account</description>
        <inlineHelpText>Allows entity to by-pass validation rules on Account</inlineHelpText>
        <label>By-Pass Account Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NGAM Settings - Hierarchy</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>CommunityStatus__c</fullName>
        <description>For community users who have been inactivated, this field contains the reason for inactivation.  If the user is active, it contains "Active".</description>
        <inlineHelpText>For community users who have been inactivated, this field contains the reason for inactivation.  If the user is active, it contains "Active".</inlineHelpText>
        <label>Community Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserID__c</fullName>
        <defaultValue>"Populate This Field"</defaultValue>
        <externalId>true</externalId>
        <label>UserID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/CommunitiesReactivateUserBatch_Test.cls
@isTest
public class CommunitiesReactivateUserBatch_Test {
    
    @testSetup static void SetupTest() {
    
        NGAMSettingsHierarchy__c hsettings = NGAMSettingsHierarchy__c.getOrgDefaults();
        hsettings.ByPassAccountValidationRules__c  = TRUE;
        upsert hsettings NGAMSettingsHierarchy__c.Id;

    
        DataFactory.CreateNGAMCustomSettings(); 
        DataFactory.insertEstatementCommunityCustomSettings();
        ExternalCommunitySettings__c myCustomSetting = ExternalCommunitySettings__c.getValues('EstatementCommunity');
        string EndClientOwnerId = myCustomSetting.EndClientOwnerId__c;
        
        List<Account> myAccounts = DataFactory.createTestAccounts(3);
        for (Account a : myAccounts)
        {
            a.OwnerId = EndClientOwnerId;
        }
        insert myAccounts;
        
        Id ECRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('End Client').getRecordTypeId();
        
        List<Contact> myContacts = DataFactory.createTestContacts(3, myAccounts, false);
        List<Contact> contacts = new List<Contact>();
        List<Contact> contactsWithFAC = new List<Contact>();
        
        myContacts[0].RecordTypeId = ECRecordTypeId;
        myContacts[0].LastName = 'Test for Reactivate';
        
        myContacts[1].RecordTypeId = ECRecordTypeId;
        myContacts[1].LastName = 'Test for remain InActive';    

        myContacts[2].RecordTypeId = ECRecordTypeId;
        myContacts[2].LastName = 'Test for Activate';    
        
        insert myContacts;
        system.debug('myContacts 1 ID: ' + myContacts[1].Id);
        
        contactsWithFAC.add(myContacts[0]); 
        contactsWithFAC.add(myContacts[2]); 
        
        List<FinancialAccount__c> faList =  DataFactory.createFinancialAccounts(1) ;
        insert faList;
        
        List<FinancialAccountContact__c> facList = DataFactory.createFinancialAccountContacts(faList,contactsWithFAC);
        insert facList;
        system.debug('facList: ' + facList);
        
    }
    
    
    static testMethod void CommunitiesReactivateUserBatch_Test() {
        
        ExternalCommunitySettings__c myCustomSetting = ExternalCommunitySettings__c.getValues('EstatementCommunity');
        string EStatementFirmName = myCustomSetting.EndClientCommunityAccountName__c;
        string PortalUserName = myCustomSetting.PotalUserName__c;
        string PermissionSetForEndClient =   myCustomSetting.PemissionSetForEndClient__c;
        String ProfileForEndClient = myCustomSetting.ProfileForEndClient__c;
        string ProfileForFAUser =  myCustomSetting.ProfileForFAUser__c;
        String PermissionSetsForFAUser = myCustomSetting.PermissionSetsForFAUser__c;
        Integer InactivateDaysForUserLogin = (Integer)myCustomSetting.InactivateDaysForUserLogin__c;
        Map<String,Id> profPermSetIdMap = new Map<String,Id>();
        PermissionSet FAPS = [SELECT Name, Id FROM PermissionSet WHERE name=:PermissionSetsForFAUser LIMIT 1];
        PermissionSet ECPS = [SELECT Name, Id FROM PermissionSet WHERE name=:PermissionSetForEndClient LIMIT 1];
        Profile FAProfile = [SELECT Name, Id FROM Profile WHERE name=:ProfileForFAUser LIMIT 1];  
        Profile EndClientProfile = [SELECT Name, Id FROM profile WHERE name=:ProfileForEndClient LIMIT 1]; 
        profPermSetIdMap.put(FAProfile.Name, FAProfile.Id);
        profPermSetIdMap.put(EndClientProfile.Name, EndClientProfile.Id);
        profPermSetIdMap.put(FAPS.Name, FAPS.Id);
        profPermSetIdMap.put(ECPS.Name, ECPS.Id);
        
        Profile UserProfile = [select id from profile where name = :ProfileForEndClient];
        
        Contact conCU1 = [SELECT id, FirstName, LastName from Contact WHERE LastName = 'Test for Reactivate' LIMIT 1];
        Contact conCU2 = [SELECT id, FirstName, LastName from Contact WHERE LastName = 'Test for remain InActive' LIMIT 1];
        Contact conCU3 = [SELECT id, FirstName, LastName from Contact WHERE LastName = 'Test for Activate' LIMIT 1];
        
        List<User> users = new List<User>(); 
        User communityUser1 = new User(contactId=conCU1.Id,
                                       IsActive=False,
                                       username='Email@emal.com.crmstage123', 
                                       firstname=conCU1.FirstName,
                                       lastname=conCU1.LastName, 
                                       email= 'Email@emal.com.crmstage',
                                       communityNickname = 'uesrid123456',
                                       alias = 'uesrid43', 
                                       UserID__c  = 'uesrid43', 
                                       profileid =UserProfile.Id, 
                                       emailencodingkey='UTF-8',
                                       languagelocalekey='en_US', 
                                       localesidkey='en_US', 
                                       timezonesidkey='America/Los_Angeles');  
        users.add(communityUser1);
        
        User communityUser2 = new User(contactId=conCU2.Id,
                                       username='Email@emal.com.crmstage1234',
                                       IsActive = false,
                                       firstname=conCU2.FirstName,
                                       lastname=conCU2.LastName, 
                                       email= 'Email@emal.com.crmstage',
                                       communityNickname = 'uesrid123',
                                       alias = 'uesrid4', 
                                       UserID__c  = 'uesrid4', 
                                       profileid =UserProfile.Id, 
                                       emailencodingkey='UTF-8',
                                       languagelocalekey='en_US', 
                                       localesidkey='en_US', 
                                       timezonesidkey='America/Los_Angeles'
                                       
                                      );  
        users.add(communityUser2);
        insert users;
        
        Test.startTest(); 
        CommunitiesReactivateUserBatch b1 = new CommunitiesReactivateUserBatch();
        ID b1id = Database.executeBatch(b1,2000);
        Test.stopTest();
        
        User cu1 = [SELECT Id, IsActive, CommunityStatus__c FROM User WHERE ContactId =: conCU1.Id LIMIT 1];
        User cu2 = [SELECT Id, IsActive, CommunityStatus__c FROM User WHERE ContactId =: conCU2.Id LIMIT 1];
        User cu3 = [SELECT Id, IsActive, CommunityStatus__c FROM User WHERE ContactId =: conCU3.Id LIMIT 1];
        
        system.assertEquals(cu1.IsActive,TRUE);
        system.assertEquals(cu2.IsActive,FALSE);
        system.assertEquals(cu3.IsActive,TRUE);
        
    }
    
}