objects/FeeStructure__c.object
<CustomObject>
    <description>Fee structure range and associated basis points for Institutional opportunities.</description>
    <label>Fee Structure</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Fee Structure #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fee Structure</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Funding__c.object
<CustomObject>
    <description>Populated as part of the Institutional Sub Advised process for new relationships and capital contributions</description>
    <label>Funding</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Funding #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/NGAMSettingsHierarchy__c.object
<CustomObject>
    <fields>
        <fullName>ApexSystemUserOrProfile__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox is used in Apex to determine if a user or profile has admin rights to bypass error messages. Normally, this is checked for System Administrator profile and NGAM Integration profile only.</description>
        <inlineHelpText>This checkbox is used in Apex to determine if a user or profile has admin rights to bypass error messages. Normally, this is checked for System Administrator profile and NGAM Integration profile only.</inlineHelpText>
        <label>Apex System User Or Profile</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NGAM Settings - Hierarchy</label>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Firm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Firm</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Firm)</relationshipLabel>
        <relationshipName>FirmOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OpportunityChannel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Channel</label>
        <referenceTo>Channel__c</referenceTo>
        <relationshipLabel>Opportunities (Opportunity Channel)</relationshipLabel>
        <relationshipName>ChannelOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OpportunityRegionDept__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the owner's activity territory's parent territory (either region or department) at time of create or update of Owner.  This value doesn't change when the owner changes roles (only when the actual owner changes or when the oppty is created).</description>
        <label>Opportunity Region/Dept</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Opportunities (Opportunity Region)</relationshipLabel>
        <relationshipName>RegionOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OpportunityRegion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is set on insert and whenever owner change (or Touch__c changes).  It ALWAYS represents the Region of the user regardless of whether activity territory is at the region or territory level.</description>
        <label>Opportunity Region</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Opportunities (Opportunity Region)</relationshipLabel>
        <relationshipName>RegionOpportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OpportunityTerritory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the owner's activity territory at time of create or update of Owner.  This value doesn't change when the owner changes roles (only when the actual owner changes or when the oppty is created).</description>
        <label>Opportunity Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Opportunities (Opportunity Territory)</relationshipLabel>
        <relationshipName>TerritoryOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RepContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For the PRCG Process to be populated with Rep/Contact associated to the request.</description>
        <label>Contact/Rep</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Do Not Show)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <description>Used in Reports to display the primary territory</description>
        <formula>Owner.ActivityTerritoryName__c</formula>
        <label>Territory</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Touch__c</fullName>
        <description>Use this field to "touch" the opportunity for purposes of executing the "after update" triggers, including sharing rules and opportunity territory/region/channel.</description>
        <label>Touch</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>InstSubAdv</fullName>
        <active>true</active>
        <businessProcess>Instututional Sub Advised</businessProcess>
        <description>Associated to the Institutional Sub Advised Sales Process</description>
        <label>InstSubAdv</label>
    </recordTypes>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>FeeStructure__c</fullName>
        <label>Fee Structure</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Funding__c</fullName>
        <label>Funding</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

objects/OpportunityTerritory__c.object
<CustomObject>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Opportunity Territories</relationshipLabel>
        <relationshipName>Opportunity_Territories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity Territory</label>
    <nameField>
        <displayFormat>OT-{0000000000}</displayFormat>
        <label>Opportunity Territory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Territories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>RoleId__c</fullName>
        <externalId>true</externalId>
        <label>Role Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Touch__c</fullName>
        <label>Touch</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ActivityChannelId__c</fullName>
        <description>Used To Tag the Activities and Opportunities created by the user.</description>
        <externalId>true</externalId>
        <inlineHelpText>READ ONLY FIELD : This Will be populated by the UserTerritory__c assignment when the Territory Assignment is tagged as an Activity Territory. Please never update this field directly. Instead Delete/Insert the relevant UserTerritory__c record.</inlineHelpText>
        <label>Activity Channel Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryId__c</fullName>
        <description>Used To Tag the Activities and Opportunities created by the user.</description>
        <externalId>true</externalId>
        <inlineHelpText>READ ONLY FIELD : This Will be populated by the UserTerritory__c assignment when the Territory Assignment is tagged as an Activity Territory. Please never update this field directly. Instead Delete/Insert the relevant UserTerritory__c record.</inlineHelpText>
        <label>Activity Territory Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryParentId__c</fullName>
        <description>The Activity Territory's parent Id</description>
        <label>Activity Territory Parent Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActivityTerritoryType__c</fullName>
        <description>The type of territory for the Activity Territory</description>
        <label>Activity Territory Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Touch__c</fullName>
        <description>This field does not carry any real data.  It is used so that it will kick off workflow, process builder, triggers, etc. when changed.</description>
        <inlineHelpText>This field does not carry any real data.  It is used so that it will kick off workflow, process builder, triggers, etc. when changed.</inlineHelpText>
        <label>Touch</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/OpportunityTriggerHandler.cls
public class OpportunityTriggerHandler {
    
    public static Id instRecTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('InstSubAdv').getRecordTypeId();
    public static Boolean systemUser = (Boolean)NGAMSettingsHierarchy__c.getInstance().ApexSystemUserOrProfile__c;
    
    public static void OpportunityBeforeInsert(List<Opportunity> newOpptyList, Map<Id,Opportunity> newOpptyMap){
        
        validateData(newOpptyList);
        newOpptyList = setOpptyTerrRegChannel(newOpptyList, null);
        newOpptyList = setOpptyFirmId(newOpptyList, null);
        
    }
    
    public static void OpportunityBeforeUpdate(List<Opportunity> newOpptyList, Map<Id,Opportunity> newOpptyMap, Map<Id,Opportunity> oldOpptyMap){
        
        validateData(newOpptyList);
        newOpptyList = setOpptyTerrRegChannel(newOpptyList, oldOpptyMap);
        newOpptyList = setOpptyFirmId(newOpptyList, oldOpptyMap);
        
    }
    
    public static void OpportunityAfterUpdate (List<Opportunity> newOpptyList, Map<Id,Opportunity> newOpptyMap, Map<Id,Opportunity> oldOpptyMap) { 
        
        createOpptyContactRole(newOpptyList, newOpptyMap, oldOpptyMap);
        createOpptyShares(newOpptyList);
        
    }
    
    public static void OpportunityAfterInsert(List<Opportunity> newOpptyList, Map<Id,Opportunity> newOpptyMap) {
        
        createOpptyContactRole(newOpptyList, newOpptyMap, null);
        createOpptyShares(newOpptyList);
        
    }
    
    public static List<Opportunity> setOpptyFirmId(List<Opportunity> newOpptyList, Map<Id,Opportunity> oldOpptysMap) {
        
        Set<Id> accountIdSet = new Set<Id>();
        
        for (Opportunity o : newOpptyList) {
            if (oldOpptysMap == null || o.AccountId != oldOpptysMap.get(o.Id).AccountId || o.Touch__c != oldOpptysMap.get(o.Id).Touch__c) {            
                accountIdSet.add(o.AccountId);
            }
        }
        
        if (!accountIdSet.isEmpty()) {
            Map<Id,Id> accountFirmIdMap = Util.getAccountFirmIdMap(accountIdSet);
            for (Opportunity o : newOpptyList) {
                if (accountFirmIdMap.containsKey(o.AccountId)) {
                    o.Firm__c = accountFirmIdMap.get(o.AccountId);
                }
            }
        }
        
        return newOpptyList;
        
    }    
    
    public static void createOpptyContactRole(List<Opportunity> newOpptyList, Map<Id,Opportunity> newOpptyMap, Map<Id,Opportunity> oldOpptysMap) {
        
        List<OpportunityContactRole> contactRolesToUpsert = new List<OpportunityContactRole>();
        
        for (Opportunity o : [SELECT Id, RepContact__c, (SELECT Id, IsPrimary, ContactId, OpportunityId FROM OpportunityContactRoles)
                              FROM Opportunity
                              WHERE Id IN : newOpptyList]) {
                                  
                                  if (o.OpportunityContactRoles.isEmpty() && o.RepContact__c != null) {
                                      contactRolesToUpsert.add(new OpportunityContactRole(OpportunityId = o.Id, ContactId = o.RepContact__c, IsPrimary = TRUE));
                                  } else {
                                      
									Set<Id> existingContacts = new Set<Id>();

                                      for (OpportunityContactRole ocr : o.OpportunityContactRoles) {
                                          existingContacts.add(ocr.Id);
                                      }
                                      
                                      for (OpportunityContactRole ocr : o.OpportunityContactRoles) {
                                          
                                          if (!existingContacts.contains(ocr.Id)) {
                                              contactRolesToUpsert.add(new OpportunityContactRole(OpportunityId = o.Id, 
                                                                                                              ContactId = o.RepContact__c, 
                                                                                                              IsPrimary = TRUE));
                                          }
                                          
                                          if (ocr.IsPrimary && o.RepContact__c != ocr.ContactId) {
                                              ocr.IsPrimary = FALSE;
                                              contactRolesToUpsert.add(ocr);
                                          }
                                          
                                          if (!ocr.IsPrimary && o.RepContact__c == ocr.ContactId) {
                                              ocr.IsPrimary = TRUE;
                                              contactRolesToUpsert.add(ocr);
                                          }
                                                                                    
                                      }
                                      
                                  }                              
                                  
                              }
        
        upsert contactRolesToUpsert;
        
    }
    
    public static List<Opportunity> setOpptyTerrRegChannel(List<Opportunity> newOpptyList, Map<Id,Opportunity> oldOpptysMap) {
        
        Set<Id> ownerIdSet = new Set<Id>();
        
        for (Opportunity o : newOpptyList) {
            if (oldOpptysMap == null || o.OwnerId != oldOpptysMap.get(o.Id).OwnerId || o.Touch__c != oldOpptysMap.get(o.Id).Touch__c) {
                ownerIdSet.add(o.OwnerId);
            }
        }
        
        if (!ownerIdSet.isEmpty()) {
            
            Map<Id,User> userTerritoryMap = Util.getUserTerritoryMap(ownerIdSet);
            
            for (Opportunity o : newOpptyList) {
                
                if (userTerritoryMap.containsKey(o.OwnerId)) {
                    
                    switch on userTerritoryMap.get(o.OwnerId).ActivityTerritoryType__c {
                        when 'Territory' {
                            o.OpportunityRegion__c = userTerritoryMap.get(o.OwnerId).ActivityTerritoryParentId__c;
                        }
                        when 'Region' {
                            o.OpportunityRegion__c = userTerritoryMap.get(o.OwnerId).ActivityTerritoryId__c;
                        }
                    }
                    
                    o.OpportunityTerritory__c = userTerritoryMap.get(o.OwnerId).ActivityTerritoryId__c;
                    o.OpportunityRegionDept__c = userTerritoryMap.get(o.OwnerId).ActivityTerritoryParentId__c;
                    o.OpportunityChannel__c = userTerritoryMap.get(o.OwnerId).ActivityChannelId__c;
                    
                }
                
            }
            
        }
        
        return newOpptyList;
        
    }    
    
    
    private static void createOpptyShares(List<Opportunity> newOpptyList) {
        
        List<OpportunityShare> opptySharesToCreate = new List<OpportunityShare>();
        
        Set<Id> ownerIdSet = new Set<Id>();
        Map<Id,Id> opptyRegionSharingMap = new Map<Id,Id>();
        Map<Id,Id> opptyTerritorySharingMap = new Map<Id,Id>();
        
        for (Opportunity op : newOpptyList) {
            ownerIdSet.add(op.OwnerId);
        }
        
        Map<Id,User> userTerritoryMap = Util.getUserTerritoryMap(ownerIdSet);
        
        for (Opportunity o : newOpptyList) {
            
            if (userTerritoryMap.containsKey(o.OwnerId)) {
                
                switch on userTerritoryMap.get(o.OwnerId).ActivityTerritoryType__c {
                    when 'Territory' {
                        opptyTerritorySharingMap.put(o.Id, userTerritoryMap.get(o.OwnerId).ActivityTerritoryId__c);
                        opptyRegionSharingMap.put(o.Id, userTerritoryMap.get(o.OwnerId).ActivityTerritoryParentId__c);
                    }
                    when 'Region' {
                        opptyRegionSharingMap.put(o.Id, userTerritoryMap.get(o.OwnerId).ActivityTerritoryId__c);
                    }
                    when else {
						opptyTerritorySharingMap.put(o.Id, userTerritoryMap.get(o.OwnerId).ActivityTerritoryId__c);
                    }
                }
                
            }
            
        }
        
        Map<Id,Id> territoryRoleMap = new Map<Id,Id>();
        Set<Id> roleIdSet = new Set<Id>();
        
        for (Territory__c t : [SELECT Id, RoleId__c FROM Territory__c
                               WHERE Id IN :opptyRegionSharingMap.values()
                               OR Id IN :opptyTerritorySharingMap.values()]) {
                                   
                                   territoryRoleMap.put(t.Id,t.RoleId__c);
                                   roleIdSet.add(t.RoleId__c);
                                   
                               }
        
        Map<Id,Id> roleGroupMap = new Map<Id,Id>();
        
        for (Group g : [SELECT Id, RelatedId
                        FROM Group
                        WHERE RelatedId IN :roleIdSet
                        AND Type = 'RoleAndSubordinates']) {
                            roleGroupMap.put(g.RelatedId, g.Id);
                        }
        
        for (Opportunity o : newOpptyList) {
            
            if (opptyTerritorySharingMap.containsKey(o.Id) &&
                roleGroupMap.get(territoryRoleMap.get(opptyTerritorySharingMap.get(o.Id))) != null) {
                opptySharesToCreate.add(new OpportunityShare(OpportunityId = o.id,
                                                             UserOrGroupId = roleGroupMap.get(territoryRoleMap.get(opptyTerritorySharingMap.get(o.Id))),
                                                             OpportunityAccessLevel='Edit'));     
            }            
            
            if (opptyRegionSharingMap.containsKey(o.Id) &&
                roleGroupMap.get(territoryRoleMap.get(opptyRegionSharingMap.get(o.Id))) != null) {
                opptySharesToCreate.add(new OpportunityShare(OpportunityId = o.id,
                                                             UserOrGroupId = roleGroupMap.get(territoryRoleMap.get(opptyRegionSharingMap.get(o.Id))),
                                                             OpportunityAccessLevel='Edit'));     
            }            
            
        }    
        
        insert opptySharesToCreate;
        
    }
    
    private static void validateData(Map<Id,Opportunity> newOpptyMap) {
        
        if (!systemUser) {
            
           for (Opportunity o : newOpptyMap.values()) {
                if (Trigger.IsInsert && o.RecordTypeId == instRecTypeId && o.StageName == 'Won Unfunded') {
                     o.addError('You must provide both Fee Structure and Funding for every product associated with this opporunity before moving to Won Unfunded. Add the opportunity in a different stage and provide this information.');
                }
            }

        List<Opportunity> opptyLineCheck = [SELECT Id, RecordTypeId, StageName, (SELECT OpportunityId, FeeStructure__c, Funding__c FROM OpportunityLineItems)
                                            FROM Opportunity
                                            WHERE Id IN: newOpptyMap.keySet()];
        
        for (Opportunity o : opptyLineCheck) {

                if (o.RecordTypeId == instRecTypeId && newOpptyMap.get(o.Id).StageName == 'Won Unfunded') {
                    
                    for (OpportunityLineItem oli : o.OpportunityLineItems) {
                        
                        if (String.isBlank(oli.FeeStructure__c) || String.isBlank(oli.Funding__c)) {
                            Opportunity actualOppty = newOpptyMap.get(o.Id);
                            actualOppty.addError('You must provide both Fee Structure and Funding for every product associated with this opporunity before moving to Won Unfunded');
                        }
                        
                    }
                    
                }
                
            }
                        
        }
        
    }

    private static void validateData(List<Opportunity> newListOpps) {

        Map<Id,Opportunity> newOpptyMap = new Map<Id,Opportunity>();
        for (Integer i = 0; i < newListOpps.size(); i++) {
            newOpptyMap.put(newListOpps[i].Id, newListOpps[i]);
        }

        validateData(newOpptyMap);
        
    }
    
}