objects/FinancialAccount__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <description>Integration: NTXS_CUST_ACCOUNTS.Account_Id</description>
        <externalId>true</externalId>
        <inlineHelpText>Id of the Financial Account in Data Central. DEPRECATED will be removed in Version 8.0.</inlineHelpText>
        <label>Account Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>AccountNameEncrypted__c</fullName>
        <description>Unique Vestmark Account name</description>
        <inlineHelpText>Unique Vestmark Account name</inlineHelpText>
        <label>Account Name</label>
        <length>30</length>
        <maskChar>X</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>AccountTitleEncrypted__c</fullName>
        <description>Integration: NTXS_CUST_ACCOUNTS.Account_Title</description>
        <inlineHelpText>Legal title of the account</inlineHelpText>
        <label>Account Title</label>
        <length>175</length>
        <maskChar>X</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>AccountType__c</fullName>
        <description>Integration: NTXS_CUST_ACCOUNTS</description>
        <inlineHelpText>Account Type (e.g. Standard, Model, user-defined)</inlineHelpText>
        <label>Account Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DCFA_Name__c</fullName>
        <description>Financial Account name from Data Central</description>
        <inlineHelpText>Financial Account name from Data Central</inlineHelpText>
        <label>Data Central - FA Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FirstTradeDate__c</fullName>
        <description>Integration: NTXS_CUST_ACCOUNTS.First_Trade_Date</description>
        <inlineHelpText>The date of the first trade</inlineHelpText>
        <label>First Trade Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FirstTradeValue__c</fullName>
        <description>Integration: NTXS_CUST_ACCOUNTS.First_Trade_Value</description>
        <inlineHelpText>The account value when the first trade was transacted in Vestmark</inlineHelpText>
        <label>First Trade Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>InceptionDate__c</fullName>
        <description>Integration: NTXS_CUST_ACCOUNTS.Inception_Date</description>
        <inlineHelpText>The date the account was added to the Vestmark system</inlineHelpText>
        <label>Inception Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>InceptionValue__c</fullName>
        <description>Integration: NTXS_CUST_ACCOUNTS.Inception_Value</description>
        <inlineHelpText>The account value at inception – an expected account value, if provided</inlineHelpText>
        <label>Inception Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LifecycleStep__c</fullName>
        <description>Integration: NTXS_CUST_ACCOUNTS.Lifecycle_Step</description>
        <inlineHelpText>The step in the lifecycle that the account is in.</inlineHelpText>
        <label>Lifecycle Step</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <description>Integration: NTXS_CUST_ACCOUNTS.Manager</description>
        <inlineHelpText>If it is a SMA, the investment manager name. If it is a MSP, the overlay manager name</inlineHelpText>
        <label>Manager</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ModelDescription__c</fullName>
        <description>Model Description</description>
        <inlineHelpText>Model Description</inlineHelpText>
        <label>Model Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ModelOrStrategyName__c</fullName>
        <description>Integration: NTXS_CUST_ACCOUNTS.Model_Or_Strategy_Name</description>
        <inlineHelpText>If it is a SMA, the model the account follows. If it is a MSP, the strategy name.</inlineHelpText>
        <label>Model or Strategy Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <description>Integration: NTXS_CUST_ACCOUNTS.Program</description>
        <inlineHelpText>Sponsor program name</inlineHelpText>
        <label>Program</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sponsor__c</fullName>
        <description>Integration: NTXS_CUST_ACCOUNTS.Sponsor</description>
        <inlineHelpText>Sponsor name</inlineHelpText>
        <label>Sponsor</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TerminationDate__c</fullName>
        <description>Integration: NTXS_CUST_ACCOUNTS.Termination_Date</description>
        <inlineHelpText>The date the account was terminated in the Vestmark system</inlineHelpText>
        <label>Termination Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TerminationValue__c</fullName>
        <description>Integration: NTXS_CUST_ACCOUNTS.Termination_Value</description>
        <inlineHelpText>The account value when the account was terminated</inlineHelpText>
        <label>Termination Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ViewableinCommunity__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If checked, this Financial Account can be viewed in Community</description>
        <inlineHelpText>If checked, this Financial Account can be viewed in Community</inlineHelpText>
        <label>Viewable in Community</label>
        <type>Checkbox</type>
    </fields>
    <description>Used in community to display Financial Account data to community users.  This object's data is sourced from Data Central and maintained via integration.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/FinancialAccountNewController.cls
public with Sharing  class FinancialAccountNewController {
    
    public FinancialAccount__c acc{get; set;}
    String accId;
    ApexPages.StandardController  stdCon;
    public String requestLabel;
    public Boolean Continued { get; set; }
    public String errorMessage { get; set; }
    public String retURL {get; set;}
    public string URL{get;set;}
    public String result{get;set;}
    public  List<FAAccountDetailResponse> ResponseList{get;set;}
    public FAAccountDetailResponse selectedRecord{get;set;}
    public String selectedId{get;set;}
    public  Map<String, FAAccountDetailResponse> responseMap{get;set;}
    Map<String,Id> alreadyExistMap = new  Map<String,Id>();
    public boolean hasRecords {get;set;}
    
    public FinancialAccountNewController(ApexPages.StandardController stdController) {
        stdCon = stdController;
        accId=ApexPages.CurrentPage().getparameters().get('id');     // access the account id from url
        if(accId != null && accId!='')           acc= (FinancialAccount__c)stdController.getRecord();
        else acc=new FinancialAccount__c();  
    }
    
    
    public String errorLevel {get; set;}
    public String messageName {get; set;}
    
    public void showMessage() {
        if(errorLevel == 'WARNING') {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Warning, messageName));
        }
    }
    
    public List<SelectOption> responseRecords {
        get{
            
            if ( (responseMap != null) && (responseMap.size() > 0))
            {
                List<SelectOption> options = new List<SelectOption>();
                /* options.add(new SelectOption('','-- Select an Account ---'));*/
                
                integer i=0;
                Boolean Showdisbale = true;
                if(responseMap.size() > 100)Showdisbale= false;
                String FirstID  = null;
                List<FAAccountDetailResponse> l = responseMap.values();
                l.sort();
                for(FAAccountDetailResponse f : l)
                {
                    if(alreadyExistMap.containsKey(String.valueOf(f.accountId)) )
                    {
                        options.add(new SelectOption( String.valueOf(f.accountId),f.accountName+'  '+f.accountTitle, Showdisbale)); 
                    }
                    else
                    {
                        options.add(new SelectOption( String.valueOf(f.accountId),f.accountName+'  '+f.accountTitle));   
                        if(i==0)FirstID=String.valueOf(f.accountId);
                        i++;
                    }
                    
                    if(i>100)break;
                }
                hasRecords = true;
                if(selectedId==null && FirstID != null){ selectedId=FirstID;  populateResponse(); }
                return options;
                
            }
            hasRecords = false;
            return null;
            
        }
        set;
        
    }
    
    
    
    // Method to start the Continuation Webservice
    public Object getData() {
        // Create continuation with a timeout
        Continuation con = new Continuation(30);
        // Set callback method
        con.continuationMethod='processResponse';
        // Call webservice using Continuation
        requestLabel = FinancialAccountGetAccountWSCCallout.getData(con,acc.AccountNameEncrypted__c, 5,URL);    
        Continued = false;     
        return con; 
    }
    
    public void resetForm()
    {
        FinancialAccount__c temp = acc;
        acc = new FinancialAccount__c();
        responseMap = new Map<String, FAAccountDetailResponse>();
        acc.AccountNameEncrypted__c = temp.AccountNameEncrypted__c;
    }
    // Method to start the Continuation Webservice
    public void getDataSync() {
        try
        {
            String val =  acc.AccountNameEncrypted__c ;
            resetForm();
            if(val.length() < 3) 
            {
                
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.WARNING,'There not enough characters in search and you may get limit exceeed warning.');
                //ApexPages.addMessage(myMsg);
                System.debug('Error : ' + myMsg );
                //return;
            }
            
            
            String result =  FinancialAccountGetAccountWSCCallout.getDataSync(acc.AccountNameEncrypted__c);
            processRequest(result);
        }
        catch(System.Exception ex)
        {
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Error: Could not get data ');
            ApexPages.addMessage(myMsg);
            System.debug('Error : ' + ex.getMessage() );
        }
    }
    
    
    public void populateResponse() 
    {
        if ( (selectedId != null) && (responseMap.containsKey(selectedId)))
        {
            selectedRecord = responseMap.get(selectedId);
            
            if(selectedRecord != null)
            {
                if(alreadyExistMap.containsKey(selectedId))  acc.Id = alreadyExistMap.get(selectedId);
                acc.AccountId__c =  selectedRecord.accountId;
                acc.Name = selectedRecord.accountName;
                if( acc.Name.length() > 3)acc.Name = selectedRecord.accountName.left(3);
                if( selectedRecord.accountName.length() >  4)acc.Name = acc.Name + selectedRecord.accountName.right(4);
                
                acc.AccountNameEncrypted__c =  selectedRecord.accountName;
                acc.AccountTitleEncrypted__c =  selectedRecord.accountTitle;
                acc.AccountType__c = selectedRecord.accountType;
                acc.Sponsor__c = selectedRecord.sponsor;
                acc.Program__c = selectedRecord.program;
                acc.Manager__c = selectedRecord.manager;
                acc.LifecycleStep__c = selectedRecord.lifeCycleStep;
                if(selectedRecord.inceptionValue != null)
                    acc.InceptionValue__c = double.valueof(selectedRecord.inceptionValue);
                if(selectedRecord.inceptionDate != null)
                {
                    DateTime t = DateTime.newInstance(selectedRecord.inceptionDate);
                    if(t != null)
                        acc.InceptionDate__c = Date.newInstance(t.year(), t.month(), t.day()) ;
                }
                acc.ModelOrStrategyName__c= selectedRecord.modelName;
                acc.ModelDescription__c = selectedRecord.modelDescription;
                acc.DCFA_Name__c = selectedRecord.faName;
                if(selectedRecord.firstTradeDate != null)   
                {
                    DateTime f = DateTime.newInstance(selectedRecord.firstTradeDate);
                    if(f != null)
                        acc.FirstTradeDate__c = Date.newInstance(f.year(), f.month(), f.day()) ;
                }
                if(selectedRecord.firstTradeValue != null)
                    acc.FirstTradeValue__c = double.valueof(selectedRecord.firstTradeValue);
                if(selectedRecord.terminationDate != null)
                {
                    DateTime te = DateTime.newInstance(selectedRecord.terminationDate);
                    if(te != null)
                        acc.TerminationDate__c = Date.newInstance(te.year(), te.month(), te.day()) ;
                }
                if(selectedRecord.terminationValue != null)
                    acc.TerminationValue__c = double.valueof(selectedRecord.terminationValue);              
                System.debug('results: ' + selectedRecord); 
                acc.ViewableinCommunity__c = true;
            }
        }
        
    }
    
    
    public void processRequest(String result) 
    {
        System.debug('result: ' + result);   
        ResponseList =  FAAccountDetailResponse.parse(result);
        responseMap = new Map<String, FAAccountDetailResponse>();
        List<Integer> accountIds = new List<Integer>();
        for(FAAccountDetailResponse r : ResponseList)
        {
            accountIds.Add(r.accountId);
        }
        List<FinancialAccount__c> alreadyExist = [SELECT Id,  AccountId__c
                                                  FROM FinancialAccount__c where AccountId__c IN:accountIds];
        alreadyExistMap = new  Map<String,Id>();
        for(FinancialAccount__c f : alreadyExist)
        {
            alreadyExistMap.put(String.valueOf(f.AccountId__c),f.Id);
        }
        
        for(FAAccountDetailResponse r : ResponseList)
        {
            if( !responseMap.containsKey(String.valueOf(r.accountId)))
            {
                // if((alreadyExistMap != null) && (alreadyExistMap.size()>0) && (!alreadyExistMap.containsKey(r.accountId)))                
                responseMap.put( String.valueOf(r.accountId), r);
            }
            
        }
        boolean hasExceededLimits = false;
        if(responseMap != null && responseMap.size()>0) {
            hasRecords = true;if(responseMap.size()>100)hasExceededLimits= true;
        } else hasRecords= false;
        if(hasRecords == false) {
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.WARNING,'No records found, Please try again with new search! ');
            ApexPages.addMessage(myMsg);
            System.debug('Error : ' + myMsg );
        }
        if(hasExceededLimits == true) {
            ApexPages.Message myMsg1 = new ApexPages.Message(ApexPages.Severity.WARNING,'Search found more than 100 records, please refine your search to get smaller dataset.');
            ApexPages.addMessage(myMsg1);
            System.debug('Error : ' + myMsg1 );
        }
        
    }
    
    
    // Callback method 
    public Object processResponse() {
        HttpResponse response = Continuation.getResponse(this.requestLabel);
        System.debug('response: ' + response);
        result = response.getBody();
        processRequest(result); 
        Continued = true;
        return null;
    }    
    
    public PageReference save() {
        
        if (String.IsBlank(selectedId)) {
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'You cannot save this record because an account has not been selected.  Fetch, select an account, or Cancel.  Note that it is possible that this account already exists.');
            ApexPages.addMessage(myMsg);
        } else {
            try
            {
                if(accId != null && accId!='')   update acc;
                else    insert acc; 
                
                PageReference NextPage = new ApexPages.StandardController(acc).view();
                NextPage.getParameters().put('retURL','/' +retURL);
                return NextPage;
            }
            catch(System.Exception ex) {
                errorMessage = ex.getMessage(); ApexPages.addMessages(ex); return null;
            }
        }
        return null;   
    }
    
    public PageReference Cancel()
    {
        // PageReference returnPage = ApexPages.currentPage().getHeaders().get('Referer');
        // a2N/o
        PageReference pg = new PageReference('/a2N/o');
        String retUrl =  ApexPages.currentPage().getParameters().get('retURL');
        if( retUrl != null)  pg = new PageReference(retUrl);
        return pg;
    }
    
    
    
    
}