objects/NGAMSettings__c.object
<CustomObject>
    <fields>
        <fullName>ProfileSystemAdministrator__c</fullName>
        <description>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</description>
        <inlineHelpText>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</inlineHelpText>
        <label>Profile: System Administrator</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Holds the NGAM settings</description>
    <label>NGAM Settings</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>ActivityZoneId__c</fullName>
        <description>Used To Tag the Activities and Opportunities created by the user.</description>
        <inlineHelpText>READ ONLY FIELD : This Will be populated by the UserTerritory__c assignment when the Territory Assignment is tagged as an Activity Territory. Please never update this field directly. Instead Delete/Insert the relevant UserTerritory__c record.</inlineHelpText>
        <label>Activity Zone Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserID__c</fullName>
        <defaultValue>"Populate This Field"</defaultValue>
        <externalId>true</externalId>
        <label>UserID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Zone__c.object
<CustomObject>
    <fields>
        <fullName>Zone__c</fullName>
        <externalId>true</externalId>
        <label>Zone</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UserData_Test.cls
@isTest 
private class UserData_Test {
    static testMethod void IsVipTest() { 
    
         //Profile p = [select id from profile where name='System Administrator'];
         DataFactory.CreateNGAMCustomSettings(); 
         NGAMSettings__c ngamSettings = [select id,ProfileSystemAdministrator__c from NGAMSettings__c limit 1]; 
         string p = Util.getCustomSettingProfileId(ngamSettings.ProfileSystemAdministrator__c);

         User u2 = new User(alias = 'standt', email='SFDCadmin@ngam.natixis.com', 
                        emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
                        localesidkey='en_US', profileid = p, 
                        timezonesidkey='America/Los_Angeles', username='SFDCadmin@ngam.natixis.com',UserID__c='SFDCadmin');
            
        System.runAs(u2){ 
    
        UserData u = new UserData();
        Test.StartTest();
        boolean isVip = u.IsVip;
        Test.stopTest();
        System.assertNotEquals(true, isVip); 
        }   
    }
    
    static testMethod void IsMDTest() { 
    
        // Profile p = [select id from profile where name='System Administrator']; 
        DataFactory.CreateNGAMCustomSettings(); 
        NGAMSettings__c ngamSettings = [select id,ProfileSystemAdministrator__c from NGAMSettings__c limit 1]; 
        string p = Util.getCustomSettingProfileId(ngamSettings.ProfileSystemAdministrator__c);

         User u2 = new User(alias = 'standt', email='SFDCadmin@ngam.natixis.com', 
                        emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
                        localesidkey='en_US', profileid = p, 
                        timezonesidkey='America/Los_Angeles', username='SFDCadmin@ngam.natixis.com',UserID__c='SFDCadmin');
                        
        System.runAs(u2){ 
        
        Zone__c z = new Zone__c(Name = 'MD', zone__c = 24);
        insert z;
        
        u2.ActivityZoneId__c = z.id;
        update u2; 
           
        UserData u = new UserData();
        Test.StartTest();  
        boolean isMd = u.isMD;      
        Test.stopTest();
        System.assertEquals(true, isMd); 
        }   
    }
}