objects/NGAMSettings__c.object
<CustomObject>
    <fields>
        <fullName>TableauProductionDomain__c</fullName>
        <description>The production Domain for Tableau reports.  VF pages use this URL in the product org (vizbi.ngam.natixis.com)</description>
        <inlineHelpText>The production Domain for Tableau reports.  VF pages use this URL in the product org (vizbi.ngam.natixis.com)</inlineHelpText>
        <label>Tableau Production Domain</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TableauQADomain__c</fullName>
        <description>Tableau QA Domain.  VF pages use this URL in all sandbox orgs. (vizbiqa.ngam.natixis.com)</description>
        <inlineHelpText>Tableau QA Domain.  VF pages use this URL in all sandbox orgs. (vizbiqa.ngam.natixis.com)</inlineHelpText>
        <label>Tableau QA Domain</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Holds the NGAM settings</description>
    <label>NGAM Settings</label>
</CustomObject>

objects/NGAMSettingsHierarchy__c.object
<CustomObject>
    <fields>
        <fullName>ByPassAccountValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows entity to by-pass validation rules on Account</description>
        <inlineHelpText>Allows entity to by-pass validation rules on Account</inlineHelpText>
        <label>By-Pass Account Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NGAM Settings - Hierarchy</label>
</CustomObject>

classes/TableauVFTest.cls
@isTest
public class TableauVFTest {
    
    @testSetup
    static void testSetup() {
    
        NGAMSettingsHierarchy__c hsettings = NGAMSettingsHierarchy__c.getOrgDefaults();
        hsettings.ByPassAccountValidationRules__c  = TRUE;
        upsert hsettings NGAMSettingsHierarchy__c.Id;

        
        NGAMSettings__c settings = new NGAMSettings__c(Name = 'NGAM_ALL',
                                                       TableauQADomain__c = 'vizbiqa.ngam.natixis.com',
                                                       TableauProductionDomain__c = 'vizbi.ngam.natixis.com');
        insert settings;
        
    }
    
    @isTest
    static void contactTest() {
        
        List<Account> a = DataFactory.createTestAccounts(1);
        insert a;
        
        List<Contact> c = DataFactory.createTestContacts(1, a, FALSE);
        insert c;
        
        Test.startTest();
        Test.setCurrentPage(Page.TableauContactAdvisorClientProfile);
        TableauVFExtension tvfe = new TableauVFExtension(new ApexPages.StandardController(c[0]));
        Test.stopTest();
        
    }

    @isTest
    static void tabTest() {
        
        Test.startTest();
        Test.setCurrentPage(Page.TableauTabAllTrades);
        TableauVFController tvfe = new TableauVFController();
        tvfe.gettableauDomain();
        Test.stopTest();
        
    }    
    
}