objects/NGAMSettingsHierarchy__c.object
<CustomObject>
    <fields>
        <fullName>ByPassAccountValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows entity to by-pass validation rules on Account</description>
        <inlineHelpText>Allows entity to by-pass validation rules on Account</inlineHelpText>
        <label>By-Pass Account Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NGAM Settings - Hierarchy</label>
</CustomObject>

objects/PRCGModelSecurity__c.object
<CustomObject>
    <fields>
        <fullName>Security__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Security</label>
        <referenceTo>Security__c</referenceTo>
        <relationshipName>RequestPortfoliosSecurity</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PRCGRequestModel__c</fullName>
        <label>PRCG Request Model</label>
        <referenceTo>PRCGRequestModel__c</referenceTo>
        <relationshipLabel>PRCG Model Securities</relationshipLabel>
        <relationshipName>PRCGModelSecurities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PRCG Model Security</label>
    <nameField>
        <displayFormat>PMS-{0000000000}</displayFormat>
        <label>Request Portfolio Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PRCG Model Securities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PRCGRequestModel__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>PRCG Request Models</relationshipLabel>
        <relationshipName>RequestModels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ModelId__c</fullName>
        <description>Artemus.request_model.model_id
numeric(38,0)</description>
        <externalId>true</externalId>
        <label>ModelId</label>
        <length>38</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>PRCG Request Model</label>
    <nameField>
        <displayFormat>PRM-{0000000000}</displayFormat>
        <label>PRCG Request Model Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PRCG Request Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PRCGResearchNote__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <description>The approval status of the Security Research</description>
        <inlineHelpText>Enter or update the approval status of the Security Research</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Note__c</fullName>
        <label>Note</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Security__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Security</label>
        <referenceTo>Security__c</referenceTo>
        <relationshipLabel>PRCG Research Notes</relationshipLabel>
        <relationshipName>PRCGResearchNotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ticker__c</fullName>
        <description>The Security Ticker Symbol (identifier)</description>
        <formula>Security__r.Ticker__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Ticker Symbol from the Security object</inlineHelpText>
        <label>Ticker</label>
        <type>Text</type>
    </fields>
    <description>Holds research related to a Security; this data is authored by PRCG.</description>
    <label>PRCG Research Note</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PRCG Research Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Security__c.object
<CustomObject>
    <fields>
        <fullName>MorningstarCode__c</fullName>
        <externalId>true</externalId>
        <label>Morningstar Code</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Ticker__c</fullName>
        <description>Artemus.security.ticker
varchar(255)</description>
        <label>Ticker</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Security</label>
    <nameField>
        <label>Security Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Securities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PRCGResearchNotes_Test.cls
@IsTest
private class PRCGResearchNotes_Test {    
    static testMethod void getNotes() {
        
        NGAMSettingsHierarchy__c hsettings = NGAMSettingsHierarchy__c.getOrgDefaults();
        hsettings.ByPassAccountValidationRules__c  = TRUE;
        upsert hsettings NGAMSettingsHierarchy__c.Id;

        
        //insert account
        List<Account> myA = DataFactory.createTestAccounts(1);
        insert myA;
        
        //insert contact
        Contact contact = new Contact(LastName = 'Test', FirstName = '1',AccountId=myA[0].Id);
        insert contact;
        
        //insert case
        Case c = new Case();
        c.RecordType = new RecordType (Name ='PRCG Request');
        c.Contact = contact;
        insert c;
        
        //insert Request Models
        PRCGRequestModel__c requestModel = new PRCGRequestModel__c();
        requestModel.Case__c = c.Id;
        requestModel.ModelId__c = '1';
        insert requestModel;
        
        //insert security
        Security__c security1 = new Security__c();
        security1.Name = 'AXA fund 1';
        security1.Ticker__c = 'AXA1';
        security1.MorningstarCode__c = '1';
        insert security1;
        
        //insert security
        Security__c security2 = new Security__c();
        security2.Name = 'AXA fund 2';
        security2.Ticker__c = 'AXA2';
        security2.MorningstarCode__c = '2';
        insert security2;
                     
        //insert request portfolios
        PRCGModelSecurity__c modelSecurity1 = new PRCGModelSecurity__c();
        modelSecurity1.Security__c = security1.Id;
        modelSecurity1.PRCGRequestModel__c = requestModel.Id;
        insert modelSecurity1;     
        
        //insert request portfolios
        PRCGModelSecurity__c modelSecurity2 = new PRCGModelSecurity__c();
        modelSecurity2.Security__c = security2.Id;
        modelSecurity2.PRCGRequestModel__c = requestModel.Id;
        insert modelSecurity2;   
        
        //insert research note
        PRCGResearchNote__c note1 = new PRCGResearchNote__c();
        note1.Note__c = 'This is test3';
        //note1.Subject__c = 'General';
        note1.Approval_Status__C = 'Approved';
        note1.Security__c = security1.Id;
        insert note1; 
        
        //insert research note
        PRCGResearchNote__c note2 = new PRCGResearchNote__c();
        note2.Note__c = 'This is test2';
        //note2.Subject__c = 'General';
        note2.Approval_Status__C = 'Approved';
        note2.Security__c = security2.Id;
        insert note2;   
        
         //insert research note
        PRCGResearchNote__c note3 = new PRCGResearchNote__c();
        note3.Note__c = 'This is test3';
        //note3.Subject__c = 'General';
        note3.Approval_Status__C = 'Approved';
        note3.Security__c = security1.Id;
        insert note3;     
      
        Test.StartTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(c);
        PRCGResearchNotes prn = new PRCGResearchNotes(sc);
        Map<string, List<PRCGResearchNote__c>> m = prn.getnoteMap(c.Id);
          
      
        Test.stopTest();
        
        system.debug('Size:' + m.size());
        
    }
}