objects/NGAMSettings__c.object
<CustomObject>
    <fields>
        <fullName>LastBatchJobErrorNotificationCompletion__c</fullName>
        <description>The last time the apex batch job error notification job completed.  Used in query to make sure we sweep all batches that may have failed since last run.</description>
        <label>Last Batch Job Error Notification Compl</label>
        <type>DateTime</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Holds the NGAM settings</description>
    <label>NGAM Settings</label>
</CustomObject>

objects/NGAMSettingsHierarchy__c.object
<CustomObject>
    <fields>
        <fullName>ByPassAccountValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows entity to by-pass validation rules on Account</description>
        <inlineHelpText>Allows entity to by-pass validation rules on Account</inlineHelpText>
        <label>By-Pass Account Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NGAM Settings - Hierarchy</label>
</CustomObject>

classes/BatchJobErrorNotificationBatchTest.cls
@istest 
private class BatchJobErrorNotificationBatchTest {
    
    static testmethod void test() {
        
        NGAMSettingsHierarchy__c settings = NGAMSettingsHierarchy__c.getOrgDefaults();
        settings.ByPassAccountValidationRules__c  = TRUE;
        upsert settings NGAMSettingsHierarchy__c.Id;

        
        NGAMSettings__c NS = new NGAMSettings__c(Name='test1'); 
        NS.LastBatchJobErrorNotificationCompletion__c = system.today(); 
        insert NS; 
        
        String query = 'SELECT ApexClassId, TotalJobItems, CompletedDate, ExtendedStatus, JobItemsProcessed, JobType, MethodName, NumberOfErrors, Status ';
        query += 'FROM AsyncApexJob LIMIT 10';
        //query += 'WHERE CompletedDate >= 1901-01-01T00:00:00Z LIMIT 10';
                 
        Test.startTest();
        BatchJobErrorNotificationBatch bjnb = new BatchJobErrorNotificationBatch(query);
        database.executebatch(bjnb);
        Test.stopTest();        
    }    
}