objects/NGAMSettings__c.object
<CustomObject>
    <fields>
        <fullName>ProfileSystemAdministrator__c</fullName>
        <description>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</description>
        <inlineHelpText>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</inlineHelpText>
        <label>Profile: System Administrator</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Holds the NGAM settings</description>
    <label>NGAM Settings</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>UserID__c</fullName>
        <defaultValue>"Populate This Field"</defaultValue>
        <externalId>true</externalId>
        <label>UserID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ApexActivitiesStatsLoggerCleanup_Test.cls
@isTest 
public class ApexActivitiesStatsLoggerCleanup_Test {
 static testMethod void ApexActivitiesStatsLoggerCleanupTesting() {
       //Profile p = [select id from profile where name='System Administrator'];
      DataFactory.CreateNGAMCustomSettings(); 
 NGAMSettings__c ngamSettings = [select id,ProfileSystemAdministrator__c from NGAMSettings__c limit 1]; 
string p = Util.getCustomSettingProfileId(ngamSettings.ProfileSystemAdministrator__c);
 
       User u2 = new User(alias = 'standt', email='SFDCadmin@ngam.natixis.com', 
                            emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
                            localesidkey='en_US', profileid = p, 
                            timezonesidkey='America/Los_Angeles', username='SFDCadmin@ngam.natixis.com',UserID__c='SFDCadmin');        
        System.runAs(u2) 
                {           
                test.startTest();    
               // ApexActivitiesStatsLoggerCleanup.CleanupLoggger(2);
                ApexActivitiesStatsLoggerCleanup trac = new ApexActivitiesStatsLoggerCleanup();
                ID tracid = database.executeBatch(trac,2000); 
                ApexActivitiesStatsLoggerCleanup.CleanupLoggger(2);
                test.stopTest();
                }
 }
}