objects/NGAMSettings__c.object
<CustomObject>
    <fields>
        <fullName>TableauParametersNotAvailableMsg__c</fullName>
        <description>Message that displays on visualforce pages when EDW Durable Key or Visualization Name is not available on the given record.</description>
        <inlineHelpText>Message that displays on visualforce pages when EDW Durable Key or Visualization Name is not available on the given record.</inlineHelpText>
        <label>Tableau Parameters Not Available Msg</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TableauProductionDomain__c</fullName>
        <description>The production Domain for Tableau reports.  VF pages use this URL in the product org (vizbi.ngam.natixis.com)</description>
        <inlineHelpText>The production Domain for Tableau reports.  VF pages use this URL in the product org (vizbi.ngam.natixis.com)</inlineHelpText>
        <label>Tableau Production Domain</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TableauQADomain__c</fullName>
        <description>Tableau QA Domain.  VF pages use this URL in all sandbox orgs. (vizbiqa.ngam.natixis.com)</description>
        <inlineHelpText>Tableau QA Domain.  VF pages use this URL in all sandbox orgs. (vizbiqa.ngam.natixis.com)</inlineHelpText>
        <label>Tableau QA Domain</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Holds the NGAM settings</description>
    <label>NGAM Settings</label>
</CustomObject>

classes/TableauHelper.cls
public class TableauHelper {
    
    public static String getTableauDomain() {
        
        String tableauDomain;
        
        NGAMSettings__c settings = NGAMSettings__c.getvalues('NGAM_ALL');
        Organization org = [SELECT Id, IsSandbox FROM Organization LIMIT 1];
        if (org.IsSandbox == FALSE) {
            tableauDomain = settings.TableauProductionDomain__c;
        } else {
            tableauDomain = settings.TableauQADomain__c;
        }
        
        return tableauDomain;
    }

    public static String getTableauParametersNotAvailableMsg() {

        NGAMSettings__c settings = NGAMSettings__c.getvalues('NGAM_ALL');
        String msg = settings.TableauParametersNotAvailableMsg__c;
        return msg;

    }





/*    public static String getTableauVisualization(SObject o, String vt) {
        
        String v;
        
        if (String.isBlank(vt)) vt = 'Default';
        
        String objectName = o.getSObjectType().getDescribe().getName();
        
        TableauVisualization__mdt vm = [SELECT Visualization__c FROM TableauVisualization__mdt
                                        WHERE VisualizationType__c = :vt
                                        AND ObjectAPIName__c = :objectName
                                        LIMIT 1];
        
        v = vm.Visualization__c;
        
        return v;
    }   */ 
    
}