objects/NGAMSettings__c.object
<CustomObject>
    <fields>
        <fullName>BusinessDays__c</fullName>
        <description>Business Days in the Current Month</description>
        <inlineHelpText>Business Days in the Current Month</inlineHelpText>
        <label>BusinessDays</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WorkDays__c</fullName>
        <description>Number of Work Days past this month</description>
        <inlineHelpText>Number of Work Days past this month</inlineHelpText>
        <label>WorkDays</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Holds the NGAM settings</description>
    <label>NGAM Settings</label>
</CustomObject>

objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>TerritoryName__c</fullName>
        <defaultValue>"Update Me"</defaultValue>
        <externalId>true</externalId>
        <label>MARS Territory Name</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/TransactionSummaryByTerritory__c.object
<CustomObject>
    <fields>
        <fullName>BusinessDaysRest__c</fullName>
        <label>Business Days Rest</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BusinessDays__c</fullName>
        <label>Business Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DailyPurchases__c</fullName>
        <label>Daily Purchases</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DailyRedemptions__c</fullName>
        <label>Daily Redemptions</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MTDGoal__c</fullName>
        <label>MTD Goal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MonthlyGoal__c</fullName>
        <label>Monthly Goal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MonthlyPurchases__c</fullName>
        <label>Monthly Purchases</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MonthlyRedemptions__c</fullName>
        <label>Monthly Redemptions</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProductType__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>COLLECTIVE TRUST</fullName>
                </value>
                <value>
                    <fullName>HEDGE FUND</fullName>
                </value>
                <value>
                    <fullName>INSTITUTIONAL INTL</fullName>
                </value>
                <value>
                    <fullName>INSTITUTIONAL US</fullName>
                </value>
                <value>
                    <fullName>MANAGED ACCOUNT</fullName>
                </value>
                <value>
                    <fullName>MANAGED ACCOUNT NON-ELIGIBLE</fullName>
                </value>
                <value>
                    <fullName>MONEY MARKET</fullName>
                </value>
                <value>
                    <fullName>MUTUAL FUND</fullName>
                </value>
                <value>
                    <fullName>MUTUAL FUND - COPY</fullName>
                </value>
                <value>
                    <fullName>MUTUAL FUND - NO FEE</fullName>
                </value>
                <value>
                    <fullName>OVERLAY</fullName>
                </value>
                <value>
                    <fullName>PRIVATE PLACEMENT</fullName>
                </value>
                <value>
                    <fullName>SERVICE</fullName>
                </value>
                <value>
                    <fullName>SUB ADVISED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Sales To Goals</relationshipLabel>
        <relationshipName>Trade_Summaries_By_Territories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TranSumTerrId__c</fullName>
        <description>Primary Key</description>
        <externalId>true</externalId>
        <label>TranSumTerrId</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>YTDGoal__c</fullName>
        <label>YTD Goal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>YearlyGoal__c</fullName>
        <label>Yearly Goal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>YearlyPurchases__c</fullName>
        <label>Yearly Purchases</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>YearlyRedemptions__c</fullName>
        <label>Yearly Redemptions</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <description>Used for Daily Sales to Goals reports</description>
    <label>Sales To Goals</label>
    <nameField>
        <displayFormat>TT-{0000000000}</displayFormat>
        <label>Sale By Territory</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales To Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TransactionSumByTerrTriggerHandlerTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TransactionSumByTerrTriggerHandlerTest {

    static testMethod void updtBusinessDaysTest() {
    	Territory__c t = new Territory__c(TerritoryName__c = 'WHSE TERR1');    	
    	insert t;
    	NGAMSettings__c ngs = new NGAMSettings__c(Name = 'NGAM_ALL', WorkDays__c = 0, BusinessDays__c = 0);
    	insert ngs;
    	TransactionSummaryByTerritory__c  tst = new TransactionSummaryByTerritory__c(
    		TranSumTerrId__c = '12345',
    		Territory__c = t.Id,
			ProductType__c = 'MF',
			BusinessDays__c = 21,
			BusinessDaysRest__c = 12,
			DailyPurchases__c = 10000,
			DailyRedemptions__c = 20000,
			MonthlyPurchases__c = 100000,
			MonthlyRedemptions__c = 100000,
			YearlyPurchases__c = 100000,
			YearlyRedemptions__c = 100000,
			MonthlyGoal__c = 300000,
			MTDGoal__c = 10000,
			YearlyGoal__c = 200000,
			YTDGoal__c = 10000000    			
    	);
    	insert tst;
		List<NGAMSettings__c> l = [select Id, WorkDays__c, BusinessDays__c from NGAMSettings__c];
    	System.assertEquals(1, l.size());
    	NGAMSettings__c sc = l.get(0);
    	System.assertEquals(21, sc.BusinessDays__c);
    	System.assertEquals(21 - 12, sc.WorkDays__c);
    }
}