objects/NGAMSettings__c.object
<CustomObject>
    <fields>
        <fullName>ActivityContactRollupBatchFromDate__c</fullName>
        <description>Used by ActivityContactRollupBatch as the starting date for AC roll up.  Can be set to any date within last 30 days, but must be before Activity Contact Rollup Batch To Date.  Value normally maintained automatically by batch.</description>
        <inlineHelpText>Used by ActivityContactRollupBatch as the starting date for AC roll up.  Can be set to any date within last 30 days, but must be before Activity Contact Rollup Batch To Date.  Value normally maintained automatically by batch.</inlineHelpText>
        <label>Activity Contact Rollup Batch From Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>FailureNotificationEmailAddress__c</fullName>
        <description>Used in apex to notify via email when processes fail. Separate multiple email addresses with semi-colons.</description>
        <inlineHelpText>Used in apex to notify via email when processes fail. Separate multiple email addresses with semi-colons.</inlineHelpText>
        <label>Failure Notification Email Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Holds the NGAM settings</description>
    <label>NGAM Settings</label>
</CustomObject>

objects/NGAMSettingsHierarchy__c.object
<CustomObject>
    <fields>
        <fullName>ByPassAccountValidationRules__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows entity to by-pass validation rules on Account</description>
        <inlineHelpText>Allows entity to by-pass validation rules on Account</inlineHelpText>
        <label>By-Pass Account Validation Rules</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NGAM Settings - Hierarchy</label>
</CustomObject>

classes/TaskFormatingSched_Test.cls
@isTest
private class TaskFormatingSched_Test {
    
    static testmethod void TaskFormatingSchedTesting() 
    {
    
         NGAMSettingsHierarchy__c hsettings = NGAMSettingsHierarchy__c.getOrgDefaults();
        hsettings.ByPassAccountValidationRules__c  = TRUE;
        upsert hsettings NGAMSettingsHierarchy__c.Id;
   
        
        NGAMSettings__c NS = new NGAMSettings__c(Name='test1'); 
        NS.ActivityContactRollupBatchFromDate__c = system.today();
        NS.FailureNotificationEmailAddress__c = 'dat@natixis.com';
        insert NS;         
        
        List<Account> myAccounts = DataFactory.createTestAccounts(3);
        insert myAccounts;
        
        List<Contact> myContacts = DataFactory.createTestContacts(3, myAccounts, false);
        insert myContacts;     
        
        List<Task> myTasks = DataFactory.createTestTasks(3,myContacts,'Mass Email:TEST');  
        insert myTasks;      
        
        Test.startTest();
        TaskFormatingSched.scheduleMe();
        Test.stopTest();
    }
}