objects/NGAMSettings__c.object
<CustomObject>
    <fields>
        <fullName>BusinessDays__c</fullName>
        <description>Business Days in the Current Month</description>
        <inlineHelpText>Business Days in the Current Month</inlineHelpText>
        <label>BusinessDays</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WorkDays__c</fullName>
        <description>Number of Work Days past this month</description>
        <inlineHelpText>Number of Work Days past this month</inlineHelpText>
        <label>WorkDays</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Holds the NGAM settings</description>
    <label>NGAM Settings</label>
</CustomObject>

objects/TransactionSummaryByTerritory__c.object
<CustomObject>
    <fields>
        <fullName>BusinessDaysRest__c</fullName>
        <label>Business Days Rest</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BusinessDays__c</fullName>
        <label>Business Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <description>Used for Daily Sales to Goals reports</description>
    <label>Sales To Goals</label>
    <nameField>
        <displayFormat>TT-{0000000000}</displayFormat>
        <label>Sale By Territory</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales To Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TransactionSumByTerritoryTriggerHandler.cls
public class TransactionSumByTerritoryTriggerHandler {
	public static void updtBusinessDays(List<TransactionSummaryByTerritory__c> tstl) {
		System.debug('Number of TransactionSummaryByTerritory__c' + tstl.size());
		TransactionSummaryByTerritory__c tst = tstl.get(0);
		List<NGAMSettings__c> l = [select Id, WorkDays__c, BusinessDays__c from NGAMSettings__c];
		if(l == null || l.size() == 0) return;
		NGAMSettings__c setting = l.get(0);
		Decimal workDays = tst.BusinessDays__c - tst.BusinessDaysRest__c;
		if(tst.BusinessDays__c == setting.BusinessDays__c && workDays == setting.WorkDays__c) return;
		List<NGAMSettings__c> sl = new List<NGAMSettings__c>();
		NGAMSettings__c s = new NGAMSettings__c(Id = setting.Id, BusinessDays__c = tst.BusinessDays__c, WorkDays__c = workDays);
		update s;		 			
	}
}