objects/NGAMSettings__c.object
<CustomObject>
    <fields>
        <fullName>ProfileSales__c</fullName>
        <description>Indicates the profile that should be used for Sales User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</description>
        <inlineHelpText>Indicates the profile that should be used for Sales User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</inlineHelpText>
        <label>Profile: Sales</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProfileSystemAdministrator__c</fullName>
        <description>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</description>
        <inlineHelpText>Indicates the profile that should be used for System Admin User in Apex.  This prevents the hard-coding of profile names into Apex classes.  This value must be an existing profile and cannot be null or Apex test classes will fail.</inlineHelpText>
        <label>Profile: System Administrator</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Holds the NGAM settings</description>
    <label>NGAM Settings</label>
</CustomObject>

objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>ChildrenCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Children Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GroupId__c</fullName>
        <externalId>true</externalId>
        <label>Group Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ParentTerritory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Territories</relationshipLabel>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RoleId__c</fullName>
        <externalId>true</externalId>
        <label>Role Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TerritoryName__c</fullName>
        <defaultValue>"Update Me"</defaultValue>
        <externalId>true</externalId>
        <label>MARS Territory Name</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Touch__c</fullName>
        <label>Touch</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>PrimaryTerritory__c</fullName>
        <label>Primary Territory</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RoleProxy__c</fullName>
        <label>RoleProxy</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Touch__c</fullName>
        <description>This field does not carry any real data.  It is used so that it will kick off workflow, process builder, triggers, etc. when changed.</description>
        <inlineHelpText>This field does not carry any real data.  It is used so that it will kick off workflow, process builder, triggers, etc. when changed.</inlineHelpText>
        <label>Touch</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserID__c</fullName>
        <defaultValue>"Populate This Field"</defaultValue>
        <externalId>true</externalId>
        <label>UserID</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/UserTerritory__c.object
<CustomObject>
    <fields>
        <fullName>ActivityTerritory__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activity Territory</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PrimaryTerritory__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Territory</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RoleId__c</fullName>
        <formula>Territory__r.RoleId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Role Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TerritoryName__c</fullName>
        <formula>Territory__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Territory Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>User Territories</relationshipLabel>
        <relationshipName>User_Territories1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Territories1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zoning__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Zone</label>
        <referenceTo>Zone__c</referenceTo>
        <relationshipLabel>User Territories</relationshipLabel>
        <relationshipName>User_Territories</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>User Territory</label>
    <nameField>
        <displayFormat>UT-{00000000}</displayFormat>
        <label>User Territory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Zone__c.object
<CustomObject>
    <fields>
        <fullName>Zone__c</fullName>
        <externalId>true</externalId>
        <label>Zone</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TerritoryTriggerHandler_Test.cls
@isTest
private class TerritoryTriggerHandler_Test {
    static testMethod void ValidateAll() {
        
        //Profile p = [select id from profile where name='System Administrator']; 
        DataFactory.CreateNGAMCustomSettings(); 
        NGAMSettings__c ngamSettings = [select id,ProfileSystemAdministrator__c,ProfileSales__c from NGAMSettings__c limit 1]; 
        string p = Util.getCustomSettingProfileId(ngamSettings.ProfileSystemAdministrator__c);
        string pSales = Util.getCustomSettingProfileId(ngamSettings.ProfileSales__c);
        
        User u = new User(alias = 'standt', email='SFDCadmin@ngam.natixis.com', 
                          emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
                          localesidkey='en_US', profileid = p, 
                          timezonesidkey='America/Los_Angeles', username='SFDCadmin@ngam.natixis.com',UserID__c='SFDCadmin');
        
        System.runAs(u) 
        {
            
            User u0 = new User(alias = 's0', email='Sales0@ngam.natixis.com', 
                               emailencodingkey='UTF-8', lastname='Testing0', languagelocalekey='en_US', 
                               localesidkey='en_US', profileid = pSales, 
                               timezonesidkey='America/Los_Angeles', username='Sales0@ngam.natixis.com',UserID__c='Sales0', RoleProxy__c=null,UserRoleid=null);   
            insert u0;


            //Territory__c myTerr = [Select Id, Name, RoleId__c, Code__c FROM Territory__c where ChildrenCount__c=0 LIMIT 1];
            
            //Creating the Territory
            Territory__c Terr = new Territory__c(Name='Test',TerritoryName__c='Test'); 
            insert Terr; 
            
            // Creating the Corresponding Role
            UserRole Ur = new UserRole();
            Ur.Name = Terr.Name;
            Ur.DeveloperName = Terr.Id;
            Ur.CaseAccessForAccountOwner = 'Read';
            Ur.OpportunityAccessForAccountOwner = 'Read';
            Ur.ContactAccessForAccountOwner = 'Read';
            insert Ur;   
            
            // Creating the Corresponding Group
            Group Gr = new Group();
            Gr.name = Terr.Name;
            Gr.DeveloperName = Terr.Id;
            Gr.Type = 'Regular';
            insert Gr;     
            
            Terr.RoleID__c = ur.id;
            Terr.GroupID__c = gr.id;    
            update Terr;     
            
            // Child Territory
            Territory__c TerrChild = new Territory__c(Name='TestCHild',TerritoryName__c='TestCHild', ParentTerritory__c=Terr.id); 
            insert TerrChild; 
            //TerrChild.
            
            // Creating the Corresponding Role
            UserRole UrChild = new UserRole();
            UrChild.Name = TerrChild.Name;
            UrChild.DeveloperName = TerrChild.Id;
            UrChild.CaseAccessForAccountOwner = 'Read';
            UrChild.OpportunityAccessForAccountOwner = 'Read';
            UrChild.ContactAccessForAccountOwner = 'Read';
            insert UrChild;   
            
            // Creating the Corresponding Group
            Group GrChild = new Group();
            GrChild.name = TerrChild.Name;
            GrChild.DeveloperName = TerrChild.Id;
            GrChild.Type = 'Regular';
            insert GrChild;     

            TerrChild.RoleID__c = UrChild.id;
            TerrChild.GroupID__c = GrChild.id;    
            update Terr; 

            List<zone__c> AllZones = DataFactory.createAllZones();
            
            
            //system.debug('0 position allzone :' + AllZones.get(0).id);
            Test.startTest();       
            List<UserTerritory__c> newUserTerr = new List<UserTerritory__c>();    
            //test.startTest();
            UserTerritory__c ut0 = new  UserTerritory__c(user__c=u0.id, territory__c=Terr.Id, PrimaryTerritory__c=true, ActivityTerritory__c=true, Zoning__c=AllZones.get(0).id);  
            newUserTerr.add(ut0);  
			insert newUserTerr;

            TerrChild.RoleID__c = Urchild.id;
            TerrChild.GroupID__c = Grchild.id;  
            update TerrChild;    

            Terr.Name = 'TestChildRename';
            Terr.Touch__c = 'TRUE';
            update Terr;

            
            //TerrChild.RoleID__c = '';
            //TerrChild.GroupID__c = '';
            //update TerrChild;   
            
            //TerrChild.RoleID__c = Urchild.id;
            //TerrChild.GroupID__c = Grchild.id;   
            //update TerrChild;    
            
            /*delete GrChild;
            delete UrChild;  
            delete TerrChild;  
            
            delete Gr;
            delete Ur;  
            delete Terr; */   
            
            
        }
        
    }
    
}