objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.ProductVisible__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RepContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For the PRCG Process to be populated with Rep/Contact associated to the request.</description>
        <label>Contact/Rep</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Do Not Show)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/LEXOpportunityBatchTest.cls
@isTest(SeeAllData=TRUE)
private class LEXOpportunityBatchTest {
    static testMethod void ValidateAll() {
        
        Test.startTest();
        String myQuery = 'SELECT Id, Product__c, Amount, RepContact__c, HasOpportunityLineItem, Pricebook2Id, RecordType.Name FROM Opportunity ORDER BY CreatedDate DESC LIMIT 200';      
		LEXOpportunityBatch LOB = new LEXOpportunityBatch();
        LOB.query = myQuery;        
        Id LOBId = database.executeBatch(LOB);     
        Test.stopTest();
        
    }
    
}