objects/PRCGResearchNote__c.object
<CustomObject>
    <fields>
        <fullName>RelatedSymbols__c</fullName>
        <description>Related Symbols of the Security Research</description>
        <inlineHelpText>Enter any related symbols, separated by semi-colons</inlineHelpText>
        <label>Related Symbols</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Security__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Security</label>
        <referenceTo>Security__c</referenceTo>
        <relationshipLabel>PRCG Research Notes</relationshipLabel>
        <relationshipName>PRCGResearchNotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ticker__c</fullName>
        <description>The Security Ticker Symbol (identifier)</description>
        <formula>Security__r.Ticker__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Ticker Symbol from the Security object</inlineHelpText>
        <label>Ticker</label>
        <type>Text</type>
    </fields>
    <description>Holds research related to a Security; this data is authored by PRCG.</description>
    <label>PRCG Research Note</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PRCG Research Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Security__c.object
<CustomObject>
    <fields>
        <fullName>MorningstarCode__c</fullName>
        <externalId>true</externalId>
        <label>Morningstar Code</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Ticker__c</fullName>
        <description>Artemus.security.ticker
varchar(255)</description>
        <label>Ticker</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Security</label>
    <nameField>
        <label>Security Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Securities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PRCGResearchNoteTriggerHandlerTest.cls
@isTest
public class PRCGResearchNoteTriggerHandlerTest {
    
    @testSetup 
    static void SetupTest() {
        
        List<Security__c> securities = new List<Security__c>();
        
        securities.add(new Security__c(Name='Test Security 1', MorningstarCode__c = '1', Ticker__c = 'TEST-REAL1'));
        securities.add(new Security__c(Name='Test Security 2', MorningstarCode__c = '2', Ticker__c = 'TEST-REAL2'));
        securities.add(new Security__c(Name='Test Security 3', MorningstarCode__c = '3', Ticker__c = 'TEST-REAL3'));
        securities.add(new Security__c(Name='Test Security 4', MorningstarCode__c = '4', Ticker__c = 'TEST-REAL4'));
        
        insert securities;
        
    }
    
    @isTest
    static void myTest() {
        
        Id analystNoteRecordTypeId = Schema.SObjectType.PRCGResearchNote__c.getRecordTypeInfosByName().get('PRC Analyst Note').getRecordTypeId();
        
        List<Security__c> testSecurities = [SELECT Id, Ticker__c FROM Security__c];
        
        List<PRCGResearchNote__c> validationNotes1 = new List<PRCGResearchNote__c>();
        
        validationNotes1.add(new PRCGResearchNote__c(Name='Test Note 1 Related Symbol', Security__c = testSecurities[0].Id, RecordTypeId = analystNoteRecordTypeId, 
                                                        RelatedSymbols__c = testSecurities[1].Ticker__c));
        
        validationNotes1.add(new PRCGResearchNote__c(Name='Test Note 2 Related Symbols', Security__c = testSecurities[0].Id, RecordTypeId = analystNoteRecordTypeId, 
                                                        RelatedSymbols__c = testSecurities[1].Ticker__c + ';' +  testSecurities[2].Ticker__c));
        
        validationNotes1.add(new PRCGResearchNote__c(Name='Test Note 3 Related Symbols', Security__c = testSecurities[0].Id, RecordTypeId = analystNoteRecordTypeId, 
                                                        RelatedSymbols__c = testSecurities[1].Ticker__c + ';' +  testSecurities[2].Ticker__c + ';' +  testSecurities[3].Ticker__c));
        
        PRCGResearchNote__c validationNote2 = new PRCGResearchNote__c(Name='Test Note 1 Fake Related Symbol', Security__c = testSecurities[0].Id, RecordTypeId = analystNoteRecordTypeId, 
                                                                          RelatedSymbols__c = 'FAKER');
        
        PRCGResearchNote__c validationNote3 = new PRCGResearchNote__c(Name='Test Note 2 Real, 1 Fake Related Symbol', Security__c = testSecurities[0].Id, RecordTypeId = analystNoteRecordTypeId, 
                                                                          RelatedSymbols__c = testSecurities[1].Ticker__c + ';' + 'FAKER' + ';' +  testSecurities[2].Ticker__c);    
        
        system.debug('validationNotes1: ' + validationNotes1);
        
        Test.startTest();
        insert validationNotes1;
        
        try
        {
            insert validationNote2;
        }
        catch(Exception e)
        {
            Boolean expectedExceptionThrown =  e.getMessage().contains('does not exist in the Securities object') ? true : false;
            System.AssertEquals(expectedExceptionThrown, true);
        } 

        try
        {
            insert validationNote3;
        }
        catch(Exception e)
        {
            Boolean expectedExceptionThrown =  e.getMessage().contains('does not exist in the Securities object') ? true : false;
            System.AssertEquals(expectedExceptionThrown, true);
        } 
        
        validationNotes1[0].RelatedSymbols__c = 'FAKER';

        try
        {
            update validationNotes1[0];
        }
        catch(Exception e)
        {
            Boolean expectedExceptionThrown =  e.getMessage().contains('does not exist in the Securities object') ? true : false;
            System.AssertEquals(expectedExceptionThrown, true);
        } 
        
        Test.stopTest();

    }    
    
}