objects/PRCGResearchNote__c.object
<CustomObject>
    <fields>
        <fullName>RelatedSymbols__c</fullName>
        <description>Related Symbols of the Security Research</description>
        <inlineHelpText>Enter any related symbols, separated by semi-colons</inlineHelpText>
        <label>Related Symbols</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Security__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Security</label>
        <referenceTo>Security__c</referenceTo>
        <relationshipLabel>PRCG Research Notes</relationshipLabel>
        <relationshipName>PRCGResearchNotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ticker__c</fullName>
        <description>The Security Ticker Symbol (identifier)</description>
        <formula>Security__r.Ticker__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Ticker Symbol from the Security object</inlineHelpText>
        <label>Ticker</label>
        <type>Text</type>
    </fields>
    <description>Holds research related to a Security; this data is authored by PRCG.</description>
    <label>PRCG Research Note</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PRCG Research Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Security__c.object
<CustomObject>
    <fields>
        <fullName>Ticker__c</fullName>
        <description>Artemus.security.ticker
varchar(255)</description>
        <label>Ticker</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Security</label>
    <nameField>
        <label>Security Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Securities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PRCGResearchNoteTriggerHandler.cls
public class PRCGResearchNoteTriggerHandler {
    
    public static void beforeInsert(List<PRCGResearchNote__c> myNewNotes) {
        
        verifyRelatedSymbols(myNewNotes);
        
    }
    
    public static void beforeUpdate(List<PRCGResearchNote__c> myNewNotes, Map<Id,PRCGResearchNote__c> myNewNotesMap, List<PRCGResearchNote__c> myOldNotes, Map<Id,PRCGResearchNote__c> myOldNotesMap) {
        
        List<PRCGResearchNote__c> toVerify = new List<PRCGResearchNote__c>();
        
        for (PRCGResearchNote__c r : myNewNotesMap.values()){
            
            if (r.RelatedSymbols__c != myOldNotesMap.get(r.Id).RelatedSymbols__c) {
                toVerify.add(r);
            }   
        }
        
        verifyRelatedSymbols(toVerify);
        
    }
    
    public static void verifyRelatedSymbols(List<PRCGResearchNote__c> myNotes) {
        
        Set<String> symbolSet = new Set<String>();
        Set<String> checkSymbolSet = new Set<String>();
        
        for (PRCGResearchNote__c n : myNotes) {
            if (!String.isBlank(n.RelatedSymbols__c)) {
                List<String> relatedSymbolList = new List<String>();
                relatedSymbolList = n.RelatedSymbols__c.split(';',0);
                for (String s : relatedSymbolList) {
                    symbolSet.add(s);
                }
            }
        }
        
        List<Security__c> securityList = [SELECT Ticker__c 
                                          FROM Security__c
                                          WHERE Ticker__c in :symbolSet];
        
        for (Security__c t : securityList) {
            checkSymbolSet.add(t.Ticker__c);
        }
        
        for (PRCGResearchNote__c n : myNotes) {
            if (!String.isBlank(n.RelatedSymbols__c)) {
                List<String> relatedSymbolList = n.RelatedSymbols__c.split(';',0);
                for (String s : relatedSymbolList) {
                    if (!checkSymbolSet.contains(s)){
                        n.addError('Ticker ' + s + ' does not exist in the Securities object.  Please add a Security with this Ticker or remove it from the Related Symbols field.');
                    }
                }
            }
            
        } 
        
    }    
    
}