objects/Product2.object
<CustomObject>
    <fields>
        <fullName>LegalName__c</fullName>
        <label>Legal Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProductCharacteristic__c.object
<CustomObject>
    <fields>
        <fullName>Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used in PB to initiate time-based workflow which sets Published__c to TRUE 0 Days after PublishDate__c</description>
        <label>Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AsOfDate__c</fullName>
        <description>The as of date of the Product Characteristic; set via integrations during creation</description>
        <label>As Of Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CouponRate__c</fullName>
        <description>Set via integrations during create if applicable</description>
        <label>Coupon Rate</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IndexCharacteristicsDecimal__c</fullName>
        <description>Holds the decimal (percent, integer, decimal) for the index from the characteristics file if the related value if a number; otherwise this is null.  Loaded from integration.</description>
        <label>Index Characteristics Decimal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IndexCharacteristicsText__c</fullName>
        <description>Holds the text from the index characteristics file if the related value if a text; otherwise this is null.  Loaded from integration.</description>
        <label>Index Characteristics Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level1__c</fullName>
        <description>Direct load from integration source</description>
        <label>Level 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level2__c</fullName>
        <description>Direct load from integration source</description>
        <label>Level 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level3__c</fullName>
        <description>Direct load from integration source</description>
        <label>Level 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MaturityDate__c</fullName>
        <description>Set via integrations during create if applicable</description>
        <label>Maturity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PercentContributionToVolatility__c</fullName>
        <description>Direct load from integration source</description>
        <label>Percent Contribution To Volatility</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PercentExposure__c</fullName>
        <description>Direct load from integration source</description>
        <label>Percent Exposure</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PercentOfIndex__c</fullName>
        <description>Direct load from integration source</description>
        <label>Percent Of Index</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PercentOfPortfolio__c</fullName>
        <description>Direct load from integration</description>
        <label>Percent Of Portfolio</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProductCharacteristicsDecimal__c</fullName>
        <description>Holds the decimal (percent, integer, decimal) for the product from the characteristics file if the related value if a number; otherwise this is null.  Loaded from integration.</description>
        <label>Product Characteristics Decimal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProductCharacteristicsText__c</fullName>
        <description>Holds the text from the product characteristics file if the related value if a text; otherwise this is null.  Loaded from integration.</description>
        <label>Product Characteristics Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Set via integrations during create.  Represents the Product to which this Product Characteristic belongs.</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Characteristics</relationshipLabel>
        <relationshipName>ProductCharacteristics</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PublishDate__c</fullName>
        <description>Set by Apex, used in PB to set Published__c</description>
        <label>Publish Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <description>Used for Top Ten Holdings; highest percentage of holdings for a Product and As Of Date is Rank 1, for example.</description>
        <label>Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SecurityDescription__c</fullName>
        <description>Set via integrations during create if applicable</description>
        <label>Security Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SecurityId__c</fullName>
        <description>Set via integrations during create if applicable</description>
        <label>Security Id</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SecurityName__c</fullName>
        <description>Set via integrations during create if applicable</description>
        <label>Security Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SortOrder__c</fullName>
        <description>Used to sort rows with the same Product, Type, and As Of Date.  Set via integrations during create if applicable or by custom setting.</description>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Set by integration on create</description>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FundAdmin Characteristics File</fullName>
                </value>
                <value>
                    <fullName>FundAdmin Expenses File</fullName>
                </value>
                <value>
                    <fullName>IPM ASG Characteristics File</fullName>
                </value>
                <value>
                    <fullName>IPM LSMAI Characteristics File</fullName>
                </value>
                <value>
                    <fullName>IPM LSSA Characteristics File</fullName>
                </value>
                <value>
                    <fullName>IPM LSSFR Characteristics File</fullName>
                </value>
                <value>
                    <fullName>IPM McDonnell Characteristics File</fullName>
                </value>
                <value>
                    <fullName>IPM Mirova Characteristics File</fullName>
                </value>
                <value>
                    <fullName>IPM MPT Port Stats File</fullName>
                </value>
                <value>
                    <fullName>IPM NSFF Characteristics File</fullName>
                </value>
                <value>
                    <fullName>Loomis Characteristics File</fullName>
                </value>
                <value>
                    <fullName>State Street Top 10 Holdings File</fullName>
                </value>
                <value>
                    <fullName>FactSet Equity Characteristics File</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Set via integrations during create.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asset Allocation</fullName>
                </value>
                <value>
                    <fullName>Asset Classes and Segments</fullName>
                </value>
                <value>
                    <fullName>Characteristics</fullName>
                </value>
                <value>
                    <fullName>Country</fullName>
                </value>
                <value>
                    <fullName>Coupon</fullName>
                </value>
                <value>
                    <fullName>Coupon detail</fullName>
                </value>
                <value>
                    <fullName>Credit quality</fullName>
                </value>
                <value>
                    <fullName>Currency</fullName>
                </value>
                <value>
                    <fullName>Duration</fullName>
                </value>
                <value>
                    <fullName>Duration detail</fullName>
                </value>
                <value>
                    <fullName>Environmental projects breakdown</fullName>
                </value>
                <value>
                    <fullName>ESG Opinion</fullName>
                </value>
                <value>
                    <fullName>Expenses</fullName>
                </value>
                <value>
                    <fullName>Exposure summary</fullName>
                </value>
                <value>
                    <fullName>Global Sector</fullName>
                </value>
                <value>
                    <fullName>Holdings</fullName>
                </value>
                <value>
                    <fullName>Industry</fullName>
                </value>
                <value>
                    <fullName>Long Positions</fullName>
                </value>
                <value>
                    <fullName>Market capitalization</fullName>
                </value>
                <value>
                    <fullName>Maturity</fullName>
                </value>
                <value>
                    <fullName>Maturity detail</fullName>
                </value>
                <value>
                    <fullName>Number of holdings</fullName>
                </value>
                <value>
                    <fullName>Portfolio composition</fullName>
                </value>
                <value>
                    <fullName>Portfolio exposures</fullName>
                </value>
                <value>
                    <fullName>Portfolio Factor Exposures Summary</fullName>
                </value>
                <value>
                    <fullName>Property Type</fullName>
                </value>
                <value>
                    <fullName>Region</fullName>
                </value>
                <value>
                    <fullName>Sector</fullName>
                </value>
                <value>
                    <fullName>Sector-LS</fullName>
                </value>
                <value>
                    <fullName>Short Positions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Holds characteristics about products for the CDR</description>
    <label>Product Characteristic</label>
    <nameField>
        <displayFormat>PC-{0000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Characteristics</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ProductCharApprovalController.cls
public with sharing class ProductCharApprovalController {
    
    public List<SelectOption> typeSelections {get;set;}
    public List<SelectOption> productSelections {get;set;}
    public List<SelectOption> sourceSelections {get;set;}
    public String choiceProduct {get;set;}
    public String choiceType {get;set;}
    public String choiceSource {get;set;}
    public List<wrapProductCharacteristic> wrapProdCharList {get; set;}
    public Boolean anyToApprove {get;set;}
    
    public ProductCharApprovalController(){
        
        this.choiceProduct = 'All';        
        this.choiceType = 'All';
        this.choiceSource = 'All';
        String query = buildQuery();
        this.productSelections = getProductSelections(query);
        this.typeSelections = getTypeSelections(query);
        this.sourceSelections = getSourceSelections(query);
        
    }
    
    
    public List<wrapProductCharacteristic> getProductCharacteristics(String q) {
        
        anyToApprove = FALSE;
        
        List<wrapProductCharacteristic> pcList = new List<wrapProductCharacteristic>();
        
        for (ProductCharacteristic__c pc : Database.query(q)) {
            pcList.add(new wrapProductCharacteristic(pc));    
        }
        
        if (!pcList.isEmpty()) anyToApprove = TRUE;
        
        return pcList;
        
    }
    
    public class wrapProductCharacteristic {
        
        public ProductCharacteristic__c pc {get; set;}
        public Boolean selected {get; set;}
        
        public wrapProductCharacteristic(ProductCharacteristic__c pci) {
            pc = pci;
            selected = false;
        }
        
    }
    
    public PageReference approveSelected() {
        
        List<ProductCharacteristic__c> prodCharToApprove = new List<ProductCharacteristic__c>();
        String errorMessage;
        
        for (wrapProductCharacteristic appr : wrapProdCharList) {
            
            if (appr.selected) {
                appr.pc.Approved__c = TRUE;
                prodCharToApprove.add(appr.pc);
            }
        }
        
        update prodCharToApprove;

        choiceProduct = 'All';        
        choiceType = 'All';
        choiceSource = 'All';

        String query = buildQuery();
        
        sourceSelections = getSourceSelections(query);
        productSelections = getProductSelections(query);
        typeSelections = getTypeSelections(query);
        anyToApprove = FALSE;
        
        return null;                            
        
    }
        
    public List<SelectOption> getProductSelections(String q) {
        
        List<SelectOption> selOpts = new List<SelectOption>();
        Map<Id,String> prodSelMap = new Map<Id,String>();
        selOpts.add(new SelectOption('All','All'));
                
        for (ProductCharacteristic__c pp1 : Database.query(q)) {
            if (!String.isBlank(pp1.Product__r.LegalName__c)) {
                prodSelMap.put(pp1.Product__c,pp1.Product__r.LegalName__c);
            } else {
                prodSelMap.put(pp1.Product__c,pp1.Product__r.Name);
            }
        }
        
        for (Id pId : prodSelMap.keySet()) {
            selOpts.add(new SelectOption(pId, prodSelMap.get(pId)));
        }
        
        return selOpts;
    }       
    
    public List<SelectOption> getSourceSelections(String q) {
        
        List<SelectOption> selOpts = new List<SelectOption>();
        Set<String> inSource = new Set<String>();
//        Map<Id,String> sourceSelMap = new Map<Id,String>();
        selOpts.add(new SelectOption('All','All'));        
        Schema.DescribeFieldResult fieldResult = ProductCharacteristic__c.Source__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        
        for (ProductCharacteristic__c i : Database.query(q)) {
            inSource.add(i.Source__c);
        }
        
        for(Schema.PicklistEntry p : ple)
            if (inSource.contains(p.getValue())) selOpts.add(new SelectOption(p.getValue(), p.getValue()));        
        return selOpts;
        
    }           
    
    public List<SelectOption> getTypeSelections(String q) {
        List<SelectOption> selOpts = new List<SelectOption>();
        Set<String> inSource = new Set<String>();
        selOpts.add(new SelectOption('All','All'));        
        Schema.DescribeFieldResult fieldResult = ProductCharacteristic__c.Type__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
                
        for (ProductCharacteristic__c i : Database.query(q)) {
            inSource.add(i.Type__c);
        }
        
        for(Schema.PicklistEntry p : ple)
            if (inSource.contains(p.getValue())) selOpts.add(new SelectOption(p.getValue(), p.getValue()));        
        return selOpts;
    }    
    
    public String buildQuery() {
        
        String q = ' SELECT Id, Name, Type__c, AsOfDate__c, Product__r.LegalName__c, Approved__c, PublishDate__c, Product__r.Name, ' +
            ' SecurityId__c, SecurityName__c, SecurityDescription__c, Rank__c, CouponRate__c, MaturityDate__c, PercentOfPortfolio__c, ' +
            ' Source__c, Level1__c, Level2__c, Level3__c, IndexCharacteristicsDecimal__c, IndexCharacteristicsText__c,  PercentContributionToVolatility__c, ' +
            ' PercentExposure__c, PercentOfIndex__c, ProductCharacteristicsDecimal__c, ProductCharacteristicsText__c ' +            
            ' FROM ProductCharacteristic__c ' +
            ' WHERE Approved__c = FALSE ';
        
        if (choiceProduct == 'All') {
            q = q + ' AND Product__c != null ';
        } else {
            q = q + ' AND Product__c =: choiceProduct ';
        }
        
        if (choiceType == 'All') {
            q = q + ' AND Type__c != null ';
        } else {
            q = q + ' AND Type__c =: choiceType ';
        }
        
        if (choiceSource == 'All') {
            q = q + ' AND Source__c != null ';
        } else {
            q = q + ' AND Source__c =: choiceSource ';
        }        
        
        q = q + ' ORDER BY Type__c, AsOfDate__c, Product__r.LegalName__c, SortOrder__c DESC LIMIT 1000';
        
        return q;
    }
    
    public String go() {
        String query = buildQuery();
        wrapProdCharList = getProductCharacteristics(query);
        
        if (wrapProdCharList.size() == 1000)
        {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'First 1,000 Rows Retrieved'));
            return null;
        } 
        return null;
    }

    public String selections() {
        
        String query = buildQuery();
        
        sourceSelections.clear();
        productSelections.clear();
        typeSelections.clear();
        
        sourceSelections = getSourceSelections(query);
        productSelections = getProductSelections(query);
        typeSelections = getTypeSelections(query);
        anyToApprove = FALSE;

        return null;
    }


    
}