objects/ReportUtilityBar__mdt.object
<CustomObject>
    <fields>
        <fullName>IsLinkBar__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Denotes whether or not this is a custom link bar.</description>
        <inlineHelpText>Denotes whether or not this is a custom link bar.</inlineHelpText>
        <label>Is Link Bar</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Strength__c</fullName>
        <defaultValue>1</defaultValue>
        <description>The Strength of the utility bar in terms of how it is shown to users. If a User meets the criteria of two utility bar records the one with the higher strength will be shown to the user.</description>
        <inlineHelpText>If a User meets the criteria of two utility bar records the one with the higher strength will be shown to the user.</inlineHelpText>
        <label>Strength</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UserFieldName__c</fullName>
        <description>The name of the field on User to check if this report list should be shown to them. If the User has the User Field Value specified on the record in the User Field Name field they will be considered a match. If left blank this will always be considered a match.</description>
        <inlineHelpText>The name of the field on User to check if this report list should be shown to them. If the User has the User Field Value specified on the record in the User Field Name field they will be considered a match.</inlineHelpText>
        <label>User Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserFieldValue__c</fullName>
        <description>The value of the field on User to check if this report list should be shown to them. If the User has the User Field Value specified on the record in the User Field Name field they will be considered a match.</description>
        <inlineHelpText>The value of the field on User to check if this report list should be shown to them. If the User has the User Field Value specified on the record in the User Field Name field they will be considered a match.</inlineHelpText>
        <label>User Field Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <description>Record that determines the utility bar that a user sees and what is on it.</description>
    <label>Report Utility Bar</label>
    <pluralLabel>Report Utility Bars</pluralLabel>
</CustomObject>

objects/ReportUtilityBarItem__mdt.object
<CustomObject>
    <fields>
        <fullName>DisplayName__c</fullName>
        <description>The name that will be displayed in the component's list item.</description>
        <inlineHelpText>The name that will be displayed in the component's list item.</inlineHelpText>
        <label>Display Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReportUtilityBar__c</fullName>
        <description>The Report Utility bar this item should show up on.</description>
        <inlineHelpText>The Report Utility bar this item should show up on.</inlineHelpText>
        <label>Report Utility Bar</label>
        <referenceTo>ReportUtilityBar__mdt</referenceTo>
        <relationshipLabel>Report Utility Bar Items</relationshipLabel>
        <relationshipName>ReportUtilityBarItems</relationshipName>
        <required>true</required>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The Order in which these objects appear in the list. Smallest to largest.</description>
        <inlineHelpText>The Order in which these objects appear in the list. Smallest to largest.</inlineHelpText>
        <label>Sort Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <description>The URL this list item should direct the user to.</description>
        <inlineHelpText>The URL this list item should direct the user to.</inlineHelpText>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <description>An item on a report utility bar.</description>
    <label>Report Utility Bar Item</label>
    <pluralLabel>Report Utility Bar Items</pluralLabel>
</CustomObject>

classes/SL_ReportUtilityBar.cls
global class SL_ReportUtilityBar {

    @AuraEnabled global static String getReportLinks(Boolean isLinkBarView) {
        String retVal = '{}';
        List<ReportUtilityBar__mdt> lstReportUBar = new List<ReportUtilityBar__mdt>();
        Set<String> setFldNames = new Set<String>();
        User uRecord = null;

        ReportUtilityBar__mdt selReportUtilityBar = null;
        
        for(ReportUtilityBar__mdt item:[SELECT Strength__c,UserFieldName__c,UserFieldValue__c,ID,MasterLabel,DeveloperName FROM ReportUtilityBar__mdt WHERE IsLinkBar__c = :isLinkBarView order by Strength__c desc limit 1000]){
            lstReportUBar.add(item);
            if(String.isNotBlank(item.UserFieldName__c)){
                setFldNames.add(item.UserFieldName__c);
            }
        }

        if(lstReportUBar.size()==0){
			throw new ReportUtilityBarException('There is no Report UtilityBar records');
        }

        if(setFldNames.size()>0){
            List<String> lstFldNames = new List<String>();
            lstFldNames.addAll(setFldNames);
            String qSOQL = 'SELECT ' + String.join(lstFldNames,',') +' FROM user where ID=\''+UserInfo.getUserId()+'\' LIMIT 1' ;

            try{
                List<sObject> lstObject = Database.query(qSOQL);
                uRecord = (User)lstObject[0];
            }
            catch(Exception e){
                throw new ReportUtilityBarException('Incorrect User Field Name in UtilityBar record'); 
            }
        }

        if(uRecord!=null){
            for(ReportUtilityBar__mdt item:lstReportUBar){

                String sUserFldVal = null;
                String fldName = item.UserFieldName__c;

                if(String.isBlank(fldName)){
                    selReportUtilityBar = item;
                    break;
                }

                String[] fldNameParts = fldName.split('\\.',2);

                if(fldNameParts.size()==1){
                    if(uRecord.get(fldNameParts[0])!=null){
                       sUserFldVal = ''+uRecord.get(fldNameParts[0]);
                    }
                }
                else if(fldNameParts.size()==2){
                    if(uRecord.getSobject(fldNameParts[0]).get(fldNameParts[1])!=null){
                       sUserFldVal = ''+uRecord.getSobject(fldNameParts[0]).get(fldNameParts[1]);
                    }
                }

                if(sUserFldVal == item.UserFieldValue__c){
                    selReportUtilityBar = item;
                    break;
                }
            }
        }
        else{
            selReportUtilityBar = lstReportUBar[0];
        }


        if(selReportUtilityBar!=null){
            ReportUtilityBarWrapper retWrapper = new ReportUtilityBarWrapper(selReportUtilityBar);
            for(ReportUtilityBarItem__mdt item:[SELECT DisplayName__c,Sort_Order__c,URL__c,ID,MasterLabel,DeveloperName  FROM ReportUtilityBarItem__mdt where ReportUtilityBar__c =:selReportUtilityBar.ID order by Sort_Order__c ASC limit 1000]){
                retWrapper.lstUBarItems.add(item);
            }
            retVal = JSON.serialize(retWrapper);

        }
        else{
            throw new ReportUtilityBarException('System can not find associated Report Utility Bar record'); 
        }


        return retVal;
    }

    public class ReportUtilityBarWrapper {

        public ReportUtilityBar__mdt recordUBar {get; set;}
        public List<ReportUtilityBarItem__mdt> lstUBarItems {get; set;}

        public ReportUtilityBarWrapper(ReportUtilityBar__mdt recordUBar) {
            this.recordUBar = recordUBar;
            this.lstUBarItems = new List<ReportUtilityBarItem__mdt>();
        }

	}
	
    public class ReportUtilityBarException extends Exception {}

}