objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>TerritoryName__c</fullName>
        <defaultValue>"Update Me"</defaultValue>
        <externalId>true</externalId>
        <label>MARS Territory Name</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TerritoryType__c</fullName>
        <label>Territory Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Territory</fullName>
                </value>
                <value>
                    <fullName>Region</fullName>
                </value>
                <value>
                    <fullName>Department</fullName>
                </value>
                <value>
                    <fullName>Division</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/UserTerritory__c.object
<CustomObject>
    <fields>
        <fullName>PrimaryTerritory__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Territory</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TerritoryName__c</fullName>
        <formula>Territory__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Territory Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TerritoryType__c</fullName>
        <formula>TEXT(Territory__r.TerritoryType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Territory Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>User Territories</relationshipLabel>
        <relationshipName>User_Territories1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>User Territory</label>
    <nameField>
        <displayFormat>UT-{00000000}</displayFormat>
        <label>User Territory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Territories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/SL_TerritoryToggleButton.cls
global class SL_TerritoryToggleButton {

    @AuraEnabled global static List<UserTerritory__c> getUserTerritory() {
        List<UserTerritory__c> retVal = new List<UserTerritory__c>();
        for(UserTerritory__c item:[Select Id, TerritoryName__c, Territory__c, primaryterritory__c FROM UserTerritory__c where ownerid =: UserInfo.getUserId() order by primaryterritory__c desc ,TerritoryName__c limit 500]){
            retVal.add(item);
        }
        return retVal;
    }

    @AuraEnabled global static UserTerritory__c getUserPrimTerritory() {
        UserTerritory__c retVal = null;
        for(UserTerritory__c item: [select Id, TerritoryName__c, Territory__c from UserTerritory__c where PrimaryTerritory__c=true and ownerid =: UserInfo.getUserId() ORDER BY Territory__r.TerritoryType__c, Territory__r.Name]){
            retVal = item;
            system.debug('-----------------' + item.TerritoryName__c + '---' + item.Territory__c );
        }

        return retVal;
    }

    @AuraEnabled global static boolean getIsShowMe(){

        boolean isShowMe = false;
        List<UserTerritory__c> lstUserTerritory = new List<UserTerritory__c>();

        for(UserTerritory__c item:[select id from UserTerritory__c where ownerid =: UserInfo.getUserId() limit 2]){
            lstUserTerritory.add(item);
        }

        if (lstUserTerritory.size() > 1) { isShowMe = true;}

        return isShowMe;
    }

    @AuraEnabled
    public static boolean btnApply( String inPrimaryTerritory ) {

        if(inPrimaryTerritory!=null && inPrimaryTerritory!='') {

            try {
                UserTerritory__c ut = new UserTerritory__c(id=inPrimaryTerritory, PrimaryTerritory__c=true) ;
                update ut;
            }
            catch (Exception ex) {
                throw new AuraHandledException('Something went wrong: ' + ex.getMessage());   
            }
        }
        
        return true;
    }

}