objects/User.object
<CustomObject>
    <fields>
        <fullName>ActivityZoneId__c</fullName>
        <description>Used To Tag the Activities and Opportunities created by the user.</description>
        <inlineHelpText>READ ONLY FIELD : This Will be populated by the UserTerritory__c assignment when the Territory Assignment is tagged as an Activity Territory. Please never update this field directly. Instead Delete/Insert the relevant UserTerritory__c record.</inlineHelpText>
        <label>Activity Zone Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VIP__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Used to easily find the main Sales Managers</inlineHelpText>
        <label>VIP</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Zone__c.object
<CustomObject>
    <fields>
        <fullName>Zone__c</fullName>
        <externalId>true</externalId>
        <label>Zone</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UserData.cls
public with sharing class UserData {
      
    public boolean IsVip{
        get{
        system.debug('------' + UserInfo.getUserId());
            List<User> users = [select VIP__c from User where id =: UserInfo.getUserId()];
            
            //if (user.size() > 0) {
                User u = users.get(0);
                return u.VIP__c;
            //}
           // else return false;
          }
      set;
    }
    
     public boolean IsMD {
         get {
             Boolean md= false;
             system.debug('------' + UserInfo.getUserId());
             List<User> users = [select ActivityZoneId__c from User where id =:UserInfo.getUserId()];    
         
             if(users != null && users.size() > 0) {
                 List<Zone__c> zones = [select id,Name,Zone__c from Zone__c where id =: users[0].ActivityZoneId__c];    
                 if(zones != null && zones.size() > 0) {            
                     if (zones[0].Name == 'MD')
                     md= true;
                 }
             }
             return md;         
          }
          set;      
    }
}